### ISSUE TITLE
关于自动加载更多  automaticallyRefresh 状态位的问题

### ISSUE THREAD

**Issue by nanjibingshuang** [CoderMJLee/MJRefresh#100]
我看了一下您的实例和代码, 我发现所有的加载更多都是可以上拉自动加载更多的; 看了一下源代码在判断加载更多的时候,没有读取automaticallyRefresh变量的值,从而导致禁用自动加载更多无效!  不知道该问题是否已经修正

**Comment by CoderMJLee** [comment]
1.在MJRefreshFooter.m的第142行是有做判断的哈
2.自动加载的意思是：当scrollView滚到底部时，自动进入刷新状态并且回调（比如发送网络请求加载更多的数据）
3.禁止自动加载的意思是：当scrollView滚到底部时，不会自动进入刷新状态。那怎样才会进入刷新状态：当用户用力向上拽或者点击footer的时候才会进入刷新状态并且回调（比如发送网络请求加载更多的数据）O(∩_∩)O~~不知道你是不是这么想的？

**Comment by nanjibingshuang** [comment]
好吧,和我想的确实不一样. 我以为 自动加载包括向上拽的操作,因为我把滚动到底部(有些情况是漏出一点就自动加载)和向上拽看做一个事件处理了.所以就会有我上面的问题了.3Q~
