### ISSUE TITLE
在iOS11上，当tableView时一个scrollView的subView时，在下拉刷新后，在没有调用endRefreshing的情况下动画消失，自动回到返回原来位置。

### ISSUE THREAD

**Issue by whihail** [CoderMJLee/MJRefresh#1001]
在iOS11上，当tableView时一个scrollView的subView时，在下拉刷新后，在没有调用endRefreshing的情况下动画消失，自动回到返回原来位置。
调试发现，当在这种情况下时，
else if (state == MJRefreshStateRefreshing) {
         dispatch_async(dispatch_get_main_queue(), ^{
            [UIView animateWithDuration:MJRefreshFastAnimationDuration animations:^{
                CGFloat top = self.scrollViewOriginalInset.top + self.mj_h;
                // 增加滚动区域top
                self.scrollView.mj_insetT = top;
                // 设置滚动位置
                [self.scrollView setContentOffset:CGPointMake(0, -top) animated:NO];
            } completion:^(BOOL finished) {
                [self executeRefreshingCallback];
            }];
         });
    }
代码中self.scrollViewOriginalInset.top的值为-60，正常的值应该是0，在iOS11中，这个值其实就是scrollView.adjustedContentInset,请问有什么办法可以解决吗？

**Comment by CoderMJLee** [comment]
是最新版本么？3.1.14.1

**Comment by whihail** [comment]
嗯嗯、就是最新版本3.1.14.1。

发自我的 iPhone

**Comment by whihail** [comment]
@CoderMJLee 你好，我用的就是最新的版本 3.1.14.1 。这个问题只有在用Xcode9打包运行在iOS11系统上才会产生。不知道如何解决这个问题？

**Comment by xiaoer** [comment]
我也出现这种情况了？哥们。你解决了嘛？只有iOS11上出现。比较紧急！

**Comment by CoderMJLee** [comment]
@whihail 麻烦写个出现这个问题的Demo哈，方便我直接调试，谢谢
