### ISSUE TITLE
为什么会出现很多多余的线条呢

### ISSUE THREAD

**Issue by sumency** [CoderMJLee/MJRefresh#1004]
下拉跟上拉都出现了很多莫名奇妙的线条

**Comment by CoderMJLee** [comment]
有截图么

**Comment by sumency** [comment]
![img_0738](https://user-images.githubusercontent.com/19161013/32207728-d3a231dc-be38-11e7-9243-8fa3712c9b43.jpg)
![img_0739](https://user-images.githubusercontent.com/19161013/32207729-d3e4e252-be38-11e7-916e-ea523dc828de.jpg)
上拉加载更多跟下拉刷新都出现了好多莫名其妙的线条，怎么都弄不掉(ಥ _ ಥ)

**Comment by CoderMJLee** [comment]
是tableViewStyle的问题？

**Comment by sumency** [comment]
@CoderMJLee 各种style我都试了，还是不行，始终会有这个线，但是奇怪的是我之前写的程序也是用的MJRfresh，就不会出现这个问题。困扰我好久了

**Comment by CoderMJLee** [comment]
能否创建一个出现此问题的Demo看看？我直接调试
