### ISSUE TITLE
本地化问题

### ISSUE THREAD

**Issue by JCleqiang** [CoderMJLee/MJRefresh#1008]
<img width="238" alt="2017-10-27 11 26 23" src="https://user-images.githubusercontent.com/13590922/32086735-c4e1c184-ba9c-11e7-9a72-63e0fce3f21a.png">

如上图所示，3.1.14版本，有的设备有时候上拉刷新字样为英文，有时候又是中文。
哪位朋友有遇到上面的问题，谢谢!

**Comment by Real-young** [comment]
我也是碰到这个问题，无论下拉刷新还是上拉加载都是。。而且是Xcode9才有这个问题，Xcode8好像没有

**Comment by lvyibao** [comment]
请协助提供本地话配置说明文档！ @CoderMJLee

**Comment by Real-young** [comment]
**
![image](https://user-images.githubusercontent.com/18461406/32095626-6275db34-bac9-11e7-8bf0-810e73975fc0.png)
**

我发现一个问题，就是用那个Default的构建系统就没问题，用新的构建系统就有这个英文的问题，时有时无是因为缓存，你可以clean 一下再编译，我都试过了

**Comment by JCleqiang** [comment]
多谢@Real-young的解答，我试试!

**Comment by Real-young** [comment]
我也是试了好多次，一直都是用默认的我就不知道了啊，你试试Xcode8？ @JCleqiang

**Comment by CoderMJLee** [comment]
@JCleqiang 是真机调试才会出现此问题？

**Comment by JCleqiang** [comment]
@CoderMJLee 抱歉，回复晚了! 这边调试一直用的是真机，模拟器没用过。

**Comment by CoderMJLee** [comment]
@JCleqiang 是使用CocoaPods安装的，还是直接拖入MJRefresh代码到项目中？

**Comment by JCleqiang** [comment]
@CoderMJLee CocoaPods安装的
