### ISSUE TITLE
老师您好，当前页面没有刷新完毕，去下一个页面再回到当前页面，刷新头就不会隐藏掉，怎么解决？

### ISSUE THREAD

**Issue by LG0915** [CoderMJLee/MJRefresh#101]

**Comment by CoderMJLee** [comment]
是一直在转圈圈？还是说显示了一个箭头？

**Comment by LG0915** [comment]
显示一个向下的箭头，整个View会下移header的距离，如果多次进行切换，头部控件会一直往下移
![2015-04-09 2 50 07](https://cloud.githubusercontent.com/assets/10163708/7061717/e5affbfa-dec7-11e4-8453-801a6323e58e.png)

**Comment by liang-zhang** [comment]
@CoderMJLee 老师您好！  我也遇到相同的问题了，求解决办法

**Comment by CoderMJLee** [comment]
已修复。谢谢提醒

**Comment by AliceWJJ** [comment]
我也遇到这个问题了呢， 公司的旧项目，用的旧框架，替换成新的框架的话难度太大，不知道怎么解决。。。555
