### ISSUE TITLE
iOS10.3.3 mj_reloadData崩溃

### ISSUE THREAD

**Issue by 6ag** [CoderMJLee/MJRefresh#1012]
在iOS11上是正常的，iOS10.3.3直接崩溃了。我还没有调用MJRefresh就崩溃了，只是tableVeiw.reloadData()。

libc++abi.dylib: terminate_handler unexpectedly threw an exception

**Comment by 6ag** [comment]
经过反复测试，最终解决了这个问题。是因为在iOS10.3.3中tableview的几个estimated属性的问题。我注释了就不会崩溃了

**Comment by 6ag** [comment]
`if #available(iOS 11.0, *) {
            tableView.estimatedRowHeight = 0.01
            tableView.estimatedSectionHeaderHeight = 0.01
            tableView.estimatedSectionFooterHeight = 0.01
}`

这样就好了，大佬。看是啥问题呢

**Comment by CoderMJLee** [comment]
如果是最新版本呢，3.1.15版本
