### ISSUE TITLE
最后刷新时间显示错误，ios11之后好像获取到的时间相差8小时，需要设置下时区

### ISSUE THREAD

**Issue by ethanbing** [CoderMJLee/MJRefresh#1016]
最后刷新时间显示错误，ios11之后好像获取到的时间相差8小时，需要设置下时区

// 2.格式化日期
        NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
        formatter.timeZone = [NSTimeZone timeZoneWithAbbreviation:@"GMT+0800"];
我添加了下面这个代码就显示正常了，希望更新下，谢谢

**Comment by mTerminal** [comment]
改你电脑的时区。

**Comment by mengzhu716** [comment]
我用的是真机，并且项目里面info设置的还是china，以前没事，就是更新新的库之后出现的问题

**Comment by mTerminal** [comment]
这个还真不清楚了，我都是继承自定义的，没有时间显示。🌚

2017-11-01 15:38 GMT+08:00 Bill <notifications@github.com>:
