### ISSUE TITLE
MJRefreshStateHeader在iOS11不显示问题

### ISSUE THREAD

**Issue by 18304089286** [CoderMJLee/MJRefresh#1017]
__weak typeof(self)weakSelf = self;
    MJRefreshStateHeader *header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [weakSelf homePageNetwork];
    }];
    header.stateLabel.textColor = [UIColor whiteColor];
    header.lastUpdatedTimeLabel.textColor = [UIColor whiteColor];
    self.collectionView.mj_header = header;
自定义了控件的颜色，不显示header了，小码哥你看看呗

**Comment by CoderMJLee** [comment]
你设置了文字颜色是白色。如果你的背景也是白色，那么就完全看不见文字了
