### ISSUE TITLE
uitableview上拉更新时，contentOffset.y貌似不对

### ISSUE THREAD

**Issue by zhuwei** [CoderMJLee/MJRefresh#1019]
当uitableview数据数量超出屏幕时， 上拉更新后，修改数据源变成1条数据时，就出现bug了，整体在上面。。。

**Comment by zhuwei** [comment]
只有ios11 才有问题。

**Comment by BobbChen** [comment]
3.1.14确实存在这个问题

**Comment by CoderMJLee** [comment]
@zhuwei  麻烦提供一个出现此问题的Demo哈，我直接在上面调试，谢谢哈

**Comment by zhuwei** [comment]
不好意思, 解决了.
加了下面代码
`if (@available(iOS 11.0, *)) {
            _tableView.estimatedRowHeight = 0;
            _tableView.estimatedSectionFooterHeight = 0;
            _tableView.estimatedSectionHeaderHeight = 0;
            _tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }`
