### ISSUE TITLE
传统上拉刷新问题

### ISSUE THREAD

**Issue by yybutcher** [CoderMJLee/MJRefresh#102]
传统上拉刷新，automaticallyRefresh ＝ NO 
上拉过程 和 松手后的弹跳过程中会一直触发上拉方法
automaticallyRefresh ＝ YES，手动点击上拉加载或再次上拉不会出现这种情况

**Comment by CoderMJLee** [comment]
每松开一次肯定会触发一次上拉方法的哈。你的意思是一松开连续调用N次上拉方法？

**Comment by yybutcher** [comment]
松开手后，只要scroll的y变 就会调用一次上拉的方法

**Comment by CoderMJLee** [comment]
松开手后肯定要调用一次的哈。或者是我理解错你的意思了？有无核心代码？打印结果？或者示例程序？

**Comment by yybutcher** [comment]
给tableview添加上拉加载：
```
[self.tableView addLegendFooterWithRefreshingBlock:^{
        self.page++;
        [self loadData];
 }];
```
理想效果是，上拉加载开始执行上面块里的内容然后结束上拉加载这一过程数据加载到tableview中。
等下一次tableview再次被拉到底部，再进行一次上拉加载。

目前的现状是，上拉加载的过程时，tableview的底边在向下降落的过程中，会无限运行上面块里的内容，而不是值运行一次。

估计是没有正确的获取到目前是否正在加载中的状态，如果是正在加载中的状态，就不执行块里的内容。

**Comment by CoderMJLee** [comment]
有没有试过最新代码？我经常会更新检查框架的哈
