### ISSUE TITLE
endRefreshing 和 endRefreshingWithNoMoreData 之间调用时间相隔太小（< 0.4 秒）导致bug

### ISSUE THREAD

**Issue by liangdahong** [CoderMJLee/MJRefresh#1020]
MJ 老师您好！在使用时发现一个小问题，望有时间可以看看是否有错。

`endRefreshing` 和 `endRefreshingWithNoMoreData` 之间调用时间相隔太小（< 0.4 秒）导致bug

1、在调用 endRefreshing 方法时，内部会使用动画的形式隐藏 箭头（0.4 秒）
2、如果在少于 0.4 又使用 `endRefreshingWithNoMoreData`  会导致方法这些完成后才执行刚才 endRefreshing 的动画结束Block 强制又把箭头设置为显示状态。

```c
    __weak typeof(self) weakSelf = self;
    self.tableView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            __strong typeof(weakSelf) self = weakSelf;
            [self.tableView.mj_footer endRefreshing];
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                [self.tableView.mj_footer endRefreshingWithNoMoreData];
            });
            [self.tableView reloadData];
        });
    }];
```
如下图：
![4246b2b5-46a0-4d2c-97cb-8dbeccb9eb5d](https://user-images.githubusercontent.com/12118567/32357532-8cf6d6ec-c078-11e7-8584-90e21497b822.png)

**Comment by CoderMJLee** [comment]
为啥需要连续调用endRefreshing和endRefreshingWithNoMoreData？这2个方法用其中一个就行哈

**Comment by asiosldh** [comment]
@CoderMJLee MJ老师好，竟然这么快就回复了，O(∩_∩)O哈哈~。

 - 1、的确不应该连续调用这2个方法（使用其中一个即可），之所以连续调用是为了简便，O(∩_∩)O哈哈~，
 - 2、但是否有这样的问题，网络特别快（直接加载本地数据），操作又很快时，导致连续2次上拉加载的时间相隔太小（<0.4秒）也会出现这个问题哦（第一次有更多数据，第二次检测到没有更多数据）。（但几乎很少见）

**Comment by CoderMJLee** [comment]
不会有问题的，因为下一次上拉加载还要先调用beginRefreshing，最后才调用endRefreshing。所以不存在连续调用2次endRefreshing的情况哈。因为是先经过beginRefreshing，然后再endRefreshing

**Comment by asiosldh** [comment]
@CoderMJLee   赞， 我简单测试了下，

- 1、如图，将动画时间设置为 2.0 为了方便测试
![1](https://user-images.githubusercontent.com/12118567/32361840-126449ba-c09f-11e7-80a3-14ae29a66518.png)

- 2、代码如下：
![3d3b3b91-b373-4100-a49d-791d94b14802](https://user-images.githubusercontent.com/12118567/32361924-e3b80a56-c09f-11e7-8ad1-09af4e1e24ac.png)

- 3、较短的时间内上拉2次（第一次有更多数据 endRefreshing ，等二次无更多数据endRefreshingWithNoMoreData ） 会有如下的 log输出
![2](https://user-images.githubusercontent.com/12118567/32361842-1627d36e-c09f-11e7-91aa-76d41bbb6cbf.png)

- 4、效果图如下：
![ccccc](https://user-images.githubusercontent.com/12118567/32361926-e88f23d4-c09f-11e7-8dec-308cedb76c71.gif)

**Comment by CoderMJLee** [comment]
嗯嗯，明白，速度过慢是会出现此情况，3Q。我有空时稍作调整哈，把它完善一下

**Comment by asiosldh** [comment]
👌 谢谢啦，辛苦MJ老师了。

**Comment by asiosldh** [comment]
@CoderMJLee  鼓起勇气提了一个PR ，希望可以通过，其实MJRefreshNormalHeader做了处理。  https://github.com/CoderMJLee/MJRefresh/blob/master/MJRefresh/Custom/Header/MJRefreshNormalHeader.m 的102行

😂

**Comment by wolfcon** [comment]
#1258
