### ISSUE TITLE
3.1.15 设置table.mj_fooer = xx 不对

### ISSUE THREAD

**Issue by biqinglin** [CoderMJLee/MJRefresh#1021]
3.1.15 设置table.mj_fooer = xx 比如gif图或者文字，全部都偏左边，没有居中.不知道有没有和我遇到一样的问题

**Comment by CoderMJLee** [comment]
具体代码呢？

**Comment by biqinglin** [comment]
MJRefreshAutoGifFooter *footer = [MJRefreshAutoGifFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreData)];
    NSMutableArray *footerimages = [NSMutableArray arrayWithCapacity:1];
    for (int i = 0; i < 10; i ++) {
        NSString *name = [NSString stringWithFormat:@"shangla_%02d",i];
        UIImage *image = [UIImage imageNamed:name];
        [footerimages addObject:image];
    }
    footer.stateLabel.hidden = YES;
    [footer setImages:footerimages forState:MJRefreshStateIdle];
    [footer setImages:footerimages forState:MJRefreshStatePulling];
    [footer setImages:footerimages forState:MJRefreshStateRefreshing];
    self.mainListTable.mj_footer.automaticallyChangeAlpha = YES;
    self.mainListTable.mj_footer = footer;
