### ISSUE TITLE
关于下拉刷新，上拉加载更多的问题

### ISSUE THREAD

**Issue by xudehuai** [CoderMJLee/MJRefresh#1022]
当我进行上拉加载更多操作的时候，如果设置了endRefreshingWithNoMoreData，即状态改为MJRefreshStateNoMoreData后，再进行下拉刷新，就无法进行上拉加载更多操作了。我需要在下拉刷新的时候手动去改变状态为MJRefreshStateIdle吗？我怎么记得以前使用都不用的啊，还是说我一直以来都使用了错误的逻辑？

**Comment by CoderMJLee** [comment]
```objc
// 重置到普通状态
[footer resetNoMoreData];
```

**Comment by xudehuai** [comment]
需要手动重置吗

**Comment by CoderMJLee** [comment]
如果你是结束刷新，仅仅调用endRefreshing就好了，不用调用endRefreshingWithNoMoreData
