### ISSUE TITLE
ios 11 [MJChiBaoZiHeader prepare]崩溃

### ISSUE THREAD

**Issue by alenQingshan** [CoderMJLee/MJRefresh#1023]
0	libobjc.A.dylib
objc_msgSend + 28
1	CoreFoundation
-[NSTaggedPointerString UTF8String] + 284
2	CoreUI
___getDeviceTraits + 420
3	CoreUI
-[CUICatalog namedLookupWithName:scaleFactor:deviceIdiom:deviceSubtype:sizeClassHorizontal:sizeClassVertical:] + 92
4	UIKit
___98-[_UIAssetManager imageNamed:scale:idiom:subtype:cachingOptions:sizeClassPair:attachCatalogImage:]_block_invoke + 424
5	UIKit
-[_UIAssetManager imageNamed:scale:idiom:subtype:cachingOptions:sizeClassPair:attachCatalogImage:] + 212
6	UIKit
-[UIImageAsset imageWithTraitCollection:] + 404
7	UIKit
-[_UIAssetManager imageNamed:withTrait:] + 276
8	UIKit
+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:] + 220
9	UIKit
+[UIImage imageNamed:] + 124
10	zhsyd_ios
-[MJChiBaoZiHeader prepare] (MJChiBaoZiHeader.m:21)
11	zhsyd_ios
-[MJRefreshComponent initWithFrame:] (MJRefreshComponent.m:26)
12	zhsyd_ios
+[MJRefreshHeader headerWithRefreshingTarget:refreshingAction:] (MJRefreshHeader.m:26)
13	zhsyd_ios
-[BonusActivityController example04] (BonusActivityController.m:423)
14	zhsyd_ios
-[BonusActivityController viewDidLoad] (BonusActivityController.m:89)
15	UIKit
-[UIViewController loadViewIfRequired] + 996
16	UIKit
-[UIViewController __viewWillAppear:] + 132
17	UIKit
-[UINavigationController _startCustomTransition:] + 1052
18	UIKit
-[UINavigationController _startDeferredTransitionIfNeeded:] + 688
19	UIKit
-[UINavigationController __viewWillLayoutSubviews] + 60

**Comment by CoderMJLee** [comment]
错误的标题描述是？

**Comment by alenQingshan** [comment]
控制台信息
12 2017-11-08 10:57:42.824 zhsyd_ios[2296]: \| JPUSH \| I - [JPUSHDeviceTokenReport] try to upload device token:e52be94bcdeddddfd0eff2c0b81cc3416ed5004fc03c14f7a918ab5db3e27a98
13 2017-11-08 10:57:43.222 zhsyd_ios[2296]: \| JPUSH \| I - [JPUSHDeviceTokenReport] upload device token success
14 2017-11-08 10:57:51.852 zhsyd_ios[2296]: [Bugly] Fatal signal(11) raised.
15 2017-11-08 10:57:51.875 zhsyd_ios[2296]: [Bugly] Trapped fatal signal 'SIGSEGV(11)'

**Comment by mg459046365** [comment]
最近全是这种错，自己工程里面，也是这种错

**Comment by mg459046365** [comment]
@CoderMJLee MJ老师要是发现了解决方法，顺便告知一下，谢谢啦。一直都在纠结，就是不知道什么原因
