### ISSUE TITLE
footer 下拉加载设置 nomoredata 无效的问题

### ISSUE THREAD

**Issue by chenbreeze** [CoderMJLee/MJRefresh#1025]
[footer endRefreshing];
footer.state = noMoreData;

类似这样的代码无效， 原因是

- (void)endRefreshing
{
    dispatch_async(dispatch_get_main_queue(), ^{
        self.state = MJRefreshStateIdle;
    });
}
这个方法变成异步执行  

望修复

**Comment by asiosldh** [comment]
如果无更多数据请使用 endRefreshingWithNoMoreData 结束刷新即可。

@chenbreeze

**Comment by CoderMJLee** [comment]
@chenbreeze 是的，可以按照 @asiosldh 的说法做

**Comment by YYDD** [comment]
mark

**Comment by hanq** [comment]
提供一个线索：endRefreshingWithNoMoreData执行之后不能再执行endRefreshing,否则会持续加载下一页，如果有endRefreshingWithNoMoreData不好用的可以排除一下这个可能。

**Comment by ZZyDong** [comment]
> 提供一个线索：endRefreshingWithNoMoreData执行之后不能再执行endRefreshing,否则会持续加载下一页，如果有endRefreshingWithNoMoreData不好用的可以排除一下这个可能。
@hanq 线索帮助我找到了刚遇到的问题的原因.因为二次封装的,在某些时候这两个会同时触发,endRefreshing会重置endRefreshingWithNoMoreData...如果调换一下顺序,显示也会出现问题(文字正常,图标没有清除)..

**Comment by asiosldh** [comment]
@ZZyDong https://github.com/CoderMJLee/MJRefresh/issues/1020 参考

**Comment by wolfcon** [comment]
不要直接修改 state. 

使用如下代码
```swift
tableView.mj_footer.endRefreshingWithNoMoreData()
```
#1258 #1020
