### ISSUE TITLE
iOS11中设置estimatedRowHeight，重复加载上拉数据的问题

### ISSUE THREAD

**Issue by shen0607** [CoderMJLee/MJRefresh#1026]
我在iOS11中设置estimatedRowHeight，并设置triggerAutomaticallyRefreshPercent = -80，（这边这边我想滑动到某个位置的时候，自动加载下一页数据）。当我快速滑动的时候，会一直重复调用加载更多的方法。

**Comment by CoderMJLee** [comment]
试过最新版了么？3.1.15

**Comment by liuaaaddxiaoer** [comment]
请看#1028

**Comment by wolfcon** [comment]
Duplicate of #1009

**Comment by wolfcon** [comment]
这里的 `Percent` 默认是 1, 你如果想早点触发, 填 -1 即可.
