### ISSUE TITLE
ios11下 进行上拉加载更多，数据是直接显示下一屏幕的，不连贯

### ISSUE THREAD

**Issue by yezhaobin** [CoderMJLee/MJRefresh#1028]
ios11下 进行上拉加载更多，数据加载后是直接显示到下一屏，给人画面滑动不连贯的感觉。 而在ios10.3.3 下上拉加载更多，画面的滑动是连贯的。

**Comment by yezhaobin** [comment]
用的版本是MJRefresh (3.1.15)

**Comment by lerosua** [comment]
应该是ios11的问题，试试
self.tableView.estimatedRowHeight = 0;
self.tableView.estimatedSectionHeaderHeight = 0;
self.tableView.estimatedSectionFooterHeight = 0;

**Comment by CoderMJLee** [comment]
@yezhaobin 可以提供一下出现此问题的Demo么，我直接调试

**Comment by liuaaaddxiaoer** [comment]
也遇到了类似的bug  http://blog.csdn.net/luolianxi/article/details/78090827

**Comment by liuaaaddxiaoer** [comment]
tableview有自己定义的sectionHeadview 解决方法 使用 lerosua的方法就可以解决

**Comment by OHeroJ** [comment]
tableview 存在，collectionView 没有

**Comment by awesomedu** [comment]
加了lerosua 的三行，一样加载更多不连贯

**Comment by pusswzy** [comment]
- (CGFloat)tableView:(UITableView *)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath *)indexPath {
    CGFloat cellHeight = [[self.cellHeightDictionary objectForKey:indexPath] floatValue];
    if (cellHeight) {
        return cellHeight;
    }
    return UITableViewAutomaticDimension;
}

- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath
{
    [self.cellHeightDictionary setObject:@(cell.frame.size.height) forKey:indexPath];
}
把cell高度缓存下来 reloadData后会对estimatedHeight重新计算的

**Comment by wolfcon** [comment]
Duplicate of #1009
