### ISSUE TITLE
关于扩展左拉 右拉刷新问题

### ISSUE THREAD

**Issue by wy19901227** [CoderMJLee/MJRefresh#103]
是这样的，实际项目中会用左右滑动的情况，一般 会出现在ipad横屏的时候，我实现左右滑动是将UITableview的tableView.transform=CGAffineTransformMakeRotation(M_PI/-2);这样就可以左右滑动了，然后再按照上下的方式添加refreshview，也设置了tableview.pageenable属性，结果有点问题，希望可以按照这种思路扩展下。谢了mj神

**Comment by CoderMJLee** [comment]
哈哈，好想法。。。不过貌似这种需求很少哦？

**Comment by wy19901227** [comment]
好快  我还没写完呢，刚写了个标题。。。

**Comment by wqforever** [comment]
collectionview 会有左右滑动刷新的需求
