### ISSUE TITLE
table View 横向滑动，加载更多的 滑动偏移的问题

### ISSUE THREAD

**Issue by yanchaoGan** [CoderMJLee/MJRefresh#1033]
#define  TableRotation  1
在mock tableview 横向滑动的时候
if (TableRotation) {
        self.tableView.transform = CGAffineTransformMakeRotation(-M_PI_2);
 }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
   if (TableRotation) {
        cell.contentView.transform = CGAffineTransformMakeRotation(M_PI/2);
    }
}
，需要滑动很大偏移量才能够 有效果。检查了源码：

#pragma mark - 私有方法
#pragma mark 获得scrollView的内容 超出 view 的高度
- (CGFloat)heightForContentBreakView
{
    CGFloat h = self.scrollView.frame.size.height - self.scrollViewOriginalInset.bottom - self.scrollViewOriginalInset.top;
    return self.scrollView.contentSize.height - h;
}

针对竖屏上下滑 || 左右拉动  self.scrollView.frame.size.height -> self.scrollView.bounds.size.height
更合理些

**Comment by wolfcon** [comment]
Duplicate of #1225
