### ISSUE TITLE
headRefresh还没有进入回调方法，就自动结束了（收回去了）

### ISSUE THREAD

**Issue by Kyoooooo** [CoderMJLee/MJRefresh#1034]
明杰老师，我进入页面就自动刷新，但是看不到headed 刷新动画，自己手动去拉的话headerRefresh还没有进入回调方法的时候，动画就自动结束了（收回去了），然后才进入了回调，回调里我才endRefreshing, 很奇怪哦，回调没回来 没调用endRefreshingheader动画就结束了，是bug吗？
另外，我pod下载MJRefresh最新版本是3.1.12的，怎么不是3.1.15呢

**Comment by CoderMJLee** [comment]
能提供一份出现这个问题的Demo么？我暂时没遇到此问题哈。
关于版本，你先pod repo update，然后再pod updtae

**Comment by Kyoooooo** [comment]
应该是我用的3.1.12版本才出现的问题，我pod updtae之后是3.1.15，就没有这个问题了

**Comment by CoderMJLee** [comment]
好的，因为3.1.12版本是没有适配iOS11的
