### ISSUE TITLE
在iOS11设置导航栏的prefersLargeTitles为YES

### ISSUE THREAD

**Issue by padishahG** [CoderMJLee/MJRefresh#1036]
1.在iOS11设置导航栏的prefersLargeTitles为YES
2.集成MJRefresh
3.在下拉tabView的时候导航栏也相应的变长（变大）
![gif5](https://user-images.githubusercontent.com/22125316/32649777-437bf7e0-c636-11e7-83e4-6c71308b72bc.gif)

**Comment by padishahG** [comment]
@大佬们

**Comment by CoderLT** [comment]
+1

**Comment by padishahG** [comment]
@CoderLT   这个mj已经解决了  你升级一下sdk就好了

**Comment by cai3804007** [comment]
怎么解决的啊  我也出现这个问题了 但是用最新的sdk还是会出现这个问题啊

**Comment by twtliaw** [comment]
你好解决了吗?

**Comment by wolfcon** [comment]
Duplicate of #1029

**Comment by VincentChow** [comment]
same issue on v3.5.0
