### ISSUE TITLE
希望能增加自定义更新时间的小功能

### ISSUE THREAD

**Issue by libercata** [CoderMJLee/MJRefresh#1038]
有时希望展示的更新时间为自定义的时间 而不是一次下拉刷新时刻的时间。

[[NSUserDefaults standardUserDefaults] setObject:model.updateTime forKey:self.scrollView.mj_header.lastUpdatedTimeKey];

 [[NSUserDefaults standardUserDefaults] synchronize];

类似这样

**Comment by CoderMJLee** [comment]
```objc
mj_header.lastUpdatedTimeText = ^(NSDate *lastUpdatedTime) {
    return 自定义字符串;
};
```
