### ISSUE TITLE
使用代理或者block回调通知前一页面进行header refresh，控件会卡住

### ISSUE THREAD

**Issue by FutureChen** [CoderMJLee/MJRefresh#104]
MJ老师，我再次出现。。
在2.0中， firstViewController push到 secondViewController  ,然后在secondViewController中执行回调，触发firstViewController  中的 [header beginRefreshing];
无法执行刷新，并且head 手动去下拉的时候，是没有箭头转动的动画也没有执行。

我记得以前的版本是可以 这么执行回调刷新的。 请查收~么么哒

**Comment by CoderMJLee** [comment]
好的，我抽空试试看，谢谢提醒

**Comment by CoderMJLee** [comment]
要不这样，你试试修改下MJRefreshHeader.m文件
- (void)beginRefreshing
{
    if (self.window) {
        self.state = MJRefreshHeaderStateRefreshing;
    } else {
        self.state = MJRefreshHeaderStateWillRefresh;
        // 刷新(预防从另一个控制器回到这个控制器的情况，回来要重新刷新一下)
        [self setNeedsDisplay];
    }
}
如果可行，你来这跟我说下，我再提交代码哈。现在没时间去写测试程序，sorry哈

**Comment by FutureChen** [comment]
恩 行，我呆会试试

**Comment by FutureChen** [comment]
oK 可以了
