### ISSUE TITLE
莫名其妙的在Window上出现一个小黑点，过一会就消失了

### ISSUE THREAD

**Issue by JackCoderForLove** [CoderMJLee/MJRefresh#1040]
原来没事，ios10.3.2系统的，前几天刷新还没有问题，这会就有问题了，总有个小黑点，很讨厌。
![2017-11-15 3 22 35 2](https://user-images.githubusercontent.com/10056702/32823719-26b8e44c-ca19-11e7-88b4-123bbd5d2f58.png)
![2017-11-15 3 22 38 2](https://user-images.githubusercontent.com/10056702/32823720-26f1728a-ca19-11e7-9690-b0a1d6c2b22d.png)

**Comment by JackCoderForLove** [comment]
![wechatimg13](https://user-images.githubusercontent.com/10056702/32823357-ddcb7a3e-ca17-11e7-895e-b20294cd6aff.jpeg)

**Comment by JackCoderForLove** [comment]
![wechatimg13](https://user-images.githubusercontent.com/10056702/32823662-f4502d80-ca18-11e7-951f-3cd522fe32a1.jpeg)
![2017-11-15 3 22 35 2](https://user-images.githubusercontent.com/10056702/32823666-f8059dac-ca18-11e7-8876-54f1db2d2701.png)
![2017-11-15 3 22 38 2](https://user-images.githubusercontent.com/10056702/32823671-fb47c580-ca18-11e7-9a99-9e9fbf9f0cd2.png)

**Comment by padishahG** [comment]
升级一下试试

**Comment by JackCoderForLove** [comment]
我昨天用的模拟器ios11系统，然并卵，还是有问题的，还有那个小黑点

**Comment by JackCoderForLove** [comment]
所以说升级并不能解决问题

**Comment by Yannmm** [comment]
查看视图结构时点击一下那个点，看他的名字，类型，父视图是谁

**Comment by JackCoderForLove** [comment]
父视图是UIWindow,名字就叫UIButton,类型也是UIButton,我不知道从哪里来的这个button
