### ISSUE TITLE
系统左滑返回手势会造成头部刷新停滞，页面假死

### ISSUE THREAD

**Issue by sj1910** [CoderMJLee/MJRefresh#1042]
利用系统自带的左滑手势，快速左滑返回时，有很大几率造成头部刷新停滞，整个页面假死，点不了，但是到别的页面再回来，这个页面会恢复正常

**Comment by sj1910** [comment]
好像是iOS11以下系统会，11以上就不会

**Comment by pilgrim1385** [comment]
+1，遇到了同样的问题

**Comment by pilgrim1385** [comment]
如果在viewWillAppear中写的header.beginRefresh，试试写在viewDidAppear中。或者在这两个方法中，不要调header.beginRefresh，直接调用逻辑或者接口吧，这样UI表现也会比调用beginRefresh好一些。
