### ISSUE TITLE
iphoneX 页面顶到头部时,刘海会遮挡到刷新控件,这个怎么解决

### ISSUE THREAD

**Issue by 1021811501** [CoderMJLee/MJRefresh#1049]
iphoneX 页面顶到头部时,刘海会遮挡到刷新控件,这个怎么解决啊,这个是正在刷新状态下的图片
![ff5d68fc-b566-4e8c-9e3e-583e15c2d6de](https://user-images.githubusercontent.com/13210765/33002022-78618f52-cdec-11e7-93be-300615344d90.png)

**Comment by Laixg** [comment]
同求

**Comment by iceVeryCold** [comment]
楼主解决了吗？

**Comment by sun2483968** [comment]
请问谁能给解决方案

**Comment by wolfcon** [comment]
#1151
