### ISSUE TITLE
iOS 8(Xcode 6.3, Swift 1.2)显示错位，另外在 Swift 中调用 tableView.footer.automaticallyRefresh = false 会 crash

### ISSUE THREAD

**Issue by imWildCat** [CoderMJLee/MJRefresh#105]
![qq20150411-1 2x](https://cloud.githubusercontent.com/assets/2396817/7101189/9a6bff50-e07e-11e4-9748-1800410bb92d.png)

**Comment by CoderMJLee** [comment]
1.能否给个错位的截图看看哈？

2.有无crash信息？

**Comment by imWildCat** [comment]
@CoderMJLee 楼上有图，不知道您是指什么样子的图？
没有 crash 就是显示混乱。

**Comment by CoderMJLee** [comment]
试试最新版？2.0版本

**Comment by imWildCat** [comment]
@CoderMJLee 抱歉，是我的失误，不是 **MJRefresh** 的问题。忘了 close 这个 issue 了。感谢。

我忘了添加
```
tableView.rowHeight = UITableViewAutomaticDimension
tableView.estimatedRowHeight = 100
```
了
