### ISSUE TITLE
footer 一直在刷新

### ISSUE THREAD

**Issue by Wangyn19920603** [CoderMJLee/MJRefresh#1052]
上拉加载更多的时候一直在刷新停不下来

**Comment by GPX-NSlog** [comment]
你是怎么解决的  我也遇到这个问题了

**Comment by Wangyn19920603** [comment]
应该就是11中 tableview上拉的时候偏移量不正确导致的 你可以试试加上 self.tableView.estimatedSectionHeaderHeight = 0;
self.tableView.estimatedSectionFooterHeight = 0;

**Comment by Wangyn19920603** [comment]
应该是11中 上拉的时候偏移量不正确导致的 你可以加上下面这两行代码试试
self.tableView.estimatedSectionHeaderHeight = 0;
self.tableView.estimatedSectionFooterHeight = 0; @GPX-NSlog
