### ISSUE TITLE
下拉刷新完毕后scrollView.contentOffset.y 跳跃式变化。

### ISSUE THREAD

**Issue by february29** [CoderMJLee/MJRefresh#1054]
代理方法- (void)scrollViewDidScroll:(UIScrollView *)scrollView 中view根据scrollView.contentOffset.y做位移动画。
scrollView.contentOffset.y 跳跃式变化导致动画不流畅。跳跃高度54。

**Comment by pusswzy** [comment]
- (CGFloat)tableView:(UITableView *)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath *)indexPath {
    CGFloat cellHeight = [[self.cellHeightDictionary objectForKey:indexPath] floatValue];
    if (cellHeight) {
        return cellHeight;
    }
    return UITableViewAutomaticDimension;
}

- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath
{
    [self.cellHeightDictionary setObject:@(cell.frame.size.height) forKey:indexPath];
}
把cell高度缓存下来

**Comment by pilgrim1385** [comment]
同样的问题，UI跟随contentOffset.y，在下拉刷新松手-开始刷新的时候，UI会直接跳到预期的刷新位置，而tableView会缓慢回到预期的刷新位置。

**Comment by guesspalm** [comment]
Same issue

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by wolfcon** [comment]
Duplicate of #1009

**Comment by JpacheGitHub** [comment]
他这个问题不是estimatedRowHeight导致的, 是因为refreshing状态设置contentoffset是动画设置的, idle设置回弹是动画设置的inset, 在DidScroll回调里, 不会回调多次过程值, 只会回调一次动画设置的预期值, 有解么, 如果在DidScroll里做的是view的动画, 就还好, 有个隐式动画可以让view看起来自然一些, 但如果是layer, 就GG了
