### ISSUE TITLE
更新到版本3.1.15.1版本，整个项目的tableView的reloaddata都无效了

### ISSUE THREAD

**Issue by Eesnh** [CoderMJLee/MJRefresh#1055]
之前用的是3.1.12版本，更新到3.1.15.1版本，tableView调用reloaddata方法无效

**Comment by DarrenKong** [comment]
我昨天也遇到这个问题了，然后我用回3.1.14版本

**Comment by guloooo128** [comment]
我也遇到这个问题了， 换回3.1.15了

**Comment by CoderMJLee** [comment]
是使用了automaticallyHidden属性？

**Comment by Eesnh** [comment]
没有使用automaticallyHidden属性
