### ISSUE TITLE
一直有这个小黑点，到底是为啥，这个button是哪里出来的，我该怎么解决

### ISSUE THREAD

**Issue by JackCoderForLove** [CoderMJLee/MJRefresh#1056]
![2017-11-23 9 30 09 2](https://user-images.githubusercontent.com/10056702/33156068-0e0b4a3e-d031-11e7-8fb6-6ab126450f52.png)

**Comment by VicoWang** [comment]
父视图是window，与MJRefresh无关吧。。

**Comment by CoderMJLee** [comment]
MJRefresh中没有任何往Window中添加UIButton相关的代码哦
