### ISSUE TITLE
UITableViewCell嵌套UICollectionView的时候,底部上拉刷新会多弹跳了一页

### ISSUE THREAD

**Issue by vistaLin** [CoderMJLee/MJRefresh#1057]
1.使用的是MJRefreshBackNormalFooter,在UITableViewCell里面嵌套了一个UICollectionView,上拉刷新的时候会自动多往上弹跳了差不多一页数据
2.使用UITableViewCell没有嵌套的时候就是正常
3.使用MJRefreshAutoNormalFooter就好了,但是我有不需要这个在数据不够的时候都展示底部刷新,所以想请问有办法吗解决吗?
4.我已经用了最新的MJRefresh版本,结果发现在10.3.3上都没有问题,只是会闪一下,但是iOS11上就会多探讨,请问是还没有时间适配吗?

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by wolfcon** [comment]
Duplicate of #1009
