### ISSUE TITLE
mj_reloadData陷入死循环了

### ISSUE THREAD

**Issue by wenrisheng** [CoderMJLee/MJRefresh#1059]
- (void)mj_reloadData
{
    [self mj_reloadData];
    
    [self executeReloadDataBlock];
}

陷入死循环了

**Comment by Kaizi-oo** [comment]
亲爱的，这个方法是用来method swizzling 的，嗯，也有这种写法啦

**Comment by CoderMJLee** [comment]
试试最新版？
