### ISSUE TITLE
添加一个提示消息

### ISSUE THREAD

**Issue by TheyCallMeTank** [CoderMJLee/MJRefresh#106]
大神你好，能不能在header和footer分别添加一个显示提示信息的方法，类似于微博那种“更新了XX条”，“加载了XX条”。

**Comment by CoderMJLee** [comment]
我建议你自己额外显示一个HUD出来提醒用户哈。因为你的提示信息颜色是怎样？要不要换行显示？字体大小多少？还要不要显示成功的打钩图片或者失败的叉叉图片？太多自定义的因素了

**Comment by TheyCallMeTank** [comment]
好的，谢谢大神回复~
