### ISSUE TITLE
MJRefresh和DZNEmptyDataSet冲突

### ISSUE THREAD

**Issue by Kaizi-oo** [CoderMJLee/MJRefresh#1060]
由于项目同时集成了MJRefresh和DZNEmptyDataSet，今天发现了一个mj_reloadData死循环的问题或者DNZEmptyDataSet不出现的问题，分析发现，reload被methodSwizzling 了两次，所以才出现了问题

问题：当使用了setAutomaticallyHidden的时候，把tableView和collectionView的reloadData都置换了，能不能只置换一个？谁用谁置换？
问题： 能不能不通过methodSwizzling实现相同的逻辑？

**Comment by HoneyLuka** [comment]
#1059

**Comment by HoneyLuka** [comment]
#1059 这个issue可能也是同样问题导致的

**Comment by caihua** [comment]
https://github.com/CoderMJLee/MJRefresh/issues/1062 这个也可能是

**Comment by Danie1s** [comment]
我也遇到这个问题

**Comment by CoderMJLee** [comment]
在下一个版本，我可能会让automaticllyHidden完全失效。如果现在继续解决，可以先把以下2个load方法注释掉，但automaticllyHidden = YES会失效
![image](https://user-images.githubusercontent.com/3817366/33821058-605085c4-de8d-11e7-89ee-65fbc16a1fa8.png)
当初设计这个API是为了方便开发者，省事，不用管footer的实现和隐藏。其实还是更建议开发者自行设置footer的显示和隐藏，这样控制地更加精细
