### ISSUE TITLE
3.1.15.1 会导致整个项目reloadData失败

### ISSUE THREAD

**Issue by colaicode** [CoderMJLee/MJRefresh#1062]
如题。已降为3.1.15解决问题

**Comment by Meliny001** [comment]
是的,我也遇到同样的问题cellForRowAtIndexPath不执行,暂时将版本解决.

**Comment by CoderMJLee** [comment]
不要使用automaticallyHidden属性，建议开发者自行控制footer的显示和隐藏

**Comment by caihua** [comment]
突然不显示内容了，查了大量资料，调试了半天，最后发现是MJRefresh的问题，赶紧来这里看看，发现了这个issue。
