### ISSUE TITLE
iOS11 存在分页 下拉刷新   有 bug

### ISSUE THREAD

**Issue by yinqiangw** [CoderMJLee/MJRefresh#1065]
第一次展示没问题 ,进入第二页
改变筛选条件后, 下拉刷新, scrollView 不会恢复到顶部,
如果改变筛选条件只有一个 cell, 会被遮挡, 稍微抖动会复原

**Comment by yinqiangw** [comment]
iOS 10 版本 正常

**Comment by yinqiangw** [comment]
_tableView.estimatedRowHeight = 0;
_tableView.estimatedSectionHeaderHeight = 0;
_tableView.estimatedSectionFooterHeight = 0;
issue 里面的解决方案

**Comment by Quxiaolei** [comment]
系统iOS 11.
选中tabA,下拉刷新至无数据状态.
切换至tabB,数据不够一页,一直显示无数据footer,用此方法解决.
thx @yinqiangw

**Comment by yinqiangw** [comment]
@Quxiaolei  我的没有这种情况啊   用resetNoMoreData试试

**Comment by wolfcon** [comment]
Demo?
