### ISSUE TITLE
关于iOS11及以上版本上拉刷新会出现跳跃式bug，暂时性的解决办法请看这里。

### ISSUE THREAD

**Issue by SuperLoveSue** [CoderMJLee/MJRefresh#1066]
if (@available(iOS 11.0, *)) {
self.mainTableView.estimatedRowHeight = 0;
self.mainTableView.estimatedSectionFooterHeight = 0;
self.mainTableView.estimatedSectionHeaderHeight = 0;
self.mainTableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
}

亲测加上这一段代码 可以解决iOS11情况下会出现跳跃式反应的问题 完全解决还是要mj大大来看一下 upupup

**Comment by unseim** [comment]
我的项目在主页就不可以，加了四行代码还是一样的跳跃，而且跳跃的距离大概是一屏多一点的高度，其他push出来的界面又没事。iOS11这次更新真是晔了狗了，目前还没找到解决方案

**Comment by igiu1988** [comment]
解决方法可以查看我在 https://github.com/CoderMJLee/MJRefresh/issues/1071 中的回答

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by wolfcon** [comment]
Duplicate of #1009
