### ISSUE TITLE
在下拉刷新的时候，会偶现tableView向下偏移一个MJHeader 高度的情况！偶现情况！

### ISSUE THREAD

**Issue by chuheridangwu** [CoderMJLee/MJRefresh#1069]
控制器在视图即将显示的时候已经将系统导航栏隐藏，所以的tableView偏移的不是一个64的高度，测量了一下出现问题的视图，跟mjHeader的高度是一致的，55的高度，会造成这样的原因是什么！！
[上载D6070725-9BED-4ECE-8752-AFD29625E193.png ...]（）

**Comment by chuheridangwu** [comment]
跟系统版本没有关系，已经关闭了系统会出现的偏移！

**Comment by BrightMoment** [comment]
我也是同样的问题，很蛋疼啊

**Comment by chuheridangwu** [comment]
嗯，很奇怪，就是header头没消失，但是看代码已经都让它消失了，不理解

**Comment by zhixingxi** [comment]
没沉吧这个，偶尔出现蛋疼的很呀

**Comment by mushanlianshi** [comment]
偶现    好蛋疼   想出现的时候不出现了

**Comment by chuheridangwu** [comment]
我这个发现是刷新频率太高的时候回出现，你们可以尝试减低一下刷新频率

**Comment by wolfcon** [comment]
已经修复了. 请更新一下新的版本试试
