### ISSUE TITLE
V3.1.15,上拉回调方法不停调用问题

### ISSUE THREAD

**Issue by lyonLiu1024** [CoderMJLee/MJRefresh#1070]
没人出现过再请求了第一页数据后,切换界面再切换回来的时候在viewwillapear方法中重新调用第一页数据时reloaddata后会不停调用上拉的block回调方法吗？

**Comment by lyoniOS** [comment]
具体情景是这样的:
1.UITabbarViewController下的两个控制器
2.A控制器viewWillApear方法中请求[self loadFirstData];方法，请求结束后上拉请求第2页数据
3.这时候切换到B控制器，再切换换来的时候，会自动调用MJ的上拉回调块方法

PS：但如果在A控制器中的viewWillApear方法中使用[self.tableview.mj_header beginRefreshing];在下拉回调用方法中写[self loadFirstData]的话则不会出现自动调用上拉回调块方法

**Comment by lianxingbo** [comment]
我遇到过，我一共五个用到上拉加载更多页面加上下面的方法，三个页面生效，还有俩页面无效。
    if (@available(iOS 11.0, *)) {
            _tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
            _tableView.estimatedRowHeight = 0;
            _tableView.estimatedSectionHeaderHeight = 0;
            _tableView.estimatedSectionFooterHeight = 0;
        }

**Comment by HYWDev** [comment]
我遇到的问题是上拉加载数据，数据不衔接问题，用了3楼的方法解决了

**Comment by LengQH** [comment]
我昨晚是:只要上拉不松手就一直在调用。 我直接弃用了最新版本的 改用了以前项目中的老版本(移除了Podfile文件中的pod 'MJRefresh' 然后 pod install 最后直接将原来的老版本拖进项目中了) 现在可以了！有需要可问我QQ:1205632644

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
