### ISSUE TITLE
关于iOS11及以上版本上拉加载更多会出现跳跃式bug

### ISSUE THREAD

**Issue by unseim** [CoderMJLee/MJRefresh#1071]
理论上来讲加上以下四行代码就可以了。但是我的项目在主页就不可以，加了四行代码还是一样的跳跃，而且跳跃的距离大概是一屏多一点的高度，其他push出来的界面又没事。iOS11这次更新真是晔了狗了，大家有遇到过吗？有没有好的解决方案呢？
if (@available(iOS 11.0, *)) {
self.mainTableView.estimatedRowHeight = 0;
self.mainTableView.estimatedSectionFooterHeight = 0;
self.mainTableView.estimatedSectionHeaderHeight = 0;
self.mainTableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
}

**Comment by CoderMJLee** [comment]
麻烦提供以一下出现此问题的Demo，我直接调试，谢谢

**Comment by HanXiaoTeng** [comment]
@CoderMJLee 我写了个小demo，上拉加载会出现该问题，请查看。
MJRefresh版本：3.1.15.1
[MJReresh_Demo.zip](https://github.com/CoderMJLee/MJRefresh/files/1549958/MJReresh_Demo.zip)

**Comment by liudiange** [comment]
我也遇到这个问题 确实是这样的 https://github.com/liudiange/practice1.git 这个demo老师你更加的熟悉 确实有这样的问题

**Comment by 2240054474** [comment]
我也出现了...如果有解决的请告知解决方法,谢谢

**Comment by unseim** [comment]
Sorrt，MJ老师，好几天没上Github没看见消息，Bug已经解决了。我说一下这个Bug吧，我不知道大家是不是跟我一样哦，说说我的Bug出现原因和解决方法。

我的代码某些宽高很活跃的界面（如朋友圈这种类似），我之前的代码是直接这样子Cell自动算宽高的。
tableView.rowHeight = UITableViewAutomaticDimension;
tableView.estimatedRowHeight = 44;

这个Bug的关键点在于：因为iOS11 之后selfSizzing 默认打开，要关闭的话只能通过上述的四行代码来操作。而此时estimatedRowHeight=44，重新给他复制了，因此selfSizzing关闭就失去效果了。所以就回出现这种跳跃式Bug，selfSizzing一旦打开，MJRefresh监听到了错误的高度，因此就出现了Bug。不信你可以试一下，你把rowHeight=100定死，estimatedRowHeight=0，这个bug就不存在了。

所以我的解决方案是用了Sunny的UITableView-FDTemplateLayoutCell框架算高。

**Comment by CoderMJLee** [comment]
@HanXiaoTeng 为啥你的Demo在我这边没看到跳跃式BUG？是怎样跳跃式？可以录个gif看看么

**Comment by CoderMJLee** [comment]
@liudiange 你的demo就出现跳跃式问题了。我有空调试一下

**Comment by liudiange** [comment]
谢谢老师

**Comment by liudiange** [comment]
@unseim 我也写了demo 我也自动计算高度的 不会出现跳跃式的bug  以为个人的观察当cell 比较高的时候也就是接近或者达到屏幕高度的时候 会出现这个bug

**Comment by dushihao** [comment]
我也出现了，大幅度下拉刷新之后，回弹的时候会先跳跃一下然后才继续滚上去。希望知道的大佬告知原因。

**Comment by monkiyang** [comment]
我的也出现了，要列表内容达到屏幕高度左右才会，目前通过加上`_tableView.estimatedRowHeight = 0;`解决，具体原因不清楚。

**Comment by shafujiu** [comment]
@monkiyang help me so much

**Comment by pthtc** [comment]
使用
`    if (@available(iOS 11.0, *)) {
        _tableView.estimatedRowHeight = 0;
    }`
可以暂时解决，期待bug解决

**Comment by igiu1988** [comment]
**结论：尝试使用`insertRowsAtIndexPaths:withRowAnimation:`来加载新数据。**

我的代码里也有跳跃问题，并且如大家所见，应该是在那些cell高度变化剧烈的页面特别容易复现，我猜测大家的代码应该是这样写的：footerRefresh->请求更多数据->使用tableView.reloadData()展示新数据。我仔细查看了MJRefresh，发现MJRefresh并没有操纵scrollView.offset，所以我猜测reloadData时tableView需要使用estimatedRowHeight来计算contentSize，这样预估出的contentSize肯定与现有的有比较大的差别，所以发生跳跃。而insertRows只预估增加的部分，不会影响已经显示的部分。

**Comment by liudiange** [comment]
@igiu1988  我觉得你虽然解决了这个问题 但是 如果我们的app是聊天的app 你用insertRowsAtIndexPaths:withRowAnimation:UITableViewRowAnimationAutomatic这个方法 在对方给你快速发消息时候很容易发生crash

**Comment by liudiange** [comment]
@igiu1988  不能说很容易 是小概率行的发生crash

**Comment by igiu1988** [comment]
@liudiange crash原因如果是：numberofRows返回的行数 != 原行数 + insert行数的话，我想需要一个机制去确保他们相等。其实我们也有这个问题，我刚刚想到了一个方案，不知道是否好使，有空我试试：轮询新消息追加放到数组a中，使用另一个轮询来检查是否有新增数据，有新增时先 b = a.copy 确保b不会被改变。

**Comment by LincLiu** [comment]
@unseim 为什么我设置_tableView.estimatedRowHeight = 0;过后会崩溃呢

**Comment by snailzzj** [comment]
缓存了高度之后还是有一点跳跃-_-比没缓存高度好一点...

**Comment by VinlorJiang** [comment]
折叠cell，header里添加的按钮来触发折叠与展开，头部用的刷新，当展开某一个cell，往上拉再和上cell的时候，整个tableView往下移，没有刷新控件的不会出现这种情况，请问大佬有什么好的解决方案吗？谢谢

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by wolfcon** [comment]
Duplicate of #1009
