### ISSUE TITLE
调用[self.tableview reloaddata] 重复进入下拉刷新

### ISSUE THREAD

**Issue by liudiange** [CoderMJLee/MJRefresh#1072]
老师你好：最近我发现一个重复进入下拉刷新的问题
- (void)viewDidLoad {
    [super viewDidLoad];
    // 初始化tableveiw
    [self setUpTableView];
    //  下拉刷新
    [self setRefresh];
    //  下拉加载更多
    [self loadMore];
}
/**
 *
 *   下拉刷新
 */
- (void)setRefresh {
    XMGNormalHeader *normalHeader = [XMGNormalHeader headerWithRefreshingBlock:^{
        
        @weakify(self);
        [XMGSessionManager.manager.dataTasks makeObjectsPerformSelector:@selector(cancel)];
        
        NSMutableDictionary *parma = [NSMutableDictionary dictionary];
        parma[@"a"] = @"list";
        parma[@"c"] = @"data";
        parma[@"type"] = @(TopicTypeVoice);
        [XMGSessionManager.manager GET:@"http://api.budejie.com/api/api_open.php" parameters:parma progress:nil success:^(NSURLSessionDataTask * _Nonnull task, NSDictionary *  _Nullable responseObject) {
            @strongify(self);
            self.maxTime = responseObject[@"info"][@"maxtime"];
            self.dataArray = [XMGTopicModel mj_objectArrayWithKeyValuesArray:responseObject[@"list"]];
            
            [self.tableView reloadData];
            [self.tableView.mj_header endRefreshing];
        } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
            @strongify(self);
            [self.tableView.mj_header endRefreshing];
        }];
    }];
    self.tableView.mj_header = normalHeader;
    [self.tableView.mj_header beginRefreshing];
}
/**
 *	
 *  上拉加载更多
 */
- (void)loadMore {
    XMGRefreshFooter *freshFooter = [XMGRefreshFooter footerWithRefreshingBlock:^{
        @weakify(self);
        [XMGSessionManager.manager.dataTasks makeObjectsPerformSelector:@selector(cancel)];
        
        NSMutableDictionary *parma = [NSMutableDictionary dictionary];
        parma[@"a"] = @"list";
        parma[@"c"] = @"data";
        parma[@"maxtime"] = self.maxTime;
        parma[@"type"] = @(TopicTypeVoice);
        [XMGSessionManager.manager GET:@"http://api.budejie.com/api/api_open.php" parameters:parma progress:nil success:^(NSURLSessionDataTask * _Nonnull task, NSDictionary *  _Nullable responseObject) {
            @strongify(self);
            self.maxTime = responseObject[@"info"][@"maxtime"];
            [self.dataArray addObjectsFromArray:[XMGTopicModel mj_objectArrayWithKeyValuesArray:responseObject[@"list"]]];
            [self.tableView reloadData];
            [self.tableView.mj_footer endRefreshing];
        } failure:^(NSURLSessionDataTask * _Nullable task, NSError * _Nonnull error) {
            @strongify(self);
            [self.tableView.mj_footer endRefreshing];
        }];
    }];
    self.tableView.mj_footer = freshFooter;
}
我本来的目的是改变数组中model的一个属性值 然后刷新页面 但是他重新调用了 [XMGRefreshFooter footerWithRefreshingBlock 这时候右边的进度条并没有到达页面的底部 查看footer的frame 的y值也是6500多 根本没有在页面的上面 我怀疑是 我reloaddata了 你监听scroller的偏移量计算的不对了 我打了断点也没进  后来我想是不是我开始的时候只加header 等有数据了在加footer 我那样改了还是同样的问题 好像还是偶现 ！

**Comment by zhanghongdou** [comment]
你的问题解决了吗，我也遇到了上拉加载时候，不停的调用，完全不理解为什么有这样的问题

**Comment by liudiange** [comment]
@zhanghongdou 我还没有解决 不过我改了我自己的代码了 我哪天有时间我的找找他的框架问题 看看能不能自己修改了然后提个pr

**Comment by wolfcon** [comment]
Duplicate of #1009
