### ISSUE TITLE
tableView 使用MJRefreshAutoFooter 在加载最后一页的问题

### ISSUE THREAD

**Issue by tianxie2002** [CoderMJLee/MJRefresh#1078]
tableView 使用MJRefreshAutoFooter进行数据加载， 在加载最后一页的时候，设置了footerhidden 为YES，然后明显有一个向下的卡顿，有别的办法吗，希望最后一页的时候 mj_footer隐藏了。

**Comment by liuhaoliang** [comment]
在numberofrows里面判断设置
