### ISSUE TITLE
IPhone X模拟器底部的footer上拉以后就一直显示

### ISSUE THREAD

**Issue by semnyqu** [CoderMJLee/MJRefresh#1080]
效果如图
<img width="433" alt="default" src="https://user-images.githubusercontent.com/14885293/34336227-6b0d2298-e990-11e7-97da-35ca25e0fb52.png">
footer继承自MJRefreshBackNormalFooter这个，
<img width="552" alt="default" src="https://user-images.githubusercontent.com/14885293/34336285-bc999bdc-e990-11e7-9aca-0a7b12477663.png">
只有iPhone X出现这个问题，其他版本没有

**Comment by zy364601065** [comment]
试试这个 self.tableView.mj_footer.automaticallyChangeAlpha = YES;

**Comment by semnyqu** [comment]
@zy364601065 感觉应该不是这个问题，我看了下，是由于scrollview的contentoffset的参数引起的

**Comment by devkiang** [comment]
你的tableview没有布局好

**Comment by semnyqu** [comment]
我使用了一个第三方库WMPageController, 估计应该是table和这个一起使用的问题，不过已经解决

**Comment by CHENDONGY** [comment]
@semnyqu 现在我也到了一样的问题,同样也是使用了WMPageController,请问最终你是怎么解决的

**Comment by semnyqu** [comment]
@CHENDONGY 
比较暴力，在viewDidAppear里面设置 self.tableView.contentInset
