### ISSUE TITLE
是否能加点Swift写法的Sample

### ISSUE THREAD

**Issue by isjeffcom** [CoderMJLee/MJRefresh#1081]
还在学习过程中，因为从Swift学起，不太清楚在Swift 4里怎么调回调，抱歉打扰，谢谢。

**Comment by Yohann-Chen** [comment]
tableView.mj_footer = MJRefreshAutoNormalFooter.init(refreshingBlock: {[unowned self] in
            self.pageNumber = self.pageNumber + 1
            self.loadMoreData()
        })

**Comment by Yohann-Chen** [comment]
`tableView.mj_footer = MJRefreshAutoNormalFooter.init(refreshingBlock: {[unowned self] in
self.pageNumber = self.pageNumber + 1
self.loadMoreData()
})`

**Comment by Yohann-Chen** [comment]
`tableView.mj_footer = MJRefreshAutoNormalFooter.init(refreshingBlock: {[unowned self] in

self.pageNumber = self.pageNumber + 1

self.loadMoreData()

})
`
