### ISSUE TITLE
下拉刷新失败tableview没数据就无法再一次下拉刷新了么？

### ISSUE THREAD

**Issue by jiangxuefeiRoadoor** [CoderMJLee/MJRefresh#1083]
下拉刷新如果tableview没有数据，那么页面就显示空白，而且当前的页面也不能继续下拉刷新了，不知道有没有同志遇到过类似的情况，能给我退出解决方案么？

**Comment by jiangxuefeiRoadoor** [comment]
如题，下拉刷新后模型数据里数据为空，【self.tableview.mj_header endrefreshing】后tableview就显示空白，接下来就无法重新下拉操作，下拉不会出现mj_header刷新的状态

**Comment by Kaizi-oo** [comment]
分两步，1.看能不能下啦，2看下啦了有没有刷新，我觉得你的问题是第一个
