### ISSUE TITLE
历史版本iOS11下加载更多时tableView的footer.endRefreshing死循环和表格偏移量异常的问题

### ISSUE THREAD

**Issue by JTWang4778** [CoderMJLee/MJRefresh#1089]
我使用的不是最新的版本做tableView的加载更多的时候，调用footer的endRefreshing时候，会引起加载更多方法的循环调用，并且加载更多刷新表格时，偏移量会出现异常

**Comment by JTWang4778** [comment]
问题已经解决，发现在低版本系统下没有出现上述问题，想到了iOS11下tableView的各种高度都有了默认值，就是自适应，所以设置tableView.estimatedRowHeight = 0  发现可以了😂 ，加载更多数据时 偏移量也正常了

**Comment by TianQiLi** [comment]
利用你的方法解决了tableView.estimatedRowHeight = 0  ，不明白为啥
