### ISSUE TITLE
如何隐藏Footer?

### ISSUE THREAD

**Issue by seanLee** [CoderMJLee/MJRefresh#109]
老师,你好. 我想麻烦问一下 如何才能隐藏Footer.我在
````(MJRefreshLegendFooter *)addLegendFooterWithRefreshingBlock:(void (^)())block```

外面设置

````self.collectionView.footer.hidden = YES;````
然后上拉刷新的功能貌似就用不了了. 

但是如果在block里面设置的话,这个footer又隐藏不了

**Comment by seanLee** [comment]
之前的问题我也看了, 但是感觉没什么用,我就重新开了一个问下你.

**Comment by CoderMJLee** [comment]
1.隐藏footer：
```
self.collectionView.footer.hidden = YES;
```
2.你都把它隐藏了，上拉刷新功能肯定用不了哈

3.最新版的上拉框架就是这么设计的：footer默认是不会隐藏的，不像以前的刷新完后会自动缩回去。这次的做法才是主流的哦，你可以参考微信朋友圈、QQ空间、新浪微博，都是这么干的。没必要隐藏footer哈

**Comment by stoneark** [comment]
@CoderMJLee 但是还是有这样的设计需求，尤其是当用户刚注册应用，列表中条目不多的时候，界面太丑。希望能够支持之前版本中的上拉方式。（我已经考虑用回旧版MJRefresh了...）

**Comment by CoderMJLee** [comment]
哈哈。我再斟酌一下

**Comment by DaliZh** [comment]
@CoderMJLee 确实有这种设计需求，我也在考虑先用回旧版的MJRefresh了。希望支持之前那种自动隐藏的方式

**Comment by LeoiOS** [comment]
@CoderMJLee 希望能添加个属性来控制是否隐藏底部的上拉加载，这样即保持了旧版的功能，又提供了新的加载方式，这样我们可以视需求决定是否隐藏底部加载。谢谢。

**Comment by CoderMJLee** [comment]
考虑在2.0版本整合以前的footer进来
