### ISSUE TITLE
下拉刷新的时候, mjheader 提示文字会和 large title 重合

### ISSUE THREAD

**Issue by lforme** [CoderMJLee/MJRefresh#1090]
下拉刷新的时候, mjheader 提示文字会和 large title 重合
![92c2a54051afe7360f9752c25fb97672](https://user-images.githubusercontent.com/13045790/34769544-0cc2d9b6-f639-11e7-897e-75c1f2fefd1b.jpg)

**Comment by lforme** [comment]
打扰了, 是自己的代码问题.

**Comment by tianmingzhi** [comment]
我也遇到了这个问题，请问你是怎么解决的，谢谢。

**Comment by lforme** [comment]
你看一下是不是自定义 UINavigationController 了

**Comment by tianmingzhi** [comment]
嗯嗯 发现是导航栏改透明的原因了，你那边遇到下拉刷新时和导航重叠的问题了吗？
