### ISSUE TITLE
我今天真的是被下拉刷新的重复调用bug弄哭了。。。。

### ISSUE THREAD

**Issue by Goallying** [CoderMJLee/MJRefresh#1093]
_tableView = [[UITableView alloc]init];
        _tableView.backgroundColor = [UIColor whiteColor];
        _tableView.delegate = self ;
        _tableView.dataSource = self ;
        _tableView.tableHeaderView = self.sdCycleView;
        _tableView.tableFooterView = [UIView new];
        _tableView.estimatedRowHeight = 100;
        [_tableView registerClass:[Ad_VdCell class] forCellReuseIdentifier:@"Ad_Vd"];
        [_tableView registerClass:[NewsSingleImageCell class] forCellReuseIdentifier:@"Single"];
        [_tableView registerClass:[NewsSeveralImageCell class] forCellReuseIdentifier:@"Several"];
        
        __weak typeof(self) wSelf = self ;
        _tableView.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
            [wSelf refresh];
        }];
        _tableView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
            [wSelf more];
        }];
refresh 方法调用了很多次，鬼畜一样的抖动。。。。。我的tableViewCell用的autolayout，所以必须estimatedRowHeight 自动算行高。怎么解决哇。。。。iOS 11.。。

**Comment by Kaizi-oo** [comment]
estimatedRowHeight = 150 try！

**Comment by LengQH** [comment]
我的也是鬼畜一样  休命就是 你的解决了么！

**Comment by LengQH** [comment]
我直接弃用了最新版本的  改用了以前项目中的老版本(移除了Podfile文件中的pod 'MJRefresh' 然后 pod install 最后直接将原来的老版本拖进项目中了)  现在可以了！有需要可问我QQ:1205632644

**Comment by wolfcon** [comment]
Duplicate of #1009
