### ISSUE TITLE
mj_totalDataCount特殊情况有bug

### ISSUE THREAD

**Issue by tangbin583085** [CoderMJLee/MJRefresh#1094]
今天同事特殊处理TableView的numberOfRowsInTable全为0，但是numberOfSectionsInTableView不为0，他只利用了sectionHeaderView 和 footerView显示视图，而不利用cell - -!
所以建议函数可以增强？
比如：        
if (totalCount <= 0) {
           totalCount = tableView.numberOfSections;
 }

**Comment by CrusherWu** [comment]
不是有遍历每个 section 有多少 row 吗？你每个section 没有 row （不利用 cell）那就是0啊？不知道我的理解是不是对的。

- (NSInteger)xst_totalDataCount
{
    NSInteger totalCount = 0;
    if ([self isKindOfClass:[UITableView class]]) {
        UITableView *tableView = (UITableView *)self;
        
        for (NSInteger section = 0; section<tableView.numberOfSections; section++) {
            totalCount += [tableView numberOfRowsInSection:section];
        }
    } else if ([self isKindOfClass:[UICollectionView class]]) {
        UICollectionView *collectionView = (UICollectionView *)self;
        
        for (NSInteger section = 0; section<collectionView.numberOfSections; section++) {
            totalCount += [collectionView numberOfItemsInSection:section];
        }
    }
    return totalCount;
}
