### ISSUE TITLE
反馈一个比较严重的性能问题

### ISSUE THREAD

**Issue by xinxi053** [CoderMJLee/MJRefresh#1095]
UIScrollView+MJExtension.m
#define SYSTEM_VERSION_GREATER_NOT_LESS_THAN(v)  ([[[UIDevice currentDevice] systemVersion] compare:v options:NSNumericSearch] != NSOrderedAscending)
这个宏被频繁调用的地方比如：
- (UIEdgeInsets)mj_inset
{
#ifdef __IPHONE_11_0
    if (SYSTEM_VERSION_GREATER_NOT_LESS_THAN(11)) {  //这里性能损耗严重，2.6%的浪费
        return self.adjustedContentInset;
    }
#endif
    return self.contentInset;
}
这个消耗几乎跟我的一个cell的更新方法持平了。建议加个缓存。

**Comment by CoderMJLee** [comment]
谢谢建议，已修改
