### ISSUE TITLE
Demo里面模拟延迟加载数据，如果在刷新的时候页面被销毁就会奔溃

### ISSUE THREAD

**Issue by tyzChar** [CoderMJLee/MJRefresh#1096]
// 下拉刷新
    tableView.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        // 模拟延迟加载数据，因此2秒后才调用（真实开发中，可以移除这段gcd代码）
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            // 结束刷新 - **`（如果这里是异步执行的,就会导致TableView被回收线程还在运行，此时tableView是一个野指针就会报错）`**
            [tableView.mj_header endRefreshing];
        });
    }];

**Comment by tyzChar** [comment]
明杰老师，刚刚我改了一下你Demo的代码，我把__unsafe_unretained 改为了__weak 就不会奔溃了，是否在这个过程中tableView 并不知道上一级的View已经被释放，所以使用__unsafe_unretained有问题？

**Comment by OCer** [comment]
__weak会置为nil  __unsafe_unretained不会
