### ISSUE TITLE
上拉加载还是会跳跃式加载

### ISSUE THREAD

**Issue by myiosemail** [CoderMJLee/MJRefresh#1097]
上拉加载还是会跳跃式加载，就是上拉加载的时候最新的一条数据会显示在屏幕的顶部上面，正常的会直接显示在上拉加载的位置追加最新的。

**Comment by myiosemail** [comment]
我把估计高度写tableView.estimatedRowHeight=150就不会出现了 写成tableView.estimatedRowHeight=44就会跳跃式加载

**Comment by xiaohai121** [comment]
@myiosemail      我也出现跳跃 这样设置解决问题的   _tableView.estimatedRowHeight = 0;
        _tableView.estimatedSectionFooterHeight = 0;
        _tableView.estimatedSectionHeaderHeight = 0;
       _tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

**Comment by chengongwen** [comment]
iOS 11 的bug。 加上这个就好了

_tableView.estimatedRowHeight = 0;
_tableView.estimatedSectionFooterHeight = 0;
_tableView.estimatedSectionHeaderHeight = 0;
_tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

**Comment by devlxin** [comment]
AppDelegate "application:didFinishLaunchingWithOptions:"方法里添加
`[UITableView appearance].estimatedRowHeight = 1000;`

**Comment by gleeeli** [comment]
自动计算行高的tableview用这句：
self.ctableView.estimatedRowHeight = [UIScreen mainScreen].bounds.size.height;
不自动计算行高的用这句：
self.stableView.estimatedRowHeight = 0;

**Comment by weikeyan** [comment]
> 自动计算行高的tableview用这句：
> self.ctableView.estimatedRowHeight = [UIScreen mainScreen].bounds.size.height;
> 不自动计算行高的用这句：
> self.stableView.estimatedRowHeight = 0;

如果是最后一行没内容还是会出现跳动

**Comment by weikeyan** [comment]
> iOS 11 的bug。 加上这个就好了
> 
> _tableView.estimatedRowHeight = 0;
> _tableView.estimatedSectionFooterHeight = 0;
> _tableView.estimatedSectionHeaderHeight = 0;
> _tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

此方法如果设置了，本来高度是通过约束自动计算的，不是就不行了么

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by wangxj4268** [comment]
> > 自动计算行高的tableview用这句：
> > self.ctableView.estimatedRowHeight = [UIScreen mainScreen].bounds.size.height;
> > 不自动计算行高的用这句：
> > self.stableView.estimatedRowHeight = 0;
> 
> 如果是最后一行没内容还是会出现跳动

兄弟，最后一行没内容时啥意思啊，我准备用他的方案解决，但是看到你说这一句我又有点慌了

**Comment by lixiangshadow** [comment]
collectionView 怎么解决?
