### ISSUE TITLE
pop回来内容会向下偏移64

### ISSUE THREAD

**Issue by 643824979** [CoderMJLee/MJRefresh#110]
你好！ 我的页面pop回来之后就出现tableview内容会向下偏移64   （项目的结构是rootViewController--nav--> tabBarController  ,tableView.frame.origin.y = 64）

![2015-04-15 11 08 45](https://cloud.githubusercontent.com/assets/7730311/7151642/014af210-e360-11e4-8165-429f126975c9.png)

**Comment by CoderMJLee** [comment]
之前有朋友提过类似的问题，你先试试最新代码哈

**Comment by 643824979** [comment]
好像pod没有更新

**Comment by CoderMJLee** [comment]
pod里面最新是1.4.6版本，你先试试pod repo update，更新下pod仓库

**Comment by foolish1016** [comment]
依然还是会有这个问题
