### ISSUE TITLE
上拉刷新只加载前两页，数据库还有数据，一直显示正在加载更多数据，打印后发现没有请求第三页数据

### ISSUE THREAD

**Issue by OMuzi** [CoderMJLee/MJRefresh#1101]

**Comment by CoderMJLee** [comment]
看看代码是怎么写的

**Comment by OMuzi** [comment]
tableView3 = UITableView(frame: CGRect.init(x: screenWidth * 2.0, y: 0.0, width: screenWidth, height: (scrollView?.frame.height)!), style: .plain)
        tableView3?.delegate = self
        tableView3?.dataSource = self
        tableView3?.tableHeaderView = UIView()
        tableView3?.tableFooterView = UIView()
        tableView3?.separatorInset = UIEdgeInsets.zero
        tableView3?.separatorColor = themeGrayColor
        let footer3 = MJRefreshAutoNormalFooter {
            self.loadData3()
        }
        tableView3?.estimatedRowHeight = 200.00
        tableView3?.mj_footer = footer3
        tableView3?.register(UINib(nibName: "StoreOrderUserInfoCell", bundle: nil), forCellReuseIdentifier: reuse3_0)
        tableView3?.register(UINib(nibName: "StoreOrderProductCell", bundle: nil), forCellReuseIdentifier: reuse3_1)
        tableView3?.register(UINib(nibName: "StoreOrderServiceCell", bundle: nil), forCellReuseIdentifier: reuse3_2)
        tableView3?.register(UINib(nibName: "StoreOrderCounterCell", bundle: nil), forCellReuseIdentifier: reuse3_3)
        tableView3?.register(UINib(nibName: "StoreOrderTimeCell", bundle: nil), forCellReuseIdentifier: reuse3_4)
        tableView3?.register(UINib(nibName: "StoreOrderGrayLineCell", bundle: nil), forCellReuseIdentifier: reuse3_5)


/// 获取已消费的订单列表
    @objc private func loadData3() {
        OMLog(".......", currentPage3)
        NetworkManager.shared.getStoreOrderList(status: status[2], page: currentPage3.description) { (state, data, error) in
            if state.code == 1 {
                OMLog("当前加载\(self.currentPage3)页数据.....")
                if self.isNeedReload[2] {
                    OMLog("@@@@@")
                    self.data3.removeAll()
                    self.allPrice3.removeAll()
                    self.numbers3.removeAll()
                    self.tableView3?.mj_footer.resetNoMoreData()
                    self.isNeedReload[2] = false
                }
                let model = StoreOrderModel(fromDictionary: data)
                self.currentPage3 = model.p + 1
                OMLog("..........")
                for index in model.pagelist {
                    var count: (Int, Int) = (0, 0)
                    var price: Float = 0.00
                    for item in index.pslist {
                        price += (item.price.floatValue * item.number.floatValue)
                        if item.type == "1" {
                            count.0 += 1
                        } else if item.type == "2" {
                            count.1 += 1
                        }
                    }
                    self.allPrice3.append(price)
                    self.numbers3.append(count)
                    self.data3.append(index)
                }
                if model.pagelist.count < 5 {
                    OMLog("加载当前页数\(self.currentPage3)完成，没有更多数据了。。。")
                    self.noMoreData3()
                }
            } else {
                OMLog("当前加载\(self.currentPage3)页数据失败")
                handle(code: state.code, msg: state.message, error: error)
            }
        }
    }


 ///是否需要刷新数据
    private var isNeedReload = [false, false, false, false]
    
    /// 当前加载的数据页数
    private var currentPage = [1, 1, 1, 1]
    
    private var currentPage3 = 1 {
        willSet{
            OMLog("页数", newValue)
        }
    }
    /// 加载的数据类型
    private var status: Array<NSNumber> = [0, 1, 2, 3]

**Comment by CoderMJLee** [comment]
好像没看到你调用endRefreshing结束刷新

**Comment by OMuzi** [comment]
noMoreData3里调用了endrefreshingWithNomoreData，你的意思是每次执行后应该调用一次endRefreshing

**Comment by OMuzi** [comment]
嗯嗯，非常感谢🙏
