### ISSUE TITLE
iOS 10.0以上 11.0以下上拉加载控件位置上移

### ISSUE THREAD

**Issue by WangXiang123** [CoderMJLee/MJRefresh#1109]
代码

//上拉加载
    self.tableView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
        
        //加载数据
        [self doLoadData];
    }];
![simulator screen shot - iphone 6s 10 0 - 2018-02-01 at 16 23 28](https://user-images.githubusercontent.com/20507704/35668533-ced6d25c-076c-11e8-81a3-708c9a85f7d9.png)

**Comment by Lisa1900** [comment]
遇到同样的问题+1

**Comment by iosyaowei** [comment]
+1

**Comment by AdminTestsGitHub** [comment]
+1

**Comment by AdminTestsGitHub** [comment]
有解么？

**Comment by FxDepths** [comment]
解决了吗
