### ISSUE TITLE
关于移除footer的处理疑问

### ISSUE THREAD

**Issue by nanjibingshuang** [CoderMJLee/MJRefresh#111]
在添加footer的时候我看到对contentInset进行了处理,但是在移除的时候没有对contentInset进行任何处理.这样子会有问题吧?如果我有一个需求,需要移除;一定条件下有需要添加,这样会导致contentInset的bottom越来越大.

**Comment by CoderMJLee** [comment]
最新代码是有处理的，在willMoveToSuperview方法中
