### ISSUE TITLE
下拉刷新完毕,54的偏移量不归位.

### ISSUE THREAD

**Issue by wangxumin** [CoderMJLee/MJRefresh#1110]
下拉刷新的时候,tableView向下inset54的偏移量,但是刷新完毕后,那个54的偏移量收不回去,刷新控件还外露显示,有人知道怎么回事没,我现在手动处理了下,调用下拉刷新结束的block,在里边判断下tableView的inset.top,如果不是0,就置为0.

**Comment by maligh** [comment]
https://github.com/CoderMJLee/MJRefresh/pull/1114    应该是这里有问题

**Comment by wolfcon** [comment]
#1283
