### ISSUE TITLE
3.1.15，iOS11，tableView只要上拉不松手，无限调用refreshingBlock

### ISSUE THREAD

**Issue by kptanjunhao** [CoderMJLee/MJRefresh#1112]
iOS11只要Cell的总数超出屏幕，上拉时只要不松手就会无数次调用refreshingBlock。

**Comment by LengQH** [comment]
我的也是,昨天晚上测试发现的

**Comment by thneng** [comment]
请问你是用的那个版本的呢？

**Comment by caoyunxiao** [comment]
好坑爹啊，我也遇到了这个问题

**Comment by CoderMJLee** [comment]
能够提供一个有此问题的Demo？谢谢

**Comment by kptanjunhao** [comment]
@CoderMJLee https://github.com/kptanjunhao/MJRefreshISSUE-1112

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
