### ISSUE TITLE
iOS 上拉加载无限次访问后台服务器

### ISSUE THREAD

**Issue by WenzheFan** [CoderMJLee/MJRefresh#1113]
iOS 上拉加载无限次访问后台服务器，导致阿里服务器老是内存溢出

**Comment by HughLi** [comment]
try
if (@available(iOS 11.0, *)) {
            tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }else {
            self.automaticallyAdjustsScrollViewInsets = NO;
        }
       tableView.estimatedRowHeight = 0;
        tableView.estimatedSectionHeaderHeight = 0;
        tableView.estimatedSectionFooterHeight = 0;

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
