### ISSUE TITLE
关于手动导入到项目中出错的问题

### ISSUE THREAD

**Issue by yezhouxiang** [CoderMJLee/MJRefresh#1116]
如果我手动导入的话就会报以下错误：
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MJRefreshNormalHeader", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
如果是使用cocopods的话就单报link错误。不知道这个是咋回事。但是Demo在本机上又是能跑的。

**Comment by 757388559** [comment]
@yezhouxiang 这个问题解决了么？
