### ISSUE TITLE
下拉刷新,弹不回去问题

### ISSUE THREAD

**Issue by k373379320** [CoderMJLee/MJRefresh#1121]
在有下拉刷新的界面,下拉停留几秒,切换到别的Controller,在其他Controller停留数秒,再回来,就能重现

#import "MJRefreshHeader.h"
- (void)scrollViewContentOffsetDidChange:(NSDictionary *)change
{
    [super scrollViewContentOffsetDidChange:change];
    
    // 在刷新的refreshing状态
    if (self.state == MJRefreshStateRefreshing) {
        // 暂时保留
        if (self.window == nil) return;
 
        //----⬇️---->以下代码,会引起bug,setctionheader停留问题,是指什么?
        // sectionheader停留解决
        CGFloat insetT = - self.scrollView.mj_offsetY > _scrollViewOriginalInset.top ? - self.scrollView.mj_offsetY : _scrollViewOriginalInset.top;
        insetT = insetT > self.mj_h + _scrollViewOriginalInset.top ? self.mj_h + _scrollViewOriginalInset.top : insetT;
        //----⬆️----<
        //以下修复方案
        insetT  = self.mj_h + _scrollViewOriginalInset.top;

**Comment by maligh** [comment]
注释掉这一句就好了 if (self.window == nil) return; 
具体看https://github.com/CoderMJLee/MJRefresh/pull/1114有demo

**Comment by wolfcon** [comment]
#1283
