### ISSUE TITLE
上拉刷新导致header向上跳动，跳动长度为拖动长度

### ISSUE THREAD

**Issue by chjsun** [CoderMJLee/MJRefresh#1122]
使用UITableViewStylePlain的tableview，需要悬浮的header在顶部，但是上拉刷新的时候出现header向上跳动的问题，代码截图
![image](https://user-images.githubusercontent.com/13481443/37020561-1d6ab880-2157-11e8-8ab5-48c20ef29175.png)

表现形式为
![new](https://user-images.githubusercontent.com/13481443/37026725-3ac8c4fe-216a-11e8-97e7-0123ec41c600.gif)

附小demo提供测试 。
https://github.com/chjsun/refreshTest

**Comment by chjsun** [comment]
我在测试源码的时候，发现，在动画调用时，tableview的位置已经发生了变化。而此时去改变mj_offsetY的值，已经是错误的值了。
![image](https://user-images.githubusercontent.com/13481443/37028419-2910e214-216f-11e8-96d0-5a9ee81bf38a.png)
而我发现，在刚开始调用setState时，scrollView 的 mj_offsetY的值是正确的，而我通过修改值已经得到了正确的结果， 所以我建议从这个方面下手进行修改
![image](https://user-images.githubusercontent.com/13481443/37028533-770e3a5c-216f-11e8-8263-499376e8963c.png)
希望我的测试能对你有所帮助

**Comment by chjsun** [comment]
@siwangrufeng 我修改了一些代码，目前还未发现是否会对其他东西造成什么其他的影响，代码为
![image](https://user-images.githubusercontent.com/13481443/38990167-c071f0c6-440b-11e8-9252-0651f331907e.png)
希望对你有所帮助

**Comment by siwangrufeng** [comment]
厉害了 ，多谢

**Comment by wolfcon** [comment]
我尝试了一下, 这样修改还是会跳动啊? 你看看你的 Demo. 按照这个修改

**Comment by qinqi777** [comment]
兄嘚，你这个代码循环引用了~哈哈哈哈

**Comment by chjsun** [comment]
@qinqi777 没有啊？！循环引用什么鬼？

**Comment by mykoma** [comment]
最新代码中没处理这个问题吗？

**Comment by wang542413041** [comment]
如果是使用Autolayout的，给滚动视图设置一个estxxxRowHeight = xxx;
尝试一下

**Comment by JiaGuowei11** [comment]
我尝试将UITableView的style改为UITableViewStyleGrouped 就不在跳动了
