### ISSUE TITLE
最新版本的 MJ 上拉加载会出现请求服务器很多次，10.0 系统也会出现

### ISSUE THREAD

**Issue by jinPeng90** [CoderMJLee/MJRefresh#1125]
上拉一下，会连续调用好多次接口，10.0  和 11.0 系统都会出现这种情况

**Comment by yanpd** [comment]
是最新版才会吗，我目前用的3.1.12，没有多次请求接口

**Comment by jinPeng90** [comment]
嗯，最新版的 3.1.15.3  ，你可以试下

**Comment by jinPeng90** [comment]
版本回滚到 3.1.12 就好了😂😂

**Comment by LengQH** [comment]
我的也是 上拉一下，会连续调用好多次接口   以前的App好像不会！

**Comment by linsendear** [comment]
tableView.estimatedRowHeight = 0 试试

**Comment by coder-Jackie** [comment]
我的也是这问题,最新版3.1.15.3

**Comment by wangxj4268** [comment]
> 最新版我也这个问题, 版本已经回滚到 3.1.12 OK了

你好，请问有3.1.12的本地包么，我不是用cocoapods管理的...

**Comment by wangxj4268** [comment]
> 我直接弃用了最新版本的 改用了以前项目中的老版本(移除了Podfile文件中的pod 'MJRefresh' 然后 pod install 最后直接将原来的老版本拖进项目中了) 现在可以了！

你好，请问有3.1.12的本地包么，我不是用cocoapods管理的...

**Comment by wolfcon** [comment]
Duplicate of #1009
