### ISSUE TITLE
UITableview pageEable= YES 时，加载更多回弹有错误

### ISSUE THREAD

**Issue by MengLiMing** [CoderMJLee/MJRefresh#1126]
UITableview  pageEable= YES 时，加载更多回弹有错误

**Comment by thyonline** [comment]
是的呢...我也发现同样的问题. 楼主解决了吗?

**Comment by MengLiMing** [comment]
把 MJRefreshBackNormalFooter 换成了 MJRefreshAutoNormalFooter 。暂时这样。

**Comment by thyonline** [comment]
@MengLiMing 我暂时也用这个类了....

**Comment by Cocowyr** [comment]
@thyonline @MengLiMing 设置tabelView.estimatedRowHeight=0试一试，因为MJRefresh底部的上拉刷新是根据contentSize来计算的，当数据更新的时候，得出来的contentSize只是预估的。

**Comment by thyonline** [comment]
@Cocowyr 您说的方法我最开始时候尝试过得。没有效果，目前我选择在刷新结束后，执行table滚动动画，也可以感觉是复位效果

**Comment by MengLiMing** [comment]
@thyonline 我的也是全屏视频。。。 正常情况下MJRefreshAutoNormalFooter 没什么问题了。但是endRefreshingWithNoMoreData的时候。就需要自己设置contentOffset了。

**Comment by wolfcon** [comment]
Duplicate of #311
