### ISSUE TITLE
上拉在iphoneX上底部一直显示上拉提示

### ISSUE THREAD

**Issue by WSGNSLog** [CoderMJLee/MJRefresh#1127]
如图上拉在iphoneX上底部一直显示上拉提示
![simulator screen shot - iphone x - 2018-03-21 at 13 59 00](https://user-images.githubusercontent.com/22335435/37696308-983a7914-2d10-11e8-9739-829e49594f71.png)

**Comment by wty302857194** [comment]
是的 系统默认是全屏的  如果我们手动把这个距离写死 就失去全屏的效果了，请问mj大神有没有办法解决呢

**Comment by forping** [comment]
if (@available(iOS 11.0, *)) {
        [[UIScrollView appearance] setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
    } else {
    }

**Comment by wolfcon** [comment]
```swift
footer.automaticallyChangeAlpha = true
```
