### ISSUE TITLE
在iOS11.0后, 设置pageEnable = true后, 上拉加载, TableView复位错误.

### ISSUE THREAD

**Issue by thyonline** [CoderMJLee/MJRefresh#1128]
当设置TableView.isPageEnable 后, 执行上拉加载, 出现TableView复位错误...
设置 contentBehavior 和 各种estimateHeight 均无效.

**Comment by thyonline** [comment]
[问题已经凑合的解决了]

**Comment by 47God** [comment]
哇,  好像可以耶.  这位大神好厉害

**Comment by Cocowyr** [comment]
设置tabelView.estimatedRowHeight=0 就好了，因为MJRefresh底部的上拉刷新是根据contentSize来计算的，当数据更新的时候，得出来的contentSize只是预估的。

**Comment by z234009184** [comment]
@Cocowyr 并不好使，不过 #1196 解决了这个问题！

**Comment by wolfcon** [comment]
Duplicate of #311
