### ISSUE TITLE
上拉加载更多重复调用回调 使用的是最新版本

### ISSUE THREAD

**Issue by ysCharles** [CoderMJLee/MJRefresh#1133]
xcode9.3  iOS11.3 环境下

**Comment by xulifeiyu900201** [comment]
同样遇到了这个问题

**Comment by xulifeiyu900201** [comment]
我的是老版本3.1.14.1

**Comment by Ryan0520** [comment]
同样遇到了这个问题

**Comment by linsendear** [comment]
tableView.estimatedRowHeight = 0; 写上这句试试

**Comment by ysCharles** [comment]
tableView.estimatedRowHeight = 0 试过了  没用

**Comment by AdMains** [comment]
使用版本3.1.15.3和3.1.12，开发环境是xcode9.3 iOS11.3, iOS10.3.1 都会出现上拉加载更多，重复调用回调 的问题。

**Comment by np8025** [comment]
我也遇到了，加个手势状态的判断就解决了

**Comment by xiaobt** [comment]
> 加个手势状态的判断

请问是怎么判断的？

**Comment by np8025** [comment]
在MJRefreshAutoFooter.h文件里：
- (void)scrollViewContentOffsetDidChange:(NSDictionary *)change
{
    [super scrollViewContentOffsetDidChange:change];
    
    if (self.state != MJRefreshStateIdle || !self.automaticallyRefresh || self.mj_y == 0) return;
    
    if (_scrollView.mj_insetT + _scrollView.mj_contentH > _scrollView.mj_h) { // 内容超过一个屏幕
        // 这里的_scrollView.mj_contentH替换掉self.mj_y更为合理
        if (_scrollView.mj_offsetY >= _scrollView.mj_contentH - _scrollView.mj_h + self.mj_h * self.triggerAutomaticallyRefreshPercent + _scrollView.mj_insetB - self.mj_h) {
            // 防止手松开时连续调用
            CGPoint old = [change[@"old"] CGPointValue];
            CGPoint new = [change[@"new"] CGPointValue];
            if (new.y <= old.y) return;
            
            // 当底部刷新控件完全出现时，才刷新
            UIGestureRecognizerState panState = _scrollView.panGestureRecognizer.state;
            ***if (panState == UIGestureRecognizerStatePossible) {
                //手势状态判断，避免重复刷新
                [self beginRefreshing];
            }***
        }
    }
}

**Comment by ToLengSon** [comment]
自己重写下MJRefreshFooter的beginRefreshing方法，然后里面判断下是offsetY是否大于0，如果满足就调用super

**Comment by wolfcon** [comment]
Duplicate of #1009
