### ISSUE TITLE
iOS 11 大标题刷新问题

### ISSUE THREAD

**Issue by smallBei** [CoderMJLee/MJRefresh#1134]
在大标题上刷新会有跳动的问题
进入页面刷新 会在大标题的下面 进行刷新
进入页面后手动刷新 header 会在大标题的后面，显示不出来，当松手后 进入到MJRefreshStateRefreshing 状态的时候 会在 大标题的后面，

如何解决

**Comment by Hello-Bye** [comment]
@CoderMJLee

**Comment by dong136279559** [comment]
请问解决了吗?

**Comment by cai3804007** [comment]
怎么解决了吗？  一样遇到这种问题

**Comment by ieliwb** [comment]
同问

**Comment by zhangjianjun056** [comment]
同问+1

**Comment by wolfcon** [comment]
大标题建议暂时不要使用 MJRefresh 进行刷新, 大标题的刷新比较特殊, 系统在动态地改变 NavigationBar 的宽度. 同时左边字号根据设置属性的不同, 逻辑也不同. 与 SearchBar 有异曲同工之处
