### ISSUE TITLE
MJRefreshBackNormalFooter的实例结束刷新后，上拉箭头不隐藏， V3.1.15.3 

### ISSUE THREAD

**Issue by LemonChao** [CoderMJLee/MJRefresh#1135]
MJRefreshBackNormalFooter的实例 endRefreshingWithNoMoreData后，上拉箭头不隐藏， V3.1.15.3 
正常情况下这个箭头不是应该不显示的吗，看了Demo上时OK的，不知道Demo上的用的是哪个版本@CoderMJLee
```
self.mTableView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
}];
...
[self.mTableView.mj_footer endRefreshingWithNoMoreData];
```
![wechatimg65](https://user-images.githubusercontent.com/18051023/38653429-3faeea08-3e3d-11e8-9b56-43d5f87b354e.png)

**Comment by ZzzM** [comment]
目前我的解决方式，可以参考一下：

1.先将 TableView 的 Content Insets 属性设置为 Never：
![44141524059972_ pic](https://user-images.githubusercontent.com/10611210/38937278-6c5b0fba-4355-11e8-92d2-bf8ed0146e15.jpg)

2.再进行如下设置：
tableView.contentInset = UIEdgeInsets(top: SafeTopHeight + NavigationBarHeight, left: 0, bottom: 0, right: 0) （SafeTopHeight = iPhoneX ? 44:20，NavigationBarHeight = 44）

**Comment by LemonChao** [comment]
@ZzzM 谢谢你的作答
不过好像你没有弄清楚我的问题，tableView.contentInset是正确的，mj_footer的位置也是OK的，
问题是  `已经全部加载完毕`左侧的箭头这个状态下不是应该隐藏的吗？？

看了Demo，调用方法是一样的，不清楚这里怎么了

**Comment by LemonChao** [comment]
我的原因找到了，
发现只要在  [footer endRefresh]调用之后紧接着调用
[footer  endRefreshingWithNoMoreData]就会发生上述情况
只调用一个就没事了
@ZzzM @shensj @ftp27 @RbBtSn0w
