### ISSUE TITLE
UIWebView使用MJRefreshAutoFooter时出现黑边

### ISSUE THREAD

**Issue by allran** [CoderMJLee/MJRefresh#1136]
在UIWebView加MJRefreshAutoFooter，以及继承它的MJRefreshAutoStateFooter，MJRefreshAutoNormalFooter时，底部会出现一块黑色的边框
![simulator screen shot - iphone 7 - 2018-04-14 at 15 04 24](https://user-images.githubusercontent.com/1505892/38765493-33e79080-3ff5-11e8-9aba-b80c9c6508f3.png)

如果把MJRefreshAutoFooter->willMoveToSuperview方法改为如下代码，则会不出现错误。
``
- (void)willMoveToSuperview:(UIView *)newSuperview
{
    [super willMoveToSuperview:newSuperview];
    
    if (newSuperview) { // 新的父控件
//        if (self.hidden == NO) {
//            self.scrollView.mj_insetB += self.mj_h;
//        }
        
        // 设置位置
        self.mj_y = _scrollView.mj_contentH;
    } else { // 被移除了
        if (self.hidden == NO) {
            self.scrollView.mj_insetB -= self.mj_h;
        }
    }
}
``

**Comment by TheLittleBoy** [comment]
你移除UIWebview的黑色背景不就行了
