### ISSUE TITLE
MJRefreshAutoNormalFooter自动刷新，位置问题

### ISSUE THREAD

**Issue by CoderChenJun** [CoderMJLee/MJRefresh#1139]
上面代码是我自定义TableView中调用MJRefreshAutoNormalFooter自动刷新。

下面图片是效果截图，刷新完毕后，mj_footer的位置很奇怪。这是怎么回事？

注：如果使用MJRefreshBackNormalFooter，刷新完毕后，mj_footer的位置就会回退到TableView的底部

```
MJRefreshAutoNormalFooter *footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(beginLoadMore)];
footer.triggerAutomaticallyRefreshPercent = -MJRefreshFooterHeight;
[footer setTitle:@"上拉加载更多" forState:MJRefreshStateIdle];
[footer setTitle:@"释放加载更多" forState:MJRefreshStatePulling];
[footer setTitle:@"正在加载更多" forState:MJRefreshStateRefreshing];
[footer setTitle:@"没有更多了" forState:MJRefreshStateNoMoreData];
self.mj_footer = footer;
```

<img width="322" alt="79e3413516a4eaffad0bbe7ba6726f98" src="https://user-images.githubusercontent.com/20350701/38977643-86757c4a-43e7-11e8-8909-fcfa79a4b991.png">

**Comment by TheLittleBoy** [comment]
没问题的，就是这么设计的。你需要手动控制footer的显示与隐藏。

**Comment by madaoCN** [comment]
同，我的也会回到tableview最底部，然后我的tableview高度还会变的很大
