### ISSUE TITLE
pod 的最新的MJ 然后上拉加载出现位置错乱

### ISSUE THREAD

**Issue by Link-Start** [CoderMJLee/MJRefresh#1140]
![4444444444444444](https://user-images.githubusercontent.com/16813937/39082283-3a660bba-4583-11e8-97e0-594cfc87a929.png)
代码如下:
  __weak __typeof(self)weakSelf = self;
    
    //下拉刷新
    self.tableView.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        __strong __typeof(weakSelf)strongSelf = weakSelf;
        strongSelf.currentPage = 1;
    }];
    //开始刷新
    [self.tableView.mj_header  beginRefreshing];
    
    //上拉加载
    self.tableView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
        __strong __typeof(weakSelf)strongSelf = weakSelf;
        strongSelf.currentPage++;
    }];
    self.tableView.mj_footer.hidden = YES;
    self.tableView.mj_header.automaticallyChangeAlpha = YES;
    self.tableView.mj_footer.automaticallyChangeAlpha = YES;
    self.tableView.mj_footer.automaticallyHidden = YES;

**Comment by Link-Start** [comment]
百度了好久发现是因为设置了下面的值
_tableView.estimatedRowHeight = 10;

把10改为0就没事了，可是项目中cell都是自动计算高度的，这怎么整？求大神帮助!!!!

**Comment by Link-Start** [comment]
好吧，试了一下，单独在这个页面，设置
_tableView.estimatedRowHeight = 0;
就OK了

**Comment by daishuyi** [comment]
我这边上拉加载更多的时候如果不设置 _tableView.estimatedRowHeight = 0话，加载完毕的时候，tableView往下自动滚动了好一段距离。现在杰哥怎么做不知道是否很好？
