### ISSUE TITLE
ios11下MJRefreshHeader首次触发刷新不显示

### ISSUE THREAD

**Issue by BadReese** [CoderMJLee/MJRefresh#1142]
你好，在搜索了现有ISSUE后还是需要请教个问题。
为一个tableView配置mj_header后在viewDidLoad的时候触发beginRefreshing，发现控件没有显示（隐藏在列表顶部的视图之下）。但是接着再手动下拉刷新，可以看到正确地显示了头部。
在IOS8下测试则都是正常显示的头部。
设置contentInsetAdjustmentBehavior为never，以及estimatedSectionHeaderHeight = 0等方案没有效果。
请您帮忙指导解决这个问题，谢谢

**Comment by BadReese** [comment]
我的header是继承了MJRefreshHeader的子类，替换了刷新的图标

**Comment by BadReese** [comment]
直接嵌入SCROLL VIEW导致的这个BUG，改在SCROLLVIEW与本视图之间嵌入了个UIVIEW就解决了该问题。

**Comment by bigNiuSanMao** [comment]
> 直接嵌入SCROLL VIEW导致的这个BUG，改在SCROLLVIEW与本视图之间嵌入了个UIVIEW就解决了该问题。

具体如何解决的 我也遇到了同样的问题 我是自定义header继承自 MJRefreshStateHeader
