### ISSUE TITLE
MJRefresh 导致 tableView sectionFooter向上偏移

### ISSUE THREAD

**Issue by niuben1990** [CoderMJLee/MJRefresh#1143]
MJRefresh 导致 tableView sectionFooter 无法悬浮在tableView底部，而是向上偏移了一段距离，有什么办法解决？

**Comment by niuben1990** [comment]
![default](https://user-images.githubusercontent.com/16039934/39164017-e0db6048-47af-11e8-94c7-7c02d264b261.gif)

**Comment by wolfcon** [comment]
Demo?
