### ISSUE TITLE
ios11.3 iohoneX运行，上拉加载还是会一直调用block

### ISSUE THREAD

**Issue by thneng** [CoderMJLee/MJRefresh#1144]
ios11.3 iohoneX运行，上拉加载还是会一直调用block,断点调试显示，KVO监听走的contentOffset，不是state,希望MJ大大更新下

**Comment by tangjinzhao** [comment]
我也遇到了 上拉加载会一直调用

**Comment by np8025** [comment]
自己加个判断条件就好了，判断下手势状态

**Comment by okayYusi** [comment]
作者说最新版本更新这个错误了，我试了一下还是在，坑爹

**Comment by wolfcon** [comment]
请尝试 3.2.3 版本
