### ISSUE TITLE
collectionView.mj_footer 结束刷新问题

### ISSUE THREAD

**Issue by augsun** [CoderMJLee/MJRefresh#1147]
coll..View 当最后一页结束刷新的时候 调用 endRefreshingWithNoMoreData, 当再取 self.collectionView.mj_footer.isRefreshing 的时候还是 YES. 导致如果再调用 [self.collectionView.mj_footer endRefreshing] 不能进入 NoMoreData 的状态.

<img width="876" alt="wx20180427-102744 2x" src="https://user-images.githubusercontent.com/12807798/39341425-b57f6bd0-4a05-11e8-80d3-34a7f2ac8277.png">
<img width="375" alt="wx20180427-102758 2x" src="https://user-images.githubusercontent.com/12807798/39341427-bc89256a-4a05-11e8-9e12-ca9b2818c31c.png">

回退到这个版本就不会
<img width="851" alt="wx20180427-103632 2x" src="https://user-images.githubusercontent.com/12807798/39341678-de8f6a88-4a06-11e8-986c-31d254aea6fd.png">

**Comment by daishuyi** [comment]
现在好像，如果你要停止刷新，且要求没有更多数据的话，就只用 endRefreshingNoMoreData, 不要再用endRefreshin了，否者会出现问题
