### ISSUE TITLE
TableView reloadData后，滚动条还在最下面

### ISSUE THREAD

**Issue by mzying2013** [CoderMJLee/MJRefresh#115]
tableview上拉加载更多数据后，UISegmentedControl切换，重新reloadData数据。为什么tableview滚动条还在最下面！期望您能尽快解决！

**Comment by mzying2013** [comment]
现在问题是，如果上拉刷新后，重新reloadData数据。滚动条不会滚到最顶端

**Comment by CoderMJLee** [comment]
为了更好地理解你的意思，搞个图片可以么？谢谢哈
