### ISSUE TITLE
iphoneX从顶部开始下拉刷新，刷新控件部分给刘海挡住了

### ISSUE THREAD

**Issue by medivh-xiong** [CoderMJLee/MJRefresh#1151]
iphoneX从顶部开始下拉刷新，刷新控件部分给刘海挡住了，该怎么处理。
![1](https://user-images.githubusercontent.com/19885098/39557710-18395e88-4ebc-11e8-9cf4-94e8cc3e5b1e.jpg)

**Comment by hh1myfei** [comment]
这个应该就是你tableView 位置的问题，你自己加个在iPX 设备上加个间距就好了，safeArea了解一下。这个不是框架的问题。

**Comment by medivh-xiong** [comment]
@hh1myfei 你理解错我的意思了，因为header的默认高度是固定的，所以在iphoneX的情况下，下拉加载显示header会被刘海挡住，所以是不是只有自定义header的高度，然后重新布局才能解决，我是想知道有没有更便捷的方式。

**Comment by hh1myfei** [comment]
@medivh-xiong  我想我应该是知道你的情况的，首先在iPhone X 设备上tableView你要是顶到头，tableView头部的内容不就被刘海挡住了？

**Comment by XHJiang** [comment]
我现在也在找这个问题,各种改好像并没有效果,刘海是挡住内容了,但是内容区域是特殊处理的, 类比京东的轮播图,有什么方法么

**Comment by qiuyubude** [comment]
请问问题解决了吗 最近也碰到这个问题

**Comment by TonyGJJ** [comment]
解决了吗？ 我也遇到了

**Comment by kinarobin** [comment]
![wechatimg173](https://user-images.githubusercontent.com/29303030/41033983-d93d32ee-69ba-11e8-9d54-6ce9fbf9219e.jpeg)
把tableView 位置设置成这样满足不了需求么？

**Comment by kinarobin** [comment]
![1528282474253](https://user-images.githubusercontent.com/29303030/41034071-15436eca-69bb-11e8-9b57-c4f8e6c6f599.jpg)
把tableView 位置设置成这样满足不了需求么？

**Comment by xiaopin** [comment]
我也遇到了，目前我们项目首页导航栏透明度是跟随用户滑动而变化的，我是这样解决的：

```ObjC
@interface VBHeaderRefresh : MJRefreshGifHeader
- (void)adaptShapedScreen;
@end

@implementation VBHeaderRefresh

- (void)prepare {
    [super prepare];
    ...
}

- (void)adaptShapedScreen {
    self.mj_h = 88.0;
    [self.gifView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.width.height.equalTo(@42.0);
        make.centerX.equalTo(self);
        make.bottom.equalTo(self).offset(-10.0);
    }];
    [self setNeedsLayout];
    [self layoutIfNeeded];
}

@end
```

如果为iPhone X时，调用`-adaptShapedScreen `方法重新设置下拉控件的frame

**Comment by sun2483968** [comment]
请问大家是在怎么解决的？

**Comment by wolfcon** [comment]
@sun2483968 你不看别人的回答吗? 自定义一个 Header.

**Comment by coderxdotwang** [comment]
我使用的：
self.tableView.mj_header?.mj_h += STATUSBAR_HEIGHT
self.tableView.mj_header?.placeSubviews()
：）

**Comment by Liyongcong** [comment]
> ```swift
> = true
> ```



> @sun2483968 你不看别人的回答吗? 关键词: `自定义一个 Header`. 你的楼上也给出方案了. 虽然这个方案不够优雅 PS: 不要刷屏. 理性讨论
> 
> # [建议做法]使用 `ignoredScrollViewContentInsetTop`
> ```swift
> tableView.mj_header.ignoredScrollViewContentInsetTop = -44
> 
> // 这样做之后通常情况下还要配合自动渐隐来达到效果更佳
> tableView.mj_header.automaticallyChangeAlpha = true
> ```
> 
> # [不推荐做法]自定义 Normal Header
> > 注意这里如果继承 Normal Header, 由于 Normal Header 默认是填充整个高度, 来布局子 view 的. 所以仅简单的加高度会导致子 view 拉伸的比较开. 你可以自定义或者使用默认高度, 来加一部分下移高度, 这时候再配合渐隐效果. 自己做吧
> 
> ## 这是下移 `header` 一部分的代码, 这个与直接修改 `ignoredScrollViewContentInsetTop` 道理相同
> ```swift
> override func placeSubviews() {
>     super.placeSubviews()
> 
>     self.mj_y += 44
> }
> ```
> 
> ## 这是自定义高度的代码
> ```swift
> override func prepare() {
>     super.prepare()
> 
>     self.mj_h = 88
> }
> ```

这样设置并没用

**Comment by gitph101** [comment]
您好，邮件已收到。

**Comment by 309598016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
