### ISSUE TITLE
The bottom of UITableViewController appear a bit problem on iPhoneX device! Help please

### ISSUE THREAD

**Issue by fengyixuanlz** [CoderMJLee/MJRefresh#1152]
![simulator screen shot - iphone x - 2018-05-09 at 17 28 38](https://user-images.githubusercontent.com/8016922/39807577-36f2d5c8-53af-11e8-9f12-5fa4a22877c4.png)

**Comment by fengyixuanlz** [comment]
Anyone here?

**Comment by xudehuai** [comment]
Maybe  u can add a FooterView that height is 34.0 on iPhone X
