### ISSUE TITLE
当大标题刷新时，在刷新状态，来回上下拖动会死循环崩溃

### ISSUE THREAD

**Issue by Manzh** [CoderMJLee/MJRefresh#1153]
![b2881f76-13d4-4a56-94d4-10be28b08af4](https://user-images.githubusercontent.com/13374152/39983735-4c733eee-578b-11e8-985b-6705025cb243.png)
这个是contentinset设置造成的，暂时还没有好的解决方案

**Comment by ieliwb** [comment]
怎么解决呢，郁闷啊，经常闪

**Comment by wolfcon** [comment]
Duplicate of #1029
