### ISSUE TITLE
MJRefreshFooter在iPhone X下显示问题

### ISSUE THREAD

**Issue by xudehuai** [CoderMJLee/MJRefresh#1154]
在iPhone X手机下，MJRefreshFooter会被屏幕底部手势响应区域黑条遮挡，正确情况应该是在屏幕区域外卖？我查找了一些资料，大体都是设置34.0的FooterView或者设置ContentInset的Bottom。我通过修改源代码，修改Footer位置实现了相关功能，但是直接这样肯定不方便，所以希望可以暴露相关接口，便于设置使用，谢谢

**Comment by TheLittleBoy** [comment]
跟tableview的设置有关！你需要适配iPhone X的安全区域。
