### ISSUE TITLE
上拉刷新提示没有更多数据后, footer的箭头有时会有, 有时会没

### ISSUE THREAD

**Issue by tounaobun** [CoderMJLee/MJRefresh#1159]
如题所示

**Comment by daishuyi** [comment]
我也是存在这种现象，哥们你有解决的方案没

**Comment by daishuyi** [comment]
应该只要上拉过后的显示的没有更多数据后，都会出现这样的bug

**Comment by tounaobun** [comment]
暂时没找到解决办法, 要么只能把footer给隐藏掉, 要么显示提示文本,并且附带它给的默认箭头 @daishuyi

**Comment by daishuyi** [comment]
self.tableView..mj_footer?.endRefreshingWithNoMoreData();
(self.tableView.mj_footer as? MJRefreshBackNormalFooter)?.arrowView.isHidden = true;

这两句写上好像也可以。我看了里面写的代码， endRefreshingWithNoMoreData的时候arrowView的isHidden被置为true，但是我之后在cell点击方法中获取到的属性是 false，意味hidden后又被置为false了。

**Comment by daishuyi** [comment]
￼
![image](https://user-images.githubusercontent.com/38234719/40836766-7c1a354c-65ca-11e8-91d6-b9a071d43dbf.png)

**Comment by daishuyi** [comment]
![1527849819978](https://user-images.githubusercontent.com/38234719/40837086-c37b802a-65cb-11e8-9cde-c06f6f6d4768.jpg)
看看这里就应该明白了，所以我们可以在0.4秒等这个动画完毕，在隐藏掉就OK了

**Comment by tounaobun** [comment]
@daishuyi /强

**Comment by tounaobun** [comment]
`            [self.tableView.mj_footer endRefreshingWithNoMoreData];
            // MJRefresh bug, 确保到底后arrow箭头隐藏掉
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)((MJRefreshSlowAnimationDuration + 0.01) * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                MJRefreshBackNormalFooter *footer = (MJRefreshBackNormalFooter *)self.tableView.mj_footer;
                footer.arrowView.hidden = YES;
            });`
只有这样处理了.

**Comment by daishuyi** [comment]
应该是我们版本的原因

**Comment by tounaobun** [comment]
@CoderMJLee 可以了, 看来endRefreshing和endRefreshingWithNoMoreData不能同时调用.

**Comment by daishuyi** [comment]
嗯，试了好使
