### ISSUE TITLE
上拉一直刷新问题

### ISSUE THREAD

**Issue by wqforever** [CoderMJLee/MJRefresh#1162]
上拉一直在刷新，我想上拉只要不松手就不刷新不行吗

**Comment by wang-yuchao** [comment]
在没有请求到数据的时候调用 [self.tableView.mj_footer endRefreshingWithNoMoreData]; 方法,

**Comment by spirit-jsb** [comment]
我也遇到这个问题了~不知道为什么只在少数的几个页面会出现这个问题

**Comment by spirit-jsb** [comment]
在没有数据的时候调用了 endRefreshingWithNoMoreData 方法

**Comment by wqforever** [comment]
我已经解决了，mj_footer.onlyRefreshPerDrag = YES; 这个设为yes 拖动一次只刷新一次 就不会上拉一直刷新了

**Comment by spirit-jsb** [comment]
我试试~
