### ISSUE TITLE
隐藏或移除 mj_footer 后，contentInset.bottom 被设置为 -44，ScrollView 导致底部被遮挡

### ISSUE THREAD

**Issue by InjoyDeng** [CoderMJLee/MJRefresh#1163]
![1](https://s3-qcloud.meiqia.com/pics.meiqia.bucket/fe954e503e78d06632ca98570ba2f5f9.png)

**Comment by allanGoldZhiKang** [comment]
怎么解决的  怎么关了

**Comment by InjoyDeng** [comment]
@allanGoldZhiKang 没解决，我看 issue 太多了，也没人管，就关了

**Comment by wolfcon** [comment]
方便拍个截图视频+ Demo 吗

**Comment by gyyxiaogao** [comment]
这么明显的问题,怎么没有被修复啊?

**Comment by InjoyDeng** [comment]
@gyyxiaogao 你给个 demo 吧，我这边没有了。
不过复现并不困难

**Comment by wolfcon** [comment]
上传 Demo 和描述清楚问题之前, 先关了. 我的确没有试出来你们的问题
