### ISSUE TITLE
自定义头部刷新偏移

### ISSUE THREAD

**Issue by OrangeFLJ** [CoderMJLee/MJRefresh#1165]
//调用
    self.tableView.mj_header = [FFRefresh headerWithRefreshingBlock:^{
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [self.tableView.mj_header endRefreshing];
        });
    }];

//继承自MJRefreshGifHeader, 从写prepare方法
- (void)prepare {
    [super prepare];
    NSMutableArray *idleImage = [NSMutableArray arrayWithCapacity:0];
    
    for (NSInteger i = 1; i < 6; i++) {
        UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"加载下拉%zd", i]];
        [idleImage addObject:image];
    }
    
    [self setImages:idleImage forState:MJRefreshStateIdle];
    
    NSMutableArray *refreshingImages = [NSMutableArray array];
    for (NSUInteger i = 1; i < 6; i++) {
        UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"加载下拉%zd", i]];
        [refreshingImages addObject:image];
    }
    [self setImages:refreshingImages forState:MJRefreshStatePulling];
    // 设置正在刷新状态的动画图片
    [self setImages:refreshingImages forState:MJRefreshStateRefreshing];
    
    //隐藏时间
    self.lastUpdatedTimeLabel.hidden = YES;
    //隐藏状态
//    self.stateLabel.hidden = YES;
    

    //所有的自定义东西都放在这里
    [self setTitle:@"普通闲置状态" forState:MJRefreshStateIdle];
    [self setTitle:@"松开就可以进行刷新的状态" forState:MJRefreshStatePulling];
    [self setTitle:@"正在刷新中的状态" forState:MJRefreshStateRefreshing];
    [self setTitle:@"即将刷新的状态" forState:MJRefreshStateWillRefresh];
    [self setTitle:@"所有数据加载完毕，没有更多的数据了" forState:MJRefreshStateNoMoreData];
}

**Comment by CoderMJLee** [comment]
？？？肿么了

**Comment by Minozmin** [comment]
您好，你是不是也出现了自定义动画，在下拉刷新的动画是有一个从右上角到中间动作，而不是从中间下拉下来的？

**Comment by wolfcon** [comment]
@Minozmin 提供一个 demo?

**Comment by linZsama** [comment]
> 您好，你是不是也出现了自定义动画，在下拉刷新的动画是有一个从右上角到中间动作，而不是从中间下拉下来的？
我也遇到这个问题了请问您解决了吗我是collectview 手动下拉的时候自定义图片会从左边跑到中间

**Comment by linZsama** [comment]
> ？？？肿么了

请问老师 当我collectionview手动下拉刷新的时候自定义图片会从左边跑到中间,怎么办

**Comment by Minozmin** [comment]
> 您好，你是不是也出现了自定义动画，在下拉刷新的动画是有一个从右上角到中间动作，而不是从中间下拉下来的？
> 我也遇到这个问题了请问您解决了吗我是collectview 手动下拉的时候自定义图片会从左边跑到中间


我是自定义了下拉动画，然后在placeSubviews这个方法中重新设置了子控件的frame。
- (void)placeSubviews
{
    [super placeSubviews];

    self.gifView.contentMode = UIViewContentModeScaleAspectFit;
    self.gifView.frame = CGRectMake((self.mj_w - 90) / 2, 0, 90, 90);
    self.stateLabel.frame = CGRectMake(0, CGRectGetMaxY(self.gifView.frame), self.mj_w, 20);
}

**Comment by linZsama** [comment]
万分感谢 ~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Minozmin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月14日(星期二) 下午5:39
收件人:&nbsp;"CoderMJLee/MJRefresh"<MJRefresh@noreply.github.com&gt;;
抄送:&nbsp;"林哲"<459517786@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [CoderMJLee/MJRefresh] 自定义头部刷新偏移 (#1165)





  
您好，你是不是也出现了自定义动画，在下拉刷新的动画是有一个从右上角到中间动作，而不是从中间下拉下来的？
 我也遇到这个问题了请问您解决了吗我是collectview 手动下拉的时候自定义图片会从左边跑到中间
  
我是自定义了下拉动画，然后在placeSubviews这个方法中重新设置了子控件的frame。
  
 
(void)placeSubviews
 {
 [super placeSubviews];
 
self.gifView.contentMode = UIViewContentModeScaleAspectFit;
 self.gifView.frame = CGRectMake((self.mj_w - 90) / 2, 0, 90, 90);
 self.stateLabel.frame = CGRectMake(0, CGRectGetMaxY(self.gifView.frame), self.mj_w, 20);
 }
