### ISSUE TITLE
iOS11 中 上拉加载更多后，真个 tableview 往下偏移了很多

### ISSUE THREAD

**Issue by ysCharles** [CoderMJLee/MJRefresh#1166]
![wechatimg1631](https://user-images.githubusercontent.com/12378478/41012541-8fcce9a6-6974-11e8-8f87-9fca40e54ae4.jpeg)

如图 我上拉加载更多后，tableview 整体下移了一段距离，

![wechatimg1632](https://user-images.githubusercontent.com/12378478/41012589-cd0e43fa-6974-11e8-9ff9-5996c53da013.jpeg)
这是 tableview 的 frame 和 bounds

**Comment by puhahalx** [comment]
是不是也是用根据约束估算行高方法的

**Comment by ysCharles** [comment]
是的 使用的 约束估算行高方法

**Comment by puhahalx** [comment]
我也是碰到这个问题了 现在还没解决

**Comment by ysCharles** [comment]
esimateRowheight 设置的接近真是高度或者大于真实高度的话  可以解决问题

**Comment by Changzw** [comment]
![e305f6ad-b9e5-4416-b86e-6cf9126e1830](https://user-images.githubusercontent.com/14252053/41906792-6eb96d9a-7971-11e8-955b-7085d3c95b0a.png)
我遇到了同样的问题，请问知道怎么解决吗，tableView 用的 是Texture 里面的tableNode做的

**Comment by ysCharles** [comment]
上面的 @puhahalx 朋友提醒了我  我esimateRowheight的高度设置的接近或者大于 cell实际高度的时候 可以避免问题出现

**Comment by Changzw** [comment]
iOS 11+ 版本会出现

**Comment by Changzw** [comment]
看这个issue: https://github.com/CoderMJLee/MJRefresh/issues/1170

**Comment by iBCode** [comment]
使用 UICollectionView，在 iOS 11 的模拟器下，也是出现这样的问题

**Comment by wolfcon** [comment]
请更新最新版, 並且设置这个
```swift
tableView.estimatedRowHeight = 0
```
