### ISSUE TITLE
"数据已全部加载" 显示在视图中央

### ISSUE THREAD

**Issue by keroushe** [CoderMJLee/MJRefresh#1167]
"数据已全部加载" 显示在视图中央， 能否显示在整个TableView 的最底部? 谢谢 !

**Comment by CoderMJLee** [comment]
你可以自定义一下刷新控件，重写某些方法，自己去调整控件位置

**Comment by daishuyi** [comment]
MJRefreshBackStateFooter就是在底部的那种
