### ISSUE TITLE
求助：crash ios8 setContentInset

### ISSUE THREAD

**Issue by zhangxing929** [CoderMJLee/MJRefresh#1169]
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist:  {length = 2, path = 0 - 4}'

Last Exception Backtrace:
0   CoreFoundation                       ___exceptionPreprocess
1   libobjc.A.dylib                      _objc_exception_throw
2   CoreFoundation                       +[NSException raise:format:]
3   Foundation                           -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4   UIKit                                ___45-[UICollectionViewData validateLayoutInRect:]_block_invoke
5   UIKit                                -[UICollectionViewData validateLayoutInRect:]
6   UIKit                                -[UICollectionView layoutSubviews]
7   UIKit                                -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
8   QuartzCore                           -[CALayer layoutSublayers]
9   QuartzCore                           __ZN2CA5Layer16layout_if_neededEPNS_11TransactionE
10  UIKit                                -[UIView(Hierarchy) layoutBelowIfNeeded]
11  UIKit                                -[UICollectionView setContentInset:]
12  myapp                            	 __30-[MJRefreshHeader setState:]_block_invoke	MJRefreshHeader.m:116
13  UIKit                                +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:]
14  UIKit                                +[UIView(UIViewAnimationWithBlocks) animateWithDuration:animations:completion:]
15  myapp                            	 -[MJRefreshHeader setState:]	MJRefreshHeader.m:127
16  myapp                            	 -[MJRefreshStateHeader setState:]	MJRefreshStateHeader.m:168
17  myapp                            	 -[MJRefreshNormalHeader setState:]	MJRefreshNormalHeader.m:94
18  libdispatch.dylib                    __dispatch_call_block_and_release
19  libdispatch.dylib                    __dispatch_client_callout
20  libdispatch.dylib                    __dispatch_main_queue_callback_4CF
21  CoreFoundation                       ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
22  CoreFoundation                       ___CFRunLoopRun
23  CoreFoundation                       _CFRunLoopRunSpecific
24  GraphicsServices                     _GSEventRunModal
25  UIKit                                _UIApplicationMain
26  myapp                             	 main	main.m:14
27  libdyld.dylib                        _start

**Comment by zhfwch** [comment]
我这边是自定义layout出了问题，还没解决。用系统的UICollectionViewFlowLayout是没问题的。不知道您那边是什么情况？

**Comment by zhfwch** [comment]
> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: {length = 2, path = 0 - 4}'
> 
> Last Exception Backtrace:
> 0 CoreFoundation ___exceptionPreprocess
> 1 libobjc.A.dylib _objc_exception_throw
> 2 CoreFoundation +[NSException raise:format:]
> 3 Foundation -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
> 4 UIKit ___45-[UICollectionViewData validateLayoutInRect:]_block_invoke
> 5 UIKit -[UICollectionViewData validateLayoutInRect:]
> 6 UIKit -[UICollectionView layoutSubviews]
> 7 UIKit -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
> 8 QuartzCore -[CALayer layoutSublayers]
> 9 QuartzCore __ZN2CA5Layer16layout_if_neededEPNS_11TransactionE
> 10 UIKit -[UIView(Hierarchy) layoutBelowIfNeeded]
> 11 UIKit -[UICollectionView setContentInset:]
> 12 myapp __30-[MJRefreshHeader setState:]_block_invoke MJRefreshHeader.m:116
> 13 UIKit +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options🏭animations:start:animationStateGenerator:completion:]
> 14 UIKit +[UIView(UIViewAnimationWithBlocks) animateWithDuration:animations:completion:]
> 15 myapp -[MJRefreshHeader setState:] MJRefreshHeader.m:127
> 16 myapp -[MJRefreshStateHeader setState:] MJRefreshStateHeader.m:168
> 17 myapp -[MJRefreshNormalHeader setState:] MJRefreshNormalHeader.m:94
> 18 libdispatch.dylib __dispatch_call_block_and_release
> 19 libdispatch.dylib __dispatch_client_callout
> 20 libdispatch.dylib __dispatch_main_queue_callback_4CF
> 21 CoreFoundation _**CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE**
> 22 CoreFoundation ___CFRunLoopRun
> 23 CoreFoundation _CFRunLoopRunSpecific
> 24 GraphicsServices _GSEventRunModal
> 25 UIKit _UIApplicationMain
> 26 myapp main main.m:14
> 27 libdyld.dylib _start

我这边是自定义layout出了问题，shouldInvalidateLayoutForBoundsChange设置为YES，同时刷新collectionview和beginrefresh就会闪退。用系统的UICollectionViewFlowLayout是没问题的。不知道您那边是什么情况？

**Comment by wolfcon** [comment]
`UICollectionView received layout attributes for a cell with an index path that does not exist: {length = 2, path = 0 - 4}` 

这个崩溃理由不是说的很明白了吗?

你的 Layout 数据源刷新前 invalidate Layout 了吗?
