### ISSUE TITLE
footer问题

### ISSUE THREAD

**Issue by zhouxl** [CoderMJLee/MJRefresh#117]
在cell未满屏时，footer怎么隐藏

**Comment by CoderMJLee** [comment]
现在已经不像以前那样子自动隐藏了哦，会一直显示哈，跟QQ空间、朋友圈是一样的做法。如果你真要隐藏，footer.hidden = YES;

**Comment by zhouxl** [comment]
那么当只有半屏的cell的时候怎么处理？

**Comment by zhouxl** [comment]
要判断contentSize 和frame的size？

**Comment by CoderMJLee** [comment]
试试最新的2.0版本能否满足你的要求哈
