### ISSUE TITLE
下拉刷新位置计算错误(与预估高度无关)

### ISSUE THREAD

**Issue by sxdxzkq** [CoderMJLee/MJRefresh#1170]
下拉刷新到可以刷新的高度不松手
点击tabbar其他item切换页面
此收到刷新的回调
请求完成后调用[weakSelf.tableView.mj_header endRefreshing];
再返回切换前的页面

看源代码
应该是由于当前页面不是正在显示的时候
[self setNeedsLayout];
不会触发- (void)layoutSubviews;
导致- (void)placeSubviews 不重新计算下拉刷新位置

**Comment by dte2mdj** [comment]
下拉的同时切换 tabBar, 必现这个问题

**Comment by vvlee** [comment]
碰到同样的问题，有人解决了吗

**Comment by Changzw** [comment]
+1

**Comment by Changzw** [comment]
目前只有 iOS 11+ 版本上会有这个问题

**Comment by Changzw** [comment]
在 iOS 11+ 上 UITableView 去掉了 UITableViewWrapperView 这层，wrapper 是显示cell 内容用的
![screen shot 2018-06-27 at 5 32 46 pm](https://user-images.githubusercontent.com/14252053/41965883-4884b002-7a30-11e8-9dea-d708d47e9297.png)

automaticallyAdjustsScrollViewInsets，这个属性在 11+上已经过时了。
控制器里面加上这几句 可以及解决问题了
`if (@available(iOS 11.0, *)) {
        tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        tableView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
        tableView.scrollIndicatorInsets = _tableView.contentInset; 
}`

**Comment by dte2mdj** [comment]
@Changzw 好像不好使啊。还是一样

**Comment by yuying2012** [comment]
确实是这样,有没有解决方式?

**Comment by lyle-luan** [comment]
@iBCode @Changzw 请教下两位，iOS11，我在控制器中添加了@Changzw 的代码，但是还没有解决问题，我的具体问题描述如下，使用MJRefreshBackNormalFooter上拉刷新，松开手进入刷新状态，显示 Loading 和菊花的时候，tableview 向下偏移了一点距离，导致 Loading 显示不出来。我的 cell 高度是固定的=屏幕的高度。不知道两位有没有遇到这种情况，或者有什么手段可以调试定位问题，多谢。

**Comment by sxdxzkq** [comment]
@lyle-luan @iBCode @yuying2012 @dte2mdj @Changzw @vvlee 
问题解决了
错误原因不是我之前想的没有触发layoutSubviews的问题

问题是ScrollView的下拉滑动手势在正常使用过程中手指离开屏幕会缓慢回弹到顶端
但是突然切换页面会导致ScrollView突然回到顶端
这时计算会出现问题

修改方式是在
```
- (void)scrollViewContentOffsetDidChange:(NSDictionary *)change
```
中加入判断
```
    if (self.state == MJRefreshStateRefreshing) {
        // 暂时保留
        if (self.window == nil) return;

        //解决手势中断带来的计算失误
        if (self.scrollView.isDecelerating) {
            // sectionheader停留解决
            CGFloat insetT = - self.scrollView.mj_offsetY > _scrollViewOriginalInset.top ? - self.scrollView.mj_offsetY : _scrollViewOriginalInset.top;
            insetT = insetT > self.mj_h + _scrollViewOriginalInset.top ? self.mj_h + _scrollViewOriginalInset.top : insetT;
            self.scrollView.mj_insetT = insetT;
            
            self.insetTDelta = _scrollViewOriginalInset.top - insetT;
        }
        
        return;
    }
```

**Comment by lyle-luan** [comment]
我刚搞定，上来想 reference 自己的 issue，正好看到你的回复，多谢分享了，我的问题跟你的不太一样，详见#1196

**Comment by dte2mdj** [comment]
目前 在viewWillAppear 中添加测试解决
if #available(iOS 11.0, *) {
    if !tableView.mj_header.isRefreshing { tableView.contentInset = .zero }
}

**Comment by sxdxzkq** [comment]
[#1197](https://github.com/CoderMJLee/MJRefresh/pull/1197) 解决
还是手势中断带来的问题
现在判断 手势中断 不显示刷新动画解决问题

**Comment by Liyongcong** [comment]
> iOS 11 模拟器下，UICollectionView 也出现这个问题，在 viewDidLayoutSubviews() 里面添加 @Changzw 的代码就可以了。
> @dte2mdj @yuying2012

你好，试了这种方式，不行啊，- (void)viewDidLayoutSubviews{
    [super viewDidLayoutSubviews];
    
    if (@available(iOS 11.0, *)) {
        self.courseWareCollectionView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        self.courseWareCollectionView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
        self.courseWareCollectionView.scrollIndicatorInsets = self.courseWareCollectionView.contentInset;
    }
}

**Comment by Liyongcong** [comment]
> @lyle-luan @iBCode @yuying2012 @dte2mdj @Changzw @vvlee
> 问题解决了
> 错误原因不是我之前想的没有触发layoutSubviews的问题
> 
> 问题是ScrollView的下拉滑动手势在正常使用过程中手指离开屏幕会缓慢回弹到顶端
> 但是突然切换页面会导致ScrollView突然回到顶端
> 这时计算会出现问题
> 
> 修改方式是在
> 
> ```
> - (void)scrollViewContentOffsetDidChange:(NSDictionary *)change
> ```
> 中加入判断
> 
> ```
>     if (self.state == MJRefreshStateRefreshing) {
>         // 暂时保留
>         if (self.window == nil) return;
> 
>         //解决手势中断带来的计算失误
>         if (self.scrollView.isDecelerating) {
>             // sectionheader停留解决
>             CGFloat insetT = - self.scrollView.mj_offsetY > _scrollViewOriginalInset.top ? - self.scrollView.mj_offsetY : _scrollViewOriginalInset.top;
>             insetT = insetT > self.mj_h + _scrollViewOriginalInset.top ? self.mj_h + _scrollViewOriginalInset.top : insetT;
>             self.scrollView.mj_insetT = insetT;
>             
>             self.insetTDelta = _scrollViewOriginalInset.top - insetT;
>         }
>         
>         return;
>     }
> ```

ipad 上用这种方案不行
