### ISSUE TITLE
pod下来，怎么没有文件夹了。是我cocoapods的问题吗

### ISSUE THREAD

**Issue by chenliangloveyou** [CoderMJLee/MJRefresh#1175]
如下图

![image](https://user-images.githubusercontent.com/10606555/41500493-d4b25c92-71c4-11e8-8264-8a5fa584a78d.png)

**Comment by CoderMJLee** [comment]
pod没有，我本来就没有配置文件夹哈

**Comment by chenliangloveyou** [comment]
j神，能不能把这个文件夹的配置加上呢，不然类太多，都找不到头问文件。

**Comment by kinarob** [comment]
你这名称取的6啊😂😂

发自我的 iPhone

在 2018年7月7日，下午1:34，MrChen <notifications@github.com<mailto:notifications@github.com>> 写道：


j神，能不能把这个文件夹的配置加上呢，不然类太多，都找不到头问文件。

**Comment by chenliangloveyou** [comment]
@kinarob 哈哈，有时间欢迎看看我库。😄
