### ISSUE TITLE
在iOS 11 及以上系统下，设置mj_header.ignoredScrollViewContentInsetTop = -20会导致下拉刷新控件mj_header显示不全，其余系统就不会有这个问题。

### ISSUE THREAD

**Issue by HZRZCW** [CoderMJLee/MJRefresh#1179]
如题，
- (void)viewWillLayoutSubviews
{
    [super viewWillLayoutSubviews];
    
    self.collectionView.mj_header.ignoredScrollViewContentInsetTop = -20;
}

**Comment by wolfcon** [comment]
Demo? 

没有复现这个问题
