### ISSUE TITLE
pod方式无法签出

### ISSUE THREAD

**Issue by peterhoucll** [CoderMJLee/MJRefresh#118]
我见文档中有写到可以通过pod 'MJRefresh'方式签出，发现不行
![1](https://cloud.githubusercontent.com/assets/12026808/7223293/87dfdd8c-e751-11e4-8354-d3b44454a160.png)
![2](https://cloud.githubusercontent.com/assets/12026808/7223295/88b37af2-e751-11e4-8f76-c2f73b6966ab.png)

**Comment by CoderMJLee** [comment]
使用新框架之前需要更新你的pod库，执行pod repo update，将pod服务器的最新信息更新到你的电脑本地，然后就OK了哈

**Comment by peterhoucll** [comment]
可以了。谢谢
