### ISSUE TITLE
上拉刷新设置  self.tableView.mj_footer.state = MJRefreshStateNoMoreData; 无效

### ISSUE THREAD

**Issue by HuangWeiDongiOS** [CoderMJLee/MJRefresh#1184]
MJRefreshAutoNormalFooter *footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        [weakSelf loadMoreData];
    }];

在网络请求回调中设置  self.tableView.mj_footer.state = MJRefreshStateNoMoreData; 失败。
尝试延迟设置        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
              self.tableView.mj_footer.state = MJRefreshStateNoMoreData;
        });
这样能成功。最新版本的

**Comment by wolfcon** [comment]
不要直接修改 state. 

使用如下代码
```swift
tableView.mj_footer.endRefreshingWithNoMoreData()
```
#1258
