### ISSUE TITLE
3.1.15版本以后，设置.state = MJRefreshStateNoMoreData;无效

### ISSUE THREAD

**Issue by MrBugDou** [CoderMJLee/MJRefresh#1185]
Pod 'MJRefresh' 更新到最新版本(3.1.15.3)以后，设置state=MJRefreshStateNoMoreData无效，这个问题我在起初升级到3.1.15就发现了，于是我退回了3.1.14，问题解决，最近有新项目，使用(3.1.15.3)时发现问题依然存在，没有解决。

**Comment by wolfcon** [comment]
不要直接修改 state. 

使用如下代码
```swift
tableView.mj_footer.endRefreshingWithNoMoreData()
```
#1258
