### ISSUE TITLE
在iOS11上突然出现了一个崩溃

### ISSUE THREAD

**Issue by Mingmingmew** [CoderMJLee/MJRefresh#1186]
![image](https://user-images.githubusercontent.com/16685324/43314608-01741b50-91c6-11e8-9a9b-989b56413b98.png)
![image](https://user-images.githubusercontent.com/16685324/43314632-140f329a-91c6-11e8-90cd-6002cc017422.png)
只要一初始化就崩溃了

**Comment by itdongbaojun** [comment]
更新最新版本，解决了这个问题
