### ISSUE TITLE
UICollectionView上拉加载block多次调用

### ISSUE THREAD

**Issue by luoqinzy** [CoderMJLee/MJRefresh#1188]
UICollectionView上拉加载的block会多次调用3-5次不等

**Comment by DemoCatKou** [comment]
__week 修饰下试试

**Comment by Yaou** [comment]
同样问题，可以说的更具体一些么？

> __week 修饰下试试

**Comment by Yaou** [comment]
@DemoCatKou 可以说的更具体一些么？

**Comment by wolfcon** [comment]
是否是AutoFooter? 默认情况下 AutoFooter 为可连续多次加载的.

**Comment by xiaotuofengfa** [comment]
解决： 设置 onlyRefreshPerDrag = NO就OK了
