### ISSUE TITLE
下拉刷新后上拉加载就失效了,不进回调了

### ISSUE THREAD

**Issue by wangdexter** [CoderMJLee/MJRefresh#1189]
第一次进入一个面的时候会自动刷新一下,这个时候上拉加载都是没有问题的,然后在这个页面下拉刷新一下,等再次上拉的时候就只能显示一页的数据,并显示已经全部加载完毕,其实有好几页数据的...

**Comment by wmc233** [comment]
请问是什么原因，我的现在也这样

**Comment by wolfcon** [comment]
demo?
