### ISSUE TITLE
关于state=MJRefreshStateNoMoreData无效

### ISSUE THREAD

**Issue by huangdougod** [CoderMJLee/MJRefresh#1192]
最新版本3.1.15，设置state=MJRefreshStateNoMoreData无效，往后退回几个版本还是有这个问题。。最后把这句代码延时执行1秒左右，才解决掉问题。但是依旧不理想。。。希望大佬能解决一下这个问题

**Comment by kCFNull** [comment]
不要在设置state=MJRefreshStateNoMoreData再调用endRefreshing（此会重置state为idle），检查一下你的代码有没有设置完nomoredata后再更改state

**Comment by wolfcon** [comment]
不要直接修改 state. 

使用如下代码
```swift
tableView.mj_footer.endRefreshingWithNoMoreData()
```

#1258
