### ISSUE TITLE
源码中刷新状态和刷新完成 状态为什么要去改变scrollView的contentInset,直接设置contentoffset不是一样可以达到效果吗

### ISSUE THREAD

**Issue by zhanghongdou** [CoderMJLee/MJRefresh#1193]
源码中刷新状态和刷新完成 状态为什么要去改变scrollView的contentInset,直接设置contentoffset不是一样可以达到效果吗

**Comment by zhanghongdou** [comment]
看了源码之后对于作者的这个写法很好奇,请作者能够解答我的疑惑,谢谢

**Comment by wolfcon** [comment]
你为什么不自己尝试一下呢? 你设置了 offset 在滑动了界面后, 会发生什么, 自己尝试一下就知道了

建议好好学习一下 ScrollView 的各项属性
