### ISSUE TITLE
上拉加载结束 tableview 闪动

### ISSUE THREAD

**Issue by 643824979** [CoderMJLee/MJRefresh#1195]
上拉加载结束 tableview 闪动

**Comment by weikeyan** [comment]
> 我这里也是上拉跳动，问题可能与 自动估算Cell高度有关，当设置的值相差较大时会出现明显闪动

解决了么

**Comment by dong09000** [comment]
本质上是 因为估算高度导致的 tableView的contentsize不确定性导致的 ，建议缓存cell高度展示。

**Comment by 643824979** [comment]
我能说我的cell高度是固定的
每次上来加载 网络结束之后停止刷新就会闪动

**Comment by XiangNanLi** [comment]
> > 我这里也是上拉跳动，问题可能与 自动估算Cell高度有关，当设置的值相差较大时会出现明显闪动
> 
> 解决了么

解决了

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by gleeeli** [comment]
已解决http://blog.sina.com.cn/s/blog_148dc6e7f0102xx46.html

**Comment by wangxj4268** [comment]
我也出现同样的问题，后来把MJRefreshBackNormalFooter改为MJRefreshAutoFooter就没有出现这个问题了
