### ISSUE TITLE
MJRefreshBackNormalFooter上拉刷新，tableview 向下偏移，cell 高度固定=屏幕高度

### ISSUE THREAD

**Issue by lyle-luan** [CoderMJLee/MJRefresh#1196]
iOS11
我的具体问题描述如下：
使用MJRefreshBackNormalFooter上拉刷新，松开手进入刷新状态，显示 Loading 和菊花的时候，tableview 向下偏移了一点距离，导致 Loading 显示不出来。
endRefreshing以后，tableview 也没有回到正确的位置上。
我的 cell 高度是固定的=屏幕的高度。
不知道各位有没有遇到这种情况，或者有什么手段可以调试定位问题，
希望大家不吝赐教。
多谢。

**Comment by lyle-luan** [comment]
因为不知道是否是因为其他的 Bug 造成的这个结果，所以暂时不 close了。

**Comment by z234009184** [comment]
@lyle-luan 不过正常的 cell 高度固定不等于屏幕高度 时 会出现上拉加载死循环。。。

**Comment by z234009184** [comment]
我添加了一行代码，可以暂时使用，希望作者尽快修复。。

```
if (self.state == MJRefreshStateRefreshing)  
{  
    if (self.scrollView.pageEnable == NO) return;  
    CGFloat refreshingOffset = [self happenOffsetY] + self.mj_h;  
    if (refreshingOffset != self.scrollView.mj_offsetY)  
    {  
        self.scrollView.mj_offsetY = [self happenOffsetY] + self.mj_h;  
    }  
    return;  
}
```

**Comment by DG1024** [comment]
我的这样修改之后,上拉加载完成之后,底部会出现正在加载中的提示,但是刷新成功之后,offset会自动定位到新出现的数据的最底部,这样的情况作者遇到过吗?

**Comment by DG1024** [comment]
上拉加载不能提示加载loading:     https://blog.csdn.net/u012796062/article/details/78498105

**Comment by wangxj4268** [comment]
> 因为不知道是否是因为其他的 Bug 造成的这个结果，所以暂时不 close了。

我的 cell 高度不是固定的，是采用的预估行高，也会出现你这样的问题，我把你的代码加在MJRefresh中，依旧没有解决问题，不知道你有没有遇到同样的问题呢？

**Comment by wolfcon** [comment]
#1294 #1245

**Comment by wolfcon** [comment]
Duplicate of #1196
