### ISSUE TITLE
老师，两个问题，1.footer问题  2.支持版本的问题

### ISSUE THREAD

**Issue by 102lianghui** [CoderMJLee/MJRefresh#120]
1.footer能不能自动弹回隐藏啊？像之前旧版本那样。要不然我这个项目变得好奇怪。下面多一个footer出来。
2.新版的MJRefresh支持iOS几到iOS几的版本？

**Comment by 102lianghui** [comment]
因为我这边是做证券的。如果我加载的时候要增加一个页码的label。怎办？

**Comment by CoderMJLee** [comment]
1.自动隐藏功能打算在2.0版本再整合了哈，你可以考虑用回0.0.1版本的，从github的release里面找
2.MJRefresh支持iOS6.0开始的系统
3.MJRefresh打算在2.0版本中增加自定义刷新功能。目前的话，你可以尝试修改框架源代码

**Comment by CNKCQ** [comment]
老师，0.0.1版本有新bug,当你下拉刷新的时候，下拉刷新还在加载时候的状态下，切换去到另外一个页面，会使下拉刷新回弹过多。

**Comment by gzucm** [comment]
上拉刷新控件自动弹回问题，pull request #164 可能满足你的需求。
