### ISSUE TITLE
上拉自动加载问题

### ISSUE THREAD

**Issue by 643824979** [CoderMJLee/MJRefresh#1201]
上拉自动加载会出现不停地自动上拉回调  陷入死循环

**Comment by yangqian111** [comment]
最新版本又坏了，之前修过，用回3.1.15可以解决问题

**Comment by maomaohang2013** [comment]
監聽滾動事件，滾動到底部就直接調用beginRefresh，不要用上拉自動加載，有bug

**Comment by Jayxiang** [comment]
确实，如果上拉不放开他会自动加载2-3次。松手又会加载一次。

**Comment by wolfcon** [comment]
Duplicate of #1009
