### ISSUE TITLE
tableView不是从顶部布局的时候，上啦加载后，reloadtableView会闪动

### ISSUE THREAD

**Issue by youeri3** [CoderMJLee/MJRefresh#1203]
tableView不是从顶部布局的时候，上啦加载后，reload TableView会跳动，跳动的距离就是tableView距离顶部的距离，比如tableView距离顶部100px,上啦加载后，tableView会跳动上啦刷新时位置后的100px距离

**Comment by Liyongcong** [comment]
你的解决了么

**Comment by zhigangwu** [comment]
同求解决方案

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by youeri3** [comment]
经试验，设置 self.tableView.estimatedRowHeight = xxxx; 有效，这样的话应该就是tableviewcell自动算高度的问题，  这里设置一个预估的高度，就行了

**Comment by saxon134** [comment]
> 已经解决。
> 参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

这个方案，我这边试了还是有问题，具体如下：

[UITableView.reloadData]
用这个方法刷新没有问题

[UITableView reloadSections:[NSIndexSet indexSetWithIndex:0] withRowAnimation:UITableViewRowAnimationNone];
用这个方法刷新，就会跳动，页面会先往上跳，再往下滚。

**Comment by Heisenbean** [comment]
if (@available(iOS 11.0, *)) {
        self.tableView.contentInsetAdjustmentBehavior= UIScrollViewContentInsetAdjustmentNever;
    }else {
        self.automaticallyAdjustsScrollViewInsets = NO;
    }

**Comment by wolfcon** [comment]
Duplicate of #1009
