### ISSUE TITLE
endRefreshingWithNoMoreData提示问题

### ISSUE THREAD

**Issue by TheifSeaMew** [CoderMJLee/MJRefresh#1204]
我们的APP每次加载数据的时候,加载5个,我判断,当加载的数据小于5个的时候,代表数据加载完成,没有更多数据,[self.tableView.mj_footer endRefreshingWithNoMoreData];
之后,下拉头部刷新,完成之后,再上拉加载更多数据的时候,还是提示没有更多数据,不能加载了.请问为什么?

**Comment by coderchou** [comment]
需要重置 **mj_footer** , 把 **mj_footer** 恢复为 **MJRefreshStateIdle** 状态
```objc
[self.tableView.mj_footer resetNoMoreData];
```
