### ISSUE TITLE
刷新无效

### ISSUE THREAD

**Issue by caimengnan** [CoderMJLee/MJRefresh#1207]
使用MJRefresh之前使用Swizzle替换系统的reloadData方法，刷新就没有效果了。我看MJRefresh里也是拦截系统的reloadData来进行替换，上面这种情况该如何避免和优化？

**Comment by CoderMJLee** [comment]
后期的版本，将取消对reloadData的Swizzle。你目前可以考虑注释掉那句Swizzle的代码
