### ISSUE TITLE
pod 'MJRefresh'出错

### ISSUE THREAD

**Issue by JummyHuang** [CoderMJLee/MJRefresh#121]
cd 到项目目录下，pod 'MJRefresh' 没用，显示的消息为

[!] Unknown command: `MJRefresh`
Did you mean: search

什么原因？

**Comment by CoderMJLee** [comment]
不是这么用的哈，建议先找找教程学学如何使用CocoaPods，比如这个：http://code4app.com/article/cocoapods-install-usage

**Comment by JummyHuang** [comment]
你好，我现在已经解决了。原来你在github上写的“pod 'MJRefresh’”意思是要放到podfile里面，然后执行pod install。我还以为直接在terminal里面pod ‘MJRefresh呢？希望能在项目readme上写清楚点，对于新手来说有点模糊。谢谢。

**Comment by CoderMJLee** [comment]
哈哈，所有github开源项目都只告诉你podfile怎么写的哈，因为CocoaPods的用法，不属于这个项目的范畴了

**Comment by JummyHuang** [comment]
嗯嗯，学习了。

发自我的 iPhone
