### ISSUE TITLE
关于MJRefresh控件占用内存较大，并且移除后内存不能释放的问题

### ISSUE THREAD

**Issue by saber623** [CoderMJLee/MJRefresh#1212]
最近在给公司项目做性能优化的时候，发现MJRefresh控件占用内存过大，每一个控件的占内存大小在500KB以上（iphone 7，ios10.3），而且刷新完成后移除控件，所占内存并没有得到释放，看了半天MJRefresh实现代码，也没看出问题在哪，网上也完全找不到有人问到相关的问题，只能来这里请教小码哥。。
以下是图文描述
<img width="657" alt="2018-09-27 6 21 39" src="https://user-images.githubusercontent.com/11836911/46140017-881dee00-c282-11e8-913a-e68e801fc99f.png">

打开App后，因为是一个可以左右滑动的列表视图，所以一次性创建了9个下拉刷新控件，和一个当前页面的上拉加载控件，可以看到此时MJRefresh占用内存已经很明显了

<img width="627" alt="2018-09-27 6 22 43" src="https://user-images.githubusercontent.com/11836911/46140041-923fec80-c282-11e8-9f85-185d5e707076.png">

这是进了一个子页面后，给当前列表添加了一个上拉加载控件，所以控件数变成了2，内存占用也相应的x2，然后我刷新完成后移除了这个控件，但是控件数依旧是2
- (void)removeFooterRefreshView
{
    objc_setAssociatedObject(self, &MJRefreshFooterKey, nil, OBJC_ASSOCIATION_ASSIGN);

    [self.mj_footer removeAllSubviews];
    [self.mj_footer removeFromSuperview];
    self.mj_footer = nil;
}
这个是我的移除方法，不知道哪里有问题

<img width="630" alt="2018-09-27 6 23 10" src="https://user-images.githubusercontent.com/11836911/46140058-9e2bae80-c282-11e8-858d-6179b974357b.png">

然后有一点让我奇怪的是，如果我替换上拉控件，按照刚才的实验，应该控件数变成3，但事实是控件数依然是2，只是瞬时控件数加1，我想这个应该是被替换的哪个控件，而且它占的内存已经被释放了，下面是图

实在是摸不着头脑，困扰一天了。

**Comment by CoderMJLee** [comment]
正常来说，只要你tableView是正常释放的，它们都会自动释放的。你可以尝试看看它们的dealloc有没有调用

**Comment by saber623** [comment]
是的，就是在tableView上拉加载完数据，将上拉控件移除后，这块占用的内存没有得到释放，不知道是什么原因。

移除的方法在这里
static const char MJRefreshHeaderKey = '\0';

- (void)removeFooterRefreshView
{
objc_setAssociatedObject(self, &MJRefreshFooterKey, nil, OBJC_ASSOCIATION_ASSIGN);

[self.mj_footer removeAllSubviews];
[self.mj_footer removeFromSuperview];
self.mj_footer = nil;
}

能帮我看看怎样移除才能释放释放这块内存吗？谢谢小码哥

**Comment by dong09000** [comment]
"打开App后，因为是一个可以左右滑动的列表视图，所以一次性创建了9个下拉刷新控件，和一个当前页面的上拉加载控件，可以看到此时MJRefresh占用内存已经很明显了."
1.我估计你是在一个scrollView上糊了9个tableView，并且进来同时调用 BeginRefresh？
2.个人建议你在scrollView上自己写个缓存池来控制 “显示与将要显示” 的tableView才调用刷新，
3. 当然2的做法也不是必须的，若是同个界面涉及到多个接口时候，需要设计该界面数据源管理类来实现   显示 tableView 的 数据的 UI层的可视刷新，未显示（即将显示）的tableView 的数据的 子线程更新。当界面显示时，发现没有数据才下拉刷新，使界面避免滚动频繁时候频繁调用。

**Comment by cddjr** [comment]
看看MJFooter被谁持有吧，也许循环引用了

**Comment by liuaaaddxiaoer** [comment]
- (void)willMoveToSuperview:(UIView *)newSuperview
{
    [super willMoveToSuperview:newSuperview];
    
    if (newSuperview) {
        // 监听scrollView数据的变化
        if ([self.scrollView isKindOfClass:[UITableView class]] || [self.scrollView isKindOfClass:[UICollectionView class]]) {
            [self.scrollView setMj_reloadDataBlock:^(NSInteger totalDataCount) {
                if (self.isAutomaticallyHidden) {
                    self.hidden = (totalDataCount == 0);
                }
            }];
        }
    }
}     是不是这个block循环引用了
