### ISSUE TITLE
iOS 10 crash 崩溃问题

### ISSUE THREAD

**Issue by dfkb2000** [CoderMJLee/MJRefresh#1214]
invalid mode 'kCFRunLoopCommonModes' provided to CFRunLoopRunSpecific - break on _CFRunLoopError_RunCalledWithInvalidMode to debug. This message will only appear once per execution

在iOS 10 系统 中，下拉刷新崩溃。好像和 estimatedRowHeight 有关系，具体原因还在进一步调试中，大家谁有好的思路吗，或者有谁也遇到过同样的问题吗

**Comment by columbusLGEN** [comment]
![mjrcrash](https://user-images.githubusercontent.com/14798133/46187151-c532c080-c314-11e8-8ded-a608e36f2edc.png)

**Comment by dong09000** [comment]
如果使用iOS8之后的自动计算高度，记得做一下高度缓存（也就是在cell显示后将cellH缓存在model或者一个字典数组里）。这样tableView显示后的contentSize会稳定下来，避免出现各种奇葩bug

**Comment by staticAlex** [comment]
问题不是MJ这边导致的吧,看调用栈是你那边的代码引起的崩溃
