### ISSUE TITLE
什么时候出纯swift

### ISSUE THREAD

**Issue by nizenyang** [CoderMJLee/MJRefresh#1215]

**Comment by dong09000** [comment]
Swift5 不向前兼容-。-，所以估计作者会在Swift5之后才会考虑出Swift版，毕竟Swift版的维护成本大多了

**Comment by cddjr** [comment]
> Swift5 不向前兼容-。-，所以估计作者会在Swift5之后才会考虑出Swift版，毕竟Swift版的维护成本大多了

swift3开始，变动就很小了。 估计是代码量太大，懒得改。“轮子能转即可”

**Comment by xxwang** [comment]
希望会出swift版
