### ISSUE TITLE
iOS11.4下拉刷新之后，tableviewcell点击不调用didSelectRowAtIndexPath

### ISSUE THREAD

**Issue by LMsowhat** [CoderMJLee/MJRefresh#1218]
下拉刷新之后，cell左边点击正常，右边部分点击没反应。cell的左边有一个imageview，点击imageview是可以正常触发didSelectRowAtIndexPath的，点击右边部分没有反应。刚进入页面也没有问题，可以正常点击触发，就是下拉刷新之后出现的这个现象，莫名其妙～

**Comment by JackZhoujian** [comment]
我感觉应该是手势冲突了

On Oct 12, 2018, at 3:07 PM, LMsowhat <notifications@github.com<mailto:notifications@github.com>> wrote:

之后

**Comment by LMsowhat** [comment]
页面没有添加任何手势，只有一个tableview

**Comment by JackZhoujian** [comment]
你有没有Scrollview


On Oct 12, 2018, at 3:13 PM, LMsowhat <notifications@github.com<mailto:notifications@github.com>> wrote:


页面没有添加任何手势，只有一个tableview

**Comment by LMsowhat** [comment]
整个页面的结构是一个navigationcontroller，下面是viewcontroller，下面是tableview。没有其他Scrollview。下拉刷新之后，出现上述问题，但是稍微滚动一下tableview，哪怕一点点，只要滚动一下，就又好使了

**Comment by LMsowhat** [comment]
viewcontroller是继承自己定义的一个baseviewcontroller，baseviewcontroller里面没有添加页面或者手势的操作，而且这个问题是个别viewcontroller出现的问题，其他有的viewcontroller也是继承baseviewcontroller，也是整个页面只有tableview，但是没有这个问题😄

**Comment by JackZhoujian** [comment]
我看到你的代码，我没看到你的刷新开始调用，以及加载后的数据模型数组的变化；另外你自己定制的cell，应该检查一下。我现在也无法判断，因为我当初是手势冲突问题

On Oct 12, 2018, at 3:24 PM, LMsowhat <notifications@github.com<mailto:notifications@github.com>> wrote:


`//
// MessageListViewController.m
// LilyOnlineeducation
//
// Created by liwenhua on 2018/5/3.
// Copyright © 2018年 liwenhua. All rights reserved.
//
#import "HttpApplication.h"
#import "MessageModel.h"
#import "MessageListViewController.h"
#import "MessageListCell.h"
#import "MessageDetailController.h"
#import "MJRefresh.h"

@interface<https://github.com/interface> MessageListViewController ()<UITableViewDelegate,UITableViewDataSource,UIGestureRecognizerDelegate>

// strong
/** mianTableView */
@Property<https://github.com/Property> (strong, nonatomic) UITableView * mainTableView;

// strong
/** data */
@Property<https://github.com/Property> (strong, nonatomic) NSMutableArray * dataSource;

// strong
/** parameters */
@Property<https://github.com/Property> (strong, nonatomic) NSMutableDictionary * parameters;

@EnD<https://github.com/EnD>

@implementation<https://github.com/implementation> MessageListViewController

  *   (void)viewDidLoad {
[super viewDidLoad];

[self.view addSubview:self.mainTableView];
}

-(void)viewWillAppear:(BOOL)animated{

[super viewWillAppear:animated];

UIButton *leftButton = [UIButton buttonWithType:UIButtonTypeCustom];
leftButton.frame = CGRectMake(0, 0, 20, 20);
[leftButton setImage:[UIImage imageNamed:@"icon_back_lessonDetail"] forState:UIControlStateNormal];
[leftButton addTarget:self action:@selector(backClick) forControlEvents:UIControlEventTouchUpInside];
UIBarButtonItem *left = [[UIBarButtonItem alloc] initWithCustomView:leftButton];
[self.navigationItem setLeftBarButtonItem:left];

self.navigationItem.title = @"我的消息";

[self setMessageListWithHttptype:NSHttpTypeNew];


}

  *   (void)viewDidAppear:(BOOL)animated{
[super viewDidAppear:animated];
if ([self.navigationController respondsToSelector:@selector<https://github.com/selector>(interactivePopGestureRecognizer)]) {
self.navigationController.interactivePopGestureRecognizer.enabled = YES;
}
}

-(UITableView *)mainTableView{

if (!_mainTableView) {
    _mainTableView = [[UITableView alloc] initWithFrame:CGRectMake(0, 0, kWidth, kHeight) style:UITableViewStyleGrouped];
    _mainTableView.backgroundColor = UIColorFromRGBA(0xf7f7f7, 1.0);
    _mainTableView.delegate = self;
    _mainTableView.dataSource = self;
    _mainTableView.showsHorizontalScrollIndicator = NO;
    _mainTableView.showsVerticalScrollIndicator = NO;
    _mainTableView.tableFooterView = [UIView new];
    _mainTableView.estimatedRowHeight = 0.;
    _mainTableView.estimatedSectionFooterHeight = 0.;
    _mainTableView.estimatedSectionHeaderHeight = 0.;

    _mainTableView.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{

        [self setMessageListWithHttptype:NSHttpTypeNew];
    }];
    MJRefreshAutoNormalFooter *footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{

        [self setMessageListWithHttptype:NSHttpTypeMore];
    }];
    [footer setTitle:@"已经全部加载完毕" forState:MJRefreshStateNoMoreData];

    _mainTableView.mj_footer = footer;

}
return _mainTableView;


}

-(NSMutableArray *)dataSource {

if (!_dataSource) {
    _dataSource = [NSMutableArray new];
}
return _dataSource;


}

-(NSMutableDictionary *)parameters {

if (!_parameters) {
    _parameters = [NSMutableDictionary new];
    _parameters[kCurrentController] = self;
    _parameters[@"page"] = @"0";
    _parameters[@"size"] = @"10";
    _parameters[@"search"] = @[];
    NSMutableDictionary *sorts = [NSMutableDictionary new];
    sorts[@"orderType"] = @"desc";
    sorts[@"orderField"] = @"id";
    _parameters[@"sorts"] = @[sorts];

    self.pageIndex = 0;
}
return _parameters;


}

#pragma mark HttpRequest

  *   (void)setMessageListWithHttptype:(NSHttpType)httpType{

switch (httpType) {
case NSHttpTypeNew:
if (self.dataSource) {
[self.dataSource removeAllObjects];
}
self.pageIndex = 0;

      break;
  case NSHttpTypeMore:
      self.pageIndex += 1;

      break;
  case NSHttpTypeCategory:

      break;
  case NSHttpTypeSort:

      break;

  default:
      break;


}
self.parameters[@"page"] = [NSString stringWithFormat:@"%ld",self.pageIndex];

[LILYAPI onHttpCode:kGetMessageList WithParameters:_parameters];
}

  *   (void)uploadMessageList:(id)reponse{

if ([reponse[@"data"][@"content"] isKindOfClass:[NSNull class]] || [reponse[@"data"][@"content"] count] == 0) {

  self.nodataView.hidden = NO;


}else{
self.nodataView.hidden = YES;

  [self.mainTableView.mj_header endRefreshing];


// [self.mainTableView.mj_footer endRefreshing];

    NSArray *data = [NSArray new];

    data = reponse[@"data"][@"content"];

    //判断数据是否加载完
    if (data.count < [self.parameters[@"size"] integerValue]) {

        [self.mainTableView.mj_footer endRefreshingWithNoMoreData];
    }
    for (NSDictionary *dict in data) {

        [self.dataSource addObject:dict];
    }
}
[self.mainTableView reloadData];


}

  *   (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch
{
if ([NSStringFromClass([touch.view class]) isEqualToString:@"UITableViewCellContentView"]) {
return NO;
}
return YES;
}

#pragma mark TableViewDataSource

-(NSInteger)numberOfSectionsInTableView:(UITableView *)tableView{

return 1;


}

-(NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section{

return self.dataSource.count;


}

-(CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{

return kHeight * 60 / 667;


}

-(CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section{

return 0.5;


}

-(CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section{

return 0.5;


}

-(UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section{

return [UIView new];


}

-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section{

return [UIView new];


}

#pragma mark TableViewDelegate

-(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath{

static NSString *CellIdentifier =@"MessageListCellIdentifier";

MessageListCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];

if (!cell) {

    cell = [[NSBundle mainBundle] loadNibNamed:@"MessageListCell" owner:nil options:nil].lastObject;


// cell.selectionStyle = UITableViewCellSelectionStyleNone;

}

MessageModel *model = [MessageModel mj_objectWithKeyValues:self.dataSource[indexPath.row]];

cell.model = model;

return cell;


}

-(NSIndexPath *)tableView:(UITableView *)tableView willSelectRowAtIndexPath:(NSIndexPath *)indexPath{

return indexPath;


}

-(void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{

[tableView deselectRowAtIndexPath:indexPath animated:YES];


//
// MessageModel *model = [MessageModel mj_objectWithKeyValues:self.dataSource[indexPath.row]];
//
// MessageDetailController *detail = [MessageDetailController new];
//
// detail.model = model;
//
// [self.navigationController pushViewController:detail animated:YES];
}

@EnD<https://github.com/EnD>
`

**Comment by CQXfly** [comment]
你好  我们同样发现会有这个问题，请问有解决了吗

**Comment by wolfcon** [comment]
请上传一个Demo

**Comment by HeYming** [comment]
将cell的宽高设置为整数可以解决。ceil(f), floor(f)

**Comment by wolfcon** [comment]
Duplicate of #1234
