### ISSUE TITLE
已经全部加载（endRefreshingWithNoMoreData）控件显示不滞留tableView底部

### ISSUE THREAD

**Issue by BruceWee01** [CoderMJLee/MJRefresh#1219]
你好，为什么调用endRefreshingWithNoMoreData方法必须延迟调用呢，不然显示“已经全部加载”了但箭头还在 还有就是显示“已经全部加载”文案了 但是控件没有滞留屏幕底部，而是跑出了屏幕之外，需要上拉才能看得见

**Comment by JackZhoujian** [comment]
你现在的操作应该在dispatch main  队列里操作的，另外，你最后的end 应该在服务器返回数据后，才操作的


On Oct 12, 2018, at 4:38 PM, BruceWee01 <notifications@github.com<mailto:notifications@github.com>> wrote:


你好，为什么调用endRefreshingWithNoMoreData方法必须延迟调用呢，不然显示“已经全部加载”了但箭头还在 还有就是显示“已经全部加载”文案了 但是控件没有滞留屏幕底部，而是跑出了屏幕之外，需要上拉才能看得见

**Comment by BruceWee01** [comment]
@JackZhoujian 

上拉数据请求成功 {

               [self.tableView reloadData];
                [self.tableView.mj_footer endRefreshing];

                NSLog(@"currentThread == %@", [NSThread currentThread]);
                
                if (没有数据返回了) {

                    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                        [self.tableView.mj_footer endRefreshingWithNoMoreData];
                    });
                }
}

线程打印信息： currentThread == <NSThread: 0x600000068440>{number = 1, name = main}

上面这么写有什么问题呢？“已经全部加载”并不滞留tableView底部，需要自己调整偏移量还是footerView的尺寸呢？

**Comment by cddjr** [comment]
估计是你endRefreshing后又马上endRefreshingWithNoMoreData导致，  重复调用了

**Comment by BruceWee01** [comment]
@cddjr 
 [self.tableView.mj_footer endRefreshingWithNoMoreData]; 是延时调用的 而且设置了5s都还是这样的问题

**Comment by cddjr** [comment]
> @cddjr
> [self.tableView.mj_footer endRefreshingWithNoMoreData]; 是延时调用的 而且设置了5s都还是这样的问题

你没弄懂我的意思， 我是指endRefreshing和endRefreshingWithNoMoreData 这两个是重复的相同操作。 即，一个begin对应一个end操作，你的估计是一个begin对应两次end导致的异常。

**Comment by BruceWee01** [comment]
@cddjr 
应该和这个无关，源码
// 根据状态来设置属性
    if (state == MJRefreshStateNoMoreData || state == MJRefreshStateIdle) {
        // 刷新完毕
        if (MJRefreshStateRefreshing == oldState) {
            [UIView animateWithDuration:MJRefreshSlowAnimationDuration animations:^{
                self.scrollView.mj_insetB -= self.lastBottomDelta;
                
                // 自动调整透明度
                if (self.isAutomaticallyChangeAlpha) self.alpha = 0.0;
            } completion:^(BOOL finished) {
                self.pullingPercent = 0.0;
                
                if (self.endRefreshingCompletionBlock) {
                    self.endRefreshingCompletionBlock();
                }
            }];
        }
        
        CGFloat deltaH = [self heightForContentBreakView];
        // 刚刷新完毕
        if (MJRefreshStateRefreshing == oldState && deltaH > 0 && self.scrollView.mj_totalDataCount != self.lastRefreshCount) {
            self.scrollView.mj_offsetY = self.scrollView.mj_offsetY;
        }
    } else if (state == MJRefreshStateRefreshing) {
        // 记录刷新前的数量
        self.lastRefreshCount = self.scrollView.mj_totalDataCount;
        
        [UIView animateWithDuration:MJRefreshFastAnimationDuration animations:^{
            CGFloat bottom = self.mj_h + self.scrollViewOriginalInset.bottom;
            CGFloat deltaH = [self heightForContentBreakView];
            if (deltaH < 0) { // 如果内容高度小于view的高度
                bottom -= deltaH;
            }
            self.lastBottomDelta = bottom - self.scrollView.mj_insetB;
            self.scrollView.mj_insetB = bottom;
            self.scrollView.mj_offsetY = [self happenOffsetY] + self.mj_h;
        } completion:^(BOOL finished) {
            [self executeRefreshingCallback];
        }];
    }

**Comment by xushixun16** [comment]
@BruceWee01 
是不是用了contentInset做去黏性操作？

**Comment by wolfcon** [comment]
`endRefreshing` 和 `endRefreshingWithNoMoreData ` 不要一起使用. 
`endRefreshingWithNoMoreData` 包含了 `endRefreshing` 的功能,

**Comment by CaiChenghan** [comment]
我的即使没有重复调用方法，直接使用 ```endRefreshingWithNoMoreData``` 方法，底部无更多数据控件依旧无法显示。

**Comment by CaiChenghan** [comment]
@wolfcon 有点懵逼，如果使用 ```MJRefreshAutoNormalFooter``` 来调用 ```endRefreshingWithNoMoreData``` 方法，则能正确显示这个无数据视图。如果集成自 ```MJRefreshBackFooter``` 的，则不能展示了。我需要重写哪个方法吗？

**Comment by wolfcon** [comment]
BackFooter 是基础类, 没有任何东西的, 只提供标准功能. 是空白的... 你想展示什么自己自定义.
