### ISSUE TITLE
传统上拉执行多次问题？

### ISSUE THREAD

**Issue by codemzy** [CoderMJLee/MJRefresh#122]
[_ShowTable addLegendFooterWithRefreshingBlock:^{
        [weakSelf loadMoreData];
        NSLog(@"1");
    }];

当我滑动到底部，log打出3个1，执行了多次，不是应该执行一次吗

**Comment by CoderMJLee** [comment]
有没有试试最新的代码？第三方框架是每隔几天就会更新一次的

**Comment by codemzy** [comment]
找到问题了，刷新scetion的时候有问题，reloaddata没问题的。你可以看看。晚上在看看
