### ISSUE TITLE
适配iPhone X  顶部没有导航栏的时候 刷新控件被刘海挡住了

### ISSUE THREAD

**Issue by tc1993** [CoderMJLee/MJRefresh#1220]
请问下怎么适配iPhone X啊？就是在没有导航栏的时候，下拉刷新的文字被刘海挡住了。我看京东和淘宝的做法是在iPhone X上加大上面下拉的展示区域，mjrefresh应该怎么设置呢？还是需要去改源码？有没有朋友遇到过啊？

**Comment by xudehuai** [comment]
可以直接自定义一个iPhoneXHeader，源码从MJRefresh拷贝出来，修改header的高度即可

**Comment by tc1993** [comment]
好的 谢谢。昨晚上看到了，已经修改了

**Comment by ghostlordstar** [comment]
继承一下就好了，为啥要拷源码？

**Comment by sun2483968** [comment]
请问你具体如何解决的？ 看的哪个问题做的参考

**Comment by sun2483968** [comment]
@tc1993

**Comment by wolfcon** [comment]
#1151
