### ISSUE TITLE
关于我使用中遇到的崩溃

### ISSUE THREAD

**Issue by xiaotuofengfa** [CoderMJLee/MJRefresh#1221]
我的代码在点击home键退到后台，继续玩其他的app，一会再次回到我的app中会出现这个错误
#import "UIScrollView+MJExtension.h"里面的
这个方法
- (void)setMj_insetT:(CGFloat)mj_insetT
{
    UIEdgeInsets inset = self.contentInset;
    inset.top = mj_insetT;
#ifdef __IPHONE_11_0
    if (respondsToAdjustedContentInset_) {
        inset.top -= (self.adjustedContentInset.top - self.contentInset.top);
    }
#endif
    self.contentInset = inset;
}
中的这一行
 self.contentInset = inset;
，抛出的错误是  
Thread1: EXC_BAD_ACCESS(code=1,address=0x)
大神可知为什么？

**Comment by wolfcon** [comment]
Thread 1 的堆栈报错能发全一点吗?

**Comment by ieliwb** [comment]
请问怎么解决，有人知道吗

**Comment by wolfcon** [comment]
你的 App 的部分资源被清理掉了. 你可能需要考虑应用所占用内存的问题? 只是一个思路, 需要其他证据佐证, 因为你提供的不全, 无法完整的判断
