### ISSUE TITLE
UICollectionview瀑布流 mj_footer位置不正确，翻页越多偏差越大

### ISSUE THREAD

**Issue by guchungang** [CoderMJLee/MJRefresh#1222]
UICollectionview瀑布流 mj_footer位置不正确，翻页越多偏差越大

我往下滑动越多，正在加载更多数据的位置越往下靠，可能是因为瀑布流位置没有计算正确，杰哥有时间可以看下

**Comment by Gitool** [comment]
已经解决。
参看[https://www.cnblogs.com/cchHers/p/9883646.html]

**Comment by WXXXXH** [comment]
这个解决很low，直接把预估高度设置一个最大值就行了

**Comment by wolfcon** [comment]
Demo 最好来一个
