### ISSUE TITLE
空白tableView 底部的上拉加载更多一直显示在底部

### ISSUE THREAD

**Issue by Goallying** [CoderMJLee/MJRefresh#1224]
![d4a77b52-f295-48a9-968f-55b03b1b8c08](https://user-images.githubusercontent.com/12438493/47775971-30185280-dd2c-11e8-9a5a-11384177101b.png)
iOS 10 系统， 怎么解决？

**Comment by Ezreal-lup** [comment]
我也遇到这个问题了，请问你最后怎么解决这个问题了

**Comment by Ezreal-lup** [comment]
> ![d4a77b52-f295-48a9-968f-55b03b1b8c08](https://user-images.githubusercontent.com/12438493/47775971-30185280-dd2c-11e8-9a5a-11384177101b.png)
> iOS 10 系统， 怎么解决？

请问你这个问题解决了吗？我也遇到了，也是一头雾水

**Comment by YikuCCCCCC** [comment]
> ![d4a77b52-f295-48a9-968f-55b03b1b8c08](https://user-images.githubusercontent.com/12438493/47775971-30185280-dd2c-11e8-9a5a-11384177101b.png)
> iOS 10 系统， 怎么解决？

大兄弟，你这个问题解决了吗，我也碰到了，发现时TableView的contentOfSize不是cell的高度总和，当cell占不满一屏时conentOfSize会等于tabelview的高度

**Comment by YikuCCCCCC** [comment]
> ![d4a77b52-f295-48a9-968f-55b03b1b8c08](https://user-images.githubusercontent.com/12438493/47775971-30185280-dd2c-11e8-9a5a-11384177101b.png)
> iOS 10 系统， 怎么解决？

老铁，我解决了。
你的tabelview是不是把searchBar设置成了tabelview的tableHeaderView

**Comment by YikuCCCCCC** [comment]
> > ![d4a77b52-f295-48a9-968f-55b03b1b8c08](https://user-images.githubusercontent.com/12438493/47775971-30185280-dd2c-11e8-9a5a-11384177101b.png)
> > iOS 10 系统， 怎么解决？
> 
> 请问你这个问题解决了吗？我也遇到了，也是一头雾水

老铁，要不要试试我的方法

**Comment by AgoniNemo** [comment]
你们是怎么弄的   我那个奇葩产品就需要这种效果

**Comment by wolfcon** [comment]
```swift
tableView.mj_header.isAutomaticallyChangeAlpha = true
```

**Comment by AgoniNemo** [comment]
@wolfcon isAutomaticallyChangeAlpha这个属性是不是没有了

**Comment by AgoniNemo** [comment]
```
MJRefreshBackNormalFooter *footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
     
    }];
    footer.automaticallyChangeAlpha = YES;
   _tableView.mj_footer = footer;
```
