### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xc000000000000116> {length = 2, path = 1 - 0} keyboard_arrow_up

### ISSUE THREAD

**Issue by wangjunhua1** [CoderMJLee/MJRefresh#1227]
<img width="861" alt="image" src="https://user-images.githubusercontent.com/11474284/48534799-2f62ed00-e8e4-11e8-8f19-da4b32f60f67.png">

**Comment by wangjunhua1** [comment]
杰哥 我升级到3.1.15.7 线上还是有这个crash

**Comment by wolfcon** [comment]
`flowLayout`? `Invalidate` first before reuse or changing.
