### ISSUE TITLE
UICollectionView使用mj_header首次加载数据时，Cell会动画显示。

### ISSUE THREAD

**Issue by Iibcore** [CoderMJLee/MJRefresh#1228]
![qq20181117-090239-hd](https://user-images.githubusercontent.com/28803151/48654425-a5cc3000-ea47-11e8-8d94-6155967d1090.gif)

**Comment by Iibcore** [comment]
不想让Cell有显示动画，怎么处理。

- (void)request {
    [self.collectionView.mj_header beginRefreshing];
}

- (void)refresh {
    [self.collectionView reloadData];
    [self.collectionView.mj_header endRefreshing];
}

**Comment by sunzhongliangde** [comment]
你调用[self.collectionView.mj_header beginRefreshing];这个方法，实际上是手动触发MJ下拉刷新，
你可以把这个方法换成你实际的网络请求，然后在reloadData就好了
