### ISSUE TITLE
setMj_footer: 导致的 crash

### ISSUE THREAD

**Issue by tianxiawoyougood** [CoderMJLee/MJRefresh#1229]
**描述bug**
清晰简单地描述这个bug是啥

**必现/偶发?**
必现/偶发

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
![image](https://user-images.githubusercontent.com/9163388/48756837-aa0d7d00-ecd5-11e8-93c8-0b9f81cb30b0.png)

**运行环境**
 - iPhone6s
 - iOS 9.2
 - Xcode未知

**额外的**
最好能提供出现bug的Demo

**Comment by tianxiawoyougood** [comment]
![image](https://user-images.githubusercontent.com/9163388/48756979-361fa480-ecd6-11e8-9101-23892e0dec7d.png)
调用的代码是这样的

**Comment by wolfcon** [comment]
方便来个 Demo 吗?
