### ISSUE TITLE
上拉刷新出现的bug

### ISSUE THREAD

**Issue by IosForZhang** [CoderMJLee/MJRefresh#123]
MJ大神，您好，我创建的tableView不是充满全屏的，大概是宽200，高200，在上拉刷新更新数据的时候，如果鼠标光标出了tableView范围的时候再松手，我的数据是下载报错的，显示=======“*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds for empty array'
*** First throw call stack:”=======，但是鼠标如果在tableView范围内松手，就没问题。不知道问题出在哪边，是要改下里面的什么属性么？

**Comment by CoderMJLee** [comment]
这个是数组越界，数据处理问题哈。跟刷新框架是没有关系的。你重点关注下代码中对数组的存取操作，比如这样的：
```objc
self.data[index]
```

**Comment by IosForZhang** [comment]
哦哦，我下的不是最新版本，用的之前的老版本，下了你最新版本之后就没问题了，默默地问下，怎么去除上拉刷新，“点击加载更多”那个按钮哈？需求里功能不需要那么强大，上拉刷新就ok了。麻烦了。

**Comment by CoderMJLee** [comment]
Sorry哈，暂时不好去掉哦。。。新版本我把旧功能踢掉了。准备在2.0版本中把旧功能弄回来。或者你从github的release中下载0.0.1版本

**Comment by IosForZhang** [comment]
哦哦，好的，谢啦。。。
