### ISSUE TITLE
UIScrollView+MJExtension中self.contentInset = inset闪退

### ISSUE THREAD

**Issue by cdpenggod** [CoderMJLee/MJRefresh#1231]
3.1.15.7版本，今天刚pod更新的最新版本，还是崩溃出问题，线上很多了，麻烦解决下

![6bbd842e-6451-4c98-84b9-70149b26336b](https://user-images.githubusercontent.com/11714870/49007846-6b7d3400-f1a7-11e8-9614-1e9feb2c5a9d.png)

**Comment by linbx08** [comment]
怎么解决的, 我也遇到了

**Comment by wolfcon** [comment]
能否上传一份 Demo? @cdpenggod @linbx08

**Comment by kinarob** [comment]
@cdpenggod  @linbx08 设置你的 `invalidateFlowLayoutDelegateMetrics = YES` 就OK，这是苹果的bug。

**Comment by wolfcon** [comment]
@cdpenggod @linbx08 是不是切换 CollectionView 数据源的时候崩的啊?
在切换数据源后首先 invalidateLayout

**Comment by linbx08** [comment]
@wolfcon 我换了原生的刷新不崩溃了, 赶项目没有细查, 下次再排查下, 希望有大神上传demo😆

**Comment by ZClee128** [comment]
这个问题没有解决呀，我还是遇到这个问题

**Comment by wolfcon** [comment]
@ZClee128 传个 demo?
