### ISSUE TITLE
特定条件下, 下拉刷新导致cell不响应selectRow方法

### ISSUE THREAD

**Issue by tristanSIF** [CoderMJLee/MJRefresh#1234]
一个viewController, 加上tableView, 设置mj_header, 刷新事件就是停止和reload
可能类似于 [#843](https://github.com/CoderMJLee/MJRefresh/issues/843)  [#1218](https://github.com/CoderMJLee/MJRefresh/issues/1218)
特定条件:
不是所有机型都出问题, 目前遇到: 
模拟器iPhoneXS MAX iOS12.1
真机6P 12.0

调试了下发现cell触发了touchesBegan, 但是很快就touchesCancelled没有正常end导致点击无效

1. vc在navigationController里( PUSH或者rootViewController)
2. tableView只有两个数据
3. cell高度为69.333    (也有一些其它高度比如71.333等等
4. 下拉触发refresh
5. 点击 `cell`, 不触发 `didSelectRow`

下面是vc代码, 下拉刷新后点击无效(代码被格了样式, 能看懂就好
使用系统UIRefreshControl替代MJRefresh没问题
```objc
#import "ViewController.h"
#import <MJRefresh/MJRefresh.h>

@interface ViewController ()<UITableViewDelegate, UITableViewDataSource>
@property (nonatomic, strong) UITableView *tableView;
@end

@implementation ViewController
- (void)viewDidLoad {
    [super viewDidLoad];
    _tableView = [[UITableView alloc] init];
    [self.view addSubview:_tableView];
    _tableView.delegate = self;
    _tableView.dataSource = self;
    _tableView.translatesAutoresizingMaskIntoConstraints = NO;
    _tableView.tableFooterView = [UIView new];
    [NSLayoutConstraint activateConstraints:@[
                                              [_tableView.topAnchor constraintEqualToAnchor:self.view.topAnchor],
                                              [_tableView.leftAnchor constraintEqualToAnchor:self.view.leftAnchor],
                                              [_tableView.rightAnchor constraintEqualToAnchor:self.view.rightAnchor],
                                              [_tableView.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor],
                                              ]];
    _tableView.mj_header = [MJRefreshHeader headerWithRefreshingTarget:self refreshingAction:@selector(refresh)];
    [self refresh];
}

- (void)refresh
{
    [self.tableView.mj_header endRefreshing];
    [self.tableView reloadData];
}

#pragma mark TableViewDelegate
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 2;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    return [UITableViewCell new];
}

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    return 69.3333; // 69.3333  71.33333 etc.
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    
}
@end
```

**Comment by tristanSIF** [comment]
2018-11-27 14:43:40.681003+0800[50698:1310292] touch began
2018-11-27 14:43:40.682096+0800[50698:1310292] tableView contentOffset Changed To: -88.000000
2018-11-27 14:43:40.682287+0800[50698:1310292] touch canceleed


再观察了下, 下拉刷新之后, 点击cell会触发tableView contentOffset的变化 (????), KVO监控到值变化

**Comment by tristanSIF** [comment]
2018-11-27 14:52:39.472420+0800[50994:1323779] touch began
2018-11-27 14:52:39.473230+0800[50994:1323779] will dragging
2018-11-27 14:52:39.473468+0800[50994:1323779] tableView contentOffset Changed To: -88.000000
2018-11-27 14:52:39.473662+0800[50994:1323779] touch canceled


再观察了下, 下拉刷新之后, 点击cell, 会触发pan手势, 触发tableView的drag, 导致cell的点击事件被取消掉

**Comment by CQXfly** [comment]
遇到同样的问题，cell 个数不满一屏时会发生

**Comment by HebeTienCoder** [comment]
这个问题我也碰到了，无法解决

**Comment by wolfcon** [comment]
请上传一个你们的 Demo.

**Comment by HeYming** [comment]
将cell的宽高设置为整数可以解决。ceil(f), floor(f)

**Comment by ericyao11** [comment]
将cell的宽高设置为整数可以解决。ceil(f), floor(f)

**Comment by GeraldAs** [comment]
请问这个问题解决了吗？

**Comment by ericyao11** [comment]
> 请问这个问题解决了吗？

手动滑动0.01像素的距离，暂时解决

**Comment by GeraldAs** [comment]
> > 请问这个问题解决了吗？
> 
> 手动滑动0.01像素的距离，暂时解决

是手动滑的吗？还是自己在刷新完成后调用的方法？手动滑体验太差了

**Comment by ericyao11** [comment]
> > > 请问这个问题解决了吗？
> > 
> > 
> > 手动滑动0.01像素的距离，暂时解决
> 
> 是手动滑的吗？还是自己在刷新完成后调用的方法？手动滑体验太差了

刷新完成后手动滑0.01

**Comment by GeraldAs** [comment]
> > > > 请问这个问题解决了吗？
> > > 
> > > 
> > > 手动滑动0.01像素的距离，暂时解决
> > 
> > 
> > 是手动滑的吗？还是自己在刷新完成后调用的方法？手动滑体验太差了
> 
> 刷新完成后手动滑0.01

手动滑动0.01（采用代码改偏移）后是不是也需要点击第二下之后才能触发didSelect方法，我这边目前是这样子的

**Comment by whf5566** [comment]
> 请问这个问题解决了吗？

将scrollview的panGestureRecognizer的cancelsTouchesInView属性设置为false后，可以点击

**Comment by GeraldAs** [comment]
> > 请问这个问题解决了吗？
> 
> 将scrollview的panGestureRecognizer的cancelsTouchesInView属性设置为false后，可以点击

谢谢您的帮助，这个方法在我这边是可以解决的，非常感谢

**Comment by wolfcon** [comment]
我一直没能复现出这个 bug. 有能 100% 复现出来的麻烦写个 Demo, 给出特定环境.

**Comment by liuaaaddxiaoer** [comment]
确实有这个bug 懵逼了一天给调好了

**Comment by fuyunmanbu** [comment]
我也遇到了这个问题，警告慢慢的调试，发现，我是由于设置
tableView.contentInset = UIEdgeInsets(top: 0.5, left: 0, bottom: 0, right: 0)

top为0.5导致，我设置成1就好了

tableView.contentInset = UIEdgeInsets(top: 1, left: 0, bottom: 0, right: 0)

其次在模拟器上没有发现此问题。

**Comment by jianqingyu** [comment]
最终解决方案是（将scrollview的panGestureRecognizer的cancelsTouchesInView属性设置为false后，可以点击）是这种吗？还是希望大佬可以修正一下

**Comment by XanderXu** [comment]
我也遇到这个问题了，下拉刷新后点击 cell 无响应。iPhoneXS MAX iOS13.1.3
cell 的 hitTest 方法可以正常返回，之后无响应。
根据上面说的 cell 高度解决方案，我测试了一下，重要的不是整数问题，而是 cell 的高度是根据内容自适应的。cell 内部有两个 label 浮动高度导致的，将其中一个 label 高度设置为固定后，另一个浮动，最终 cell 高度仍然是小数，但可以点击了。

**Comment by XanderXu** [comment]
我也遇到了这个问题：iPhoneXS MAX iOS13.1.3
经过测试，这个应该是 tabelViewCell 高度导致的问题，在 @3X 手机上，当 cell 高度为 x.3333 时，reload 之后 cell 无法点击。cell 高度为整数或 x.667 时，可正常点击。
在@2X 手机上，cell 高度只能是整数或者 x.5，均无此问题。

这个问题在 tableView 左滑删除后，也会出现，应该并不是 MJRefresh 的问题。
