### ISSUE TITLE
如何移除刷新控件

### ISSUE THREAD

**Issue by liusr** [CoderMJLee/MJRefresh#1235]
新版里如何移除刷新控件呢

**Comment by wolfcon** [comment]
介绍详细点?

**Comment by 0x1306a94** [comment]
@liusr self.tableView.mj_header = nil

**Comment by kinarob** [comment]
@liusr `removeFromSuperview` 不能解决你的问题吗？

**Comment by tounaobun** [comment]
self.tableView.mj_header?.removeFromSuperview()
self.tableView.layoutIfNeeded()
