### ISSUE TITLE
我已经调用了head ending  但是下拉刷新不会弹回，而且一直刷新就会一直下移，上拉加载正常

### ISSUE THREAD

**Issue by afskalsfk** [CoderMJLee/MJRefresh#1239]
如题  请指点

**Comment by mafangchao** [comment]
我也遇到了这个问题，怎么修复的

**Comment by afskalsfk** [comment]
Mas布局导致的，修改布局顺序，把添加刷新的方法提前




| |
杨战旗
|
|
邮箱：yzqbeijixing@163.com
|

签名由 网易邮箱大师 定制

在2018年12月13日 10:30，小马哥 写道：

我也遇到了这个问题，怎么修复的

**Comment by mafangchao** [comment]
ok thanks

**Comment by GarthGit** [comment]
> ok thanks

我是将添加刷新控件的方法添加到了 viewWillAppear 里面，这样可以每次切换界面都会刷新数据
总会出现偏移问题，也不知到是不是和你一样的原因
