### ISSUE TITLE
setTitle:forState:方法失效

### ISSUE THREAD

**Issue by moseschou** [CoderMJLee/MJRefresh#124]
`[self.collectionView.header setTitle:@"正在刷新..." forState:MJRefreshHeaderStateRefreshing];`
我在viewDidLoad加了这行代码，提示信息还是默认的，不知道是bug还是我的用法有问题？

**Comment by CoderMJLee** [comment]
要先addLegendHeader，再拿到header调用setTtitle哦。如果还是不行，试试最新代码哈，3Q

**Comment by moseschou** [comment]
李老师给力啊，回复这么快，是你说的这样
