### ISSUE TITLE
隐藏严重bug!! HeaderView下拉刷新后不能正确回到初始位置!

### ISSUE THREAD

**Issue by lilongcnc** [CoderMJLee/MJRefresh#1240]
在HeaderView结束后,  调用end方法开始归位向上偏移的几ms间,  再次下拉刷新, 会出现HeaderView不能正确归位的问题. 跟了下代码,  scrollViewContentOffsetDidChange中初始计量值发生看了变化, 希望杰哥一起看下

**Comment by annilq** [comment]
> 在HeaderView结束后, 调用end方法开始归位向上偏移的几ms间, 再次下拉刷新, 会出现HeaderView不能正确归位的问题. 跟了下代码, scrollViewContentOffsetDidChange中初始计量值发生看了变化, 希望杰哥一起看下

怎么解决的这个问题？我这边也出现了，衰····

**Comment by lilongcnc** [comment]
@annilq ui你该是继承了mj的headr，然后改了东西。但是执行完所有的刷新之后，导致mj不能自己把他自己全部的初始化标识归位。 解决就是把所有的mj刷新的那些表示和header的frame这些归位。 另外要做一些防止暴力刷新

**Comment by annilq** [comment]
> @annilq ui你该是继承了mj的headr，然后改了东西。但是执行完所有的刷新之后，导致mj不能自己把他自己全部的初始化标识归位。 解决就是把所有的mj刷新的那些表示和header的frame这些归位。 另外要做一些防止暴力刷新

谢谢，不知道为啥我订阅的消息没有邮件...我更新到最新版就可以了，谢谢
