### ISSUE TITLE
在UICollectionView上使用非常偶现刷新完后刷新栏没有归位问题

### ISSUE THREAD

**Issue by Han-yang** [CoderMJLee/MJRefresh#1241]
有人遇到这个问题吗，项目里面多个地方使用了下拉刷新功能，但是就一个UICollectionView的界面，测试方几天会遇到一次下拉刷新后没有收回的现象，而且无法恢复，有解法吗

**Comment by Climb0516** [comment]
我也遇到了，你这边解决了吗？

**Comment by wolfcon** [comment]
方便来个Demo吗?
