### ISSUE TITLE
ios 10 崩溃了 MJRefresh

### ISSUE THREAD

**Issue by cczufish** [CoderMJLee/MJRefresh#1244]
**描述bug**
崩溃了

-[MJRefreshBackGifFooter setState:] (in MJRefresh) (MJRefreshBackGifFooter.m:121)

**必现/偶发?**
情况

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone未知
 - ios 10 
 - Xcode未知

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
demo? 必现?
