### ISSUE TITLE
iOS11 PageEnabled MJRefresh 偏移

### ISSUE THREAD

**Issue by miyiyake** [CoderMJLee/MJRefresh#1245]
关闭iOS 11Self-Sizing预估行高，
如果设置tableview的PageEnabled= YES，
tableview底部上拉加载更多时，cell向下偏移。
如果不设置PageEnabled，正常。
怎么解决分页错位问题？？？

**Comment by miyiyake** [comment]
找到一个伪方法，在数据加载完时使用[mj_footer endRefreshingWithNoMoreData].可以试试

**Comment by huxq-coder** [comment]
可以稍微详细说下是怎么解决的吗？谢谢了

**Comment by miyiyake** [comment]
数据加载完时再次调用[mj_footer endRefreshingWithNoMoreData].

**Comment by wolfcon** [comment]
Duplicate of #1196
