### ISSUE TITLE
求一个历史版本

### ISSUE THREAD

**Issue by hwqing** [CoderMJLee/MJRefresh#1250]
目前项目中刚刚接手了一个旧的项目，里面用上了MJRefresh，从代码上来看，引用了MJRefreshHeaderView和MJRefreshFooterView以及MJRefreshBaseViewDelegate。现在问题是没有随机提供MJRefresh的源代码，也没有写明用的是哪个版本的MJRefresh，由于代码量挺大逻辑也不少，所以想暂时先能够保证可以编译通，再考虑改写等等。请问，这可能是哪个版本的MJRefresh，我先pod一下自己编译看看？
非常感谢各位大神了。

**Comment by daniceda** [comment]
-> MJRefresh (3.1.15.7)
   An easy way to use pull-to-refresh
   pod 'MJRefresh', '~> 3.1.15.7'
   - Homepage: https://github.com/CoderMJLee/MJRefresh
   - Source:   https://github.com/CoderMJLee/MJRefresh.git
   - Versions: 3.1.15.7, 3.1.15.6, 3.1.15.3, 3.1.15.2, 3.1.15.1, 3.1.15,
   3.1.14.1, 3.1.14, 3.1.13, 3.1.12, 3.1.11, 3.1.10, 3.1.9, 3.1.8, 3.1.7, 3.1.6,
   3.1.5, 3.1.4, 3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4,
   3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.5.0, 2.4.12, 2.4.11, 2.4.10, 2.4.9, 2.4.8,
   2.4.7, 2.4.6, 2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0,
   2.2.1, 2.2.0, 2.1.0, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.4.7, 1.4.6, 1.4.5,
   1.4.4, 1.4.3, 1.4.1, 1.4.0, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2,
   1.3.1, 1.3.0, 1.2.0, 1.1.0, 1.0.5, 1.0.4, 1.0.3, 0.0.1 [master repo]
