### ISSUE TITLE
针对WKWebView的集成，发现刷新后，webview内容向上偏移了，是什么原因》

### ISSUE THREAD

**Issue by Michaelyb520** [CoderMJLee/MJRefresh#1252]
**描述bug**
清晰简单地描述这个bug是啥

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
截图, demo, 详细描述
