### ISSUE TITLE
改变了contentInset后然后恢复到UIEdgeInsetsZero，下拉加载列表滚动不到最底部，需要手滑动一下才可以

### ISSUE THREAD

**Issue by LXManMan** [CoderMJLee/MJRefresh#1253]
做的是类似于京东店铺的效果，一开始改变了contentInset，可是在下拉加载的时候contentInset已经为UIEdgeInsetsZero，可是下拉加载后tableView滚动不到最底部，需要手滑动一下才可以，初步测量是差44.我也试着改了ignoredScrollViewContentInsetBottom，可是这个属性是改变mj_footer的位置的，

**Comment by wolfcon** [comment]
demo?
