### ISSUE TITLE
> 大家可以试试3.1.15版本，iOS11真是不让人省心呐😆

### ISSUE THREAD

**Issue by zhanght-02** [CoderMJLee/MJRefresh#1254]
> 大家可以试试3.1.15版本，iOS11真是不让人省心呐😆

hello,明杰大神，现在在iOS11上，上拉加载更多时，偏移量会随着上拉的次数越变越高，最后会发现，"上拉可以加载更多"这个控件都跑屏幕中间了(版本已更新到最新的3.1.15.7，尝试使用了上边提到的所有办法都没有作用)。求解答，谢谢

_Originally posted by @kopuCoder in https://github.com/CoderMJLee/MJRefresh/issues/981#issuecomment-447213255_

**Comment by F80EZ6** [comment]
我也同遇到,,求大神解答????

**Comment by F80EZ6** [comment]
我已经解决了.我的项目里  原理是每次网络请求完 给 tableview 又重新加了一个 footer,现在改为只在 table 初始化的时候,添加了一次.
我现在觉得 是因为每次网络请求,又重复添加了 footer, 导致 footer 被添加的越来越多.所以底部的间距越来越大  现在整个项目都改完了 测试 OK!

**Comment by CoderJackySong** [comment]
我也遇到同样的问题，有什么好的解决办法没？

**Comment by wolfcon** [comment]
方便上传一个问题 Demo 吗?

**Comment by wolfcon** [comment]
Duplicate of #981
