### ISSUE TITLE
MJRefresh下拉箭头不回弹的可能情况复现与解决

### ISSUE THREAD

**Issue by LiJinShi** [CoderMJLee/MJRefresh#1257]
我遇到的情况——如果在一个控制器的 viewWillAppear 有网络请求，同时在请求回调里 endRefresh 了。在调用 endRefresh 的时刻如果用户这时也去下拉tableView，那么就可能会出现这种情况。。。测了下，在页面出现后立即去下拉时复现率很高。

解决方案:  用变量进行区分，即只有当手动下拉时才调用 endRefresh ，其他情况请求成功时则不调用，区分后就没有这个问题了。

**Comment by wolfcon** [comment]
#1283
