### ISSUE TITLE
箭头问题

### ISSUE THREAD

**Issue by tpctt** [CoderMJLee/MJRefresh#126]
请问你是取消了下/上拉箭头,还是忘记了?取消的话是基于上面原因呢

**Comment by CoderMJLee** [comment]
什么意思？

**Comment by TheSolitary** [comment]
哈哈，MJ老师，我来给你翻译一下，“请问你是取消了下/上拉箭头呢，还是忘记加上去了？取消的话是基于什么原因呢？”
