### ISSUE TITLE
大标题状态刷新会闪退, 有遇到的吗?

### ISSUE THREAD

**Issue by twtliaw** [CoderMJLee/MJRefresh#1265]
大标题状态刷新会闪退, 有遇到的吗?

**Comment by twtliaw** [comment]
我发现这是必现的, 开始下拉刷新, 但不执行结束, 然后滚动窗口, 就会闪退

**Comment by 13104495959** [comment]
@twtliaw 按照你的描述, 模拟了你的使用场景, 但是并未发现你所描述的问题, 你是否可以上传可以复现这个Bug的Demo呢, 非常感谢.

**Comment by twtliaw** [comment]
```
@13104495959    就用GitHub上的这个demotion就可以 加上这句
[self.navigationController.navigationBar setPrefersLargeTitles:YES]; 
下拉刷新, 刷新的过程中向上滑动 闪退
````

- (void)viewDidLoad
{
    [super viewDidLoad];
    
    __unsafe_unretained UITableView *tableView = self.tableView;
	self.tableView.estimatedRowHeight = 0;

	self.tableView.estimatedSectionHeaderHeight = 0;

	self.tableView.estimatedSectionFooterHeight = 0;
	
	[self.navigationController.navigationBar setPrefersLargeTitles:YES];
	
    // 下拉刷新
    tableView.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        // 模拟延迟加载数据，因此2秒后才调用（真实开发中，可以移除这段gcd代码）
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            // 结束刷新
            [tableView.mj_header endRefreshing];
        });
    }];
    
    // 设置自动切换透明度(在导航栏下面自动隐藏)
    tableView.mj_header.automaticallyChangeAlpha = YES;

    // 上拉刷新
    tableView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
        // 模拟延迟加载数据，因此2秒后才调用（真实开发中，可以移除这段gcd代码）
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            // 结束刷新
//            [tableView.mj_footer endRefreshing];
        });
    }];
}`

**Comment by twtliaw** [comment]
`
@13104495959 就用GitHub上的这个demotion就可以 加上这句
[self.navigationController.navigationBar setPrefersLargeTitles:YES]; 
下拉刷新, 刷新的过程中向上滑动 闪退
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    __unsafe_unretained UITableView *tableView = self.tableView;
	self.tableView.estimatedRowHeight = 0;

	self.tableView.estimatedSectionHeaderHeight = 0;

	self.tableView.estimatedSectionFooterHeight = 0;
	
	[self.navigationController.navigationBar setPrefersLargeTitles:YES];
	
    // 下拉刷新
    tableView.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        // 模拟延迟加载数据，因此2秒后才调用（真实开发中，可以移除这段gcd代码）
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            // 结束刷新
            [tableView.mj_header endRefreshing];
        });
    }];
    
    // 设置自动切换透明度(在导航栏下面自动隐藏)
    tableView.mj_header.automaticallyChangeAlpha = YES;

    // 上拉刷新
    tableView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
        // 模拟延迟加载数据，因此2秒后才调用（真实开发中，可以移除这段gcd代码）
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            // 结束刷新
//            [tableView.mj_footer endRefreshing];
        });
    }];
}`

**Comment by 13104495959** [comment]
@twtliaw 感谢你的及时回复 我会尽快调查 然后回复您

**Comment by 13104495959** [comment]
@twtliaw 我用你的代码复现了这个Bug 感谢你的代码

**Comment by ieliwb** [comment]
> @twtliaw 我用你的代码复现了这个Bug 感谢你的代码

大佬，请问怎么解决呢

**Comment by 13104495959** [comment]
@twtliaw 很抱歉 我下班后 才能调试 弄好联系你

**Comment by 13104495959** [comment]
@twtliaw 
CGFloat insetT = -self.scrollView.mj_offsetY > _scrollViewOriginalInset.top + 52 ? -self.scrollView.mj_offsetY : _scrollViewOriginalInset.top;
可以在使用大标题的情况下, 保证不崩溃

**Comment by twtliaw** [comment]
@13104495959  好的, 谢谢

**Comment by twtliaw** [comment]
@13104495959 你好  这个52是怎么计算出来的?

**Comment by ieliwb** [comment]
为什么是52？

**Comment by 13104495959** [comment]
大标题
-self.scrollView.mj_offsetY----194.000000----_scrollViewOriginalInset.top----140.000000
非大标题
-self.scrollView.mj_offsetY----142.000000----_scrollViewOriginalInset.top----88.000000

**Comment by ieliwb** [comment]
@13104495959 大佬，这个怎么搞成自动判断的，我有个项目有的页面是大标题，又的不是

**Comment by 13104495959** [comment]
@ieliwb  我下班之后 发你
