### ISSUE TITLE
你好，能否把MJRefreshLegendHeader的arrowImage放出来？

### ISSUE THREAD

**Issue by peterhoucll** [CoderMJLee/MJRefresh#127]
对我来说，传统方式的下拉刷新已经够用，只是想把箭头和文字调整下。现在发现箭头没办法调整，要改图片，必须用MJRefreshGifHeader，这个又太麻烦了

谢谢

**Comment by CoderMJLee** [comment]
在2.0版本会开放的哈

**Comment by xilin** [comment]
@CoderMJLee 好像目前还是没有放出来？
