### ISSUE TITLE
默认状态下下拉箭头没有隐藏起来

### ISSUE THREAD

**Issue by VisualEcho** [CoderMJLee/MJRefresh#1273]
<img width="246" alt="image" src="https://user-images.githubusercontent.com/5999906/56786555-f97b4a80-682b-11e9-94f6-a7de7d019124.png">
没有下拉的时候，这个箭头一只显示出来的，下拉刷新一下后还是在。怎么都消不掉这个箭头，隐藏不了

**Comment by VisualEcho** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/5999906/56786688-6db5ee00-682c-11e9-8132-3ab74cc3712b.png">
补充一张调试时候的图

**Comment by wolfcon** [comment]
默认是一直显示的. 你可以尝试这样操作

```swift
self.tableView.mj_header.endRefreshing(completionBlock: {
    self.tableView.mj_header.alpha = 0;
})
```
並且在 `scrollView` 的 `Delegate` 中做如下操作
```swift
override func scrollViewDidScroll(_ scrollView: UIScrollView) {
    // 根据下拉的距离动态改变 self.tableView.mj_header 的 alpha 值
}
```
或者直接简单粗暴
```swift
override func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {
    UIView.animate(withDuration: 0.7) {
        self.tableView.mj_header.alpha = 1
    }
}
```
