### ISSUE TITLE
请问没有更多数据了不显示是什么原因

### ISSUE THREAD

**Issue by yukifeng** [CoderMJLee/MJRefresh#1274]
请教两个不同的tableView 刷新逻辑一样 但是其中一个在没更多数据的时候不显示 断点显示已经走endingrefreshWithNoMoreData了是什么原因？

**Comment by yukifeng** [comment]
[hahaha.zip](https://github.com/CoderMJLee/MJRefresh/files/3155895/hahaha.zip)
@wolfcon  求教原因

**Comment by wolfcon** [comment]
请使用`MJRefreshAutoNormalFooter` 而不是 `MJRefreshAutoFooter`, 那个 AutoFooter 本来就是没有任何东西的空 View
