### ISSUE TITLE
3.2.0 carthage编译失败

### ISSUE THREAD

**Issue by hjzCy** [CoderMJLee/MJRefresh#1279]
*** Building scheme "MJRefreshFramework" in MJRefreshExample.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/huangjianggui/Desktop/DEMO/Carthage/Checkouts/MJRefresh/MJRefreshExample.xcodeproj -scheme MJRefreshFramework -configuration Release -derivedDataPath /Users/huangjianggui/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2.1_10E1001/MJRefresh/3.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/j7/sglyh9yx3850d3f_vhgrtys40000gn/T/MJRefresh SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/huangjianggui/Desktop/DEMO/Carthage/Checkouts/MJRefresh)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/j7/sglyh9yx3850d3f_vhgrtys40000gn/T/carthage-xcodebuild.BUbIAa.log

**Comment by yutingLei** [comment]
我遇到同样的问题，好像是这个文件`MJRefreshConfig.m`没有添加到`Compile Sources`中去。

解决方法：打开工程->TARGETS(选择MJRefreshFramework)->Build Phases->Compile Sources->点击'+'号，将刚才说的文件`MJRefreshConfig.m`添加进去就可以了

注意，在编译的时候不要用update命令，用build(`carthage build MJRefresh`)。
*`carthage update`会自动获取仓库的代码，这样上面的设置就无效了，等作者改了以后应该就不会这样了吧*

**Comment by wolfcon** [comment]
Srr. Have already fixed
