### ISSUE TITLE
KVO 导致的闪退

### ISSUE THREAD

**Issue by maguoxi** [CoderMJLee/MJRefresh#1282]
<img width="799" alt="屏幕快照 2019-05-07 下午1 49 53" src="https://user-images.githubusercontent.com/18694127/57274874-2f8fb880-70cf-11e9-8403-962efb7b2f8d.png">
iOS9.0、10.0的机器上，进入一个使用MJRefresh的界面，当点击返回的时候会闪退，错误信息如上图，是KVO没有移除。观察的Key path为contentOffset和contentSize

**Comment by kinarob** [comment]
@maguoxi 是100%复现在iOS9和10的设备上，还是偶尔？

**Comment by maguoxi** [comment]
> @maguoxi 是100%复现在iOS9和10的设备上，还是偶尔？

100%复现的，只要点返回，UITableView一释放就会闪退。目前我的解决方法是在dealloc方法中把header和footer手动释放，不过这个写起来很麻烦

**Comment by kinarob** [comment]
@maguoxi 方便贴一部分，你使用框架的代码吗？

**Comment by wolfcon** [comment]
@maguoxi 请给出一份 Demo
