### ISSUE TITLE
在iPhoneX系列上下拉刷新，隐藏导航栏，部分文字图片会被遮挡请问如何正确解决

### ISSUE THREAD

**Issue by sun2483968** [CoderMJLee/MJRefresh#1285]
![WX20190508-170854](https://user-images.githubusercontent.com/13990779/57363713-422fed80-71b4-11e9-9fc8-d21c448117e7.png)

**Comment by sun2483968** [comment]
请问谁解决过类似问题，麻烦告诉一下 谢谢

**Comment by sun2483968** [comment]
是控件正在刷新状态时 文字与图片会被刘海部分遮挡

**Comment by wolfcon** [comment]
#1151

**Comment by Liyongcong** [comment]
我也遇到了同样的问题，请问怎么解决
