### ISSUE TITLE
navigationVC 下 push到其他vc在返回来 tableView显示位置不对

### ISSUE THREAD

**Issue by ipoolo** [CoderMJLee/MJRefresh#129]
navigationVC 下 push到其他vc在返回来 tableView显示位置不对
界面上增加了UISearchBar 不push都正常
push后界面返回后整体下移了

**Comment by ipoolo** [comment]
查看是下移了offset -64

**Comment by sdaheng** [comment]
手动把offset改回来？刷新完有时候offset也是-64

**Comment by ipoolo** [comment]
self.automaticallyAdjustsScrollViewInsets = NO;

ios7 后 系统默认吧VC的这个是设置为yes会 从而导致 系统帮你设置Scrollview inset inset上边距被系统设置成了-64 导致offset.x=-64 用上面那行代码关闭就好了 这样就会完全按照自己设置的显示了
