### ISSUE TITLE
下拉刷新后collectionView会闪一下

### ISSUE THREAD

**Issue by 657651096** [CoderMJLee/MJRefresh#1290]
闪动的原因我已经找到了，是设置scrollView的contentInset的时候，系统会设置中间值导致闪动，异步调用可解决问题。我发现MJRefreshHeader中setState:方法中，state == MJRefreshStateRefreshing时是异步调用的，而state == MJRefreshStateIdle时不是，我试着改成异步调用之后问题解决，请问，为什么不都改成异步调用呢？

**Comment by wolfcon** [comment]
能否给出一个Demo. 另外请上传个视频. or gif
