### ISSUE TITLE
如何加载json动图

### ISSUE THREAD

**Issue by afskalsfk** [CoderMJLee/MJRefresh#1291]
想加载json动图  lottie可以展示  但是怎样跟MJRefresh结合起来   有没有开放的方法直接加载json动图资源

**Comment by wolfcon** [comment]
自定义 header 然后用 lottie 在 header 内操作即可

**Comment by afskalsfk** [comment]
搞定   多谢
| |
杨战旗
|
|
yzqbeijixing@163.com
|
签名由网易邮箱大师定制


在2019年05月16日 10:03，Frank<notifications@github.com> 写道：

Closed #1291.

**Comment by liuzhuoming** [comment]
> 搞定 多谢 | | 杨战旗 | | yzqbeijixing@163.com | 签名由网易邮箱大师定制 在2019年05月16日 10:03，Frank<notifications@github.com> 写道： Closed #1291. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

view能正常显示了，但是无法动起来，求助
