### ISSUE TITLE
header刷新不回弹的问题

### ISSUE THREAD

**Issue by XiaoFengCode** [CoderMJLee/MJRefresh#1292]
1.header刷新不回弹的问题
复现代码：[table.mj_header beginRefreshing];
    [table.mj_footer endRefreshing];
一起使用就会毕现，当然一般人不会这么用，只是举个例子说明问题
MJRefreshHeader中setState方法
`- (void)setState:(MJRefreshState)state
{
    MJRefreshCheckState
    
    // 根据状态做事情
    if (state == MJRefreshStateIdle) {
        NSLog(@"2");
        if (oldState != MJRefreshStateRefreshing) return;
        
        // 保存刷新时间
        [[NSUserDefaults standardUserDefaults] setObject:[NSDate date] forKey:self.lastUpdatedTimeKey];
        [[NSUserDefaults standardUserDefaults] synchronize];
        
        // 恢复inset和offset
        [UIView animateWithDuration:MJRefreshSlowAnimationDuration animations:^{
            self.scrollView.mj_insetT += self.insetTDelta;
            
            // 自动调整透明度
            if (self.isAutomaticallyChangeAlpha) self.alpha = 0.0;
        } completion:^(BOOL finished) {
            self.pullingPercent = 0.0;
            
            if (self.endRefreshingCompletionBlock) {
                self.endRefreshingCompletionBlock();
            }
        }];
    } else if (state == MJRefreshStateRefreshing) {
        MJRefreshDispatchAsyncOnMainQueue({
            NSLog(@"1");
            [UIView animateWithDuration:MJRefreshFastAnimationDuration animations:^{
                if (self.scrollView.panGestureRecognizer.state != UIGestureRecognizerStateCancelled) {
                    CGFloat top = self.scrollViewOriginalInset.top + self.mj_h;
                    // 增加滚动区域top
                    self.scrollView.mj_insetT = top;
                    // 设置滚动位置
                    CGPoint offset = self.scrollView.contentOffset;
                    offset.y = -top;
                    [self.scrollView setContentOffset:offset animated:NO];
                }
            } completion:^(BOOL finished) {
                [self executeRefreshingCallback];
            }];
        })
    }
}`
打印结果：2，1
从代码中也可以发现state == MJRefreshStateRefreshing时加了这一句MJRefreshDispatchAsyncOnMainQueue

**Comment by XiaoFengCode** [comment]
[table.mj_header beginRefreshing];
[table.mj_header endRefreshing];
都是header，上面写错了

**Comment by wolfcon** [comment]
如果你非要连续用, 请将 endRefreshing 包裹在
```swift
tableView.mj_header.beginRefreshing()
DispatchQueue.main.async {
    self.tableView.mj_header.endRefreshing()
}
```

**Comment by wolfcon** [comment]
现阶段的 `State 状态机` 有缺陷, 的确在这样的特殊误用情况下会产生问题

> 原因是: 状态机中某些操作时依赖 DispatchQueue 的异步分发, 导致有微延迟, 而某些改变状态时又未使用异步分发

### 在修复之前, 非要误用的话, 这样使用先
```swift
tableView.mj_header.beginRefreshing()
DispatchQueue.main.async {
    self.tableView.mj_header.endRefreshing()
}
```

**Comment by wolfcon** [comment]
#1258

**Comment by corderguo** [comment]
的确有这个bug，而且下次刷新也不会恢复，建议下次刷新的时候可以自动恢复
