### ISSUE TITLE
当tableViewCell的高度等于屏幕的高度时，上拉加载到最后没数据时，加载停止后，tableViewCell位置向下偏移

### ISSUE THREAD

**Issue by CoderJackySong** [CoderMJLee/MJRefresh#1294]
在iOS11.0.2和iOS 12.3系统上，当tableViewCell的高度等于屏幕的高度时，上拉加载更多(带动画的)，当加载刷新停止后，当前的tableViewCell位置发生向下偏移，上拉的位置越往上，tableViewCell向下偏移越大，尤其是上拉到最后没有数据的时候最明显。我当前使用的MJRefresh， 在Cocoapods下的版本是3.2.0。希望作者或者哪位大神看到后，能帮忙解决哈，谢谢了。

**Comment by wolfcon** [comment]
Duplicate of #1196

**Comment by wolfcon** [comment]
方便发一个视频吗? 顺带来一个 demo

**Comment by CoderJackySong** [comment]
> 方便发一个视频吗? 顺带来一个 demo

这个应该可以用其他代码测试的，比如MJRefresh中Demo，设置tableviewCell的高度等于屏幕的高度，当加载到最后没有数据的时候，刷新挺时候，就能复现出来了。

**Comment by wolfcon** [comment]
你可以试试
```swift
tableView.estimatedRowHeight = Your own row height
// or
tableView.estimatedRowHeight = 0
// or
func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
     // your cached estimated height
}
```

**Comment by wolfcon** [comment]
#1304

**Comment by CoderJackySong** [comment]
> 方便发一个视频吗? 顺带来一个 demo

[https://pan.baidu.com/s/1CoubYHpDul6nnmVeCjAb4Q](url)

**Comment by CoderJackySong** [comment]
> > 方便发一个视频吗? 顺带来一个 demo
> 
> 这个应该可以用其他代码测试的，比如MJRefresh中Demo，设置tableviewCell的高度等于屏幕的高度，当加载到最后没有数据的时候，刷新挺时候，就能复现出来了。

[wx_camera_1559184226816.mp4.zip](https://github.com/CoderMJLee/MJRefresh/files/3328577/wx_camera_1559184226816.mp4.zip)
