### ISSUE TITLE
如何让 refreshHeader的高度动态变化？

### ISSUE THREAD

**Issue by bigNiuSanMao** [CoderMJLee/MJRefresh#1296]
现在refreshHeader的高度为固定的54 高度，如何随着下拉的距离增大 refreshHeader的高度也随之增大，高度始终是下拉的距离，我尝试 继承MJRefreshHeader ，重新scrollViewDidChange方法，在此方法中 动态设置 self.mj_y = 0, self.mj_h = 偏移量，然后调用 layoutIfNeed方法，确实达到想要的效果，但是有bug，随着下拉距离的增大，self.mj_y 变为  self.mj_h我改如何处理

**Comment by wolfcon** [comment]
这个你要自定义的东西就比较多了...首先你没有描述的很清楚, 是松手后变为 self.mj_h? 还是没有松手

1. 将初始的高度记住
2. 修改 mj_y 和 mj_h(这里你要注意 super 里干了什么)
3. 根据你需求还需要修改其他的状态变量
