### ISSUE TITLE
Wkwebview里的下拉刷新问题

### ISSUE THREAD

**Issue by LJW008** [CoderMJLee/MJRefresh#1297]
请教下，当H5页面里弹出一个浮层，里面也是一个上下拉的滚动视图,当下拉 这个滚动视图的时候，也会触法MJ的下拉刷新，请问这个H5前端代码可以处理吗，还是需要一起才可以处理这个问题？

**Comment by wolfcon** [comment]
你禁用bounce

**Comment by LJW008** [comment]
刷新也是H5页面里自己做吗？

**Comment by wolfcon** [comment]
是的, 否则很大程度上会出现异常
