### ISSUE TITLE
GifFooter在MJRefreshStateNoMoreData状态下不显示图片

### ISSUE THREAD

**Issue by jihongboo** [CoderMJLee/MJRefresh#1298]
**描述bug**
GifFooter在MJRefreshStateNoMoreData状态下不显示图片

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
欢迎给出更多信息

**Comment by jihongboo** [comment]
MJRefreshAutoGifFooter 中的 (void)setState:(MJRefreshState)state 方法中，当没有更多数据时，会将gifView隐藏。
但是我们的需求是，当没有数据时，需要显示一个没有数据的图片，因此gifView不能够隐藏。如果要达到这样的效果，有什么好的方法？
![IMG_F59640D8F0F0-1](https://user-images.githubusercontent.com/15397647/60088996-2daeb100-9772-11e9-9230-b8b7f57a1bbc.jpeg)

**Comment by wolfcon** [comment]
继承 `MJRefreshAutoGifFooter`, 然后不隐藏即可
