### ISSUE TITLE
在真机测试中传统下拉刷新会crash

### ISSUE THREAD

**Issue by codemzy** [CoderMJLee/MJRefresh#130]
在真机测试中传统下拉刷新调用- (MJRefreshLegendHeader *)addLegendHeaderWithRefreshingBlock:(void (^)())block 
时会crash。
原因是:
在 UIscrollView + Mjrefresh的第41行处
- (MJRefreshLegendHeader *)addLegendHeaderWithRefreshingBlock:(void (^)())block 方法中把dataKey设置为nil
导致刷新时在MJrefreshHeader.m的125行的
[[NSUserDefaults standardUserDefaults] setObject:updatedTime forKey:self.dateKey];
的key为nil导致crash

改用- (MJRefreshLegendHeader *)addLegendHeaderWithRefreshingBlock:(void (^)())block dateKey:(NSString *)dateKey正常

**Comment by CoderMJLee** [comment]
试试最新版本2.0版本哈
