### ISSUE TITLE
刷新执行顺序问题

### ISSUE THREAD

**Issue by chdo002** [CoderMJLee/MJRefresh#1300]
MJRefreshComponent中的executeRefreshingCallback对刷新执行顺序似乎有点问题

beginRefreshingCompletionBlock应该是最先执行的
refreshingAction和refreshingBlock应该是之后执行吧?

**Comment by wolfcon** [comment]
没有问题啊. beginRefreshing`Completion`Block 不是 beginRefreshingBlock 啊, 老哥

要等待开始执行后, 也就是 refreshingAction/refreshingBlock 执行完后, 菊花开转, 小圈圈开转, gif 图开跑....然后才是开始`完成`啊, 这时候再 block

**Comment by chdo002** [comment]
beginRefreshingCompletionBlock  
这里面又有begin 又有 complete 让人有点摸不着头脑

像viewwillappear  viewdidappear  这种就很清楚

改成didEnterRefreshingBlock 或许会好点

**Comment by wolfcon** [comment]
不过很少有人用这个 beginRefreshingCompletionBlock 吧... 一般都直接在 refresh 那里之后直接写代码了.

只有一些特殊情况用这个.
