### ISSUE TITLE
页面保持下拉状态，点击其他tab，回到该页面时header下偏移不恢复刷新失效问题！！！

### ISSUE THREAD

**Issue by Climb0516** [CoderMJLee/MJRefresh#1301]
页面保持下拉状态，点击其他tab，回到该页面时header下偏移不恢复刷新失效问题！！！
看了类似问题的issue，尝试了3.1.17版本，3.2.0版本，及3.2.1版本 都没有修复该问题。请关注一下，谢谢老铁们！

**Comment by wolfcon** [comment]
到底是`偏移不恢复`, 还是`刷新失效`? 请描述清楚一点

**Comment by GarthGit** [comment]
> 到底是`偏移不恢复`, 还是`刷新失效`? 请描述清楚一点

collectionView下拉刷新时偏移54pt，每次刷新都会向下偏移54:

**Comment by GarthGit** [comment]
就是在Collectionview.mj_header beginRefreshing与Collectionview.mj_header endRefreshing之间，contentOffset.y = 54.00pt,而且collectionVIew的item也可以在0--54之间上下移动

**Comment by GarthGit** [comment]
第一次刷新，偏移量大于0就会开始执行刷行方法
第二次刷新，偏移量大于54才会执行
第三次刷新，偏移量大于108pt才会执行
……

**Comment by wolfcon** [comment]
方便传一份 demo 吗?

**Comment by GarthGit** [comment]
`- (void)createRefreshControl
{
    MJRefreshNormalHeader *header = [MJRefreshNormalHeader headerWithRefreshingTarget:self refreshingAction:@selector(getLightGroupData)];
    self.lightGroupCollectionview.mj_header = header;
    [header setTitle:@"加载数据中..." forState:MJRefreshStateRefreshing];
    [header setTitle:@"下拉加载" forState:MJRefreshStatePulling];
    [header setTitle:@"加载完成" forState:MJRefreshStateNoMoreData];
    header.lastUpdatedTimeLabel.hidden = YES;
    self.lightGroupCollectionview.mj_header.automaticallyChangeAlpha = YES;
    [self.lightGroupCollectionview.mj_header beginRefreshing];
}




`

**Comment by GarthGit** [comment]
> 方便传一份 demo 吗?

这个是公司项目，方法可以啊

**Comment by GarthGit** [comment]
界面来回切换时容易出线collectionView 向下偏移的情况

**Comment by wolfcon** [comment]
你单独写一个 demo. 逻辑上只要复现你们项目的 bug 即可, 因为我这边没有出现这个问题..也不好复现, 是不是代码逻辑上可能造成的 bug

**Comment by GarthGit** [comment]
> 你单独写一个 demo. 逻辑上只要复现你们项目的 bug 即可, 因为我这边没有出现这个问题..也不好复现, 是不是代码逻辑上可能造成的 bug, 也方便定位修改

嗯，我单独把刷新方法分离出来以后，在新建的demo中没有问题

**Comment by GarthGit** [comment]
> 你单独写一个 demo. 逻辑上只要复现你们项目的 bug 即可, 因为我这边没有出现这个问题..也不好复现, 是不是代码逻辑上可能造成的 bug, 也方便定位修改

Using MJRefresh (3.2.0)

**Comment by GarthGit** [comment]
会不会是因为 我将iOS9.0 升级到iOS11.0  
这个原因引起的呢？

**Comment by GarthGit** [comment]
我重新用Xcode10.2构建一下项目，本来项目时Xcode8.0创建的，后来我升级了一下Mac系统和Xcode

**Comment by wolfcon** [comment]
你试试吧. 对了. 你只要编辑你的消息就好了...不要刷屏, 避免以后的人, 看一大长传流水账. 哈哈哈, 整理一下, 编辑一下

**Comment by GarthGit** [comment]
> 你试试吧. 对了. 你只要编辑你的消息就好了...不要刷屏, 避免以后的人, 看一大长传流水账. 哈哈哈, 整理一下, 编辑一下

找到了 应该是 添加的观察者的原因：观察网络参数是否发生改变--即重新发出请求/改变UI
`
- (void)addObsverFamilyIDChange
{
    [self.userManager addObserver:self forKeyPath:@"userFamilyID" options:NSKeyValueObservingOptionNew| NSKeyValueObservingOptionOld context:nil];
    [self createRefreshControl];
}
- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSKeyValueChangeKey,id> *)change context:(void *)context
{
    if ([keyPath isEqualToString:@"userFamilyID"]) {
        dispatch_async(dispatch_get_main_queue(), ^{
            [self createRefreshControl];
        });
    }
}
`
