### ISSUE TITLE
xib加载的UITableView和UICollectionView下拉和上拉刷新时，页面不回弹，偏移量不断增大。

### ISSUE THREAD

**Issue by Mr-Dsg** [CoderMJLee/MJRefresh#1303]
xib加载的UITableView和UICollectionView下拉和上拉刷新时，页面不回弹，每次调用，偏移量不断增大。

**Comment by wolfcon** [comment]
Demo? 我测试的工程没有发现这个问题.

**Comment by Mr-Dsg** [comment]
创建一个带xib的UIViewController，将UICollectionView拖入到xib中，将xib的UICollectionView关联到UIViewController，在UIViewController创建方法- (UICollectionView *)collectionView，在- (UICollectionView *)collectionView 这个方法中调用，_collectionView.mj_header = [MJRefreshStateHeader headerWithRefreshingBlock:^{及_collectionView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{刷新方法。

**Comment by wolfcon** [comment]
能劳烦您做个 demo, 将 zip 拖上来吗?

**Comment by Mr-Dsg** [comment]
> xib加载的UITableView和UICollectionView下拉和上拉刷新时，页面不回弹，每次调用，偏移量不断增大。

**Comment by Mr-Dsg** [comment]
那就暂时不需要帮助了，谢谢~自己能解决

**Comment by wolfcon** [comment]
欢迎你解决后 PR
