### ISSUE TITLE
下拉刷新时，collectionView.backgroundView背景图 往上弹了一下是什么原因

### ISSUE THREAD

**Issue by 674481501** [CoderMJLee/MJRefresh#1305]
**描述bug**
清晰简单地描述这个bug是啥

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
请提供截图以及Demo

**Comment by 674481501** [comment]
整个控制器就是collectionController 用[[UICollectionViewFlowLayout alloc]init]创建的 
然后设置collection的背景图   下拉刷新的时候整个背景图会上下弹一下

**Comment by 674481501** [comment]
![Uploading UJNP8048.2019-06-27 16_49_49.gif…]()

**Comment by 674481501** [comment]
![UJNP8048 2019-06-27 16_49_49](https://user-images.githubusercontent.com/50482539/60251749-b86ee780-98fb-11e9-8c66-f4223eb1ea8b.gif)

**Comment by wolfcon** [comment]
这个是由于动画冲突造成的. CollectionView 在刷新时/ 后使用 `UIView animation` 动画时会发生异常

**Comment by ericlee16888** [comment]
這個問題在 3.7.2 還是存在
