### ISSUE TITLE
跳转到其他页面马上回来tableview出现卡顿 无法滑动

### ISSUE THREAD

**Issue by Chancetc** [CoderMJLee/MJRefresh#131]
您好，在tableview中点击图片跳转到其他页面马上返回会出3秒左右无法滑动tableview的情况 大部分情况是在tableview头几个点击跳转会有问题

**Comment by CoderMJLee** [comment]
一般可能是因为在主线程做的事情时间太长，或者页面内容太多，比如显示了一堆控件或者一堆图片
