### ISSUE TITLE
endRefreshingWithNoMoreData无法展示无数据View的问题

### ISSUE THREAD

**Issue by CaiChenghan** [CoderMJLee/MJRefresh#1312]
**描述bug**
在继承自 ```MJRefreshBackFooter``` 的 ```自定义Footer``` 调用 ```endRefreshingWithNoMoreData``` 无法正确展示无数据视图。
但是继承自 ```MJRefreshAutoFooter``` 的却正常。

**必现/偶发?**
必现

**怎么样重现这个bug**
代码很少，我就直接贴出来了。
```
@interface MyRefreshFooter : MJRefreshBackFooter

@end
```

```
#import "MyRefreshFooter.h"

@interface MyRefreshFooter ()

@property (nonatomic, strong) UILabel *lab;

@end

@implementation MyRefreshFooter

- (void)prepare {
    [super prepare];
    self.mj_h = 100;
    [self addSubview:self.lab];
}

- (void)placeSubviews {
    [super placeSubviews];
    self.lab.sd_layout
    .spaceToSuperView(UIEdgeInsetsZero);
}

- (void)setState:(MJRefreshState)state {
    MJRefreshCheckState;
    if (state == MJRefreshStateNoMoreData) {
        self.lab.text = @"无更多数据";
    } else if (state == MJRefreshStateRefreshing) {
        self.lab.text = @"正在刷新";
    } else {
        self.lab.text = @"我要刷新";
    }
}

- (UILabel *)lab {
    if (_lab == nil) {
        _lab = [[UILabel alloc]init];
        _lab.textAlignment = NSTextAlignmentCenter;
    }
    return _lab;
}
```
无数据结束刷新
```
- (void)endRefrehs {
    __weak typeof(self) weakSelf = self;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [weakSelf.tableView.mj_footer endRefreshingWithNoMoreData];
    });
}
```

**你期望的结果是什么？**
能正确显示无数据的footer，但是现在，这个footer不能正确显示了，需要手动往上拖，才能展示。

**截图**
![image](https://user-images.githubusercontent.com/9568389/60479969-6098fd80-9cba-11e9-85e8-ce52407ccb61.png)

**运行环境**
 - iPhone8
 - iOS12.0
 - Xcode10
 - MJRefresh 3.2.0

**额外的**
我发现继承自 ```MJRefreshAutoFooter``` 的能够正确的展示，但继承自 ```MJRefreshBackFooter``` 的却不能。我看了下 ```MJRefreshBackFooter``` 里面的代码，断点了下，感觉这个```- (void)setState:(MJRefreshState)state```方法是不是有点问题？还是说我自定义的时候，哪个方法漏掉了没写？

**有疑问的代码**
 ```MJRefreshBackFooter``` 里的第83行。
```
- (void)setState:(MJRefreshState)state
{
    MJRefreshCheckState
    
    // 根据状态来设置属性
    if (state == MJRefreshStateNoMoreData || state == MJRefreshStateIdle) {
        // 刷新完毕
        if (MJRefreshStateRefreshing == oldState) {
            [UIView animateWithDuration:MJRefreshSlowAnimationDuration animations:^{
                self.scrollView.mj_insetB -= self.lastBottomDelta;
```
我有些疑惑，```self.scrollView.mj_insetB -= self.lastBottomDelta;```  把NoMoreData和StateIdle作为相同的条件一起来处理这个偏移，那么NoMoreData要如何才能给展示?

**Comment by Huang-Libo** [comment]
所谓 BackFooter，就是会自动回弹、隐藏到视图下方的 Footer，你可以看看本项目的 demo。

**Comment by CaiChenghan** [comment]
@Huang-Libo 这个不能设置NoMoreData的footer吗？我需要的是手动上拉刷新、加载数据、展示无数据的footer，而不需要滚动到底部后自动触发刷新加载数据。主要是调用了endRefreshingWithNoMoreData，却不能展示。

**Comment by wolfcon** [comment]
这个 BackFooter 本身的工作机理就是这样的. 如果想显示出来的那种, 
请用 AutoFooter. 
并且设置
```swift
footer.automaticallyRefresh = false
```

**Comment by Huang-Libo** [comment]
楼主应该是想用 BackFooter 那种交互，但希望没数据的时候Footer又显示在用户可视范围内，AutoFooter 可能也没法满足他的需求。@wolfcon

我觉得可以继续使用 BackFooter，然后，无数据的时候将 mj_footer 隐藏，再自行添加一个 tableView 的自定义 footer。@CaiChenghan

**Comment by CaiChenghan** [comment]
@Huang-Libo 对，需要用 ```BackFooter``` 的那种交互。使用 ```AutoFooter``` ，在设置 ```footer.automaticallyRefresh = false``` 后，还没有下拉，那个footer就已经展示出来了。

我用了2种方法，来实现了footer的展示。
- 在tableView的底部添加一个自定义的无数据视图。

    因为 ```AutoFooter``` 和 ```BackFooter``` 都是继承自 ```RefreshFooter```，所以我给 ```RefreshFooter``` 写了个扩展，补充了```endRefreshingWithNoMoreData```方法（可传入无数据内容：text、color、font、height，甚至可直接传入自定义一个无数据的view）。根据RefreshFooter的scrollView，动态绑定一个无数据view到scrollView的底部，从而实现展示无数据视图。自定义方法里，仍旧要执行MJ的 ```endRefreshingWithNoMoreData``` 方法。同时需要 **replace**   ```resetNoMoreData``` 方法，以便能移除自定义的无数据视图。

- hook ```MJRefreshBackFooter``` 的 ```setState``` 的方法。

    在不改MJ源码的情况下，写个 ```MJRefreshBackFooter``` 的分类，hook ```setState``` 然后把源码方法内容复制过来，然后去掉 **if** 里的 ```state == MJRefreshStateNoMoreData``` ，然后kov/kvc修改一下里面爆红的错误，就可以像 ```AutoFooter``` 去使用 ```NoMoreData``` 方法了。

@wolfcon 个人对 ```BackFooter``` 里，那个 **if** 判断把 ```NoMoreData``` 和 ```StateIdle``` 作为同一个条件去处理还是有疑问的，毕竟这两种结果的展示，是不相同的。

**Comment by Huang-Libo** [comment]
不需要做这么复杂吧...

**Comment by CaiChenghan** [comment]
@Huang-Libo 项目有些混乱，我只是想统一一下。

**Comment by wolfcon** [comment]
BackFooter 是基础类. 你要用的是 `MJRefreshBackNormalFooter.m ` / `MJRefreshBackStateFooter` / `MJRefreshBackGifFooter` 而不是 MJRefreshBackFooter.h
