### ISSUE TITLE
下拉刷新状态中，切换tabbar到另外一个rootvc，再点击tabbar返回，下拉状态消失了

### ISSUE THREAD

**Issue by Maxcucurbit** [CoderMJLee/MJRefresh#1313]
**描述bug**
下拉刷新状态中，切换tabbar到另外一个rootvc，再点击tabbar返回，下拉状态消失了

**必现/偶发?**
必现

**怎么样重现这个bug**
下拉刷新状态中，切换tabbar到另外一个rootvc，再点击tabbar返回，下拉状态消失

**你期望的结果是什么？**
继续展示下拉刷新的状态

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone7Plus
 - iOS12.1
 - Xcode10.2

**Comment by wolfcon** [comment]
#1271

**Comment by Maxcucurbit** [comment]
> #1271
所以说这个是防止其他BUG而在tababr切换时主动结束了刷新吗？

**Comment by Huang-Libo** [comment]
刷新没有完成，下拉刷新的样式不应该消失吧？ @wolfcon

**Comment by wolfcon** [comment]
@Huang-Libo 有没有想过出了这个VC. 顶部底部的 Inset 会发生变化这件事, 因为在刷新前保存的是老的. 在其他页面 VC 可能控制了顶部栏和底部栏, 这时候如果回来, 就可能发生异常.

**Comment by wolfcon** [comment]
@Maxcucurbit 是的. 但是你的请求并没有结束, 你可以保存下来数据, 在该界面再次出现时刷新一下界面即可.

**Comment by Maxcucurbit** [comment]
> > 所以说这个是防止其他BUG而在tababr切换时主动结束了刷新吗？
> 
> @Maxcucurbit 是的. 但是你的请求并没有结束, 你可以保存下来数据, 在该界面再次出现时刷新一下界面即可. 或者cancel request

好的 谢谢解答！

**Comment by Huang-Libo** [comment]
> @Huang-Libo 有没有想过出了这个VC. 顶部底部的 Inset 会发生变化这件事, 因为在刷新前保存的是老的. 在其他页面 VC 可能控制了顶部栏和底部栏, 这时候如果回来, 就可能发生异常.

目前的改动回避了这个问题，没有解决这个问题，或许我们可以想想如何能直接解决这个问题。

**Comment by wolfcon** [comment]
欢迎 PR, 理论上界面跳转后, 原页面应该停止它的行为, 后台行为除外

**Comment by Huang-Libo** [comment]
有个比较直观的问题是，用户会误以为刷新完成了（因为下拉刷新的动画已经结束了）

**Comment by CaiChenghan** [comment]
@Maxcucurbit  你这个问题，我感觉应该是你操纵(或者其他地方影响)了scrollView的contentInset，或者是contentOffset。毕竟refresh的header或者footer，都是 **独立的对象** ，附属于scrollView的独立对象，不是共用的对象。这个应该跟你页面怎么跳没关系了吧？mj的header、footer里刷新状态的记录，是其对象内的，跟其他的刷新对象已经是没有关系了。个人觉得你这个问题，可能需要先别添加mj的header、footer，然后kvo一下scrollView的contentOffset及contentInset。

**Comment by CaiChenghan** [comment]
我有个疑问：如果切换的是window的rootController，这个rootController，不是应该被清理掉吗？如果能正常的被清理掉，那么其所持有的对象都应该被销毁，包括网络请求（可能还在飞，但是接受者已经不存在了，没什么影响）、mj的header和footer。在重设rootController后，页面为refresh的常态页面，这个就比较正常了。如果那个rootController没被清理，而是切换后继续使用，那么其所有状态也应该是不变的，包括正在刷新的状态。

**Comment by dong09000** [comment]
导致这个问题的原因是 网络请求 结束的回调  block中，你的结束刷新代码未执行？还是说回调 block直接失效？ 我猜测是 block中 关于  self 的操作全部失效导致的？因为 self 此时可能被释放掉了？  这个如果有demo给我看看就好了

**Comment by Maxcucurbit** [comment]
> 束的回调 block中

不用demo 你用最新的MJRefresh版本在TabBar的一个rootVC做下拉刷新，然后切换到其他页面，再回去会发现下拉刷新的状态直接被结束了

**Comment by dong09000** [comment]
window的rootVc切换？还是tabbarVc是rootVc切换页卡

**Comment by Maxcucurbit** [comment]
> window的rootVc切换？还是tabbarVc是rootVc切换页卡
tabbarVc是rootVc切换页卡
