### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by mafaming** [CoderMJLee/MJRefresh#1314]
**描述bug**
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MJRefreshAutoNormalFooter", referenced from:
      objc-class-ref in MPGetDailyCollectionCell.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**必现/偶发?**
必现

**怎么样重现这个bug**
UICollectionView 嵌套 UICollectionView，里面的UICollectionView添加
self.collectionView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        //Call this Block When enter the refresh status automatically
        [ws loadMoreData];
    }];
编译不成功
![image](https://user-images.githubusercontent.com/11641379/60709523-36a63c00-9f43-11e9-8fac-3281e7729abb.png)

**你期望的结果是什么？**

**运行环境**
 - iPhone6
 - iOS12.3.1
 - Xcode10.2.1

**Comment by wolfcon** [comment]
这个明显是你没引入库造成的. 你是通过什么方式集成的MJRefresh?

**Comment by mafaming** [comment]
@wolfcon   pod 方式，引用肯定是成功了，我lipo -info 看libMJRefresh.a 是支持64，但就是编译不过去，很奇怪

**Comment by wolfcon** [comment]
你自己再重写个demo传上来看看?

**Comment by langyangyangzzZ** [comment]
同样的问题,刚解决, 选择Build Phasses, 找到Link Binary With Libraies 添加 CoreData.fragmentwork 
参考:https://stackoverflow.com/questions/10563426/undefined-symbols-for-architecture-error
