### ISSUE TITLE
iPhone 8plus（12.1.4） 上拉加载更多 会抖动一下 其它机型（所有系统）正常

### ISSUE THREAD

**Issue by xiaowangqinghui** [CoderMJLee/MJRefresh#1315]
**描述bug**
8p上拉加载更多会抖动一下并且加载出来的数据会往上走一个cell，其它手机除了8p不管什么系统都正常。

**必现/偶发?**
必现

**你期望的结果是什么？**

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone8p
 - iOS12.1.4
 - Xcode10

**额外的**
最好能提供出现bug的Demo
<img width="475" alt="image" src="https://user-images.githubusercontent.com/15713276/60868474-b55eea00-a25f-11e9-9f87-f695df8f60fc.png">

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`

**Comment by wolfcon** [comment]
老哥, 你做的这个App......有点黄暴啊
