### ISSUE TITLE
切换tab再返回，刷新状态消失，已找到问题原因

### ISSUE THREAD

**Issue by KingOfSea** [CoderMJLee/MJRefresh#1318]
**描述bug**
页面A在刷新，切换tab到页面B，再返回A，刷新状态消失，但此时确实在刷新，代码问题如下图

**必现/偶发?**
必现

**截图**
文件:MJRefreshHeader.h，方法:willMoveToWindow，为什么切换时需要endRefreshing

![](https://user-images.githubusercontent.com/16201498/61118651-b98f3f80-a4cb-11e9-8c83-e2bf1e25a971.png)

**Comment by fengyunjue** [comment]
请问你是怎么解决的，我现在也遇到了同样的问题，感谢

**Comment by wolfcon** [comment]
现在的机制就是如此. 因为切换了界面. `contentInsets` 可能由于新的界面受到影响, 导致老的 `contentInsets` 不能正确的作用, 然后导致切换 tab, 再回去发现, 有一个 `refreshHeader` 的空白问题

**Comment by wolfcon** [comment]
Duplicate of #1313
