### ISSUE TITLE
在隐藏导航情况下，下拉刷新，怎样实现不覆盖住状态栏，在状态栏下刷新

### ISSUE THREAD

**Issue by justyour** [CoderMJLee/MJRefresh#1320]
**你的新功能建议是否牵扯到某个常见的问题？**
在隐藏导航情况下，下拉刷新，怎样实现不覆盖住状态栏，在状态栏下刷新

**Comment by wolfcon** [comment]
`header.ignoredScrollViewContentInsetTop = -20 `
