### ISSUE TITLE
设置ignoredScrollViewContentInsetTop后，下拉刷新显示不正常

### ISSUE THREAD

**Issue by justyour** [CoderMJLee/MJRefresh#1321]
**描述bug**
设置 `tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;`
`tableView.mj_header.ignoredScrollViewContentInsetTop = -44;`
下拉刷新显示不正常

**必现/偶发?**
必现

**截图**
<img width="297" alt="图片" src="https://user-images.githubusercontent.com/9986693/61576529-c20bf980-ab0d-11e9-97f6-f140e5e648ac.png">

**运行环境**
 - iPhoneXR
 - iOS12.2
 - Xcode10.2.1

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
逻辑本就是如此啊? 

你使用了 `UIScrollViewContentInsetAdjustmentNever` , 自己不预留顶部控件, 你的 row0 显示正常吗?

你不使用 `UIScrollViewContentInsetAdjustmentNever`, 则系统会自动适配不需要设置 `tableView.mj_header.ignoredScrollViewContentInsetTop `

你要什么效果? 在你上一个 issue 里继续不好吗? 狂开 issue 干嘛
Duplicate of #1320
