### ISSUE TITLE
cocoapods更新到3.2.0版本,fastlane打包失败,Xcode能正常编译

### ISSUE THREAD

**Issue by ToninZhao** [CoderMJLee/MJRefresh#1322]
用fastlane打包时,出现"MJRefreshComponent.h"相关的错误❌提示,用3.1.16版本正常
<img width="1490" alt="bug01" src="https://user-images.githubusercontent.com/15906945/61600315-9baba280-ac62-11e9-8978-bc8b535e63d0.png">
.
pod search不到3.2.1版本.

**Comment by wolfcon** [comment]
pod 的 `3.2.0` 是正常的. 3.2.1 主要针对 `Carthage`

**Comment by ToninZhao** [comment]
> pod 的 `3.2.0` 是正常的. 3.2.1 主要针对 `Carthage`

嗯,关闭了issue.
