### ISSUE TITLE
iOS13，beta5崩溃

### ISSUE THREAD

**Issue by vitasapple** [CoderMJLee/MJRefresh#1325]
NSObject+MJProperty.m的153行
#pragma mark - 公共方法
+ (NSMutableArray *)properties
{
    NSMutableArray *cachedProperties = [self dictForKey:&MJCachedPropertiesKey] [NSStringFromClass(self)];
崩溃在这行

**Comment by kinarobin** [comment]
@vitasapple 大兄弟，这不是MJExtension的issue ？
