### ISSUE TITLE
iOS 8.4 死循环 reloadData 闪退

### ISSUE THREAD

**Issue by jiurong001** [CoderMJLee/MJRefresh#1326]
**描述bug**
清晰简单地描述这个bug是啥

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by kinarobin** [comment]
@jiurong001 使用最新的版本哈，新版本我们没有这个问题的！

**Comment by jiurong001** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/17971763/62917387-a0c9c080-bdce-11e9-95b8-92af04484282.png">

上午试了一下，最新代码也不能解决，大神指点

我们的需求是  死循环，持续调用  [self.tableView reloadData];  刷新数据， 直接崩在这句代码；

**Comment by wolfcon** [comment]
新版本没有这句代码了, 你是怎么用着新版本, 然后还在这行报错的呢?
