### ISSUE TITLE
UITableView style 为 UITableViewStylePlain 下拉偏移问题 

### ISSUE THREAD

**Issue by Nododo** [CoderMJLee/MJRefresh#1327]
**描述bug**
1.UITableView style 为 UITableViewStylePlain 
2.tableview 有多个section
3.让header跟随滚动实现scrollview 代理
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    CGFloat sectionHeaderHeight = 68;
    if (scrollView.contentOffset.y<=sectionHeaderHeight&&scrollView.contentOffset.y>=0) {
        scrollView.contentInset = UIEdgeInsetsMake(-scrollView.contentOffset.y, 0, 0, 0);
    } else if (scrollView.contentOffset.y>=sectionHeaderHeight) {
        scrollView.contentInset = UIEdgeInsetsMake(-sectionHeaderHeight, 0, 0, 0);
    }
}
4.让tableview 向上滚动一定的距离，然后大范围下拉刷新，刷新结束后会向上偏移

**必现/偶发?**
必现

**临时解决方法**
将tableview  style 改为 UITableViewStyleGroup

**Comment by JsonFu** [comment]
能把关键代码发一下吗？我是swift引用mj,iOS 12系统。只要分页再reload(),tableView就向下偏移（contentSize.y > 0），设置self?.tableView.setContentOffset(CGPoint(x: 0, y: 0), animated: false)都不行。

**Comment by Nododo** [comment]
> 能把关键代码发一下吗？我是swift引用mj,iOS 12系统。只要分页再reload(),tableView就向下偏移（contentSize.y > 0），设置self?.tableView.setContentOffset(CGPoint(x: 0, y: 0), animated: false)都不行。

我们碰到的不是同样的问题

**Comment by JsonFu** [comment]
> > 能把关键代码发一下吗？我是swift引用mj，iOS 12系统。只要分页再重载（），tableView就向下偏移（contentSize.y> 0），设置self？.tableView.setContentOffset（CGPoint（x ：0，y：0），动画：false）都不行。
> 
> 我们碰到的不是同样的问题

我的也是上滑大段距离之后，再去reload,结果就是tableView没有在最顶端，页面显示的第一个cell是第5个cell。我遇到的问题是这样的。

**Comment by Nododo** [comment]
> > > 能把关键代码发一下吗？我是swift引用mj，iOS 12系统。只要分页再重载（），tableView就向下偏移（contentSize.y> 0），设置self？.tableView.setContentOffset（CGPoint（x ：0，y：0），动画：false）都不行。
> > 
> > 
> > 我们碰到的不是同样的问题
> 
> 我的也是上滑大段距离之后，再去reload,结果就是tableView没有在最顶端，页面显示的第一个cell是第5个cell。我遇到的问题是这样的。

将tableview style 改为 UITableViewStyleGroup   这样做就解决了我的问题
