### ISSUE TITLE
UISearchBar引起的滚动条问题

### ISSUE THREAD

**Issue by twmsh** [CoderMJLee/MJRefresh#133]
在tableview加了一个UISearchBar作为它的tableHeaderView, 在向下拖拉刷新，过临界值，放手后，屏幕出现一个竖的滚动条，从屏幕的最左边飞到屏幕最右边，如果换成TextField或是其它控件，没有出现这种情况，什么原因呢？

**Comment by twmsh** [comment]
xcode 6.3.1+swift+MJRefresh 1.4.5，在iphone4（真机+模拟器）7.1滚动条不正常，在iphone5s(真机+模拟器)滚动条正常。

**Comment by CoderMJLee** [comment]
试试最新的2.0版本？
