### ISSUE TITLE
iOS 13适配 实现- (void)scrollViewDidScroll:(UIScrollView *)scrollView 并调用@property (nonatomic, readonly) NSArray<__kindof UITableViewCell *> *visibleCells;属性动画失效

### ISSUE THREAD

**Issue by pengshengsongcode** [CoderMJLee/MJRefresh#1331]
Xcode - Version 11.0 beta (11M336w)
macOS Mojave 10.14.4
iPhoneXS iOS 13

配demo

[mj.zip](https://github.com/CoderMJLee/MJRefresh/files/3519395/mj.zip)

**Comment by wolfcon** [comment]
你的代码里哪里有动画?

**Comment by wolfcon** [comment]
哦, 我了解了. 
你为什么要在 `scrollViewDidScroll` 方法中调用 `visibleCell`? 
scrollView 在 scroll 时不断会调用 `scrollView` 的 `layoutSubviews` 方法, 用以刷新界面

`visibleCell` 在调用时, 同时会调用 `TabbleView` 的 `layoutSubviews` 方法.
这就导致 `TabbleView` 在 `scrollViewDidScroll` 时调用 `visibleCell`, 会导致不断的 `layoutSubViews`. 你这样做是非常不明智的.

你可以试试在 `scrollViewDidScroll` 中把 `visibleCell` 换成 `layoutSubviews`

ScrollView. 手指拖动 触发 `layoutSubviews`, 后续会触发 `scrollViewDidScroll`, 你这里又来 `layoutSubviews`

**Comment by pengshengsongcode** [comment]
你把visibleCells注释掉，再点cell会有下拉刷新，打开注释就没有了




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年08月21日 18:30，Frank 写道：

哦, 我了解了.
你为什么要在 scrollViewDidScroll 方法中调用 visibleCell?
scrollView 在 scroll 时不断会调用 scrollView 的 layoutSubviews 方法, 用以刷新界面

visibleCell 在调用时, 同时会调用 TabbleView 的 layoutSubviews 方法.
这就导致 TabbleView 在 scrollViewDidScroll 时调用 visibleCell, 会导致不断的 layoutSubViews. 你这样做是非常不明智的.

你可以试试在 scrollViewDidScroll 中把 visibleCell 换成 layoutSubviews

ScrollView. 手指拖动 触发 layoutSubviews, 后续会触发 scrollViewDidScroll, 你这里又来 layoutSubviews

**Comment by pengshengsongcode** [comment]
我们业务需求需要调用这个api，iOS 13之前这么写是没有问题的




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年08月21日 18:31，彭盛凇 写道：
你把visibleCells注释掉，再点cell会有下拉刷新，打开注释就没有了




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年08月21日 18:30，Frank 写道：

哦, 我了解了.
你为什么要在 scrollViewDidScroll 方法中调用 visibleCell?
scrollView 在 scroll 时不断会调用 scrollView 的 layoutSubviews 方法, 用以刷新界面

visibleCell 在调用时, 同时会调用 TabbleView 的 layoutSubviews 方法.
这就导致 TabbleView 在 scrollViewDidScroll 时调用 visibleCell, 会导致不断的 layoutSubViews. 你这样做是非常不明智的.

你可以试试在 scrollViewDidScroll 中把 visibleCell 换成 layoutSubviews

ScrollView. 手指拖动 触发 layoutSubviews, 后续会触发 scrollViewDidScroll, 你这里又来 layoutSubviews

**Comment by pengshengsongcode** [comment]
我们需求需要做悬浮cell




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年08月21日 18:34，彭盛凇 写道：
我们业务需求需要调用这个api，iOS 13之前这么写是没有问题的




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年08月21日 18:31，彭盛凇 写道：
你把visibleCells注释掉，再点cell会有下拉刷新，打开注释就没有了




| |
彭盛凇
邮箱：psscode@163.com
|

签名由 网易邮箱大师 定制

在2019年08月21日 18:30，Frank 写道：

哦, 我了解了.
你为什么要在 scrollViewDidScroll 方法中调用 visibleCell?
scrollView 在 scroll 时不断会调用 scrollView 的 layoutSubviews 方法, 用以刷新界面

visibleCell 在调用时, 同时会调用 TabbleView 的 layoutSubviews 方法.
这就导致 TabbleView 在 scrollViewDidScroll 时调用 visibleCell, 会导致不断的 layoutSubViews. 你这样做是非常不明智的.

你可以试试在 scrollViewDidScroll 中把 visibleCell 换成 layoutSubviews

ScrollView. 手指拖动 触发 layoutSubviews, 后续会触发 scrollViewDidScroll, 你这里又来 layoutSubviews

**Comment by dong09000** [comment]
被炸过来了，这位兄弟，你可以尝试写一个继承自 UITableView 的 控件，重写其 layoutSubViews，在其中处理这个问题即可； 您在 scrollViewDidScroll 这个方法中做操作本身就是有问题的，它会触发 UIScrollView（TableView）的layoutSubViews，所以这个方法中拿到的visibleCells的frame是不准确的；还有你在UITrackingMode做这么多工作不担心卡帧？

**Comment by dong09000** [comment]
还有，悬浮cell为啥不直接使用 Plain样式的 sectionHeader？

**Comment by wolfcon** [comment]
你要做你的需求, 应该从如下的协议中找寻答案, 不是无休止在 Scroll 回调里调用 `visibleCell`, Scroll 回调触发非常频繁. 不应该将刷新界面的工作 x2. 

```objc
// Display customization

- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)tableView:(UITableView *)tableView willDisplayHeaderView:(UIView *)view forSection:(NSInteger)section API_AVAILABLE(ios(6.0));
- (void)tableView:(UITableView *)tableView willDisplayFooterView:(UIView *)view forSection:(NSInteger)section API_AVAILABLE(ios(6.0));
- (void)tableView:(UITableView *)tableView didEndDisplayingCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath*)indexPath API_AVAILABLE(ios(6.0));
- (void)tableView:(UITableView *)tableView didEndDisplayingHeaderView:(UIView *)view forSection:(NSInteger)section API_AVAILABLE(ios(6.0));
- (void)tableView:(UITableView *)tableView didEndDisplayingFooterView:(UIView *)view forSection:(NSInteger)section API_AVAILABLE(ios(6.0));

// Variable height support

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section;
```

**Comment by pengshengsongcode** [comment]
首先我明白你的意思和你推荐的做法是可以实现我们的需求，其次就是为什么iOS 13之前没有问题，iOS 13之后就出问题了

**Comment by wolfcon** [comment]
每一版 SDK, 内部的实现机制都有可能发生变化, 你需要尽量少的依赖这种(This works fine)的方式去实现需求. 多去深究一下更加优雅的实现方式才是正道🤪
