### ISSUE TITLE
每个cell的高度为taleView的高度时，上拉加载更多和isPagingEnabled冲突，contentoffset不准

### ISSUE THREAD

**Issue by baishikele** [CoderMJLee/MJRefresh#1332]
每个cell的高度为taleView的高度时，上拉加载更多和isPagingEnabled冲突，contentoffset不准

**Comment by 008v** [comment]
the same issue.

**Comment by wolfcon** [comment]
Duplicate of #311

**Comment by magicaldevil** [comment]
这个问题跟有没有使用本框架无关，把UITableView设置如下的几个属性值，再看一看：
estimatedRowHeight = 0，estimatedSectionHeaderHeight = 0，estimatedSectionFooterHeight = 0
