### ISSUE TITLE
iOS13,gif图片太大

### ISSUE THREAD

**Issue by MrGuys** [CoderMJLee/MJRefresh#1334]
**描述bug**
清晰简单地描述这个bug是啥
在iOS13下，原本正常的gif会变的很大，不知道怎么解决
**必现/偶发?**
必现

**你期望的结果是什么？**
跟iOS13之前的版本一样就好了

**截图**
如果有必要的话，请上传几张截图
![image](https://user-images.githubusercontent.com/17960104/64139475-97fb6600-ce33-11e9-9de0-5aa296160f1f.png)

**运行环境**
 - iPad
 - iOS13

**Comment by wolfcon** [comment]
Demo? 截图?

**Comment by MrGuys** [comment]
不是尺寸问题，同样的图，在iOS13以下就是正常的。而且，iOS 13的iPhone 8跟iOS13的iPad会出现太大的，问题，但是iOS 13的XR就是正常显示的

**Comment by MrGuys** [comment]
![data_reload](https://user-images.githubusercontent.com/17960104/64220123-cabc6180-cefa-11e9-88a1-bc22a8cd8f30.gif)
就是这个图

**Comment by MrGuys** [comment]
` NSString *imgName = @"data_reload";
    UIImage *image = [UIImage imageWithGIFNamed:imgName];

    
    MJRefreshGifHeader *header =[MJRefreshGifHeader headerWithRefreshingTarget:self refreshingAction:@selector(refreshData)];
    [header setImages:@[image] forState:MJRefreshStateRefreshing];
    [header setImages:@[image] forState:MJRefreshStateIdle];
    [header setImages:@[image] forState:MJRefreshStatePulling];
    header.lastUpdatedTimeLabel.hidden= YES;//如果不隐藏这个会默认 图片在最左边不是在中间
    
    [header setTitle:@"啊哦，这都被你发现了" forState:MJRefreshStateIdle];
    [header setTitle:@"松手！我要回家" forState:MJRefreshStatePulling];
    [header setTitle:@"略略略，玩得开心~" forState:MJRefreshStateRefreshing];
    
    self.tableView.mj_header = header;`

**Comment by wolfcon** [comment]
麻烦抽一个 demo 出来吧. `imageWithGIFNamed:` 估计是这个方法的猫腻

**Comment by MrGuys** [comment]
改成MJDemo里面的方法，用图片数组来做就👌了，感谢大佬提醒

**Comment by Smeegol** [comment]
已经是图片数组做GIF动画，仍然必现

**Comment by TalkingJourney** [comment]
同样遇到，图片数组做GIF动画，也是必现

**Comment by JRJian** [comment]
同样遇到，图片数组做GIF动画，也是必现

**Comment by wolfcon** [comment]
上 Demo @JRJian

**Comment by bolee** [comment]
现在还是有，和是否数组设置没关系吧

**Comment by bolee** [comment]
最新的iOS17.5.1

**Comment by bolee** [comment]
经过测试是因为下拉刷新还未结束，就调用beginRefreshing导致的，做判断修复后就没问题了
