### ISSUE TITLE
MJRefreshBackNormalFooter arrowView 没有更多时不能消失

### ISSUE THREAD

**Issue by csc-EricWu** [CoderMJLee/MJRefresh#1335]
**描述bug**
清晰简单地描述这个bug是啥
1.在使用MJRefreshBackNormalFooter 上拉加载更多，网络返回我会调用endRefreshing 
2.判断数据是否有更多数据。如果没有则调用endRefreshingWithNoMoreData 隐藏arrowView.hidden = YES
3.arrowView 仍然显示，原因是调用endRefreshing会进行一个0.4秒的动画，动画成功后又将arrowView.hidden = NO

**必现/偶发?**
必现

**怎么样重现这个bug**
```
 NetworkManager.request(api: api, parameters: params) { [weak self] succeed, response in
            self?.dismissHUD()
            self?.listView.refreshControl?.endRefreshing()
            self?.listView.mj_footer.endRefreshing()
            if succeed {
                var data: Any = []
                if PackageManager.checkResponseSucceed(json: response, data: &data) {
                    let json = JSON(data as Any)
                    if let list = JSONDeserializer<WalletDetailModel>.deserializeModelArrayFrom(array: json["list"].arrayObject) {
                        self?.dataSource = list as! [WalletDetailModel]
                        if list.count < pageSize {
                            self?.listView.mj_footer.endRefreshingWithNoMoreData()
                        }
                    }
                    self?.defaultView.isHidden = self?.dataSource.count != 0
                    self?.listView.reloadData()
                } else {
                    let json = JSON(response as Any)
                    showToast(message: json[JSON_MSG_KEY].stringValue)
                }
            } else {
                CRPresentAlert(title: nil, msg: kNetworkFailureMessage, handler: { [weak self] action in
                    if "重试" == action.title {
                        self?.loadData(needLoading: needLoading, directionDown: directionDown)
                    }
                }, canel: "取消", action: "重试")
            }
        }
```
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
`endRefreshing` 不要和 `endRefreshingWithNoMoreData` 一起使用.

另外你的代码数据跟 View 的操作耦合的太严重了. 重构一下吧少年

**Comment by csc-EricWu** [comment]
就这么给关了？这个处理很正常把，数据够就可以继续刷新，不够则没有更多。

**Comment by wolfcon** [comment]
不要重复调用, 保持逻辑一致性, 因为你不能保证封装库不重构, 不依赖某黑科技, 不采用特殊机制 等等这些你都无法保证, 你能保证的是你的代码, 行为执行的一致性, 而不是不负责任的少些代码(这些其实是由于代码结构混乱造成的)

**Comment by csc-EricWu** [comment]
// 根据状态做事情
    if (state == MJRefreshStateIdle) {
        if (oldState == MJRefreshStateRefreshing) {
            self.arrowView.transform = CGAffineTransformMakeRotation(0.000001 - M_PI);
            [UIView animateWithDuration:MJRefreshSlowAnimationDuration animations:^{
                self.loadingView.alpha = 0.0;
            } completion:^(BOOL finished) {
                // 防止动画结束后，状态已经不是MJRefreshStateIdle
                if (state != MJRefreshStateIdle) return;
                
                self.loadingView.alpha = 1.0;
                [self.loadingView stopAnimating];
                
                self.arrowView.hidden = NO;
            }];
        } else {

**Comment by csc-EricWu** [comment]
// 防止动画结束后，状态已经不是MJRefreshStateIdle
                if (state != MJRefreshStateIdle) return;

这是mj 的代码这里只需要把state 改为_state 就行了。因为我是先调用endRefreshing，然后再调用endRefreshingWithNoMoreData 动画结束回来_state 已经改变了。

**Comment by csc-EricWu** [comment]
用state 判断，会被block引用，所以这个判断永远无效。应该是个bug

**Comment by wolfcon** [comment]
的确是有这个问题

**Comment by csc-EricWu** [comment]
[https://github.com/CoderMJLee/MJRefresh/pull/1336](url)
修复了，帮忙合并下。
