### ISSUE TITLE
在使用重新布局的gif类型的header在UIwebview中使用会产生EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by openUmbrella** [CoderMJLee/MJRefresh#1339]
**描述bug**
我通过继承MJRefreshGifHeader类来重新布局子控件, 想要把动画图片放在顶部. 然后在ScrollView中使用正常. 但是在UIWebView中, 如果将statelabel和lastupdatetimeLabel 都显示或者隐藏, 使用正常. 但是当隐藏其中之一的时候, 就会报EXC_BAD_ACCESS.

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 重写 placeSubviews 方法, 重新布局gifview, statelabel, lastupdatetimeLabel
2. 隐藏statelabel和lastupdatetimeLabel中的一个 hidden 为true
3. 会报EXC_BAD_ACCESS
4. 具体布局代码如下:
```objc
if (!self.stateLabel.hidden) {
        // 定义高度余量
        CGFloat gapHeight = 6;
        // 图片的高度
        CGFloat imageH = self.gifView.image.size.height + gapHeight;
        
      CGFloat labelH = self.stateLabel.xy_textHeight + gapHeight;
      // 设置frame
      self.gifView.mj_h = imageH;
      self.stateLabel.frame = CGRectMake(0, imageH + self.labelLeftInset, self.mj_w, labelH);
      self.mj_h = imageH + labelH  + self.labelLeftInset;
      
      self.lastUpdatedTimeLabel.frame = CGRectZero;
     
    }
```

**截图**
报错的地方
![image](https://user-images.githubusercontent.com/17615716/64497372-13e82900-d2e0-11e9-8d40-2662339ab987.png)

**解决方案**
通过排查, 解决的方法是将 数值变量的单位由CGFloat设置为NSInteger, 就这样不报错了

按理说如果使用CGFloat是没毛病的🤣🤣

**Comment by wolfcon** [comment]
麻烦来个 Demo? 我也复现下...

**Comment by openUmbrella** [comment]
重新新建了一个demo，刚开始跑的时候出现过一次。后来再复现不了了😅😅
我写了一个在React-Native中使用MJRefresh的库[react-native-mjrefresh-ios](https://github.com/openUmbrella/react-native-mjrefresh-ios)
在里面的example里面有那样的一个例子，在那样的环境中百分百会出现这个问题。

**Comment by openUmbrella** [comment]
![image](https://user-images.githubusercontent.com/17615716/69620347-39333a80-1078-11ea-974c-1fd301e6bc85.png)
![image](https://user-images.githubusercontent.com/17615716/69620453-62ec6180-1078-11ea-8e17-1ac8afa9a03f.png)
