### ISSUE TITLE
1.4.6这个版本没有放到cocoapod上吧？

### ISSUE THREAD

**Issue by sdaheng** [CoderMJLee/MJRefresh#134]
[!] Unable to satisfy the following requirements:

- `MJRefresh (~> 1.4.6)` required by `Podfile`

The easiest way to use pull-to-refresh
   pod 'MJRefresh', '~> 1.4.5'
   - Homepage: https://github.com/CoderMJLee/MJRefresh
   - Source:   https://github.com/CoderMJLee/MJRefresh.git
   - Versions: 1.4.5, 1.4.4, 1.4.3, 1.4.1, 1.4.0,。。。

**Comment by CoderMJLee** [comment]
谢谢提醒，刚传到pod
