### ISSUE TITLE
KMNavigationBarTransition 与 MJRefresh 一起用会导致调用 beginRefreshing 和 endRefreshing 时导航栏闪动

### ISSUE THREAD

**Issue by Frozen-Tofu** [CoderMJLee/MJRefresh#1340]
**描述bug**
KMNavigationBarTransition 与 MJRefresh 一起用会导致调用 beginRefreshing 和 endRefreshing 时导航栏闪动，而使用系统的 UIRefreshControl 不会出现这个问题，因为历史原因无法做迁移。

**必现/偶发?**
必现

**怎么样重现这个bug**
0、引入 KMNavigationBarTransition 和 MJRefresh
1、页面添加 UITableView，为 tableView 添加 MJRefresh 头部
2、viewDidLoad 中调用 beginRefreshing

**你期望的结果是什么？**
仅 tableView 发生位移

**截图**
![未命名 2019-09-11 10_51_19](https://user-images.githubusercontent.com/4312700/64664570-226e4600-d482-11e9-9945-065d2b018310.gif)
与 UITabBarController 无关，在无 tabBar 的情况下也会发生

**运行环境**
 - iPhone 6s
 - iOS 12.4
 - Xcode 10.3

**Comment by wolfcon** [comment]
```objc
- (void)km_adjustScrollViewContentOffsetIfNeeded {
    UIScrollView *scrollView = self.km_visibleScrollView;
    if (scrollView) {
        UIEdgeInsets contentInset;
#ifdef __IPHONE_11_0
        if (@available(iOS 11.0, *)) {
            contentInset = scrollView.adjustedContentInset;
        } else {
            contentInset = scrollView.contentInset;
        }
#else
        contentInset = scrollView.contentInset;
#endif
        const CGFloat topContentOffsetY = -contentInset.top;
        const CGFloat bottomContentOffsetY = scrollView.contentSize.height - (CGRectGetHeight(scrollView.bounds) - contentInset.bottom);
    
        CGPoint adjustedContentOffset = scrollView.contentOffset;
        if (adjustedContentOffset.y > bottomContentOffsetY) {
            adjustedContentOffset.y = bottomContentOffsetY;
        }
        if (adjustedContentOffset.y < topContentOffsetY) {
            adjustedContentOffset.y = topContentOffsetY;
        }
        [scrollView setContentOffset:adjustedContentOffset animated:NO];
    }
}
```

你使用的这个库, 通过各种判断, 修改 `adjustedContentInset` 或 `contentInset`, 这 2 个属性也是 MJRefresh 正常工作时需要更改的属性, 所以你自己得取舍或者修改源码以便于同时适配 2 个库. 由于修改的时机在每个库中都是不同的. 所以总会导致各种各样的问题. 无法单独通过修改一个库来解决.

建议你在 viewDidAppear 中调用 `beginRefresh` 或许应该可以避免这个问题 (在不修改源码的情况下)
