### ISSUE TITLE
在UIPageViewController切换到第二个视图控制器的时候，数据没回来之前自动下拉刷新会自己关闭

### ISSUE THREAD

**Issue by zfy199466** [CoderMJLee/MJRefresh#1341]
我使用的是MJRefresh 3.2.0的。iPhone XsMax 12.2的模拟器发现的这个问题。
我的首页有四个切换的菜单视图控制器，我使用UIPageViewController来实现他们的，并且每个视图控制器都开启了自动下拉刷新beginRefreshing。
但是我发现在第一个默认的视图控制器切换到第二个视图控制器的时候，我的数据明明还在加载，数据没有返回来的，但是下拉刷新就自己关闭结束了。但是在第一个默认的视图控制器不会出现这个问题点。
最后我找出是因为在视图切换的时候，MJRefresh调用了基类里面的willMoveToWindow方法。请问这种情况需要怎么解决呢？麻烦告知下，谢谢。

**Comment by wolfcon** [comment]
是这样的, 因为要保证在切换控制器时顶部 Insets 保持正常, 否则再切换后的控制器如果对顶部 insets 做了操作, 就会导致之前的界面在刷新之前的状态异常, 刷新恢复后恢复成旧的值, 导致错误

其实切换控制器后只是停止了刷新 UI. 后台数据逻辑依靠你自己的实现, 你可以保存数据在界面 willAppear 时刷新界面. 后台的数据请求逻辑(你如果做了的话)并没有停止.

如果真的想实现回来时还是刷新的话, 建议你在刷新逻辑里做一个状态判断有数据请求中时, 开始刷新, 但是不调用请求(过滤掉), 可以实现你的需求.

**Comment by zfy199466** [comment]
您好。我录了gif，您看看就知道我描述的具体内容是怎么样的了。

MJRefresh -  3.1.15.7 版本下的效果，这个就是我想要的效果，每次第一次切换过去的视图控制器都会自动刷新而且等数据回来才结束刷新
![Untitled1](https://user-images.githubusercontent.com/6743573/65105066-48f22b00-da06-11e9-8489-d0457dabf778.gif)

MJRefresh - 3.2.0 版本下的效果，第一个页面是没有问题的，会等到数据加载结束后才结束刷新，但是我切换到第二个或者第三个的时候，那时候数据还在拉取，但是就自动结束了下拉刷新，导致展示数据的时候会有一定时间的延时，让人觉得有卡顿
![Untitled2](https://user-images.githubusercontent.com/6743573/65105165-9c647900-da06-11e9-9133-063e8d9ad66f.gif)

这是我写的代码，您可以在pod文件指定版本号后重新试试看。有时间您可以研究看看，谢谢
[MJRefreshTestDemo.zip](https://github.com/CoderMJLee/MJRefresh/files/3624306/MJRefreshTestDemo.zip)

**Comment by wolfcon** [comment]
这个问题上面已经回答过了. 因为会导致收不回去的 bug, 所以暂时先切换后就停止刷新了.

已经有初步构想解决这个问题了. 等有时间了实现后就应该没问题了.

**Comment by wangyongy** [comment]
我也出现了这个问题,现在解决了吗

**Comment by wangyongy** [comment]
> 这个问题上面已经回答过了. 因为会导致收不回去的 bug, 所以暂时先切换后就停止刷新了.
> 
> 已经有初步构想解决这个问题了. 等有时间了实现后就应该没问题了.

实现了吗

**Comment by mushanlianshi** [comment]
> 



> 这个问题上面已经回答过了. 因为会导致收不回去的 bug, 所以暂时先切换后就停止刷新了.
> 
> 已经有初步构想解决这个问题了. 等有时间了实现后就应该没问题了.

实现了吗
