### ISSUE TITLE
MJRefreshAutoNormalFooter调整位置

### ISSUE THREAD

**Issue by jianqingyu** [CoderMJLee/MJRefresh#1342]
请问我想用autonormalfooter的功能、又要backnormalfooter的页面底部位置、怎么实现啊

**Comment by wolfcon** [comment]
请描述的更详细一点, 什么功能

**Comment by jianqingyu** [comment]
就是说我要autonormalfooter的上拉到最后直接加载、不能像backfooter一样要再拉一下才加载，但是UI又要想backfooter一样 不能跟在tableview的后面 要跟在屏幕的后面

**Comment by wolfcon** [comment]
自己根据源码实现就好
