### ISSUE TITLE
iOS13 大标题情况下，无法下拉刷新

### ISSUE THREAD

**Issue by ieliwb** [CoderMJLee/MJRefresh#1343]
**描述bug**
iOS13 大标题情况下，无法下拉刷新

**必现/偶发?**
必现

有人遇到过吗？

**Comment by qiangge8888** [comment]
[self.tableView setContentOffset:CGPointMake(0, - self.tableView.mj_header.frame.size.height) animated:YES];   增加这行代码试试

**Comment by wolfcon** [comment]
大标题的适配不是很好. 建议你先用系统的.(系统的也比较诡异)
