### ISSUE TITLE
支持富文本

### ISSUE THREAD

**Issue by PggMan** [CoderMJLee/MJRefresh#1344]
杰哥我再实现富文本的时候发现一个问题。

@implementation MJRefreshComponent 的262行

`stringWidth =[self.text
                      boundingRectWithSize:size
                      options:NSStringDrawingUsesLineFragmentOrigin
                      attributes:@{NSFontAttributeName:self.font}
                      context:nil].size.width;`

如果我给lable赋值的是富文本，到这里就cresh了，因为这个计算lable尺寸的函数式NSStreing的。不支持富文本文字。

我个人觉得改成
stringWidth = [self sizeThatFits:CGSizeMake(MAXFLOAT, MAXFLOAT)]

会更好点

**Comment by wolfcon** [comment]
来个 Demo?

**Comment by wolfcon** [comment]
正常你应该自己根据 `Label` 的 `numberOfLines` 的值, 来计算 `Label` 的宽高. 不要简单的使用 `mj_textWidth` 来算宽度.

你可能会用到这个方法
```swift
func textRect(forBounds bounds: CGRect, limitedToNumberOfLines numberOfLines: Int) -> CGRect
```
