### ISSUE TITLE
iOS13 beginRefreshing无效

### ISSUE THREAD

**Issue by wangyongy** [CoderMJLee/MJRefresh#1345]
**描述bug**
清晰简单地描述这个bug是啥
iOS13环境下,点击上方按钮调用beginRefreshing刷新页面,页面并没有出现下拉刷新动画,但却触发了RefreshingBlock回调
**必现/偶发?**
必现

**Comment by wangyongy** [comment]
前提是scrollViewDidScroll里调用了visibleCells方法

**Comment by wolfcon** [comment]
Duplicate of #1331
