### ISSUE TITLE
iOS13，WKWebview上加gifheader，首次刷新图片被拉伸很大

### ISSUE THREAD

**Issue by HemingTai** [CoderMJLee/MJRefresh#1346]
**描述bug**
iOS13，WKWebview上加gifheader，首次刷新图片被拉伸很大

**必现/偶发?**
必现

**截图**
![Simulator Screen Shot - iPhone 11 Pro - 2019-09-27 at 15 36 10](https://user-images.githubusercontent.com/13804911/65751208-9d02bb00-e13c-11e9-83b5-7068d08dafa3.png)

**Comment by HemingTai** [comment]
首次加载wkwebview并调用下拉刷新，gif图会被拉伸，再次下拉刷新，恢复正常

**Comment by Smeegol** [comment]
我也必现啊
你们没试出来吗
怎么就移除bug标签呢

**Comment by wolfcon** [comment]
@Smeegol 请提供 Demo

> 怎么就移除bug标签呢

没看到加了个标签吗? 😆

**Comment by MillerJiang538** [comment]
请李大大赶紧解决啊

**Comment by wolfcon** [comment]
#1357 
既然你们不给例子, 那么我写一个, 并没有你们说的这个问题.

**Comment by ToLengSon** [comment]
初始化的时候，这个时候已经添加了图标，但是没有设置ImageView的size是0，默认显示的是图片的大小，在添加header的时候，调用下强制布局，让在显示的时候就设置好ImageView的大小
