### ISSUE TITLE
这个MJRefresh (3.2.0) 的 Crash怎么解决？

### ISSUE THREAD

**Issue by zxl777** [CoderMJLee/MJRefresh#1347]
在 scrollViewContentOffsetDidChange 这一行出错“EXC_BAD_ACCESS KERN_PROTECTION_FAILURE ”

用的是 MJRefresh (3.2.0) ， 这个Crash 我自己无法复现，是用户端偶然出现的。

Platform: ios
Date: 2019-09-28T15:16:00Z
OS Version: 12.4.1 (16G102)
Device: iPhone 6s Plus
RAM Free: 6%
Disk Free: 8.6%
#0. Crashed: com.apple.main-thread
0 Foundation 0x1bd713f80 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 44
1 Foundation 0x1bd666664 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey🔑key:usingBlock:] + 68
2 Foundation 0x1bd71005c _NSSetPointValueAndNotify + 284
3 UIKitCore 0x1e9a0fd60 -[UIScrollView(UIScrollViewInternal) _adjustContentOffsetIfNecessary] + 60
4 UIKitCore 0x1e99f43a4 -[UIScrollView _updateForChangedScrollRelatedInsets] + 48
5 UIKitCore 0x1e99f40cc -[UIScrollView setContentInset:] + 88
6 UIKitCore 0x1e97e3170 -[UITableView setContentInset:] + 128
7 MJRefresh 0x1030801b0 -[MJRefreshHeader scrollViewContentOffsetDidChange:] + 70 (MJRefreshHeader.m:70)
8 MJRefresh 0x10307e160 -[MJRefreshComponent observeValueForKeyPath:ofObject:change:context:] + 120 (MJRefreshComponent.m:120)

**Comment by zxl777** [comment]
Crash重现方法：
下拉刷新，旋转动画还没消失时，马上上拉一下，就闪退了。

证实 pod 'MJRefresh' 的代码
和 pod 'MJRefresh', :git => 'https://github.com/CoderMJLee/MJRefresh'  不同。
不过改用MJRefresh最新的代码，问题依旧。

然后用原生UIRefreshControl替换下拉的MJRefresh的代码，问题解决。
下拉还用MJRefresh的。

**Comment by wolfcon** [comment]
麻烦贴一个 demo?
