### ISSUE TITLE
3.2.0版本中在最新的系统版本中会Crash

### ISSUE THREAD

**Issue by WenboBoy88** [CoderMJLee/MJRefresh#1348]
**描述bug**
在最新的系统iOS13、iOS12.4.1中  使用SnapKit自定义动态布局CollectionViewCell，下拉刷新时会直接Crash掉，系统没升级之前的是正常的。

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面    很普通的自定义布局的界面
2. 点击哪个位置   下拉刷新，松手
3. 滚动到哪个位置 随意滚动，只要下拉刷新时
4. 发生了什么错误 Crash
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c2af71 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff23aab26e -[__NSArrayM objectAtIndex:] + 142
	4   UIKitCore                           0x00007fff469c6a2e -[_UIFlowLayoutInfo setSizes:forItemsAtIndexPaths:] + 626
	5   UIKitCore                           0x00007fff469a92d3 -[UICollectionViewFlowLayout _didPerformUpdateVisibleCellsPass] + 179
	6   UIKitCore                           0x00007fff4696114c -[UICollectionView _updateVisibleCellsNow:] + 12376
	7   UIKitCore                           0x00007fff4696119e -[UICollectionView _updateVisibleCellsNow:] + 12458
	8   UIKitCore                           0x00007fff4696119e -[UICollectionView _updateVisibleCellsNow:] + 12458
	9   UIKitCore                           0x00007fff46964b37 -[UICollectionView layoutSubviews] + 353
	10  UIKitCore                           0x00007fff47636722 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
	11  QuartzCore                          0x00007fff2b030ef9 -[CALayer layoutSublayers] + 255
	12  QuartzCore                          0x00007fff2b0358ff _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 517
	13  UIKitCore                           0x00007fff47621a35 -[UIView(Hierarchy) layoutBelowIfNeeded] + 980
	14  UIKitCore                           0x00007fff4696cc0f -[UICollectionView setContentInset:] + 253
	15  MJRefresh                           0x0000000110e03784 -[UIScrollView(MJExtension) setMj_insetT:] + 308
	16  MJRefresh                           0x0000000110dff39f -[MJRefreshHeader scrollViewContentOffsetDidChange:] + 719
	17  MJRefresh                           0x0000000110dfbbc6 -[MJRefreshComponent observeValueForKeyPath:ofObject:change:context:] + 326
	18  Foundation                          0x00007fff25626032 NSKeyValueNotifyObserver + 329
	19  Foundation                          0x00007fff2562974f NSKeyValueDidChange + 499
	20  Foundation                          0x00007fff25629052 -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 741
	21  Foundation                          0x00007fff2562994b -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 68
	22  Foundation                          0x00007fff25624a06 _NSSetPointValueAndNotify + 304
	23  UIKitCore                           0x00007fff475c8586 -[UIScrollView _adjustContentOffsetIfNecessary] + 53
	24  UIKitCore                           0x00007fff475a5b4a -[UIScrollView _updateForChangedScrollRelatedInsets] + 39
	25  UIKitCore                           0x00007fff475a5887 -[UIScrollView setContentInset:] + 178
	26  UIKitCore                           0x00007fff4696cb54 -[UICollectionView setContentInset:] + 66
	27  MJRefresh                           0x0000000110e03784 -[UIScrollView(MJExtension) setMj_insetT:] + 308
	28  MJRefresh                           0x0000000110e00097 __28-[MJRefreshHeader setState:]_block_invoke_2 + 471
	29  UIKitCore                           0x00007fff4762a1e6 +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 528
	30  UIKitCore                           0x00007fff4762a804 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:animations:completion:] + 86
	31  MJRefresh                           0x0000000110dffe4a __28-[MJRefreshHeader setState:]_block_invoke.77 + 282
	32  libdispatch.dylib                   0x0000000111b31df0 _dispatch_call_block_and_release + 12
	33  libdispatch.dylib                   0x0000000111b32d64 _dispatch_client_callout + 8
	34  libdispatch.dylib                   0x0000000111b40e1c _dispatch_main_queue_callback_4CF + 1500
	35  CoreFoundation                      0x00007fff23afb699 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	36  CoreFoundation                      0x00007fff23af62f9 __CFRunLoopRun + 2329
	37  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	38  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	39  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	40  CRM                                 0x000000010d1cda5b main + 75
	41  libdyld.dylib                       0x00007fff5123bcf5 start + 1
	42  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果
和之前的系统一样，正常运行不闪退

**截图**
如果有必要的话，请上传几张截图
![image](https://user-images.githubusercontent.com/13030959/65832152-e6950680-e2f2-11e9-87f9-bde74df2cad8.png)
![image](https://user-images.githubusercontent.com/13030959/65832221-6cb14d00-e2f3-11e9-82ef-89f286173887.png)

**运行环境**
 - iPhone11
 - iOS13
 - Xcode11

**Comment by WenboBoy88** [comment]
最近这个闪退的问题看到好多人都提出来了

**Comment by wolfcon** [comment]
你的这个问题. 很明显是由于你的约束问题...

**Comment by YAANNZ** [comment]
解决了吗？

**Comment by Hesse-Huang** [comment]
@wolfcon But this crash is not happening on iOS 12 or earlier using the same demo attached, so I think it's MJRefresh's issue. Please check.
