### ISSUE TITLE
CocoaPods v1.8.3 使用MJRefresh v3.2.0拉到的是老代码？

### ISSUE THREAD

**Issue by ryan7cruise** [CoderMJLee/MJRefresh#1349]
**描述bug**
CocoaPods v1.8.3 使用MJRefresh v3.2.0拉到的是老代码。
`MJRefreshHeader.m`这个文件里面，v3.1.17 主要修正正在刷新时切换控制器导致的顶部 Insets 异常的问题，相关的代码没有更新。

**必现/偶发?**
必现

**怎么样重现这个bug**
pod 'MJRefresh', '~> 3.2.0'
pod update

**你期望的结果是什么？**
拉取到最新的代码

**截图**
本地代码：
![QQ20191007-175710](https://user-images.githubusercontent.com/20790857/66302938-79a1f200-e92c-11e9-9845-90facbace364.png)

GitHub master代码：
<img width="979" alt="QQ20191007-175822@2x" src="https://user-images.githubusercontent.com/20790857/66302960-86bee100-e92c-11e9-99f9-b43b11a1c703.png">

**运行环境**
 - Xcode11

**Comment by wolfcon** [comment]
这不是 CocoaPods 的问题吗? 你是不是切换错工程了?

**Comment by ryan7cruise** [comment]
![QQ20191008-163529](https://user-images.githubusercontent.com/20790857/66380282-b1bb3a80-e9e9-11e9-8df9-aa4628ec5c27.png)

 ~/Library/Caches/CocoaPods/Pods/Release/MJRefresh/3.2.0-ed450/MJRefresh/Base

MJRefreshHeader.m

这个代码真没更新...

**Comment by ryan7cruise** [comment]
> 这不是 CocoaPods 的问题吗? 你是不是切换错工程了?

![QQ20191008-163529](https://user-images.githubusercontent.com/20790857/66380412-f515a900-e9e9-11e9-8c64-23815a67030d.png)

~/Library/Caches/CocoaPods/Pods/Release/MJRefresh/3.2.0-ed450/MJRefresh/Base

cat MJRefreshHeader.m

这个真没更新...

**Comment by ryan7cruise** [comment]
@wolfcon

**Comment by wolfcon** [comment]
> 这不是 CocoaPods 的问题吗?

**Comment by ryan7cruise** [comment]
> > 这不是 CocoaPods 的问题吗?

@wolfcon 感谢回复。但是，我直接下载release的source code还是老代码。

<img width="919" alt="QQ20191009-152626@2x" src="https://user-images.githubusercontent.com/20790857/66460447-8730b680-eaa9-11e9-9f8e-97bc82e29318.png">

![QQ20191009-152828](https://user-images.githubusercontent.com/20790857/66460452-8a2ba700-eaa9-11e9-8bd7-460f9ef0aaa1.png)

**Comment by wolfcon** [comment]
还没有更新库~最新的代码并不在 3.2.0 里啊
