### ISSUE TITLE
iOS13，使用带约束的CollectionViewCell会Crash

### ISSUE THREAD

**Issue by qufeng33** [CoderMJLee/MJRefresh#1351]
**描述bug**
在最新的系统iOS13（未测试低版本）中 使用自定义带约束的CollectionViewCell，下拉刷新时会直接Crash掉

**必现/偶发?**
必现

**怎么样重现这个bug**
附上[附件](https://github.com/qufeng33/MJRefreshDemo)
附件内有2个例子，下啦刷新均会复现问题

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果
下啦刷新正常

**截图**
![图片1](https://i.loli.net/2019/10/18/URuZCwryc3QVPgi.png)
![图片2](https://i.loli.net/2019/10/18/jhsn9Ry7o15cEMz.png)

**运行环境**
 - iPhoneXR
 - iOS13.1.3
 - Xcode11

**额外的**
[DEMO](https://github.com/qufeng33/MJRefreshDemo)

**Comment by DoctorWiseman** [comment]
请问下这个bug修复了吗，我试了下新的commit，无法修复

**Comment by DoctorWiseman** [comment]
只在iPhoneXR 上出现

**Comment by wolfcon** [comment]
@DoctorWiseman #1353 你试的是这个吗?

**Comment by DoctorWiseman** [comment]
是的------------------ 原始邮件 ------------------
发件人: "Frank"<notifications@github.com>
发送时间: 2019年10月31日(星期四) 下午3:02
收件人: "CoderMJLee/MJRefresh"<MJRefresh@noreply.github.com>;
抄送: "DoctorWiseman"<450055185@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [CoderMJLee/MJRefresh] iOS13，使用带约束的CollectionViewCell会Crash (#1351)



@DoctorWiseman #1353 你试的是这个吗?
 
&mdash;

**Comment by wolfcon** [comment]
@DoctorWiseman 你那边能给出 demo 吗?
你测试的时候, 有 clean 工程吗?

**Comment by wolfcon** [comment]
@DoctorWiseman 你这边能给出 Demo 么? 我这边用他的例子没有问题了.

记得更新下 Pod (把 Podfile 的源改一下 )
```sh
pod 'MJRefresh', :git => 'https://github.com/CoderMJLee/MJRefresh.git', :branch => 'master'
```
再次执行
```sh
pod update MJRefresh
```

不要忘了 `Clean` (⌘+⇧+K) 

另外他 demo 中有误用 IGListKit 的地方改一下:
```objc
//[weakSelf.dataArray addObject:@""];
[weakSelf.dataArray addObject:@(NSDate.date.timeIntervalSince1970)];
```

**Comment by Hesse-Huang** [comment]
@wolfcon Thanks, it works!
