### ISSUE TITLE
ios13 切换暗黑模式更换菊花类型会出现2个菊花

### ISSUE THREAD

**Issue by YinZhifu** [CoderMJLee/MJRefresh#1352]
**描述bug**
ios13 来回多次切换暗黑模式更换菊花类型会多出个菊花

必现

**怎么样重现这个bug**
在程序里监听暗黑模式，一旦修改就变换菊花类型，深色变成白色菊花，浅色变成黑色菊花，来回切换就会出现多了一个菊花

![556404A45756845F14B6B83AEC9D37EF](https://user-images.githubusercontent.com/15342721/67175487-d9060480-f3f8-11e9-832f-248636081bb5.jpg)

**运行环境**
 - iPhone7
 - iOS13.1.3
 - Xcode11.1

**Comment by YinZhifu** [comment]
> 稍后会增加 Darkmode 支持. 不需要手动修改了.
> 
> 另外, 你是通过这种方式修改的吗?
> 
> ```objc
> xxx.mj_header.activityIndicatorViewStyle = UIActivityIndicatorViewStyleMedium;
> ```

我这个情况是在转菊花的时候来回切换暗黑模式出现的

**Comment by wolfcon** [comment]
之后这个会被禁用掉. 会报警告...⚠️

**Comment by wolfcon** [comment]
#1354
