### ISSUE TITLE
使用MJ的时候，下拉刷新菊花开始转然后执行下拉方法，这里有一个等待时间大概1.5秒的样子，可不可以设置成手指松开立刻执行刷新方法？？

### ISSUE THREAD

**Issue by SJQforIOS** [CoderMJLee/MJRefresh#1355]
我现在的需求是数据以及全部请求好了，使用MJ是为了上拉下拉切换数据，但是我在使用过程中发现  MJRefreshNormalHeader *header = [MJRefreshNormalHeader headerWithRefreshingTarget:self refreshingAction:@selector(loadTopNewData)]; 这个方法，loadTopNewData会在下拉手指离开屏幕，菊花大概转1.5s左右才会执行loadTopNewData方法，这个时间对我来说是不适合的，我希望是手离开屏幕后立马执行方法，请问这种有解决方法吗？

**Comment by wolfcon** [comment]
demo

**Comment by wolfcon** [comment]
自己自定义 Header 吧
