### ISSUE TITLE
同一个项目里，同样的初始代码，有的页面可以下拉刷新，但有的页面不可以，何故？

### ISSUE THREAD

**Issue by sharehoney** [CoderMJLee/MJRefresh#1356]
连下拉的箭头都不显示，空白的一片。

—— 是我哪里弄错了呢？继续寻找原因。。。

**Comment by sharehoney** [comment]
- (void)prepareMJRefreshAction {
    
    self.typeString = @"";
    self.keyString = @"...";
    
    self.theTable.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [self getCustomerListNetActionWithPage:1];
    }];
    
    self.theTable.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
        NSInteger nextPage = [...];
        [self getCustomerListNetActionWithPage:nextPage + 1];
    }];
    
}

**Comment by guojingjingghost** [comment]
我的也是请问你是遇到的什么问题，怎么解决的
