### ISSUE TITLE
iOS13下UICollectionView使用MJRefreshFooter时，下拉刷新时底部的cell会出现奇怪的动画

### ISSUE THREAD

**Issue by gongsunqingyang** [CoderMJLee/MJRefresh#1359]
**描述bug**
iOS13下UICollectionView使用MJRefreshFooter时，下拉到一定距离（最后一排cell离开屏幕），然后松开，底部的cell会出现奇怪的动画。iOS12及以下没有这个问题，我看市场上好多使用MJRefresh框架的应用都有这个问题。

**必现/偶发?**
必现

**怎么样重现这个bug**
iOS13下，当UICollectionView使用上拉和下拉控件时，下拉回弹时，底部的cell会凭空出现

**截图**
![2019-11-01 15-18-52 2019-11-01 15_19_31](https://user-images.githubusercontent.com/13862075/68008777-038a7400-fcbb-11e9-952d-4096247ab6b2.gif)

**运行环境**
 - iPhone Xs
 - iOS13.0
 - Xcode10

**Comment by wolfcon** [comment]
Demo? 另外你这个 gif 上没显示出来啊.
对于隐式动画问题. 可以参见

> 另外老哥, 你也是 CSGO 爱好者么..整天看着龙狙, 全系泰坦, 蓝宝石, 不蛋疼么

**Comment by gongsunqingyang** [comment]
@wolfcon 重新上传了图片
#227 属性已经没有了 
#737 #225 设置延迟无效

**Comment by wolfcon** [comment]
方便整一个 demo 吗

**Comment by fuhanzhang** [comment]
是有这个问题，下拉刷新，拉出屏幕的cell或者sectionHead在松手回到屏幕内的时候会这样。

**Comment by cwwise** [comment]
> 是有这个问题，下拉刷新，拉出屏幕的cell或者sectionHead在松手回到屏幕内的时候会这样。

我也遇到了

**Comment by miaodongCoder** [comment]
请问一下我页面一进来请求接口会自动调用下拉刷新的头视图动画 , 现在我这个页面有一些别的按钮 , 我想我点击这个按钮在请求别的接口的时候也给我显示出下拉刷新的动画 , 该怎么做? 下拉刷新动画有自己的调用动画接口么? 我最后想达到的效果就是页面有一个按钮 , 我点一次你给我自动下拉一次 ~

**Comment by fuhanzhang** [comment]
> 请问一下我页面一进来请求接口会自动调用下拉刷新的头视图动画 , 现在我这个页面有一些别的按钮 , 我想我点击这个按钮在请求别的接口的时候也给我显示出下拉刷新的动画 , 该怎么做? 下拉刷新动画有自己的调用动画接口么? 我最后想达到的效果就是页面有一个按钮 , 我点一次你给我自动下拉一次 ~

[self.tableView.mj_header beginRefreshing];

**Comment by miaodongCoder** [comment]
> > 请问一下我页面一进来请求接口会自动调用下拉刷新的头视图动画 , 现在我这个页面有一些别的按钮 , 我想我点击这个按钮在请求别的接口的时候也给我显示出下拉刷新的动画 , 该怎么做? 下拉刷新动画有自己的调用动画接口么? 我最后想达到的效果就是页面有一个按钮 , 我点一次你给我自动下拉一次 ~
> 
> [self.tableView.mj_header beginRefreshing];

谢谢您的回复 , 这个接口我之前试过不行 , 但是您一说完之后我再试用就好了...看来我之前使用的方式还是不太对 , 谢谢您的指导;

**Comment by wolfcon** [comment]
#1372

**Comment by forping** [comment]
> #1372 @fuhanzhang @cwwise @gongsunqingyang 试试吧
> 
> 原因是使用 UIViewAnimation 在做动画时会与 CollectionView 的渲染动画冲突. 引起的

什么时候发新包啊。

**Comment by wolfcon** [comment]
你们有试么...都没人给个回复.🤣

**Comment by johhHuYi** [comment]
3.3.0是否 能提交个podspec...看了最新的还是3.2.3...我这边目前也遇到该类型的问题了

**Comment by JohnSmithHY** [comment]
对了 针对渲染动画冲突的问题 什么时候发新包呀...
