### ISSUE TITLE
请问  mj哥  关于加载完所有数据的时候

### ISSUE THREAD

**Issue by wy19901227** [CoderMJLee/MJRefresh#136]
当我们加载完最后一页数据的时候，footerview应该显示的是，没有更多数据，同时箭头应该没有，这个应该怎么做？

**Comment by CoderMJLee** [comment]
[tableView.footer noticeNoMoreData];

**Comment by wy19901227** [comment]
没这个方法啊

**Comment by CoderMJLee** [comment]
有的，你要拿到footer对象。你看看我的Demo

**Comment by wy19901227** [comment]
最近跟新的嘛？  我这个版本的 footer还是个私有的属性呢

**Comment by CoderMJLee** [comment]
最新版和旧版本差别好大的哦。。。慎重使用
