### ISSUE TITLE
关于动态改变UICollectionView contentInset

### ISSUE THREAD

**Issue by FuckUmei** [CoderMJLee/MJRefresh#1360]
**描述bug**
 collectionView.contentInset = UIEdgeInsetsMake(100, 0, 0, 0);
 collectionView.mj_header.ignoredScrollViewContentInsetTop = 100;
这里是没有问题，数据超出全屏时滑动到最底部看到底部的footer。

 collectionView.contentInset = UIEdgeInsetsMake(150, 0, 0, 0);
 collectionView.mj_header.ignoredScrollViewContentInsetTop = 150;
但是，我再次改变contentInset，就看不到底部的footer，总是差一点。

**运行环境**
 - iPhone7
 - iOS11.4.1
 - Xcode11.1

**Comment by wolfcon** [comment]
1. Footer 用的什么? MJRefresh 的 Footer? 用的是哪一个 `footer`
2. 有无 `tabbar`
3. CollectionView 的 `automaticallyAdjustsScrollIndicatorInsets` 属性设置是什么
4. 在何处修改的 Inset
5. 最初修改 inset 的位置是在加载 footer 前还是后

最好还是上 Demo. 你这样片面的给出信息, 就要获得答案, 你觉得别人怎么帮你
