### ISSUE TITLE
iPhoneX系列在iOS13.2系统下崩溃，针对CollectionView下拉刷新（必现！）

### ISSUE THREAD

**Issue by ys323945** [CoderMJLee/MJRefresh#1361]
**描述bug**
当ColletionView的Item没有占满整个屏幕时，下拉刷新会崩溃在下面这一行。当超出屏幕范围下拉正常。

**必现/偶发?**
必现

**怎么样重现这个bug**
1、设置ColletionView的Item数量较少，不超过整个屏幕。
2、设备运行在iPhoneX系列上，并且在iOS13.2系统下。
3、下拉刷新崩溃。

调用方法:
`

        let header:MJRefreshNormalHeader = MJRefreshNormalHeader.init {
        }

      self.mj_header = header
`

**你期望的结果是什么？**
修复bug.

**截图**
![image](https://user-images.githubusercontent.com/15976276/68821755-1b55f500-06ca-11ea-99db-06cc787407f4.png)
![image](https://user-images.githubusercontent.com/15976276/68821900-8273a980-06ca-11ea-94dc-e4d25eb96c26.png)
![image](https://user-images.githubusercontent.com/15976276/68822460-ee0a4680-06cb-11ea-8d1a-e4f9c4a1b4ef.png)

**运行环境**
 - iPhoneXR模拟器,iPhone11模拟器,iPhone
 - iOS13.2
 - Xcode11.2.1

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
Demo?

**Comment by wolfcon** [comment]
Duplicate of #1351
