### ISSUE TITLE
swift版本-tableview上拉刷新没回调

### ISSUE THREAD

**Issue by KBvsMJ** [CoderMJLee/MJRefresh#1362]
tableview 上拉刷新不回调。
![image](https://user-images.githubusercontent.com/8489350/68946687-8dbff580-07ee-11ea-90e7-177f0deaca52.png)

**Comment by wolfcon** [comment]
你的 `SetupFooterRefresh` 方法都不贴出来, 代码也不贴出来, 就说没回调. 
你调用了吗?
