### ISSUE TITLE
好奇怪，我这里更新3.2.2后，MJRefreshAutoNormalFooter自动加载失效

### ISSUE THREAD

**Issue by JanWirt** [CoderMJLee/MJRefresh#1363]
**描述bug**
版本3.2.2，MJRefreshAutoNormalFooter无法自动加载，需要上拉才能触发。不知道跟项目里什么冲突导致了这个问题。

**必现/偶发?**
必现

**怎么样重现这个bug**
tableView和collectionView在版本3.2.2都出现了这个问题，回退3.2.0，恢复正常

**截图**
![截屏2019-11-19上午10 30 30](https://user-images.githubusercontent.com/17246517/69111613-08239a80-0ab9-11ea-8f6d-ffdb992976c2.png)

**运行环境**
 - iPhone8 plus
 - iOS13.0
 - Xcode11

**Comment by guojingjingghost** [comment]
我的也是 那个beginRefreshing()不行了 需要手动刷新

**Comment by guojingjingghost** [comment]
再次发现加上分页控制器的页面能正常刷新，单独的控制器不行  请尽快修正

**Comment by wolfcon** [comment]
#1366 你们试试这个版本.

**Comment by guojingjingghost** [comment]
MJRefreshAutoFooter 用这个footer都没了===你试过没？？？

**Comment by JanWirt** [comment]
> MJRefreshAutoFooter 用这个footer都没了===你试过没？？？

是不显示了，但是上拉功能还是可用，我是继承的这个类，自定义的刷新动画。

**Comment by wolfcon** [comment]
@guojingjingghost  `MJRefreshAutoFooter` 本来就是空的啊. 你是不是有什么误解? 
好好看文档不好吗. 普通的是`MJRefreshAutoNormalFooter`

**Comment by wolfcon** [comment]
@JanWirt 试了吗? #1366 给个反馈呀

**Comment by CivelXu** [comment]
@wolfcon 貌似不太行 还crash了

**Comment by wolfcon** [comment]
Crash 给下日志或者 demo 啊

**Comment by CivelXu** [comment]
crash log  -[MJRefreshAutoNormalFooter setAutoTriggerTimes:]: unrecognized selector sent to instance 0x108965bc0
demo MJRefreshAutoNormalFooter无法自动加载 bug可以复现
crash 无法复现，还在排查，貌似和Scrollview视图嵌套有关，使用 JXCategoryView嵌套的tableview。

**Comment by HaijunWei** [comment]
3.2.2 在MJRefreshAutoFooter 里增加了`oneNewPan` 字段判断是否可以发起beginRefreshing，导致ScrollView在松手自动滚动到底部时不会触发super.beginRefreshing方法 ，希望可以尽快修复
