### ISSUE TITLE
MJRefresh 3.2.2 swift       iphone 11 prox max dataArr.count = 6  上拉刷新会造成无限次重复上拉刷新

### ISSUE THREAD

**Issue by Q14** [CoderMJLee/MJRefresh#1364]
**描述bug**
清晰简单地描述这个bug是啥
MJRefresh 3.2.2 swift       iphone 11 prox max dataArr.count = 6  上拉刷新会造成无限次重复上拉刷新
    tableView.estimatedRowHeight = 119
        tableView.estimatedSectionFooterHeight = 80

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone11
 - iOS13
 - Xcode10
<img width="295" alt="B64E89EE-7D5E-4FE5-A007-68031DFB6FF2" src="https://user-images.githubusercontent.com/17269432/69122956-1682ae00-0adb-11ea-8bed-b78a50a0131c.png">

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
Demo? 用的是哪个控件

**Comment by Q14** [comment]
MJRefreshAutoGifFooter

**Comment by Q14** [comment]
> Demo? 用的是哪个控件

MJRefreshAutoGifFooter

**Comment by wolfcon** [comment]
Demo?
