### ISSUE TITLE
项目swift 版本3.2.2

### ISSUE THREAD

**Issue by guojingjingghost** [CoderMJLee/MJRefresh#1365]
项目中使用mj_footer?.beginRefreshing() 或者mj_header?.beginRefreshing()都失效了，都得手动刷新才可以

**Comment by guojingjingghost** [comment]
func openHeaderFresh(target:Any?,action:Selector) {
        let header = MJRefreshNormalHeader(refreshingTarget: target!, refreshingAction: action)
        header.lastUpdatedTimeLabel?.isHidden = true
        self.tableView.mj_header = header
    }
有的页面加上分页控制器的可以  单独的控制器 不可以

**Comment by wolfcon** [comment]
Duplicate of #1363

**Comment by guojingjingghost** [comment]
MJRefreshAutoFooter 用这个footer都没了
