### ISSUE TITLE
UITableView reloadData之后, section区头的位置变化

### ISSUE THREAD

**Issue by xiaoyebukuang** [CoderMJLee/MJRefresh#1367]
**描述bug**
UITableView上拉分页加载更多reloadData之后, section区头的位置变化，下移或不见，不再固定在顶端

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 分页加载tableView
2. 上拉加载页面，等网络加载后，务滑动
3. 滚动位置不定
4. section区头位置不对

**你期望的结果是什么？**
正确显示区头

**截图**
![uploadImg_744211495700331 jpg](https://user-images.githubusercontent.com/8789590/69396298-bd09c180-0d1c-11ea-9b19-9eae40bb25a9.png)

**运行环境**
 - iPhone6
 - iOS10.3
 - Xcode11

**额外的**
最好能提供出现bug的Demo

**Comment by xiaoyebukuang** [comment]
UITableViewCell采用的是自动适应高度
UITableView设置了setEstimatedRowHeight高度，若固定高度，无此现象

**Comment by wolfcon** [comment]
来个 Demo?
