### ISSUE TITLE
iOS13大标题带搜索框下通过代码实现刷新[self.tableView.mj_header beginRefreshing];不是手拉的，navbar、搜索框和内容重叠在一起

### ISSUE THREAD

**Issue by ieliwb** [CoderMJLee/MJRefresh#1369]
iOS13大标题带搜索框下通过代码实现刷新[self.tableView.mj_header beginRefreshing];
自己实现的双击tabbar刷新当前页内容，类似微博。
不是手拉的，navbar、搜索框和内容重叠在一起，有人知道怎么解决吗

**Comment by wolfcon** [comment]
双击那个, 自己去添加相关的 tabBar 的 Button 事件.
大标题下的刷新适配是有问题的. 建议用系统的刷新控件

**Comment by ieliwb** [comment]
双击已经实现了的，主要是不是手动下拉，错位了，我现在把大标题关了，也错位，看下图，带UISearchController
![https://i.v2ex.co/q314cxpi.png](https://i.v2ex.co/q314cxpi.png)
