### ISSUE TITLE
MJ 你好， 下拉刷新状态下， section view 显示偏移了

### ISSUE THREAD

**Issue by luomu0371** [CoderMJLee/MJRefresh#137]
下拉刷新状态下， 向上滚动tableView后， section header 显示向下偏移了。 本来应该是现在在顶部的

![ios simulator screen shot 2015 5 6 4 31 03](https://cloud.githubusercontent.com/assets/5474804/7489836/922e23c0-f40d-11e4-8596-67f9d5b8fc22.png)
![ios simulator screen shot 2015 5 6 4 31 24](https://cloud.githubusercontent.com/assets/5474804/7489837/9233fe26-f40d-11e4-8e8c-6625e51ab320.png)

**Comment by luomu0371** [comment]
#pragma mark 根据contentOffset调整state
- (void)adjustStateWithContentOffset
{
    if (self.state != MJRefreshHeaderStateRefreshing) {
        // 在刷新过程中，跳转到下一个控制器时，contentInset可能会变
        _scrollViewOriginalInset = _scrollView.contentInset;
    }
    
    // 在刷新的 refreshing 状态，动态设置 content inset
    if (self.state == MJRefreshHeaderStateRefreshing ) {
        if(_scrollView.contentOffset.y >= -_scrollViewOriginalInset.top )
        {
            _scrollView.mj_insetT = _scrollViewOriginalInset.top;
        }
        else if (_scrollView.contentOffset.y > -118  //增加了这部分判断后 显示正常了， 但不知道会不会影响其它问题。 请MJ大大 看看
                 && _scrollView.contentOffset.y < -64)
        {
            _scrollView.mj_insetT =  _scrollViewOriginalInset.top - (_scrollViewOriginalInset.top + _scrollView.contentOffset.y);
            
            NSLog(@"contentOffset %.0f  %.0f", _scrollView.contentOffset.y, _scrollViewOriginalInset.top);
        }
        else
        {
            
            _scrollView.mj_insetT = MIN(_scrollViewOriginalInset.top + self.mj_h,
                                        _scrollViewOriginalInset.top - _scrollView.contentOffset.y);
            
        }
        return;
    }

**Comment by luolisheng** [comment]
添加完也不起作用啊

**Comment by 624560545** [comment]
下载最新版就可以了！

**Comment by winfredzen** [comment]
下载最新的也不行啊

**Comment by CoderMJLee** [comment]
这个问题不好解决，官方的UIRefreshControl也有这样的问题，有空了我再好好看看哈

**Comment by yx-mike** [comment]
J哥加油，我也遇到这个问题，我看好你哟。

**Comment by 624560545** [comment]
为何我换了下载最新版这个问题就解决了？

**Comment by 624560545** [comment]
哦原来我只有一组没有多组不会偏移

**Comment by wyhazq** [comment]
换一个，谢谢，这个框架里面的下拉控件处理了这个问题https://github.com/zhuchaowe/EasyIOS

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈
