### ISSUE TITLE
3.2.3 是不是移除了onlyRefreshPerDrag

### ISSUE THREAD

**Issue by lilong7676** [CoderMJLee/MJRefresh#1370]
**描述bug**
清晰简单地描述这个bug是啥
Property 'onlyRefreshPerDrag' not found on object of type 'MJRefreshAutoNormalFooter *'

**必现/偶发?**
必现

**怎么样重现这个bug**
编译失败

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**

**运行环境**
 - iPhone6
 - iOS13
 - Xcode11

**Comment by lilong7676** [comment]
另外升级到了3.2.3，发现点击statusBar 列表不会自动滚动置顶了。

**Comment by wolfcon** [comment]
https://github.com/CoderMJLee/MJRefresh/releases/tag/3.2.3

**Comment by lilong7676** [comment]
@wolfcon 点击statusBar 列表不会自动滚动置顶了，这个是什么原因呢？

**Comment by lilong7676** [comment]
多谢。
