### ISSUE TITLE
MJRefreshStateHeader - (void)setLastUpdatedTimeKey:(NSString *)lastUpdatedTimeKey 方法崩溃

### ISSUE THREAD

**Issue by luomu0371** [CoderMJLee/MJRefresh#1373]
**描述bug**
XCODE11 新建swift工程，使用MJRefresh 下拉刷新时 下面方法崩溃
MJRefreshStateHeader
- (void)setLastUpdatedTimeKey:(NSString *)lastUpdatedTimeKey

**必现/偶发?**
必现

NSDate *lastUpdatedTime = [[NSUserDefaults standardUserDefaults] objectForKey:lastUpdatedTimeKey];
    
    // 如果有block
 if (self.lastUpdatedTimeText ) {
        self.lastUpdatedTimeLabel.text = self.lastUpdatedTimeText(lastUpdatedTime);
        return;
    }

当 lastUpdatedTime 为空时崩溃， 因为swift下 lastUpdatedTimeText方法的参数需要非空值

**Comment by wolfcon** [comment]
Demo?
