### ISSUE TITLE
建议可以给 ”点击或上拉加载更多" 字样加一个显示隐藏的开关

### ISSUE THREAD

**Issue by melo30** [CoderMJLee/MJRefresh#1377]
遇到公司的需求，说这个字样不好看，不想要，看网上的做法就是去 去掉MJRefreshConst.m 中的MJRefreshAutoFooterIdleText 定义的文字。这种做法确实有效，但是大部分人都是用cocoapods导入的，那么如果这样做的话，每次MJRefresh更新的话，我就要记得去改一次，不然又会出现这个问题。

**Comment by wolfcon** [comment]
```swift
header.setTitle("", for: .idle)
```
