### ISSUE TITLE
footer在ios13上会多次调用

### ISSUE THREAD

**Issue by chunxige** [CoderMJLee/MJRefresh#1378]
**描述bug**
上拉加载更多时候，如果在加载最有一页数据继续上拉加载更多，会重复调用多次footer
**必现/偶发?**
必现

**运行环境**
 - 所有设备包含模拟器
 - iOS13.3
 - Xcode11.3

**Comment by wolfcon** [comment]
哪个 footer? 
所用版本?
demo?
