### ISSUE TITLE
3.3.0版本开始出现的问题

### ISSUE THREAD

**Issue by CoderMaurice** [CoderMJLee/MJRefresh#1379]
~3.3.0版本开始，endRefreshing时scrollview.contentOffset.y的变化不再线性~
3.3.0 版本开始, 动画改为 bounds 动画, 不再控制 offset. `因为 offset 的改变最终反映在 bounds 上`, bounds 修改改了最终的状态. 中间状态不再触发 `scrollViewDidScroll` 方法. 並且为了防止在 bounds 动画中状态异常, 关闭了动画期间的手势(后期需要改进)

具体问题请看demo
文件夹中包含了3.2.3和3.3.1版本

[RefreshDEMO.zip](https://github.com/CoderMJLee/MJRefresh/files/3993424/RefreshDEMO.zip)

**Comment by Yigol2008** [comment]
有没有解决办法？

**Comment by CoderMaurice** [comment]
> 有没有解决办法？

不升级版本，暂时使用3.2.3，等更新吧

**Comment by wolfcon** [comment]
@CoderMaurice 你确定是不线性吗? 你把`MJRefreshConst` 中修改以下 2 项, 仔细看看变化的状态
```objc
const CGFloat MJRefreshFastAnimationDuration = 2;
const CGFloat MJRefreshSlowAnimationDuration = 4;
```
PS: 你这个例子很诡异诶, 你把那个黄色 view 放在 tableViewHeader 即可.

**Comment by janicezhw** [comment]
相同的问题

**Comment by wolfcon** [comment]
#1407
