### ISSUE TITLE
把[_tableView.header beginRefreshing]放到viewWillAppear的时候，返回来会有问题

### ISSUE THREAD

**Issue by xiaozhi** [CoderMJLee/MJRefresh#138]
把[_tableView.header beginRefreshing]放到viewWillAppear的时候，从其他页面返回来，下拉更新不会自动重新刷新，人为下拉也不会更新，只显示最后更新的时间。

**Comment by xiaozhi** [comment]
放在viewDidApper的时候，倒没什么问题~

**Comment by xiaozhi** [comment]
- (void)beginRefreshing
{
    if (self.window) {
        self.state = MJRefreshHeaderStateRefreshing;
    } else {
        self.state = MJRefreshHeaderStateWillRefresh;
        // 刷新(预防从另一个控制器回到这个控制器的情况，回来要重新刷新一下)
        [self setNeedsDisplay];
    }
}
参照以前的问题解决了~不好意思

**Comment by xiaozhi** [comment]
```
- (void)beginRefreshing
{
    if (self.window) {
        self.state = MJRefreshHeaderStateRefreshing;
    } else {
        self.state = MJRefreshHeaderStateWillRefresh;
        // 刷新(预防从另一个控制器回到这个控制器的情况，回来要重新刷新一下)
        [self setNeedsDisplay];
    }
}
```
参照其他问题，这样子解决了~但是没加到pod库上面

**Comment by CoderMJLee** [comment]
上一次已经解决了哦，也已经传到pod，你需要pod repo update一下，更新远程的pod库哈
