### ISSUE TITLE
3.3.1的问题

### ISSUE THREAD

**Issue by HebeTienCoder** [CoderMJLee/MJRefresh#1381]
**描述bug**
3.3.1通过按钮或者双击tabbar的方式触发开始刷新会有问题，scrollView会一直向下跑

**必现/偶发?**
必现

**运行环境**
 - iPhoneXsMax
 - iOS13.3
 - Xcode11.3

**Comment by wolfcon** [comment]
Demo? 我这边没发现这个问题
