### ISSUE TITLE
foot 不显示

### ISSUE THREAD

**Issue by lhf19900402** [CoderMJLee/MJRefresh#1382]
**描述bug**
在不执行其他刷新的操作的情况之下，直接手动endRefreshingWithNoMoreData，这时候 footer 根本不显示了。。。

**必现/偶发?**
必现

**截图**
https://i.postimg.cc/PxdgG8nM/CA1-F94856-C40-B7-ED888149-F557-EB14-DB.png

**运行环境**
 - iPhone7P
 - iOS13.3
 - Xcode11.3

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
Demo?
