### ISSUE TITLE
使用Refresh导致UITableView失去响应

### ISSUE THREAD

**Issue by haichong** [CoderMJLee/MJRefresh#1383]
**描述bug**
使用Refresh导致UITableView失去响应

**必现/偶发?**
必现
使用JXCategoryView
![屏幕快照 2019-12-25 下午3 41 55](https://user-images.githubusercontent.com/14902905/71437521-19ea0480-272d-11ea-90f0-d9b392d31a23.png)
每个item添加的是ViewController，在每个item的viewDidLoad里面调用beginRefreshing方法，不等刷新动画完成，就是还没走- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)flag 方法，切换item。此时上一个item的UITableView的userInteractionEnabled还是NO。如果想毕现可以增加动画时间，设置 boundsAnimation.duration = 10;等再返回上一个item的时候，它的UITableView失去响应。

**Comment by haichong** [comment]
如果有疑问，可以加我QQ

**Comment by wolfcon** [comment]
Duplicate of #1379
