### ISSUE TITLE
3.3.1 MJRefresh中使用bounds动画在xib中不适配（主要是addChildViewController的情况）

### ISSUE THREAD

**Issue by zisulu** [CoderMJLee/MJRefresh#1384]
**描述bug**
因为早期问题，我们app中很多控制器使用了xib，众所周知xib拿到的宽度是不准的，在更新到3.3.1之后，部分页面xib的宽度是375，如果在viewDidAppear的时候触发下拉刷新，在ip7plus上（414的宽度）页面出现了宽度变化的过程，经过调试发现是3.3.0版本中新增的bounds动画导致的，我看了下issue，也有关于这个动画的其他问题，建议检查下。

**必现/偶发?**
必现

**怎么样重现这个bug**
正常情况下的页面没有这个问题，但是因为特殊需求我的项目里会在控制器第一次appear的时候添加ChildViewController，这在3.3.1表现异常，之前的版本没有问题，经过测试3.3.1之后 我只有在viewDidLoad的时候添加ChildViewController，才能保证MJRefresh中的bounds动画能获取到正确的bounds

**你期望的结果是什么？**
我自己这边会更换特殊需求的方案，不过这个bounds动画确实会导致一些问题，我这边先回滚到3.2.3了。

**截图**
如果有必要的话，请上传几张截图
![WX20191226-102024](https://user-images.githubusercontent.com/15645270/71454257-d04ff700-27ca-11ea-833e-9b860b28e460.png)
![WX20191226-102150](https://user-images.githubusercontent.com/15645270/71454259-d34ae780-27ca-11ea-9282-e6f359353a2a.png)

**运行环境**
 - iPhone7plus
 - iOS13.2.3
 - Xcode11

**额外的**
这里是demo
[MJRefresh.zip](https://github.com/CoderMJLee/MJRefresh/files/4001345/MJRefresh.zip)

**Comment by wolfcon** [comment]
你在 `MJBugSubViewController` 中加入这 2 个方法, 这 2 个方法是保证子 view 被正确渲染成正确大小用的(`storyboard` 和 `xib` 中尤其需要注意), 此时才是正常的大小. 
```objc
- (void)viewDidLayoutSubviews {
    NSLog(@"");
// 打断点 po self.scrollView.frame
}

- (void)viewWillLayoutSubviews {
    NSLog(@"");
// 打断点 po self.scrollView.frame
}
```

### 结论: 不知道你有没有发现, 正常的 `ViewController` 调用顺序是:
1. `viewWillLayoutSubviews `
2. `viewDidLayoutSubviews`
3. `viewDidAppear`

而你的 SubBugViewController 的调用顺序而是: 
1. `viewDidAppear`
2. `viewWillLayoutSubviews `
3. `viewDidLayoutSubviews`

现在你知道发生了什么了吧?
如果你不想改现有代码, 建议你直接在`showSubViewController` 方法中直接初始化一下子 view 的大小, 包括`view` `scrollView`
