### ISSUE TITLE
3.3.1版本刷新头一直显示的问题

### ISSUE THREAD

**Issue by huanxinyanyue** [CoderMJLee/MJRefresh#1385]
**描述bug**
3.3.1版本，navigation的rootviewcontroller，隐藏导航栏，刷新头不能正常回收，一直显示。
基类控制器中设置了
`if #available(iOS 11.0, *) {
            UIScrollView.appearance().contentInsetAdjustmentBehavior = .never
        } else {
            automaticallyAdjustsScrollViewInsets = false
        }`

不隐藏导航栏的控制器没有这个问题。
之前是用的3.2.0版本，没有发现这个问题。
**必现/偶发?**
必现

**你期望的结果是什么？**
隐藏导航条的情况下，在刷新完成后能正常回收刷新头

**运行环境**
 - iPhone7
 - iOS12.4
 - Xcode11

**Comment by tkotf61412** [comment]
遇到同样了同样的问题

刷新完毕后 contentInset.top 为 54 ，正常应该为 0.

### 运行环境
+iPhone 6p / 11 pro max
+iOS 13.3 / 13.2
+Xcode11

**Comment by wolfcon** [comment]
麻烦给出 Demo. 我这边这样设置没有遇到这个问题啊

```objc
- (void)viewDidLoad {
...
    [UIScrollView appearance].contentInsetAdjustmentBehavior =      UIScrollViewContentInsetAdjustmentNever;
    [self.navigationController setNavigationBarHidden:YES];
}
```
