### ISSUE TITLE
3.3.1版本问题

### ISSUE THREAD

**Issue by CivelXu** [CoderMJLee/MJRefresh#1386]
之前 MJRefreshAutoNormalFooter设置如下属性   
 footer.triggerAutomaticallyRefreshPercent = -20
 footer.autoTriggerTimes = -1
实现 预先加载， 不知道这样设置是否使用正确？
新版本3.3.1 里面 这样设置会有bug
下拉header刷新会先走一次footer刷新
导致header 往下移动了

**Comment by wolfcon** [comment]
老哥...`percent` 属性取值范围0-1 啊. 你这个-20 怕不是覆盖了整个屏幕...不触发才有鬼吧
