### ISSUE TITLE
导航条透明时，3.3.1版本MJRefreshHeader动画，下拉刷新头部有个闪现，3.2.3版本正常

### ISSUE THREAD

**Issue by huipengo** [CoderMJLee/MJRefresh#1388]
**描述bug**
使用 `MJRefresh 3.3.1` 版本，导航条设置成透明状态，下拉时头部背景应该吸附在顶部不动，现在头部会有一个闪现的白屏，已定位在 `MJRefreshHeader` 的 `- (void)setState:(MJRefreshState)state` 动画修改导致的

**必现/偶发?**
必现

**你期望的结果是什么？**
下拉时头部背景应该吸附在顶部不动

**截图**
![refresh](https://user-images.githubusercontent.com/9402895/72131253-a7c52100-33b6-11ea-8271-7045dc226e74.GIF)

**运行环境**
 - iPhone7
 - iOS12.2
 - Xcode11.3

**额外的**
Demo：https://github.com/huipengo/RefreshDemo

**Comment by wolfcon** [comment]
Demo

**Comment by huipengo** [comment]
> Demo
你好，Demo 请看
https://github.com/huipengo/RefreshDemo
多谢啦

**Comment by huipengo** [comment]
> Demo
