### ISSUE TITLE
国际化 languageCode无法动态更改

### ISSUE THREAD

**Issue by Shannon-Yang** [CoderMJLee/MJRefresh#1389]
我的app里面有一个语言切换页面，点击语言切换，我想要做到界面动态的更改语言，当点击语言选择后，我设置了 MJRefreshConfig.default().languageCode = 'zh-Hant'，但是还是无法生效，只有下一次启动后才生效

必现

**Comment by tipshot** [comment]
https://blog.csdn.net/Bloody_Leaves/article/details/53907523

**Comment by tipshot** [comment]
求 官方支持国际化可以自定义控制。

**Comment by wolfcon** [comment]
目前是这样, 后续可能会出一个动态切换功能, 敬请期待
