### ISSUE TITLE
MJ 你好，UICollectionView下拉刷新的时候，能否确定下拉刷新的下拉距离

### ISSUE THREAD

**Issue by AgentEric** [CoderMJLee/MJRefresh#139]
RT, 做项目的过程中，我们有一个设计是下拉一小段距离的时候，有别的action，下拉一定距离才可以刷新。MJ老师我想问一下怎么才能处理好这种需求。

很紧急，如果您能看到请回复我，谢谢。我是MJ的忠实粉

**Comment by CoderMJLee** [comment]
这个需要加一些判断。我看看能否在2.0版本中提供这么一个功能

**Comment by AgentEric** [comment]
好的，很感谢MJ老师。百忙之中，回复的很及时...挺感动的,祝愿MJRefresh成为中国乃至世界开发界最好用的控件

**Comment by CoderMJLee** [comment]
你看看最新的2.0版本能否满足你的要求哈
