### ISSUE TITLE
刚好松开立即刷新的时候会出现抖动

### ISSUE THREAD

**Issue by a497500306** [CoderMJLee/MJRefresh#1390]
**描述bug**
刚好松开立即刷新的时候会出现抖动

**必现/偶发?**
必现

**怎么样重现这个bug**
下拉到刚好松开立即刷新的时候会出现抖动

**你期望的结果是什么？**
不出现抖动

**Comment by xtaykhksghy** [comment]
的确有这种问题，刚注意到
