### ISSUE TITLE
最新版3.3.1还是会出现下拉不回弹

### ISSUE THREAD

**Issue by seanLee** [CoderMJLee/MJRefresh#1394]
**描述bug**
之前使用旧版本会导致下拉之后不回弹,然后昨天替换成最新版本还是会出现同样的问题.我观察到的现象是出现不回弹的情况后,还是可以下拉界面,这应该就是意味着重置Bounds的动画已经结束.所以我猜测是不是过程中设置Bounds的时候,哪个环节的值没有获取对导致Bounds无法还原.

**必现/偶发?**
偶发

**你期望的结果是什么？**
希望能解决掉下拉之后不会弹的问题

**运行环境**
刘海屏

**额外的**
最好能提供出现bug的Demo

**Comment by xujunquan** [comment]
同样遇到此问题，频率较高。

**Comment by jiexingtianxia** [comment]
中途设置滚动试图的偏移量，会出现下拉不回弹的现象，导致滚动视图一点一点往下偏移，出现不正常的现象。

**Comment by stone4302** [comment]
在全屏手机上出现的频率很高，而且下拉的偏移值很大，不知道使用低版本会不会有这个问题，希望作者早日解决

**Comment by TianBaoLi** [comment]
3.1.15.3  之前使用的是这个版本也出现了这个问题，还偶现一种情况 是 来回抖动。有点类似弹簧那种 来回弹。

**Comment by docee** [comment]
同样问题。在刷新时present新的控制器就会出现这种情况。

**Comment by Conan-R** [comment]
遇到概率颇高啊

**Comment by WS-Vincent** [comment]
是有这个问题，确实比较紧急。有朋友有别的办法解决了么

**Comment by wolfcon** [comment]
> 同样问题。在刷新时present新的控制器就会出现这种情况。
@docee present 前先停止刷新.

**Comment by wolfcon** [comment]
这么多人没人写个 demo 吗? 个人个例

**Comment by February12** [comment]
请问  3.3.1 header 刷新不回弹 你们怎么解决的

**Comment by hpzerozero** [comment]
同问

**Comment by openUmbrella** [comment]
@wolfcon 我写了一个Demo,主要的代码如下:
![image](https://user-images.githubusercontent.com/17615716/78759227-e9636900-79b1-11ea-9e2a-954da99de672.png)
[mjflash.zip](https://github.com/CoderMJLee/MJRefresh/files/4449055/mjflash.zip)

**Comment by February12** [comment]
我用的是  3.3.1   老机型概率行出现 header 回不去




| |
朱云龙
|
|
邮箱：18075375969@163.com
|

签名由 网易邮箱大师 定制

在2020年04月08日 16:01，opu 写道：

@wolfcon 我写了一个Demo,主要的代码如下:

mjflash.zip

**Comment by Asingers** [comment]
上边的 Demo 看起来有点问题，dispatch_after 添加的延时任务可能不会立即执执行。 换 performSelector 就不会有问题。
我尝试使用 GCD Group 临时解决了我遇到的问题，requestData -> endRefresh -> reloadData，不回弹的问题没有再复现，希望有一些参考价值。
（iPhone X，iOS 13.2）

**Comment by wolfcon** [comment]
# [3.4.0](https://github.com/CoderMJLee/MJRefresh/releases)
已经默认采用之前的方式了. 
> 如果需要 CollectionView 版本的动画 bug 解决方案(使用 bounds CAAnimation 动画), 请打开 `isCollectionViewAnimationBug`

对于 bounds CAAnimation 的 bug, 目前请继续提供 Demo. 感谢

**Comment by BestLeeSinCN** [comment]
我补充下这个问题, 我们app大概率触发是这样操作的, 在一个tabbarvc上 比如在第一个vc下拉刷新时, 还未刷新完成的情况下, 快速切换到第二个vc,再次下拉刷新, 此时大概率第一个vc会出现刷新完成之后不回弹的情况

**Comment by wolfcon** [comment]
@BestLeeSinCN  建议你在切换 VC 时, 手动 end

**Comment by wenhao-fly** [comment]
> 我补充下这个问题, 我们app大概率触发是这样操作的, 在一个tabbarvc上 比如在第一个vc下拉刷新时, 还未刷新完成的情况下, 快速切换到第二个vc,再次下拉刷新, 此时大概率第一个vc会出现刷新完成之后不回弹的情况

一样 就是推送的时候  打开app直接跳到tabbar的其他位置 首页的刷新不回弹必现 手动end也不行 最后dispatch_after(0.1, dispatch_get_main_queue() 里跳过去解决

**Comment by wolfcon** [comment]
Demo 来一个?@wenhao-fly

**Comment by wenhao-fly** [comment]
要推送我才能复现 不好写demo 其他包括通用链接进app也不复现。我就是推送的时候进app 在极光didReceiveNotificationResponse执行[[UIViewController topViewController].navigationController.tabBarController setSelectedIndex:2]; 一句代码会出现

**Comment by wolfcon** [comment]
推送不需要你推送 (其实本地推送即可). 给出格式即可.
@wenhao-fly
其他代码麻烦整个 Demo
