### ISSUE TITLE
MJRefreshGifHeader中图片动画时间长度能不能设成一个属性呢？

### ISSUE THREAD

**Issue by tuyuan2012** [CoderMJLee/MJRefresh#140]
MJRefreshGifHeader中图片动画时间最好设成一个可设置的属性吧，这样我们可以在外面进行控制，现在我们在使用的过程中遇到：如果图片帧比较多的时候，动画就会很慢...
      我看你的源码设置如下：
      case MJRefreshHeaderStateRefreshing: {
                [self.gifView stopAnimating];
                if (images.count == 1) { // 单张图片
                    self.gifView.image = [images lastObject];
                } else { // 多张图片
                    self.gifView.animationImages = images;
                    self.gifView.animationDuration = images.count * 0.5;
                    [self.gifView startAnimating];
                }
                break;
            }

**Comment by CoderMJLee** [comment]
好的，在即将发布的2.0版本中会提供此属性的
