### ISSUE TITLE
请移除有关UIWebView的逻辑（替换为WKWebView）

### ISSUE THREAD

**Issue by haokunjiang** [CoderMJLee/MJRefresh#1401]
通过grep -r "UIWebView" .发现（    pod 'MJRefresh', '3.3.1'）有如下内容：
./Pods/MJRefresh/README.md:    * [UIWebView01-The drop-down refresh](#UIWebView01-The_drop-down_refresh)
./Pods/MJRefresh/README.md:* `UIScrollView`、`UITableView`、`UICollectionView`、`UIWebView`
./Pods/MJRefresh/README.md:## <a id="UIWebView01-The_drop-down_refresh"></a>UIWebView01-The drop-down refresh
而苹果官方给出：
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of app updates that use UIWebView APIs starting from December 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by kinarobin** [comment]
@haokunjiang 源码中并没有 `UIWebView`。 上述只是README中提到`UIWebView`。
