### ISSUE TITLE
下拉刷新scrollIndicator会抖动

### ISSUE THREAD

**Issue by hahaGitHub** [CoderMJLee/MJRefresh#1403]
**描述bug**
清晰简单地描述这个bug是啥
现在使用最新版本3.3.1，下拉刷新后，scrollIndicator会抖动，另外发现抖动会导致一直调用scrollViewDidScroll，如果在scrollViewDidScroll中做些其他页面的逻辑，就会产生问题。
下载了您的demo，发现scrollIndicator也会抖动。我们之前使用的版本是3.1.15.7，没有这个问题呢。

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果
期望能修改这个问题，因为后续还需要适配暗黑模式，必须升级此sdk，多谢！

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhoneX
 - iOS13.2
 - Xcode11.3.1

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
麻烦写个 Demo

**Comment by wolfcon** [comment]
3.4.0 之后已经暂时恢复之前的实现逻辑.

**Comment by hahaGitHub** [comment]
我们升级试试
