### ISSUE TITLE
所有的tableviewcell 就都是高亮状态的问题

### ISSUE THREAD

**Issue by FunnyFzl** [CoderMJLee/MJRefresh#1406]
viewcontroller内是可下拉刷新的tableview （下拉刷新用的MJRefresh）进入立即刷新状态beginRefreshing
在数据还未刷新出来的时候，一直点击空白的tableview，数据一出现，所有的tableviewcell 就都是高亮状态了，这是什么原因呢？
<img width="414" alt="截屏2020-03-27下午10 50 31" src="https://user-images.githubusercontent.com/15104149/77995526-87c24f80-735e-11ea-8597-8897385aad21.png">

**Comment by wolfcon** [comment]
你的 Demo ? 
如果默认没有选中状态, 建议你将 `Cell` 的属性改为 
`cell.selectionStyle = UITableViewCellSelectionStyleNone;`

**Comment by FunnyFzl** [comment]
> 你的 Demo ?
> 如果默认没有选中状态, 建议你将 `Cell` 的属性改为
> `cell.selectionStyle = UITableViewCellSelectionStyleNone;`

需要有点击高亮的状态，让用户感觉有交互，直接把selectionStyle 置为none 肯定是不行的

**Comment by wolfcon** [comment]
Demo?
有操作的视频么?

**Comment by FunnyFzl** [comment]
以下是有操作的视频：
[屏幕录制2020-04-07 下午6.37.26.mov.zip](https://github.com/CoderMJLee/MJRefresh/files/4443636/2020-04-07.6.37.26.mov.zip)


> Demo?
> 有操作的视频么?

**Comment by wolfcon** [comment]
来个 Demo?

**Comment by FunnyFzl** [comment]
> 来个 Demo?

似乎是MJRefresh的这次commit(https://github.com/CoderMJLee/MJRefresh/commit/c0868527914d25da123e97aa0a8bc5c0e947819b)导致的，我把MJRefresh改成这个版本(https://github.com/CoderMJLee/MJRefresh/commit/4488bf1093c327116ccf90815030e9fae8a860bb)后没再复现了

**Comment by FunnyFzl** [comment]
> 来个 Demo?

似乎是MJRefresh的这次commit(c086852)导致的，我把MJRefresh改成这个版本(4488bf1)后没再复现了。

**Comment by wolfcon** [comment]
麻烦上个你那边复现的 Demo. 谢谢啦
