### ISSUE TITLE
iOS13中 下拉刷新loading动画，自动结束动画

### ISSUE THREAD

**Issue by 13923724235** [CoderMJLee/MJRefresh#1408]
**描述bug**
调用 beginRefreshing 下拉刷新时候，自己没有调用endRefreshing，自动提前结束刷新，导致中间下拉动画一闪而过，目前使用最新Xcode11打包时候出现问题。

**必现/偶发?**
必现

**你期望的结果是什么？**
不会自动提前结束下拉操作，而是等我们调用了end函数后才结束

**运行环境**
 - iPhone7Plus
 - iOS13.3
 - Xcode11

**Comment by wolfcon** [comment]
Demo?
