### ISSUE TITLE
下拉刷新导致contentOffset不归零

### ISSUE THREAD

**Issue by baiyidjp** [CoderMJLee/MJRefresh#1409]
**描述bug**
MJRefresh 3.3.1 下拉刷新tableView的contentOffset没有归零，会向上滑动一小段

**必现/偶发?**
必现

**你期望的结果是什么？**
恢复老版本的处理，下拉刷新完成后回到初始位置

**截图**

**运行环境**
 - 模拟器、真机
 - iOS13.3
 - Xcode11

**额外的**
最好能提供出现bug的Demo

**Comment by baiyidjp** [comment]
scrollView.contentOffset.y: 54.0
scrollView.contentInset.top: 0.0

这是打印 scrollDidScroll 代理中的数据 最后有个 contentOffset.y  = 54 了 刚好是mj_header的高度

**Comment by JRJian** [comment]
没有解决，为何关闭？
我这里打印的是
contentOffset: {0, -54};
adjustedContentInset: {54, 0, 44, 0};
