### ISSUE TITLE
当MJRefreshHeader 是 isRefreshing状态的时候

### ISSUE THREAD

**Issue by yan632915202** [CoderMJLee/MJRefresh#141]
当MJRefreshHeader 是 isRefreshing状态的时候，再去调用 MJRefreshHeader的beginRefresh的时候，刷新的block好像没有执行，即使，我调用了 endRefresh 也不能马上停止。。。。。。  这样的话；如果我有两个按钮都要控制刷新的话，两个按钮点击速度快的时候，可能就还会因为这个原因，刷出来的数据可能就不是自己想要的

**Comment by CoderMJLee** [comment]
如果连点2次，是否意味着第一次的数据不要了？

**Comment by hengchengfei** [comment]
我也有这个问题, beginRefresh没有执行

**Comment by yan632915202** [comment]
是的  第一次的数据 不要了 以最后一次为准！！！

**Comment by CoderMJLee** [comment]
好的，在2.0版本，我会跟进的哈。最近忙死了，望理解

**Comment by zziajkx** [comment]
同问，现在靠判断TableView的偏移量暂时解决，建议增加一个动画完成时的回调
