### ISSUE TITLE
能不能给个MJRefresh的Logo?

### ISSUE THREAD

**Issue by jingliancui** [CoderMJLee/MJRefresh#1411]
你好，我是做跨平台开发的，最近用了你的库，打算写个文章宣传一下你的库，但是貌似找不到MJRefresh的Logo。

**Comment by kinarobin** [comment]
Demo 里面使用的是这个Logo：

![ios-marketing-1024x1024png](https://user-images.githubusercontent.com/29303030/78321864-ac593a00-759f-11ea-9049-eb8b21c88936.png)

**Comment by jingliancui** [comment]
ok ,收到了，那建议你也把logo放到readme，好让其他人也知道你们哦

**Comment by jingliancui** [comment]
另外有没有透明背景的png呢，你这个白底喔。。。
