### ISSUE TITLE
largetitle下拉松开的时候，largetitle直接回弹。

### ISSUE THREAD

**Issue by ameue** [CoderMJLee/MJRefresh#1412]
**你的新功能建议是否牵扯到某个常见的问题？**
比如，在开发中，经常遇到XXX问题，目前框架的功能不足以解决这个问题
如果在demo中的MJExampleViewController中添加下面这句话：
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];

    if (@available(iOS 11.0, *)) {
        self.navigationController.navigationBar.prefersLargeTitles = YES;
        self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeAlways;
    }
}

当下拉刷新松开时，largetitle直接回弹回去了。
**你希望达到的效果**
比如，我希望框架能够帮助我解决XXX问题，实现XXXX那样的效果
可以实现tableview收回的时候largetitle再收回吗？
**你能考虑到的可选实现方案**
描述一下你认为要实现这个功能，有哪些可行的一些实现方案？
没有想到

**Comment by wolfcon** [comment]
LargeTitle 暂时还不支持.
