### ISSUE TITLE
beginRefreshing()没有header自动下拉停留效果

### ISSUE THREAD

**Issue by JayLin0920** [CoderMJLee/MJRefresh#1419]
**描述bug**
使用self.tableView.mj_header?.beginRefreshing()时，页面没有header自动下拉，然后停留的动画效果（个别页面）

**必现/偶发?**
必现

**你期望的结果是什么？**
能有正常的自动下拉的停留动画效果

**运行环境**
 - iPhone11
 - iOS13.4.1
 - Xcode11.4
- 使用本地代码，未使用pod，对应pod版本号应该是3.4.1（未使用pod，是swift上有个lastUpdatedTimeKey为nil的闪退，所以使用了本地）

**bug定位分析**
定位后，发现是在这个地方
```
#import "MJRefreshHeader.h"

- (void)resetInset {
    if (@available(iOS 11.0, *)) {
    } else {
        // 如果 iOS 10 及以下系统在刷新时, push 新的 VC, 等待刷新完成后回来, 会导致顶部 Insets.top 异常, 不能 resetInset, 检查一下这种特殊情况
        if (!self.window) { return; }
    }
    
    // sectionheader停留解决
    CGFloat insetT = - self.scrollView.mj_offsetY > _scrollViewOriginalInset.top ? - self.scrollView.mj_offsetY : _scrollViewOriginalInset.top;
    insetT = insetT > self.mj_h + _scrollViewOriginalInset.top ? self.mj_h + _scrollViewOriginalInset.top : insetT;
    self.insetTDelta = _scrollViewOriginalInset.top - insetT;
    // 避免 CollectionView 在使用根据 Autolayout 和 内容自动伸缩 Cell, 刷新时导致的 Layout 异常渲染问题
    if (self.scrollView.mj_insetT != insetT) {
        self.scrollView.mj_insetT = insetT;
    }
    NSLog(@"jl==   %f, %f", - self.scrollView.mj_offsetY, _scrollViewOriginalInset.top);
}
```
经上述代码打印，调用beginRefreshing()方法时，这个无动画效果的页面self.scrollView.mj_offsetY,一直为0，其他正常页面为-75。
我目前的解决方案为加了如下代码
```
// sectionheader停留解决

// ----- add start -----
    if (self.scrollView.mj_offsetY == 0) {
        self.scrollView.mj_offsetY = self.mj_h;
    }
// ----- add end -----

    CGFloat insetT
```
希望能修复这个bug，同时了解下导致这个问题的原因

**Comment by wolfcon** [comment]
能不能给出 Demo? 我这边没有复现你说的这个 `必现` bug

**Comment by JayLin0920** [comment]
demo不好拆，我这边只有一个页面是必现的，其他页面没有这个问题，然后我用了我说的那种办法解决了

**Comment by wolfcon** [comment]
只要实现 bug 逻辑即可.

**Comment by fanjaycn** [comment]
我这里也出现了类似的问题，建议重点关注一下出现问题页面的 UIScrollViewDelegate 里的 - (void)scrollViewDidScroll:(UIScrollView *)scrollView；和这个方法里的处理逻辑有关系。

**Comment by gitph101** [comment]
您好，邮件已收到。

**Comment by 309598016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fanjaycn** [comment]
> 我这里也出现了类似的问题，建议重点关注一下出现问题页面的 UIScrollViewDelegate 里的 - (void)scrollViewDidScroll:(UIScrollView *)scrollView；和这个方法里的处理逻辑有关系。

找到原因了，我这里是因为其他类接管了scrollViewDidScroll 方法，判断一下
if (![scrollView.mj_header isRefreshing])
