### ISSUE TITLE
UICollectionViewCell 自适应布局 crash！

### ISSUE THREAD

**Issue by ouyanghuacom** [CoderMJLee/MJRefresh#1423]
**描述bug**
iphone 7 ios 10.3.2
UICollectionView 自适应布局，上拉加载更多之后，contentOffset异常，然后下拉刷新，就crash.

**必现/偶发?**

必现

**怎么样重现这个bug**

UICollectionView 自适应布局 上拉加载更多之后，contentOffset异常，然后下拉刷新，就crash.

**你期望的结果是什么？**

功能正常

**截图**
![image](https://user-images.githubusercontent.com/59241132/80211045-7ae80180-8667-11ea-8d46-0acaaaffe3b9.png)

**运行环境**
 - iPhone7
 - iOS10.3.2
 - Xcode11

**额外的**
[MJRefreshCrash.zip](https://github.com/CoderMJLee/MJRefresh/files/4528734/MJRefreshCrash.zip)

**Comment by wolfcon** [comment]
Duplicate of #1227 

Invalidate layout before ending
