### ISSUE TITLE
从上拉刷新到设置的方法被调用中间有1s的延迟

### ISSUE THREAD

**Issue by alexazhou** [CoderMJLee/MJRefresh#143]
看了代码，是通过dispatch_after故意设置的延迟调用，这样会让刷新变慢，是否有必要呢？

**Comment by CoderMJLee** [comment]
最新的2.0版本已经修改为0.5秒，这个目的是防止某些特殊的bug，比如上拉太猛，由于惯性导致一直上拉加载（就是一上拉就加载完毕的这种情况）
