### ISSUE TITLE
iOS13下CollectionView下拉刷新底部cell会有错位的动画，如何解决？

### ISSUE THREAD

**Issue by CoderTanX** [CoderMJLee/MJRefresh#1434]
<img width="384" alt="企业微信截图_306b2a29-25de-4976-bc99-c24e7369599d" src="https://user-images.githubusercontent.com/9928212/82414203-453d0980-9aa9-11ea-82d5-efe378861b97.png">

**Comment by wolfcon** [comment]
Duplicate of #1359

**Comment by wolfcon** [comment]
使用最新的 SDK. 並且打开 `isCollectionViewAnimationBug `

**Comment by dwade333** [comment]
上拉加载更多的时候 同样也会有一样的问题🤣
