### ISSUE TITLE
mj_header下移或者上移

### ISSUE THREAD

**Issue by zhaiyulei** [CoderMJLee/MJRefresh#1438]
tabbar上添加了双击刷新列表后，第一次加载控制器的时候，多次快速切换点击tabbar，有时候会导致mj_header下移或者上移，是偶现的，希望能给出建议

**Comment by wolfcon** [comment]
点击 tabBar 后, `endRefresh` 当前页面.

**Comment by zhaiyulei** [comment]
使用endRefresh会造成一直下移的
目前解决方式
1.先判断刷新状态
if (self.tableView.mj_header.state == MJRefreshStateIdle) {
        [self.tableView.mj_header beginRefreshing];
    }
2.在刷新结束后对contentInset重置

测试了下，目前没有出现上下移了
根源问题为什么在刷新的时候会出现adjustedContentInset改变的情况，我们已经进行了scrollView的适配

**Comment by zhaiyulei** [comment]
这是两种解决方式

**Comment by Hsoso** [comment]
我这也出现了同样的问题，偶现，发现是这个adjustedContentInset和contentInset和正常情况不一样了，没有变回去
