### ISSUE TITLE
我感觉可以给框架再加点动能

### ISSUE THREAD

**Issue by Winzlee** [CoderMJLee/MJRefresh#144]
可以加一个网络不好情况下的超时处理，现在如果断网了菊花会一直在那转。。

**Comment by gzucm** [comment]
应该是网络错误情况下没有调用endRefreshing方法结束刷新。

**Comment by CoderMJLee** [comment]
是的，需要在网络错误情况下调用endRefreshing方法结束刷新。因为MJRefresh是个UI框架，并不知道你的网络情况
