### ISSUE TITLE
demo 转屏幕从portrait to landscape,header回不去

### ISSUE THREAD

**Issue by liangxiuchen** [CoderMJLee/MJRefresh#1440]
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

在portrait时候下拉刷新，转屏幕到landscape

🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

**描述bug**
header不会回去

**必现/偶发?**
必现

**你期望的结果是什么？**
至少不应该停留在那?
 

**截图**
如果有必要的话，请上传几张截图
<img width="750" alt="151A13C6-197E-44B6-B5AB-A1903BC7FE0D" src="https://user-images.githubusercontent.com/13012683/84261414-4f08d880-ab4e-11ea-8361-b3003e5602aa.png">

**运行环境**
 - iPhone6
 - iOS8.1
 - Xcode10

**额外的**
1.可以监听 UIDeviceOrientationDidChangeNotification 系统通知做处理。
2.建议状态机分成UI和业务逻辑2个状态机。
例如：https://github.com/liangxiuchen/CLXRefresh

**Comment by liangxiuchen** [comment]
此外你们针对iOS11.0以上search bar的支持，也可以完善

**Comment by wolfcon** [comment]
Duplicate of #1267

**Comment by wolfcon** [comment]
这个在框架内处理起来考虑的情况非常复杂. 
### 建议自己在旋转时自行处理

**Comment by liangxiuchen** [comment]
Hi～ wolfcon, 已经重新提交了PR, 不好意思
