### ISSUE TITLE
MJRefreshAutoFooter，自动的footer，请问如何在刷新完毕再回收footer？

### ISSUE THREAD

**Issue by li-qingnan** [CoderMJLee/MJRefresh#1447]
**你希望达到的效果**
MJRefreshAutoFooter，自动的footer，请问如何在刷新完毕再回收footer？
就是在当触发了 MJRefreshStateRefreshing 状态时，不立即回收footer。

李老师，请问这种需求该如何设置？

**Comment by wolfcon** [comment]
你到底在说什么没看懂....

**Comment by li-qingnan** [comment]
> 你到底在说什么没看懂....
> 
> `AutoFooter` 本来就不会收回啊

AutoFooter触发会立即回收的啊。我这边需求是，触发后需要调用endRefreshing、endRefreshingWithNoMoreData再回收。

**Comment by wolfcon** [comment]
你自己运行 `Demo 11` 就是 `AutoFooter`. 根本不会收回的...
要收回的看 `Demo 21`
