### ISSUE TITLE
NSBundle+MJRefresh.m  Memory leak

### ISSUE THREAD

**Issue by hw20101101** [CoderMJLee/MJRefresh#1448]
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

😁为了能够更好地复现问题和修复问题, 请提供 Demo 和详细的 bug 重现步骤😭

🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

**描述bug**
使用 Instruments - Leaks 工具检测到内存泄露，如下发的截图

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面：无
2. 点击哪个位置：无
3. 滚动到哪个位置：无
4. 发生了什么错误：内存泄露

**你期望的结果是什么？**
解决内存泄露

**截图**
<img width="839" alt="WX20200704-114030@2x" src="https://user-images.githubusercontent.com/9107226/86504509-cf3bfa00-bdeb-11ea-8547-29fbe93afa8c.png">

**运行环境**
 - iPhone6s
 - iOS13
 - Xcode11

**额外的**
最好能提供出现bug的Demo：无

**Comment by wolfcon** [comment]
Demo
