### ISSUE TITLE
刷新状态补充

### ISSUE THREAD

**Issue by puhahalx** [CoderMJLee/MJRefresh#1449]
**你的新功能建议是否牵扯到某个常见的问题？**
刷新状态缺少了刷新完成的状态 导致自定义刷新头的时候缺了完成状态而不能满足需求

**你希望达到的效果**
增加刷新完成状态,即MJRefreshStateRefreshing之后变成MJRefreshStateDone(刷新完成)
**你能考虑到的可选实现方案**
描述一下你认为要实现这个功能，有哪些可行的一些实现方案？
在底层的实现中 刷新状态之后变为刷新完成状态,再次下拉的时候才变成待刷新状态

**Comment by wolfcon** [comment]
请使用 `endRefreshingCompletionBlock`
