### ISSUE TITLE
请问 mj哥 关于 动画做完的时候

### ISSUE THREAD

**Issue by zziajkx** [CoderMJLee/MJRefresh#145]
就是在 tableView 还没有回到原来位置的时候，再去请求数据，会出问题。能不能增加一个类似completion 动画完成，tableView 回到原来位置的回调。

**Comment by CoderMJLee** [comment]
这个不太可能会加进去哈。建议：加载成功或者失败的提示信息最好由开发者自己去定义，可以搞一些HUD指示器，比如MBProgressHUD。
