### ISSUE TITLE
collectionView修改了contentInset，造成footer的位置不正确，请问如何解决？

### ISSUE THREAD

**Issue by li-qingnan** [CoderMJLee/MJRefresh#1450]
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

😁为了能够更好地复现问题和修复问题, 请提供 Demo 和详细的 bug 重现步骤😭

🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

**描述bug**
1、使用的是collectionView，添加的继承于MJRefreshAutoFooter的自定义Footer。
2、在第一次获取数据后，根据数据情况，修改了collectionView.contentInset，然后判断是否collectionView.mj_footer是否存在，如果不存在就还是通过footerWithRefreshingBlock的方式设置了footer。此时footer的位置正常。
3、然后下拉刷新，获取数据后根据数据情况，又修改了collectionView.contentInset，然后判断是否collectionView.mj_footer是否存在，如果不存在就还是通过footerWithRefreshingBlock的方式设置了footer。这时的footer的位置就不对了，就是footer不能在底部正常的露出。

尝试了，下拉刷新获取数据根据数据情况，又修改了collectionView.contentInset后，将collectionView.mj_footer置nil，再重新通过footerWithRefreshingBlock的方式设置了footer，footer的位置还是不对的，还是footer不能在底部正常的露出。

log了一下数据，发现第一次添footer时，MJRefreshComponent里的scrollView的contentInset.bottom = 0，但是之后的scrollView的contentInset.bottom = -44了。

总结：多次修改collectionView.contentInset，就会造成footer的位置不对。

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
如何解决多次修改collectionView.contentInset，造成footer的位置不对的情况。

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone7
 - iOS13.5.1
 - Xcode11.5

**额外的**
最好能提供出现bug的Demo

**Comment by kinarobin** [comment]
看看这个属性能不能帮助到你：

`@property (assign, nonatomic) CGFloat ignoredScrollViewContentInsetBottom;`

**Comment by li-qingnan** [comment]
> 看看这个属性能不能帮助到你：
> 
> `@property (assign, nonatomic) CGFloat ignoredScrollViewContentInsetBottom;`

这个属性并不能解决我的问题，设置这个话，footer确实是可以露出来了，但是位置是透在cell的底下，而不是在内容的底部。

**Comment by ioslzx** [comment]
@li-qingnan 请问这个问题你改好没啊

**Comment by wolfcon** [comment]
> 如何解决多次修改collectionView.contentInset，造成footer的位置不对的情况。
@li-qingnan 建议你不要这样做 

如果你非要这样做, 那么请你上传你的 Demo, 并说明你的需求
