### ISSUE TITLE
tableview设置contentInset，上拉加载完成之后会向下滑动

### ISSUE THREAD

**Issue by ioslzx** [CoderMJLee/MJRefresh#1451]
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

😁为了能够更好地复现问题和修复问题, 请提供 Demo 和详细的 bug 重现步骤😭
tableview在scrollViewDidScroll代理方法里面，设置contentInset = UIEdgeInsetsMake(50, 0, 0, 0)，滑动到底部上拉加载时，tableview在刷新完会向下滑动44像素
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

**描述bug**
tableview设置contentInset，上拉加载问题

**必现/偶发?**
必现

**怎么样重现这个bug**
创建tableview，然后设置contentinset = UIEdgeInsetsMake(50, 0, 0, 0)，添加上拉加载
 
**你期望的结果是什么？**
上拉加载完成之后不向下滑动

**运行环境**
 - iPhone8
 - iOS13.5
 - Xcode11.5

**Comment by wolfcon** [comment]
不要在`scrollViewDidScroll` 中写任何东西

在 `endRefreshingCompletionBlock` 设置位置或者其他的什么操作

**Comment by ioslzx** [comment]
> 不要在`scrollViewDidScroll` 中写任何东西
> 
> 在 `endRefreshingCompletionBlock` 设置位置或者其他的什么操作

但是现在需要一个悬停效果，只能这么写
