### ISSUE TITLE
iOS13上 上拉加载更多回弹时 头部的cell会有动画冲突的效果

### ISSUE THREAD

**Issue by dwade333** [CoderMJLee/MJRefresh#1452]
**描述bug**
#1434 和这个bug一样 不过是在上拉加载更多的时候 导致回弹时 头部会有类似的效果

**必现/偶发?**
必现

还望能够处理下😆

**Comment by wolfcon** [comment]
目前的解决方案不是很完美, 建议先用 Auto 来替代一下.

**Comment by sizhugongzi** [comment]
这个demo的MJSingleViewController有问题，当你点击示例2刷新然后快速点击示例1刷新就奔溃。

**Comment by wolfcon** [comment]
@sizhugongzi 这个是由于 `__unsafe_unretained` 导致的, 你自己换成 `__weak` 即可. 这个问题跟这个 issue 无关
