### ISSUE TITLE
上拉加载更多MJRefreshAutoNormalFooter不显示

### ISSUE THREAD

**Issue by npzlxph0415** [CoderMJLee/MJRefresh#1453]
上拉提前预加载，当接口数据返回足够快的时候MJRefreshAutoNormalFooter一直不会在屏幕上出现导致上拉到最后一页数据的时候也不会显示；
如果上拉的足够快，在上拉的过程中MJRefreshAutoNormalFooter出现在了屏幕上，加载到最后一页的时候MJRefreshAutoNormalFooter就会有显示
![截屏2020-07-22 下午4 17 02](https://user-images.githubusercontent.com/17661049/88152574-cb570700-cc36-11ea-83bc-283c1964135f.png)

**Comment by wolfcon** [comment]
Duplicate of #1258
