### ISSUE TITLE
MJ_Reflesh 我奇思妙想的写在分类里面 用runtime的形式 为什么会崩溃？

### ISSUE THREAD

**Issue by 295060456** [CoderMJLee/MJRefresh#1454]
//
//  BaseVC+MJRefresh.h
//  MonkeyKingVideo
//
//  Created by Jobs on 2020/8/4.
//  Copyright © 2020 Jobs. All rights reserved.
//

#import "BaseVC.h"

NS_ASSUME_NONNULL_BEGIN

@interface BaseVC (MJRefresh)

#pragma mark —— BaseVC+MJRefresh
@property(nonatomic,strong)MJRefreshAutoGifFooter *tableViewFooter;
@property(nonatomic,strong)MJRefreshGifHeader *tableViewHeader;
@property(nonatomic,strong)MJRefreshBackNormalFooter *refreshBackNormalFooter;
///下拉刷新
-(void)pullToRefresh;
///上拉加载更多
- (void)loadMoreRefresh;

@end

NS_ASSUME_NONNULL_END

//
//  BaseVC+MJRefresh.m
//  MonkeyKingVideo
//
//  Created by Jobs on 2020/8/4.
//  Copyright © 2020 Jobs. All rights reserved.
//

#import "BaseVC+MJRefresh.h"
#import <objc/runtime.h>

@implementation BaseVC (MJRefresh)

static char *BaseVC_MJRefresh_tableViewHeader = "BaseVC_MJRefresh_tableViewHeader";
static char *BaseVC_MJRefresh_tableViewFooter = "BaseVC_MJRefresh_tableViewFooter";
static char *BaseVC_MJRefresh_refreshBackNormalFooter = "BaseVC_MJRefresh_refreshBackNormalFooter";

@dynamic tableViewHeader;
@dynamic tableViewFooter;
@dynamic refreshBackNormalFooter;

///下拉刷新
-(void)pullToRefresh{
    NSLog(@"下拉刷新");
}
///上拉加载更多
- (void)loadMoreRefresh{
    NSLog(@"上拉加载更多");
}
#pragma mark SET | GET
//MJ 这一套比较特殊 需要做调整 否则要崩溃
#pragma mark —— @property(nonatomic,strong)MJRefreshGifHeader *tableViewHeader;
-(MJRefreshGifHeader *)tableViewHeader{//get  objc_getAssociatedObject(self, BaseVC_MJRefresh_tableViewHeader);
    MJRefreshGifHeader *TableViewHeader =  [MJRefreshGifHeader headerWithRefreshingTarget:self
                                                                         refreshingAction:@selector(pullToRefresh)];
    // 设置普通状态的动画图片
    [TableViewHeader setImages:@[kIMG(@"官方")]
                      forState:MJRefreshStateIdle];
    // 设置即将刷新状态的动画图片（一松开就会刷新的状态）
    [TableViewHeader setImages:@[kIMG(@"Indeterminate Spinner - Small")]
                      forState:MJRefreshStatePulling];
    // 设置正在刷新状态的动画图片
//        [_tableViewHeader setImages:@[kIMG(@"gif_header_1"),
//                                      kIMG(@"gif_header_2"),
//                                      kIMG(@"gif_header_3"),
//                                      kIMG(@"gif_header_4")]
//                           duration:0.4
//                           forState:MJRefreshStateRefreshing];
    NSMutableArray *dataMutArr = NSMutableArray.array;
    for (int i = 1; i <= 55; i++) {
        NSString *str = [NSString stringWithFormat:@"gif_header_%d",i];
        [dataMutArr addObject:kIMG(str)];
    }

    [TableViewHeader setImages:dataMutArr
                       duration:0.7
                       forState:MJRefreshStateRefreshing];

    // 设置文字
    [TableViewHeader setTitle:@"Click or drag down to refresh"
                      forState:MJRefreshStateIdle];
    [TableViewHeader setTitle:@"Loading more ..."
                      forState:MJRefreshStateRefreshing];
    [TableViewHeader setTitle:@"No more data"
                      forState:MJRefreshStateNoMoreData];

    // 设置字体
    TableViewHeader.stateLabel.font = [UIFont systemFontOfSize:17];
    // 设置颜色
    TableViewHeader.stateLabel.textColor = KLightGrayColor;
    //震动特效反馈
    [TableViewHeader addObserver:self
                       forKeyPath:@"state"
                          options:NSKeyValueObservingOptionNew
                         context:nil];
    objc_setAssociatedObject(self,
                             BaseVC_MJRefresh_tableViewHeader,
                             TableViewHeader,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    return TableViewHeader;
}

-(void)setTableViewHeader:(MJRefreshGifHeader *)tableViewHeader{
    objc_setAssociatedObject(self,
                             BaseVC_MJRefresh_tableViewHeader,
                             tableViewHeader,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}
#pragma mark —— @property(nonatomic,strong)MJRefreshAutoGifFooter *tableViewFooter;
-(MJRefreshAutoGifFooter *)tableViewFooter{//objc_getAssociatedObject(self, BaseVC_MJRefresh_tableViewFooter);
    MJRefreshAutoGifFooter *TableViewFooter = [MJRefreshAutoGifFooter footerWithRefreshingTarget:self
                                                                refreshingAction:@selector(loadMoreRefresh)];
    // 设置普通状态的动画图片
    [TableViewFooter setImages:@[kIMG(@"官方")]
                      forState:MJRefreshStateIdle];
    // 设置即将刷新状态的动画图片（一松开就会刷新的状态）
    [TableViewFooter setImages:@[kIMG(@"Indeterminate Spinner - Small")]
                       forState:MJRefreshStatePulling];
    // 设置正在刷新状态的动画图片
//        [_tableViewFooter setImages:@[kIMG(@"gif_header_1"),
//                                      kIMG(@"gif_header_2"),
//                                      kIMG(@"gif_header_3"),
//                                      kIMG(@"gif_header_4")]
//                           duration:0.4
//                           forState:MJRefreshStateRefreshing];
    
    NSMutableArray *dataMutArr = NSMutableArray.array;
    for (int i = 1; i <= 55; i++) {
        NSString *str = [NSString stringWithFormat:@"gif_header_%d",i];
        [dataMutArr addObject:kIMG(str)];
    }

    [TableViewFooter setImages:dataMutArr
                       duration:0.4
                       forState:MJRefreshStateRefreshing];
    // 设置文字
    [TableViewFooter setTitle:@"Click or drag up to refresh"
                      forState:MJRefreshStateIdle];
    [TableViewFooter setTitle:@"Loading more ..."
                      forState:MJRefreshStateRefreshing];
    [TableViewFooter setTitle:@"No more data"
                      forState:MJRefreshStateNoMoreData];
    // 设置字体
    TableViewFooter.stateLabel.font = [UIFont systemFontOfSize:17];
    // 设置颜色
    TableViewFooter.stateLabel.textColor = KLightGrayColor;
    //震动特效反馈
    [TableViewFooter addObserver:self
                       forKeyPath:@"state"
                          options:NSKeyValueObservingOptionNew
                          context:nil];
    TableViewFooter.hidden = YES;
    objc_setAssociatedObject(self,
                             BaseVC_MJRefresh_tableViewFooter,
                             TableViewFooter,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    return TableViewFooter;
}

-(void)setTableViewFooter:(MJRefreshAutoGifFooter *)tableViewFooter{
    objc_setAssociatedObject(self,
                             BaseVC_MJRefresh_tableViewFooter,
                             tableViewFooter,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}
#pragma mark —— @property(nonatomic,strong)MJRefreshBackNormalFooter *refreshBackNormalFooter;
-(MJRefreshBackNormalFooter *)refreshBackNormalFooter{//objc_getAssociatedObject(self, BaseVC_MJRefresh_refreshBackNormalFooter);
    MJRefreshBackNormalFooter *RefreshBackNormalFooter = [MJRefreshBackNormalFooter footerWithRefreshingTarget:self
                                                                       refreshingAction:@selector(loadMoreRefresh)];
    objc_setAssociatedObject(self,
                             BaseVC_MJRefresh_refreshBackNormalFooter,
                             RefreshBackNormalFooter,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    return RefreshBackNormalFooter;
}

-(void)setRefreshBackNormalFooter:(MJRefreshBackNormalFooter *)refreshBackNormalFooter{
    objc_setAssociatedObject(self,
                             BaseVC_MJRefresh_refreshBackNormalFooter,
                             refreshBackNormalFooter,
                             OBJC_ASSOCIATION_RETAIN_NONATOMIC);
}

@end

**Comment by wolfcon** [comment]
请提供 Demo

**Comment by wolfcon** [comment]
框架已经提供了 `mj_header` 和 `mj_footer`, 请使用

**Comment by 295060456** [comment]
我这人有强迫症，我现在有个baseVC，里面有很多功能，我希望把不同的功能弄成分类的形式，但是分类是没有办法实例化属性的，只有用runtime，我其他功能这样做都没问题，唯独MJ_Reflesh，源码我确实没时间仔细看，功力可能也差很远，但我打断点的结果是，貌似出现了死循环。我突然想到MJ_Reflesh里面用了Rumtime方法交换，大量的，所以我想会不会和这个有关，我如果硬要满足我的强迫症，那么应该怎么写呢？谢谢回复。

**Comment by wolfcon** [comment]
```swift
extension <#YourBaseViewController#> {
    func setupRefreshControl() {
        <#yourScrollView#>.mj_header = MJRefreshGifHeader(refreshingBlock: { [unowned self] in 
             // Do something
        }

        <#yourScrollView#>.mj_footer = MJRefreshAutoGifFooter(refreshingBlock: { [unowned self] in 
             // Do something
        }
    }
}
```
