### ISSUE TITLE
横向左滑右滑刷新

### ISSUE THREAD

**Issue by hahaGitHub** [CoderMJLee/MJRefresh#1456]
现在我们使用MJRefresh实现了上拉下拉分页，但是我们现在有一个需求是横向实现左滑右滑分页功能。请问咱何时会支持呢？

**Comment by wolfcon** [comment]
`3.5.0`

**Comment by hahaGitHub** [comment]
@wolfcon 您好 我看到了这个
/** 左滑刷新控件 */
@property (strong, nonatomic, nullable) MJRefreshTrailer *mj_trailer;

不过这个只是左滑刷新，请问这个能实现右滑刷新吗？

**Comment by kinarobin** [comment]
@hahaGitHub 考虑到使用右滑的场景非常少，所以没有实现右滑刷新功能！
