### ISSUE TITLE
下拉刷新 crash

### ISSUE THREAD

**Issue by iOSyifeng** [CoderMJLee/MJRefresh#1458]
当下啦刷新 很长一段 超过cell距离时候 crash index 0 beyond bounds for empty array'

**Comment by wolfcon** [comment]
Demo?

**Comment by iOSyifeng** [comment]
> Demo?

公司项目 放不出来的 只是google了一下 的确有一些人遇到了这个问题

**Comment by iOSRG** [comment]
我也遇到了

**Comment by wolfcon** [comment]
@iOSRG 遇到就放 Demo
