### ISSUE TITLE
MJ,在nav中删除tableviewcell，但是删除方法没执行完，（即动画都没执行完，还在逻辑判断），此时我突然用nav返回pop到上一级，然后程序就挂了

### ISSUE THREAD

**Issue by nanmingzhidian** [CoderMJLee/MJRefresh#146]
![image](https://cloud.githubusercontent.com/assets/7157746/7536371/cf4e4dd8-f5c1-11e4-9d2e-c48ef56d1dd1.png)
错误就老是出现在这里

**Comment by CoderMJLee** [comment]
最新的2.0版本已经彻底解决此问题了哈
