### ISSUE TITLE
特定条件下, 下拉刷新导致cell不响应selectRow方法

### ISSUE THREAD

**Issue by jiaxiaochao** [CoderMJLee/MJRefresh#1461]
iPhoneX, 7p 真机 模拟器都复现 必现
设置UIEdgeInsets时 只要top为 0.5 、1.5 、2.5  、。。。所有以 .5 的数字就会复现 其他数字不会

1、初始化 UITableView时 设置
tableView.contentInset = UIEdgeInsets(top: 1.5, left: 0, bottom: 15, right: 0)
2、tableView只有一个或者两个数据未满一屏 
3、下拉刷新
4、点击 cell, 不触发 didSelectRow

调试到 MJRefreshHeader.m类中
scrollViewContentOffsetDidChange方法 offsetY > happenOffsetY 始终为true

**Comment by kinarobin** [comment]
@jiaxiaochao 方便上传一个demo上来不？

**Comment by jiaxiaochao** [comment]
[demo_mj.zip](https://github.com/CoderMJLee/MJRefresh/files/5212598/demo_mj.zip)

**Comment by kinarobin** [comment]
主要是因为当时为了解决这样的问题：
```objc
// 避免 CollectionView 在使用根据 Autolayout 和 内容自动伸缩 Cell, 刷新时导致的 Layout 异常渲染问题
if (self.scrollView.mj_insetT != insetT) {
    self.scrollView.mj_insetT = insetT;
}
```

**Comment by kinarobin** [comment]
@jiaxiaochao 感觉好像是 apple 的bug, 代码中不用MJRefresh, 单纯设置tableView的contentInset
`tableView.contentInset = UIEdgeInsets(top: 10.5, left: 0, bottom: 15, right: 0)`:

```objc
func scrollViewDidScroll(_ scrollView: UIScrollView) {
    print("scrollViewDidScroll------%@", scrollView.contentOffset.y)
}
```
打印的结果竟然是 ：**scrollViewDidScroll------%@ -98.33333333333333**

**Comment by jiaxiaochao** [comment]
估计是精度转换的问题 只能不适用 .5这样的数字了
