### ISSUE TITLE
我需要MJRefreshAutoNormalHeader

### ISSUE THREAD

**Issue by 597579501** [CoderMJLee/MJRefresh#1467]
**你的新功能建议是否牵扯到某个常见的问题？**
我需要一个类似我需要MJRefreshAutoNormalFooter的一样的我需要MJRefreshAutoNormalHeader

**你希望达到的效果**
因为有时候数据加载是反过来的。好比微信加载聊天记录是从tableview的上边获取的

**Comment by wolfcon** [comment]
自定义
