### ISSUE TITLE
MJRefreshComponent文件removeObservers 崩溃

### ISSUE THREAD

**Issue by DonsonWu** [CoderMJLee/MJRefresh#1468]
iOS 14.0
MJRefreshComponent 文件下的
- (void)willMoveToSuperview:(UIView *)newSuperview 方法没有做newSuperview的非空判断
导致removeObservers 下的方法崩溃
[self.superview removeObserver:self forKeyPath:MJRefreshKeyPathContentOffset]
是我使用姿势不正确吗？

**截图**
如果有必要的话，请上传几张截图
![image](https://user-images.githubusercontent.com/15194024/93959028-6335b600-fd8a-11ea-8d00-6794b8474a64.png)

**运行环境**
 - iPhone11
 - iOS14.0
 - Xcode12

**Comment by kinarobin** [comment]
@DonsonWu 是必现的么？

**Comment by DonsonWu** [comment]
我目前发现是必现，可以使用iOS 14.0调试一下

**Comment by wolfcon** [comment]
Demo?

**Comment by djp-djp-djp** [comment]
这个 有解决吗？iOS 26.3.1 偶现了

**Comment by gitph101** [comment]
您好，邮件已收到。
