### ISSUE TITLE
WKWebView正在加载的时候webView可以横向滑动，导致refreshHeader也会跟着滑动

### ISSUE THREAD

**Issue by CodeWCJ** [CoderMJLee/MJRefresh#1469]
**描述bug**
WKWebView正在加载的时候webView可以横向滑动，导致refreshHeader也会跟着滑动

**必现/偶发?**
必现

**怎么样重现这个bug**
WKWebView正在加载的时候webView可以横向滑动，导致refreshHeader也会跟着滑动

**你期望的结果是什么？**

> WKWebView正在加载的时候webView不可以横向滑动

**截图**
demo就可以重现

**Comment by wolfcon** [comment]
建议你把 webView 做在网页里面而不是原生实现. 否则填满横屏, 不要让其左右滑动.
因为左右滑动这个涉及到具体业务层面
- 有些希望跟着走
- 有些希望不动
- 有些希望滑动后仅展示一个圈

框架内不做处理, 实在想要可以自定义

**Comment by CodeWCJ** [comment]
好的，謝謝



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Frank"<notifications@github.com&gt;; 
发送时间: 2020年9月29日(星期二) 下午3:07
收件人: "CoderMJLee/MJRefresh"<MJRefresh@noreply.github.com&gt;; 
抄送: "晨风落叶"<1468619237@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CoderMJLee/MJRefresh] WKWebView正在加载的时候webView可以横向滑动，导致refreshHeader也会跟着滑动 (#1469)





 
建议你把 webView 做在网页里面而不是原生实现. 否则填满横屏, 不要让其左右滑动.
 因为左右滑动这个涉及到具体业务层面
  
有些希望跟着走
 
有些希望不动
 
有些希望滑动后仅展示一个圈
  
框架内不做处理, 实在想要可以自定义
