### ISSUE TITLE
objc_msgSend too many arguments to function call,expected 0, have3 

### ISSUE THREAD

**Issue by hbzhuhj** [CoderMJLee/MJRefresh#1471]
// 回调
```objc
if ([self.beginRefreshingTaget respondsToSelector:self.beginRefreshingAction]) {
   objc_msgSend(self.beginRefreshingTaget, self.beginRefreshingAction, self); // zhhj 2020.10.20 
}
```
            

编绎报错，objc_msgSend too many arguments to function call,expected 0, have3 

网上提供：选中项目 - Project - Build Settings - ENABLE_STRICT_OBJC_MSGSEND  将其设置为 NO 

但xcode12 没有ENABLE_STRICT_OBJC_MSGSEND

**Comment by wolfcon** [comment]
![image](https://user-images.githubusercontent.com/1538729/96687940-240f7a80-13b3-11eb-8a4f-68d2f77b9c9b.png)
Xcode 12

**Comment by AldenLei** [comment]
我Xcode 14.3.1版本，ENABLE_STRICT_OBJC_MSGSEND 将其设置为 NO在真机上拍还是会报这个错误，但是模拟器上跑没有报这个错误，求解呀
<img width="1126" alt="image" src="https://github.com/CoderMJLee/MJRefresh/assets/21965551/47995477-6f6b-41eb-aeb4-ebf65fe7787b">
