### ISSUE TITLE
Demo里的UICollectionView的example21,数据多的话下拉刷新bug

### ISSUE THREAD

**Issue by ioslzx** [CoderMJLee/MJRefresh#1472]
**描述bug**
当最底部cell滑出屏幕,松开手,最底部cell会先出来,然后回弹

**必现/偶发?**
必现

**怎么样重现这个bug**
1. example21
2. 先下拉刷新,多增加点数据,最少超出一屏的数据
3. 滚动到最底部的cell超出屏幕
4. cell会先显示,然后回弹

**你期望的结果是什么？**
正常的下拉刷新

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhonexr
 - iOS14
 - Xcode12

**额外的**
最好能提供出现bug的Demo
MJRefresh的demo

**Comment by wolfcon** [comment]
`self.collectionView.mj_header.isCollectionViewAnimationBug = YES;` 
加上这句

**Comment by anhuijhy** [comment]
加上isCollectionViewAnimationBug=yes,会导致多次连续刷新可能offset错位的情况。视频如附件

[RPReplay_Final1607398800.mov.zip](https://github.com/CoderMJLee/MJRefresh/files/5656699/RPReplay_Final1607398800.mov.zip)

**Comment by wolfcon** [comment]
因为现阶段这个问题还没有办法很好的解决, 在动画过程中, 禁用了手势, 可能会导致拉动的时候出现这种情况.

**Comment by anhuijhy** [comment]
@wolfcon 不好意思，我发过发现是在close的bug里，所以在bug里面又提了一个。另外我把isCollectionViewAnimationBug=NO,其实是可以的，就是有点抖。
