### ISSUE TITLE
UICollectionView 上拉刷新底部动画不隐藏

### ISSUE THREAD

**Issue by xhp281** [CoderMJLee/MJRefresh#1474]
**描述bug**
清晰简单地描述这个bug是啥
UICollectionView 上拉刷新底部动画不隐藏, 示例demo也是这样的

**必现/偶发?**
必现

**怎么样重现这个bug**
示例demo,  UICollectionView上拉刷新，底部的动画不隐藏

**运行环境**
 -模拟器 iPhoneX
 - iOS13
 - Xcode12

**Comment by wolfcon** [comment]
底部动画不隐藏是什么意思?

**Comment by xhp281** [comment]
> 底部动画不隐藏是什么意思?

可能是我表达的不对，就是刷新完底部那个箭头和时间都在 贴了截图辛苦看下
[https://xhp281-blog.oss-cn-beijing.aliyuncs.com/test/WechatIMG141.jpeg](url)

**Comment by wolfcon** [comment]
增加
```objc
self.collectionView.mj_footer.automaticallyChangeAlpha = YES;
```

**Comment by xhp281** [comment]
> 增加
> 
> ```objc
> self.collectionView.mj_footer.automaticallyChangeAlpha = YES;
> ```

我现在是自定义的一个动画，要怎么利用这个属性啊，我自己加了一个Lottie的动画控件，现在设置这个属性了还是不行，这个是我的设置代码

`// MARK: - 上拉刷新
class RefreshFooter: MJRefreshBackGifFooter {
    lazy var lottieView: AnimationView = {
        let lottie         = AnimationView(name: "loadMore")
        lottie.frame       = CGRect(x: (kScreenWidth - 32) / 2, y: 10, width: 32, height: 32)
        lottie.loopMode    = .loop
        lottie.contentMode = .scaleAspectFill
        lottie.isHidden    = false
        return lottie
    }()
    
    override func prepare() {
        super.prepare()
        self.stateLabel?.isHidden = true
        // 刷新文字颜色
        self.stateLabel?.textColor = ColorConst.theme
        // 状态文字
        self.setTitle(kRefreshFotterIdleText, for: .idle)
        self.setTitle(kRefreshHeaderPullingText, for: .pulling)
        self.setTitle(kRefreshHeaderRefreshingText, for: .refreshing)
        self.addSubview(lottieView)
    }
    
    override var state: MJRefreshState{
        didSet{
            if state == .refreshing {
                self.lottieView.play()
            }else if state == .pulling || state == .idle {
                self.lottieView.pause()
            }
        }
    }
}
`

**Comment by xhp281** [comment]
> ```objc
> ```objc
> self.collectionView.mj_footer.automaticallyChangeAlpha = YES;
> ```
> 
> 
>       
> ```

我再demo里面设置这个代码 self.collectionView.mj_footer.automaticallyChangeAlpha = YES; 也不起作用

**Comment by wolfcon** [comment]
```swift

    override var state: MJRefreshState {
        didSet {
            switch state {
                case .refreshing:
                    self.lottieView.play()
                case .idle, .noMoreData:
                    self.lottieView.pause()
                    UIView.animate(withDuration: 0.3) {
                        if self.isAutomaticallyChangeAlpha {
                            self.lottieView.alpha = 0
                        }
                    }
                case .pulling:
                    self.lottieView.pause()
                default:
                    break
            }
        }
    }
```

**Comment by wolfcon** [comment]
> > ```objc
> > ```objc
> > self.collectionView.mj_footer.automaticallyChangeAlpha = YES;
> > ```
> 
> 我再demo里面设置这个代码 self.collectionView.mj_footer.automaticallyChangeAlpha = YES; 也不起作用

大兄帶, 我写了一个 Demo, 用了你的代码, 设置了该属性, 能够正常隐藏.

**Comment by xhp281** [comment]
> > > ```objc
> > > ```objc
> > > self.collectionView.mj_footer.automaticallyChangeAlpha = YES;
> > > ```
> > 
> > 
> > 我再demo里面设置这个代码 self.collectionView.mj_footer.automaticallyChangeAlpha = YES; 也
> > 不起作用
> 
> 大兄帶, 我写了一个 Demo, 用了你的代码, 设置了该属性, 能够正常隐藏. 你参考一下吧
> 
> [SampleCode.zip](https://github.com/CoderMJLee/MJRefresh/files/5479703/SampleCode.zip)

好的，多谢，我发现是因为我设置偏移量导致的，已经可以了，感谢
