### ISSUE TITLE
iOS 14系统，tableView刷新后上移大概35个像素

### ISSUE THREAD

**Issue by simpleonly** [CoderMJLee/MJRefresh#1475]

**Comment by wolfcon** [comment]
demo

**Comment by anhuijhy** [comment]
加上isCollectionViewAnimationBug=yes,会导致多次连续刷新可能offset错位的情况。视频如附件。
[RPReplay_Final1607398800.mov.zip](https://github.com/CoderMJLee/MJRefresh/files/5656703/RPReplay_Final1607398800.mov.zip)
@wolfcon
