### ISSUE TITLE
如何扩展刷新后的状态回调？

### ISSUE THREAD

**Issue by Lovezysong** [CoderMJLee/MJRefresh#1476]
想在这个库的基础上，增加刷新后的状态回调，例如像今日头条那样，比如增加这个方法[self.tableView.mj_header endRefreshingWithStatus:@"获取了3条新动态"];

**Comment by wolfcon** [comment]
? 
`endRefreshing` 后调用你自己的方法不好吗?
这是你自己要定义的东西.

```swift
self.tableView.mj_header?.endRefreshing()
showTipMessage("xxxxx")
```

**Comment by Lovezysong** [comment]
你说的自定义展示消息我懂，效果不一样。endRefreshing后tabelview就已经回归原位置了，我的意思是，endRefreshing后会在mj_header的位置显示刷新后的状态，展示1秒后，tabelview再回弹

发自我的iPhone

> 在 2020年11月6日，11:14，Frank <notifications@github.com> 写道：
> 
> endRefreshing

**Comment by wolfcon** [comment]
```swift
popup(tips: "xxxxx")
DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
    self.tableView.mj_header?.endRefreshing()
}

func popup(tips: String) {

}
```
