### ISSUE TITLE
使用swiftOC混编  swift下上拉加载crash

### ISSUE THREAD

**Issue by yukifeng** [CoderMJLee/MJRefresh#1478]
> lazy var tableView:UITableView = {
        let tableView = UITableView(frame: CGRect(x: 0, y: 0, width: SCREEN_WIDTH, height: SCREENH_HEIGHT), style: .plain)
        tableView.dataSource = self
        tableView.delegate = self
        tableView.rowHeight = 50
        tableView.separatorStyle = .none
        tableView.mj_footer = MJRefreshBackNormalFooter(refreshingTarget: self, refreshingAction: #selector(loadData(searchCotent:)))
        tableView.register(GTTopicListCell.self, forCellReuseIdentifier: GTTopicListCell.description())
        return tableView
    }()

上拉后报错

-[MJRefreshBackNormalFooter copyWithZone:]: unrecognized selector sent to instance 0x11d451220

**Comment by yukifeng** [comment]
请问这是什么情况

**Comment by wolfcon** [comment]
Demo?

**Comment by yukifeng** [comment]
loadData(searchCotent:) 无参方法不会出现这个问题  已解决
