### ISSUE TITLE
上拉刷新在全面屏下会默认显示出来

### ISSUE THREAD

**Issue by zhonglaoban** [CoderMJLee/MJRefresh#1480]
**描述bug**
清晰简单地描述这个bug是啥
上拉刷新控件在全面屏下会默认显示出来。

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
demo首页

2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
期望上拉刷新控件在没有上拉的时候不显示

**截图**
![image](https://user-images.githubusercontent.com/14174614/100058839-ffe90280-2e64-11eb-85c1-c92483961057.png)

**运行环境**
 - iPhoneX
 - iOS12.4.1
 - Xcode12

**额外的**
clone下来的demo

**Comment by wolfcon** [comment]
Duplicate of #1474
