### ISSUE TITLE
trunk库比master库少了个版本号了

### ISSUE THREAD

**Issue by hubin97** [CoderMJLee/MJRefresh#1482]
**你的新功能建议是否牵扯到某个常见的问题？**
比如，在开发中，经常遇到XXX问题，目前框架的功能不足以解决这个问题

**你希望达到的效果**
比如，我希望框架能够帮助我解决XXX问题，实现XXXX那样的效果

**你能考虑到的可选实现方案**
描述一下你认为要实现这个功能，有哪些可行的一些实现方案？

**Comment by wolfcon** [comment]
Why not check out the [notes](https://github.com/CoderMJLee/MJRefresh/releases)

**Comment by hubin97** [comment]
[](https://tva1.sinaimg.cn/large/0081Kckwgy1glhqgkle4tj30uw0dmjv9.jpg)
删除本地master库后,查不到

**Comment by hubin97** [comment]
![](https://tva1.sinaimg.cn/large/0081Kckwgy1glhqgkle4tj30uw0dmjv9.jpg)
删除本地master库后,查不到
