### ISSUE TITLE
在 large title 下死循环+崩溃

### ISSUE THREAD

**Issue by Hesse-Huang** [CoderMJLee/MJRefresh#1486]
**描述bug**
使用 large title，下拉刷新 且 data 还没拿回来前，scroll view 手动往下滑时必现 crash。是一个有 setMj_insetT 和 KVO 参与的死循环。
如果是正常 navigation title 下没有问题。
下面附 demo app。

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 启用 demo app
2. 在 loading 结束前 scroll view 往下滑动 （navigation title 渐小）
3. 滑一下就马上卡死、崩溃

**你期望的结果是什么？**
不卡死不崩溃

**截图**
![image](https://user-images.githubusercontent.com/12207083/102860465-e2f61e00-4468-11eb-9297-588e0a23f81d.png)

**运行环境**
 - iPhone 11 Pro Simulator
 - iOS 14.3
 - Xcode 12.3 (12C33)

**额外的**
[LargeTitleCrash.zip](https://github.com/CoderMJLee/MJRefresh/files/5728353/LargeTitleCrash.zip)

**Comment by Hesse-Huang** [comment]
https://user-images.githubusercontent.com/12207083/102860988-d1614600-4469-11eb-8ddd-09ddc4ef873e.mov

**Comment by Hesse-Huang** [comment]
添加录屏
https://user-images.githubusercontent.com/12207083/102861062-f8b81300-4469-11eb-9f27-f9d065091ae9.mov

**Comment by wolfcon** [comment]
Duplicate of #1029
