### ISSUE TITLE
iOS 13.4.1 UICollectionView下拉刷新还是会出现闪动

### ISSUE THREAD

**Issue by XavierLost** [CoderMJLee/MJRefresh#1489]
**描述bug**
iOS 13.4.1 UICollectionView下拉刷新还是会出现闪动(文本),只是不会有折叠问题
使用
collectionView.mj_header?.isCollectionViewAnimationBug = true 
[结合下面可以解决]
UIView.performWithoutAnimation {
       collectionView.reloadData()
 }
**必现/偶发?**
必现

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone  SE, iPhone X
 - iOS 13.4.1,  iOS 14.3
 - Xcode 12.3

**额外的**
最好能提供出现bug的Demo

**Comment by alienJion** [comment]
跟新版本，使用isCollectionViewAnimationBug方法
CollectionView.mj_header.isCollectionViewAnimationBug = YES;

**Comment by wolfcon** [comment]
闪动的图麻烦给一张或者描述一下...
