### ISSUE TITLE
有sectionHeader的时候刷新，在没有停止刷新的时候往上拖sectionHeader会移位

### ISSUE THREAD

**Issue by cbahai** [CoderMJLee/MJRefresh#149]
有sectionHeader的时候刷新，在没有停止刷新的时候往上拖sectionHeader会移位。

(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section { UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, tableView.frame.size.width, 30)]; view.backgroundColor = [UIColor redColor]; return view; }
这个header就会移位了。

**Comment by cbahai** [comment]
![333rrr](https://cloud.githubusercontent.com/assets/5957012/7567231/3f9aaeba-f82e-11e4-994e-d09baa6c25df.png)

**Comment by cbahai** [comment]
刷新完成之后往上拖就正常，如图：
![Uploading iOS Simulator Screen Shot 2015年5月11日 下午10.40.39.png…]()

**Comment by cbahai** [comment]
刷新完成之后往上拖就正常，如图：
![ios simulator screen shot 2015 5 11 10 40 39](https://cloud.githubusercontent.com/assets/5957012/7567450/a8c38e74-f82f-11e4-8cc3-de182890a0ca.png)

**Comment by mryun11** [comment]
不知2.0有没有解决这个问题？

**Comment by 624560545** [comment]
下载最新版就可以了

**Comment by RobotAmiee** [comment]
// 在刷新的refreshing状态
    if (self.state == MJRefreshStateRefreshing) {
        // sectionheader停留解决
        return;
    }

还没解决，可以参考下https://github.com/samvermette/SVPullToRefresh/blob/master/SVPullToRefresh/UIScrollView%2BSVPullToRefresh.m 中 setScrollViewContentInsetForLoading 方法的做法？

**Comment by wyhazq** [comment]
换一个，谢谢，这个框架里面的下拉控件处理了这个问题https://github.com/zhuchaowe/EasyIOS，就是SV的

**Comment by wyhazq** [comment]
换一个，谢谢，这个框架里面的下拉控件处理了这个问题https://github.com/zhuchaowe/EasyIOS，就是sv的

**Comment by wyhazq** [comment]
换一个，谢谢，这个框架里面的下拉控件处理了这个问题，就是sv的，https://github.com/zhuchaowe/EasyIOS

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈
