### ISSUE TITLE
能出个SwiftUI版本的刷新吗？

### ISSUE THREAD

**Issue by damonZDM** [CoderMJLee/MJRefresh#1490]
SwiftUI没有好用的刷新控件，这款刷新控件用的人最多。
希望能够支持SwiftUI

**Comment by DuShuYuan** [comment]
支持

**Comment by wolfcon** [comment]
实现机制不同. 不是这个库该干的

**Comment by jiapumin** [comment]
swiftUI使用的越来越多，可以考虑支持下

**Comment by gitph101** [comment]
您好，邮件已收到。

**Comment by 309598016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
