### ISSUE TITLE
继承于MJRefreshHeader的控件内部做动画，某些情况下当VC销毁时，无法释放控件对象。

### ISSUE THREAD

**Issue by nameIsYong** [CoderMJLee/MJRefresh#1493]
**我的新功能遇到一个目前无法解决的问题？**

比如，自定义控件xxxHeader继承于MJRefreshHeader，在内部用NSTimer或CADisplayLink做动画。

若：网络请求完，手动调用[tableView.mj_header endRefreshing]，在监听方法- (void)setState:(MJRefreshState)state后，调用对应结束动画的代码，则可以结束定时器，销毁timer，则可销毁该header控件；

问题：正在网络请求时，在不调用[tableView.mj_header endRefreshing]情况下，直接把当前VC给dismiss或pop掉，则无法拦截到- (void)setState:(MJRefreshState)state方法，则Timer无法销毁，则该header控件无法销毁；

****
请教一下，像这种情况请问如何解决呢，谢谢~~。

**Comment by wolfcon** [comment]
写个 Demo?

> 你在 dismiss 或者 pop 的时候为什么不先调用 `endRefreshing`/ 或者销毁 Timer?

**Comment by nameIsYong** [comment]
> 写个 Demo?
> 
> > 你在 dismiss 或者 pop 的时候为什么不先调用 `endRefreshing`/ 或者销毁 Timer?

若在dismiss或pop的时候还调用endRefreshing销毁Timer比较麻烦，因为项目里面涉及到这样的VC都要改动。

这里是demo，运行工程中的“TestTX120”
链接: https://pan.baidu.com/s/1Ze7c6N7Is_Wa7vWRrRy2qQ 提取码: i3ch 复制这段内容后打开百度网盘手机App，操作更方便哦

谢谢~~

**Comment by wolfcon** [comment]
> 题外话: Demo 直接拖到对话框即可

建议你加上
```objc
- (void)viewDidDisappear:(BOOL)animated {
    [super viewDidDisappear:animated];
    
    [self.tableView.mj_header endRefreshing];
}
```

**Comment by nameIsYong** [comment]
> > 题外话: Demo 直接拖到对话框即可
> 
> 建议你加上
> 
> ```objc
> - (void)viewDidDisappear:(BOOL)animated {
>     [super viewDidDisappear:animated];
>     
>     [(TX120RefreshHeader *)self.tableView.mj_header clearTimer];
>     // or 
>     // [self.tableView.mj_header endRefreshing];
> }
> ```

好的，谢谢~~
