### ISSUE TITLE
footer能否写在懒加载里面

### ISSUE THREAD

**Issue by 295060456** [CoderMJLee/MJRefresh#1495]
我喜欢代码块管理，很自然的就是懒加载，在里面全部配置完，外界调用
-(UICollectionView *)collectionView{
    if (!_collectionView) {
        _collectionView = [[UICollectionView alloc] initWithFrame:CGRectZero
                                             collectionViewLayout:self.layout];
        _collectionView.backgroundColor = self.bgCor;
        _collectionView.dataSource = self;
        _collectionView.delegate = self;
        _collectionView.showsVerticalScrollIndicator = NO;
        
        _collectionView.mj_header = self.mjRefreshGifHeader;
        _collectionView.mj_header.automaticallyChangeAlpha = YES;//根据拖拽比例自动切换透明度
//        _collectionView.mj_footer = self.mjRefreshAutoNormalFooter;
//        _collectionView.mj_footer.hidden = YES;
        
        _collectionView.contentInset = UIEdgeInsetsMake(0, 0, 50, 0);
        
        [_collectionView RegisterClass];

//        [self.scrollView addSubview:_collectionView];
        [self.view addSubview:_collectionView];
        [_collectionView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.edges.equalTo(self.view);
        }];
    }return _collectionView;
}

我很仔细的对比了demo
我的写法是：在懒加载里面进行配置
demo的写法是，请求到了数据才进行生成

我知道是监视contentsize。但如果要像我一样的写法，我需要做些什么，目前我的footer是在顶端

**Comment by 295060456** [comment]
我自答自问吧。我重写
-(void)viewDidLayoutSubviews{
    [super viewDidLayoutSubviews];
    collectionView.mj_footer.y = collectionView.contentSize.height;
}

**Comment by 295060456** [comment]
![image](https://user-images.githubusercontent.com/13795605/104834468-109c7e80-58d2-11eb-852a-328c6a980868.png)
![image](https://user-images.githubusercontent.com/13795605/104834471-18f4b980-58d2-11eb-947e-c7916d0f0ee3.png)
![image](https://user-images.githubusercontent.com/13795605/104834482-2ad65c80-58d2-11eb-91bc-afb6361db7e1.png)

**Comment by 295060456** [comment]
将封装追求到极致。
还有个就是我记忆力不是很好，这样做的话我下次直接复制粘贴，没必要再看你的demo

**Comment by wolfcon** [comment]
你这样不感觉多此一举么...凭空再搞出一个 targetView...

另外首先 Demo 不是请求到数据才配置的 Footer.
是在 `viewDidLoad` 里配置好的.

在你的配置里, 不清楚是否有初始数据, **如果没有的话, 那 footer 可不就在最顶上么.** 如果不想显示出 Footer 那么就在第一次获取到/配置数据时显示/配置 footer. 

> 如果你想得到一个更好的代码结构, 我建议你写一个 Demo, 拖上来
