### ISSUE TITLE
MJ老师，新版的MJRefresh的上拉刷新能增加一个类似老版本刷新回弹的功能吗？

### ISSUE THREAD

**Issue by CNKCQ** [CoderMJLee/MJRefresh#150]
就是类似老版本，刷新，加载，回弹就OK了，因为我们这边的app,是一次性加载刷新20个，并不是类似您那种往下增加20个那样。所以不回弹太难看了。本来打算用老版本的，但是老版本的下拉刷新也有问题，就是你还在刷新加载的一瞬间，切换到别的页面，回弹位置会往上过多偏移的Bug.

**Comment by gzucm** [comment]
pull request #164 可能满足你的需求。

**Comment by CoderMJLee** [comment]
2.0版本已经拥有这个功能了哈
