### ISSUE TITLE
MJRefreshAutoFooter 在设置triggerAutomaticallyRefreshPercent 设置较大的负值时，下拉刷新时，header和footer的刷新方法会同时触发

### ISSUE THREAD

**Issue by zhmios** [CoderMJLee/MJRefresh#1500]
问题描述：
MJRefreshAutoFooter 在设置triggerAutomaticallyRefreshPercent 较大的负值（例如-50）时，下拉刷新数据时，header和footer的刷新方法会同时触发。
理论上负值不应该太大，超出屏幕似乎更不合理，所以算优化建议

优化建议：
在MJRefreshAutoFooter类中，scrollViewContentOffsetDidChange:方法的if (_scrollView.mj_offsetY >= _scrollView.mj_contentH - _scrollView.mj_h + self.mj_h * self.triggerAutomaticallyRefreshPercent + _scrollView.mj_insetB - self.mj_h)条件中，增加_scrollView.mj_offsetY>-_scrollView.mj_insetT的条件，以免在下拉刷新时触发footer的刷新方法。

**Comment by wolfcon** [comment]
兄弟, 你这个过分了啊...这玩意是来调节自动刷新的控件在底部显示时漏出的触发百分比. 取值一般在 -1~1 之间...你这个-50.....

**Comment by zhmios** [comment]
😁 你说的对，知道是因为负值过大导致footer和header判断同时满足触发了它们的刷新，加上我说的判断能够兼容那些不合理的负值情况，所以算优化...,我自己其实在自定义footer重写了- (void)beginRefreshing,做了兼容。
