### ISSUE TITLE
MJRefreshAutoFooter 在翻了两页之后不执行了

### ISSUE THREAD

**Issue by Mayinwei** [CoderMJLee/MJRefresh#1501]
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

😁为了能够更好地复现问题和修复问题, 请提供 Demo 和详细的 bug 重现步骤😭

🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶
> 记得删除以上内容

**描述bug**
uitableview 上拉加载更多，翻页不执行block  
**必现/偶发?**
这个必先

**怎么样重现这个bug**
1. 显示哪个页面
2. 点击哪个位置
3. 滚动到哪个位置
4. 发生了什么错误

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
如果有必要的话，请上传几张截图

**运行环境**
 - iPhone11 pro
 - iOS14.4
 - Xcode12.4

**额外的**
最好能提供出现bug的Demo

**Comment by wolfcon** [comment]
Demo
