### ISSUE TITLE
MJRefreshStateWillRefresh为什么不会调用

### ISSUE THREAD

**Issue by DotaAntiMagic** [CoderMJLee/MJRefresh#1505]
请问下MJRefreshStateWillRefresh是在什么时候调用,我用的demo里面的MJRefreshStateWillRefresh为啥都不走呢？
- (void)setState:(MJRefreshState)state
{
    MJRefreshCheckState;
    
    switch (state) {
        case MJRefreshStateIdle:
            NSLog(@"普通闲置状态");
            break;
        case MJRefreshStatePulling:
            NSLog(@"松开就可以进行刷新的状态");
            break;
        case MJRefreshStateRefreshing:
            NSLog(@"正在刷新中的状态");
            break;
        case MJRefreshStateWillRefresh:
            NSLog(@"即将刷新的状态 ");
            break;
        case MJRefreshStateNoMoreData:
            NSLog(@"所有数据加载完毕，没有更多的数据了");
        default:
            break;
    }
}

**Comment by wolfcon** [comment]
```objc
// 只要正在刷新，就完全显示
    if (self.window) {
        self.state = MJRefreshStateRefreshing;
    } else {
        // 预防正在刷新中时，调用本方法使得header inset回置失败
        if (self.state != MJRefreshStateRefreshing) {
            self.state = MJRefreshStateWillRefresh;
            // 刷新(预防从另一个控制器回到这个控制器的情况，回来要重新刷新一下)
            [self setNeedsDisplay];
        }
    }
```

willRefresh 状态只有在控件不在 window 上的时候才会有这个状态. 普通是没这个状态的.
