### ISSUE TITLE
kvo崩溃

### ISSUE THREAD

**Issue by songxing10000** [CoderMJLee/MJRefresh#1509]
![Snip20210331_52](https://user-images.githubusercontent.com/10040131/113127683-9bdbae00-924b-11eb-85dd-2128ee85d648.png)

**Comment by wolfcon** [comment]
Demo? 细节有吗?

**Comment by songxing10000** [comment]
偶现，未找到复现路径

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Frank ***@***.***>
发送时间: Thursday, April 1, 2021 2:03:38 PM
收件人: CoderMJLee/MJRefresh ***@***.***>
抄送: xingsong ***@***.***>; Author ***@***.***>
主题: Re: [CoderMJLee/MJRefresh] kvo崩溃 (#1509)


Demo? 细节有吗?

―

**Comment by Danie1s** [comment]
我这边也出现了

由于 是对 scrollView 进行 KVO 监听，所以移除的时候也要对 scrollView 进行 removeObserver，如下图
![image](https://github.com/CoderMJLee/MJRefresh/assets/19432029/a0a895f1-3da9-47ed-937c-6afa1c2a17f1)
