### ISSUE TITLE
希望添加右滑自动加载

### ISSUE THREAD

**Issue by iOSleep** [CoderMJLee/MJRefresh#1510]
**你的新功能建议是否牵扯到某个常见的问题？**
横向滚动的时候自动加载，在 iPad 上的儿童类应用比较常见

**你希望达到的效果**
滑动后松手滚动到右侧自动触发刷新，类似 footer 的`automaticallyRefresh` 

**你能考虑到的可选实现方案**
修改部分 `MJRefreshAutoFooter` 的代码应该能打到效果

**Comment by wolfcon** [comment]
请自定义
