### ISSUE TITLE
先设置tableView.mj_footer，后设置tableView.contentInset时，mj_footer的位置不正确

### ISSUE THREAD

**Issue by jiasongs** [CoderMJLee/MJRefresh#1511]
**描述bug**
先设置tableView.mj_footer，后设置tableView.contentInset时，mj_footer的位置不正确，或者说contentInset只计算了mj_footer的高度，没有计算我后续更改的contentInset，导致tableView.contentSize没有正确被设置，从而引起mj_footer被全面屏指示条遮挡。只要后设置tableView.contentInset，mj_footer必定被遮挡

**必现/偶发?**
必现

**怎么样重现这个bug**
[MJRefreshIssue.zip](https://github.com/CoderMJLee/MJRefresh/files/6316041/MJRefreshIssue.zip)
这个Demo可以完全复现，Demo中我标记了注释「issue1」「issue2」, 可以先后注释掉看看效果

**你期望的结果是什么？**
前后设置tableView.contentInset，都可以符合预期。
目前的解决方案只能手动再加一下mj_footer的高度。

**截图**
见Demo

**运行环境**
 - iPhone 12 Pro 模拟器
 - iOS 14.4
 - Xcode 12.4

**Comment by jiasongs** [comment]
<img width="1183" alt="图片" src="https://user-images.githubusercontent.com/22904757/114836485-4d124480-9e05-11eb-8e91-e3aa1cd98793.png">
写了个解决方案

**Comment by wolfcon** [comment]
的确有这个问题, 因为修改 TableView 的 contentInsets 是在 `- (void)willMoveToSuperview:` 中进行的.
请先设置 contentInset, 再添加 component.

如果实在是想先添加 footer, 再修改 contentinsets. 你应该这样做(你原始的方法是错误的. 因为覆盖了框架设置的值)
```swift
    var contentInsets: UIEdgeInsets {
        var top = self.view.safeAreaInsets.top
        if top <= 0 {
            top = UIApplication.shared.windows.first?.safeAreaInsets.top ?? 0
        }
        var bottom = self.view.safeAreaInsets.bottom
        if bottom <= 0 {
            bottom = UIApplication.shared.windows.first?.safeAreaInsets.bottom ?? 0
        }
        
        var contentInset = self.tableView.contentInset
        contentInset.top += top
        contentInset.bottom += bottom
        
        print("top: \(top), bottom: \(bottom)")
        return contentInset
    }
```

**Comment by jiasongs** [comment]
> ### 乍看之下的确有这个问题
> 
> 因为框架会对 `tableView` 的 `contentInset` 进行设置, 它是在 `- (void)willMoveToSuperview:` 中.
> 所以请先设置 contentInset, 再添加 component. 确保框架有把值计算进去.
> ### 但其实你的使用方式是有问题的
> 
> 如果实在是想先添加 footer, 再修改 `contentInset`. 你应该这样做(你原始的方法是错误的. 因为覆盖了框架设置的值), `你要修改, 需要在原值的基础上进行添加或者删减, 不应该直接覆盖一个固定值)`
> 
> ```swift
>     var contentInsets: UIEdgeInsets {
>         var top = self.view.safeAreaInsets.top
>         if top <= 0 {
>             top = UIApplication.shared.windows.first?.safeAreaInsets.top ?? 0
>         }
>         var bottom = self.view.safeAreaInsets.bottom
>         if bottom <= 0 {
>             bottom = UIApplication.shared.windows.first?.safeAreaInsets.bottom ?? 0
>         }
>         
>         var contentInset = self.tableView.contentInset
>         contentInset.top += top
>         contentInset.bottom += bottom
>         
>         print("top: \(top), bottom: \(bottom)")
>         return contentInset
>     }
> ```

这个写法有可能会多次累加contentInset，也造成了维护的难度，业务上不清楚contenInset到底加了多少bottom，不如直接加上mj_footer的高度来的直观和可控。

我写了个修复的程序，参考「UIScrollView+__RMUIFix」，目前不改动源码的情况下可以修正这类情况，作者酌情考虑是否有必要适配，我个人认为是有必要的，因为框架里设置了`self.scrollView.mj_insetB += self.mj_h;`，那么业务上不清楚你到底加没加footer的高度，当然业务上每次设置contentInset时手动加上footer的高度也合理，就是比较麻烦。修复程序如下：
[MJRefreshIssue.zip](https://github.com/CoderMJLee/MJRefresh/files/6317048/MJRefreshIssue.zip)

**Comment by wolfcon** [comment]
麻烦提个 pr 看吧.

**Comment by jiasongs** [comment]
> 麻烦提个 pr 看吧.

有时间会提交个PR

**Comment by jiasongs** [comment]
> ### 乍看之下的确有这个问题
> 
> 因为框架会对 `tableView` 的 `contentInset` 进行设置, 它是在 `- (void)willMoveToSuperview:` 中.
> 所以请先设置 contentInset, 再添加 component. 确保框架有把值计算进去.
> ### 但其实你的使用方式是不正确的
> 
> 如果实在是想先添加 footer, 再修改 `contentInset`. `要想修改, 需要在原值的基础上进行添加或者删减, 不应该直接覆盖一个固定值)`
> 应该这样做(你原来的方法是错误的. 因为覆盖了框架设置的值)
> 
> ```swift
>     var contentInsets: UIEdgeInsets {
>         var top = self.view.safeAreaInsets.top
>         if top <= 0 {
>             top = UIApplication.shared.windows.first?.safeAreaInsets.top ?? 0
>         }
>         var bottom = self.view.safeAreaInsets.bottom
>         if bottom <= 0 {
>             bottom = UIApplication.shared.windows.first?.safeAreaInsets.bottom ?? 0
>         }
>         // 这里是关键之处. 
>         var contentInset = self.tableView.contentInset
>         contentInset.top += top
>         contentInset.bottom += bottom
>         
>         print("top: \(top), bottom: \(bottom)")
>         return contentInset
>     }
> ```

我后面想了一下，这个问题比较棘手，而且也不属于框架用法的问题，属于MJRefreshAutoFooter的设计缺陷
<img width="479" alt="图片" src="https://user-images.githubusercontent.com/22904757/117264189-92b2b200-ae85-11eb-8f2a-f4581b37b34b.png">
<img width="503" alt="图片" src="https://user-images.githubusercontent.com/22904757/117264700-0e146380-ae86-11eb-91b4-d40f4b4c70b5.png">
使用者必须在触发「这俩方法前先设置contentInset」或者必须在「触发这两个方法后再设置contentInset」，其他情况都会有问题，但是使用者在业务上并不能保证完全在这两个方法前后设置，我在想如何解决此问题
