### ISSUE TITLE
collectionView.mj_footer.hidden

### ISSUE THREAD

**Issue by DotaAntiMagic** [CoderMJLee/MJRefresh#1513]
我是做的分类菜单页面,点击左侧分类变换右边商品，右边的商品是collectionview布局有多种collectionviewcell样式,但是当我来回切换左侧分类的时候,右边collectionview我会设置collectionView.mj_footer.hidden，这时候会发生页面cell闪现的非常巨大下又正常的现象，去掉collectionView.mj_footer.hidden就正常了

**Comment by wolfcon** [comment]
Why hidden? 

Demo?

**Comment by DotaAntiMagic** [comment]
是业务上的需求,在到最后一页的时候滑动 是要隐藏footer，demo暂时还没有

**Comment by wolfcon** [comment]
截图~, 拍视频.
