### ISSUE TITLE
在`scrollViewDidScroll`里处理其它逻辑时遇到的问题

### ISSUE THREAD

**Issue by friendsheeps** [CoderMJLee/MJRefresh#1516]
项目中有个需求，tableView后有一个背景图，需要跟随tableView一起滑动，但目前不能把它做成tableView的headerView，所以用了一个UIImageView，想在- (void)scrollViewDidScroll:(UIScrollView *)scrollView方法里通过判断scrollView.contentOffset.y来改变它的frame。
目前遇到的问题时使用MJRefreshStateHeader后，当向下拖动很大一段距离后松手，从 MJRefreshStatePulling 进入 MJRefreshStateRefreshing 和 刷新结束从 MJRefreshStateRefreshing 进入 MJRefreshStateIdle 时 scrollView.contentOffset.y 会变化很快，tableView视觉上很平滑的回弹，但是UIImageView视觉上会很跳跃，和tableView不同步。请问该如何修改以达到同步效果。
<img width="183" alt="截屏2021-05-07 上午9 10 46" src="https://user-images.githubusercontent.com/13128046/117385958-a0fdde00-af18-11eb-8fe1-6caae10cf347.png">

**Comment by wolfcon** [comment]
因为有动画.

**Comment by wolfcon** [comment]
动画会有独立的 View 去渲染动画, 和实际的 View 不是同一个.
