### ISSUE TITLE
自定义footer高度问题

### ISSUE THREAD

**Issue by iOSyifeng** [CoderMJLee/MJRefresh#1517]
自定义footer时候 想要在 state == noMoreData 时  改变footer高度 其余状态下高度不变 但是只在 state == noMoreData 设置高度没有用

**Comment by wolfcon** [comment]
Demo?

**Comment by iOSyifeng** [comment]
- (void)setState:(MJRefreshState)state
{
    MJRefreshCheckState;
    
    switch (state) {
        case MJRefreshStateIdle:
            self.label.text = @"赶紧上拉吖(开关是打酱油滴)";
            [self.loading stopAnimating];
            [self.s setOn:NO animated:YES];
            break;
        case MJRefreshStateRefreshing:
            [self.s setOn:YES animated:YES];
            self.label.text = @"加载数据中(开关是打酱油滴)";
            [self.loading startAnimating];
            break;
        case MJRefreshStateNoMoreData:
            self.label.text = @"木有数据了(开关是打酱油滴)";
            [self.s setOn:NO animated:YES];
            [self.loading stopAnimating];
            self.mj_h = 250;
            break;
        default:
            break;
    }
}

self.mj_h = 250 是没有用的

**Comment by wolfcon** [comment]
你上传整个工程上来吧. 我这边加了这行是有效的.

**Comment by iOSyifeng** [comment]
嗯 是有效的 我看了下层级 其实高度是设置上的 但是我希望的效果是整个footer在滑动到没数据时候能完全露出来 但是它只会根据最开始的高度来展示 不知道是不是contentOffset哪里有问题么

**Comment by wolfcon** [comment]
修改 ContentInset 的 bottom

**Comment by iOSyifeng** [comment]
直接改tableView 的么  还是mj footer里面有相关改的地方啊?

**Comment by wolfcon** [comment]
> 直接改tableView 的么 还是mj footer里面有相关改的地方啊?

对修改 TableView 的. 但是你要考虑好时机. 不要在动画中做这个事, 会干扰框架本身刷新前的记录值, 最终导致恢复时出错.

**Comment by iOSyifeng** [comment]
但其实这样有点不好 就是我每个业务的tableView页面如果都想要这种效果 都要去改下 如果框架支持的话 我重写下footer就好了啊

**Comment by wolfcon** [comment]
这个属于自定义了. 你自定义一个 Footer.
