### ISSUE TITLE
混编带来的继承问题 

### ISSUE THREAD

**Issue by yanghl** [CoderMJLee/MJRefresh#1519]
**描述bug**

swift项目重写 header 赋值方法 编译报错

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 创建一个swift 组件【testLib】  里面建一个基类baseTest。创建一个返回header刷新头的方法   例如：
open func refreshHeader() -> MJRefreshNormalHeader {
        return MJRefreshNormalHeader(refreshingBlock: { [weak self]  in
            self?.headerRefreshing()
        })
    }

2. 创建一个swift 主工程项目  引入 testLib组件。  建一个子类 继承baseTest  然后重写 refreshHeader 函数 

这时候编译提示：
Cannot inherit from class 'AXRefreshTableViewController' because it has overridable members that could not be loaded

**你期望的结果是什么？**
需求是这样的  主工程自定义刷新header  覆盖组件通用的刷新header封装

**运行环境**
 - Xcode12.4
- Swift 5

**Comment by wolfcon** [comment]
这是你 `AXRefreshTableViewController` 它的问题. 跟框架有什么关系. 
如果你实在是不知道怎么解决, 你可以传个 Demo 上来.

**Comment by yanghl** [comment]
根本原因昨天我们已经定位到了  、、和podfile 中这两个配置有关
#use_frameworks!
#use_modular_headers!

采用了use_modular_headers 可以正常实现方法继承

采用 use_frameworks 就会提示 那个错误，，

如果你依然需要demo 定位问题 ，回复我，我可以稍厚帮你写一个

**Comment by wolfcon** [comment]
你引入框架是怎么引入的呢? 
不是用 
```swift
import MJRefresh
```
而是从 Bridge Header 引入的?

**Comment by yanghl** [comment]
使用 import MJRefresh方式

**Comment by wolfcon** [comment]
有空来个 Demo 看下

**Comment by wolfcon** [comment]
这里补充一下, Demo 我已经收到啦. 我描述一下问题, 顺带回答这个解决方案(这个解决方案只是规避了问题, 并没有解决问题)

> 根本原因昨天我们已经定位到了 、、和podfile 中这两个配置有关
> #use_frameworks!
> #use_modular_headers!
> 
> 采用了use_modular_headers 可以正常实现方法继承
> 
> 采用 use_frameworks 就会提示 那个错误，，
> 
> 如果你依然需要demo 定位问题 ，回复我，我可以稍厚帮你写一个

Demo 里是将 `MJRefresh` 以依赖方式引入了一个动态库, `Pod` 将这个动态库作为本地库再被一个业务工程引用, 导致出来的问题.

这里的业务工程里使用了混编, 在 `BridgeHeader` 中写入了 `#import <MJRefresh.h>`, 同时动态库以 `import MJRefresh` 方式引入. 这里造成了编译时的错误, 仅需要将 `BridgeHeader` 中的引入删掉就会解决问题.

这里也给后面来这里看的大家一个建议, 对于混编的工程, 引入框架时, 注意一致性.
