### ISSUE TITLE
添加上拉刷新的时候会崩溃

### ISSUE THREAD

**Issue by qs3673132** [CoderMJLee/MJRefresh#152]
每次调用 [self.tableView addLegendFooterWithRefreshingTarget:self refreshingAction:@selector(footerRereshing)];的时候都会崩溃，不知道怎么回事

![2015-05-13 10 09 44](https://cloud.githubusercontent.com/assets/8708750/7602645/a2c0c426-f959-11e4-9699-05b3b6adc82e.png)

**Comment by BenLoomToys** [comment]
我也出现过,求MJ给出建议啊

**Comment by godlikeonline** [comment]
我也遇到了,是不是使用了autolayout?

**Comment by CoderMJLee** [comment]
我亲自测试了一下，Xcode7，MJRefresh2.0，CocosPods0.36.3。没有一点问题哈。

**Comment by godlikeonline** [comment]
我也遇到了这个问题,使用的时pod进行安装的,后来发现无法进入源代码进行调试,后来改用手动安装,之后就没有报错,估计是coccoapod没有正确安装的原因.
