### ISSUE TITLE
关于设置刷新视图的mj_w和mj_x

### ISSUE THREAD

**Issue by iamkata** [CoderMJLee/MJRefresh#1520]
我在你们的Demo中给tableView添加了内边距
```
- (void)example01
{
    __weak __typeof(self) weakSelf = self;
    
    //添加内边距
    self.tableView.contentInset = UIEdgeInsetsMake(0, 20, 0, 30);
    
    MJRefreshNormalHeader *header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [weakSelf loadNewData];
    }];
    header.backgroundColor = [UIColor systemPinkColor];
    self.tableView.mj_header = header;
    
    // 马上进入刷新状态
    [self.tableView.mj_header beginRefreshing];
    
    self.tableView.backgroundColor = [UIColor yellowColor];
}
```

你们的代码MJRefreshComponent.m里面：
```
self.mj_w = _scrollView.mj_w; //屏幕宽度
self.mj_x = -_scrollView.mj_insetL; // -20
```

所以这就导致我的mj_header是这样的，如下图：

<img width="262" alt="左0" src="https://user-images.githubusercontent.com/35477358/119076810-cebd4980-ba25-11eb-8a38-c1787f08962f.png">

<img width="265" alt="右0" src="https://user-images.githubusercontent.com/35477358/119076829-d5e45780-ba25-11eb-93a3-906ca058fa9f.png">

我想，如果改成：
方式1：
```
self.mj_w = _scrollView.mj_w;
self.mj_x = 0;
```
效果如下：

<img width="267" alt="左1" src="https://user-images.githubusercontent.com/35477358/119076855-e3014680-ba25-11eb-91c6-431f33d8ca08.png">

<img width="258" alt="右1" src="https://user-images.githubusercontent.com/35477358/119076880-e98fbe00-ba25-11eb-8619-98ada9df8dab.png">

或者方式2：
```
self.mj_w = _scrollView.mj_w +_scrollView.mj_insetL + _scrollView.mj_insetR;
self.mj_x = -_scrollView.mj_insetL;
```
效果如下：

<img width="259" alt="左2" src="https://user-images.githubusercontent.com/35477358/119076913-f7ddda00-ba25-11eb-8070-7a8019efa691.png">

<img width="259" alt="右2" src="https://user-images.githubusercontent.com/35477358/119076922-fe6c5180-ba25-11eb-801f-ff94d703940a.png">

方式1是不是会更好，我不知道这是不是bug，也许是我没弄明白代码误解了，说的不对的请批评指教。

**Comment by wolfcon** [comment]
这种情况自定义一下 Header.
因为根据需求不同, 实现也略有不同的.

自定义的话, 你需求什么就自己写一下.
```swift
override func placeSubviews() {
    super.placeSubviews()
    // 在这里自定义
    ...
} 
```
