### ISSUE TITLE
tableView设置MJRefreshAutoNormalFooter后，设置.Idle的在无网络的时候（加载失败）显示“加载失败”，操作步骤：1、首先加载第一页数据，2、关闭网络后上拉刷新出现“加载失败”，3、重新开启WiFi，4、点击footer无法刷新

### ISSUE THREAD

**Issue by Burgessly** [CoderMJLee/MJRefresh#1525]
在点击footer无法刷新的原因：
MJRefreshAutoFooter中的self.triggerByDrag = Yes
所以在beginRefreshing方法中由于self.triggerByDrag为YES，所以直接return掉

导致上面self.triggerByDrag = Yes的原因是有在点击之前有过滑动（无网络状态），触发过scrollViewPanStateDidChange:方法，在这个方法中执行了self.triggerByDrag = Yes; [self beginRefreshing]，之后没有把self.triggerByDrag置为NO，所以下次的点击就没用

iOS：14.4
Xcode： 12.4

哪位大佬帮忙看看这怎么解决？

**Comment by wolfcon** [comment]
上传个 Demo? 

这里简单回复下, 你看可以解决不, 如果不能请传 demo
你是不是在加载数据请求失败那里没有加 `endRefreshing` 方法?

**Comment by Burgessly** [comment]
具体问题场景：在无网络状态直接endRefresh，end之后tableView的contentOffset还一直在变动，调用到回调方法，所以triggerByDrag为YES，点击的时候没有把triggerByDrag置为NO，所以点击无效。
本质：endRefresh的时机在contentOffset还没有结束改变就已经设置过了（如果endRefresh的时机放在列表滚动之后就可以了）
解决方案：是否可以在点击的时候把triggerByDrag置为NO

**Comment by Burgessly** [comment]
具体问题场景：在无网络状态直接endRefresh，end之后tableView的contentOffset还一直在变动，调用到回调方法，所以triggerByDrag为YES，点击的时候没有把triggerByDrag置为NO，所以点击无效。
本质：endRefresh的时机在contentOffset还没有结束改变就已经设置过了（如果endRefresh的时机放在列表滚动之后就可以了）
解决方案：是否可以在点击的时候把triggerByDrag置为NO

**Comment by wolfcon** [comment]
Demo? 辅以视频说明?

**Comment by Burgessly** [comment]
[test_MJRefresh.zip](https://github.com/CoderMJLee/MJRefresh/files/6798156/test_MJRefresh.zip)
直接运行看log就行，复现步骤，直接上拉刷新，然后点击footer就可以了

**Comment by wolfcon** [comment]
@Burgessly 试试这个 PR.
