### ISSUE TITLE
tableView 刷新太快会导致视图布局不正常

### ISSUE THREAD

**Issue by feixue299** [CoderMJLee/MJRefresh#1528]
测试环境iOS14.5
MJRefresh (3.5.0)
在UIViewController中的viewDidLoad，连续写下两行
tableView.mj_header?.beginRefreshing()
tableView.mj_header?.endRefreshing()
会导致视图布局不正常。
![Simulator Screen Shot - iPhone 12 Pro - 2021-07-08 at 18 25 30](https://user-images.githubusercontent.com/12168109/124906791-09049980-e01a-11eb-9bb4-302a5fe29e07.png)

**Comment by wolfcon** [comment]
Duplicate of #1292
