### ISSUE TITLE
[!] [Xcodeproj] Generated duplicate UUIDs

### ISSUE THREAD

**Issue by wimbledon** [CoderMJLee/MJRefresh#1531]
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

After `pod update` from version 3.6.1 to 3.7.1, there are duplicate UUIDs.
![image](https://user-images.githubusercontent.com/3291853/125451526-eef61710-df06-40ad-b74e-e354053effca.png)

🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

**Comment by wolfcon** [comment]
Demo?

**Comment by AlvinBoy** [comment]
什么情况， 改完不测试吗

**Comment by wimbledon** [comment]
Here is the Xcode project that demonstrates the issue. 
[Sample.zip](https://github.com/CoderMJLee/MJRefresh/files/6812947/Sample.zip)

To reproduce, just run `pod install`.

**Comment by wolfcon** [comment]
这个 Warning 不影响功能, 仅仅会导致警告.

**Comment by wimbledon** [comment]
谢谢🙏 @wolfcon
