### ISSUE TITLE
我这边在不停刷新mj_header的时候，UITableView的contentOffset.y不能正常还原到0，UITableView头部有一大片的空白

### ISSUE THREAD

**Issue by luopan1990911** [CoderMJLee/MJRefresh#1537]
🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶

😁为了能够更好地复现问题和修复问题, 请提供 Demo 和详细的 bug 重现步骤😭

🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶🥶
> 记得删除以上内容

**描述bug**
我这边在不停刷新mj_header的时候，UITableView的contentOffset.y不能正常还原到0，UITableView头部有一大片的空白

**必现/偶发?**
必现

**怎么样重现这个bug**
1. 进入APP页面之后，点击右上角消息，进入我的消息，不停的点击《其他》按钮会出现这种问题

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**
![Uploading 1.jpg…]()
![Uploading 2.jpg…]()
![Uploading 671628143589_.pic_hd.jpg…]()

**运行环境**
 - iPhone6s
 - iOS10.3.1
 - Xcode11.6

**额外的**
[Uploading Travel.zip…]()

**Comment by luopan1990911** [comment]
![671628143589_ pic_hd](https://user-images.githubusercontent.com/16304166/128302124-8023a071-f992-4eae-a493-07e354e104f9.jpg)

**Comment by wolfcon** [comment]
你的 Demo 没传完.

**Comment by zhangzhen132738** [comment]
我也遇到这个问题了，我用3.5.0 tag
随便一个tableview，加上一个tableView，连续调用下面3行代码，就能必现

[self.tableView.mj_header endRefreshing];
 [self.tableView.mj_header beginRefreshing];
 [self.tableView.mj_header endRefreshing];

**Comment by zhangzhen132738** [comment]
Uploading 屏幕录制2021-08-09 下午5.20.50.mov…

**Comment by zhangzhen132738** [comment]
这是我用别人的demo修改后，找出的必现方法
https://user-images.githubusercon

https://user-images.githubusercontent.com/38234587/128685115-e311a5cb-92bc-4dcc-814f-4f3c0f0de9dd.mov
[MJRefresh-3.4.1 2.zip](https://github.com/CoderMJLee/MJRefresh/files/6953275/MJRefresh-3.4.1.2.zip)

tent.com/38234587/128685038-d4b2e6b4-33e1-4892-ba7f-f99228a8f371.mov

**Comment by zhangzhen132738** [comment]
我去掉MJRefreshDispatchAsyncOnMainQueue的主线程判断后，能修复上述问题
![image](https://user-images.githubusercontent.com/38234587/128697002-88ab45d9-84ff-4d7c-8443-9223d1a6587c.png)

**Comment by kedu** [comment]
什么时候可以修复?
