### ISSUE TITLE
子类重写 setPullingPercent:方法  pullingPercent 参数在自动回弹的时候直接从1点多置为0了  

### ISSUE THREAD

**Issue by dingyongg** [CoderMJLee/MJRefresh#1539]
**描述bug**
项目中用的下拉刷新的图是gif图，而且下拉的过程中有个从小到大的动画， 所以在我继承了gifheader类， 子类重写了setPullingPercent 这个方法，下拉的过程中，传入的值pullingPercent 是没问题， 是从0开始慢慢递增的，子类可以根据这个值逐渐的放大gif图， 但是当调用完endRreshing之后， pullingPercent直接边为0了， 这就导致了gif图突然消失的情况，感觉是一下就闪没了，体验不好
但是如果下拉到刷新位置不放手， 再手动推回去， 就可以实现gif图从小到大， 再从大到小的切换。

**必现/偶发?**
必现

**你期望的结果是什么？**
调用完 endRreshing之后 pullingPercent可以从1逐渐递减到0

看了源码发现刷新完回弹是改变contentinset  再用uiview的动画实现的。 没有用Contentoffset, 所以滑动时没有偏移量的回调。
建议优化

**Comment by wolfcon** [comment]
做判断啊. 兄弟. 😥
下拉刷新开始后就不要再随 percent 变了. 变化仅控制在下拉的时候即可啊.
