### ISSUE TITLE
scrollView 设置 contentInset 的left和right，但是 MJRefreshComponent 的没有及时更新位置

### ISSUE THREAD

**Issue by zisulu** [CoderMJLee/MJRefresh#1541]
**描述bug**
对 tableView 或者 collectionView 设置 contentInset 的left和right，但是 MJRefreshComponent 的宽度没有进行相应的计算

**必现/偶发?**
必现

**怎么样重现这个bug**
在刷新之前修改 contentInset
MJTableViewController 
`/// 设置 contentInset 导致 header 宽度不对
    self.tableView.contentInset = UIEdgeInsetsMake(15, 20, 15, 20);
    self.tableView.mj_header.backgroundColor = [UIColor redColor];`
MJCollectionViewController
`/// 设置 contentInset 导致 header 宽度不对
self.collectionView.contentInset = UIEdgeInsetsMake(15, 20, 15, 20);
self.collectionView.mj_header.backgroundColor = [UIColor redColor];`
然后执行下拉刷新即可看到

**你期望的结果是什么？**
能根据contentInset及时更新位置

**截图**
如果有必要的话，请上传几张截图
![QQ20210825-100359](https://user-images.githubusercontent.com/15645270/130714968-f71ca4f7-21a8-4d34-95c2-1c7ef7fa338b.png)

**运行环境**
 - iPhone 12 Pro Max 模拟器  真机 iPhone 12 也能复现
 - iOS 14.4
 - Xcode 12.4

**额外的**
最好能提供出现bug的Demo
[MJRefresh-demo.zip](https://github.com/CoderMJLee/MJRefresh/files/7043158/MJRefresh-demo.zip)

**Comment by zisulu** [comment]
我看之前的 issue 里面提到建议自定义 https://github.com/CoderMJLee/MJRefresh/issues/1520
这个我知道。但我觉得对于默认代码来说，给人的感觉就是 bug

**Comment by wolfcon** [comment]
Duplicate of #1511
