### ISSUE TITLE
添加了tableViewHeader崩溃

### ISSUE THREAD

**Issue by vistaLin** [CoderMJLee/MJRefresh#1542]
![截屏2021-09-08 上午10 08 27](https://user-images.githubusercontent.com/16410016/132434750-73085fe4-1855-4426-8a4a-450a78a5e5de.png)
崩溃在：    // 首先在 MJRefresh 内置语言文件中寻找
    value = [mj_systemI18nBundle localizedStringForKey:key value:value table:nil];

必现：
如果设置了tableViewHeader就崩溃，不设置就不崩溃，写在tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView?也不会崩溃。
环境:
语言：swift
手机：基本测试几个手机都会复现。
xcode：12.5.1
mjrefresh:3.7.2

**Comment by wolfcon** [comment]
能写个崩溃的 Demo 么? 我这边无法复线

**Comment by vistaLin** [comment]
不好提demo，在项目里面，我在尝试哈子吧！可能我使用的不对，我写了一个继承了MJRefreshNormalHeader，写了一个header，然后封装在pageListViewModel里面。
