### ISSUE TITLE
特定情况下使用MJRefreshAutoFooter会触发两次回调

### ISSUE THREAD

**Issue by ldy694** [CoderMJLee/MJRefresh#1543]
**描述bug**
1、UITableView 使用 MJRefreshAutoFooter 做为上拉
2、只有一页数据时，大幅度的往上拉列表并松手
3、在第二页数据网络请求结束后，立马调用刷新列表和结束刷新事件
table.reloadData()
table.mj_footer?.endRefreshing()  
4、下拉回调会再次触发

**必现/偶发?**
必现

**怎么样重现这个bug**
列表reloadData和endRefreshing同时执行就会出现这个问题，如果改由reloadData结束0.4秒后再执行endRefreshing也是正常的

**你期望的结果是什么？**
能够正常调用，不用加延迟处理

**运行环境**
 - iPhoneX
 - iOS14.7.1
 - Xcode12.5.1

**额外的**

**Comment by wolfcon** [comment]
Duplicate of #1020
