### ISSUE TITLE
采用Method Swizzle之后dealloc会崩溃

### ISSUE THREAD

**Issue by woshiqyb** [CoderMJLee/MJRefresh#155]
采用Method Swizzle之后dealloc会崩溃，使用zombies分析，发现是系统某API在对象retainCount为－1还会调用。不仅MJRefresh有此问题，UITextField+PlaceHolder以及其他一些开源库在采用Method Swizzle改变了dealloc方法之后，也出现了类似崩溃的问题。本人水平有限，先是直接在源码基础上还原了dealloc方法，崩溃情况少一点，地方也不一样。也注释过 [self deallocSwizzle]，也没有出现崩溃情况。由于崩溃的是我并没有用到MJRefresh的地方，最终我尝试在- (void)deallocSwizzle方法内加了if (self.footer || self.header) 这样一个判断，后来就不崩溃了。但我想知道之前是因为我使用不当才导致的崩溃么，为什么会导致崩溃？

**Comment by Thinker2014** [comment]
我遇到了和楼主同样的问题，注释了之后，内存却无法正常释放，因为我是在push地图的时候崩溃的，可是我在地图里没有引用mj的任何文件，mj我只是在需要刷新的地方引用了，也没放在全局里，求解
![rbu v i_uom 2wgsy44j4g](https://cloud.githubusercontent.com/assets/10498756/7625004/3d7039dc-fa24-11e4-86ba-ea4778f991ce.jpg)

**Comment by shaozl** [comment]
是的。这里是不是一个死循环？

**Comment by woshiqyb** [comment]
这里不是死循环，[self deallocSwizzle]实际会调用dealloc方法，MJ在load方法中交换了两个方法

**Comment by woshiqyb** [comment]
二楼把deallocSwizzle方法改一下，崩溃情况或许有所改善。
![3fe583c8-00c0-4e92-a4b2-27d2a23b17d7](https://cloud.githubusercontent.com/assets/7382583/7645411/6414d6ba-fae7-11e4-8db6-ddae0fe53ebc.png)

**Comment by Thinker2014** [comment]
楼上说的对，但并不是所有的页面都会有footer和header。也就是说，其他的视图无法调用dealloc函数，也就无法释放内存了，我最近在用高德地图，多调几次之后，内存就吃不消了

**Comment by CoderMJLee** [comment]
2.0版本已经彻底解决这个问题哈
