### ISSUE TITLE
在placeSubviews加了一种状态，修改gifView的位置动画效果不执行了

### ISSUE THREAD

**Issue by npzlxph0415** [CoderMJLee/MJRefresh#1550]
- (void)placeSubviews
{
    [super placeSubviews];
    
    if (self.gifView.constraints.count) return;
    
    self.gifView.frame = self.bounds;
    if (self.stateLabel.hidden && self.lastUpdatedTimeLabel.hidden) {
        self.gifView.contentMode = UIViewContentModeCenter;
    } else if ([_type isEqualToString:@"1"]) {
        self.gifView.contentMode = UIViewContentModeCenter;
        CGFloat stateY = self.stateLabel.mj_y;
        CGFloat timeY = 0.0;
        if (!self.lastUpdatedTimeLabel.hidden) {
            timeY = self.lastUpdatedTimeLabel.mj_y;
        }
        CGFloat textY = MIN(stateY, timeY);
        NSLog(@"scscsc%f-----%f------%f",stateY,timeY,self.stateLabel.mj_size.height);
        [self.stateLabel setMj_y:15];
        self.gifView.mj_y = (textY - self.gifView.mj_size.height) / 3;//间距太大手动除2
    } else {
        self.gifView.contentMode = UIViewContentModeRight;
        
        CGFloat stateWidth = self.stateLabel.mj_textWidth;
        CGFloat timeWidth = 0.0;
        if (!self.lastUpdatedTimeLabel.hidden) {
            timeWidth = self.lastUpdatedTimeLabel.mj_textWidth;
        }
        CGFloat textWidth = MAX(stateWidth, timeWidth);
        self.gifView.mj_w = self.mj_w * 0.5 - textWidth * 0.5 - self.labelLeftInset;
    }
}

**Comment by wolfcon** [comment]
你还是写个 Demo 吧.
