### ISSUE TITLE
iOS 15.1 中出现使用mj_header会导致导航栏变透明的问题

### ISSUE THREAD

**Issue by tpian928** [CoderMJLee/MJRefresh#1551]
**描述bug**
iOS 15.1 Xcode 13.1 中
```
self.tableView.mj_header = MJRefreshNormalHeader(refreshingTarget: self, refreshingAction: #selector(tableViewViewfreshed))
```
导航栏会变透明，删除之后就正常了

**必现/偶发?**
正常

**怎么样重现这个bug**
使用上述配置，bug必现

**你期望的结果是什么？**
像之前一样，添加了mj_header后导航条是不透明的

**截图**
![IMG_3957](https://user-images.githubusercontent.com/8392842/140448089-db40121f-b835-4688-adfd-7d69f2f9ba91.jpg)

**运行环境**
 - iPhone 11
 - iOS 15.1
 - Xcode13.1

**Comment by wolfcon** [comment]
建议你看下[这篇文章 https://www.6hu.cc/archives/18801.html](https://www.6hu.cc/archives/18801.html), 应该可以解决你的问题
