### ISSUE TITLE
iOS  15下使用MJRefreshAutoFooter/MJRefreshBackFooter，结束刷新时可能会有一些不符合预期的动画效果

### ISSUE THREAD

**Issue by jiasongs** [CoderMJLee/MJRefresh#1552]
**描述bug**
iOS  15下使用MJRefreshAutoFooter/MJRefreshBackFooter，结束刷新时可能会有一些不符合预期的动画效果。
实测在iOS 15以下不会出现此问题。

**必现/偶发?**
必现

**怎么样重现这个bug**
1、UITableView/UICollectionView使用`performBatchUpdates:completion:`，在completion回调里调用 `[weakSelf.collectionView.mj_footer endRefreshing]`

**你期望的结果是什么？**
不会出现额外的动画效果

**视频**
观察视频中页面底部的mj_footer，会有明显的下滑动画。
https://user-images.githubusercontent.com/22904757/141225139-e73e1cd4-67b9-48cf-b702-4f09c78cdaab.mov

**DEMO**
全局搜索：`issues/1552`，来查看改动的地方，Demo中也已经提供了解决方案
[MJRefreshIssue.zip](https://github.com/CoderMJLee/MJRefresh/files/7517177/MJRefreshIssue.zip)

**运行环境**
 - iPhone 13 Pro 模拟器
 - iOS 15.0
 - Xcode 13.1

**Comment by wolfcon** [comment]
? 解决方案是?

**Comment by jiasongs** [comment]
> ? 解决方案是?

[MJRefreshIssue.zip](https://github.com/CoderMJLee/MJRefresh/files/7517191/MJRefreshIssue.zip)
不好意思，刚才demo上传错误了TAT，我又上传了一个新的Demo，全局搜索`issues/1552`，可以看到。

**Comment by wolfcon** [comment]
你的解决方案无效啊/
你只需要这样做即可.
```objc
[UIView animateWithDuration:0 animations:^{
    [weakSelf.collectionView performBatchUpdates:^{
        [weakSelf.collectionView reloadSections:[NSIndexSet indexSetWithIndex:0]];
    } completion:^(BOOL finished) {
        // 结束刷新
        [weakSelf.collectionView.mj_footer endRefreshing];
    }];
}];
```

**Comment by wolfcon** [comment]
`reloadData` 是没有这个问题. `performBatchUpdates` 会带部分动画. 直接取消即可

**Comment by jiasongs** [comment]
> 你的解决方案无效啊/ 你只需要这样做即可.
> 
> ```objc
> [UIView animateWithDuration:0 animations:^{
>     [weakSelf.collectionView performBatchUpdates:^{
>         [weakSelf.collectionView reloadSections:[NSIndexSet indexSetWithIndex:0]];
>     } completion:^(BOOL finished) {
>         // 结束刷新
>         [weakSelf.collectionView.mj_footer endRefreshing];
>     }];
> }];
> ```
<img width="747" alt="图片" src="https://user-images.githubusercontent.com/22904757/141230881-e3deb8db-8045-439f-b991-17a1b57b9be1.png">
我试了下我的解决方案是有效的，你可以打开模拟器的Slow Animations会更明显，mj_footer没有下滑的动画效果了。
另外业务之所以用performBatchUpdates，一个是为了批量提交更新，另一个就是为了更新时的动画。如果按照上述方法，就会失去UICollectionView的更新动画效果。
此问题可以通过继承去解决，但是我觉得应该属于MJRefresh框架的一个问题。不管业务外部使用reloadData还是performBatchUpdates，在各个iOS版本应该保持相同预期，但目前iOS 15下会有此问题。

**Comment by wolfcon** [comment]
我这边打开你的注释...仍然会闪动啊@@

**Comment by jiasongs** [comment]
> 我这边打开你的注释...仍然会闪动啊@@

不是闪动的动画效果，是下滑。。。

观察视频中页面「底部的mj_footer」，会有明显的「下滑动画」。
https://user-images.githubusercontent.com/22904757/141225139-e73e1cd4-67b9-48cf-b702-4f09c78cdaab.mov

**Comment by wolfcon** [comment]
恩, 看到了.
主要有以下几个变化:
- < iOS 15, 是停滞在原位, 然后消失的. 多少也是有点问题的.
- iOS 15 的确把停滞在原位的效果变成了下移.

你的代码的确解决了下移, 但仅限于 iOS 15. 非 iOS 15 的停滞问题还是得解决. 建议在解决之前先关闭动画.(况且 BackFooter 在 iOS 15 之前还存在以下的问题)

### 题外话
iOS 15 也将此前的 Header 和 BackFooter 的 Cell 提前出现平移问题 Bug 也给整没了. 看来 Apple 还是对 FlowLayout 代码有做过修改.

**Comment by jiasongs** [comment]
> 恩, 看到了. 主要有以下几个变化:
> 
>     * < iOS 15, 是停滞在原位, 然后消失的. 多少也是有点问题的.
> 
>     * iOS 15 的确把停滞在原位的效果变成了下移.
> 
> 
> 你的代码的确解决了下移, 但仅限于 iOS 15. 非 iOS 15 的停滞问题还是得解决. 建议在解决之前先关闭动画.(况且 BackFooter 在 iOS 15 之前还存在以下的问题)
> ### 题外话
> 
> iOS 15 也将此前的 Header 和 BackFooter 的 Cell 提前出现平移问题 Bug 也给整没了. 看来 Apple 还是对 FlowLayout 代码有做过修改.
> 
> > #1523 #1506 #1483 #818 #1502 #1489 #1472 #225

< iOS 15 停滞原位的问题我特别研究过，我们业务主要是UICollectionView，使用`performBatchUpdates:completion:`时，flowLayout的`UICollectionViewLayoutAttributes`有个渐变的动画效果，当渐变效果完成时UICollectionView的contentSize才会真正被赋值，这样的话就只有等待动画结束后才会回调`scrollViewContentSizeDidChange`来设置`self.mj_y`。所以就出现了上述停滞的效果，解决此问题有两个方案：
1、去掉flowLayout的动画效果，可以重写flowLayout的`initialLayoutAttributesForAppearingItem`设置alpha，项目目前就是采用的这个方法，这样就看不出停滞原位了，但实际上还是停滞的，只不过是个障眼法。
2、hook flowLayout的`finalizeCollectionViewUpdates`，`finalizeAnimatedBoundsChange`方法，在此方法里设置`self.mj_y`，这个方案我们正在灰度测试，看看实际效果，可行的话会在此issue提供下解决方案

**Comment by wolfcon** [comment]
其实这一类问题都与相关 View 的动画冲突或者动画渲染时机有关. #818 中的 TableView 的 `performBatchUpdates` 也同样存在类似的问题.

**Comment by jiasongs** [comment]
> 其实这一类问题都与相关 View 的动画冲突或者动画渲染时机有关. #818 中的 TableView 的 `performBatchUpdates` 也同样存在类似的问题.
> 
> > 再往深层想一下, 其实 Footer 加载这个问题或许不应该存在. 优秀的设计思路应是在用户无察觉情况下, prefetch 数据, 动态加载出来, 但是这可能也真的因人而异, 毕竟存在即合理...🙄

是这样的，理论上不应该显示出footer，而是当浏览的过程中就已经预加载底部的数据，但是也跟需求有关系，类似抖音那种的必须得做到无感知，但是一个普通的列表也许没必要这么复杂。

**Comment by jiasongs** [comment]
> 其实这一类问题都与相关 View 的动画冲突或者动画渲染时机有关. #818 中的 TableView 的 `performBatchUpdates` 也同样存在类似的问题.
> 
> > 再往深层想一下, 其实 Footer 加载这个问题或许不应该存在. 优秀的设计思路应是在用户无察觉情况下, prefetch 数据, 动态加载出来, 但是这可能也真的因人而异, 毕竟存在即合理...🙄
UICollectionViewLayout:
<img width="1456" alt="图片" src="https://user-images.githubusercontent.com/22904757/141265950-79451984-a0a3-4b70-a834-81c1f274aded.png">
scrollViewContentSizeDidChange:
<img width="813" alt="图片" src="https://user-images.githubusercontent.com/22904757/141266290-907cedeb-2410-411a-8bb4-950f2316c5f5.png">
这是方案2，解决此issue的核心代码，目的就是让MJRefreshFooter提前拿到contentSize进行布局。
