### ISSUE TITLE
中文太多

### ISSUE THREAD

**Issue by zhoumopashan** [CoderMJLee/MJRefresh#156]
提个建议，就是项目里面的中文太多，不利于做成国际化的控件

**Comment by CoderMJLee** [comment]
谢谢提醒，2.0版本会消除这些问题的哈

**Comment by ss1271** [comment]
@CoderMJLee MJ哥，如果需要帮助，我可以协助翻译文档以及注释。现在我的同事用这个好痛苦的，哈哈

**Comment by CoderMJLee** [comment]
@ss1271  等2.0发布，望帮忙翻译，谢谢
