### ISSUE TITLE
在swift语言下引用MJRfresh出现打包错误

### ISSUE THREAD

**Issue by zhosy022** [CoderMJLee/MJRefresh#1561]
**描述bug**
当用swift语言下引用MJRfresh出现打包错误
**必现/偶发?**
必现

**怎么样重现这个bug**
编写一个bridge.h 并添加以下内容引用

#ifndef bridge_h
#define bridge_h

#import "MJRefresh.h"

#endif /* bridge_h */

运行正常但是archive报错

**你期望的结果是什么？**
你本来期望得到的正确结果是怎样的？就是解决bug之后的结果

**截图**

**运行环境**
 - iPhone11
 - iOS15.1
 - Xcode13.1

**额外的**

**Comment by wolfcon** [comment]
直接拖代码进去的吗? 还是使用包管理器了?

**Comment by zhosy022** [comment]
直接拖的然后写bridge

**Comment by wolfcon** [comment]
你写个 Demo?
