### ISSUE TITLE
Swift 项目中使用上拉加载的状态问题

### ISSUE THREAD

**Issue by Kejiasir** [CoderMJLee/MJRefresh#1565]
**描述bug**
在 Swift 项目中使用 `MJRefreshAutoNormalFooter`，`state` 设置为 `.noMoreData` 后，表现的状态依然是 `.idle`（`点击或上拉加载更多`），并且可以继续上拉动作，同样的代码逻辑在 OC 项目中没有问题

**必现/偶发?**
必现（但是偶尔表现正常）

**代码截图**
![QQ20220216-211457](https://user-images.githubusercontent.com/14361443/154272239-0e759709-e598-4924-ab68-c4d2d7742509.png)

**录屏展示**
https://user-images.githubusercontent.com/14361443/154275208-2f6008da-494f-4771-98a7-37cb9627ace9.MOV

**Comment by gitph101** [comment]
您好，邮件已收到。

**Comment by 309598016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wolfcon** [comment]
使用

```swift
tableView.mj_footer?.endRefreshingWithNoMoreData()
```
