### ISSUE TITLE
非全屏的Present出来的VC做下拉刷新，手势冲突了

### ISSUE THREAD

**Issue by wenjinfu321** [CoderMJLee/MJRefresh#1566]
Present出一个非全屏的VC，系统自带下拉关闭手势，这时候添加下拉刷新，手势冲突了，有什么办法可解吗？

**Comment by wolfcon** [comment]
这种弹出式的页面, 是临时一次性的, 不适合刷新(与系统定义的交互方式冲突). 
建议不要设计类似的功能, 改为自动刷新或者全屏弹出, 如果强行将系统手势屏蔽后会影响交互.
