### ISSUE TITLE
刷新控件都是居中。可以居左、居右或者调整刷新控件的frame吗？

### ISSUE THREAD

**Issue by MathewChen** [CoderMJLee/MJRefresh#1579]
找了一下，没有找到相关的操作，请问一下，我可以这样操作吗？

**Comment by 309598016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wolfcon** [comment]
自定义或者修改默认的 view 位置皆可
