### ISSUE TITLE
与iCarousel合用的时候,会出现错位的问题.

### ISSUE THREAD

**Issue by seanLee** [CoderMJLee/MJRefresh#159]
我不确实是不是与iCarousel合用才会产生的问题.我用四个不同的TableView,但是每次下拉刷新完之后,我切换TableView,然后在返回之前刷新完的TableView,就会出现向下的偏移.

**Comment by seanLee** [comment]
解决错误了,是因为多次加载上拉刷新造成的错位.现在我想问下,能不能添加一个属性判断tableview或者collectionview是否已经加载过上下拉刷新的事件?或者更智能一点,添加的时候就去判断?

**Comment by seanLee** [comment]
解决问题了,是因为多次加载上拉刷新造成的错位.现在我想问下,能不能添加一个属性判断tableview或者collectionview是否已经加载过上下拉刷新的事件?或者更智能一点,添加的时候就去判断,如果已经添加就不用再次添加?

**Comment by CoderMJLee** [comment]
试试2.0版本

**Comment by seanLee** [comment]
@CoderMJLee 好的
