### ISSUE TITLE
与ODRefreshControl共存一个项目的时候出错

### ISSUE THREAD

**Issue by nanmingzhidian** [CoderMJLee/MJRefresh#160]
因为多人合作，大家用的刷新工具不一样，当我把MJRefresh加进项目是会一直出现这个错误，但是移除MJRefresh就没事了，求解决。

报错：
2015-04-03 18:16:10.077 YFFamilyMall[9283:256070] NSScanner: nil string argument

2015-04-03 18:16:10.077 YFFamilyMall[9283:256070] NSScanner: nil string argument

libc++abi.dylib: terminate_handler unexpectedly threw an exception

异常：
exception:
An instance 0x7fbdd4170800 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7fbdd2685840> (
<NSKeyValueObservance 0x7fbdd26b0e60: Observer: 0x0, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7fbdd48cddb0>
<NSKeyValueObservance 0x7fbdd2688ba0: Observer: 0x0, Key path: contentSize, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7fbdd48d3f80>
)

**Comment by CoderMJLee** [comment]
你用的是哪个版本？

**Comment by nanmingzhidian** [comment]
上个星期下载的

**Comment by githhhh** [comment]
我也遇到了....

**Comment by CoderMJLee** [comment]
2.0版本已经彻底解决此问题了哈
