### ISSUE TITLE
PrivacyInfo.xcprivacy会重复

### ISSUE THREAD

**Issue by CloudlessMoon** [CoderMJLee/MJRefresh#1604]
<img width="691" alt="图片" src="https://github.com/CoderMJLee/MJRefresh/assets/22904757/9dd20a22-efb8-4b5e-bbec-4e9a268f82e8">

如上图所示，podspec中使用`s.resources = MJRefresh/PrivacyInfo.xcprivacy`，会与其他这样写法的库或者主工程里的`PrivacyInfo.xcprivacy`冲突，最好改为`s.resource_bundles = {
      'MJRefresh_Privacy' => ['MJRefresh/PrivacyInfo.xcprivacy']
  }`

<img width="236" alt="图片" src="https://github.com/CoderMJLee/MJRefresh/assets/22904757/885cff68-a3c7-4167-af76-060bc386dba7">

App解包之后，实际上`PrivacyInfo.xcprivacy`会暴露在根目录，所以会产生重复的问题。resource_bundles里有key值可以规避，如上面`MJRefresh_Privacy`，解包后会变成`MJRefresh_Privacy.bundle`。

**Comment by A-Dirt** [comment]
@CoderMJLee

**Comment by wolfcon** [comment]
Acknowledged

**Comment by jiasongs** [comment]
> Acknowledged

any release plans?  it's already causing duplication with `SVProgressHUD`, please see: https://github.com/SVProgressHUD/SVProgressHUD/issues/1120#issuecomment-2005863978

**Comment by wolfcon** [comment]
It is only influenced in `Static pod`. `Framework` is fine

**Comment by TheLittleBoy** [comment]
When you're building your app to submit to the App Store, **Xcode 15 can aggregate all the privacy manifests in your app's project, and produce a privacy report that summarizes the declared data uses.** To view this, go to Xcode Organizer, show the context menu for an archive, and select "Generate Privacy Report." The privacy report is a PDF and easy to use. It is organized in a similar way to Privacy Nutrition Labels. So you can easily reference this report when you provide your app's privacy details in App Store Connect. This helps you review, understand, and describe the privacy practices of your app and its dependencies.

[https://developer.apple.com/videos/play/wwdc2023/10060/](url)

**Comment by TheLittleBoy** [comment]
我下载并解压了腾讯IM的SDK，发现PrivacyInfo.xcprivacy文件就包含在framework、xcframework的根目录下，并没有用bundle啊
<img width="583" alt="image" src="https://github.com/CoderMJLee/MJRefresh/assets/3365421/9aab593a-ac45-493a-a758-209168bc98cb">

腾讯IM隐私策略文档：[https://cloud.tencent.com/document/product/269/104138](url)

腾讯IM的SDK下载地址：[https://github.com/CocoaPods/Specs/blob/master/Specs/2/2/b/TXIMSDK_Plus_iOS_XCFramework/7.8.5505/TXIMSDK_Plus_iOS_XCFramework.podspec.json](url)

**Comment by wolfcon** [comment]
@TheLittleBoy 3.7.7的方式打包出来动态库是没问题的. 这个 Issue 主要针对 CocoaPods 用静态库引入时才会存在这个问题.
