### ISSUE TITLE
隐私清单PrivacyManifest中未添加UserDefault的API信息，我看该库中调用了

### ISSUE THREAD

**Issue by FanningHau** [CoderMJLee/MJRefresh#1608]
![image](https://github.com/CoderMJLee/MJRefresh/assets/106377136/b04e5e4e-2a56-40e0-8f48-46dabb0bcc50)

**Comment by FanningHau** [comment]
![image](https://github.com/CoderMJLee/MJRefresh/assets/106377136/3ba4385c-1824-48e8-9f6f-29245525af4f)
请确认一下

**Comment by wolfcon** [comment]
Resolved. Thx.
