### ISSUE TITLE
MJ哥,我用cocoapods管理的MJrefresh构建版本的时候不能用了

### ISSUE THREAD

**Issue by winterzou** [CoderMJLee/MJRefresh#161]
事实上xcode6.1构建版本都没有问题,升级到6.3后构建版本就会报linker command failed with exit code 1 (use -v to see invocation)(真机测试部分机型会有这个问题),具体错误代码是

file is universal (2 slices) but does not contain a(n) armv7s slice: /Users/apple/Library/Developer/Xcode/DerivedData/DuCarClient-ftmhkxhdylrbudbczrznfgratpcs/Build/Intermediates/ArchiveIntermediates/DuCarClient/BuildProductsPath/Release-iphoneos/libPods-MJExtension.a file '/Users/apple/Library/Developer/Xcode/DerivedData/DuCarClient-ftmhkxhdylrbudbczrznfgratpcs/Build/Intermediates/ArchiveIntermediates/DuCarClient/BuildProductsPath/Release-iphoneos/libPods-MJExtension.a' for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CoderMJLee** [comment]
看报错信息，应该是MJExtension吧？

**Comment by winterzou** [comment]
不好意思,发错代码了,MJRefresh也是差不多这个问题,我新建了工程用cocoapods导入后测试,也是这样的问题

**Comment by CoderMJLee** [comment]
Build Active Architecture Only的值设置为Yes试试，这个是对armv7s支持的问题

**Comment by winterzou** [comment]
release和debug 都设置了yes,但是还是这个错误,
这是新建的工程,用cocoapods导入的,我知道你的库肯定没问题,但是你能不能帮我看看这是哪个姿势不对啊

**Comment by Daniate** [comment]
错误信息表明，静态库缺少对armv7s架构的支持，可以在编译静态库的时候，加上armv7s试试
![snip20150521_4](https://cloud.githubusercontent.com/assets/1210634/7741784/216ec300-ffb7-11e4-8ad7-cc0b26affcef.png)
