### ISSUE TITLE
ios18 beta4版本下拉刷新时候崩溃 或者 卡住不动阻塞主线程

### ISSUE THREAD

**Issue by climlove** [CoderMJLee/MJRefresh#1612]
等了许久后 可能会卡在
- (void)scrollViewContentOffsetDidChange:(NSDictionary *)change 这个函数这里，目前测试了iOS16 17 14 都没有问题，唯独在iOS18上面出现了这个问题。
**运行环境**
 - iPhone14 Pro max
 - iOS18 beta4 版本
 - Xcode15

**Comment by climlove** [comment]
![50226234550ac4bc97c2e206477f13d0](https://github.com/user-attachments/assets/cf35c7be-f51c-4f8a-acda-b27e98533b9a)
等了许久 就会出现这个

**Comment by climlove** [comment]
![6f9bf399bb39e7bc506b7d64b31d3b11](https://github.com/user-attachments/assets/88265613-cf90-45f0-9482-5e371077df97)
HKWAnimationHeader 只是这样的东西

**Comment by Nuyaij-c** [comment]
你好，我也遇到了这个问题，在 iOS18，xcode16 的版本上，请问你是怎样解决的
