### ISSUE TITLE
footer.triggerAutomaticallyRefreshPercent = -30;

### ISSUE THREAD

**Issue by ptlCoder** [CoderMJLee/MJRefresh#1618]
为了能提前上拉加载设置了footer.triggerAutomaticallyRefreshPercent = -30;
但是这样设置后，下拉刷新会先调用Footer的上拉回调，再回调下拉刷新，这样的话在弱网下会看得到两次数据的变化。 如果这样设置后只要下拉必然会先调用上拉的回调。

**Comment by wolfcon** [comment]
这个需要你手动去处理, 因为这个涉及到数据以及业务逻辑, 而且 Footer 其实是跟 Header 解耦开的. 如果说让 SDK 来处理, 则需要动态判断 Header 和 Footer 的状态
