### ISSUE TITLE
MJ哥,下拉加载数据的时候有时候会导致奔溃,提示数据源数组为0,有时候下拉又不会报错

### ISSUE THREAD

**Issue by BenLoomToys** [CoderMJLee/MJRefresh#162]
我的代码:
__weak typeof(self) weakSelf = self;
    [self.dynamicTableView addLegendHeaderWithRefreshingBlock:^{
        [weakSelf requestData:NO];//下拉
    }];
    [self.dynamicTableView.header beginRefreshing];

    
    [self.dynamicTableView addLegendFooterWithRefreshingBlock:^{
        [weakSelf requestData:YES];//上拉
    }];

**Comment by CoderMJLee** [comment]
数据源、数组都是数据相关的东西哈，跟刷新控件无关哦
