### ISSUE TITLE
【优化建议】

### ISSUE THREAD

**Issue by AndyM129** [CoderMJLee/MJRefresh#165]
能不能添加一个下拉刷新状态，就是“刷新成功/失败”，使得刷新流程为：下拉可刷新 -> 松开立即刷新 -> 刷新中 -> 刷新成功 -> 收起刷新。再通过一个可选项，使得可以选择是否刷新成功后提示“刷新成功”后再收起~~~

另外有没有可能再添加一个参数：指定下拉位移超过指定值就立即激活刷新功能呢？

**Comment by shaozl** [comment]
建议不错~~~QQ就是这么干的

**Comment by CoderMJLee** [comment]
好的
