### ISSUE TITLE
Pod 引入后不能使用

### ISSUE THREAD

**Issue by HelloWorldsir** [CoderMJLee/MJRefresh#166]
使用Pod 后
[self.MJTableView addLegendHeaderWithRefreshingBlock:^{
        [weakSelf headerRereshing];
    }];
报错：
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableView addLegendHeaderWithRefreshingBlock:]: unrecognized selector sent to instance 0x15c78800'

**Comment by crazypoo** [comment]
啦啦啦,我也是这个问题,我想换用这个的时候,也是这样的报错,但是新建项目则没问题

**Comment by CoderMJLee** [comment]
是pod install，other linker flag出现了问题，导致分类不能用哈。是pod的问题，其他网友自行解决了
