### ISSUE TITLE
关于激活灵敏度

### ISSUE THREAD

**Issue by lm2343635** [CoderMJLee/MJRefresh#167]
MJ哥，下来和上拉太高了 我怎么把它改低一点呢

**Comment by CoderMJLee** [comment]
直接修改header或者footer的高度
```objc
CGRect frame = self.tableView.footer.frame;
frame.size.height = xxx;
self.tableView.footer.frame = frame;
```

**Comment by lm2343635** [comment]
我刚才表达好像有点问题，我想问的是控件激活的灵敏度如何更改，更改footer的高度好像不能更改下拉激活的灵敏度，我把高度设为600了还是轻轻一向下滑动就激活控件。有没有什么办法能让控件激活变得迟钝一点呢？

**Comment by CoderMJLee** [comment]
下拉的目的就是让用户能够快速刷新数据，降低灵敏度是否有违背这种想法？
