### ISSUE TITLE
Bug 很多啊

### ISSUE THREAD

**Issue by shaozl** [CoderMJLee/MJRefresh#168]
从一个带有下拉刷新的界面push到另一个带有下拉刷新和上啦刷新的界面，再pop回来的时候就会crash 
*** -[UITableViewRowData release]: message sent to deallocated instance 0x178324240 
这个错误点就在deallocSwizzle方法

**Comment by CoderMJLee** [comment]
Sorry哈，创业初期事比较多，会尽快抽时间修复的，网友们提到的问题都将在2.0版本中解决。暂时来说，你可以尝试把deallocSwizzle方法删掉试试哈

**Comment by shaozl** [comment]
恩。注释掉也没用。因为你的原因不是这里。我看下源码，发现了一个问题，你注册的observer 需要remove掉。你都没有这样remove，所以导致了各种崩溃.我修改了下。目前基本OK。不过还有待进一步的各种场合的测试

**Comment by CoderMJLee** [comment]
其实是由remove的哈，在willMoveToSuperview:那个方法里面。有时候可能没进去，没处理好。谢谢提醒。如果可以的话，能否贴出你的解决方案？谢谢

**Comment by CoderMJLee** [comment]
最好来个pull request哈，万分感谢

**Comment by shaozl** [comment]
是的，你willMovetoSuperView方法的作用是只保持一个observer：增加一个观察者之前先remove掉原来的一个，这是对的。但是当你的view或者scrollview 执行dealloc的时候，也应该移除掉它所注册的观察者！

**Comment by CoderMJLee** [comment]
之前是这样的，view在dealloc之前会调用一次willMoveToSuperview:，所以是被移除了，Demo里面就没有问题的。但是不知道为啥，有些朋友的项目里面就不会执行willMoveToSuperview:哈，之前也有朋友遇到这个问题了，不过由于创业忙，也一直没有时间去查找原因哈，实在抱歉。希望你能分享一下你的解决方案，谢谢哈

**Comment by shaozl** [comment]
嗯。我还看怎么用pull request。。。。。等下我看看可不可以提交。
