### ISSUE TITLE
明杰 用CocoaPods 导入 出现这样的错误,请看一下.

### ISSUE THREAD

**Issue by shenguanjiejie** [CoderMJLee/MJRefresh#170]
![2015-05-26 11 31 41](https://cloud.githubusercontent.com/assets/9425605/7804849/94056a80-039b-11e5-9454-f23618105e13.png)
![2015-05-26 11 33 07](https://cloud.githubusercontent.com/assets/9425605/7804851/97dac84e-039b-11e5-9479-0ceb4c11b21a.png)
![2015-05-26 11 38 02](https://cloud.githubusercontent.com/assets/9425605/7804858/b82c64e0-039b-11e5-812d-47e57704ec8c.png)

**Comment by shenguanjiejie** [comment]
好吧 我自己查到原因了在Podfile里需要写上最低支持版本才行.我是这样写的:

platform :ios, '7.0'
pod 'MJRefresh'

然后就不报错了...

 MJ哥你在README里也加进去吧,我感觉其他人也会遇到这种问题.
加油MJ哥~

**Comment by CoderMJLee** [comment]
谢谢
