### ISSUE TITLE
MJRefreshGifHeader建议增加动画时长控制

### ISSUE THREAD

**Issue by baight** [CoderMJLee/MJRefresh#171]
看到的代码是，默认每帧图片用0.1秒，并且是写死的，
建议动画时长增加配置属性。

**Comment by CoderMJLee** [comment]
好的，2.0版本会增加此接口

**Comment by baight** [comment]
另外，建议增加控制动画重复次数的属性或方法。
如比，我想做一个箭头 由下 旋转 到上 的动画，结果就成了箭头不停地由下旋转到上（其实我想要的效果只是转一次就行了，和LegendHeader的箭头一样的效果）
