### ISSUE TITLE
footer 和 header 可定制性不高啊

### ISSUE THREAD

**Issue by githhhh** [CoderMJLee/MJRefresh#172]
如果能不关心内在逻辑，可以完全自定义footer和 header 就好啦。

**Comment by coramo** [comment]
INSPullToRefresh , MJ老师不要打我 = =

**Comment by CoderMJLee** [comment]
哈哈，谢谢提醒，值得学习参考。2.0版本就会包含自定义控件功能了。最近时间紧哈，没法写
