### ISSUE TITLE
上拉刷新刷新一次被调用多次怎么回事？

### ISSUE THREAD

**Issue by z624821876** [CoderMJLee/MJRefresh#176]
向上拉scrollView  还没有松手就开始刷新！！！！

**Comment by 100mango** [comment]
请描述清楚触发事件的地方以及相关代码。想清楚代码的前后文,看看是否有配置不当。

**Comment by z624821876** [comment]
刚检查了一遍，方法没有被多次调用，不过上拉的时候 UIActivityIndicatorView就开始转，不是应该上拉松开的时候才开始转得吗？

**Comment by z624821876** [comment]
。。找到原因了     我每次加载完数据   调用  [_tableView.footer endRefreshing];    然后他就会刷新好多次

**Comment by z624821876** [comment]
#pragma mark 根据contentOffset调整state
- (void)adjustStateWithContentOffset
{
    if (self.mj_y == 0) return;
    
    if (_scrollView.mj_insetT + _scrollView.mj_contentSizeH > _scrollView.mj_h) { // 内容超过一个屏幕
        // 这里的_scrollView.mj_contentSizeH替换掉self.mj_y更为合理
        if (_scrollView.mj_offsetY > _scrollView.mj_contentSizeH - _scrollView.mj_h + self.mj_h * self.appearencePercentTriggerAutoRefresh + _scrollView.mj_insetB - self.mj_h) {
            // 当底部刷新控件完全出现时，才刷新
            [self beginRefreshing];
        }
    }
}

这个方法     刚上拉就开始被调用     导致 回调  block 调用了多次
