### ISSUE TITLE
[bug] 下拉刷新过程中滚动tableview会导致第二个section悬空

### ISSUE THREAD

**Issue by chenweiyj** [CoderMJLee/MJRefresh#18]
我的tableview有两个section，第二个section的header有标题，滚动的时候这个header会一直显示紧贴navigator bar。现在刷新的时候，滚动table，第二个section的header会悬空，跟navigator bar有一段距离，table cell的内容从这个header下面穿过去了。这应该是个bug吧？

**Comment by menervil** [comment]
http://stackoverflow.com/questions/664781/change-default-scrolling-behavior-of-uitableview-section-header 
http://stackoverflow.com/questions/5466097/section-headers-in-uitableview-when-inset-of-tableview-is-changed
这个也许可以帮到你。

**Comment by magiccash** [comment]
这个问题怎么解决的？我按照第二篇文章的解决，还是有问题

**Comment by BooJKit** [comment]
直接在源码里修改，刷新状态下重置tableview的contentInset，刷新结束再修复contentInset。
