### ISSUE TITLE
杰哥，pod导入项目之后无法使用

### ISSUE THREAD

**Issue by kidneyband** [CoderMJLee/MJRefresh#181]
用pod导入，结果在
[self.tableView addLegendHeaderWithRefreshingTarget:self refreshingAction:@selector(refreshDataSource)];时，显示野指针错误

**Comment by kidneyband** [comment]
不对，是因为pod install之后，other_link_flag不一致导致的，没MJ没关系啊，祝小码哥越办越好哈。

**Comment by CoderMJLee** [comment]
谢谢

**Comment by LiXiaoXiang** [comment]
怎么解决的呢
