### ISSUE TITLE
上拉刷新能否做到和下拉刷新的方式一样？

### ISSUE THREAD

**Issue by alex4814** [CoderMJLee/MJRefresh#182]
从 demo 来看，上拉和下拉的方式是不同的。

我想问下，上拉能不能也和下拉一样，有一个“下拉可以刷新”到“松开立即刷新”的过程。
目前的上拉只是上拉到一定程度后刷新，在体验上并没有下拉刷新的好。

另外，下拉在刷新完后自动隐藏，想刷新的时候显示。但是上拉则一起显示在 tableview 的底部，感觉也不太好。一旦设置 hidden 为 true，那么就不能再用上拉刷新了！

如果没有的话，能否增加这样的功能？

**Comment by CoderMJLee** [comment]
2.0版本已经增加这个功能哈
