### ISSUE TITLE
不是刷新状态下，调用endRefreshing 布局会出问题

### ISSUE THREAD

**Issue by mislsl** [CoderMJLee/MJRefresh#183]
杰哥：
不清楚是否跟我的页面布局有关系，我的页面nav里有3个来按照不同参数查询。
当两个条件来回切换时。希望在点击一个条件时结束上一个条件的刷新状态，这样是没有问题的。
但是如果当前不是刷新状态，页面还是会向上64。
尽管可以在外部先通过isRefreshing判断是否是刷新状态，但我还是觉得这应该是在框架里完成的工作。
- (void)endRefreshing
{
    
    if (self.isRefreshing) {
        
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.05 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            self.state = MJRefreshHeaderStateIdle;
        });
    }
    
}

**Comment by CoderMJLee** [comment]
试试最新的2.0版本？
