### ISSUE TITLE
uicollectview的bug

### ISSUE THREAD

**Issue by zhaoxuezhi888** [CoderMJLee/MJRefresh#184]
![5bff7562-3e2d-4f02-8dfb-09532bd4a3c0](https://cloud.githubusercontent.com/assets/3005352/8027236/5fdacba8-0dc6-11e5-922a-0654f4a3fc0e.png)
在IOS8.2下，uicollectview+mjrefresh，如果上面导航栏有按钮，可以push到其他页面，这时候push到其他页面，再返回来，刷新控件隐藏不了，显示出来了，ios7下没问题

**Comment by CoderMJLee** [comment]
试试2.0版本是否还有此问题？
