### ISSUE TITLE
Mjrefresh导入奔溃

### ISSUE THREAD

**Issue by xuxueing** [CoderMJLee/MJRefresh#187]
MJRefresh通过cocoapods导入的时候 按导航栏的back按钮会莫名其妙的闪退

**Comment by CoderMJLee** [comment]
是CocoaPods Llinker Flags设置问题，导致分类不能使用

**Comment by xuxueing** [comment]
额 这个问题怎么解决呢  我之前用着挺好的 就是现在新项目导入的时候就会出现这个问题

**Comment by CoderMJLee** [comment]
我亲自测试了一下，Xcode7，MJRefresh2.0，CocosPods0.36.3。没有一点问题哈

**Comment by xuxueing** [comment]
嗯 我之前用也没问题 不知道是不是导入的库冲突了  我导入了这些库 你看看
source 'https://github.com/CocoaPods/Specs.git'

#platform:ios,'6.0'

pod 'Masonry','0.6.1'

pod 'AFNetworking','2.5.4'

pod 'SDWebImage','3.7.1'

pod 'UITableView+FDTemplateLayoutCell', '~> 1.1-beta'

pod 'M80AttributedLabel', '1.3.1'

pod 'MWPhotoBrowser', '1.4.1'

pod 'IQKeyboardManager', '~> 3.2.3'

pod 'JSONModel', '~> 1.1.0'

pod 'MBProgressHUD', '~> 0.9.1'

#pod 'MJRefresh', '~> 1.4.7'


我把MJrefresh注释掉就ok了  一打开 然后更新 点2次返回就会闪退
