### ISSUE TITLE
2.0版本无法再隐藏掉footer？

### ISSUE THREAD

**Issue by itdongbaojun** [CoderMJLee/MJRefresh#190]
现在的问题是不能设置footer的hidden属性来达到隐藏上拉控件的目的，现在设置hidden直接留下了固定的宽度，之前版本没问题，难道是我姿势不对？哈哈

**Comment by MarsLuo** [comment]
MJRefreshBackGifFooter  使用这个带有回弹效果的，可以隐藏。

**Comment by CoderMJLee** [comment]
我设想如果你需要隐藏的话，可以考虑用MJRefreshBack....。不过我也可以把以前的功能加上去哈，稍等

**Comment by CoderMJLee** [comment]
还有一种思路哈，self.tableView.footer = nil;清空它，用到时再去创建

**Comment by CoderMJLee** [comment]
@itdongbaojun 君哥，已经搞定了。你更新下就可以了

**Comment by itdongbaojun** [comment]
@CoderMJLee 惊呆了，这效率真是太高了，点赞点赞

**Comment by MarsLuo** [comment]
@CoderMJLee  提示信息可以定制吗， 我试着自定义stateLabel的显示效果，发现没什么用。

另外：为MJ哥点赞！

**Comment by CoderMJLee** [comment]
是自定义显示的文字么？这是可以的哈。你可以详细研究一下README.md和Demo哈

**Comment by MarsLuo** [comment]
抱歉MJ哥，我发现问题了， header和Footer搞混了。

**Comment by CoderMJLee** [comment]
没事哈

**Comment by WangMasterpro** [comment]
MJRefreshAutoStateFooter 这个好像不能隐藏？
