### ISSUE TITLE
关于autofooter刷新问题

### ISSUE THREAD

**Issue by blackchena** [CoderMJLee/MJRefresh#194]
我进入一个页面时候设置了 MJRefreshNormalHeader 和 MJRefreshAutoNormalFooter。并设置了beginRefreshing。刚进入页面header正在刷新的时候footer上的点击加载更多可以点击，当我点击之后footer和header的block 都被调用了，照理说应该在header 或者 footer 处于刷新状态时，是不能让footer或者header 调用与之相对应的block吧？

**Comment by CoderMJLee** [comment]
这2个是不冲突的哈，可以一起使用，很多应用都是可以同时使用的。当然，你可以自己去控制他们别一起使用
