### ISSUE TITLE
UICollectionView 水平分页加入刷新功能

### ISSUE THREAD

**Issue by Veilly** [CoderMJLee/MJRefresh#198]
是否可以给UICollectionView 水平分页加入刷新功能。

**Comment by CoderMJLee** [comment]
Sorry哈，没有考虑过增加这个功能，因为感觉这种需求比较少见

**Comment by broccolii** [comment]
https://github.com/enormego/EGOTableViewPullRefresh 可以通过这个库实现 不知道 题主 的问题解决了么

**Comment by Veilly** [comment]
@broccolii :谢谢了兄弟，我自己写了个简单的水平左拉刷新右拉加载已经解决了。

**Comment by CrazyGitter** [comment]
https://github.com/CrazyGitter/EhanCollectionView  @Veilly 这个可以
