### ISSUE TITLE
当UIColectionView中的内容不满一屏幕时下拉无法激活刷新

### ISSUE THREAD

**Issue by debug510** [CoderMJLee/MJRefresh#20]
在UIColectionView中加入刷新头部控件，从服务器取得的数据量在显示时没有超过UIColectionView的高度，此时下拉没有反应，如果超过UIColectionView高度，则下拉可以刷新，麻烦MJ老师解决一下下

**Comment by Mark-SS** [comment]
你好， 我用self.collectionView addFooterWithCallback 但是依然无法出现上提加载是什么情况？

**Comment by CoderMJLee** [comment]
尝试self.collectionView.alwaysBounceVertical = YES;，因为你的collectionView可能内容不够多，导致无法拖拽

**Comment by Mark-SS** [comment]
好的 已解决，是和另外一个scrollView 冲突了。 麻烦你了，非常感谢。
