### ISSUE TITLE
tableview重用时，如何展示table的数据加载状态

### ISSUE THREAD

**Issue by ntliuxiang** [CoderMJLee/MJRefresh#203]
横向存在的多个数据列表，可侧滑，通过重用tableview实现的。因为要重用，所以每次侧滑reloaddata之前都会先让tableview的header和footer先endRefreshing，然后再根据数据的请求状态来设置header和footer的状态。
    我在api里面找到的beginRefreshing，一旦执行就会触发header或者footer请求数据的方法。我暂时的解决方法是在header和footer的数据请求方法里面先作判断，如果数据已经在请求中就直接return。
    能否提供一个方法可以直接设置tableview的header和footer的状态，而不用触发header和footer的数据请求方法呢？

**Comment by CoderMJLee** [comment]
你横向有多少个页面？

**Comment by ntliuxiang** [comment]
j哥好迅速啊= =好激动啊。。。。。

**Comment by ntliuxiang** [comment]
10来个页面吧

**Comment by CoderMJLee** [comment]
那能不能这么设计呢？一旦某个页面被循环利用了，就将以前的请求关掉，就算请求回调回来了，也不处理

**Comment by sylarhcn** [comment]
我之前做过类似的功能，可以将请求数据管理数据的功能独立出来成一个单独的dataSource类，用url来做key缓存数据，每个页面对应一个url，再设置一个时间间隔的判断，就不必担心每次重用时request混乱的问题了，都是独立。而且还不会短时间重复一个request，不会浪费流量
