### ISSUE TITLE
希望有的功能

### ISSUE THREAD

**Issue by MaiyaT** [CoderMJLee/MJRefresh#204]
上拉加载更多的时候，想不用拉到最底部再往上拉一点才开始加载更多的数据。希望上拉的时候可自动加载更多，比如拉到当前的还有半个屏幕或者一整个屏幕就出发加载更多这个动作。

**Comment by CoderMJLee** [comment]
你可以研究一下footer.appearencePercentTriggerAutoRefresh属性，他可以控制刷新控件出现多少时，出发刷新状态，比如设置个0.5，就是出现一半；设置个负数，就是还未出现就刷新
