### ISSUE TITLE
您好，关于上拉加载我这有一个问题

### ISSUE THREAD

**Issue by pczhai** [CoderMJLee/MJRefresh#208]
根据项目需求，用到的是Gif图片，而且要求下拉刷新跟上拉加载的交互是一样的：
只有图片，没有字。
    [header setImages:refreshImages forState:MJRefreshStatePulling];
    [header setImages:normalImages forState:MJRefreshStateIdle];
    header.lastUpdatedTimeLabel.hidden = YES;
    header.stateLabel.hidden = YES;
下拉刷新
    [footer setImages:refreshImages forState:MJRefreshStatePulling];
    [footer setImages:normalImages forState:MJRefreshStateIdle];
    footer.lastUpdatedTimeLabel.hidden = YES;
    footer.stateLabel.hidden = YES;
上拉加载

出现的问题是：下拉刷新有一个Idle的Gif，也就是例子中的那60张图片
而上拉加载没有。
请问是不支持，还是我代码写错了。

**Comment by CoderMJLee** [comment]
你的footer是啥类型？

**Comment by pczhai** [comment]
之前用的这个MJRefreshAutoGifFooter

后来改成MJRefreshBackGifFooter 就OK了

现在不明白的是MJRefreshAutoGifFooter为啥不行，还是说我的代码有问题

**Comment by CoderMJLee** [comment]
可以发个Demo给我看看么？

**Comment by CoderMJLee** [comment]
AutoGifFooter是自动刷新的footer，不存在往上拉的情况，所以没有MJRefreshStateIdle状态下的图片，只有MJRefreshStateRefreshing状态下的图片。只有BackGifFooter才有往上拽切换图片的功能。他们的用法是不一样的哈

**Comment by pczhai** [comment]
这样子啊，那我明白了，谢谢！
