### ISSUE TITLE
swift 中podfile 加上 use framework 在桥接文件中即使引入mjrefresh也没法子在viewcontroller中使用，说找不到这些方法。如果不加 use framework就可以使用。

### ISSUE THREAD

**Issue by hatjs880328** [CoderMJLee/MJRefresh#210]
swift 中podfile 加上 use framework 在桥接文件中即使引入mjrefresh也没法子在viewcontroller中使用，说找不到这些方法。如果不加 use framework就可以使用。

**Comment by CoderMJLee** [comment]
podfile写pod 'MJRefresh'就OK了，不用写其他哈

**Comment by wealon** [comment]
下面是我们在项目中Podfile的配置:
platform :ios,7.0
pod 'MJRefresh', '~> 2.0.2'
pod 'SVProgressHUD', '~> 1.1.3'

use_frameworks!
下面是我们在桥接文件中的引入：
#import <MJRefresh/MJRefresh.h>

在控制器中import 
import MJRefresh

在下面的方法中使用就没有问题
