### ISSUE TITLE
可以加个配置吗：当内容超出界面时才显示下拉刷新

### ISSUE THREAD

**Issue by maimake** [CoderMJLee/MJRefresh#212]
可以配置只有在contentSize.height大于tableview.bounds.size.height时，才出现下拉刷新吗？

**Comment by CoderMJLee** [comment]
这个需求并不是每个项目都有哈，所以框架里面是不可能默认就做这个配置的哈。
这个功能可以由自己去控制控件显示还是隐藏的
```objc
header.hidden = YES; // 隐藏下拉刷新
footer.hidden = YES; // 隐藏上拉刷新
```
