### ISSUE TITLE
小码哥你好，在上拉加载更多操作成功后，点击其他按钮返回tableView的顶部，tableView会发生偏移

### ISSUE THREAD

**Issue by liu521227** [CoderMJLee/MJRefresh#213]
小码哥你好，在上拉加载更多操作成功后，点击其他按钮返回tableView的顶部，tableView会发生偏移，在不加载的情况下是没有问题的
NSIndexPath *lastPath = [NSIndexPath indexPathForRow:0 inSection:0];
 [_tableView scrollToRowAtIndexPath:lastPath atScrollPosition:UITableViewScrollPositionBottom animated:YES];
![ios simulator screen shot 2015 7 7 10 38 32](https://cloud.githubusercontent.com/assets/11803388/8537674/f2e8aaca-2494-11e5-9643-dcc14a6c39e5.png)

**Comment by CoderMJLee** [comment]
我测试了一下Demo，没发现有这样的问题哦。
1.是往下偏移么？
2.使用上拉刷新是哪个footer类？

**Comment by liu521227** [comment]
是往下偏移，我使用的是默认的上拉加载

**Comment by CoderMJLee** [comment]
你有没有设置过tableView的其他属性，比如contentOffset、contentInset、headerView、footerView？或者发一份有这个问题的Demo给我可以么？谢谢哈

**Comment by liu521227** [comment]
稍等，我写一个Demo试试

**Comment by liu521227** [comment]
小码哥，我怎么发给你？

**Comment by CoderMJLee** [comment]
richermj123go@vip.qq.com

**Comment by liu521227** [comment]
小码哥，发过去了

**Comment by CoderMJLee** [comment]
你每次请求数据完毕后都调用了setupRefresh，导致不断重复创建Footer，实际上如果footer有了，直接结束刷新就好了
```objc
- (void)setupRefresh
{
    refreshBool = NO;

    urlStr = [NSString stringWithFormat:@"%@&page=%ld", urlStr,page++];
    if (_tableView.footer) {
        [_tableView.footer endRefreshing];
    } else {
        _tableView.footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(initData)];
    }
}
```

**Comment by liu521227** [comment]
ok了，万分感谢！我自己再研究下

**Comment by CoderMJLee** [comment]
不客气哈

**Comment by xiaoboJoin** [comment]
HI,MJLee, 
我需要滚动到最底部，调用一下方法，但是出现了问题
 [_tableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:self.topicCommentList.count -1 inSection:2] atScrollPosition:UITableViewScrollPositionBottom animated:NO];
![image](https://cloud.githubusercontent.com/assets/6210610/9375282/6e0f816a-4731-11e5-9e36-05bd59433624.png)

**Comment by KelaKing** [comment]
调用`scrollToRowAtIndexPath:atScrollPosition:animated:`会有偏移，原因：`endRefreshing`内部异步操作，导致整个`cententOffSet`计算有误。解决：外部业务也对应加上异步
```objc
dispatch_async(dispatch_get_main_queue(), ^{
    // 推迟到下一个run loop去滚动
    [self.tableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:0] atScrollPosition:UITableViewScrollPositionTop animated:YES];
});
```
