### ISSUE TITLE
加入MJRefresh后不显示下拉刷新控件

### ISSUE THREAD

**Issue by hanhailong** [CoderMJLee/MJRefresh#214]
![1b101707-e09f-43d8-8e62-492a177b95ed](https://cloud.githubusercontent.com/assets/4241807/8549468/80cc0356-24fd-11e5-8ce5-3a439324b12f.png)

如果所示，我加入MJRefresh后，执行下拉不显示下拉控件，这是为啥？

**Comment by CoderMJLee** [comment]
应该是用错类型了哈，应该用MJRefreshNormalHeader，你应该是用了MJRefreshHeader这个抽象类

**Comment by hanhailong** [comment]
![aff4f5c4-9467-4b19-bc2e-7b60a7451105](https://cloud.githubusercontent.com/assets/4241807/8549989/5b4fb9b2-2500-11e5-8694-5129a65fb891.png)

太感谢了，好使了，我检查了下代码，果然是用的MJRefreshHeader这个抽象类，感谢大神！
