### ISSUE TITLE
杰哥，CocoaPods添加的类库，内容不全，是我打开方式不对吗

### ISSUE THREAD

**Issue by YAANNZ** [CoderMJLee/MJRefresh#216]
UIScrollView+MJRefresh.h   文件里只有两个方法声明。
![1](https://cloud.githubusercontent.com/assets/9867567/8564794/077d0b28-2582-11e5-9a61-15293832284b.png)

**Comment by CoderMJLee** [comment]
最新版本确实是只有2个方法

**Comment by YAANNZ** [comment]
是我fork的没有更新😓，谢谢杰哥。

**Comment by CoderMJLee** [comment]
不客气哈
