### ISSUE TITLE
endRefreshing 建议

### ISSUE THREAD

**Issue by yuchuanfeng** [CoderMJLee/MJRefresh#217]
MJ哥你好, 我在用你的下拉刷新, 我想可否在结束刷新的时候传递个成功或者失败的状态, 就像 QQ 的那样, 如果请求成功了 就传递 YES 然后在head 上显示个刷新成功, 只是个人想法~~~~

**Comment by CoderMJLee** [comment]
显示出来的文字或者内容，每个项目都不一样哈。所以增加这个功能，建议使用MBProgressHUD或者SVProgressHUD来显示提醒信息
