### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zx1050336132** [CoderMJLee/MJRefresh#218]
亲爱的MJ哥，我用cocoapods导入的库，arrow@2x.png图片不能显示

**Comment by Onetaway** [comment]
我也碰到了。。。

**Comment by zx1050336132** [comment]
大神解决了吗

**Comment by zx1050336132** [comment]
我直接拷贝了图片到项目里面，代码改成”UIImageView *arrowView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"arrow"]];“，看来暂时是解决了，可能是pods资源文件路径的问题

**Comment by CoderMJLee** [comment]
啊？为何我这里没事呢？哈哈。你的Xcode版本是多少？项目SDK是多少？OC还是Swift？

**Comment by Onetaway** [comment]
Xcode 6.4  SDK8.4  项目是OC 。我跟进去看了。`MJRefreshNormalHeader` 里面
```
- (UIImageView *)arrowView
{
    if (!_arrowView) {
        
        UIImageView *arrowView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:MJRefreshSrcName(@"arrow.png")]];
        [self addSubview:_arrowView = arrowView];
    }
    return _arrowView;
}
``` 

里面没取到图片

**Comment by CoderMJLee** [comment]
看看Pods项目里面的MJRefresh文件夹，里面有个Resources文件夹，截图看看里面的东西哈，3Q

**Comment by zx1050336132** [comment]
里面就是MJRefresh.bundle\arrow@2x.png

**Comment by Onetaway** [comment]
![screen shot 2015-07-10 at 09 16 14](https://cloud.githubusercontent.com/assets/3251826/8610412/5debd3e6-26e4-11e5-91f5-3ddd467dd2de.png)

**Comment by zx1050336132** [comment]
xcode6.3.2，ios8.3 ，oc

**Comment by CoderMJLee** [comment]
[UIImage imageNamed:MJRefreshSrcName(@"arrow.png")]改成[UIImage imageNamed:MJRefreshSrcName(@"arrow")]试试？
或者将arrow@2x.png文件名改为arrow.png试试？

**Comment by Onetaway** [comment]
两个都试了，都不行。。。我觉得还是图片路径的问题   那个UIImage 返回的 是  nil

**Comment by zx1050336132** [comment]
把arrow@2x.png拷到自己工程中，用[UIImage imageNamed:@"arrow.png"]可以暂时解决

**Comment by Onetaway** [comment]
恩  我也打算先这么弄了  :)

**Comment by CoderMJLee** [comment]
那应该是CocoaPods在编译资源的时候出了问题

**Comment by Onetaway** [comment]
我知道是哪的问题了，没有箭头的情况是 target是iOS 8的时候  use_framework!的情况下，我前几天改成platform iso 7 ,不使用framework就好了，杰哥可以再看看使用framework的情形

**Comment by CoderMJLee** [comment]
2.3.2版本已经解决这个问题了哈，确实是use_frameworks!带来的小问题，谢谢大家
