### ISSUE TITLE
小码哥你好，对于tableview底部的contentInset该如何处理？

### ISSUE THREAD

**Issue by expkzb** [CoderMJLee/MJRefresh#219]
若底部存在contentInset，MJRefresh会不会在此基础上向下平移？
刚才试了一下，貌似穿帮了

**Comment by CoderMJLee** [comment]
其实已经做过处理了，比如导航栏造成的contentInset.top == 64，tabbar造成的contentInset.bottom == 49，都已经处理过了。设计的初衷并不是向下平移哈，而是刚好粘着contentInset.bottom顶部的边

**Comment by CoderMJLee** [comment]
如果是希望在底部刷新控件的上面显示一些东西，建议使用tableViewFooterView

**Comment by 12207480** [comment]
我也遇到了这样的问题 contentInset.buttom 设置 比较大 上拉 会漂移

**Comment by CoderMJLee** [comment]
我刚才发布了个2.3.0版本了，如果你不希望你的inset对header或者footer的显示造成影响，可以参考2个属性：
```objc
@interface MJRefreshHeader : MJRefreshComponent
/** 忽略多少ignoredInsetTop */
@property (assign, nonatomic) CGFloat ignoredInsetTop;
@end

@interface MJRefreshFooter : MJRefreshComponent
/** 忽略多少ignoredInsetBottom */
@property (assign, nonatomic) CGFloat ignoredInsetBottom;
@end
```
刷新控件漏出了多少，你就设置ignored为多少哈。详情可以参考Demo
```objc
#pragma mark UITableView + 上拉刷新 自动回弹的上拉01
- (void)example18
{
    // 设置回调（一旦进入刷新状态，就调用target的action，也就是调用self的loadMoreData方法）
    self.tableView.footer = [MJRefreshBackNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreData)];
    // 设置了底部inset
    self.tableView.contentInset = UIEdgeInsetsMake(0, 0, 30, 0);
    // 忽略掉底部inset
    self.tableView.footer.ignoredInsetBottom = 30;
}
```

**Comment by lan603168** [comment]
我也遇到这个问题了，看来已经解决了，我的tableViewFooterView和tableViewHeaderView都使用了......然后上面还有一个广告，为了能滚动，直接contentInset.top=120之后，添加在了tableview里面了

**Comment by CoderMJLee** [comment]
@lan603168 
```objc
self.tableView.header.ignoredScrollViewContentInsetTop = 120;
```

**Comment by 12207480** [comment]
MJRefreshAutoNormalFooter   这个没对ignoredScrollViewContentInsetTop作出处理，我设置contentInset = UIEdgeInsetsMake(0, 0, 40, 0); 放上去的view 会挡住上拉加载

**Comment by CoderMJLee** [comment]
@12207480 你的橙色控件是自己addSubview加上去的？还是tableViewFooterView？最好发个Demo过来哈，谢谢

**Comment by CoderMJLee** [comment]
建议使用tableViewFooterView，不要直接addSubView。MJRefresh的Footer是直接拼接在contentSize最后面的

**Comment by chanbendong** [comment]
我用mjrefresh想做第一张图的效果，用了[_tableview bringSubviewToFront:_tableView.mj_header];

**Comment by chanbendong** [comment]
我用mjrefresh想做第一张图的效果，用了[_tableview bringSubviewToFront:_tableView.mj_header];
但是在恢复的时候出现了图2的情况，请问怎么解决 #
![wechatimg1](https://cloud.githubusercontent.com/assets/15088537/20559340/ebacef84-b1ae-11e6-839e-1b8561ed7c63.jpeg)
![wechatimg3](https://cloud.githubusercontent.com/assets/15088537/20559343/edd739b8-b1ae-11e6-9a2d-fb15429be228.jpeg)

**Comment by chanbendong** [comment]
我用mjrefresh想做第一张图的效果，用了[_tableview bringSubviewToFront:_tableView.mj_header];
结果恢复的时候出现了图2的效果，请问怎么解决
![wechatimg3](https://cloud.githubusercontent.com/assets/15088537/20559367/119baa0a-b1af-11e6-928b-11fd252be981.jpeg)
![wechatimg1](https://cloud.githubusercontent.com/assets/15088537/20559368/13fde7ae-b1af-11e6-9331-bb4a4d52c589.jpeg)
