### ISSUE TITLE
国际化

### ISSUE THREAD

**Issue by tyrone782** [CoderMJLee/MJRefresh#22]
MJRefreshConst中文字有办法国际化吗？

**Comment by CoderMJLee** [comment]
现在提供了随时设置文字的接口，可以试试哈

**Comment by Hitooo** [comment]
的确是提供设置文字的接口，但是用的地方太多了，而且那几种状态的文字基本都是不变的，所以你支持国际化的话我们会很方便

**Comment by CoderMJLee** [comment]
有一种取而代之的方法哈，自定义刷新控件即可，继承自MJRefreshNormalHeader，然后实现下面的方法
```objc
- (void)prepare
{
    [super prepare];
    // 设置文字
}
```

**Comment by CoderMJLee** [comment]
有时间的话，我考虑把国际化加进去哈，谢谢提醒
