### ISSUE TITLE
MJ哥，能不能做个类似这样的刷新方式

### ISSUE THREAD

**Issue by happying** [CoderMJLee/MJRefresh#221]
MJ哥，能做个类似这样的刷新方式么？貌似体验不错：页面整体不动，上面拉下来一个圆圈（页面整体不会下拉，只是一个原形随拖动向下），园中环形箭头不停的转，然后进行刷新
![2015-07-13 11 51 51](https://cloud.githubusercontent.com/assets/7139165/8642359/a75a3a40-2955-11e5-8dee-ea163488e47f.png)

**Comment by CoderMJLee** [comment]
有没有具体的App参考一下？

**Comment by xn1108100154** [comment]
参考 简书 for Android

**Comment by happying** [comment]
楼上说的对，我问过貌似现在安卓方面都往这方面的体验靠

**Comment by CoderMJLee** [comment]
大概明白意思哈。有没有iOS的App参考下？我身边都木有安卓手机。。。

**Comment by happying** [comment]
不好意思，MJ哥，这两天有事没上GIT，回复迟了，我找了一下。。貌似暂时没在iOS上找到类似的体验效果啊。

**Comment by CoderMJLee** [comment]
好的，以后我见到了，有空了，尝试增加一下哈
