### ISSUE TITLE
bounces = NO时上拉加载bug

### ISSUE THREAD

**Issue by xn1108100154** [CoderMJLee/MJRefresh#222]
将bounces = NO，缓慢上拉至最底端（实际在阅读时也确实是这种情况的），不会触发加载更多。原因仿佛是在这种情况下，isDragging的状态不对

**Comment by CoderMJLee** [comment]
那就设置footer.appearencePercentTriggerAutoRefresh小于1.0

**Comment by xn1108100154** [comment]
这个想法挺巧妙的👍

**Comment by CoderMJLee** [comment]
我刚才修改了一下判断条件哈，不用设置appearencePercentTriggerAutoRefresh也可以自动刷新了，你试试最新版哈，2.2.1版本

**Comment by xn1108100154** [comment]
cool
