### ISSUE TITLE
MJ大神，希望修改对外 API 的时候能顾及版本兼容性

### ISSUE THREAD

**Issue by yangyangyyluck** [CoderMJLee/MJRefresh#223]
项目一直默认追踪的最新版MJRefresh，这次pod update 后突然一片红。。
原来是MJRefresh 的API改了。。

addLegendHeaderWithRefreshingBlock:
addLegendFooterWithRefreshingBlock:
self.tableView.footer.automaticallyRefresh = NO;
等等都没有了

以后改动对外API的时候希望能友好一点。。
需要修改的地方太多了。。

**Comment by CoderMJLee** [comment]
好的，Sorry哈。从1.0升级到2.0，确实改变比较大，因为2.0是全新设计了，扩展性比1.0强很多。从2.0开始，接口就基本不会再有大变化，这是比较痛的升级。对不起哈
