### ISSUE TITLE
下拉刷新动画 这个方法没有了吗？headerWithRefreshingTarget:  refreshingAction

### ISSUE THREAD

**Issue by mahong125** [CoderMJLee/MJRefresh#224]
[MJRefreshGifHeader headerWithRefreshingTarget:self refreshingAction:@selector(loadNewData)];

下拉刷新动画 这个方法没有了吗？headerWithRefreshingTarget:  refreshingAction

**Comment by mahong125** [comment]
cocoapods 更新的库竟然不是最新的。。。。。//  Created by MJ Lee on 15/3/4.
//  Copyright (c) 2015年 itcast. All rights reserved.

**Comment by CoderMJLee** [comment]
先执行pod repo update，更新一下仓库哈

**Comment by mahong125** [comment]
搞定了，非常感谢
