### ISSUE TITLE
和sticky header（头部固定）的UICollectionView混用的时候，下拉刷新出现奇怪的动画效果

### ISSUE THREAD

**Issue by kyfxbl** [CoderMJLee/MJRefresh#225]
我故意把动画的时间从MJRefreshFastAnimationDuration改成3秒，为了看得更清楚。在默认的动画时间下，不会这么明显，但是也有明显的一闪，显得很奇怪

![animation_bug](https://cloud.githubusercontent.com/assets/2126825/8742268/2caaac1e-2c96-11e5-84d8-80adcf92ae7d.gif)

读了一下代码，最后定位到这一段：

```
[UIView animateWithDuration:3 animations:^{
            // 增加滚动区域
            CGFloat top = self.scrollViewOriginalInset.top + self.mj_h;
            self.scrollView.mj_insetT = top;

            // 设置滚动位置
            self.scrollView.mj_offsetY = - top;
        } completion:^(BOOL finished) {
            [self executeRefreshingCallback];
        }];
```

似乎是因为修改contentInset引起的，好像UICollectionView的隐式动画和这里的显式动画有冲突，但也不确定。可否提供一点思路，这个现象可能是由什么原因引起的？谢谢！

**Comment by CoderMJLee** [comment]
好的，我抽空看看哈

**Comment by zymxxx** [comment]
Mj，我也遇到了这个问题，我在使用CSStickyHeaderFlowLayout之后，上下拉刷新都会出现headerView浮动的情况，我尝试着把开始刷新以及结束刷新的代码屏蔽之后，该现象倒是没有了。不知道是CSStickyHeaderFlowLayout的问题还是怎样，麻烦你看一下吧。

**Comment by ShannonChenCHN** [comment]
将动画引擎由 Apple 的 Core Animation 改为 facebook 的 Pop 之后，貌似没有问题了。->_->[https://github.com/CoderMJLee/MJRefresh/pull/737](url)

**Comment by ShannonChenCHN** [comment]
@zymxxx 可以试试在下拉刷新时，让 sticky header（头部固定）的 UICollectionViewLayout 的那几个自定义布局的方法返回默认值：

``` Objective-C
- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect {
    
    NSArray *originalAttributes = [super layoutAttributesForElementsInRect:rect];
    
    // https://github.com/CoderMJLee/MJRefresh/issues/225
    if (self.enabled == NO) {
        return originalAttributes;
    }
    ...
}

- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds {
    if (self.enabled == NO) {
        return [super shouldInvalidateLayoutForBoundsChange:newBounds];
    }
    
    return YES;
}

```

**Comment by RisingSSR** [comment]
https://github.com/CoderMJLee/MJRefresh/assets/88606535/4f672147-007c-41f0-bb89-659b8ad3bbda

我继承 **UICollectionViewLayout** 自定义了一个layout，在实现的时候出现了上述情况

```Swift

      let header = MJRefreshGifHeader {
          // self.mappy.clean()
          // self.request(sno: "2021215154")
      }
      .autoChangeTransparency(true)
      .set_refresh_sports()
      .ignoredScrollView(contentInsetTop: -58)
      .link(to: collectionView)
      
      header.isCollectionViewAnimationBug = true
      header.endRefreshingAnimationBeginAction = {
          collectionView.collectionViewLayout.finalizeLayoutTransition()
      }
```

而我的自定义的layout，是重写 `layoutAttributesForSupplementaryView(ofKind:at:)` 实现头部固定的，请问如何处理这种动画效果
