### ISSUE TITLE
自动刷新和自动回弹

### ISSUE THREAD

**Issue by sitting2002** [CoderMJLee/MJRefresh#228]
小码哥
感谢你开源这套棒棒的上下拉控件

我现在遇到一个需求，上下拉刷新的控件需要同时具备自动刷新和自动回弹功能。（自动刷新然后回弹）
尝试修改你的源码未能成功，请教如何同时实现这两个功能呢？

（补充：已经全部加载完毕后回弹）

期盼你的答复

**Comment by CoderMJLee** [comment]
你的意思是：同一个刷新控件，既具备自动刷新，又具备上拉回弹的功能？

**Comment by sitting2002** [comment]
是的

**Comment by CoderMJLee** [comment]
没考虑过这种情况哦。。。市面上的需求基本都是只占用一种情况哈

**Comment by sitting2002** [comment]
我也感觉我的需求比较奇葩，但如果要实现的话如何实现呢？ 能指导一下吗？

**Comment by CoderMJLee** [comment]
那就需要时刻修改scrollView的inset，监听scrollview滚动。。。比较恶心哦
