### ISSUE TITLE
在上拉刷新的时候，如果没有数据了，怎么让底部显示无数据

### ISSUE THREAD

**Issue by tounaobun** [CoderMJLee/MJRefresh#229]
在往上拉刷新时，如果没有可加载的数据了，底部显示的文本一直是“点击或上拉加载更多”，而我需要的是类似这样的文本”到达底部了“，并且上拉刷新的时候不会有菊花出现。我查了一下有这样一个方法，［noticeNoMoreData］，但是效果不是我想要的。

**Comment by CoderMJLee** [comment]
就是用noticeNoMoreData方法哈，你只需要改下文字就好了：
```objc
[footer setTitle:@"到达底部了" forState:MJRefreshStateNoMoreData];
```
