### ISSUE TITLE
pod 导入 版本6.4（6E35B）Xcode中，请问MJ怎么解决？

### ISSUE THREAD

**Issue by littleniu** [CoderMJLee/MJRefresh#230]
<img width="558" alt="2015-07-21 3 08 24" src="https://cloud.githubusercontent.com/assets/9244582/8794898/64293972-2fba-11e5-8064-c6e6ae8e26b2.png">

**Comment by alicksnake** [comment]
俺也有问题，6.4，用pod安装，出这个问题，不能用

**Comment by littleniu** [comment]
我有用 下载好了 直接导进去，不知道为撒又能用了，奇怪了。。。你试试

**Comment by CoderMJLee** [comment]
哈哈，我没遇到过哦

**Comment by alicksnake** [comment]
...真的啊，真的用pod安装的话没有这个文件download下来

**Comment by littleniu** [comment]
哈哈 MJ没遇见过哦。。。。
