### ISSUE TITLE
同一个页面有2个tableview，都添加了refresh，但是第二个tableview的下拉不显示MJrefresh

### ISSUE THREAD

**Issue by chanmd** [CoderMJLee/MJRefresh#232]
代码如下
    
WeakSelf(BRTreasuresViewController);
    self.tableview_customer.header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [weakSelf ___fetch_customer_list];
    }];
    
    self.tableview_commission.header = [MJRefreshHeader headerWithRefreshingBlock:^{
        [weakSelf ___fetch_commision_list];
    }];

**Comment by CoderMJLee** [comment]
第2个的类型用错了哈。不是MJRefreshHeader，得用MJRefreshNormalHeader

**Comment by chanmd** [comment]
太感谢了！！！！

**Comment by skytosky** [comment]
self.tableview_commission.header = [MJRefreshHeader headerWithRefreshingBlock:^{
    [weakSelf ___fetch_commision_list];
}]; 
我使用的是这个方法  在上拉的时候 没更新的时候如何想提示已是最新代码  如何设置啊 大牛，foot可以通过tableView.foot 转换成一个 MJRefreshFooter，有一个noticeNoMoreData 方法 但是header 却没有，如何解决
