### ISSUE TITLE
上拉加载更多里面reloaddata后tableview向下滑的时候会发生严重卡顿？目测是因为contentsize改变了使得tableview跳动，请问这个有什么解决办法么？

### ISSUE THREAD

**Issue by 651893553** [CoderMJLee/MJRefresh#233]

**Comment by CoderMJLee** [comment]
是不是因为cell里面的内容和结构过于复杂？或者在主线程做了耗时的操作？

**Comment by 651893553** [comment]
谢谢你的回答，因为我的tableview要展示三种cell，而且都是变高在cell返回高度的delegate方法中耗时较长。

**Comment by skytosky** [comment]
self.tableview_commission.header = [MJRefreshHeader headerWithRefreshingBlock:^{
[weakSelf ___fetch_commision_list];
}]; 
我使用的是这个方法 在上拉的时候 没更新的时候如何想提示已是最新代码 如何设置啊 大牛，foot可以通过tableView.foot 转换成一个 MJRefreshFooter，有一个noticeNoMoreData 方法 但是header 却没有，如何解决

**Comment by CoderMJLee** [comment]
Header没有这个功能哦，因为我觉得下拉刷新应该是一直都可以刷新的才对，不存在已经是最新了，不能刷新了

**Comment by iPermanent** [comment]
目前新的代码依旧存在这个问题，把所有有计算的都排除了，下拉后正常，上拉以后再往上滑动就会卡顿跳跃

**Comment by iPermanent** [comment]
已经解决，问题出在 estimateHeight上，已经给出了自行计算的高度的时候，就要给三个预估高度设置为0，新系统上默认会给值，需要手动设置为0

**Comment by iPermanent** [comment]
已经解决，问题出在 estimateHeight上，已经给出了自行计算的高度的时候，就要给三个预估高度设置为0，新系统上默认会给值，需要手动设置为0
