### ISSUE TITLE
NoticeNoMoreData 占据了一定的空间

### ISSUE THREAD

**Issue by tounaobun** [CoderMJLee/MJRefresh#234]
当调用方法refreshFooter.setTitle("", forState: MJRefreshStateNoMoreData)，footer底部的文字确实不见了，但是还是保留了它所占据的空间，控件能不能再添加一个功能，比如设置title为nil时底部的加载完毕提示文字消失，同时不占据空间。比如:refreshFooter.setTitle(nil, forState: MJRefreshStateNoMoreData)。

**Comment by CoderMJLee** [comment]
如果希望消失的话，可以考虑这样用哈：footer.hidden = YES

**Comment by tounaobun** [comment]
把footer设为hidden后，上拉刷新的功能就失效了。。能不能加载完毕后让footer消失？

**Comment by CoderMJLee** [comment]
消失以后，上拉刷新功能也一样就没了的。
你可以尝试使用MJRefreshBackNormalFooter哈，不用MJRefreshAutoNormalFooter。看看是不是你想要的效果

**Comment by tounaobun** [comment]
谢谢小玛哥，MJRefreshBackNormalFooter正是我想要的footer。
