### ISSUE TITLE
使用xib时MJ无法自适应大小

### ISSUE THREAD

**Issue by KIDXO** [CoderMJLee/MJRefresh#235]
![4801140b-fe7a-447e-80c4-e40222075fac](https://cloud.githubusercontent.com/assets/5291982/8899761/06234cfe-346b-11e5-8bbc-c9fc31d46261.png)

**Comment by KIDXO** [comment]
- (void)viewDidLoad
{
    [super viewDidLoad];
    self.tableView.header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{

    }];
    self.tableView.header = [MJRefreshNormalHeader headerWithRefreshingTarget:self refreshingAction:@selector(requestDataNew)];
    self.tableView.footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{

    }];
    self.tableView.footer = [MJRefreshBackNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(requestDataMore)];
}

**Comment by CoderMJLee** [comment]
我刚才测试下Xib，没发现问题哦。你是哪一块控件用了Xib？可以发个Demo么？谢谢

**Comment by KIDXO** [comment]
- (void)viewDidLayoutSubviews
{
    self.refreshControl = [BOZPongRefreshControl attachToScrollView:self.tableView
                                                  withRefreshTarget:self
                                                   andRefreshAction:@selector(actionRefresh)];
    self.refreshControl.backgroundColor = [UIColor blackColor];
    self.refreshControl.foregroundColor = [UIColor whiteColor];
}

写在viewDidLayoutSubviews函数里面问题解决了
