### ISSUE TITLE
在下拉刷新的时候，如果没有数据了，怎么让顶部显示无数据

### ISSUE THREAD

**Issue by haifenghuang** [CoderMJLee/MJRefresh#236]
现在的实现中，上拉刷新的时候，如果没有数据了，底部可以显示无数据。  

但是下拉刷新的时候却没有相关的实现。请问是否有什么机制，也能够使顶部显示无数据？

**Comment by CoderMJLee** [comment]
这种需求比较少吧？我是这么想的哈：下拉刷新的目的是加载最新的数据，永远都有会最新的数据出现吧？不会出现没有新数据。就算没有新数据，应该也是时间问题哈

**Comment by haifenghuang** [comment]
我这里的需求是这样的，一个类似微信的聊天界面，最初只加载最后的15条聊天记录，当在聊天界面下拉刷新的时候，需要加载显示更旧的15条聊天记录，这个过程一直重复，直到没有更多的旧的聊天记录。而且我认为下拉刷新是显示旧的数据，上拉刷新才是显示最新的数据，不知道是不是正确？

**Comment by wonderffee** [comment]
我也有这种需求，但是另外一种，是上拉刷新的时候，如果上拉到底部了，再也没有更多数据的时候，在底部显示“没有更多数据了”，这个需求应该比较普遍吧？

**Comment by CoderMJLee** [comment]
@wonderffee 这个需求很早以前可以实现了哈，细细看一下README和Demo就知道怎么做了。3Q
