### ISSUE TITLE
上拉刷新bug

### ISSUE THREAD

**Issue by shaozl** [CoderMJLee/MJRefresh#237]
[MJRefreshBackNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreData)]

用这个上拉刷新，noticeNoMoreData的时候，发现箭头还是依然存在，不会消失

**Comment by CoderMJLee** [comment]
我刚才试了哈，箭头并没有显示出来。有Demo可以看看么？谢啦

**Comment by shaozl** [comment]
Demo 地址：https://github.com/shaozl/DemoMJ.git  。上拉刷新3秒后，通知tableview.footer noticeNomoreData

**Comment by CoderMJLee** [comment]
我看了下你的代码哈，正确的写法是这样的
```objc
-(void)endRefresh
{
    // 当显示没有“更多数据”时，不需要调用endRefreshing哈
//    [_tableView.footer endRefreshing];
    [_tableView.footer noticeNoMoreData];
}
```
