### ISSUE TITLE
底部状态文字没有水平居中

### ISSUE THREAD

**Issue by tounaobun** [CoderMJLee/MJRefresh#238]
底部状态文字没有水平居中

**Comment by tounaobun** [comment]
UICollectionView设置了contentInset属性。
collectionView.contentInset = UIEdgeInsets(top: 0, left: 8, bottom: 8, right: 8)
UICollectionView左右两边有8个点的间距。
顶部的状态文字和底部的状态文字都没有居中，稍微往右边移了一点。

建议MJRefresh的状态文字UILabel应该考虑到ScrollView的contentInset属性。

**Comment by zhangferry** [comment]
我也遇到这个问题，用最新版的SDK测试还是有这个问题，设置contentInset，刷新控件不居中。这个issue为什么关了呀？？ @CoderMJLee
