### ISSUE TITLE
上拉刷新MJRefreshAutoNormalFooter触发太容易

### ISSUE THREAD

**Issue by tujinqiu** [CoderMJLee/MJRefresh#242]
MJRefreshAutoNormalFooter在上拉刷新的时候，感觉太容易触发了，也就是我往上拉，拉到没有列表的时候，稍微提动一点就会触动刷新，这个触发太容易了。好像MJRefreshBackNormalFooter的触发就比较正常。但是MJRefreshBackNormalFooter默认隐藏，又不能显示提示的作用。能否有兼顾这两者的footer？

**Comment by CoderMJLee** [comment]
MJRefreshAutoNormalFooter的设计初衷就是自动刷新哈，稍微动一下就刷新，如果希望用力上拉才刷新的话，可以设置`footer.automaticallyRefresh = NO;`试试哈，看看是不是你想要的效果

**Comment by tujinqiu** [comment]
OK，可以实现我要的效果，谢杰哥

**Comment by CoderMJLee** [comment]
不客气哈
