### ISSUE TITLE
请问如何更改 MJHeader 的 frame？

### ISSUE THREAD

**Issue by jkyin** [CoderMJLee/MJRefresh#243]
我现在碰到的需求是在一个用头 tableHeaderView 的 tableView 中把 MJHeader 刷新控件移动到 tableHeaderView 的底部。请问能给些建议吗。

**Comment by jkyin** [comment]
OK，我已经解决了。

设置这个属性 `ignoredScrollViewContentInsetTop`。

## 讨论：

如果想要往下移，那么就必须给这个属性设置复数，然而按照字面意思和 contentInset 原本的意义应该是设置正值才是往下。不知作者的意图是？

**Comment by shangleixun** [comment]
有时候可能想让 tableView 顶部距离 naviBar 有一定宽度，此时如果不设置 ignoredScrollViewContentInsetTop 的话， mjHeader 会在没有刷新时，露出一截，不好看。
设置这个属性为正值的话，就可以免去设置“一定宽度”了，会自动在头部空出一截来。
