### ISSUE TITLE
如果让下拉具有上拉的功能

### ISSUE THREAD

**Issue by jiongge** [CoderMJLee/MJRefresh#245]
我有历史消息需要下来加载,就像qq的历史消息,下拉几次没有系统消息显示加载完毕,就像上拉的功能,这个控件怎么实现?3q

**Comment by CoderMJLee** [comment]
MJRefresh并没有考虑支持这样的功能哦。我建议通过SVProgressHUD这样的HUD控件提醒用户加载完毕
