### ISSUE TITLE
上拉加载有点问题

### ISSUE THREAD

**Issue by tinoras** [CoderMJLee/MJRefresh#246]
tableView.footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(XHloadMoreData)];
    __weak typeof(self) ctl = self;
    tableView.footer = [MJRefreshAutoFooter footerWithRefreshingBlock:^{
        [ctl XHloadMoreData];
    }];

在我的应用中，这两个方法在进行两次加载更多后，就不再触发，XHloadMoreData 该方法仅仅只是一个网络请求方法，不用理会。目前定位具体是哪里出了问题，可以查查看

**Comment by CoderMJLee** [comment]
但从这个代码，看不出问题哦。最好贴出XHloadMoreData看下哈。或者发个Demo？

**Comment by zyvv** [comment]
tableView的数据是空的的时候，是无法触发上拉加载的。看你是不是这个问题～

**Comment by CoderMJLee** [comment]
@zyvv 默认情况下，没有数据时，footer是默认隐藏的。如果你希望一直出来，可以设置：
```objc
footer.automaticallyHidden = NO;
```

**Comment by SunshineOMT** [comment]
我也出现了相同的问题,请MJ老师看一下.

**Comment by SunshineOMT** [comment]
第二次上拉的时候,就不再触发tableView.footer = [MJRefreshAutoFooter footerWithRefreshingBlock:^{ }];
里的回调方法,请MJ老师看一下.

**Comment by zhengbuqian** [comment]
@CoderMJLee 您好，我今天也遇到了这个问题。
```
self.mjFooterView = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{[self startRetriveData];}];
self.tableView.tableFooterView = self.mjFooterView;
```
`startRetriveData`的第一行是一个`NSLog(@"startRetriveData");`，前两次刷新都可以正常的刷新数据并且打印；刷新两次之后，第三次拉到底，footer一直显示正在加载，但是这行`NSLog`语句都没有执行，也就没有更新数据了。

**Comment by tinoras** [comment]
很抱歉现在才回复。我详细讲一下具体问题吧。情况就和上面@zhengbuqian 的问题类似，感觉好像是触发条件有点问题，在网络都正常的情况下，前两次上滑加载更多，回调能被正常启用，但是再次上滑后，加载更多的回调(footerWithRefreshingBlock)里面，自定义加载方法没被调用，怎么滑动都无法触发回调。

**Comment by xiaoxiongke** [comment]
同样，杰哥 现在出现第三次上拉刷新 就不调用上拉刷新方法了。。。。

**Comment by xiaoxiongke** [comment]
现在好了。发现调用的不是MJRefreshAutoNormalFooter 这个类。。。用这个就好了。

**Comment by xiaoxiongke** [comment]
需要添加tableView.mj_footer endRefreshing 结束刷新一次，不然footer总是正在卷菊花，而且不调用上啦刷新方法

**Comment by CoderMJLee** [comment]
@xiaoxiongke 服务器的数据回来，结束了，肯定要调用endRefreshing方法的，不然它怎么知道你的数据什么时候刷新完毕

**Comment by xiaoxiongke** [comment]
@CoderMJLee 嗯嗯 是的，开始看的好几个人也出现这样的情况 只能加载两次，然后上拉就失效了  问题就出在这里。  非常感谢啦~~对啦 顺便问一下 杰哥，现在iOS大神班视频有没有出，一路跟随你的视频教程来的~！还有有您的qq群吗？

**Comment by yao23** [comment]
_collectionView.footer.hidden = YES; 
    [_collectionView.footer endRefreshing];

I removed the first line which prevents loading more, then it works well
