### ISSUE TITLE
MJ哥 我遇到一点问题 关于 MJRefresh 和 dealloc

### ISSUE THREAD

**Issue by qiang437587687** [CoderMJLee/MJRefresh#248]
下面这个原因是说我还没有释放观察者 就dealloc 了??  后来找到  [_tableView removeHeader]; 这个方法才解决了 ,,  在这其实也就是想问问 每一个添加了 MJRefresh  Controller 如果要销毁都需要  [_tableView removeHeader]; 这个方法吗????

An instance 0x15ca78000 of class UITableView was deallocated while key value observers were still registered with it. Current observation info:  (
 Context: 0x0, Property: 0x170442640>
)
(null)
(
	0   CoreFoundation                      0x00000001854a42f4  + 160
	1   libobjc.A.dylib                     0x0000000196cc80e4 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001854a4218  + 0
	3   Foundation                          0x0000000186329810  + 340
	4   CoreFoundation                      0x0000000185381458 CFRelease + 524
	5   CoreFoundation                      0x000000018538da18  + 152
	6   libobjc.A.dylib                     0x0000000196ce1724  + 564
	7   CoreFoundation                      0x0000000185385074 _CFAutoreleasePoolPop + 28
	8   CoreFoundation                      0x00000001854598a8  + 1500
	9   CoreFoundation                      0x00000001853852d4 CFRunLoopRunSpecific + 396
	10  GraphicsServices                    0x000000018eb9b6fc GSEventRunModal + 168
	11  UIKit                               0x0000000189f4afac UIApplicationMain + 1488
	12  NursingWorkers                      0x100153af8 main + 124
	13  libdyld.dylib                       0x0000000197346a08  + 4
)

dSYM UUID: 0EDD2BE3-D895-3F63-A645-F364756C6EE9
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: NursingWorkers
Base Address: 0x000000010003c000

**Comment by CoderMJLee** [comment]
Sorry哈，这是MJRefresh1.0版本遗留的一个不稳定的问题，目前在2.0版本中已经完美解决了哈。你可以试着使用2.0版本。但是2.0版本的接口跟1.0的接口有点差别哈

**Comment by qiang437587687** [comment]
MJ哥..如果是替换有点来不及（项目马上上线...）那用 「tableview removeHeader」 能避免这个问题吗？
                                                   先谢了.MJ哥.


发自网易邮箱大师
在2015年08月12日 15:47，M了个J 写道:

Closed #248.
