### ISSUE TITLE
可不可以不显示最后更新时间？

### ISSUE THREAD

**Issue by heyehao2008** [CoderMJLee/MJRefresh#25]
MJ老师您好！
库中提供了这两个方法：
- (void)addHeaderWithCallback:(void (^)())callback;
- (void)addHeaderWithCallback:(void (^)())callback dateKey:(NSString*)dateKey;
先以为第一个方法不会显示时间，第二个会显示更新时间。但却是两个都要显示更新时间。有没有方法可以设置不显示更新时间呢？

还有，MJ老师，这个除了可以自定义刷新时的文字，还可以自定义刷新时的headerView么？比如像SVPullToRefresh一样有这样的方法：
[scrollView.pullToRefreshView setCustomView:label2 forState:SVPullToRefreshStateTriggered];
[scrollView.pullToRefreshView setCustomView:label3 forState:SVPullToRefreshStateLoading];
[scrollView.pullToRefreshView setCustomView:label1 forState:SVPullToRefreshStateStopped];
这个刷新库用起来非常方便，就是可自定义的东西比较少，持续关注

**Comment by CoderMJLee** [comment]
已经全新升级，提供了很多自定义手段哈。如果要隐藏更新时间，可以这样：
self.tableView.header.updatedTimeHidden = YES;
