### ISSUE TITLE
使用中发现了一个bug

### ISSUE THREAD

**Issue by loumzy** [CoderMJLee/MJRefresh#251]
// 集成下拉刷新控件
- (void)setHeaderRefresh
{
    // 1.下拉刷新(进入刷新状态就会调用self的headerRereshing)
    self.tableView.header = [MJRefreshNormalHeader headerWithRefreshingTarget:self refreshingAction:@selector(headerRereshing)];
    
}

//集成上拉刷新控件
- (void)setFooterRefresh
{
    // 上拉加载更多(进入刷新状态就会调用self的footerRereshing)
    self.tableView.footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(footerRereshing)];
    
}

-------------------------------问题-----------------------------------------------------
使用时，上拉刷新后，再下拉刷新，反复上拉下拉刷新多次，contentsize高度都会变窄，最后只是屏幕的高度，虽然内容是高度是高于屏幕的

**Comment by CoderMJLee** [comment]
没有遇到这样的情况哦。可以发个Demo看看么？3Q

**Comment by loumzy** [comment]
我做了个demo好像没有这个问题了，我再研究研究吧，O(∩_∩)O谢谢

**Comment by CoderMJLee** [comment]
有问题的话再跟我说一下哈
