### ISSUE TITLE
一个崩溃bug 

### ISSUE THREAD

**Issue by 643824979** [CoderMJLee/MJRefresh#252]
崩在 [self deallocSwizzle] 上面  注释了这句话就OK了  
不知道有没有其他影响

请问MJRefresh的版本号在哪看  找了半天没有发现 

麻烦了 谢谢

**Comment by 643824979** [comment]
在iOS 8.0 一下概率比较大  大于等于 8.0 暂时没有发现 谢谢

**Comment by CoderMJLee** [comment]
这是2.0版本之前残留的问题哈。最新的2.0版本开始就没问题了哈。不过2.0和1.0版本接口有点差异哈
