### ISSUE TITLE
请问在IOS7遇到这样的情况怎么解？

### ISSUE THREAD

**Issue by zhangjianqianger** [CoderMJLee/MJRefresh#256]
![snip20150807_151](https://cloud.githubusercontent.com/assets/10346165/9134374/17376c86-3d36-11e5-860b-a9423fef58e3.png)
![snip20150807_152](https://cloud.githubusercontent.com/assets/10346165/9134395/3a76c250-3d36-11e5-9a02-e56d0654f9b4.png)

**Comment by zhangjianqianger** [comment]
偶尔会卡最后更新那里  然后tab往下拽动后就这样子了

**Comment by CoderMJLee** [comment]
你这个是使用了UINavigationController并且隐藏了UINavigationBar么？
