### ISSUE TITLE
a bug in the version of that was published in 2015.08.08

### ISSUE THREAD

**Issue by llh2010** [CoderMJLee/MJRefresh#258]
i am using the UICollectionView with its private header(not MJRefresh header) that i want to show the advertisement, and make the footer using MJRefreshBackNormalFooter,but in the new version,the footer have not showed when pull up to refresh. However it can be showed at the bottom of UICollectionView that without its private header.
what is more,the old version work without bug for that situation.

**Comment by CoderMJLee** [comment]
Thanks for your using and issue.The latest MJRefreshFooter is automatically hidden when the count of data is 0.If you want to disable this function, you can set property like 'footer.automaticallyHidden = NO'.
