### ISSUE TITLE
自己根据您的demo改写了上拉加载的方式,  但是出现了一个bug解决不了 我能把源码发您,帮我看一下么

### ISSUE THREAD

**Issue by Aster0id** [CoderMJLee/MJRefresh#26]
MJ老师您好 我今天看您做的这个控件. 我根据这个改写了上拉加载的方式,无网情况下显示重新加载的按钮, 这些都弄好了 就是有个一Bug, 我知道问题发生什么位置 不知道怎么改或者改哪个属性 您能帮我看看么?

**Comment by CoderMJLee** [comment]
现在看看最新的框架能不能满足你的要求？

**Comment by heistings** [comment]
这个问题解决了吗？
