### ISSUE TITLE
上拉刷新

### ISSUE THREAD

**Issue by KunHuiChang** [CoderMJLee/MJRefresh#260]
你好我在代码中加入上拉刷新有些画面会出现但有但有些画面却没有出现请问是什么问题呢？

谢谢

**Comment by CoderMJLee** [comment]
1.最新版本的footer控件，当没有数据时，默认是自动隐藏的；有数据时会自动显示
2.也可能是因为类名用错了，比如用了MJRefreshFooter、MJRefreshAutoFooter等，应该要用MJRefreshAutoNormalFooter这些子类

**Comment by KunHuiChang** [comment]
好的，我来试看看
谢谢你
