### ISSUE TITLE
更新后的MJRefresh上拉加载更多没有了

### ISSUE THREAD

**Issue by MuZiLee** [CoderMJLee/MJRefresh#261]
为什么新版本调用[self.tableView setHidden:NO];之后上拉加载就没有了?
李老师,怎么每次更新更版本都有一些别的问题?我搞了很久才找到原因.最终于我还是换成旧版本.
李老师啊,都2.4.3版本了,加油吧

**Comment by CoderMJLee** [comment]
为了适应大部分需求，新版本增加了个新功能，自动根据数据量来显示和隐藏Footer，如果你不希望拥有这个功能：
```objc
self.tableView.footer.automaticallyHidden = NO;
```

**Comment by Ryannnnnnn** [comment]
刚好也碰到这个问题了，果然有人问。。
