### ISSUE TITLE
提示文字重叠

### ISSUE THREAD

**Issue by allanzhang** [CoderMJLee/MJRefresh#262]
UITableView 用了自动布局后，上下拉的时候，提示字经常重叠，不知道和自动布局有没有关系。
每次改变状态的时候，self.statusLabel.text = @""；也没有用，何解？

**Comment by CoderMJLee** [comment]
这种修改是没用的，stateLabel是分状态的，你要多看看README哈：
```objc
[self.tableView.header setTitle:@"4444" forState:....];
```

**Comment by hgshh** [comment]
我也遇到了提示文字重叠 ，是iOS10的问题 ，要设置UILable的backgroundColor , 不要设置为nil ，也不可以设置为 clearColor 。我设置为 whiteColor之后 ，就正常了
