### ISSUE TITLE
初始状态 cell count = 0， 在远程获取数据之后，reloadData情况下没有上拉加载更多

### ISSUE THREAD

**Issue by zfha** [CoderMJLee/MJRefresh#264]
我的应用情况：
1、在初始加载TableView的时候，数据源 NSArray count = 0
2、然后远程获取数据，获取数据后， tableView reloadData, 这种情况下 “上拉加载更多” 没有。

我现在猥琐解决：
1、我尝试了下，初始状态如果count = 1， 按上面的步骤，获取数据，reload后，有上拉加载更多。
2、因此，我现在初始不加载tableView，在第一次拉取到数据后，再 addSubView: tableView。

看看什么原因。。

**Comment by CoderMJLee** [comment]
Sorry哈，是有个问题我没有测试完整。你试试最新2.4.4版本

**Comment by zfha** [comment]
OK, 测试了下，问题已解决

**Comment by CoderMJLee** [comment]
好的，解决了就好哈
