### ISSUE TITLE
上拉刷新问题

### ISSUE THREAD

**Issue by wasonxie** [CoderMJLee/MJRefresh#265]
我在viewDidLoad中使用collectionView?.header.beginRefreshing()这个进入页面就开始刷新加载数据
但上拉加载就不能用了

self.collectionView?.footer = MJRefreshAutoNormalFooter(refreshingTarget: self, refreshingAction: "footerRefresh") 这个方法就不执行了

如果在viewDidLoad，调用加载数据的方法，不用collectionView?.header.beginRefreshing()，上拉加载就可以用了，这是什么原因？

**Comment by CoderMJLee** [comment]
可以截一段稍微完整的使用代码看看么？

**Comment by wasonxie** [comment]
下面我在viewdidload里注释了loadData(),使用了self.collectionView?.header.endRefreshing()，下拉加载就不行了，如果使用loadData(),不用self.collectionView?.header.endRefreshing()就可以
class SceneListCollectionViewController: UICollectionViewController,UICollectionViewDelegateFlowLayout {
    
    let reuseIdentifier = "Cell"
    let reuseLoadingIdentifer = "loading"
    var objectArray = [SceneObj]()
    var stringArray = [String]()
    var i = 0
    var cellHeight = UIScreen.mainScreen().bounds.height*266/568
    var currentPage = 1
    var keyWord = ""
    var scenes = [SceneObj]()
    
    override func viewDidLoad() {
        super.viewDidLoad()
//        loadData()
        
        self.collectionView?.dataSource = self
        self.collectionView?.delegate = self
        
        self.collectionView!.registerClass(SceneCollectionView.classForCoder(), forCellWithReuseIdentifier: reuseIdentifier)
        
        self.collectionView?.header = MJRefreshNormalHeader(refreshingTarget: self, refreshingAction: "headerRefresh")
        self.collectionView?.footer = MJRefreshAutoNormalFooter(refreshingTarget: self, refreshingAction: "footerRefresh")
        self.collectionView?.header.beginRefreshing()
        
    }
    
    func loadData(){
        for i; i < 10 ; i++ {
            var sceneObj:SceneObj = SceneObj(browse: i, name: "新场景\(i)", nick: "wason")
            self.objectArray.append(sceneObj)
        }
    }
    
    func footerRefresh(){
        self.Delay(2, closure: { () -> () in
            var j = self.i + 10
            for self.i;self.i<j;self.i++ {
                var sceneObj:SceneObj = SceneObj(browse: self.i, name: "新场景\(self.i)", nick: "wason")
                self.objectArray.append(sceneObj)
            }
            dispatch_async(dispatch_get_main_queue(), { () -> Void in
                self.collectionView?.reloadData()
            })
            self.collectionView!.footer.endRefreshing()
        })
    }
    
    func headerRefresh(){
        self.Delay(2, closure: { () -> () in
            self.objectArray.removeAll(keepCapacity: false)
            self.i = 0
            for self.i;self.i < 10;self.i++ {
                var sceneObj:SceneObj = SceneObj(browse: self.i, name: "新场景\(self.i)", nick: "wason")
                self.objectArray.append(sceneObj)
            }
            
            dispatch_async(dispatch_get_main_queue(), { () -> Void in
                self.collectionView?.reloadData()
            })
            self.collectionView?.header.endRefreshing()
        })
    }
    
    func Delay(time:Double,closure:()->()){
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, Int64(time * Double(NSEC_PER_SEC))), dispatch_get_main_queue(), closure)
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    override func numberOfSectionsInCollectionView(collectionView: UICollectionView) -> Int {
        return 1
    }
    
    
    override func collectionView(collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return objectArray.count
    }
    
    override func collectionView(collectionView: UICollectionView, cellForItemAtIndexPath indexPath: NSIndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCellWithReuseIdentifier(reuseIdentifier, forIndexPath: indexPath) as! SceneCollectionView
        let rowData = objectArray[indexPath.row]
        cell.imageView.image = UIImage(named: "BG.png")
        cell.sceneName.text = "场景\(rowData.name)"
        cell.authorNameLabel.text = "\(rowData.nick)"
        cell.backgroundColor = UIColor(red: (CGFloat(arc4random_uniform(256)))/255.0, green: (CGFloat(arc4random_uniform(256)))/255.0, blue: (CGFloat(arc4random_uniform(256)))/255.0, alpha: 1)
        
        return cell
    }
    
    func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: NSIndexPath) -> CGSize {
        return CGSize(width: collectionView.frame.width, height: cellHeight)
    }
    
    func collectionView(collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAtIndex section: Int) -> UIEdgeInsets {
        return UIEdgeInsetsMake(0, 0, 0, 0)
    }
    
}

class SceneCollectionView: UICollectionViewCell {
    let imageView = UIImageView()
    let sceneName = UILabel()
    let createTime = UILabel()
    let collectBtn = UIButton()
    let collectLabel = UILabel()
    let favourBtn = UIButton()
    let favourLabel = UILabel()
    let authorImg = UIImageView()
    let authorNameLabel = UILabel()
    
    required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        
        var cellWidth = frame.width
        var cellHeight = frame.height
        
        imageView.frame = CGRectMake(0, 0, frame.width, frame.height-50)
        self.addSubview(imageView)
        
        sceneName.frame = CGRectMake(10, CGFloat(frame.height-45), CGFloat(frame.width - 150), 25)
        sceneName.font = UIFont.systemFontOfSize(15)
        sceneName.textColor = UIColor.blackColor()
        sceneName.text = "xxx"
        self.addSubview(sceneName)
        
        createTime.frame = CGRectMake(11, CGFloat(frame.height-25), CGFloat(frame.width/3), 25)
        createTime.textColor = UIColor.grayColor()
        createTime.font = UIFont.systemFontOfSize(10)
        createTime.text = "1年前"
        self.addSubview(createTime)
        
        collectBtn.frame = CGRectMake(CGFloat(frame.width - 130), CGFloat(frame.height-40), 22, 22)
        collectBtn.setBackgroundImage(UIImage(named: "chooseClick"), forState: .Normal)
        self.addSubview(collectBtn)
        
        collectLabel.frame = CGRectMake(CGFloat(cellWidth - 130), CGFloat(cellHeight-20), 22, 22)
        collectLabel.textAlignment = NSTextAlignment.Center
        collectLabel.font = UIFont.systemFontOfSize(14)
        collectLabel.textColor = UIColor.grayColor()
        collectLabel.text = "24"
        self.addSubview(collectLabel)
        
        //收
        favourBtn.frame = CGRectMake(CGFloat(cellWidth - 90), CGFloat(cellHeight-40), 22, 22)
        favourBtn.setBackgroundImage(UIImage(named: "praiseClick"), forState: .Normal)
        self.addSubview(favourBtn)
        
        favourLabel.frame = CGRectMake(CGFloat(cellWidth - 90), CGFloat(cellHeight-20), 22, 22)
        favourLabel.textAlignment = NSTextAlignment.Center
        favourLabel.font = UIFont.systemFontOfSize(14)
        favourLabel.textColor = UIColor.grayColor()
        favourLabel.text = "8"
        self.addSubview(favourLabel)
        
        authorImg.frame = CGRectMake(CGFloat(cellWidth - 50), CGFloat(cellHeight - 70), 40, 40)
        authorImg.image = UIImage(named: "nohead")
        authorImg.clipsToBounds = true
        authorImg.layer.cornerRadius = 20
        self.addSubview(authorImg)
        
        authorNameLabel.frame = CGRectMake(CGFloat(cellWidth - 60), CGFloat(cellHeight - 25), 60, 30)
        authorNameLabel.font = UIFont.systemFontOfSize(14)
        authorNameLabel.adjustsFontSizeToFitWidth = true
        authorNameLabel.textColor = UIColor.grayColor()
        authorNameLabel.textAlignment = NSTextAlignment.Center
        authorNameLabel.text = "wason"
        self.addSubview(authorNameLabel)
        
    }
}

class SceneCollectionViewLoadingCell: UICollectionReusableView {
    let spinner = UIActivityIndicatorView(activityIndicatorStyle: UIActivityIndicatorViewStyle.WhiteLarge)
    
    required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        
        spinner.startAnimating()
        spinner.center = self.center
        addSubview(spinner)
    }
}

**Comment by wasonxie** [comment]
想问下，什么原因会导致上拉加载不能用
因为我在本地做demo的时候，发现如果是自己造的数据，上拉加载可以用，就是上面那情况
如果是从网络中获取的数据，上拉加载也用不了。

**Comment by CoderMJLee** [comment]
pod repo update，试试更新2.4.4版本

**Comment by wasonxie** [comment]
不好意思，回复晚了。更新了2.4.4版本，下拉还是不能刷新。

**Comment by CoderMJLee** [comment]
有Demo发过来看看么？这样最方便解决哈

**Comment by wasonxie** [comment]
好的。你稍等，我整理个Demo发给你

**Comment by imWildCat** [comment]
![image](https://cloud.githubusercontent.com/assets/2396817/9241564/e88c03f8-41a7-11e5-9e02-dde3333d6b00.png)
借楼问下，上拉加载更多 错位，怎么办

**Comment by wasonxie** [comment]
MJLee,Demo发你邮箱了，请查收！谢谢！

**Comment by Coder-Leo** [comment]
期待同样的答案。谢谢。

**Comment by CoderMJLee** [comment]
@wasonxie 你指的是footer控件看不见么？因为从2.4.1版本开始，我会自动根据数据量来显示和隐藏footer控件。比如数据量为0，会隐藏footer控件，数据量不为0，会显示footer控件。如果你不希望拥有这个功能，希望自己去控制footer的显示和隐藏，可以加上这段代码
```objc
self.collectionView?.footer.automaticallyHidden = false
```

**Comment by CoderMJLee** [comment]
@Coder-Leo 你试过最新版了么？2.4.4版本？如果还有问题的话，希望能发个Demo到邮箱哈，谢谢

**Comment by Coder-Leo** [comment]
我用的是tableview，header没有问题，但是footer就看不到业务刷新，您说的方案我试过了，无效。请问有没有其他的解决可能性？

发自我的 iPhone

**Comment by CoderMJLee** [comment]
@Coder-Leo 是不是最新的2.4.4版本？

**Comment by Coder-Leo** [comment]
@CoderMJLee 升级2.4.4后问题解决。谢谢。

**Comment by wasonxie** [comment]
@CoderMJLee 我用self.collectionView?.footer.automaticallyHidden = false成功地上拉加载数据了。不过这样进入页面的时候会出现stateLabel的文字，我把stateLabel设为空，然后header.beginRefreshing()加载数据就好了。谢谢！MJRefresh很强大，还有很多功能有待研究。谢谢！

**Comment by KunHuiChang** [comment]
更新最新版本后，原本footer没出现的问题解决了，
变成tableView.footer.hidden = YES 无法隐藏了呢？
请问为什么呢？谢谢

**Comment by CoderMJLee** [comment]
谢谢。解决了就好

**Comment by yao23** [comment]
比起self.collectionView?.footer.automaticallyHidden = false，如果能提供个新接口，参数是uicollectionview每页显示的个数，当总个数小于这个数时就自动隐藏footer（而非只有为零的时候，因为个数不满一页自然不需要加载更多）

**Comment by huiyumiao** [comment]
杰哥，上拉刷新时，如果网络加载未完成（self.tableView.mj_footer 没有执行endRefresh），还能继续上拉刷新吗？

**Comment by wumeijun** [comment]
@CoderMJLee       执行endRefreshing()的时候collectionView会变透明，再出现的时候collectionView回到起始位置 ，我的版本是'MJRefresh', '~> 3.1.10'
 homeView.collectionView.mj_header = MJRefreshNormalHeader(refreshingBlock: { _ in
            self.design.doReload()
        })

 homeView.collectionView.mj_header.endRefreshing()

**Comment by wumeijun** [comment]
[1.zip](https://github.com/CoderMJLee/MJRefresh/files/385400/1.zip)
你好，这是我遇到问题的文件
