### ISSUE TITLE
正在刷新时，下滑，section的headView错位

### ISSUE THREAD

**Issue by ShrinkLynn** [CoderMJLee/MJRefresh#266]
![ios simulator screen shot 2015 8 12 4 15 34](https://cloud.githubusercontent.com/assets/7589500/9219439/80f8c4b4-410d-11e5-83d3-e13867e14364.png)

用的就是提供的demo。。

**Comment by allabttony** [comment]
我也有这个问题！

**Comment by lexiaoyao20** [comment]
有同样问题的飘过。。

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈

**Comment by xdream86** [comment]
![simulator screen shot jul 26 2016 3 56 42 pm](https://cloud.githubusercontent.com/assets/1835487/17130153/a90e3a0c-5349-11e6-9af1-3602601afb2f.png)
 最新版本依然这样
