### ISSUE TITLE
[2.4.7] [MJRefreshAutoNormalFooter footerWithRefreshingTarget: refreshingAction:] 产生的 footer 错位

### ISSUE THREAD

**Issue by imWildCat** [CoderMJLee/MJRefresh#268]
版本: 2.4.7  
Xcode version:  6.4 (6E35b)  
iOS: 8.4  

```objective-c
self.tableView.footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreData)];
```
的效果：
![image](https://cloud.githubusercontent.com/assets/2396817/9288350/eddb8634-4374-11e5-9c2b-802c8013c526.png)

```objective-c
self.tableView.footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
   // ...
}];
```
的效果：

![image](https://cloud.githubusercontent.com/assets/2396817/9288354/2e8ae9a4-4375-11e5-924d-4788a8ffcd3c.png)

**Comment by CoderMJLee** [comment]
footerWithRefreshingTarget:refreshingAction:和footerWithRefreshingBlock:的效果不一致？

**Comment by imWildCat** [comment]
@CoderMJLee 很显然不一致，做了几次修改测试，bug 有重现。

**Comment by CoderMJLee** [comment]
@imWildCat 能发个有这种问题的Demo么？谢谢哈。我这边无法重现这个问题
