### ISSUE TITLE
使用 MJRefreshAutoNormalFooter 并修改 title 时出现问题

### ISSUE THREAD

**Issue by EggmanQi** [CoderMJLee/MJRefresh#269]
> MJRefreshAutoNormalFooter *footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self
                                                                             refreshingAction:@selector(sthMethod)];
>[footer setTitle:@"这里" forState:MJRefreshStateNoMoreData];

然后报错：

  >  Reference to 'MJRefreshStateNoMoreData' is ambiguous

**Comment by CoderMJLee** [comment]
你下载最新的MJRefresh 2.4.7试试？我暂时没遇到这样的问题哦。或者可以发个Demo看看么？谢谢

**Comment by NSKevin** [comment]
@EggmanQi 可能是头文件引用问题
#import <MJRefresh/MJRefresh.h>
这样引用，不要#improt "MJRefresh.h"

**Comment by yangmiemie1116** [comment]
@NSKevin 说的对
