### ISSUE TITLE
自定义gif下拉刷新控件的图片位置不对

### ISSUE THREAD

**Issue by qazwyw** [CoderMJLee/MJRefresh#270]
图片没有挨着状态文字，而是左对齐

**Comment by CoderMJLee** [comment]
可以给个效果截图看看么？或者发个Demo给我看看哈。谢谢

**Comment by qazwyw** [comment]
iPhone6上的截图:(iPhone6上位置的错误还不是很明显)
![eae137fc-50bb-4823-908a-884c8793c0d9](https://cloud.githubusercontent.com/assets/9583838/9434512/5ed73622-4a72-11e5-9058-e8e2ea912e11.png)

iPhone4s上的截图:(iPhone4s上位置的错误就很明显了)
![a80d592e-16bc-4565-97dc-b6922313dc4e](https://cloud.githubusercontent.com/assets/9583838/9434560/df937cbc-4a72-11e5-85d6-d2a3260089d1.png)

**Comment by yangfeiyu** [comment]
我也遇到了这个问题。
