### ISSUE TITLE
MJ哥

### ISSUE THREAD

**Issue by tubie** [CoderMJLee/MJRefresh#273]
我这边用的是普通模式上啦刷新会有一个小条子在tableView下面，而且这个小条子和tableViewFootView的高度一样。这个小条子怎么去掉？

**Comment by CoderMJLee** [comment]
把你使用MJRefresh的代码、还有最终的效果截图提供一下哈，谢谢

**Comment by tubie** [comment]
![Uploading 屏幕快照 2015-08-19 10.46.40.png…]()

代码如下：
  NSString *sign = [[GetUrl shareUrl]getSign];
    NSString *userName =[[NSUserDefaults standardUserDefaults]objectForKey:@"userName"];
    NSString *timeStr = [[GetUrl shareUrl]getTimeStr];
    NSString *urlString = [NSString stringWithFormat:@"%@AppApi/is_agents_order/client_type/ios/q/%@/u/%@/t/%@/%ld/", kURL,  sign, userName, timeStr,(long)loadMoreDataNum];
    [Common sendGetURL:urlString withParams:nil success:^(id responseObj) {
        
        if ([responseObj [@"status"]integerValue]==1) {
            loadMoreDataNum ++;
            NSArray *dictArray =  responseObj [@"info"];
            NSMutableArray *sendOrderArray = [NSMutableArray array];
            for (NSDictionary *dic  in dictArray) {
                
                OrderModel *orderM = [OrderModel sendOrderWithDict:dic];
                [sendOrderArray addObject:orderM];
                
            }
            self.orderArray = sendOrderArray;
            [self.tabeView reloadData];
            [self.tabeView.footer endRefreshing];
            
            
            DLog(@"%@", self.orderArray);
            DLog(@"%@", dictArray);
        }else{
            [self initStateView];
            
        }
    } failure:^(NSError *error) {
        DLog(@"%@", error);
        [Common hideHud:self.view animated:YES];
    }];
