### ISSUE TITLE
小码哥，这个footer和header能不能在“不可用”和“可用”中切换？

### ISSUE THREAD

**Issue by angelen10** [CoderMJLee/MJRefresh#275]
因为我的TableView上面有一个SearchBar，显示普通列表和显示搜索结果列表我都是使用同一个TableView，因此，我想能不能在显示普通列表的时候，footer和header是可用的；在显示搜索结果的时候，footer和header是不可用的。我代码如下，程序会死掉：
我实现了UISearchBarDelegate的两个方法：
```java
func searchBarShouldBeginEditing(searchBar: UISearchBar) -> Bool {
        println("-------------开始搜索")
        self.mTableView.header.hidden = true
        self.mTableView.footer.hidden = true
        return true
    }
    
    func searchBarCancelButtonClicked(searchBar: UISearchBar) {
        println("-------------结束搜索")
        self.mTableView.header.hidden = false
        self.mTableView.footer.hidden = false
    }
```
发现header的确可以按照我的要求，在搜索页面的时候隐藏掉了；但是footer却没有隐藏掉，这header和footer都是继承UIView的呀，为什么会不行的呢？

**Comment by CoderMJLee** [comment]
我刚才测试了，没有崩溃哦。你能将有问题的代码发给我看看么？

**Comment by angelen10** [comment]
喔，后来我测试了的确没有崩溃了，但是我想问footer却没有隐藏掉，而header却可以隐藏掉的呢？
我上面的代码是无法实现我要的效果

**Comment by CoderMJLee** [comment]
你加个footer.automaticallHidden = NO试试

**Comment by angelen10** [comment]
好的，可以了，谢谢
