### ISSUE TITLE
self.table.foot.hidden = Yes;不能关闭

### ISSUE THREAD

**Issue by jsaonpeng** [CoderMJLee/MJRefresh#278]

**Comment by jsaonpeng** [comment]
2.4.0版本self.table.foot.hidden = yes,就可以关闭上拉加载。2.4.0以后的版本都不行了，我下载了你github的工程，我看你也是self.table.foot.hidden = yes，可以隐藏。真是纳闷了

**Comment by CoderMJLee** [comment]
可能是代码顺序的问题，你可以尝试在reloadData后调用hidden = YES;

**Comment by jsaonpeng** [comment]
你看看能不能抽個時間改一下代碼或備註一下

**Comment by jiangyancong** [comment]
@CoderMJLee 
我们以前的版本不存在这种依赖关系，使用一直正常，最近更新了MJ，发现大量页面在下拉刷新的时候存在问题。foot一直没有办法hidden。只有先reload再hidden才可以。

请问能不能不依赖reloadData的调用顺序。目前大量代码都是先调用self.table.foot.hidden = yes，再做reloadData，如果跟reloadData的调用顺序存在依赖，代码review和修改量比较大，之后维护的人员写新代码也容易出错。

十分感谢！

**Comment by CoderMJLee** [comment]
那就加一句代码关掉自动显示和隐藏的功能哈
```objc
self.tableView.footer.automaticallyHidden = NO;
```

**Comment by jiangyancong** [comment]
谢谢！解决了我们燃眉之急！@CoderMJLee
