### ISSUE TITLE
回调方法错误

### ISSUE THREAD

**Issue by Guicai-Li** [CoderMJLee/MJRefresh#28]
objc_msgSend(msgTarget(self.beginRefreshingTaget, self.beginRefreshingAction, self);

原因：
Too many arguments to function call, expected0, have3.

**Comment by datouyu123** [comment]
http://www.cnblogs.com/ygm900/p/4105282.html

**Comment by CoderMJLee** [comment]
这个问题好久以前就修复了哈，使用最新的代码就没问题了
