### ISSUE TITLE
真机调试崩溃

### ISSUE THREAD

**Issue by Jasonbroker** [CoderMJLee/MJRefresh#280]
MJ 你好！

上报一个bug。

环境： osx 10.10mac mini Xcode 6.4
 iPhone6 iOS 8.4 

模拟器 Debug, 模式，第二次上啦加载更多崩溃。
模拟器release scheme下，不崩溃。

手机连接Xcode后，Debug模式，第二次上啦加载更多崩溃。
但是！断开手机与xcode连接，直接点击手机屏幕图标运行正常。

我试着自己获取offset来加载更多，发现也是崩溃。

怀疑是该框架运行时进行了某些属性的监听导致调试不能工作。

**Comment by CoderMJLee** [comment]
能否贴出详细的报错信息？谢谢
