### ISSUE TITLE
MJ老师，2.4.7版本出现了仅加footer无法自动刷新的bug

### ISSUE THREAD

**Issue by qazwyw** [CoderMJLee/MJRefresh#281]
项目需求在此模块中只需要上拉刷新框架，我是这样使用的:
在viewdidload方法中先添加了tableview，然后    
  MJRefreshAutoNormalFooter *footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self    refreshingAction:@selector(loadMoreData)];
    self.tableView.footer = footer;
    [self.tableView.footer beginRefreshing];
结果不调用loadMoreData的方法，无奈只能回滚回之前的版本，望能尽快修复哈。

**Comment by CoderMJLee** [comment]
为啥我这里可以调用呢。。。是不是没看到footer显示？

**Comment by qazwyw** [comment]
果然是这个问题。。。

**Comment by CoderMJLee** [comment]
好的，没有考虑周到，我以后会注意下哈
