### ISSUE TITLE
集成MJChiBaoZiHeader 的页面跳转其他页面的时候报错

### ISSUE THREAD

**Issue by cjckkk** [CoderMJLee/MJRefresh#282]
reason: 'An instance 0x7c3dce00 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7d6ed040> (
<NSKeyValueObservance 0x7d6ecfb0: Observer: 0x7b646c50, Key path: contentOffset, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x7b630950>
<NSKeyValueObservance 0x7d6ed000: Observer: 0x7b646c50, Key path: contentSize, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x7b630180>
)'

//这段代码注释 不报错 没事
    MJChiBaoZiHeader *header =[MJChiBaoZiHeader headerWithRefreshingTarget:self refreshingAction:@selector(loadNewData)];
    header.lastUpdatedTimeLabel.hidden = YES;
    header.stateLabel.hidden = YES;
    self.tableView.header = header;

**Comment by CoderMJLee** [comment]
那使用MJRefreshNormalHeader呢？

**Comment by cjckkk** [comment]
normal header 是没问题

**Comment by CoderMJLee** [comment]
能写个有问题的Demo看看么？3Q

**Comment by cjckkk** [comment]
//
//  chatTableViewController.m
//  bdhailiao
//
//  Created by cjc-mac on 15/8/7.
//  Copyright (c) 2015年 beidou. All rights reserved.
//

#import "chatViewController.h"
#import "define.h"
#import "contactsTool.h"
#import "contactsModel.h"
#import "messageTool.h"
#import "chaTableViewCell.h"
#import "chatToolbar.h"
#import "messageModel.h"
#import "NSString+Tools.h"
#import "contactsProfileTableViewController.h"
#import <CoreLocation/CoreLocation.h>
#import "contactProfile2TableViewController.h"
#import <AVFoundation/AVFoundation.h>
#import "MJRefresh.h"
#import "MJChiBaoZiHeader.h"


#define navH  self.navigationController.navigationBar.frame.size.height
#define statusH  [[UIApplication sharedApplication] statusBarFrame].size.height
#define scW [UIScreen mainScreen].bounds.size.width

@interface chatViewController ()<UITextViewDelegate,UITableViewDataSource,UITableViewDataSource,CLLocationManagerDelegate>
@property (weak, nonatomic) IBOutlet NSLayoutConstraint *inputH;

- (IBAction)backTApped:(id)sender;
@property (strong, nonatomic) NSMutableArray *messageArray;
@property (nonatomic, assign) SystemSoundID soundID;

/**
 *  tool botton constrains
 */
@property (weak, nonatomic) IBOutlet NSLayoutConstraint *toolbarBottom;
@property (weak, nonatomic) IBOutlet UITableView *tableView;
//@property (weak, nonatomic) IBOutlet toolbar *toolbar;
@property (weak, nonatomic) IBOutlet chatToolbar *toolbar;
@property (copy, nonatomic) NSString *meslocationWithNoformat;
@property (assign, nonatomic) NSInteger maxC;
@property (assign, nonatomic) int page;




/**
 *  定位管理者
 */
@property (nonatomic ,strong) CLLocationManager *mgr;

@end

@implementation chatViewController



- (void)viewDidLoad {
    [super viewDidLoad];
    
    // notification
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillChangeFrame:) name:UIKeyboardWillChangeFrameNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(reloadMes:) name:@"reloadForDeleteMes" object:nil];
    
   //tableview
    self.tableView.allowsSelection = NO;
    self.tableView.separatorStyle= UITableViewCellSeparatorStyleNone;
    self.tableView.bounces = YES;
    self.tableView.delegate = self;
    self.tableView.dataSource = self;
   
    MJChiBaoZiHeader *header =[MJChiBaoZiHeader headerWithRefreshingTarget:self refreshingAction:@selector(loadNewData)];
    header.lastUpdatedTimeLabel.hidden = YES;
    header.stateLabel.hidden = YES;
    self.tableView.header = header;
    
    
    self.tableView.showsVerticalScrollIndicator = NO;
    
    UITapGestureRecognizer *tableViewGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(commentTableViewTouchInSide)];
    tableViewGesture.numberOfTapsRequired = 1;
    //todo
    tableViewGesture.cancelsTouchesInView = YES;
    [self.tableView addGestureRecognizer:tableViewGesture];

    //toolbar
    [self.toolbar.locationlbtn addTarget:self action:@selector(location:) forControlEvents:UIControlEventTouchUpInside];
    self.toolbar.input.delegate = self;
    self.toolbar.input.placeholder = [NSString stringWithFormat:@"发送至%@",[contactsTool getUserInfoById:self.userID].userPhone];
    [self.toolbar.signalbtn addTarget:self action:@selector(sendMes:) forControlEvents:UIControlEventTouchUpInside];
    self.toolbar.input.showsVerticalScrollIndicator = NO;
     // default
    NSMutableAttributedString *s = [[NSMutableAttributedString alloc]initWithString:[NSString stringWithFormat:@"你还可以输入31字数"]];
    [s addAttribute:NSForegroundColorAttributeName value:[UIColor redColor] range:NSMakeRange(6,2)];
    self.toolbar.countl.attributedText = s;
    self.page = 1;
    

    
    //加载数据
    [self refresh];
          //    //3. 自动上移
    //    //    //移动的位置
    if (self.messageArray.count >3 ) {
        NSIndexPath *path = [NSIndexPath indexPathForRow:self.messageArray.count -1 inSection:0];
        //    //    //真正去是位置 atSrcollPosition :  滚到位置
        [self.tableView scrollToRowAtIndexPath:path atScrollPosition:UITableViewScrollPositionBottom animated:YES];

    }
   

    
    //location
    self.mgr.delegate = self;
    
}

- (NSMutableArray *)messageArray
{
    if(!_messageArray)
       {
           
           self.messageArray = [[NSMutableArray alloc]init];
           
       }
    return _messageArray;
    
}

#pragma mark - CLLocationManagerDelegate click location btn action

- (void)locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray *)locations
{
    CLLocation *location = [locations lastObject];
    // 先纬度 再经度
    self.meslocationWithNoformat = [NSString stringWithFormat:@"%f,%f", location.coordinate.latitude ,location.coordinate.longitude];

    // 经纬度转成度分秒显示的格式
    //经
    int a =location.coordinate.longitude;
    int b = (location.coordinate.longitude - a)*60;
    float c = ((location.coordinate.longitude - a)*60 -b)*60;
    NSString *longitudeDFM = [NSString stringWithFormat:@"E%dº%d'%.2f\"",a ,b,c];
    //纬
    int i =location.coordinate.latitude;
    int j = (location.coordinate.latitude - i)*60;
    float k = ((location.coordinate.latitude - i)*60 -j )*60;
    NSString *latitudeDFM = [NSString stringWithFormat:@"N%dº%d'%.2f\"",i ,j,k];
    
    
    NSString *loc =[NSString stringWithFormat:@"位置(%@,%@)",longitudeDFM,latitudeDFM];
    
    [self.toolbar.locationlbtn setTitle:loc forState:UIControlStateSelected];
    [self.toolbar.locationlbtn setTitle:@"位置" forState:UIControlStateNormal];
    
    
}
/**
 *  unwind view
 *
 *  @param segue 
 */
-(IBAction)unwindseguetoContactProfileView :(UIStoryboardSegue *)segue{
    
}
#pragma mark - clloactionmanager懒加载
- (CLLocationManager *)mgr
{
    if (!_mgr) {
        _mgr = [[CLLocationManager alloc] init];
    }
    return _mgr;
}


- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status
{
   
    
    if (status == kCLAuthorizationStatusNotDetermined) {
        NSLog(@"等待用户授权");
    }else
        if (status == kCLAuthorizationStatusAuthorizedAlways ||
              status == kCLAuthorizationStatusAuthorizedWhenInUse)
        
    {
        NSLog(@"授权成功");
        // 开始定位
        [self.mgr startUpdatingLocation];
        
    }else
    {
        NSLog(@"授权失败");
    }
}
-(void)location:(UIButton *)btn
{
   
    btn.selected = ! btn.selected;
    [self IslocSelAndBeyondText];
    
    
    // 判断是否是iOS8
    if([[UIDevice currentDevice].systemVersion doubleValue] >= 8.0)
    {
        NSLog(@"是iOS8");
        // 主动要求用户对我们的程序授权, 授权状态改变就会通知代理
        //
        [self.mgr requestAlwaysAuthorization]; // 请求前台和后台定位权限
//                [self.mgr requestWhenInUseAuthorization];// 请求前台定位权限
        [self.mgr startUpdatingLocation];

        
    }else
    {
        NSLog(@"是iOS7");
        // 3.开始监听(开始获取位置)
        [self.mgr startUpdatingLocation];
    }

    

}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];

}

//当tableview 滚动的时候 结束编辑事件  （退出键盘）
- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView
{
    [self.view endEditing:YES];
}
// click tableview  dismiss keyboard
- (void)commentTableViewTouchInSide{
    [self.toolbar.input resignFirstResponder];
}
- (void)keyboardWillChangeFrame:(NSNotification *)notification
{

    
    NSDictionary *userInfo = notification.userInfo;
    // 动画的持续时间
    double duration = [userInfo[UIKeyboardAnimationDurationUserInfoKey] doubleValue];
    // 键盘的frame
    CGRect keyboardF = [userInfo[UIKeyboardFrameEndUserInfoKey] CGRectValue];
    // 执行动画
    [UIView animateWithDuration:duration animations:^{
       //  工具条的Y值 == 键盘的Y值 - 工具条的高度
        if (keyboardF.origin.y > self.view.bounds.size.height) { // 键盘的Y值已经远远超过了控制器view的高度
#warning TOOLBAT CONSTRIN
            self.toolbarBottom.constant = 33;
        }
        
        else {
            
            self.toolbarBottom.constant = 0-keyboardF.size.height;
         
        }
        
        
        [UIView animateWithDuration:1 animations:^{
            // 让view上的约束执行动画
            [self.view layoutIfNeeded];
            //    //    //移动的位置
            if (self.messageArray.count >3)
            {
                
                NSIndexPath *path = [NSIndexPath indexPathForRow:self.messageArray.count -1 inSection:0];
                //    //    //真正去是位置 atSrcollPosition :  滚到位置
                [self.tableView scrollToRowAtIndexPath:path atScrollPosition:UITableViewScrollPositionBottom animated:YES];
                
            }

        }];


    }];
    
}


-(BOOL)textView:(UITextView *)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text
{
    NSInteger count = [self unicodeLengthOfString:textView.text];
    NSInteger max = 31;
    //frame change
    NSDictionary *textDict = @{NSFontAttributeName: [UIFont systemFontOfSize:14]};
    CGRect textFrame = [textView.text textRectWithSize:CGSizeMake(([UIScreen mainScreen].bounds.size.width)-10, MAXFLOAT) attributes:textDict];
    self.inputH.constant = textFrame.size.height+13.3;
    
    
    if (self.toolbar.locationlbtn.selected)
    {
        max = 24;
    }
    self.maxC = max;


    //    NSLog(@"shouldchange  %ld",count);
    if (count +[self unicodeLengthOfString:text] >= max+1)
    {
           return NO;
    }
       return YES;
}
-(void)textViewDidChange:(UITextView *)textView
{
    
    
    // string text
    NSString *stt = [NSString stringWithFormat:@"%u",self.maxC - [self unicodeLengthOfString:textView.text]];
    HWLog(@"%@",[NSString stringWithFormat:@"didchange %ld",(unsigned long)[self unicodeLengthOfString:textView.text]]);
    NSMutableAttributedString *s = [[NSMutableAttributedString alloc]initWithString:[NSString stringWithFormat:@"你还可以输入%@字数",stt]];
    [s addAttribute:NSForegroundColorAttributeName value:[UIColor redColor] range:NSMakeRange(6,stt.length)];
    self.toolbar.countl.attributedText = s;
}
//记录等于24的字符串长度
-(void)IslocSelAndBeyondText
{
    if (self.toolbar.locationlbtn.selected && [self unicodeLengthOfString:self.toolbar.input.text] > 24 )
    {
        NSString *strB = @"";
        for (int i=0; i<[self.toolbar.input.text length]; i++)
        {
            strB = self.toolbar.input.text;
            strB = [strB  substringToIndex:strB.length-i];
            if (24 == [self unicodeLengthOfString:strB])
            {
                self.toolbar.input.text = strB;
                return;
            }
        }
        NSLog(@"24 -- %@---- textview%@",self.toolbar.input.text,strB);
    }

}
//限制字节
-(NSUInteger) unicodeLengthOfString: (NSString *) text {
    NSUInteger asciiLength = 0;
    
    for (NSUInteger i = 0; i < text.length; i++)
    {
        
        
        unichar uc = [text characterAtIndex: i];
        
        asciiLength += isascii(uc) ? 1 : 2;
    }
    
    NSUInteger unicodeLength = asciiLength / 2;
    
    if(asciiLength % 2) {
        unicodeLength++;
    }
    
    
    return unicodeLength;
}

// sigal btn send mes
-(void)sendMes:(UIButton *)sender
{

    //1发送一条数据
    messageModel *mes =   [[messageModel alloc]init];
    mes.messageFrom = @"me";
    mes.messageTo = self.userID;
    mes.messageDate =[NSDate date];
    mes.messageContent = self.toolbar.input.text;
    mes.mesStatus = @"发送状态:发送成功";
//    mes.mesStatus = @"发送状态:发送失败";
    //1.‘1’是自己发送的 (短信)
    NSNumber* a = [NSNumber numberWithInt: 1];
    mes.messageType = a ;
    
    if (self.toolbar.locationlbtn.selected == YES)
    {
        mes.meslocation = self.meslocationWithNoformat;
    }
    else
    {
        mes.meslocation = nil;
    }
    [messageTool addmessage:mes];
    
    
    [self refresh];

    
    
    //4. 清空表格
    self.toolbar.input.text = @"";  //nil
    [self.toolbar.input resignFirstResponder];
    
    
    
    // auto to bottom
    if (self.messageArray.count >2)
    {
        NSIndexPath *path = [NSIndexPath indexPathForRow:self.messageArray.count -1 inSection:0];
        [self.tableView scrollToRowAtIndexPath:path atScrollPosition:UITableViewScrollPositionBottom animated:YES];
    }
    
    // receiveMes.m4r
    NSURL *url = [[NSBundle mainBundle] URLForResource:@"sendMes.m4r" withExtension:nil];
//    NSURL *url = [[NSBundle mainBundle] URLForResource:@"" withExtension:nil];

    AudioServicesCreateSystemSoundID((__bridge CFURLRef)(url), &_soundID);
    //播放音效(本地音效)
    AudioServicesPlaySystemSound(self.soundID);
    
}

#pragma mark - Table view data source


- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
#warning Incomplete method implementation.
    // Return the number of rows in the section.
    self.tableView.header.hidden = (self.messageArray.count == [messageTool coutMessageListWithUser:self.userID]);

    return self.messageArray.count;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    //1. 可重用标示符
    static NSString *ID = @"messageCell";
    // 2. tableView查询可重用Cell
    chaTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:ID];
    
    
    // 3. 如果没有可重用cell
    //    if (cell == nil) {
    //可重用
  
    
    //4.设置cell内容
 
    
    messageModel *mesM = self.messageArray[indexPath.row];
  
    
    [cell initWithModel:mesM anduserID:self.userID ];
    
    
//
    
    return cell;
    
}
#pragma tableview heightforRow cell
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
  
     messageModel *cell = self.messageArray[indexPath.row];
    
    if (cell.meslocation) { //有地址
        return 170+16;
    }
    else{    //没地址
        return 170;
}
}

#pragma 加载数据 page 1
- (void)refresh
{
    //asyus
    NSArray *mesArray = [messageTool fetchMessageListWithUser:self.userID andPage:1];
    [self.messageArray removeAllObjects];
//    HWLog(@"%@",[mesArray[0]  valueForKey:@"messageContent"]);
    if (mesArray) {
        for (int i =0; i<mesArray.count; i++) {
            [self.messageArray addObject:mesArray[mesArray.count - 1 -i]];
        }
        [self.tableView reloadData];

    }
   
    

}
#pragma 上啦加载数据
-(void)loadNewData
{
    
    self.page ++;
    //asyus
    NSArray *mesArray = [messageTool fetchMessageListWithUser:self.userID andPage:self.page];
    if (mesArray && self.messageArray) {
        for (int i =0; i<mesArray.count; i++) {
            [self.messageArray insertObject: mesArray[i] atIndex:0];
        }
//        for (messageModel *mes in mesArray) {
//            HWLog(@"mecontent- %@  %ld",mes.messageContent,mesArray.count);
//        }
        [self.tableView reloadData];
        
        [self.tableView.header endRefreshing];
        
//        HWLog(@"mecontent- %ld  %ld",self.messageArray.count,[messageTool coutMessageListWithUser:self.userID]);
        
    }
}
/**
 *  return to root view
 *
 *  @param sender btn
 */

- (IBAction)backTApped:(id)sender {
    
    [self.navigationController popToRootViewControllerAnimated:YES];
    
}

-(void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender
{
        
    //传递数据至编辑联系人页
    if ([segue.identifier isEqualToString:@"toProfile2"])
    {
        contactProfile2TableViewController *editContactViewController = segue.destinationViewController;
        editContactViewController. userID = self.userID;
        
        
    }


}

/**
 *  重新刷新表格   todo
 */
-(void)reloadMes: (NSNotification *)notification

{
    [self.messageArray removeObject:[notification valueForKey:@"mes"]];
    HWLog(@"%@",[notification valueForKey:@"mes"]);
    [self.tableView reloadData];

}

-(void)dealloc
{
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIKeyboardWillChangeFrameNotification object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:@"reloadForDeleteMes" object:nil];
}

@end







点击backTApped 就是左边的button item 就报错 换成默认的就没问题

**Comment by CoderMJLee** [comment]
这个还真看不出问题哈。能不能发一个可以跑有这个问题的程序？因为暂时没有其他人遇到这样的问题哈

**Comment by cjckkk** [comment]
老师qq多少

**Comment by CoderMJLee** [comment]
邮箱：richermj123go@vip.qq.com
