### ISSUE TITLE
在自定义的header中使用masonry约束控件位置，在ios7下会crash

### ISSUE THREAD

**Issue by wangyutao0424** [CoderMJLee/MJRefresh#283]
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Auto Layout still required after executing -layoutSubviews. MYRefreshHeader's implementation of -layoutSubviews needs to call super.'

**Comment by CoderMJLee** [comment]
感觉是布局方面的问题哦，跟框架内部无关。有具体的代码么？

**Comment by wangyutao0424** [comment]
试了下，不能直接跟header约束，需要做一个contentView，子view跟contentView约束，contentView在layoutSubviews的时候setFrame与header的bounds一样

**Comment by CoderMJLee** [comment]
MYRefreshHeader有没有重写layoutSubviews？重写了的话有没有调用super layoutSubviews?
