### ISSUE TITLE
建議

### ISSUE THREAD

**Issue by jsaonpeng** [CoderMJLee/MJRefresh#285]
我们以前的版本不存在这种依赖关系，使用一直正常，最近更新了MJ，发现大量页面在下拉刷新的时候存在问题。foot一直没有办法hidden。只有先reload再hidden才可以。

请问能不能不依赖reloadData的调用顺序。目前大量代码都是先调用self.table.foot.hidden = yes，再做reloadData，如果跟reloadData的调用顺序存在依赖，代码review和修改量比较大，之后维护的人员写新代码也容易出错。

十分感谢！

**Comment by CoderMJLee** [comment]
如果不希望依赖的话，那就设置footer.automaticallyHidden = NO;
