### ISSUE TITLE
上提加载有重大BUG

### ISSUE THREAD

**Issue by DouKing** [CoderMJLee/MJRefresh#287]
在VC里给`UICollectionView`设置`footer`之后，发现该VC不会走`dealloc`方法，有内存泄露！

```oc
  __weak typeof(self) weakSelf = self;
  self.lvm_collectionView.footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
    __strong typeof(weakSelf) strongSelf = weakSelf;
    ...
  }];
```

**Comment by CoderMJLee** [comment]
这个不属于框架的BUG，Objective-C的block在某些场合直接引用外面的对象，有可能会导致对象无法释放，解放方案统一都是使用__weak

**Comment by iosDevZhong** [comment]
关于这方面的问题,下边这些资料可能对大家有些帮助.
http://www.cnblogs.com/biosli/p/block_usage.html <http://www.cnblogs.com/biosli/p/block_usage.html>
http://www.cnblogs.com/biosli/p/block_usage.html <http://www.cnblogs.com/biosli/p/block_usage.html>

**Comment by iosDevZhong** [comment]
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html#//apple_ref/doc/uid/TP40011210-CH8-SW16 <https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/WorkingwithBlocks/WorkingwithBlocks.html#//apple_ref/doc/uid/TP40011210-CH8-SW16>
http://www.cnblogs.com/biosli/p/block_usage.html <http://www.cnblogs.com/biosli/p/block_usage.html>
