### ISSUE TITLE
BUG：从别的页面返回时，上拉刷新箭头和label会出现在view的顶部

### ISSUE THREAD

**Issue by yhquan** [CoderMJLee/MJRefresh#288]
A页面有个tableView 添加了 MJRefreshBackNormalFooter ，点击tableViewcell 进入到B页面，然后从B页面返回A，A页面的footer 的位置会出现在A页面视图的顶部？？？

**Comment by CoderMJLee** [comment]
MJRefresh的示例程序和其他网友未出现过这样的问题。能发个Demo看看么？3Q

**Comment by YueLiXing** [comment]
我也发现了这个BUG
http://pan.baidu.com/s/1pJqZzGB
这个Demo就是

**Comment by YueLiXing** [comment]
![ios simulator screen shot 2015 9 6 15 40 15](https://cloud.githubusercontent.com/assets/9456800/9703182/989feddc-54ad-11e5-80a2-fb474fc2f470.png)

**Comment by yhquan** [comment]
貌似那个header的箭头一直在顶部的，只是不知道为啥我那个footer的箭头也会出现在顶部

**Comment by YueLiXing** [comment]
我觉得就算是tableView 上面没有遮盖物，这个箭头也不应该显示出来。。总感觉怪怪的

**Comment by zymxxx** [comment]
@YueLiXing MJRefreshComponent文件中有个automaticallyChangeAlpha适合你。
