### ISSUE TITLE
上拉刷新显示不对

### ISSUE THREAD

**Issue by lvjg** [CoderMJLee/MJRefresh#290]
当设置完footer之后，在改变scrollview的contentInset之后，上拉刷新显示不正常

**Comment by CoderMJLee** [comment]
建议设置完inset后重新设置header
```objc
scrollView.contentInset = ...;
scrollView.header = ...;
```
如果位置还是不对，还可以通过header.ignoredScrollViewContentInsetTop属性来调节到你想要的效果，Inset是scrollView中一个比较纠结的属性
