### ISSUE TITLE
用UIKIT_EXTERN方式替代Macro

### ISSUE THREAD

**Issue by WenchaoIOS** [CoderMJLee/MJRefresh#291]
Hi, MJ：
    我尝试过使用`UIKIT_EXTERN`或者`extern`的方式定义UIColor和UIFont常量，但是实现文件必须是.mm结尾，在项目中可以正常运行，但是不知道是否能在cocoapods中正常运行。因为看你所有字符串都是用这种方式定义而不是用的Macro，所以猜测应该你也应该倾向于这种方式吧

**Comment by CoderMJLee** [comment]
一些全局常量，尽量使用extern来引用，其次再选择考虑Macro

**Comment by WenchaoIOS** [comment]
是的。但是像UIColor和UIFont这样的或者任意类型都可以用extern的，但是要把MJRefreshConst.m换成MJRefreshConst.mm. 你是故意不这么做或者是这么做出过问题么？

**Comment by CoderMJLee** [comment]
不想随便用.mm这种混编的文件（以后可能会出现编译器相关的问题，虽然都可以通过配置一些编译器参数解决，但毕竟作为第三方库哈，还是稳妥简单一点好）

**Comment by WenchaoIOS** [comment]
OK，明白
