### ISSUE TITLE
UISearchDisplayController中的searchResultsTableView加上上拉加载时，footer一直在页面外面，位置不对？

### ISSUE THREAD

**Issue by Duzj** [CoderMJLee/MJRefresh#295]
UISearchDisplayController中的searchResultsTableView加上上拉加载时，footer一直在页面外面，位置不对？

**Comment by meloanyang** [comment]
兄弟，这问题，你解决了吗？我也遇到这样的问题。

**Comment by Duzj** [comment]
#pragma mark - UISearchDisplayDelegate
-(void)searchDisplayController:(UISearchDisplayController *)controller willShowSearchResultsTableView:(UITableView *)tableView{
   
    [tableView setContentInset:UIEdgeInsetsMake(0, 0, 44, 0)];
    [tableView setScrollIndicatorInsets:UIEdgeInsetsZero];
}
你可以试试这个方法

**Comment by meloanyang** [comment]
你好，这种方法也不行。。

**Comment by meloanyang** [comment]
![111111](https://cloud.githubusercontent.com/assets/13743089/11523506/c032107a-98fd-11e5-926f-e5a494f56dbb.png)

**Comment by Duzj** [comment]
我就是用这个方法调的，你的这种情况跟我那个不是很像，可能不是一个问题。

**Comment by meloanyang** [comment]
好吧，也谢谢你了
