### ISSUE TITLE
一个奇怪的  需求 

### ISSUE THREAD

**Issue by wy19901227** [CoderMJLee/MJRefresh#296]
虽然这个是刷新控件 ，但 可以请你加个这样的 需求吗？  就是 拉动刷新的时候  不经过freshing这个 状态，直接 执行拉动的操作。
呵呵。。。
现实中就又这样的 需求 ，比如淘宝的详情页，有个 下拉 返回 顶部详情的 动作， 虽然是个刷新的控件，却干着不是刷新的事， 所以 ，看你觉得 有必要加没，如果没必要，我就自己来写这个“刷新view”。

**Comment by CoderMJLee** [comment]
这个还是建议自己监听contentOffset去做一个刷新控件。MJRefresh针对的是刷新数据

**Comment by wy19901227** [comment]
恩。自己做了一个。
