### ISSUE TITLE
底部提示文字无法隐藏

### ISSUE THREAD

**Issue by weihong1028** [CoderMJLee/MJRefresh#298]
使用的是最新版本
<img width="359" alt="qq20150902-1 2x" src="https://cloud.githubusercontent.com/assets/7336582/9628612/f225fc50-519e-11e5-8f09-f8f198d0a248.png">
我使用 self.tableView.footer.hidden = false 并不能使我的footer隐藏掉
然后也没有footer.refreshingTitleHidden 和 footer.stateLabel.hidden这两个方法

**Comment by CoderMJLee** [comment]
你是使用CocoaPods么？尝试pod repo update后再下载框架。
先reloadData，再设置hidden试试。
或者设置footer.automaticallyHidden = false后再处理hidden

**Comment by weihong1028** [comment]
我设置了设置footer.automaticallyHidden = false 就可以了，谢谢！
