### ISSUE TITLE
BUG下拉刷新箭头和label 会在开始的时候出现在顶部

### ISSUE THREAD

**Issue by YueLiXing** [CoderMJLee/MJRefresh#299]

**Comment by YueLiXing** [comment]
Demo链接 http://pan.baidu.com/s/1pJqZzGB

**Comment by CoderMJLee** [comment]
```objc
_tableView.header.ignoredScrollViewContentInsetTop = 20;
```

**Comment by YueLiXing** [comment]
加上这个之后又出现了新问题。。
http://pan.baidu.com/s/1ntvhudV

**Comment by CoderMJLee** [comment]
我觉得这个不属于框架的问题了哈。那是因为你隐藏了NavigationController的NavigationBar，导致，顶部空出了一块20

**Comment by YueLiXing** [comment]
顶部空出 20是故意的，但是在有 sectionHeaderView 的情况下
_tableView.header.ignoredScrollViewContentInsetTop = 20;
这句话直接导致整个tableView往下便宜了 20，这就有点不应该的意思了

**Comment by CoderMJLee** [comment]
或者为了去掉隐藏导航栏带来的负面效果，我还建议可以这么做：
```objc
_tableView.contentInset = UIEdgeInsetsMake(-20, 0, 0, 0);
// _tableView.header.ignoredScrollViewContentInsetTop = 20;
```

**Comment by lotus-lotus** [comment]
去掉隐藏导航栏导致iPhoneX顶部有20遮挡显示刷新,利用下面的方法是可以解决,但是刷新完成后因为底色和tableView的header颜色并不一样,所以有个色差,我并不想创建个view去覆盖,不知道有什么方法
<img width="404" alt="55c69bf8-cad2-4df9-9777-ee79bd434958" src="https://user-images.githubusercontent.com/24632295/37958711-c4aff2ee-31e3-11e8-88ad-6e221f224e48.png">

self.tableView.contentInset = UIEdgeInsetsMake（20，0，0，0）
