### ISSUE TITLE
如果不想要那个上拉时的时间

### ISSUE THREAD

**Issue by romitlee9325** [CoderMJLee/MJRefresh#30]
产品经理说要简洁,给那个时间也没有用户去关注到底上次的刷新是什么时候,所以要我取消那个时间,我觉得这个时间应该有个枚举值,分为 有时间的label和只有状态的label. 因为我屏蔽了时间的label的代码时,高度没有和那个刷新圆圈对齐,费了好大的劲才改了样式

**Comment by CoderMJLee** [comment]
最新框架已经可以轻易去除刷新的时间：
self.tableView.header.updatedTimeHidden = YES;
