### ISSUE TITLE
uicollectionview + footer 没效果

### ISSUE THREAD

**Issue by jianjunlu** [CoderMJLee/MJRefresh#303]
代码如下：
MJRefreshBackNormalFooter *footer = [MJRefreshBackNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreItem)];
        [footer setTitle@"load more ..." forState:MJRefreshStatePulling];
        self.collectionView.footer = footer;

上拉触发呢，不知道还要什么设置吗
以同样方式添加 下拉刷新正常，就是 上拉 不正常，不知道什么原因

**Comment by CoderMJLee** [comment]
默认情况下，没有数据的时候是隐藏的。如果你希望一直出现，那么就
```objc
footer.automaticallyHidden = NO;
```

**Comment by jianjunlu** [comment]
已经有了超过一个屏幕的数据，然后上拉到底也没有出现，也不触发

**Comment by jianjunlu** [comment]
我发现原因了，加上 footer.automaticallyHidden = NO; 
一切都正常，也不会一直出现
多谢
