### ISSUE TITLE
cocoapods安装MJRefresh出了问题。

### ISSUE THREAD

**Issue by Aimeow** [CoderMJLee/MJRefresh#305]
错误信息如下：
[!] Error installing MJRefresh
[!] /usr/bin/git clone https://github.com/CoderMJLee/MJRefresh.git /var/folders/_n/mhhbdcyd03n_g4jkzjs75flc0000gn/T/d20150909-3693-ju5kkm --single-branch --depth 1 --branch 2.4.3

Cloning into '/var/folders/_n/mhhbdcyd03n_g4jkzjs75flc0000gn/T/d20150909-3693-ju5kkm'...
warning: Could not find remote branch 2.4.3 to clone.
fatal: Remote branch 2.4.3 not found in upstream origin

然后我看了下，MJRefresh中的tags没有2.4.1到2.4.3，然后我用pod search mjrefresh查找的时候，发现搜到的版本是2.4.3的。请尽快解决。

**Comment by CoderMJLee** [comment]
pod repo update

**Comment by Aimeow** [comment]
嗯，正解，谢谢啦，已经集成成功了。。

**Comment by CoderMJLee** [comment]
不客气哈
