### ISSUE TITLE
UICollectionView添加下拉刷新，并在UIScrollView代理设置上提时导航栏可以移动时，下拉刷新头显示有问题

### ISSUE THREAD

**Issue by jffun** [CoderMJLee/MJRefresh#306]
给UICollectionView添加下拉刷新
_collectionV.header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
    }];
然后在- (void)scrollViewDidScroll:(UIScrollView *)scrollView代理中根据contentOffset的变化，在_collectionV往上拉时，设置导航栏也跟着上提，出现问题
1.如果设置
if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 7.0 ) {
        self.automaticallyAdjustsScrollViewInsets = NO;
        self.edgesForExtendedLayout = UIRectEdgeNone;
    }
下拉刷新后_collectionV和导航栏间会有一段黑色空白，如附图所示
2.如果设置_collectionV的偏移
if ([self respondsToSelector:@selector(automaticallyAdjustsScrollViewInsets)]) {
        self.automaticallyAdjustsScrollViewInsets = NO;
        UIEdgeInsets insets = self.collectionV.contentInset;
        insets.top = self.navigationController.navigationBar.bounds.size.height +
        [UIApplication sharedApplication].statusBarFrame.size.height;
        self.collectionV.contentInset = insets;
        self.collectionV.scrollIndicatorInsets = insets;
    }
下拉刷新后显示正常，但是push出新界面后，再回来，下拉刷新头就会一直显示在_collectionV和导航栏之间，如附图所示
在viewWillAppear中检查了下collectionV的frame，contentInset，contentOffset，scrollIndicatorInsets的值都没有任何变化 
![1](https://cloud.githubusercontent.com/assets/8054128/9778258/a0ccbf1c-57a0-11e5-97f5-53c788b9ab14.png)
![2](https://cloud.githubusercontent.com/assets/8054128/9778261/a2c8cd2e-57a0-11e5-957e-61a77243f6ec.png)

麻烦MJ大神看下是什么原因

**Comment by CoderMJLee** [comment]
可以发个有问题的Demo代码不？我基本没遇到这样的问题哈

**Comment by jffun** [comment]
好，麻烦MJ大神看下
http://yunpan.cn/cmGgH5WnmZCPK （提取码：7075）

**Comment by CoderMJLee** [comment]
我看了Demo哈，判断应该要改为64
```objc
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    //collectionView的contentOffset变化时，改变导航栏的位置
        CGFloat y = _collectionV.contentOffset.y;
        if (y > - 64) {
            self.navigationController.navigationBar.frame = CGRectMake(0,20 - (y + 64), self.view.frame.size.width, self.navigationController.navigationBar.frame.size.height);
    //        self.navigationController.navigationBar.hidden = YES;
        } else {
           CGRectMake(0,20, self.view.frame.size.width, self.navigationController.navigationBar.frame.size.height);
        }
}
```

**Comment by jffun** [comment]
跟这个值没关系 ，-48是collectionView.contentOffset.y的初始值，我改成64后，push出nextViewController后再回来，下拉刷新头还是一直显示在导航栏和collectionView之间

**Comment by lexiaoyao20** [comment]
self.hidesBottomBarWhenPushed = YES;

Push之前调用上面的代码试试
