### ISSUE TITLE
分组情况下。sectionHeadVIew不能置顶

### ISSUE THREAD

**Issue by HorexC** [CoderMJLee/MJRefresh#307]
分组情况下。sectionHeadVIew不能置顶
上拉的时候红色的head不是应该在顶部么。怎么解决这个问题啊。
![Uploading A2CE90D8-5192-480C-B764-338A266D8F7A.png…]()
![Uploading A08C0F9C-45AE-4A5C-9DF7-A426A478FB34.png…]()

代码如下：
    // Do any additional setup after loading the view, typically from a nib.
    self.tab = [[UITableView alloc] initWithFrame:self.view.bounds style:UITableViewStylePlain];
    self.tab.delegate = self;
    self.tab.dataSource = self;
    self.tab.header = [MJRefreshNormalHeader
                       headerWithRefreshingBlock:^{

```
}];
[self.view addSubview:self.tab];
```

}
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
  {
  return 2;
  }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
  {
  return 10;
  }
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
  {
  UIView *v = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 30)];
  v.backgroundColor = [UIColor redColor];
  return v;
  }
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
  {
  return 30;
  }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
  {
  UITableViewCell *cel = [tableView dequeueReusableCellWithIdentifier:@"123"];
  if (!cel) {
      cel = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:@"123"];
  }
  cel.textLabel.text = @"213";
  return cel;
  }

**Comment by HorexC** [comment]
![Uploading A2CE90D8-5192-480C-B764-338A266D8F7A.png…]()
![Uploading A08C0F9C-45AE-4A5C-9DF7-A426A478FB34.png…]()

**Comment by HorexC** [comment]
![Uploading A2CE90D8-5192-480C-B764-338A266D8F7A.png…]()

**Comment by HorexC** [comment]
截图如下 ﻿http://pan.baidu.com/s/1sj0zbyd

﻿﻿

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈
