### ISSUE TITLE
TableView上加了UISearchDisplayController。搜索返回后更新的字样在navgation下不会隐藏

### ISSUE THREAD

**Issue by ztangxu** [CoderMJLee/MJRefresh#308]
TableView上加了UISearchDisplayController。搜索返回后更新的字样在navgation下不会隐藏

正常情况下我设置了_mTable.header.automaticallyChangeAlpha = YES; 那么在半透明的nav下就不会显示 更新的字样了。但是点击searchbar  返回后，又显示出来了。请问如何解决

**Comment by CoderMJLee** [comment]
应急解决方案，在点击searchbar返回后：
```objc
_mTable.header.alpha = 0.0;
```

**Comment by ztangxu** [comment]
应急解决方案，在点击searchbar返回后：
_mTable.header.alpha = 0.0;
达不到效果的，会引发其他问题，比如再次下拉，就没有refreshheader了， 点击searchbar返回后再重新设置_mTable.header 也是无效。
坐等mj哥终极解决方案

**Comment by CoderMJLee** [comment]
能不能帮忙写出有这个问题的Demo，发到我邮箱？谢谢哈

**Comment by ztangxu** [comment]
richermj123go@vip.qq.com;
demo发送到这个邮箱了，麻烦看看咋回事，谢谢

**Comment by CoderMJLee** [comment]
试试2.4.9版本。
```objc
pod repo update
pod update
```

**Comment by ztangxu** [comment]
解决了，谢mj哥

**Comment by CoderMJLee** [comment]
不客气
