### ISSUE TITLE
无法释放视图(不走dealloc方法)

### ISSUE THREAD

**Issue by fengyang0329** [CoderMJLee/MJRefresh#309]
self.tableView.header=[MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [self reSetParams];
        [self requestDataList];
    }];
    self.tableView.footer = [MJRefreshBackNormalFooter
                             footerWithRefreshingTarget:self refreshingAction:@selector(requestDataList)];
这样调用后，BViewController pop 回AViewController,不反选dealloc方法，注掉上面的代码，就会执行dealloc..我试了所有使用MJ的类，发现都有这个问题。。

**Comment by fengyang0329** [comment]
...

**Comment by AbeiOS** [comment]
我也遇到了同样的问题，楼主怎么解决的？

**Comment by fengyang0329** [comment]
self用__weak 修饰下,好像是这样解决的。

**Comment by AbeiOS** [comment]
恩，已经这么解决了 谢谢哈 另外还有一个疑问，当我block 嵌套多个block时怎么处理weakself 和strongself？

**Comment by johanntony** [comment]
我也无法释放 最新版本 3.1.12 weakSelf 设了

**Comment by sa124a** [comment]
我也无法释放 最新版本 3.1.12 weakSelf 设了
