### ISSUE TITLE
在tableview使用分页滑动pagingEnabled = YES的时候，整个人都不好了

### ISSUE THREAD

**Issue by SharePeng** [CoderMJLee/MJRefresh#311]
在tableview使用分页滑动pagingEnabled = YES的时候，整个人都不好了，手动刷新完之后，内容会往上偏移一部分。

**Comment by xjcristal** [comment]
为啥我会收到你们的讨论呢？


发自网易邮箱大师
在2015年09月11日 14:09，pp253942011 写道:

在tableview使用分页滑动pagingEnabled = YES的时候，整个人都不好了，手动刷新完之后，内容会往上偏移一部分。

**Comment by xdongdan** [comment]
我是在tableview使用pagingEnable的时候，内容会往下偏移一部分

**Comment by lijy91** [comment]
@SharePeng 楼主后来解决这个问题了吗？

**Comment by CoderMJLee** [comment]
由于pagingEnabled带来的影响比较奇怪，试试这种做法
```objc
self.tableView.header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
    self.tableView.pagingEnabled = NO;
    // 执行任务
    
    // 模拟执行完任务以后
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.tableView.header endRefreshing];
        self.tableView.pagingEnabled = YES;
    });
}];
```

**Comment by milkerL** [comment]
下拉刷新仍然有这个问题. 正在看代码, 估计 contentSize 和 分页的冲突了

**Comment by xdongdan** [comment]
可以试试我的方法

**Comment by MrCaoBoHan** [comment]
楼主刷新问题有解决吗

**Comment by zhangchioulin** [comment]
同样也遇到了相同的问题MJRefresh和SVP都遇到了:  tableviewcell的内容大小跟当前屏幕大小一致且开启了pageEnable  = YES 碰到,起初认为是通过KVC设置ScrollView 的位置时引起的,禁用了SVP代码中KVO的部分无果,但是SVP的功能达不到要求.转战研究MJ的.目前还在研究当中.如果解决了,我会贴出思路.

上面MJ写的
`self.tableView.header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
    self.tableView.pagingEnabled = NO;
    // 执行任务

    // 模拟执行完任务以后
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.tableView.header endRefreshing];
        self.tableView.pagingEnabled = YES;
    });
}];`
我这里设置了,不起作用.

**Comment by wolfcon** [comment]
目前没有对 `PagingEnabled` 情况做适配, 请等待

**Comment by CoderLGL** [comment]
使用pagingEnabled,还是会出现同样的问题
