### ISSUE TITLE
Bug：上拉加载更多NoMoreData后，箭头没消失

### ISSUE THREAD

**Issue by sunhr** [CoderMJLee/MJRefresh#312]
![image](https://cloud.githubusercontent.com/assets/4961449/9812690/9123fe1a-58b1-11e5-81d6-ad4ea45d48e5.png)
state设置为NoMoreData后，上面的animation回调执行，又把arrowView.hidden设置为NO了

**Comment by CoderMJLee** [comment]
你是连续执行了下面2句么
```objc
[footer endRefreshing];
[footer noticeNoMoreData];
```
这2句代码只需要执行一句哈

**Comment by sunhr** [comment]
OK，感谢回复~
