### ISSUE TITLE
下载运行MJRefreshExample出错

### ISSUE THREAD

**Issue by Caeson** [CoderMJLee/MJRefresh#313]
直接下载最新的source code，打开MJRefreshExample里的project，模拟器直接运行，报错：

2015-09-11 21:32:32.753 MJRefreshExample[1619:90620] *** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3473.13/UIApplication.m:3109
2015-09-11 21:32:32.755 MJRefreshExample[1619:90620] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application windows are expected to have a root view controller at the end of application launch'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010de70885 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010d8e9df1 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010de706ea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010d53bbb1 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   UIKit                               0x000000010e437350 -[UIApplication _runWithMainScene:transitionContext:completion:] + 2875
	5   UIKit                               0x000000010e43473f -[UIApplication workspaceDidEndTransaction:] + 188
	6   FrontBoardServices                  0x00000001118dbd7b FrontBoardServices + 163195
	7   FrontBoardServices                  0x00000001118dc118 FrontBoardServices + 164120
	8   CoreFoundation                      0x000000010dd9b0f1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x000000010dd90eac __CFRunLoopDoSources0 + 556
	10  CoreFoundation                      0x000000010dd90363 __CFRunLoopRun + 867
	11  CoreFoundation                      0x000000010dd8fd78 CFRunLoopRunSpecific + 488
	12  UIKit                               0x000000010e434091 -[UIApplication _run] + 402
	13  UIKit                               0x000000010e43879b UIApplicationMain + 171
	14  MJRefreshExample                    0x000000010d3bb29f main + 111
	15  libdyld.dylib                       0x00000001105ffa05 libdyld.dylib + 10757
	16  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

使用环境：Xcode Version 7.0 beta (7A120f)
模拟器：Version 9.0 (SimulatorApp-602 CoreSimulator-159)

谢谢老师了！

**Comment by hanxiao790** [comment]
Xcode 7.0 GM
iOS 9.0 GM
同样的问题, 难道是没有适配iOS 9 ?

**Comment by CoderMJLee** [comment]
应该是Xcode7跑了Xcode6的项目出现的问题，改天我换下Demo

**Comment by CoderMJLee** [comment]
已经修复哈
