### ISSUE TITLE
将UISearchBar作为tableHeaderView添加时，footer位置有问题

### ISSUE THREAD

**Issue by takanashi-positive** [CoderMJLee/MJRefresh#314]
只有一条数据，但是footer的位置却跑到了比第二条数据还靠下的部分，如果数据大于一条，偏差会小一点,大概几十px
![988bd1a6-a3ba-41dc-888a-5cb99c155a22](https://cloud.githubusercontent.com/assets/5235108/9843277/0b7ad96e-5aeb-11e5-84d6-43b757883085.jpg)
![7b55e5e5-ac87-4085-9bd3-4d64ec610e1b](https://cloud.githubusercontent.com/assets/5235108/9843278/0dc22e16-5aeb-11e5-809b-decd9226abca.jpg)

**Comment by takanashi-positive** [comment]
为什么木有人理我，难倒这不算个bug咩 T T

**Comment by CoderMJLee** [comment]
@takanashi-positive 哈哈，最近忙哈，sorry，我有空就看看咋回事哈
