### ISSUE TITLE
下拉刷新，HeaderView 卡住的 bug 的问题讨论解决？！

### ISSUE THREAD

**Issue by allabttony** [CoderMJLee/MJRefresh#315]
这个问题不止 MJRefresh 存在，Instagram 的下拉也会出现

可以参考 Instagram 的解决方式：下拉刷新后，如果向下滚动一定距离，则取消下拉刷新动画，endRefresing，线程可以继续拉数据。

**Comment by CoderMJLee** [comment]
是的。。。苹果官方的UIRefreshControl也有这样的问题。本质还是因为contentInset的影响。

**Comment by YeJinliang** [comment]
监听事件么?

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈

**Comment by allabttony** [comment]
太给力！
