### ISSUE TITLE
国际化的问题

### ISSUE THREAD

**Issue by liuyan3176** [CoderMJLee/MJRefresh#316]
除了通过header自定义文字，在MJRefreshConst里可以直接自定义国际化吗？
## 我试了NSLocalizedString(<#key#>, <#comment#>),不过提示initializer element is not a compile

我尝试直接在MJRefreshStateHeader里直接修改，应该没有什么问题吧

**Comment by CoderMJLee** [comment]
MJRefreshConst里面没有函数和方法的实现，不能使用NSLocalizedString宏，在MJRefreshStateHeader中可以
