### ISSUE TITLE
mjrefresh footer  一直在刷新

### ISSUE THREAD

**Issue by anyuhao** [CoderMJLee/MJRefresh#317]
刚开始刷新两次,连续刷新3-4次两次,
结果就卡在那里一直在刷新了.
先结束刷新再刷新tableView一样不行...

**Comment by anyuhao** [comment]
iOS 7上出现 这样的问题 iOS 8没问题
               [self.tableView reloadData];
                NSLog(@"\n\nlog:--------------\n\n");
                [self.tableView.header endRefreshing];
                [self.tableView.footer endRefreshing];
                if (self.dataSource.count == totalCount) {
                    [self.tableView.footer noticeNoMoreData]; //此方法没有调用...
                }

**Comment by CoderMJLee** [comment]
noticeNoMoreData和endRefreshing不要一起执行，应该是这样
```objc
if (self.dataSource.count == totalCount) {
    [self.tableView.footer noticeNoMoreData]; 
} else {
    [self.tableView.footer endRefreshing];
}
```

**Comment by anyuhao** [comment]
不走那个方法,也会执行两次刷新.
这个怎么回事?

**Comment by anyuhao** [comment]
self.tableView.footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        [self refreshRequestMore];
        NSLog(@"加载更多.....");
    }];

然后就是上面那个方法了

**Comment by anyuhao** [comment]
刚刷试试了下,还是刷新两次...

**Comment by CoderMJLee** [comment]
看看你的refreshRequestMore方法实现？只在iOS7下面会这样？

**Comment by anyuhao** [comment]
对,,,

**Comment by anyuhao** [comment]
- (void)refreshRequestMore
{
    self.pageIndex++;
    [self request];
}

- (void)request
{
    if (USERID) {
        NSString *pageNo = [NSString stringWithFormat:@"%ld",(long)self.pageIndex];
        NSString *pageSize = [NSString stringWithFormat:@"%ld",(long)self.pageSize];
        NSDictionary *dic = @{@"userId": USERID,
                                           @"pageNo":pageNo,
                                           @"pageSize":pageSize};
        [MKHttpRequest requestWithAction:@"GET_USER_ORDERLIST" parameters:dic finished:^(NSURLResponse *response, NSData *data, id JSONObject) {
            
             self.isShowEmptDataView = YES;
            
            NSLog(@"\n\n............\n\n");
            if ([JSONObject integerValueForKey:@"retCode"] == 0) {
                if (self.pageIndex == 1) {
                    [self.dataSource removeAllObjects];
                }
                NSArray *resultArray = [JSONObject objectForKey:@"result"];
                NSInteger totalCount = [JSONObject integerValueForKey:@"totalCount"];
                for (NSDictionary *dic in resultArray) {
                    OrderDetailModel *model = [[OrderDetailModel alloc] initWithDictionary:dic];
                    [self.dataSource addObject:model];
                }

               
                
                [self.tableView reloadData];
                NSLog(@"\n\nlog:--------------\n\n");

                if (self.dataSource.count == totalCount) {
                    [self.tableView.footer noticeNoMoreData];
                }
                else {
                    [self.tableView.header endRefreshing];
                    [self.tableView.footer endRefreshing];
                }

            }
            else
            {
                NSLog(@"\n\nlog:xxxxxxxx  \n\n");
                [self.tableView.header endRefreshing];
                [self.tableView.footer endRefreshing];
                [self showHint:[JSONObject objectForKey:@"retMsg"]];
            }
        } failed:^(NSURLResponse *response, NSError *error) {
            [self showNetTipsError:error];
            [self.tableView.header endRefreshing];
            [self.tableView.footer endRefreshing];
        }];
    }
    else
    {
        NSLog(@"log:我的约单用户id为空...");
    }
}

**Comment by anyuhao** [comment]
requestWithAction 这个是封装好的,你就当跟 afnet    post一样

**Comment by anyuhao** [comment]
好多人都发现有这样的情况了,
这跟tableIView有关?

**Comment by anyuhao** [comment]
if ([tableView respondsToSelector:@selector(setEstimatedRowHeight:)]) {
        tableView.estimatedRowHeight =  66;
    }
这个方法影响的..

**Comment by anyuhao** [comment]
谢谢了,

**Comment by anyuhao** [comment]
问个问题, 加这个方法是怎么回事

**Comment by CoderMJLee** [comment]
加了这个就会有重复调用的问题？

**Comment by anyuhao** [comment]
对，跟iOS7机智有关吧，刷新机智不一样，就会一直调用，可能是。s
偏移量全段错误了吧

**Comment by anyuhao** [comment]
加了高度估算是让table 计算高度少执行一半，所以加了，然而会多次刷新，刷新几次然后就一直刷新，有空你可以优化下。
以后优化，可以把优化内容写到readme里面就更好了

**Comment by doubleJJJJ** [comment]
原来是tableView.estimatedRowHeight，我就奇怪为什么endRefreshing这个方法没有，一直在刷新，现在我把estimatedRowHeight这个估算值加大之后，终于停止刷新了
