### ISSUE TITLE
Refresh + Search bar

### ISSUE THREAD

**Issue by danipralea** [CoderMJLee/MJRefresh#318]
Hello and congrats for the great library!
I have one small glitch though when having a search bar together with the table. I am attaching the screenshots:
Before:
![screenshot 2015-09-15 23 46 04](https://cloud.githubusercontent.com/assets/768893/9889653/3e51ebec-5c04-11e5-9279-d0b5c7a68bfb.png)

And with the search bar active:
![screenshot 2015-09-15 23 49 00](https://cloud.githubusercontent.com/assets/768893/9889680/5ce15b42-5c04-11e5-859d-0d6f9528a1b3.png)

**Comment by CoderMJLee** [comment]
Did you hide the navigation bar?

**Comment by danipralea** [comment]
Nope. You can actually see the navigation bar in the first screenshot. In the second one it disappears because the search bar has become active

**Comment by CoderMJLee** [comment]
self.tableView.header.automaticallyChangeAlpha = YES;  // try it

**Comment by danipralea** [comment]
That solved it
Thank you!!

**Comment by CoderMJLee** [comment]
You're welcome.
