### ISSUE TITLE
demo程序在Xcode 7下用iOS9的模拟器运行直接crash

### ISSUE THREAD

**Issue by 21074223** [CoderMJLee/MJRefresh#320]

**Comment by XAmateur** [comment]
I have the same issue, when run on Xcode7.It will crash

*** Assertion failure in -[UIApplication _runWithMainScene:transitionContext:completion:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3505.16/UIApplication.m:3294

**Comment by XAmateur** [comment]
- (void)applicationDidBecomeActive:(UIApplication *)application {
    // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [MJExampleWindow show];
    });
}
注释掉   
  static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [MJExampleWindow show];
    });
这方法在xcode7上又问题

**Comment by CoderMJLee** [comment]
已经修复哈
