### ISSUE TITLE
push下个控制器,再返回有崩溃了

### ISSUE THREAD

**Issue by Kratos28** [CoderMJLee/MJRefresh#321]
要在控制器加上
- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    self.tableView.header = nil;
    self.tableView.footer = nil;
}
才不崩溃

**Comment by CoderMJLee** [comment]
3Q，这个问题有些开发者会遇到，有些开发者不会。有空我再深挖一下哈。
