### ISSUE TITLE
你好，关于内存问题。

### ISSUE THREAD

**Issue by JackZYH** [CoderMJLee/MJRefresh#324]
在使用了MJ之后，页面不会被释放，怎么破？删掉了MJ的代码之后页面就能正常释放了。如果这样用了MJ之后内存无限增加的话，问题就大了。

**Comment by CoderMJLee** [comment]
这个问题与MJRefresh没有关系哈。遇到这个问题的开发者都是因为在block里面直接使用了self，没有使用weakSelf，这是iOS开发的一个基本技术点哈。你可以看看Demo里面怎么使用block的。

**Comment by JackZYH** [comment]
我之前以为ARC不用这么写，我基础不够哈。
现在改好了，谢谢解答。

**Comment by CoderMJLee** [comment]
不客气哈，解决了就好

**Comment by MarsLeo** [comment]
用啦 weakself后 页面释放啦 但是会出现崩溃啊
