### ISSUE TITLE
关于collectionview自定义footer的使用问题

### ISSUE THREAD

**Issue by LehemYang** [CoderMJLee/MJRefresh#325]
mj老师你好，我在开发一直在用你的刷新控件，非常好用，谢谢你的贡献。我最近在开发当中，继承MJRefreshBackFooter作为自定义的collectionview的footer，遇到一个问题：如果collectionview加载的cell内容不足一页，那么footer的内容文字会短暂的跟在cell后面出现，而不是出现在本该出现的页面底端。当页面开始上拉滑动的时候，这错位的文字就会消失。第一张图是文字出现在collectionview上。轻轻滑动就会消失，再上拉滑动，就是从底部出现。
<img width="311" alt="9ea74046-4aed-46a1-b06b-874643c62826" src="https://cloud.githubusercontent.com/assets/14569638/10010212/5a7a1f0e-611a-11e5-9ce0-a96e38f4976a.png">
第二张是正常刷新的时候文字从底部出现的样子
<img width="311" alt="qq20150922-2 2x" src="https://cloud.githubusercontent.com/assets/14569638/10010233/c4afd666-611a-11e5-9668-0e71e3e6a791.png">

另：第二个问题：使用MJRefreshAutoFooter的问题。同样的collectionview，滑倒底部自动上拉加载的控件。如果我不是在初始化的时候加入自动的上拉刷新控件， 而是在collection加载一个分页数据之后，再添加自动上拉刷新控件，那么就会出现无限自动加载的情况，即无限调用footrefresh的方法。我想问的第二问题就是，如何在MJRefreshAutoFooter里面给自动上拉刷新添加一个判断机制。

望解答  不胜感激！

**Comment by CoderMJLee** [comment]
可以发个Demo看看么？不然没法调试哈，因为之前暂时没有遇到类似的问题

**Comment by LehemYang** [comment]
后来我自己找到原因了，想要替换刷新控件，先要把刷新控件设为nil，添加完新的数据之后，然后reloaddata，  再执行添加新的刷新控件。总体总结起来时方法执行顺序的问题。

**Comment by CoderMJLee** [comment]
好的，谢谢提醒哦
