### ISSUE TITLE
MJRefreshBackNormalFooter 的noticeNoMoreData 没有效果，控件还是可以上刷。

### ISSUE THREAD

**Issue by yuanqing-ye** [CoderMJLee/MJRefresh#327]
MJRefreshBackNormalFooter 的noticeNoMoreData 没有效果，控件还是可以上刷。
简单的把 MJRefreshBackNormalFooter 替换成 MJRefreshAutoNormalFooter，一切正常。

**Comment by yuanqing-ye** [comment]
这个bug实在UICollectionview下出现的。UITableView是正常的。

**Comment by CoderMJLee** [comment]
调用noticeNoMoreData的时候不要调用endRefreshing
