### ISSUE TITLE
MJRefresh的title有语法错误

### ISSUE THREAD

**Issue by tounaobun** [CoderMJLee/MJRefresh#328]
"A easy way to use pull-to-refresh."的"A"我觉得应该改成
"An easy way to use pull-to-refresh.".不然会让老外笑话的。- -

**Comment by CoderMJLee** [comment]
哈哈哈，这么多年了，都没发现这个问题，文化程度是硬伤。。。3Q

**Comment by tubie** [comment]
好细心
