### ISSUE TITLE
下拉刷新问题，ios9

### ISSUE THREAD

**Issue by lenvonsam** [CoderMJLee/MJRefresh#329]
![image](https://cloud.githubusercontent.com/assets/10168476/10068734/68b49728-62d9-11e5-9fa5-83feafae41f7.png)
我下拉刷新一次后，第二次拉到底部就不行了

**Comment by CoderMJLee** [comment]
贴出代码看看？

**Comment by lenvonsam** [comment]
![image](https://cloud.githubusercontent.com/assets/10168476/10069126/926575d0-62dc-11e5-9869-0197d6e8bc4b.png)


![image](https://cloud.githubusercontent.com/assets/10168476/10069135/9cdfd352-62dc-11e5-8478-91df5b5e5340.png)

![image](https://cloud.githubusercontent.com/assets/10168476/10069154/bf25ae14-62dc-11e5-819a-e6f7f41fdb62.png)

我是刷新一次传10个数据，下拉刷新一次后，再也不会调用下拉刷新的方法

**Comment by CoderMJLee** [comment]
没有遇到过这样的问题哈，会不会是因为这样：你刷新完毕后并没有调用endRefreshing结束刷新，导致一直在那里转圈圈。要不你详细参考一下Demo？

**Comment by jianghaibing** [comment]
IOS9,我也遇到同样问题

**Comment by jianghaibing** [comment]
已解决，在数据请求完成后调用endRefreshing，ok
