### ISSUE TITLE
快速下拉crash

### ISSUE THREAD

**Issue by 1036938520** [CoderMJLee/MJRefresh#33]
控件快速下拉，当拉到最下面的时候，程序会crash。

**Comment by CoderMJLee** [comment]
希望能贴出报错信息，因为我这边测试不出这个结果，谢谢哈

**Comment by 1036938520** [comment]
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds for empty array'

**Comment by CoderMJLee** [comment]
这个错误是数组越界错误，跟刷新框架是没关系的哈，框架内部不存在数组操作。我猜是数据的处理问题，比如self.data[较大的索引]导致越界

**Comment by 1036938520** [comment]
好的

**Comment by qiang437587687** [comment]
MJ 哥 真的是太热心了.. 谢谢~

**Comment by guoxuanlaiye** [comment]
请问楼主问题解决了没？我也遇到了和你一样的问题，但数组检查好久没有可改的地方啊？

**Comment by CoderMJLee** [comment]
if (index < count || index >=0 ) {
    self.data[index]
}

**Comment by guoxuanlaiye** [comment]
问题解决了  感谢MJ哥

**Comment by feiadan** [comment]
dfvdfvdfvdsfvdfvdfvdfvdfvdfvsfdvsv

**Comment by feiadan** [comment]
fvfv

**Comment by 1036938520** [comment]
对了，什么时候MJRefresh支持webview

**Comment by CoderMJLee** [comment]
你可以试试[webView.scrollView addLegendHeader....];因为webView内部有个scrollView

**Comment by 1036938520** [comment]
3q

**Comment by 1036938520** [comment]
addHeaderWithTarget:(id)target action:(SEL)action，没有用

**Comment by CoderMJLee** [comment]
你要下载最新的框架代码哈，addHeader已经过期了，改为addLegendHeader

**Comment by 1036938520** [comment]
在一个页面，如果数据没有铺满整个屏幕，那个加载更多怎么调整可以不显示

**Comment by 1036938520** [comment]
还有个问题，上拉加载，加载完后，加载控件没有消失，仍然在tabview底部

**Comment by 1036938520** [comment]
加载的时候，正在加载更多的数据总是闪烁不定

**Comment by CoderMJLee** [comment]
不显示加载更多：self.tableView.footer.hidden = YES;
加载完毕后，应该结束刷新状态吧：[footer endRefreshing];
闪烁不定是啥意思？有动态图看看么？或者Demo
