### ISSUE TITLE
semantic issue duplicate declaration of category

### ISSUE THREAD

**Issue by qisedao0215** [CoderMJLee/MJRefresh#331]
编译后出现了4个警告。

**Comment by CoderMJLee** [comment]
啥警告信息？

**Comment by qisedao0215** [comment]
Pods/MJRefresh/MJRefresh/Base/MJRefreshComponent.h:91:12: Duplicate definition of category 'MJRefresh' on interface 'UILabel'

**Comment by qisedao0215** [comment]
不好意思，这4个警告。是因为我的头文件添加错误导致的。

**Comment by blusewang** [comment]
能说的详细一些吗？我也遇到了

**Comment by binbins** [comment]
use this way
 #import <MJRefresh/MJRefresh.h>
