### ISSUE TITLE
iOS 9 项目中 加载更多不能隐藏了。

### ISSUE THREAD

**Issue by XBear1986** [CoderMJLee/MJRefresh#333]
dataTableView.footer.hidden = YES;   这句不起作用了？

**Comment by CoderMJLee** [comment]
默认情况下：一旦reloadData后，MJRefresh会自动根据有无数据来显示和隐藏footer。如果你不希望有这个功能，可以这么写
```objc
self.tableView.footer.automaticallyHidden = NO;
```

**Comment by XBear1986** [comment]
多谢，我是想没有更多数据的时候，就隐藏掉加载更多。
以前：1、dataTableView.footer.hidden = YES; 2、 reloadData  在Xcode 7下编译，基于iOS 9，这样就不能隐藏footer了，之前是可以隐藏的。
现在修改为：1、reloadData 2、dataTableView.footer.hidden = YES 就可以隐藏了。

**Comment by CoderMJLee** [comment]
嗯嗯，建议的顺序是先reloadData，再hidden哈
