### ISSUE TITLE
控件很给力,一直用,但最近发现一问题

### ISSUE THREAD

**Issue by yuanshuainiuniu** [CoderMJLee/MJRefresh#337]
当重设tableView的contentSize后,刷新后又回到原来的size了,求解

https://github.com/yuanshuainiuniu/lyfen5.0-

**Comment by CoderMJLee** [comment]
是感觉是因为你设置footerView是collectionView的原因，tableView和collectionView都是scrollView，混合使用容易出问题哈。底部九宫格，搞个UIView试试？

**Comment by yuanshuainiuniu** [comment]
嗯,好吧,你觉得淘宝首页是怎么做的?scrollView?tableView?collectionView?或tableView+collectionView?

**Comment by CoderMJLee** [comment]
scrollView

**Comment by yuanshuainiuniu** [comment]
好,了解,谢谢.

**Comment by CoderMJLee** [comment]
不客气哈
