### ISSUE TITLE
用block回调代码块里使用[self.tableView.header beginRefreshing]后没反应，还导致下拉效果失效，求解

### ISSUE THREAD

**Issue by Tate-zwt** [CoderMJLee/MJRefresh#339]
以下为代码： 
  WTWeakSelf
    odvc.reloadDataTableView = ^(){
        weakSelf.dataArray = nil;
        
        [weakSelf.tableView.header beginRefreshing];
        
//        [self.tableView.header beginRefreshing];
    };

**Comment by CoderMJLee** [comment]
你调了这个block没？
```objc
odvc.reloadDataTableView();
```

**Comment by Tate-zwt** [comment]
调用了，打了断点代码都有执行到的

**Comment by Tate-zwt** [comment]
用最新的MJRefresh，就没问题了😄
