### ISSUE TITLE
如果能加上webview下拉刷新，想来也是极好的

### ISSUE THREAD

**Issue by xujiajia** [CoderMJLee/MJRefresh#34]
用混合框架的越来越多 如果webview的下拉刷新加上 就更完美了 要不只能转头别的框架了

**Comment by CoderMJLee** [comment]
谢谢提醒，有哪些webView下拉刷新框架可以推荐下么？我借鉴一下，看看需要哪些功能

**Comment by AllLuckly** [comment]
大神你好，我是菜鸟，下载了你发的上下刷新，感觉很好，但是我下拉加载更多的page+=20应该调用什么方法啊？

**Comment by CoderMJLee** [comment]
你的意思加载20条数据？这个需要你设置服务器的请求参数

**Comment by heistings** [comment]
这个问题是不是可以关了？

**Comment by KBvsMJ** [comment]
可以通过webview中的scrollerview来实现上下拉刷新功能
