### ISSUE TITLE
使用MJRefreshAutoNormalFooter的时候，pop出当前页面时候崩溃。

### ISSUE THREAD

**Issue by johnsonlrd** [CoderMJLee/MJRefresh#340]
很奇怪的问题，退出页面的时候崩溃，说是没有移除对TableView的contentOffset和contentSize的KVO。我看了一下源代码，杰哥你是在MJRefreshComponent里面添加的KVO的。我在ViewController的dealloc方法里面移除对TableView的KVO才不崩溃。你知道是为什么吗，杰哥？
下面是我报错日志：
UMLOG: error: session_id=BF4CF3BA5085FCEF4F84DF5F602449F5, context=An instance 0x12f1eac00 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x130210540> (
<NSKeyValueObservance 0x12efb8fa0: Observer: 0x12ef87a70, Key path: contentOffset, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x130090d60>
<NSKeyValueObservance 0x130210510: Observer: 0x12ef87a70, Key path: contentSize, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x13014f190>
)
(null)
((
    0   CoreFoundation                      0x00000001831ecf74 <redacted> + 148
    1   libobjc.A.dylib                     0x0000000197de3f80 objc_exception_throw + 56
    2   CoreFoundation                      0x00000001831ecea4 <redacted> + 0
    3   Foundation                          0x00000001840aab60 <redacted> + 300
    4   libobjc.A.dylib                     0x0000000197dfdae8 <redacted> + 508
    5   CoreFoundation                      0x00000001830d0b6c _CFAutoreleasePoolPop + 28
    6   CoreFoundation                      0x00000001831a20c8 <redacted> + 1636
    7   CoreFoundation                      0x00000001830d0dc0 CFRunLoopRunSpecific + 384
    8   GraphicsServices                    0x000000018e224088 GSEventRunModal + 180
    9   UIKit                               0x00000001887aaf44 UIApplicationMain + 204
    10  CarIn                               0x000000010022dc48 main + 124
    11  libdyld.dylib                       0x000000019860e8b8 <redacted> + 4
)

**Comment by CoderMJLee** [comment]
这个情况偶尔有时候才会出现，有时间我检查下哈。暂时的解决方案是：
```objc
- (void)viewWillDissappear
{
    [super viewWillDissappear];
    self.tableView.header = nil;
    self.tableView.footer = nil;
}
```

**Comment by BetrayalPromise** [comment]
+1
