### ISSUE TITLE
上拉加载更多 无法关闭

### ISSUE THREAD

**Issue by quanweiwang** [CoderMJLee/MJRefresh#342]
self.table.footer.hidden = YES;
设置了,但是还是有上拉加载更多出现

同时 我也出现cell数组越界的情况
例如 屏幕可以显示8条cell
我数组里就4个数据
我先下啦刷新载入4个数据
再上拉更多重新载4个数据,总共就8个数据了
这时我再下啦刷新 就出现数组越界了,断点发现cell的indexPath.row是5 然而数组只有4个对象

**Comment by 1414648814** [comment]
我也有这个问题啊，求解决啊啊啊啊啊

**Comment by CoderMJLee** [comment]
```objc
footer.automaticallyHidden = NO;
```
