### ISSUE TITLE
属性字符串的二次处理

### ISSUE THREAD

**Issue by gq630960023** [CoderMJLee/MJRefresh#343]
因服务器设定, 所有的dictionary中的string都进行了 URLEncode . 所以在生成的模型中的string属性, 全部没有解析.
如图.
<img width="378" alt="urlencode" src="https://cloud.githubusercontent.com/assets/3872235/10425084/678005f4-7107-11e5-87ab-e4fe1f60bd1e.png">

请问, 这种情况有没有相应的解决办法, 可以在生成过程中就进行 URLDecode

**Comment by CoderMJLee** [comment]
```objc
[User setupNewValueFromOldValue:^id(id object, id oldValue, MJProperty *property) {
        if ([property.name isEqualToString:@"nick"]) {
               return 转码后的字符串;
        }
        return oldValue;
    }];
```

**Comment by gq630960023** [comment]
在 User 中 写入
,,,javeScript
+(void)load{
    [NHUserModel setupNewValueFromOldValue:^id(id object, id oldValue, MJProperty *property) {
        if ([property.name isEqualToString:@"nick"]) {
            return [property.name decodedString];
        }
        
        return oldValue;
    }];
}
,,,
是否是可行的?

**Comment by gq630960023** [comment]
测试为可行, THX.
如果没问题.请close
