### ISSUE TITLE
上拉加载MJRefreshAutoNormalFooter如何在没有更多数据的情况下移除？

### ISSUE THREAD

**Issue by ApesTalk** [CoderMJLee/MJRefresh#352]
你好，我在程序中使用了MJRefreshAutoNormalFooter，设置了footer.triggerAutomaticallyRefreshPercent = 0.1;当我从后台接口返回的标志hasNextPage=0的时候要把这个footer给移除，我是这么用的：
table.footer = hasNextPage==1?self.loadFooter:nil;
但是页面显示不正常，table下面有一部分显示空的，并没有占满屏幕。
如图：
![111](https://cloud.githubusercontent.com/assets/5499434/10485583/911bd386-72bd-11e5-8633-c101ef57a198.png)

请问怎么处理才会让tableview铺满整个屏幕呢？

**Comment by CoderMJLee** [comment]
建议这么用
```objc
// 只需要在viewDidLoad中创建一次，以后就用hidden属性控制显示或者隐藏
tableView.footer.hidden = YES\NO; 
```

**Comment by lqcjdx** [comment]
试了这种的，不行，hidden之后还是tableview不能铺满屏幕。设置footer的高度为0也不行。
我是这么处理的：
再定义一个footer：
MJRefreshAutoNormalFooter *footer1 = [[MJRefreshAutoNormalFooter alloc]initWithFrame:CGRectZero];
        footer1.state = MJRefreshStateIdle;
        footer1.mj_h = 0;//重新设置高度
        footer1.clipsToBounds = YES;//不让看不到菊花
然后在没有更多数据可以加载的情况下设置table.footer=footer1，有更多数据的情况下设置为原来的footer.

**Comment by bawn** [comment]
强制隐藏 `self.tableView.mj_footer.hidden = YES;` 还是不可以
