### ISSUE TITLE
有Section的TableView，在刷新过程中滚动会出现Section错位问题

### ISSUE THREAD

**Issue by lexiaoyao20** [CoderMJLee/MJRefresh#353]
如题，这个有没有解决方案啊

**Comment by wyhazq** [comment]
换一个，谢谢，这个框架里面的下拉控件处理了这个问题https://github.com/zhuchaowe/EasyIOS

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈
