### ISSUE TITLE
上拉刷新后，tableview会的contentoffset会网上跳一段距离

### ISSUE THREAD

**Issue by zcrhappy** [CoderMJLee/MJRefresh#359]
代码是这样的：
- (void)pullUpToRefresh{
  //获取到数据后的block
  ^{
  //填充数据的dataSource
          dispatch_async(dispatch_get_main_queue(), ^{
              [_tableview.footer endRefreshing];
              [_tableview reloadData];
          });
  }
  }

这时候tableview会位置会跳到上方已有的几个cell的位置。
请问怎么办，有人遇到吗？

**Comment by XAmateur** [comment]
contentOffSet 的值变了 我不知道MJ要怎么处理这个？
比较low的做法就是记住当前contentOffSet的值，然后再设置一下就可以

**Comment by CoderMJLee** [comment]
调换顺序试试？
```objc
[_tableview reloadData]; 
 [_tableview.footer endRefreshing]; 
```

**Comment by XAmateur** [comment]
调换顺序也不OK啊。 有空你再看，不是什么大问题。

场景：
1.当tableview没有做上拉更多操作时，点击tableviewcell进入详情页、back回来，这时contentOffset没有问题
2.当tableview操作一次上拉更多时，点击tableviewcell进入详情页、back回来，这时的contentOffset变小了一些

**Comment by xiaoboJoin** [comment]
这个问题解决了吗？版本: 'MJRefresh', '~> 3.0.7',还是出现这个问题，求解！

**Comment by xiaoboJoin** [comment]
方案一：会跳动 
//        self.mj_footer = [BMYRefreshAutoGifFooter footerWithRefreshingBlock:^{
//            if (weakSelf.actionBlock)
//            {
//                weakSelf.actionBlock(TableViewActionMore);
//            }
//        }];



方案二： 不会跳动，没时间查原因了，先贴上
  Giffooter = [MJRefreshAutoGifFooter footerWithRefreshingTarget:self refreshingAction:@selector(footerTrigger)];
    // 设置正在刷新状态的动画图片
    [Giffooter setImages:refreshingImages forState:MJRefreshStateRefreshing];
    // 隐藏状态
    Giffooter.stateLabel.hidden = YES;
    Giffooter.refreshingTitleHidden = YES;
    self.mj_footer = Giffooter;

**Comment by KakaMic** [comment]
一样 碰到这个问题 有解了吗

**Comment by KakaMic** [comment]
一样 碰到这个问题 有解了吗
