### ISSUE TITLE
footer 能不能使用beginRefreshing

### ISSUE THREAD

**Issue by wangbiye** [CoderMJLee/MJRefresh#361]
我用header的时候beginRefreshing是正常工作的,后来尝试了让footer也执行这个方法,不过好像没用,特来确认一下.如果不行的话怎么样才能让加载第一页的时候footer就处于刷新状态

**Comment by CoderMJLee** [comment]
我试过了，可以使用的
```objc
[self.tableView.footer beginRefreshing];
```

**Comment by kingyangtao** [comment]
发自我的小米手机

Biye Wang <notifications@github.com>编写：

**Comment by angBiu** [comment]
好像没效果。。。
