### ISSUE TITLE
关于本地化/国际化的问题

### ISSUE THREAD

**Issue by megumi-kato** [CoderMJLee/MJRefresh#362]
首先感谢一下这个项目，真的很好用！
然后就是本地化的问题了，我发现虽然可以通过自定义文字来实现_部分_的本地化，但是貌似那个“最后更新： 今天。。。”这部分没有可以实现本地化的方式（没仔细看，只是阅读了一下参考文档所以不是很确定

重点来了。。像我这种懒人。。一般都是用默认的啦，我不知道别人是不是也这样，所以本地化这块，是否存在优化的必要，以提升体验

祝好，
     Ironyyy

**Comment by CoderMJLee** [comment]
谢谢建议，我会考虑增加本地化功能

**Comment by CoderMJLee** [comment]
暂时可以使用以下属性解决
```objc
/** 利用这个block来决定显示的更新时间文字 */
@property (copy, nonatomic) NSString *(^lastUpdatedTimeText)(NSDate *lastUpdatedTime);
```

**Comment by CoderAO** [comment]
正好我也在搞这个本地化功能,如果给每个scrollView都定义提示文字感觉略麻烦,又不想派生一个基类使用.希望有更好的解决办法

**Comment by lych0317** [comment]
这个现在好像还没有个很好的解决方案吧！我们现在是修改源代码，但是每次更新时都要再改一次，太麻烦了。
