### ISSUE TITLE
为什么没有自动刷新头部的控件呢？

### ISSUE THREAD

**Issue by TheWalkingDead1024** [CoderMJLee/MJRefresh#363]
比如说获取旧的聊天记录，肯定不是下拉刷新呀，应该是下拉自动去刷新，为什么没有这样的控件呢？

**Comment by CoderMJLee** [comment]
```objc
[self.tableView.header beginRefreshing];
```

**Comment by TheWalkingDead1024** [comment]
@CoderMJLee ,你好，你们有提供MJRefreshFooter，为什么就不能给一个autoheader呢？我现在模仿你们的MJRefreshFooter去实现一个autoheader，还是挺麻烦的，呵呵。

**Comment by TheWalkingDead1024** [comment]
@CoderMJLee ，不好意思写错了，是MJRefreshAutoFooter。

**Comment by CoderMJLee** [comment]
这套控件不是给聊天记录那种界面使用的哈，需要人为下拉刷新

**Comment by TheWalkingDead1024** [comment]
@CoderMJLee ,OK, 谢谢啦。

**Comment by CoderMJLee** [comment]
不客气

**Comment by kingyangtao** [comment]
发自我的小米手机

M了个J <notifications@github.com>编写：
