### ISSUE TITLE
一个collection内嵌套两个Table的bug

### ISSUE THREAD

**Issue by iPermanent** [CoderMJLee/MJRefresh#364]
如果在一个collectionView里嵌套两个tableView，然后设置好两个tableView的footer和header以后，只有第二个Table里的才有效果，第一个Table的上拉和下拉都没有设置进去，我记得这个使用的类方法不是单例的吧？为何会出现这个bug呢？
![fae50728-1bb1-4ea8-b47c-53b3df38e85b](https://cloud.githubusercontent.com/assets/1712759/10627090/07accd32-77e8-11e5-9227-7857ec40f000.png)

**Comment by CoderMJLee** [comment]
贴出代码看看？
