### ISSUE TITLE
我在同一个controller中添加了多个header和footer,在dealloc时发生崩溃

### ISSUE THREAD

**Issue by zzlmilk** [CoderMJLee/MJRefresh#37]
我在同一个controller中添加了多个header和footer,在dealloc调用free方法时发生崩溃~
![Uploading 1.jpg . . .]()
![Uploading image.png . . .]()

**Comment by CoderMJLee** [comment]
free方法是很久以前的用法了哈，你可以看看最新MJRefresh用法，没有提供free方法了，都是框架内部自己管理内存的
