### ISSUE TITLE
在iOS9.1下，如果不显示time和state，开始显示动画图片的时候位置会错

### ISSUE THREAD

**Issue by imyellow** [CoderMJLee/MJRefresh#372]
如图：
![](http://ww1.sinaimg.cn/large/5f789f8fgw1exflidhd0zg208w0487wh.gif)

在iOS8的时候没有问题，我找了一下，发觉是 `MJRefreshHeader.m` 的 `setState` `MJRefreshStateRefreshing` 的时候的动画导致的。

**Comment by CoderMJLee** [comment]
希望能发一个Demo给我，便于我及时修复哈，谢谢
