### ISSUE TITLE
能不能知道最后一次操作是上拉还是下拉？

### ISSUE THREAD

**Issue by zingos** [CoderMJLee/MJRefresh#373]
headerWithRefreshingBlock里面执行的方法是网络请求数据，那么如果请求完毕后，如何判断之前的用户的操作是上拉的还是下拉的呢

**Comment by vaintwyt** [comment]
网络请求的方法如果支持透传额外的参数（不上传到后台，只是在回包的时候，透传给回调方法），就可以在请求的的时候，加上下拉还是上拉的标记，在返回数据的回调那里，取出来。

**Comment by CoderMJLee** [comment]
@vaintwyt 正解。也可以通过判断self.tableView.header.isRefreshing和self.tableView.footer.isRefreshing来确实是上拉还是下拉
