### ISSUE TITLE
带有section header的tableView如何使用MJRefresh？

### ISSUE THREAD

**Issue by vaintwyt** [CoderMJLee/MJRefresh#374]
由于section header不随tableView滚动，所以下拉刷新后（未收回，还在loading），往上滑动tableView，section header不会回到最顶部，固定。而是在一开始loading的下方固定。

请问这种情况如何解决？

另外，如果由两个scrollView 嵌套两个tableView实现的多列表格，有办法使用MJRefresh吗？或者有其他刷新组件可以替代？

感谢！

**Comment by mryun11** [comment]
section header的问题已经纠结了几个版本了，一直没能解决。。。

**Comment by wyhazq** [comment]
换一个，谢谢，这个框架里面的下拉控件处理了这个问题https://github.com/zhuchaowe/EasyIOS

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈
