### ISSUE TITLE
能否支持collectionView的横向滚动加载？

### ISSUE THREAD

**Issue by GoldFriedRice** [CoderMJLee/MJRefresh#377]
如题

**Comment by lcccch** [comment]
顶！急需这功能！

**Comment by AgentEric** [comment]
Hi,MJ老师好，能否添加支持横向刷新的功能。谢谢

**Comment by CoderMJLee** [comment]
Sorry, 不支持哦

**Comment by GoldFriedRice** [comment]
可否添加这个功能呢？因为平时有用到这方面的，觉得没有这个功能比较难做出效果，感谢！ 发自网易邮箱大师 在2015年11月07日 11:25 ，M了个J写道： Sorry, 不支持哦 — Reply to this email directly or view it on GitHub.
