### ISSUE TITLE
能用这个框架实现对普通UIViewController的刷新吗？

### ISSUE THREAD

**Issue by jbasttdi** [CoderMJLee/MJRefresh#38]
MJ您好，在项目中用了你的MJRefresh感觉很方便，但不知这个框架能不能对普通UIViewController进行刷新呢，实现像对TableView进行上拉，下拉时的效果。这要很多页面中就不需要加个刷新按钮了。
谢谢了。

**Comment by CoderMJLee** [comment]
这跟UIViewController没有联系，只要你是一个UIScrollView（UITableView和UICollectionView包含在内），就能使用刷新功能
