### ISSUE TITLE
CollectionView reloadData 有时会出现闪烁的问题

### ISSUE THREAD

**Issue by ancoo** [CoderMJLee/MJRefresh#380]
CollectionView reloadData 有时会出现闪烁 不丝滑 
不知道是不是collectionView自己的问题 
各位有没有解决方法

**Comment by loumzy** [comment]
CollectionView reloadData 每次都会重新加载，会出现闪烁的现象，可以通过插入的方式

[self.collectionView performBatchUpdates:^{
                
              [self.collectionView insertItemsAtIndexPaths:[NSArray arrayWithObjects:[NSIndexPath indexPathForItem:2 inSection:0]]];
                
      } completion:nil];

**Comment by ancoo** [comment]
@loumzy 原来如此 学习了 多谢多谢

**Comment by AzenXu** [comment]
endRefresh之后，延时0.01秒再reloadData即可解决
