### ISSUE TITLE
SectionView无法滚动到最顶部

### ISSUE THREAD

**Issue by zingos** [CoderMJLee/MJRefresh#381]
TableView实现了这个方法，返回了一个SectionView
-(UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
还同时设置了UITableViewHeadView

这个时候开始下拉刷新，数据还在读取，然后将TableView向上滑动，这时SectionView是不会移动到最顶部的，中间有一段间隙，这个间隙的高度正好是MJRefresh的下拉刷新View的高度，这么怎么破？

**Comment by wyhazq** [comment]
换一个，谢谢，这个框架里面的下拉控件处理了这个问题https://github.com/zhuchaowe/EasyIOS

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈

**Comment by cyvoit** [comment]
请参考 #400
