### ISSUE TITLE
UIScrollView+MJRefresh.m的源码中有一个手动触发KVO的错误

### ISSUE THREAD

**Issue by zhanjiarong** [CoderMJLee/MJRefresh#384]
98~100行的内容如下：
[self willChangeValueForKey:@"reloadDataBlock"]; // KVO
objc_setAssociatedObject(self, &MJRefreshReloadDataBlockKey, reloadDataBlock, OBJC_ASSOCIATION_COPY_NONATOMIC);
 [self willChangeValueForKey:@"reloadDataBlock"]; // KVO

最后一行应该是：(不知道是MJ哥有特别的想法还是手误，我目前认为是写错了)
 [self didChangeValueForKey:@"reloadDataBlock"]; // KVO

**Comment by CoderMJLee** [comment]
哈哈哈，sorry哈，是我自己写错了

**Comment by CoderMJLee** [comment]
在最新的源码中已经改掉了哈
