### ISSUE TITLE
 引发mj_reloadData 方法的循环递归调用

### ISSUE THREAD

**Issue by BeyondVincent** [CoderMJLee/MJRefresh#385]
在程序中启动完成会调用[self.tableView.header beginRefreshing];进行网络请求时，一切正常没有问题。
但是写了一个单元测试，单元测试中有网络请求。此时会在Xcode中发生[self mj_reloadData]; 方法的循环递归调用，然后程序挂了。
如果把如下方法中的  [self mj_reloadData]; 注释掉就不会引发问题。
- (void)mj_reloadData
  {
  [self mj_reloadData];
  
  [self executeReloadDataBlock];
  }

如需提供更多信息，可以qq联系我：77973689（破船）。

**Comment by CoderMJLee** [comment]
可以贴出具体的调用代码么？比如reloadData和endRefreshing，谢谢

**Comment by sdaheng** [comment]
我有一个页面也出现了这种情况，tableView reloadData 完 endRefreshing 一直重复调用了我的加载更多的请求方法。在获取完数据以后 调用的reloadData 和 endRefreshing，这个和我datasource数组的格式没什么关系吧？没有出现问题的页面是这种格式的@[ @[ @"", @"", @"" ] ]，出现问题的页面的格式是@[ @"", @"", @"" ], @[ @"", @"", @"" ]

**Comment by wangchaodong** [comment]
我在swift2.0中也遇到这个情况. 
我使用alamofire请求网络, 处理好返回的json后,我 
'''
self.timeCollectionView.reloadData()
'''
不会一直出现楼上说的情况, 一旦多次请求(多次异步reloadData)后, 就必回crash.
如需提供更多信息，可以qq联系我：776466614  :)

**Comment by lqcjdx** [comment]
@BeyondVincent 大神怎么解决的？

**Comment by yuhanle** [comment]
这个地方如果注释掉，会不会有其他的影响？
