### ISSUE TITLE
初始化时经常 crash，断在currentCalendar

### ISSUE THREAD

**Issue by shannonchou** [CoderMJLee/MJRefresh#386]
![image](https://cloud.githubusercontent.com/assets/3939980/10992282/7588cf04-849f-11e5-9239-374b62739916.png)

![image](https://cloud.githubusercontent.com/assets/3939980/10992276/6e396024-849f-11e5-8ee0-b4421e1648d3.png)

**Comment by CoderMJLee** [comment]
你是MRC环境么？

**Comment by shannonchou** [comment]
是ARC。也是最近才发现的。似乎是发生在iOS 9 上。而且线上也出现大量异常。
Application received signal SIGSEGV
(null)
((
	0   CoreFoundation                      0x00000001858e4f60 <redacted> + 148
	1   libobjc.A.dylib                     0x000000019a497f80 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001858e4e90 <redacted> + 0
	3   ????                        0x00000001005e6584 UmengSignalHandler + 128
	4   libsystem_platform.dylib            0x000000019aec593c _sigtramp + 52
	5   CoreFoundation                      0x00000001857cb6a0 <redacted> + 668
	6   CoreFoundation                      0x00000001857ed298 CFDictionaryCreateCopy + 148
	7   CoreFoundation                      0x0000000185884324 <redacted> + 564
	8   CoreFoundation                      0x0000000185820fbc CFCalendarSetLocale + 176
	9   CoreFoundation                      0x0000000185820ee0 CFCalendarCopyCurrent + 84
	10  CoreFoundation                      0x0000000185820db4 <redacted> + 40
	11  ????                        0x00000001005ab478 -[MJRefreshStateHeader setLastUpdatedTimeKey:] + 376
	12  ????                        0x00000001005a9950 -[MJRefreshHeader prepare] + 88
	13  ????                        0x00000001005ab724 -[MJRefreshStateHeader prepare] + 56
	14  ????                        0x00000001005aa674 -[MJRefreshNormalHeader prepare] + 56
	15  ????                        0x00000001005a79d4 -[MJRefreshComponent initWithFrame:] + 80
	16  ????                        0x00000001005a98c0 +[MJRefreshHeader headerWithRefreshingTarget:refreshingAction:] + 76
	17  ????                        0x00000001002baa98 _TTSf4g___TFCX13wHuwGEcqHdDJp27JCPGCListBaseViewController12setupRefreshfS0_FT_T_ + 104
	18  ????                        0x00000001002ba290 _TFCX13wHuwGEcqHdDJp27JCPGCListBaseViewController12setupRefreshfS0_FT_T_ + 20
	19  ????                        0x00000001002b9b84 _TFCX13wHuwGEcqHdDJp27JCPGCListBaseViewController11viewDidLoadfS0_FT_T_ + 1120
	20  ????                        0x00000001002b6544 _TTSf4g___TFCX13wHuwGEcqHdDJp27JCPGCHandpickViewController11viewDidLoadfS0_FT_T_ + 48
	21  ????                        0x00000001002b53bc _TToFCX13wHuwGEcqHdDJp27JCPGCHandpickViewController11viewDidLoadfS0_FT_T_ + 28
	22  UIKit                               0x000000018ae78098 <redacted> + 996
	23  UIKit                               0x000000018ae77c9c <redacted> + 28
	24  ????                        0x000000010025c3a8 _TTSf4s_g___TFCX13wHuwGEcqHdDJp12CAPSPageMenu14addPageAtIndexfS0_FSiT_ + 724
	25  ????                        0x0000000100252300 _TTSf4g___TFCX13wHuwGEcqHdDJp12CAPSPageMenu22configureUserInterfacefS0_FT_T_ + 2436
	26  ????                        0x00000001002502f8 _TTSf4gs_s_g_n___TFCX13wHuwGEcqHdDJp12CAPSPageMenucfMS0_FT15viewControllersGSaCSo16UIViewController_5frameVSC6CGRect15pageMenuOptionsGSqGSaOS_18CAPSPageMenuOption___S0_ + 996
	27  ????                        0x000000010024e148 _TFCX13wHuwGEcqHdDJp12CAPSPageMenuCfMS0_FT15viewControllersGSaCSo16UIViewController_5frameVSC6CGRect15pageMenuOptionsGSqGSaOS_18CAPSPageMenuOption___S0_ + 104
	28  ????                        0x00000001002c76d8 _TTSf4g___TFCX13wHuwGEcqHdDJp24JCPGCSlideViewControllerP33_76A2EF7D2961BB9A0BF5E64E770995CA13setupPageMenufS0_FT_T_ + 584
	29  ????                        0x00000001002c56c4 _TToFCX13wHuwGEcqHdDJp24JCPGCSlideViewController11viewDidLoadfS0_FT_T_ + 112
	30  UIKit                               0x000000018ae78098 <redacted> + 996
	31  UIKit                               0x000000018af37580 <redacted> + 72
	32  UIKit                               0x000000018af37458 <redacted> + 416
	33  UIKit                               0x000000018af366a0 <redacted> + 144
	34  UIKit                               0x000000018af36244 <redacted> + 868
	35  UIKit                               0x000000018af35e6c <redacted> + 60
	36  UIKit                               0x000000018af35dd4 <redacted> + 208
	37  UIKit                               0x000000018ae737ac <redacted> + 644
	38  QuartzCore                          0x000000018a672b58 <redacted> + 148
	39  QuartzCore                          0x000000018a66d764 <redacted> + 292
	40  QuartzCore                          0x000000018a66d624 <redacted> + 32
	41  QuartzCore                          0x000000018a66ccc0 <redacted> + 252
	42  QuartzCore                          0x000000018a66ca08 <redacted> + 512
	43  QuartzCore                          0x000000018a6660f8 <redacted> + 80
	44  CoreFoundation                      0x000000018589bbd0 <redacted> + 32
	45  CoreFoundation                      0x0000000185899974 <redacted> + 372
	46  CoreFoundation                      0x0000000185899da4 <redacted> + 928
	47  CoreFoundation                      0x00000001857c8ca0 CFRunLoopRunSpecific + 384
	48  GraphicsServices                    0x0000000190a04088 GSEventRunModal + 180
	49  UIKit                               0x000000018aee0ffc UIApplicationMain + 204
	50  ????                        0x000000010024243c main + 216
	51  libdyld.dylib                       0x000000019ace68b8 <redacted> + 4
)

dSYM UUID: B67C3B35-CFAD-3089-BE1F-8C907230DDF4
CPU Type: arm64
Slide Address: 0x0000000100000000
Binary Image: ????
Base Address: 0x00000001000a4000

**Comment by shannonchou** [comment]
![image](https://cloud.githubusercontent.com/assets/3939980/10996279/b1aabc94-84be-11e5-8820-e16dc523369c.png)

**Comment by ytqiu** [comment]
也遇到同样的问题了，貌似使用currentCalendar的库都会挂，不清楚是不是iOS的bug。不知道有没有什么方案可以绕过去？

**Comment by CoderMJLee** [comment]
每一次使用都会么？

**Comment by ytqiu** [comment]
不是每次都会触发。目前还没有找到可重现的操作路径。随机出现。

**Comment by CoderMJLee** [comment]
能不看发出前面的报错信息看看，比如reason后面的信息

**Comment by ytqiu** [comment]
没在前面发现有报错信息。我这边的错误输出和LZ哥们基本上一样的。*** -[CFString retain]: message sent to deallocated instance 0x7f940bd09180。感觉很奇怪， 说是这个String已经释放了。但是其实这里不看到哪里使用了String。

**Comment by ytqiu** [comment]
+ (NSCalendar *)xxx_currentCalendarForChina {
    if (SYSTEM_VERSION_GREATER_THAN(@"8.0")) {
        return [NSCalendar calendarWithIdentifier:NSCalendarIdentifierChinese];
    }
    
    return [NSCalendar currentCalendar];
}
我怀疑是iOS9系统引入的bug。我添加了一个分类，把原来统一的currentCalendar获取日历的方式改成了iOS8.0之后使用较新的API。目前多次运行还未出过crash。有类似问题的朋友可以试试。

**Comment by shannonchou** [comment]
@ytqiu 我也感觉像是iOS 9的问题，我的报错的系统版本都是iOS9 的，还没找到更早系统报这个问题。

**Comment by shannonchou** [comment]
感谢@ytqiu 我马上用下你的方法验证一段时间看看

**Comment by CoderMJLee** [comment]
@shannonchou 等你消息哈

**Comment by ytqiu** [comment]
我这边一天用下来没有crash过。不知道@shannonchou 那边情况怎么样？

**Comment by shannonchou** [comment]
@ytqiu @CoderMJLee 我这里也用了一天了，没有crash。赞👍

**Comment by ytqiu** [comment]
那麻烦@CoderMJLee 抽空把这个改动同步到MJRefresh吧。

**Comment by shannonchou** [comment]
@ytqiu 你也可以创建个pull request

**Comment by ytqiu** [comment]
恩。好的。

**Comment by CoderMJLee** [comment]
谢谢

**Comment by xilin** [comment]
我这并没有在iOS9.x上出现日历相关的crash。确定是currentCalendar引起的吗？我的应用中有不少日历计算的。

**Comment by shannonchou** [comment]
@xilin 的确不是用到的都crash。我的也是一定概率，只是概率比较高。其他也有遇到的但是概率比较低。所以我怀疑跟多线程还有一定关系。我有一些用到currentCalendar 的类是在后台线程调用的。我猜想在多线程环境下调用currentCalendar 可能会触发。

**Comment by xilin** [comment]
@shannonchou 嗯，我基本上是在主线程里用的。
