### ISSUE TITLE
把mjrefresh封装到framework里，下拉刷新箭头无法显示的问题

### ISSUE THREAD

**Issue by XJYao** [CoderMJLee/MJRefresh#387]
MJ大神，您好。

当我把mjrefresh封装到framework里，这时下拉刷新是无法显示出箭头的，因为图片实际上并不是直接在工程目录下，而是在工程目录/xxxFramework.framework/ 下。所以导致图片无法读取。

以下是您加载箭头图片的代码

// 图片路径
#define MJRefreshSrcName(file) [@"MJRefresh.bundle" stringByAppendingPathComponent:file]
#define MJRefreshFrameworkSrcName(file) [@"Frameworks/MJRefresh.framework/MJRefresh.bundle" stringByAppendingPathComponent:file]

- (UIImageView *)arrowView
{
    if (!_arrowView) {
        UIImage *image = [UIImage imageNamed:MJRefreshSrcName(@"arrow.png")] ?: [UIImage imageNamed:MJRefreshFrameworkSrcName(@"arrow.png")];
        UIImageView *arrowView = [[UIImageView alloc] initWithImage:image];
        [self addSubview:_arrowView = arrowView];
    }
    return _arrowView;
}

请问这种情况该如何解决呢？

另外，不知道您是否提供了修改箭头图片的方法，如果有麻烦告诉我一下，我没有找到。 如果没有，建议提供接口。

谢谢！

**Comment by CoderMJLee** [comment]
```objc
@interface MJRefreshNormalHeader : MJRefreshStateHeader
@property (weak, nonatomic, readonly) UIImageView *arrowView;
/** 菊花的样式 */
@property (assign, nonatomic) UIActivityIndicatorViewStyle activityIndicatorViewStyle;
@end
```

**Comment by XJYao** [comment]
谢谢！

**Comment by CoderMJLee** [comment]
不客气

**Comment by whpanda** [comment]
这不是readonly吗？怎么设置？

**Comment by whpanda** [comment]
> ```objc
> @interface MJRefreshNormalHeader : MJRefreshStateHeader
> @property (weak, nonatomic, readonly) UIImageView *arrowView;
> /** 菊花的样式 */
> @property (assign, nonatomic) UIActivityIndicatorViewStyle activityIndicatorViewStyle;
> @end
> ```

readonly怎么设置？？？

**Comment by wolfcon** [comment]
继承 `MJRefreshStateHeader`, 自己写
