### ISSUE TITLE
下拉刷新页面闪烁

### ISSUE THREAD

**Issue by shuoshi** [CoderMJLee/MJRefresh#39]
下拉刷新时，如果动作幅度比较大，不等scrollview停止滑动即松手刷新，会发现页面闪烁

在MJRefreshHeaderView.m的observeValueForKeyPath监听MJRefreshContentOffset

NSLog(@"%f", self.scrollView.mj_contentOffsetY);

会发现offset持续变小后突然变为-64，然后再变小，最后维持在-64

我修改了一下

} else if (self.state == MJRefreshStatePulling) {// 即将刷新 && 手松开
        // 开始刷新
        CGFloat top = self.scrollViewOriginalInset.top + self.mj_height;
        if (currentOffsetY >= -top) {
            self.state = MJRefreshStateRefreshing;
        }
    }

在设置状态变为MJRefreshStatePulling的时候判断下当前offset是否已经大于
header高度，在这个条件满足的情况下刷新就不会出现offset突变为-64再变小的问题了

**Comment by CoderMJLee** [comment]
试试最新版2.0版本哈，可以参考README和Demo
