### ISSUE TITLE
一个用户体验的问题

### ISSUE THREAD

**Issue by tangzzz-fan** [CoderMJLee/MJRefresh#394]
我在使用的过程中，发现mj_header在刷新完毕之后，是被隐藏在导航栏之后的，当下拉动作产生时，会从上面位移到tableView的头部。这在导航栏alpha较低的情况下体验不好，能够明显的看到藏在导航栏后面的header，我查看header的头文件，没有找到可以修改header隐藏时的颜色或者其他设置方法。

**Comment by CoderMJLee** [comment]
header.automaticallyChangeAlpha = YES;

**Comment by tangzzz-fan** [comment]
谢谢杰哥，是我之前没有好好在实现文件中找。
