### ISSUE TITLE
MJ的下拉刷新时间机制设置的又问题呀

### ISSUE THREAD

**Issue by dami7786** [CoderMJLee/MJRefresh#396]
应该是在执行endRefresh的时候记录本次下拉刷新完成的时间，在下次下拉刷新刚刚开始的时候设置lastUpdatedTimeLabel的text显示；
MJ现在的设置是在每次设置状态的时候更新lastUpdatedTimeLabel的text；：

```
- (void)setState:(MJRefreshState)state
{
    MJRefreshCheckState

    // 设置状态文字
    self.stateLabel.text = self.stateTitles[@(state)];

    // 重新设置key（重新显示时间）
    self.lastUpdatedTimeKey = self.lastUpdatedTimeKey;
}
```

而保存时间是设置在state == MJRefreshStateIdle时候：

```
- (void)setState:(MJRefreshState)state
{
    MJRefreshCheckState

    // 根据状态做事情
    if (state == MJRefreshStateIdle) {
        if (oldState != MJRefreshStateRefreshing) return;

        // 保存刷新时间
        [[NSUserDefaults standardUserDefaults] setObject:[NSDate date] forKey:self.lastUpdatedTimeKey];
        [[NSUserDefaults standardUserDefaults] synchronize];
  ...     
```

**Comment by GabrielOmarBatistuta** [comment]
#pragma mark - 日历获取在9.x之后的系统使用currentCalendar会出异常。在8.0之后使用系统新API。
- (NSCalendar *)currentCalendar {
    if ([NSCalendar instancesRespondToSelector:@selector(calendarWithIdentifier:)]) {
        return [NSCalendar calendarWithIdentifier:NSCalendarIdentifierGregorian];
    }
    return [NSCalendar currentCalendar];
}

我这里也是  DEBUG调试时，经常定位到这个方法里。
日志错误：*** -[CFString retain]: message sent to deallocated instance 0x7f8fe2405870

**Comment by CoderMJLee** [comment]
@GabrielOmarBatistuta 试试3.0.4版本

**Comment by GabrielOmarBatistuta** [comment]
@CoderMJLee 好的
