### ISSUE TITLE
isAutomaticallyHidden的问题

### ISSUE THREAD

**Issue by 21074223** [CoderMJLee/MJRefresh#399]
footer的 isAutomaticallyHidden默认是YES，tableView在刚出现的时候，footer是隐藏的。我在网上获取到数据后，不调用reloadData，而是调用reloadSections:withRowAnimation:，那么tableView的footer就会一直隐藏着。

**Comment by CoderMJLee** [comment]
目前isAutomaticallyHidden只支持reloadData哈，所以可以考虑人为控制footer的hidden
