### ISSUE TITLE
下拉刷新删除全部数据的话崩溃

### ISSUE THREAD

**Issue by boboGoodMan** [CoderMJLee/MJRefresh#40]
当在tabVIew 里在下啦刷新的方法里把所有数据全部删除的话，程序会崩溃；或者把所有数据全部删除，在从网络异步获取的话也会出问题。
*** Assertion failure in -[UITableView _configureCellForDisplay:forIndexPath:], /SourceCache/UIKit/UIKit-2935.138/UITableView.m:6509

**Comment by CoderMJLee** [comment]
从方法名可以看出：这是cell和数据处理问题，跟刷新框架没有关系的哈

**Comment by boboGoodMan** [comment]
我看了一下，貌似是跟tabview冲突，您可以试一下在您的demo里单纯删除数据试一下


发送自魅族手机

-------- 原始邮件 --------
发件人：M了个J <notifications@github.com>
时间：周六 2月28日 11:57
收件人：CoderMJLee/MJRefresh <MJRefresh@noreply.github.com>
抄送：boboGoodMan <guanjiangbo@126.com>
主题：Re: [MJRefresh] 下拉刷新删除全部数据的话崩溃 (#40)

**Comment by CoderMJLee** [comment]
你删除完数据后，要进行reloadData或者reloadRows，这是tableView的正确用法哈。跟刷新框架没关系的

**Comment by boboGoodMan** [comment]
[self.fakeData removeAllObjects];
//    [self.tableView reloadData];
//    [self.tableView headerEndRefreshing];
    
    
    dispatch_async(dispatch_get_global_queue(0, 0), ^{
        for (int i = 0; i<5; i++) {
            [self.fakeData insertObject:MJRandomData atIndex:0];
        }
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.tableView reloadData];
            [self.tableView headerEndRefreshing];

        });
    });


我这样写的话是会出问题的

**Comment by CoderMJLee** [comment]
嗯，那也是数据处理的问题。你就算不用刷新框架，也还是有问题的。你的异步操作时间太短，导致插入数据和刷新表格的先后顺序不稳定

**Comment by boboGoodMan** [comment]
dispatch_async(dispatch_get_global_queue(0, 0), ^{
        [self.fakeData removeAllObjects];
        for (int i = 0; i<5; i++) {
            [self.fakeData insertObject:MJRandomData atIndex:0];
        }
        dispatch_async(dispatch_get_main_queue(), ^{
            [self.tableView reloadData];
            [self.tableView headerEndRefreshing];

        });
    });
这样写的话就没有问题，如果我在工程里去重新获取数据，并且网速非常好的话，这样异步操作时间肯定也短，难道需要延时操作？

**Comment by CoderMJLee** [comment]
你的思路很正确，不用延迟的。其实一般的步骤就是去子线程拿数据，拿完数据就去主线程刷新。拿数据的话一般用的是异步请求框架，不用自己写gcd的dispatch_asyc代码

**Comment by boboGoodMan** [comment]
3q,我貌似已经理通了，是我写的本身跟tabview的重用机制冲突了。
