### ISSUE TITLE
下拉刷新和UITableView的section headerView冲突

### ISSUE THREAD

**Issue by zijiejue** [CoderMJLee/MJRefresh#400]
当下拉刷新状态时，section headerView的位置错乱了

**Comment by CoderMJLee** [comment]
这个问题正在修复哈，近期会搞定的

**Comment by syhuanggz** [comment]
临时紧急修复可以参考这里： https://github.com/telly/TLYShyNavBar/issues/30 ，其实也勉强算是系统API的一个未考虑全面的场景吧~，即使不适用mjrefresh，通过更改contentInset也是存在这个问题的

**Comment by syhuanggz** [comment]
简单修复：
- (void)scrollViewDidScroll:(UIScrollView *)scrollView{
    if(self.tableView.header.state == MJRefreshHeaderStateRefreshing){
        CGFloat offsetY = scrollView.contentOffset.y >= -54 ? scrollView.contentOffset.y : -54;
        CGFloat insetTop = MIN(offsetY,0);
        [scrollView setContentInset:UIEdgeInsetsMake(-insetTop, 0.0, 0.0, 0.0)];
    }
}

**Comment by CoderMJLee** [comment]
试试最新的3.0.7版本，应该完美解决SectionHeader问题了哈

**Comment by syhuanggz** [comment]
估计还要解决sectionFooter的问题，以及他们同时存在的问题
```objecttive-c
- (void)scrollViewDidScroll:(UIScrollView *)scrollView{
    if([self.viewModel isNeedToShowProgressViewInContentView:scrollView]){
        [self showProgressViewWhenScroll];
    }else{
        [self.progressView changeToState:ScrollProgressViewStateHidden];
    }
    if(self.tableView.header.state == MJRefreshHeaderStateRefreshing){
        CGFloat offsetY = MAX(scrollView.contentOffset.y,-54);
        CGFloat insetTop = MIN(offsetY,0);
        [scrollView setContentInset:UIEdgeInsetsMake(-insetTop, 0.0, 0.0, 0.0)];
    }else{
        CGFloat insetBottom = 0.0;
        if(!scrollView.footer.hidden)insetBottom = 44.0;
       [scrollView setContentInset:UIEdgeInsetsMake(0.0, 0.0, insetBottom, 0.0)];
    }
    //NSLog(@"inset y:%f,%f",scrollView.contentInset.top,scrollView.contentInset.bottom);
}
```

**Comment by koalahl** [comment]
hi, 3.0.7版本是不是还没到CocoaPods里面呀？cocoapads中最新的是3.0.4

**Comment by cyvoit** [comment]
我clone了最新的代码（commit 709e3ab），当下拉刷新状态时，section headerView的位置没问题了。
不过上拉松开立即加载更多的时候section headerView（图示灰色部分）会抖动一下。旧版本也会抖动。
![screen shot 2016-05-26 at 10 45 33](https://cloud.githubusercontent.com/assets/8186665/15562148/3e428d80-232f-11e6-865d-03ec3092aa4e.png)
