### ISSUE TITLE
现在项目是好的，集成其他的没问题，只要用cocospod集成就报错，试了好几个版本都是这个问题

### ISSUE THREAD

**Issue by IslandMask** [CoderMJLee/MJRefresh#403]
提示no such file or directory:"...MJExtension-dummy.m"这个文件,还有一个是no input files。我用的7.1

**Comment by CoderMJLee** [comment]
是MJRefresh还是MJExtension？你可以先试试pod repo update

**Comment by IslandMask** [comment]
昨天更新了下cocospods，今天集成地图也是报错，一样的错误，最后手动集成的，李校长知道为啥会报错不，集成了afn和mjextension没问题，集成mjrefresh报错，地图也报错

**Comment by CoderMJLee** [comment]
报错信息可以贴出来么？

**Comment by IslandMask** [comment]
![1 2d tf6k7dk34t j3v2](https://cloud.githubusercontent.com/assets/13137044/11237745/a43751a0-8e1c-11e5-826b-a276dcebb597.jpg)

**Comment by CoderMJLee** [comment]
Google 百度下"-dummy.m"

**Comment by IslandMask** [comment]
搜了，没有具体解决方法，都是些不相关的
