### ISSUE TITLE
“点击或上拉加载更多”这几个字，能不能只有在上拉的情况下再显示。

### ISSUE THREAD

**Issue by meloanyang** [CoderMJLee/MJRefresh#404]
如果数据源不足一页，“点击或上拉加载更多”这几个字就会出现在页面上，怎么样设置，才能达到我说的那种效果【只有在上拉的情况下显示】

**Comment by reinventgithub** [comment]
在Demo中搜索“点击或上拉加载更多”，改成“”

**Comment by meloanyang** [comment]
你理解错了。。我要的效果是，无论界面上否有数据，“点击或上拉加载更多”以及左边的转圈，都默认隐藏在界面的下方，只有上拉才会出现。。。

**Comment by lucifer001** [comment]
我也出现了相同的问题，“点击或上拉加载更多”几个字在无数据或数据不够多的情况下 会显示在tableView的上方而不是下方。

**Comment by CoderMJLee** [comment]
@meloanyang 请使用MJRefreshBackNormalFooter

**Comment by meloanyang** [comment]
@CoderMJLee 谢谢，我用了MJDIYBackFooter，定制了一个。用这个也可以吧？？

**Comment by CoderMJLee** [comment]
可以的

**Comment by Rookie920** [comment]
我看到mj里有国际化，但是是跟随系统的，现在我想跟随app的语言请问怎么设置
