### ISSUE TITLE
杰哥,   scrollView 下拉刷新有问题

### ISSUE THREAD

**Issue by S-Freedom** [CoderMJLee/MJRefresh#406]
旧版本的scrollView 下拉刷新header 没有刷新的过程,而且松开手会很快的向上滚动一块,而且拉的越下,回去的越多.   最新版的scrollView 无法下拉啊, 杰哥.
//    self.scrollView.mj_header = [MJRefreshHeader headerWithRefreshingTarget:self refreshingAction:@selector(requestProjectDetail)];
    self.scrollView.mj_header = [MJRefreshHeader headerWithRefreshingBlock:^{
        NSLog(@"ss");
    }];   这样不调用,是我写错了吗

**Comment by CoderMJLee** [comment]
请使用MJRefreshNormalHeader，不是MJRefreshHeader哈

**Comment by thomas0326** [comment]
恩,好的,  多谢杰哥哈
