### ISSUE TITLE
cocoapods 3.0.2版本 DEBUG调试时经常崩溃

### ISSUE THREAD

**Issue by GabrielOmarBatistuta** [CoderMJLee/MJRefresh#407]
定位到的错误行：

#pragma mark - 日历获取在9.x之后的系统使用currentCalendar会出异常。在8.0之后使用系统新API。

(NSCalendar *)currentCalendar { if ([NSCalendar instancesRespondToSelector:@selector(calendarWithIdentifier:)]) { return [NSCalendar calendarWithIdentifier:NSCalendarIdentifierGregorian]; } return [NSCalendar currentCalendar]; }
我这里也是 DEBUG调试时，经常定位到这个方法里。

日志错误：*** -[CFString retain]: message sent to deallocated instance 0x7f8fe2405870

**Comment by CoderMJLee** [comment]
试试3.0.4版本

**Comment by VictDog** [comment]
今天在使用您的这个框架的时候,报错出现在这一行if (NSFoundationVersionNumber >= NSFoundationVersionNumber_iOS_8_0) , 提示信息为:Use of undeclared identifier 'NSFoundationVersionNumber_iOS_8_0'. 后来我打印了一下系统版本,在NSObjCRuntime.h 里加上了#define NSFoundationVersionNumber_iOS_8_0 1144.170000 然后就解决了报错. 然后我来github 准备提交这个错误,发现您已经更新 . 看来是我离线下载的版本比较老所出现的问题吧.

**Comment by GabrielOmarBatistuta** [comment]
@CoderMJLee pod上最新版是3.0.3  求更新3.0.4-3.0.5

**Comment by CoderMJLee** [comment]
已经更新，pod repo update
