### ISSUE TITLE
在UITabbarVController 中其中一个页面出现动画 刷新动画 未完成 的提示？

### ISSUE THREAD

**Issue by PCfans** [CoderMJLee/MJRefresh#409]

**Comment by PCfans** [comment]
提示如下：Unbalanced calls to begin/end appearance transitions for <PLAlertsVC

**Comment by RainbowMango** [comment]
我也出现了类似的问题，目前没有解决方案。

我有4个tab，当从第一个tab push时才会出现。目前发现跟MJRefresh无关

**Comment by PCfans** [comment]
恩恩，跟我一样情况，你发现是什么情况了么，我还没找到
