### ISSUE TITLE
MJ哥 关于下拉刷新

### ISSUE THREAD

**Issue by yuchuanfeng** [CoderMJLee/MJRefresh#41]
MJ哥 您好, 我用了你的下拉刷新控件, 如果想让控制器一加载就自动刷新 , 需要将
[self.tableView headerBeginRefreshing]; 放在 [self.tableView  addHeaderWithTarget:self action:@selector(refreshStart)]; 后面才能 正常自动 刷新, 这个算不算个小Bug呀

**Comment by CoderMJLee** [comment]
谢谢提醒，一开始就是这么设计的哈：先添加回调方法，然后再开始刷新。有空我看能不能再改进下
