### ISSUE TITLE
杰哥，我用的最新得MJRefresh，有个bug

### ISSUE THREAD

**Issue by LvJianfeng** [CoderMJLee/MJRefresh#411]
使用self.tableView.mj_footer的，没有mj_footer，只有footer。也就是你git readme中demo code是测试的？

**Comment by CoderMJLee** [comment]
试试pod repo update更新成最新版本

**Comment by LvJianfeng** [comment]
嗯嗯 我用的是2.4.12的，谢谢杰哥啊。😄
