### ISSUE TITLE
Swift 工程header不能自动隐藏

### ISSUE THREAD

**Issue by RainbowMango** [CoderMJLee/MJRefresh#412]
Hello 杰哥，

我的是swift工程，发现header view不能自动隐藏，一直显示在那里。
代码如下：

class CompanyListTableViewController: UITableViewController {

    var tableHeader: MJRefreshNormalHeader = MJRefreshNormalHeader()
    var tableFooter: MJRefreshBackNormalFooter = MJRefreshBackNormalFooter()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        //添加下拉刷新控件
        tableHeader = MJRefreshNormalHeader(refreshingTarget: self, refreshingAction: "tableHeaderRefresh")
        self.tableView.tableHeaderView = tableHeader
        
        //添加上拉刷新控件
        tableFooter = MJRefreshBackNormalFooter(refreshingTarget: self, refreshingAction: "tableFooterRefresh")
        self.tableView.tableFooterView = tableFooter

view初次展现效果如下：
![Uploading Simulator Screen Shot 2015年11月21日 下午6.18.11.png…]()

下拉一次效果如下：
![Uploading Simulator Screen Shot 2015年11月21日 下午6.26.17.png…]()

另外，关于footer，上拉刷新后没有更多数据怎么修改成"没有更多了"？

**Comment by RainbowMango** [comment]
![simulator screen shot 2015 11 21 6 18 11](https://cloud.githubusercontent.com/assets/8268873/11318066/4893f5ec-907e-11e5-8daa-78d1ac1144dc.png)

初次展现效果

**Comment by CoderMJLee** [comment]
用法是这样的哈
```objc
self.tableView.mj_header =  MJRefreshNormalHeader(refreshingTarget: self, refreshingAction: "tableHeaderRefresh");
self.tableView.mj_footer = MJRefreshBackNormalFooter(refreshingTarget: self, refreshingAction: "tableFooterRefresh");
```
如果需要显示“没有更多”
```objc
[self.tableView.mj_footer endRefreshingWithNoMoreData];
```

**Comment by RainbowMango** [comment]
多谢杰哥快速support. "没有更多"解决了。
self.tableFooter.endRefreshingWithNoMoreData()

Swift里没有mj_header，mj_header。
我的开发环境是Xcode7.1.1,  IOS7.1, Swift.  
MJRefresh: pod 'MJRefresh', '~> 3.0.4'

所以，header不能自动隐藏的问题还没解决。杰哥没理解么？
换个说法，没加header前，table view的第一个cell是紧接着导航栏的。
加了header，第一个cell和导航栏有一段空白，如上图。

**Comment by RainbowMango** [comment]
查了很多资料，发现跟MJRefresh无关，这是IOS7引入的一个特性，scrollview的第一个子view自动留白。没找到很好的解决办法，暂时用了个tricky的办法...

//解决tableview和导航之间留白--方案1，留白尺寸=状态栏高度+导航栏的高度+10
        let navbarHeight = self.navigationController?.navigationBar.frame.height
        let statusBarHeight = UIApplication.sharedApplication().statusBarFrame.height
        self.tableView.contentInset = UIEdgeInsetsMake(0 + 10 - statusBarHeight - navbarHeight!, 0, 0, 0)
        
        //解决tableview和导航之间留白--方案2，会导致第一个cell被导航栏遮挡一部分
        //self.automaticallyAdjustsScrollViewInsets = false

**Comment by CoderMJLee** [comment]
你是用了group样式的tableView么？

**Comment by RainbowMango** [comment]
当然没有，Plain和Group都试过的。

**Comment by CoderMJLee** [comment]
没有mj_header和mj_footer属性，那有没有header和footer属性？

**Comment by RainbowMango** [comment]
没有的。Swift下只能像我这么用。我发现有几个人遇到同样的困惑了。我还没看你的源码，也没搞明白原因。

tableHeader = MJRefreshNormalHeader(refreshingTarget: self, refreshingAction: "tableHeaderRefresh")

self.tableView.tableHeaderView = tableHeader

tableFooter = MJRefreshAutoNormalFooter(refreshingTarget: self, refreshingAction: "tableFooterRefresh")

self.tableView.tableFooterView = tableFooter




--

天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为，所以动心忍性，曾益其所不能。

在 2015-11-22 14:14:54，"M了个J" <notifications@github.com> 写道：


没有mj_header和mj_footer属性，那有没有header和footer属性？

**Comment by 20120608** [comment]
if #available(iOS 11.0, *) {
            table.contentInsetAdjustmentBehavior = .never
        }

**Comment by 309598016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by RainbowMango** [comment]
GitHub的通知让我想起当年搞的小项目了，好怀旧啊。
大家新年好！
