### ISSUE TITLE
MJRefresh header not compatible with TLYShyNavBar

### ISSUE THREAD

**Issue by tuantmdev** [CoderMJLee/MJRefresh#413]
In my project, i used both of those libraries but i got 1 issue with refresh header. It appears under navigation bar (maybe the content offset or content size of uitableview changed when using TLYShyNavBar).

Any idea to fix this? Thanks so much!

**Comment by CoderMJLee** [comment]
```objc
self.tableView.mj_header.ignore....InsetTop = ....;
```

**Comment by tuantmdev** [comment]
I tried both YES and NO but nothing change!

**Comment by CoderMJLee** [comment]
set a CGFloat value, not a BOOL value

**Comment by tuantmdev** [comment]
Thanks for your help, but still not working. The refresh header seems on right position when i pull down. But when i release, the loading icon move back to old position even when it's still loading.

Here is the screenshot for more detail

Before using TLYShyNavBar

![Before integrate with TLYShyNavBar](http://i.imgur.com/LITZui0.png)

After using TLYShyNavBar. The loading icon show under nav bar

![After integrate with TLYShyNavBar](http://i.imgur.com/yTvVD6y.png)
