### ISSUE TITLE
setLastUpdatedTimeKey崩溃，iOS8.3

### ISSUE THREAD

**Issue by meway24** [CoderMJLee/MJRefresh#415]
杰哥，更新到3.0.7，发现会导致崩溃
![bug2](https://cloud.githubusercontent.com/assets/1956079/11359499/aa888ce6-92b7-11e5-8727-cafa21126501.png)

**Comment by CoderMJLee** [comment]
试试最新的3.0.5？上一个其实是3.0.4。是偶尔崩溃，还是经常？

**Comment by meway1991** [comment]
额，是3.0.4的版本，偶尔崩溃

**Comment by meway1991** [comment]
更新了3.0.5的版本，目前没有测试出崩溃，之前出现主要是APP第一次安装打开会崩溃
