### ISSUE TITLE
下拉刷新的过程中有时候会出现，整个tableview向上移动的情况

### ISSUE THREAD

**Issue by ianisme** [CoderMJLee/MJRefresh#42]
下拉刷新的过程中有时候会出现，整个tableview向上移动的情况，希望您看一下

**Comment by CoderMJLee** [comment]
这个问题比较鲜有哈，希望你能发个demo到邮箱，谢谢

**Comment by ianisme** [comment]
我就是把你提供的Demo放在真机上测试，因为之前用EGO有卡顿问题，所以我就疯狂的测试你这个Demo，发现有时候会出现这个情况，只是轻微的移动。不是必现的。

我的手机是 iPhone5 7.1.2系统的

**Comment by dong09000** [comment]
这个问题我遇到过,你重写一下
MJRefreshHeaderView.m文件中的这部分代码修改下试试

//#warning 这句代码修复了，top值不断累加的bug
//#warning if判断修复了top值递减的bug 11月20 by-if_done
                    if (self.scrollView.mj_contentInsetTop == 0) {
                        self.scrollView.mj_contentInsetTop = 0;
                    } else if (self.scrollViewOriginalInset.top == self.scrollView.mj_contentInsetTop || self.scrollView.mj_contentInsetTop >= MJRefreshViewHeight * 2)
                    {
                        self.scrollView.mj_contentInsetTop -= self.mj_height;
                    }else
                    {
                        self.scrollView.mj_contentInsetTop = self.scrollViewOriginalInset.top;
                    }

**Comment by ianisme** [comment]
@dong09000 谢谢！
