### ISSUE TITLE
下拉刷新

### ISSUE THREAD

**Issue by l19901001** [CoderMJLee/MJRefresh#420]
MJ 你好,在使用框架时, 在下拉刷新中,如果不设置闲置状态的 image, 我直接调用 endRefresh 结束刷新的情况下.为什么在开始刷新设置好的动画,在 endRefresh 后在导航栏后面还是在执行动画.而且第二次下拉的时候,动画也一直存在.

**Comment by CoderMJLee** [comment]
3.0.6，已经修复。之前没有考虑过不设置idle图片的情况哈，sorry。
