### ISSUE TITLE
明杰老师好，新版的用了看不到刷新图片了，箭头文字，菊花都没有……

### ISSUE THREAD

**Issue by SKiiGitHub** [CoderMJLee/MJRefresh#423]
替换新版的刷新就没图了。
以为是项目的问题，自己写了个tableview的demo也没有。有写了个scrollView的demo也没有…
iOS8.4.1，xcode7.1

**Comment by CoderMJLee** [comment]
你用的是哪个类？MJRefreshNormalHeader?不要用错了哈，不要用MJRefreshHeader哦

**Comment by SKiiGitHub** [comment]
我用MJRefreshHeader了，改过来了。以前都用的这个是有图的，一下子没有了没想到这块。谢谢老师

**Comment by CoderMJLee** [comment]
不客气
