### ISSUE TITLE
loadingView position in placeSubviews 

### ISSUE THREAD

**Issue by davidear** [CoderMJLee/MJRefresh#425]
I got a problem is :
When I subclass MJRefreshNormalHeader and override the function placeSubviews, I change the arrowView's position by directly setting frame or constraint, the loadingView's position does not changed with it.
I look into the original code, the loadIngView's center is aligned with arrowView. But the loadView's position is already set before the subclass's function placeSubviews is called. So how can I solve the problem rather than forking the repository and changing the code?
thanks!

**Comment by CoderMJLee** [comment]
```objc
- (void)placeSubviews
{
    [super placeSubviews];
    self.arrowView.frame = ...;
    self.loadingView.frame = ...; // or self.loadingView.center = ...;
}
```

**Comment by davidear** [comment]
Yes, that is the way to do it.  
In MJRefreshNormalHeader.m:
@property (weak, nonatomic) UIActivityIndicatorView *loadingView;  
The the loadingView property is internal property of Header. I can't visit it, so if possible to put the property in .h
