### ISSUE TITLE
如何滑动到底部自动加载呢？

### ISSUE THREAD

**Issue by hengchengfei** [CoderMJLee/MJRefresh#43]
最好有一个属性设置一下，即是否自动加载

**Comment by CoderMJLee** [comment]
谢谢提醒，我有空就增加一个这个功能。当初设计的时候没想过做成自动加载哈，个人比较喜欢手动加载，sorry

**Comment by hengchengfei** [comment]
添加好后，能否邮件通知一下啊

**Comment by CoderMJLee** [comment]
嗯，我会这里通知你

**Comment by hengchengfei** [comment]
有没一个属性设置上拉无效？
应用场景是：当页面没有数据时，上拉是没有意义的。或者返回的数据没有更多了，能设置其无效就好了。

**Comment by CoderMJLee** [comment]
self.tableView.footerHidden = YES;

**Comment by hongdong** [comment]
同等自动加载、、、

**Comment by BaiCanLin** [comment]
同等自动加载、、、

**Comment by mg459046365** [comment]
同等自动加载！

**Comment by Coneboy-k** [comment]
我尝试修了改为自动加载，与逻辑耦合度比较大。但也能成功。这个期待，@CoderMJLee  来完善 :D。
@CoderMJLee 的方案是修改contentInSet来显示 footer。 这么做的结果，导致，刷新前滚到哪，刷新完还滚到哪。修改为 微信朋友圈那种，自动加载。只能调整自己的逻辑代码。

**Comment by kevinMkY** [comment]
MJ哥加油!~~

**Comment by yorling** [comment]
MJ哥加油!~~

**Comment by CoderMJLee** [comment]
已经集成这个功能，大家可以看看最新的示例代码哈

**Comment by hengchengfei** [comment]
MJ牛

**Comment by hengchengfei** [comment]
为何滑动到底部自动加载时，会一直闪呢

**Comment by Coneboy-k** [comment]
我这的block 调用了多次。  你先结束 刷新状态， 在进行刷新cell 。   
是KVO 导致响应多次。

**Comment by CoderMJLee** [comment]
你试试最新的代码，我记得今天我调整了一下。如果还不行，希望发一个Demo到我邮箱哈，谢谢

**Comment by hengchengfei** [comment]
MJ哥，非常感谢您了。

另外，uicollectionview的gif动画好像不支持block刷新了，setRefreshingTarget是可以的。
self.collectionView.gifHeader.refreshingBlock

**Comment by CoderMJLee** [comment]
我试过了，refreshingBlock回调肯定有效的。你再看看哪里不太对哈

**Comment by hengchengfei** [comment]
MJ哥，能否加一下qq啊（58551038）或者加您的。

新版本，还有一个问题是，添加footer时，会自动执行加载更多，不像以前的方式了吗，先加载再手动调用方法。

[self.collectionView addLegendFooter];

**Comment by CoderMJLee** [comment]
Sorry，不太明白你的描述？！

**Comment by hengchengfei** [comment]
您好，MJ。

demo发到您的qq邮箱了。非常感谢。
－－－－－－－－－－－－－－－
首次运行时，在block内部打上断点，会发现第一次竟然也进入了。
不是应该在加载更多的时候才进入吗？
self.collectionView.footer.refreshingBlock = ^{
｝

**Comment by hengchengfei** [comment]
您好，MJ。

demo发到您的qq邮箱了。非常感谢。
－－－－－－－－－－－－－－－
首次运行时，在block内部打上断点，会发现第一次竟然也进入了。
不是应该在加载更多的时候才进入吗？
self.collectionView.footer.refreshingBlock = ^{
｝

**Comment by CoderMJLee** [comment]
你的Demo我看完了，没有一点问题哈。你调用的是[self.collectionView.gifHeader beginRefreshing]，所以header. refreshingBlock被调用了，而footer.refreshingBlock没有被调用啊。。。你看错了吧

**Comment by hengchengfei** [comment]
请问MJ，如何去掉“加载更多”，当没有网络的时候，会显示出来，我希望这个不要显示的。

麻烦了。

**Comment by CoderMJLee** [comment]
直接来个self.tableView.footer.hidden = YES;

**Comment by hengchengfei** [comment]
下拉刷新的动画，在首次进入Controller时，动画有一个位置移动的过程，即从左侧滑动中间位置。
是不是因为隐藏了state原因？

**Comment by hengchengfei** [comment]
MJ哥,你的demo里的MJCollectionViewController,要在 self.collectionView.footer.refreshingBlock前面加上 self.collectionView.footer.automaticallyRefresh =NO;
,不然的话,当数据变大的时候,首次会进入的时候,也会进入 self.collectionView.footer.refreshingBlock

**Comment by CoderMJLee** [comment]
你试试最新的代码，我记得已经修复过了

**Comment by hengchengfei** [comment]
MJ哥,我刚下的最新的demo,在MJCollectionViewController.m里第38行,把5换成25,首次进来时, 打个断点后,发现他会进入到self.collectionView.footer.refreshingBlock 里

**Comment by CoderMJLee** [comment]
谢谢提醒，已修复

**Comment by hengchengfei** [comment]
谢谢MJ，不好意思，老是麻烦您了。

下拉动画的图的问题能帮忙看一下吗，就是刚进入的时候，图片是从左侧划入到顶部中心的。

**Comment by CoderMJLee** [comment]
我已经修复刚开始会出现动画这个问题了

**Comment by chenjianAgain** [comment]
#pragma mark - 公共方法
#pragma mark 设置状态
- (void)setState:(MJRefreshHeaderState)state
{
    if (self.state == state) return;
    
    // 旧状态
    MJRefreshHeaderState oldState = self.state;
    
    NSArray *images = self.stateImages[@(state)];
    if (images.count != 0) {
        switch (state) {
            case MJRefreshHeaderStateIdle: {
                if (oldState == MJRefreshHeaderStateRefreshing) {
                    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(MJRefreshSlowAnimationDuration * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                        self.pullingPercent = 0.0;
                    });
                } else {
                    self.pullingPercent = self.pullingPercent;
                }
                break;
            }
                
            case MJRefreshHeaderStatePulling:
            case MJRefreshHeaderStateRefreshing: {
                [self.gifView stopAnimating];
                if (images.count == 1) { // 单张图片
                    self.gifView.image = [images lastObject];
                } else { // 多张图片
                    self.gifView.animationImages = images;
                    self.gifView.animationDuration = images.count * 0.1;
                    [self.gifView startAnimating];
                }
                break;
            }
                
            default:
                break;
        }
    }
    
    // super里面有回调，应该在最后面调用
    [super setState:state];
}


    这样一句赋值  self.pullingPercent = self.pullingPercent; 是为啥呢？谢谢

**Comment by CoderMJLee** [comment]
这是设置下拉的百分比，执行set方法里面的代码

**Comment by wys13114** [comment]
如果想实现网易新闻那种到底部自动加载改如何实现呐
