### ISSUE TITLE
iOS9 tableviewheader为searchbar的时候下拉时显示有问题

### ISSUE THREAD

**Issue by JinWuZhao** [CoderMJLee/MJRefresh#431]
如下图
![pull-down-issue](https://cloud.githubusercontent.com/assets/4271558/11464585/5ceca61c-976b-11e5-82bf-6a46b43e4ae0.gif)

**Comment by JinWuZhao** [comment]
发现貌似和屏幕大小有关，iphone4上是正常的，5以上都不正常

**Comment by JinWuZhao** [comment]
ios7 iphone4真机上也不正常

**Comment by CoderMJLee** [comment]
就是滚动条会飘来飘去？

**Comment by JinWuZhao** [comment]
下拉的时候也看不到上方的提示文字

**Comment by horsley** [comment]
下拉的时候也看不到上方的提示文字 我这边也遇到这个问题

**Comment by Ailix** [comment]
数据不满一屏时mj_footer也偏到底部去了

**Comment by JinWuZhao** [comment]
下拉看不到提示文字的问题我找到解决方案了，把mj_header的初始化放到viewDidLoad里面就好了。原来的时候我放在了一个回调里，要延迟一会才初始化

**Comment by horsley** [comment]
@JinWuZhao 我的初始化也在viewDidLoad  依然有下拉看不到文字问题

**Comment by ClegeJJ** [comment]
同求这个问题..

tableView.tableheaderView = searchController.searchBar

就会为tableview加一个UIView 是自动伸缩的  正好挡住MJHeaderView

**Comment by ClegeJJ** [comment]
<img width="326" alt="2016-03-08 4 50 27" src="https://cloud.githubusercontent.com/assets/13790283/13596535/0c06bb80-e54e-11e5-8804-ee0b452f3d7e.png">


RT所示

**Comment by ClegeJJ** [comment]
<img width="403" alt="2016-03-08 4 54 23" src="https://cloud.githubusercontent.com/assets/13790283/13596599/79a6aeb6-e54e-11e5-9796-0c2a9252c70a.png">
突然看到上面的答案 解决了- -.. 

 先给tableview.mj_header 添加控件 再给tableview.tableheaderView添加searchbar就没有问题 ... 

不过还是请教下MJ老师- - ...为什么searchcontroller会莫名其妙给tableview加一个遮挡的view...

我加了您微信的 ~  微信号 : qinxin_Pis  

希望有空和MJ探讨学习~~

**Comment by KayonYang** [comment]
@Ailix mj_footer加了seachbar后跑到底部怎么让他跑上来

**Comment by hbxn740150254** [comment]
@Ailix @KayonYang  解决 tableheaderView 为 UISearchBar 时候，数据不满一屏，mj_footer文字一直在底部的问题，方案如下 包装一下UISearchBar 即可
UIView *view = [[UIView alloc] initWithFrame:(CGRect){0,0,SCREEN_WIDTH,44}];
[view addSubview:searchBar];
self.tableView.tableHeaderView = view;

**Comment by gonghonglou** [comment]
杰哥，求指教`MJRefresh`一个问题：    
`tableView.tableHeaderView = searchController.searchBar;` 时，`tableView`下拉出来的背景会变成更深一点的颜色，这时候`mj_header`就会有半截视图显示出来非常 ugly 啊。我现在的做法是
```
UIView *searchView = [UIView new];
[searchView addSubview:searchController.searchBar];
searchView.frame = CGRectMake(0, 0, self.view.frame.size.width, 44);
tableView.tableHeaderView = searchView;
```
但是这样有两个问题：    
1、横竖屏时`searchBar`的宽度不变
2、下拉刷新时`mj_header`会闪一下一道黑线    

该怎么解决呢？
或者`tableHeaderView`为`searchBar`时，怎么样令下拉出来的背景色和`tableView`的背景色保持一致呢？

![wechatimg1](https://cloud.githubusercontent.com/assets/14970112/20631818/c71e155a-b373-11e6-8c0f-71d186491764.png)

**Comment by gonghonglou** [comment]
杰哥，求指教`MJRefresh`一个问题：
`tableView.tableHeaderView = searchController.searchBar;` 时，`tableView`下拉出来的背景会变成更深一点的颜色，这时候`mj_header`就会有半截视图显示出来非常 ugly 啊。我现在的做法是
```
UIView *searchView = [UIView new];
[searchView addSubview:searchController.searchBar];
searchView.frame = CGRectMake(0, 0, self.view.frame.size.width, 44);
tableView.tableHeaderView = searchView;
```
但是这样有两个问题：
1、横竖屏时`searchBar`的宽度不变
2、下拉刷新时`mj_header`会闪一下一道黑线

该怎么解决呢？
或者`tableHeaderView为searchBar`时，怎么样令下拉出来的背景色和`tableView`的背景色保持一致呢？

![wechatimg2](https://cloud.githubusercontent.com/assets/14970112/20632009/3d76ead2-b375-11e6-802b-ab80ee1b1864.png)
