### ISSUE TITLE
'header' is deprecated: first deprecated in iOS 2.0 - 使用mj_header

### ISSUE THREAD

**Issue by stefansky** [CoderMJLee/MJRefresh#434]
self.tableView.header =  [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        NSLog(@"开始刷新数据");
        [self.tableView.header endRefreshing];
    }];

ios9中使用header提示过期,怎么解决???

**Comment by JinWuZhao** [comment]
根据提示，使用mj_header属性，header属性已经废弃了。

**Comment by stefansky** [comment]
最早期的版本是mj_header,后来更新版本后规范化了,一直使用的header 而且文档介绍上大家都是用header,是不是最近更新的版本有问题了???

**Comment by CoderMJLee** [comment]
没问题。现在统一使用mj_header才是最规范的
