### ISSUE TITLE
上拉加载控件显示问题：“已无更多数据”，当改变tableHeaderView后，显示位置出错

### ISSUE THREAD

**Issue by PanXueYang** [CoderMJLee/MJRefresh#438]
进入页面,只有一条数据,上拉会显示“已无更多数据”。这时候改变tableHeaderView，并且headerView高度+cell高度超过了屏幕，“已无更多数据”就会显示到最后一个cell里边。
还有一种情况是已无更多数据后，又下拉刷新,正好多了一条数据，“已无更多数据”也会显示到cell里边

**Comment by CoderMJLee** [comment]
改变headerView后，试试这个，让tableView的contentSize改变一下
```objc
[self.tableView reloadData];
```

**Comment by PanXueYang** [comment]
试过了，没有效果。视图加载完后,因为数据很少，“已无更多数据”已经加到了视图上，这时候改变tableView的contentSize(改变headerView，刷新增加了cell)，这个控件的位置就显示不正确了。

**Comment by CoderMJLee** [comment]
试试这个：
```objc
[self.tableView.mj_header layoutIfNeeded];
```

**Comment by codwam** [comment]
mj_footer 也出现了同样的问题。
reloadData 和 layoutIfNeeded 都没用。
我的tableHeaderView是用AutoLayout布局，Swift SnapKit。
@CoderMJLee

**Comment by ChunXu** [comment]
这个问题是因为没有在主线程刷新UI导致
