### ISSUE TITLE
上拉刷新与动态高度cell兼容有问题

### ISSUE THREAD

**Issue by guoguoli** [CoderMJLee/MJRefresh#439]
我在storyboard中通过约束和代码    ：
    self.tableView.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [weakSelf loadNewData];
    }];
    self.tableView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        [weakSelf loadMoreData];
    }];
    self.tableView.separatorColor = kOurGrayColor;
    self.tableView.estimatedRowHeight = kRowHeight;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
想要实现带刷新和动态高度变化的cell，但是出现一个问题就是上拉刷新根本停不下来，上拉刷新一直在调用loadMoreData。

**Comment by MrReN** [comment]
是有这个问题，并且很严重。应该还没做适配吧

**Comment by heyz-lzj** [comment]
estimatedRowHeight 设置大一点 可以解决这个问题

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
