### ISSUE TITLE
最新版设置     self.tableView.mj_footer.hidden = YES 无效 header倒是有效

### ISSUE THREAD

**Issue by juvenlie** [CoderMJLee/MJRefresh#440]
self.tableView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        NSLog(@"页面加载");
        [self.tableView.mj_footer endRefreshing];
    }];
    
    self.tableView.mj_footer.hidden = YES;

还是显示有上拉加载 如题 望解答

**Comment by CoderMJLee** [comment]
MJRefresh默认情况下会自动显示和隐藏footer，如果不希望有这个功能，可以这么做：
```objc
self.tableView.mj_footer.automaticallyHidden = NO;
```

**Comment by havthgem** [comment]
`automaticallyHidden` 并不适用于所有情况，这个只能判断 UITableView 的 DataSource 中是否为空，如果为空，才回隐藏。

但是特殊情况下，我加载的内容如果只有几条，并未能撑满当前屏，则 `mj_footer` 会在整个 UITableView 的当中显示，非常影响视觉体验。并且在确定之后不再有新数据的时候，也应当隐藏。一般我会处理为当新数据不足所设置的 limit 的时候，则会隐藏 `mj_footer`。

现在 `automaticallyHidden` 会在 `mj_footer.hidden = YES` 之后再次设置其 `hidden`。并不合理，而且在文档上也没有说明清楚。这样会给新手们挖了一个大坑。

**Comment by jb522185660** [comment]
的确如此

**Comment by bawn** [comment]
+1 
发现在 reloadData 执行完之后可以调整 mj_footer，但是如果一开始设置 
```
self.collectionView.mj_footer.hidden = YES;
```
那么之后 self.collectionView.mj_footer.hidden = NO; 会无效

**Comment by CoderMJLee** [comment]
已经将automaticallyHidden默认值改为NO
