### ISSUE TITLE
with navigation bar transparent and UIRectEdgeAll, gif header view is not hidden

### ISSUE THREAD

**Issue by peiweichen** [CoderMJLee/MJRefresh#444]
<img width="370" alt="screen shot 2015-12-03 at 2 57 21 pm" src="https://cloud.githubusercontent.com/assets/6760710/11553957/8fd86eac-99ce-11e5-85fe-033e2d98f570.png">
Any clue?

**Comment by CoderMJLee** [comment]
```objc
header.automaticallyChangeAlpha = YES;
```
