### ISSUE TITLE
上拉刷新. 点击tableview触发 上拉刷新 事件.

### ISSUE THREAD

**Issue by coderXBPoo** [CoderMJLee/MJRefresh#445]
tableview分为两组  第一组是一些可点击按钮 ,然后第二组是 服务器 拉取的数据.当拉取的数据为空时, 点击第一组的按钮  却触发上拉刷新的事件.. 而且整个tableView点击 时都会 触发 上拉刷新时间...求解

**Comment by 540161331** [comment]
MJRefreshAutoNormalFooter *footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(uploadActivityFeatures)];
    [footer setTitle:@"" forState:MJRefreshStateIdle];
    [footer setTitle:@"加载更多" forState:MJRefreshStateRefreshing];
    [footer setTitle:@"没有更多" forState:MJRefreshStateNoMoreData];
    self.tableView.mj_footer = footer;

// 上拉刷新
- (void)uploadActivityFeatures
{
    CGFloat Start = self.featuresArray.count;
    __weak typeof(self) weakSelf = self;
    [PHTAPIManager getActivityFeaturesWithStart:Start
                                         length:2
                                        success:^(NSArray *features) {
                                            
                                            [weakSelf handleUploadActivityFeaturesSuccess:features];
                                            
                                        } failure:^(NSError *error) {
                                            if (error.userInfo[NSLocalizedDescriptionKey]) {
                                                [ProgressHUD showError:error.userInfo[NSLocalizedDescriptionKey]];
                                            } else {
                                                [ProgressHUD dismiss];
                                            }
                                            [weakSelf.tableView.mj_footer endRefreshing];
                                        }];
}
