### ISSUE TITLE
用scrollView做刷新出现这个问题，杰哥，怎么回事啊

### ISSUE THREAD

**Issue by yangxiaopeng** [CoderMJLee/MJRefresh#449]
**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7f89f488ec00 of class UIScrollView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7f89f3505430> (
<NSKeyValueObservance 0x7f89f584c230: Observer: 0x7f89f581cc60, Key path: contentSize, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7f89f584c170>
)'，

**Comment by yangxiaopeng** [comment]
退出当前页面的时候，提示我
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <ListStatusController 0x7fc6c584e040> for the key path "contentOffset" from <UITableView 0x7fc6c38f2600> because it is not registered as an observer.'

**Comment by loveuqian** [comment]
看错误是你注册了 KVO 但是在 dealloc 时没有 remove
