### ISSUE TITLE
能不能分拆出下拉刷新的代码 并给出接口方便自定义实现

### ISSUE THREAD

**Issue by nicknull** [CoderMJLee/MJRefresh#45]
具体的就是各个刷新状态以及变化 给出接口方便自定义实现刷新样式 例如给出一个接口快捷的实现https://github.com/cyndibaby905/GIFRefreshControl 这样的刷新样式
                                                                                                                                                best wishes

**Comment by liuchunlao** [comment]
不用拆分，直接只写下拉刷新的代码就ok了，不要写上拉刷新的操作。

**Comment by CoderMJLee** [comment]
谢谢提醒，我尽量抽时间去整一整，把很多接口重新定义一下

**Comment by nicknull** [comment]
谢谢回复 在实际应用中用户都会碰到刷新样式自定义的问题

发自我的 iPhone

**Comment by CoderMJLee** [comment]
已经全新升级，可以参考最近的Demo哈

**Comment by nicknull** [comment]
看到了非常感谢  这些功能应该够大部分用户用的了  哈哈

发自我的 iPhone
