### ISSUE TITLE
断网后重新联网上拉刷新问题

### ISSUE THREAD

**Issue by chen-hui** [CoderMJLee/MJRefresh#450]
杰哥，我们使用MJRefresh时，ios9.0以下版本系统断网后重新联网，上拉刷新不能调到相应方法，请问是什么问题？
- (void)viewDidLoad
  {
  // 下拉刷新
  self.mainTable.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{
      [self beginPullDownRefreshing];
  }];
  
  // 设置自动切换透明度(在导航栏下面自动隐藏)
  self.mainTable.mj_header.automaticallyChangeAlpha = YES;
  
  // 上拉刷新
  self.mainTable.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
      [self beginLoadMoreRefreshing];
  }];
  }

**Comment by loveuqian** [comment]
你断网后重新联网有调用 viewDidLoad 方法嘛？

**Comment by chen-hui** [comment]
没有重新调用viewDidLoad方法，这个需要吗？
> 在 2015年12月8日，下午11:46，王胜峰 <notifications@github.com> 写道：
> 
> viewDidLoad
