### ISSUE TITLE
杰哥，下拉刷新时能不能完全影藏刷新控件

### ISSUE THREAD

**Issue by chglog** [CoderMJLee/MJRefresh#451]
就跟微博的详情页、qq空间里的我的空间、与我相关等界面一样，下拉时不要让用户看到刷新的控件，但实际上确实触发了loadData方法

**Comment by CoderMJLee** [comment]
```objc
header.automaticallyChangeAlpha = YES;
```

**Comment by loveuqian** [comment]
MJRefreshStateHeader *header = [MJRefreshStateHeader headerWithRefreshingBlock:^{
        NSLog(@"123");
        [self.tableView.mj_header endRefreshing];
    }];
    header.lastUpdatedTimeLabel.hidden = YES;
    [header setTitle:@"" forState:MJRefreshStateIdle];
    [header setTitle:@"" forState:MJRefreshStatePulling];
    [header setTitle:@"" forState:MJRefreshStateRefreshing];
    self.tableView.mj_header = header;

简单粗暴

**Comment by chglog** [comment]
杰哥可能理解错了我的意思， 胜峰的办法不错，但像详情页这种界面还是会有冲突的

**Comment by loveuqian** [comment]
那就别用框架啦
监听 contentOffset 超过指定范围就执行操作吧

**Comment by chglog** [comment]
我设置了一个下拉的最大高度让头部视图固定住    这样就解决了
