### ISSUE TITLE
点击状态栏返回顶部位置错误

### ISSUE THREAD

**Issue by loveuqian** [CoderMJLee/MJRefresh#453]
![2015-12-09 10 01 05](https://cloud.githubusercontent.com/assets/9745332/11674435/cc907b82-9e5b-11e5-9492-d10087611ea3.png)
![2015-12-09 9 59 45](https://cloud.githubusercontent.com/assets/9745332/11674424/af3af0b2-9e5b-11e5-9dd7-849e3e074273.png)
- 给状态栏覆盖一个20高度的透明 topWindow 并添加点击事件
- 遍历子控件找到 scrollView 然后修改 contentOffset 完成返回顶部功能
- 当一个界面有多个 scrollView 或者多层嵌套时，功能正常
- 但如果只有一个 tableView 的时候会出现错误

**Comment by CoderMJLee** [comment]
尝试使用
```objc
[scrollView scrollRectToVisiable:rect animated:YES];
```
