### ISSUE TITLE
mj_header 无法恢复

### ISSUE THREAD

**Issue by zgcrichard** [CoderMJLee/MJRefresh#455]
有一个列表，想在进入的时候刷新数据在Viewwillappear里面输入 table.mj_header beginrefresh，但是当点击列表进入二级页面，从二级页面返回的时候就会自动刷新，刷新完后就卡在页面上了，不能任何操作。求解决。模块和模块之间来回切换是可以刷新完自己弹回的。

**Comment by CoderMJLee** [comment]
最后有调用header的endRefreshing么？

**Comment by zgcrichard** [comment]
有的。

**Comment by vincent-cihan** [comment]
@CoderMJLee MJ老师，这个问题好像一直存在，主要是右滑返回上一级页面时有一定几率会触发，不知道解决了没有

**Comment by Natai** [comment]
@CoderMJLee 这个问题真的很严重啊。我的情况是从第二个页面的左边缘滑动回第一个页面的同时往下拉，基本都会卡住。
