### ISSUE TITLE
什么都没做，却仍然显示加载

### ISSUE THREAD

**Issue by 1414648814** [CoderMJLee/MJRefresh#459]
![ios simulator screen shot 2015 12 10 4 05 48](https://cloud.githubusercontent.com/assets/5500125/11710160/1abb7d1e-9f58-11e5-944e-4a98dd408290.png)

代码：
/**
 *  设置刷新界面
 */
- (void)setUpRefreshView{
    
    // 添加动画图片的下拉刷新
    // 设置回调（一旦进入刷新状态，就调用target的action，也就是调用self的loadNewData方法）
    [_contentTableView addGifHeaderWithRefreshingTarget:self refreshingAction:@selector(loadNewYanchanghuiData)];

    // 马上进入刷新状态
    //[_contentTableView.gifHeader beginRefreshing];
    
    //NSLog(@"%@",NSStringFromCGRect(_contentTableView.gifHeader.bounds));
    
    [_contentTableView.gifHeader setTitle:@"普通闲置状态" forState:MJRefreshHeaderStateIdle];
    [_contentTableView.gifHeader setTitle:@"松开就可以刷新了" forState:MJRefreshHeaderStatePulling];
    [_contentTableView.gifHeader setTitle:@"正在刷新中" forState:MJRefreshHeaderStateRefreshing];
    [_contentTableView.gifHeader setTitle:@"即将刷新中" forState:MJRefreshHeaderStateWillRefresh];
    
    // 添加动画图片的上拉刷新
    // 设置回调（一旦进入刷新状态，就调用target的action，也就是调用self的loadMoreData方法）
    [_contentTableView addGifFooterWithRefreshingTarget:self refreshingAction:@selector(loadMoreYanchanghuiData)];
    [_contentTableView.gifFooter setTitle:@"普通闲置状态" forState:MJRefreshFooterStateIdle];
    [_contentTableView.gifFooter setTitle:@"下面刷新啦" forState:MJRefreshFooterStateRefreshing];
    _contentTableView.gifFooter.hidden = YES;
    
}

我把[_contentTableView.gifHeader beginRefreshing];注释了仍然显示出来，把end注释还显示
只有把  [_contentTableView addGifHeaderWithRefreshingTarget:self refreshingAction:@selector(loadNewYanchanghuiData)];注释了才不显示，怎么弄都显示。。这是为什么？

**Comment by 1414648814** [comment]
我把[_contentTableView.gifHeader beginRefreshing];注释了仍然显示不出来，

**Comment by CoderMJLee** [comment]
这个是1.0版本的吧？现在是3.0版本了哦
