### ISSUE TITLE
上拉加载，contentSize.height<frame.size.height时，footview出现在高度contentSize.height

### ISSUE THREAD

**Issue by mixuan** [CoderMJLee/MJRefresh#460]
旧版本的MJRefresh，当cell不铺满时，footview是在frame.size.height后面的，现在出现在了contentSize.height高度的位置，请问这是故意这么做的吗

**Comment by CoderMJLee** [comment]
MJRefreshAutoNormalFooter是出现在了contentSize.height高度的位置，MJRefreshBackNormalFooter是在frame.size.height后面
