### ISSUE TITLE
刷新状态

### ISSUE THREAD

**Issue by stevenlfg** [CoderMJLee/MJRefresh#462]
你好，用MJRefresh来做head的头部刷新，效果是一系列动画，刷新完成的时候对应的是哪个状态？

**Comment by CoderMJLee** [comment]
MJRefreshStateIdle

**Comment by stevenlfg** [comment]
现在要显示三种不同的状态：1.刚开始下拉的状态 2.正在刷新的状态3.刷新完成的状态。如果设置刷新完成的时候对应的是MJRefreshStateIdle，好像刚下拉的时候也会出现刷新完成的时候对应的那个动画。
- (void)prepare
{
    [super prepare];
    NSMutableArray *PullingImages = [NSMutableArray array];
    for (NSUInteger i=1; i<=20; i++) {
        UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"pulling_100%zd.png",i]];
        [PullingImages addObject:image];
    }
    [self setImages:PullingImages forState:MJRefreshStatePulling];
    
    NSMutableArray *refreshingImages = [NSMutableArray array];
    for (NSUInteger i = 1; i<=25; i++) {
        UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"100%zd.png", i]];
        [refreshingImages addObject:image];
    }
    [self setImages:refreshingImages forState:MJRefreshStateRefreshing];

    
    NSMutableArray *IdleImages = [NSMutableArray array];
    for (NSUInteger i=1; i<=1; i++) {
        UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"bd.png"]];
        [IdleImages addObject:image];
    }
    [self setImages:IdleImages forState:MJRefreshStateIdle];
    
}
