### ISSUE TITLE
MJRefreshAutoNormalFooter上拉加载会触发2次

### ISSUE THREAD

**Issue by devSC** [CoderMJLee/MJRefresh#463]

**Comment by devSC** [comment]
经过我检查, 当每次我设置玩endRefresh后, 会这个方法中:
`- (void)scrollViewContentOffsetDidChange:(NSDictionary *)change
{
    [super scrollViewContentOffsetDidChange:change];
    
    if (self.state != MJRefreshStateIdle || !self.automaticallyRefresh || self.mj_y == 0) return;
    
    if (_scrollView.mj_insetT + _scrollView.mj_contentH > _scrollView.mj_h) { // 内容超过一个屏幕
        // 这里的_scrollView.mj_contentH替换掉self.mj_y更为合理
        if (_scrollView.mj_offsetY >= _scrollView.mj_contentH - _scrollView.mj_h + self.mj_h * self.triggerAutomaticallyRefreshPercent + _scrollView.mj_insetB - self.mj_h) {
            // 防止手松开时连续调用
            CGPoint old = [change[@"old"] CGPointValue];
            CGPoint new = [change[@"new"] CGPointValue];
            if (new.y <= old.y) return;
            
            // 当底部刷新控件完全出现时，才刷新
            [self beginRefreshing];
        }
    }
}

`
立即再调用一次.beginRefreshing.
打印后,发现
`new.y > old.y.`

但我先reloadData后,延迟0.1秒来调用endRefreshing,就没事了.

说明: 我用ARC布局.

**Comment by ToLengSon** [comment]
自己重写下MJRefreshFooter的beginRefreshing方法，然后里面判断下是offsetY是否大于0，如果满足就调用super
