### ISSUE TITLE
MJRefreshAutoNormalFooter上拉加载 只加载一次

### ISSUE THREAD

**Issue by karson711** [CoderMJLee/MJRefresh#464]
MJRefreshAutoNormalFooter上拉只加载了一次，第二次就没有进入响应加载更多的方法。这是为什么呢？

**Comment by JhonSun** [comment]
你好，你的问题解决了吗？？我也遇到这个问题了

**Comment by JhonSun** [comment]
我知道了，在刷新完成之后需要调用结束刷新，下一次刷新才能响应

**Comment by CoderMJLee** [comment]
肯定要结束刷新的，因为框架内部是不知道你想在什么时候结束

**Comment by karson711** [comment]
问题已解决，谢谢MJ，谢谢JhonSun
