### ISSUE TITLE
发现了个crash，但不确定是哪里的问题

### ISSUE THREAD

**Issue by kldxcr** [CoderMJLee/MJRefresh#465]
杰哥，我在设置mj_footer的时候，断点走到设置mj_insetB的方法中的self.contentInset时crash了
我不确定是什么问题，报错的是：“[__NSArrayM insertObject:atIndex:]”，但注释掉设置mj_footer的方法后，app本身没有问题，如果你有任何建议，希望能恢复我，谢啦
- (void)setMj_insetB:(CGFloat)mj_insetB
  {
  UIEdgeInsets inset = self.contentInset;
  inset.bottom = mj_insetB;
  self.contentInset = inset;
  }

**Comment by kldxcr** [comment]
杰哥，我把footer的设置方法放到ViewDidAppear中，就没问题了
放到viewWillAppear和viewDidLoad方法中在iOS7、8中都crash
请获悉

**Comment by wangchaodong** [comment]
viewwillappear你的footer都还没有设置,不存在当然报错. 你要先设置MJfooter,再来reloa
