### ISSUE TITLE
为什么tableview cell数量为0，不能显示“已经全部加载完毕”

### ISSUE THREAD

**Issue by khj986** [CoderMJLee/MJRefresh#466]
为什么tableview cell数量为0，不能显示“已经全部加载完毕”，这样就需要用其他方式来提示，而且就不能刷新数据了，希望能加上这个功能

**Comment by CoderMJLee** [comment]
可以自己判断数量来决定要不要显示“已经全部加载完毕”
```objc
if (count == 0) {
   [footer endRefreshingWithNoMoreData];
}
```

**Comment by khj986** [comment]
好的，我现在是这样做的
if (count == 0) {
   [footer endRefreshingWithNoMoreData];
footer.hidden = NO;
}
