### ISSUE TITLE
下拉刷新无法恢复原布局

### ISSUE THREAD

**Issue by charsdavy** [CoderMJLee/MJRefresh#468]
使用下拉刷新是，在4寸屏设备上，刷新成功后视图向上缩进不出来。

**Comment by CoderMJLee** [comment]
有效果图么？

**Comment by CharsDavy** [comment]
首先很抱歉问题描述错误，已经更改。效果图上传不了。问题自己已经解决，原因是我自己添加了导航条，所以下拉刷新之后，顶部滚出的区域空间不够，只需多让视图在刷新完成之后在顶部多滚出一定区域即可。
