### ISSUE TITLE
预加载功能实现

### ISSUE THREAD

**Issue by FutureChen** [CoderMJLee/MJRefresh#471]
我们这里的需求是希望快滑到底的时候预先进行请求，加载数据。

所以我在wilDisplayCell 里面做了判断，调用了 footer.begingRefresh
但是会出现神奇的闪屏效果，并且很卡。

于是乎换了一种写法继承footer ,依然卡~
- (void)scrollViewContentOffsetDidChange:(NSDictionary *)change
{
    [super scrollViewContentOffsetDidChange:change];
    if ([self.scrollView isKindOfClass:[UITableView class]]) {
        CGPoint oldPoint= [[change objectForKey:@"old"]CGPointValue];
        CGPoint newPoint= [[change objectForKey:@"new"]CGPointValue];
        if (newPoint.y>oldPoint.y) {//向下滑才出发自动刷新
            UITableView *tableView=(UITableView *)self.scrollView;
            NSIndexPath *indexPath= [tableView indexPathForRowAtPoint:newPoint];
            NSInteger rowNum= self.scrollView.mj_totalDataCount;
            if (rowNum-5==indexPath.row&&!tableView.mj_footer.isRefreshing) {
                [self executeRefreshingCallback];
                
            }
        }
    }
    
}

**Comment by FutureChen** [comment]
清空了下 模拟器就好了。囧

**Comment by jinxiansen** [comment]
帮我解决了1个问题。

**Comment by iosApem** [comment]
你这个拓展非常好，虽然有很多细节没处理好，但是确实可以这样实现预加载
