### ISSUE TITLE
肿么没有做本地化，我的app需要做本地化

### ISSUE THREAD

**Issue by lekerning** [CoderMJLee/MJRefresh#474]

**Comment by Jeff-F** [comment]
哈哈， 正准备提， 看到了这个， @CoderMJLee ， 大神， 快支持国际化

**Comment by ucoker** [comment]
[header setTitle:@"Pull down to refresh" forState:MJRefreshStateIdle];
    [header setTitle:@"Release to refresh" forState:MJRefreshStatePulling];
    [header setTitle:@"Loading ..." forState:MJRefreshStateRefreshing];
