### ISSUE TITLE
UITableView的Header下拉松开瞬间偶尔会有白线闪烁?

### ISSUE THREAD

**Issue by 4dmoonlight** [CoderMJLee/MJRefresh#475]

**Comment by studyBully** [comment]
你的也有白线闪烁的情况吗？ 是不是控件的问题？  我的tableview也出现了白线闪烁的情况，我还以为是我的问题

**Comment by EntityGJ** [comment]
tableView 如果没有headerView 或footerView  将代理方法注释掉 
heightForHeaderInSection 、heightForFooterInSection
viewForHeaderInSection   、viewForFooterInSection  都注释掉、  
也别写0.001这种
