### ISSUE TITLE
动画效果一般，这个咋样？求作者集成

### ISSUE THREAD

**Issue by yorling** [CoderMJLee/MJRefresh#49]
参考 https://github.com/jcavar/refresher 的动画

**Comment by CoderMJLee** [comment]
已经集成了一些基本的动画，可以参考最新示例代码哈

**Comment by yorling** [comment]
MJ哥来个Swift版本吧，嘿嘿

**Comment by BaiCanLin** [comment]
MJ 哥 pod 还没更新呢～ 嘿嘿

**Comment by CoderMJLee** [comment]
我家的网络比较蛋疼，pod一直提交不上去，改天换个环境搞搞
