### ISSUE TITLE
网络不佳状态下下拉刷新还在持续，进入下一界面，网好了，通知回来beginRefresh，导致刷新的头回不去

### ISSUE THREAD

**Issue by e21169191** [CoderMJLee/MJRefresh#493]

**Comment by e21169191** [comment]
网络不佳状态下下拉刷新还在持续，在此期间下降了一个高度，进入下一界面，网好了，改变下一个界面数据，通知回来beginRefresh，又下降了一个高度，刷新完成后，导致刷新的头回不去

**Comment by chengongwen** [comment]
网络不佳状态下下拉刷新还在持续，在此期间下降了一个高度，进入下一界面，网好了，改变下一个界面数据，通知回来beginRefresh，又下降了一个高度，刷新完成后，导致刷新的头回不去。

同问 ，急急急

**Comment by chengongwen** [comment]
网络不佳状态下下拉刷新还在持续，在此期间下降了一个高度，进入下一界面，网好了，改变下一个界面数据，通知回来beginRefresh，又下降了一个高度，刷新完成后，导致刷新的头回不去。

同问 ，急急急 ！！！
