### ISSUE TITLE
WkWebView

### ISSUE THREAD

**Issue by hexu2016** [CoderMJLee/MJRefresh#508]
请问什么时候可以支持WkWebView吗

**Comment by CoderMJLee** [comment]
webView.scrollView.mj_header = ....;

**Comment by hexu2016** [comment]
谢谢！

发自我的 iPhone

**Comment by kokoar** [comment]
使用WK时，存在bug。你可以试试https://www.qq.com

**Comment by kokoar** [comment]
MJ与scrollView在一起，与页面的头部底部元素重现重合现象。

**Comment by tanranran** [comment]
+1
