### ISSUE TITLE
idle状态下动画停住

### ISSUE THREAD

**Issue by f33chobits** [CoderMJLee/MJRefresh#51]
hi, @CoderMJLee 
    gif例子里面还没有松开手动画就动了，我觉得是否改成这样会好些？
![refresh_idle](https://cloud.githubusercontent.com/assets/5186464/6541229/fe88d7b4-c4ff-11e4-92e3-a78b5aa8c9cf.gif)

**Comment by CoderMJLee** [comment]
嗯，可以的。看你的具体需求哈，我仅仅是举个例子的。

**Comment by f33chobits** [comment]
额，其实在gIfHeader里面的 MJRefreshHeaderStatePulling状态下加个break就这样了，有必要提个PR么？

**Comment by CoderMJLee** [comment]
我的用意是自由选择，开发者根据需要去选择自己的显示方式。如果不希望即将刷新的时候播放动画，那就不要设置MJRefreshHeaderStatePulling状态下的动画图片就行了哈，不用改框架源代码的。

**Comment by f33chobits** [comment]
原来如此，只看框架了，没有仔细看Demo，我的
