### ISSUE TITLE
MJ老师在TableViewController中，如果有多resection，并且所有section中的row都是合并的，这样无法进行上拉刷新，除非把section展开才可以

### ISSUE THREAD

**Issue by mzmJACK** [CoderMJLee/MJRefresh#510]
![2016-01-19 1 25 22](https://cloud.githubusercontent.com/assets/15830076/12410441/3acd934a-beb0-11e5-8c96-b80112d7df5a.png)
这是合并的不能上拉刷新
![2016-01-19 1 25 36](https://cloud.githubusercontent.com/assets/15830076/12410447/4ba0b094-beb0-11e5-9031-96b967ea217b.png)
这是展开的，展开后才能刷新

**Comment by chaziyjs** [comment]
不知道你最后怎么解决的这个问题,我和你发生了同样的问题.我最后的解决方法就是重新写了一个上拉加载的方法.在使用scrollView的代理方法中实现.如果你有更好的解决方法,欢迎提供给我~~~
