### ISSUE TITLE
版本升级后崩溃

### ISSUE THREAD

**Issue by hh1myfei** [CoderMJLee/MJRefresh#512]
我用cocospod 升级后，提示，要用mj_header 替换header ，但是替换后之后崩溃，但是在另一个项目中，替换完不崩溃，不知道为什么，非常奇怪。

**Comment by CoderMJLee** [comment]
崩溃信息是？

**Comment by LilyLiulili** [comment]
你好，我也遇到了这种情况，怎么解决呢
