### ISSUE TITLE
tableview 使用 mj  insert bug

### ISSUE THREAD

**Issue by juvham** [CoderMJLee/MJRefresh#519]
使用 mj refresh 的 footer 刷新列表方式 使用插入数据方式 会产生 mj_footer 和  cell 重叠 显示在 同一位置的 bug

**Comment by demoker** [comment]
@juvham 解决了吗？

**Comment by demoker** [comment]
@CoderMJLee 求解决

**Comment by CoderMJLee** [comment]
试试tableView reloadData

**Comment by demoker** [comment]
有这个问题是因为，我插入cell之后还调用了scrollposition方法，用了一个动画，所以会有这个bug，去掉这个之后就没有了
