### ISSUE TITLE
pod MJRefresh   少了几个文件

### ISSUE THREAD

**Issue by amuluo24** [CoderMJLee/MJRefresh#52]
MJRefreshGifFooter.h        MJRefreshGifFooter.m
MJRefreshGifHeader.h        MJRefreshGifHeader.m  这几个文件都不存在 下载的zip 包中还是存在的。但但是pod自动导入 没有这几个文件

**Comment by CoderMJLee** [comment]
Sorry。。。我家里的网络比较蛋疼，所以我还没有及时更新pod，实在是sorry

**Comment by lockezhang** [comment]
zip包我下载了也没有看到这几个类啊？

**Comment by CoderMJLee** [comment]
肯定有的哈
