### ISSUE TITLE
调用self.tableView.mj_header beginRefreshing方法时bug

### ISSUE THREAD

**Issue by CoderDKBai** [CoderMJLee/MJRefresh#521]
当tableView的contentOffset的Y值大于某一值（例如1000）时，手动调用下拉刷新方法[self.tableView.mj_header beginRefreshing]，会出现一片空白，然后tableView开始滚动并刷新，如果contentOffset的Y值小于某一值（如300），就不会出现空白

**Comment by jianqingyu** [comment]
为什么关掉了，请问怎么解决的
