### ISSUE TITLE
Pod 是否没有更新最新版本？

### ISSUE THREAD

**Issue by amuluo24** [CoderMJLee/MJRefresh#53]
如题

**Comment by CoderMJLee** [comment]
嗯，是的，非常抱歉。这几天内会更新的，主要是我家的网络各种问题。。。用的是方正网络，被堵了

**Comment by jbasttdi** [comment]
难怪了，我今天搞了很久cocoapods,都删除master,重下master了，还死活是0.0.1版本，原来是MJ老大没上传到cocopods啊。

**Comment by CoderMJLee** [comment]
pod已经是最新的1.0.3版本了

**Comment by amuluo24** [comment]
TKS 向你学习

**Comment by heistings** [comment]
➜  iOS  pod search MJRefresh


-> MJRefresh (0.0.1)
   The easiest way to use pull-to-refresh
   pod 'MJRefresh', '~> 0.0.1'
   - Homepage: https://github.com/CoderMJLee/MJRefresh
   - Source:   https://github.com/CoderMJLee/MJRefresh.git
   - Versions: 0.0.1 [master repo]

**Comment by CoderMJLee** [comment]
先更新库信息：
pod repo update
或者
pod setup

**Comment by heistings** [comment]
@CoderMJLee 感谢。
