### ISSUE TITLE
上拉自动刷新出现无限自动刷新

### ISSUE THREAD

**Issue by spStep** [CoderMJLee/MJRefresh#536]
一个列表的界面，经过多次上拉，内容超过2个屏幕左右后，此时再调用header的beginRefresh，表格会会滚到顶部，然后头部开始刷新数据，但头部刷完之后，footer不知道为什么也开始刷新数据了，而且还是无限刷新，停不下了！

**Comment by spStep** [comment]
找到原因了，是开启tableView估算高度(estimatedRowHeight)的原因，导致contentOffset的KVO一直调用,我把估算高度（estimatedRowHeight）关了就没这问题。但还是希望以后能兼容estimatedRowHeight，可以减少高度的计算。我用的是autoLayout的高度自适应cell，用的UITableView+FDTemplateLayoutCell

**Comment by winterWD** [comment]
希望杰哥尽快解决掉这个问题！

**Comment by xd54622** [comment]
取消自动刷新，也可以解决这个问题。

**Comment by Immanito** [comment]
估算高度怎么关的

**Comment by wolfcon** [comment]
Duplicate of #1294
