### ISSUE TITLE
在iOS系统7版本上出现闪退情况

### ISSUE THREAD

**Issue by kuqiqi** [CoderMJLee/MJRefresh#538]
-[__NSArrayM insertObject:atIndex:]:object cannot be nil

 UIScrollView+MJExtension.m

定位在这一行    - (void)setMj_insetB:(CGFloat)mj_insetB
{
    UIEdgeInsets inset = self.contentInset;
    inset.bottom = mj_insetB;
    self.contentInset = inset;
}      

中的 self.contentInset = inset;

**Comment by gbfansheng** [comment]
SAME PROBLEM. DONT NO WHY

**Comment by wuyeRoy** [comment]
这个问题解决了吗？ @kuqiqi @gbfansheng

**Comment by gbfansheng** [comment]
忘记了，好像跟数据类型有关。你看看数据类型，float,double,cgfloat之类的。
