### ISSUE TITLE
使用demo的时候报警告

### ISSUE THREAD

**Issue by seanLee** [CoderMJLee/MJRefresh#54]
````[self performSelector:NSSelectorFromString(self.method) withObject:nil];````

performSelector may cause a leak because its selector is unknown

**Comment by CoderMJLee** [comment]
这个没有关系的哈，是为了Demo的正常使用而写的。跟框架源代码无关。

**Comment by seanLee** [comment]
因为现在还没加到代码里去,所以暂时不知道会有什么问题.可是我注释掉这行代码,demo就没有刷新的效果了。这不会影响实际使用吧?

**Comment by CoderMJLee** [comment]
那一行是Demo代码，不属于框架内部的代码。你实际用框架时用不上这句代码

**Comment by heistings** [comment]
这个问题可以关了。

**Comment by seanLee** [comment]
好吧～谢了～
