### ISSUE TITLE
mjrefreshheader 显示空白，绑定的函数都会触发

### ISSUE THREAD

**Issue by HelloWilliam** [CoderMJLee/MJRefresh#540]
我用的是frame布局

**Comment by HelloWilliam** [comment]
@CoderMJLee 能看看嘛？

**Comment by HelloWilliam** [comment]
- tvList.mj_header = [MJRefreshHeader headerWithRefreshingTarget:self refreshingAction:@selector(headRefresh)]; //it's ok

- (void)headRefresh{
    [tvList.mj_header performSelector:@selector(endRefreshing) withObject:nil afterDelay:2];
} //it's ok

- The user interface can not show,just a blank with some frame.??

**Comment by HelloWilliam** [comment]
@CoderMJLee 我看到外面有2个人这么反应这个问题了，是不是哪里需要修改，能麻烦看下嘛？

**Comment by HelloWilliam** [comment]
@CoderMJLee 已解决。

**Comment by Ssunnyy** [comment]
@HelloWilliam 你是怎么解决的。我也遇到同样的问题了

**Comment by moekyo** [comment]
加上 `[self.tableView.mj_header` endRefreshing];
 self.tableView.contentInset = UIEdgeInsetsMake(64, 0, 0, 0);
 self.tableView.contentOffset = CGPointMake(0, -64);`
