### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by CDYeah** [CoderMJLee/MJRefresh#545]
建议文字支持国际化，每次都要改动源码很不方便，或者提供给用户方便加入国际化的修改接口

**Comment by Cunqi** [comment]
顶一个，虽然可以定制state， 但是`lastUpdatedTimeText`里面的文字还是中文。

**Comment by CDYeah** [comment]
可以提供一个公开的接口，可以统一设置，现在每设置一次就要写一遍不太好
