### ISSUE TITLE
下拉刷新后，可以改变上拉刷新条的状态

### ISSUE THREAD

**Issue by ZezhongLi** [CoderMJLee/MJRefresh#548]
不知道有没有看错代码，但是在我的使用中，我觉得可以改进的是：
如果上拉刷新变为没有更多数据，可以在下次下拉刷新后，自动改变上拉刷新条的状态为上拉加载更多，而不是不改变，保留为没有更多数据。应该在下拉后默认认为，可以上拉。

**Comment by superBing** [comment]
我也发现这个问题了，需要自己手动再次把footer变为endrefreshing状态，希望杰哥能改下
