### ISSUE TITLE
无法容忍的 Bug，作者应该尽快修改，返回到上一页的时候，卡死！

### ISSUE THREAD

**Issue by jacksonpan** [CoderMJLee/MJRefresh#549]
当上一页的 viewWillAppear 里加载 mjrefresh 的刷新，会几率性出现卡死并且无法点击动弹，状态在刷新中，尤其是使用手指快速右滑返回上一页，这个 Bug 可以说是必现！

作者赶紧改一下吧，太严重了！

**Comment by Han113122** [comment]
顶， 同样的问题，在viewWillAppear里使用[self.tableView.header beginRefreshing];  在下一级界面里用手指快速右滑，就会出现无法动弹，而且，block里面的方法并未被调用。

**Comment by jacksonpan** [comment]
没人回应

**Comment by CoderMJLee** [comment]
不好意思，近期忙，没有时间去回复大家的问题。近期我会尽量尽快抽时间去看看咋回事哈

**Comment by cochn** [comment]
顶  今天用也遇到了 求解决

**Comment by vincent-cihan** [comment]
出现同样的问题，希望MJ能够尽快解决，谢谢

**Comment by CoderMJLee** [comment]
我自己亲测了没发现这个问题，可能代码环境跟大伙的不一样。希望能给一个出现这个问题的Demo，谢谢。

**Comment by vincent-cihan** [comment]
@CoderMJLee     #687 里面的貌似描述的很专业，具体不知道对不对，他的重现方法是可以的，您可以试一下，另外我试了最新的3.1.12、退回到2.5.0版本都会出现这个问题

**Comment by cyW0923** [comment]
几乎必现

**Comment by onlyAngelia** [comment]
我们这边也是，必先

**Comment by onlyAngelia** [comment]
我们这也是 ，必现

**Comment by ToLengSon** [comment]
我这边出现的是：正在下拉刷新时，切换页面，当前正在下拉刷新时的页面没有了父视图，导致系统调用了方法，MJ内部计算出问题，我是在刷新回调的block判断了；判断条件是：回调无父视图，并且MJ的insetTDelta >= 0时，把mj的mj_insetT设置为0；不知道大家是不是跟我一样的情况

**Comment by SuDream** [comment]
现在时间2019年4月 28日,这个问题还是存在的, ios9 ios10...都不行,(ios12不会出现这个问题),我试了网上各种方法都不行啊 .都是在viewWillAppear里使用[self.tableView.header beginRefreshing]; 在下一级界面里用手指快速右滑返回，上个页面的下拉就没有收回,然后卡死,endRefreshing 就失效   求大神给个方案 @jacksonpan @hantaoye @CoderMJLee

**Comment by wolfcon** [comment]
#1108 参见这个

**Comment by lawDavid** [comment]
> #1108 参见这个

是不是没找对问题啊？这个问题在3.3.1还存在，iOS9 iOS10必现，在列表的viewWillAppear中使用mj_header beginRefreshing，在详情通过手势侧滑返回列表loading就不会停而且整个页面卡住。

**Comment by wolfcon** [comment]
来个 demo. 是真机还是模拟器也必现?
