### ISSUE TITLE
使用[self.tableView.footer endRefreshing];没用，还在转菊花

### ISSUE THREAD

**Issue by TZZhan** [CoderMJLee/MJRefresh#55]
![b1e4582b-bc1c-4ba7-8da4-8339f5959559](https://cloud.githubusercontent.com/assets/8191963/6551557/4370ea44-c675-11e4-8752-b2f9554ab9d5.png)
我使用了最新的框架，从pod上更新的，上拉刷新时，到了末尾，如果没有数据了，使用[self.tableView.footer endRefreshing];，菊花还在转，不知道为什么，求解

**Comment by heistings** [comment]
可能应该用下面这个接口：

```objective-c
/** 提示没有更多的数据 */
- (void)noticeNoMoreData;
```

**Comment by zombiegift** [comment]
MJ哥已修复

**Comment by yorling** [comment]
pod好像不是最新的吧

**Comment by TZZhan** [comment]
应该是AutoLayout的问题，是最新的版本

**Comment by heistings** [comment]
@TZZhan 你用那个接口了吗？

**Comment by TZZhan** [comment]
@heistings 嗯，我用过了，已经解决了，谢谢

**Comment by Xlff** [comment]
@heistings 网络请求返回错误的时候调用endrefreshing也不起作用呢
