### ISSUE TITLE
UICollectionView.mj_footer 刷新状态 修改失败

### ISSUE THREAD

**Issue by srxboys** [CoderMJLee/MJRefresh#551]
*_//这是创建 *_  
`_collectionView.mj_footer = [MJRefreshBackNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadNetData)];
`

**//请求方法**

```
- (void)loadNetData {
//省略请求过程

[_collectionView.mj_footer endRefreshing];
if(_currentPage >= _totalPageCount) {
            [_collectionView.mj_footer endRefreshingWithNoMoreData];
        }
        else {
            _currentPage ++;
        }

       [_collectionView reloadData];
}
```

MJRefreshBackNormalFooter、MJRefreshBackStateFooter   下的 endRefreshingWithNoMoreData的状态 不起作用
_---_
_tableView 的可以实现
# 致敬

**Comment by shanlh** [comment]
我在请求之后，不管成功失败都会对footer调用endRefreshing，然后导致endRefreshingWithNoMoreData失效，做了判断不加endRefreshing就好了

**Comment by srxboys** [comment]
我请求 成功 结束刷新！ 接口告诉就只有这一页了， 我就 mj 没有数据刷新了   table 可以    ，collenctiongView 就不行


发自 网易邮箱大师
在2016年05月13日 16:00，单泠浩 写道:

我在请求之后，不管成功失败都会对footer调用endRefreshing，然后导致endRefreshingWithNoMoreData失效，做了判断不加endRefreshing就好了

**Comment by jakejone** [comment]
这么严重的问题，不修吗？

**Comment by wolfcon** [comment]
endRefreshing
endRefreshingWithNoMoreData

不要一起使用
