### ISSUE TITLE
mj_footer隐藏导致section悬空

### ISSUE THREAD

**Issue by Stroustrup-Lee** [CoderMJLee/MJRefresh#552]
UITableView为UITableViewStylePlain，并且使用
-(CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section
{
    return 6;
}
这个时候使用MJRefreshAutoNormalFooter会使最后面的一个section悬空

**Comment by shmchen** [comment]
也遇到了。。。。。
