### ISSUE TITLE
gif图片的尺寸太大，UI就不合适了

### ISSUE THREAD

**Issue by fanhoucheng** [CoderMJLee/MJRefresh#553]
自定义gif head，无文字无时间时，如果gif尺寸太大，整个head就很大，这应该很不合适吧
建议control有个最大gif对应的imageview尺寸，是不是？

我觉得应该是gif的高度是有max值，比如60，超过了也限定在60，那样UI才好看

虽然限定gif的size可以，但是总觉得这样不好

**Comment by CuiPengfeiGitHub** [comment]
遇到了同样的问题，image的尺寸太大的话，GIFHeader的尺寸也很大，但是强制更改gifView的frame的话，size没有效果，而且位置发生偏差。你是怎么解决的？

**Comment by wolfcon** [comment]
继承后, 自己对 `header` 进行适配
