### ISSUE TITLE
添加个获取原始contentInset的方法

### ISSUE THREAD

**Issue by GreedBell** [CoderMJLee/MJRefresh#558]
在下拉刷新的时候需要根据contentInset计算将要显示的Cell高度，但是MJRefresh里下拉刷新会修改contentInset，结束后再恢复。这样就导致Cell高度计算出错

**Comment by Zcating** [comment]
没办法判断View 是否跳转，只能在Contoller中做保存。

**Comment by GreedBell** [comment]
已经找到了，MJRefreshComponent.scrollViewOriginalInset 这个就是原始的 contentInset

**Comment by Zcating** [comment]
= = 好吧，以后还是要多看源码，我一直都在controller中作保存。
