### ISSUE TITLE
Header 没有自动隐藏

### ISSUE THREAD

**Issue by luffyj** [CoderMJLee/MJRefresh#56]
无论是刚初始化好 还是下拉刷新过
Header始终显示在界面中 并且将ScrollView下移了。

跟Demo中有所区别的是：
1) ScrollView上面还有其他控件
2) ScrollView是用AutoLayout布局的

**Comment by CoderMJLee** [comment]
有时间的话，能发个Demo看看么？我估计是Autolayout对ScrollView的contentInset产生了影响

**Comment by luffyj** [comment]
好的
今天下班了 家里没机器  明天发个demo给你。

谢谢你的关注

btw:你的这个玩意儿很赞

**Comment by luffyj** [comment]
demo写了 没法重现这个问题。

不知道是哪个地方增加 contentInset.top 64....

我先关了把
