### ISSUE TITLE
我用 RefreshFooter 做了一个类似于淘宝的上拉查看详情

### ISSUE THREAD

**Issue by wangbiye** [CoderMJLee/MJRefresh#562]
做好之后有一点瑕疵, 我把 refreshFooter 设置成手动的, 上拉一下让新页面出来, 但是会有一个 loading 的过程, 我的代码是连续的, 应该没有耗时操作, 所以不需要显示这个 loading 也可以, 这样看起来就更连贯一点, 看图对比
![](http://ww1.sinaimg.cn/large/661902d8gw1f2sscfwk18g20dm0mm1l0.gif)

![](http://ww4.sinaimg.cn/large/661902d8gw1f2sscw34nvg20dm0mmx6q.gif)

**Comment by WormZh** [comment]
你好，请问你用上拉加载的时候tableview的下面有多余的cell分割线出现吗？

**Comment by wangbiye** [comment]
没有, 这个页面本身是一个 scrollView, 然后下边加了一个 refreshFooter

**Comment by LargeShrimp** [comment]
这个主要是动画事件造成的我感觉。
const CGFloat MJRefreshFastAnimationDuration = 0.25;
const CGFloat MJRefreshSlowAnimationDuration = 0.4;

**Comment by fuchenxi** [comment]
楼主这个页面的结构是怎么样的, 我也做的类似这样的界面, 但感觉结构有点不太好

**Comment by wangbiye** [comment]
参考 IGListKit, 我已经准备用 IGListKit 重构了
