### ISSUE TITLE
table加了header后，在cell刚好显示满屏幕，下拉刷新会出现滚动条闪现

### ISSUE THREAD

**Issue by Ghyud** [CoderMJLee/MJRefresh#563]
发现一个bug，在tableview加了searchBar作为headerView时，当cell的数量刚刚达到屏幕的最大显示范围，下拉刷新会出现垂直滚动条，有左至右闪现放大的问题
![ios simulator screen shot 2016 4 12 8 13 18](https://cloud.githubusercontent.com/assets/17560766/14480499/448aa3ca-015c-11e6-913a-95199eb88779.png)
![ios simulator screen shot 2016 4 12 8 13 17](https://cloud.githubusercontent.com/assets/17560766/14480500/489af6ea-015c-11e6-8942-0532bcb23bb1.png)

**Comment by Ghyud** [comment]
@CoderMJLee

**Comment by superous123** [comment]
我也有 同样的问题。 同问 @CoderMJLee

**Comment by LarkNan** [comment]
我这边也出现这样的问题了，请问怎么解决呢。 @CoderMJLee

**Comment by xuwenlang** [comment]
同问

**Comment by wolfcon** [comment]
Duplicate of #1009
