### ISSUE TITLE
Assertion failure in -[UISectionRowData refreshWithSection:tableView:tableViewRowData:]

### ISSUE THREAD

**Issue by Sum123** [CoderMJLee/MJRefresh#564]
小马哥  刷新的时候出现这个bug  
我断点看数据都没问题  就是执行到
- (void)mj_reloadData
  {
  [self mj_reloadData];
  
  [self executeReloadDataBlock];
  }
  卡主了

**Comment by fandongtongxue** [comment]
这页面应该有图片但是图片未加载上,导致计算高度出现问题,返回nan值

**Comment by Rsenjoyer** [comment]
我自己计算的高度都会出现这个的

**Comment by LazyScream** [comment]
Hello ?!!?!!
