### ISSUE TITLE
UIScrollView+MJRefresh.m 崩溃， iOS8 ，跪求大神回复

### ISSUE THREAD

**Issue by superous123** [CoderMJLee/MJRefresh#567]
Line table dir : '/Pods/MJRefresh/MJRefresh'
Line table file: 'UIScrollView+MJRefresh.m' line 146, column 5 with start address 0x00000001001499b0
Looking up address: 0x00000001001499b0 in .debug_frame... not found.

// code 

static const char MJRefreshReloadDataBlockKey = '\0';
- (void)setMj_reloadDataBlock:(void (^)(NSInteger))mj_reloadDataBlock
  {
  [self willChangeValueForKey:@"mj_reloadDataBlock"]; // KVO
  objc_setAssociatedObject(self, &MJRefreshReloadDataBlockKey, mj_reloadDataBlock, OBJC_ASSOCIATION_COPY_NONATOMIC);
  [self didChangeValueForKey:@"mj_reloadDataBlock"]; // KVO
  }
- (void (^)(NSInteger))mj_reloadDataBlock
  {
  return objc_getAssociatedObject(self, &MJRefreshReloadDataBlockKey);
  }
- (void)executeReloadDataBlock
  {
  !self.mj_reloadDataBlock ? : self.mj_reloadDataBlock(self.mj_totalDataCount);
  }
  @end

@implementation UITableView (MJRefresh)
- (void)load
  {
  [self exchangeInstanceMethod1:@selector(reloadData) method2:@selector(mj_reloadData)];
  }
- (void)mj_reloadData
  {
  [self mj_reloadData];
  
  [self executeReloadDataBlock];
  }

**Comment by superous123** [comment]
0x002473df:     TAG_subprogram [170] *
                 AT_low_pc( 0x0000000100149994 )
                 AT_high_pc( 0x00000001001499c8 )
                 AT_frame_base( reg29 )
                 AT_object_pointer( {0x002473ff} )
                 AT_name( "-[UITableView(MJRefresh) mj_reloadData]" )
                 AT_decl_file( "/Users/jenkins/jenkins-slave-home/workspace/COS-Moma/MOMA-Plus/MOMA-Plus-Online/Pods/MJRefresh/MJRefresh/UIScrollView+MJRefresh.m"

**Comment by lqcjdx** [comment]
我也遇到这个问题了，在ios8.4.1上莫名闪退，通过dsym文件定位到-[UITableView(MJRefresh) mj_reloadData] (in YLLanJiQuan) (UIScrollView+MJRefresh.m:125)此处。不清楚为何。

**Comment by sunSink** [comment]
我在ios9.3.4上也出现了闪退，定位到-[UITableView(MJRefresh) mj_reloadData] (UIScrollView+MJRefresh.m:146) ，不清楚为什么，解决了吗？

**Comment by OskarZhang** [comment]
Same issue here

**Comment by AnyaWork** [comment]
I meet same issue here!  called the [self mj_reloadData] is crash

**Comment by liLeiBest** [comment]
调用 - (CGFloat)tableView:(UITableView *)tableView estimatedHeightFor…… 方法，可以解决崩溃。

**Comment by AnyaWork** [comment]
I have been solved, but thank you very much!


原始邮件
发件人:Lileinotifications@github.com
收件人:CoderMJLee/MJRefreshMJRefresh@noreply.github.com
抄送:DeveloperWang858642232@qq.com; Commentcomment@noreply.github.com
发送时间:2017年2月28日(周二) 16:53
主题:Re: [CoderMJLee/MJRefresh] UIScrollView+MJRefresh.m 崩溃， iOS8 ，跪求大神回复 (#567)


调用 - (CGFloat)tableView:(UITableView *)tableView estimatedHeightFor…… 方法，可以解决崩溃。

**Comment by yuhanle** [comment]
我也遇到了同样的问题，在7.1.2 系统和 8.0+ 上都有崩溃，看这个[issues#385](https://github.com/CoderMJLee/MJRefresh/issues/385) 里是说循环引用导致，感觉有这个可能。

这个问题显示解决了，不知道这种方式是不是可以彻底解决，我使用的是最新的Release 版本
