### ISSUE TITLE
English README

### ISSUE THREAD

**Issue by dkhamsing** [CoderMJLee/MJRefresh#568]
Hi
Is it possible to have an English version of the README (or short summary)? That would be for inclusion to https://github.com/vsouza/awesome-ios

Let me know if this is possible or not
Thanks!

**Comment by CavalcanteLeo** [comment]
+1

**Comment by lfarah** [comment]
+ 1

**Comment by CoderMJLee** [comment]
Thank you.Recently I try to take the time to write a English version.

**Comment by dkhamsing** [comment]
@CoderMJLee hi there, any time to work on this? Does not have to be the whole README, at least a section for how to install and get started

**Comment by dkhamsing** [comment]
I will remove this asap

**Comment by BruceChen5683** [comment]
@dkhamsing     https://github.com/CoderMJLee/MJRefresh/pull/590, @zzBelieve  translate it,this may can help u
