### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by bawn** [CoderMJLee/MJRefresh#57]
首先感谢MJ提供了这么好的工具
1. tableview同时集成了下拉刷新和上拉加载组件时，第一次自动的下拉更新的时候能看见footer的“点击加载更多字样”
2. 当数据加载完全之后，如果不手动调用noticeNoMoreData，再次上拉的时候footer就会出现快速状态切换的问题
3. 当手动调用noticeNoMoreData后，tableview再次刷新新的数据时，比如数据源数组减少了，会出现footer消失的问题

**Comment by CoderMJLee** [comment]
好的，谢谢反馈。
第1个问题：可以参考最新Demo的MJCollectionViewController里面是怎么处理的
第2个问题：数据加载完全后，建议一定要调用noticeNoMoreData哈
第3个问题：你先试试最新的框架，昨天改了一些小问题。
如果还有问题的话，麻烦你辛苦一点，整一份Demo给我看看哈，谢啦

**Comment by bawn** [comment]
谢谢@CoderMJLee
这是第三个问题的[demo](https://github.com/bawn/MJRefreshDemo)
操作步骤是：
1. 进入collectionview的例子(已改为使用tableview)
2. 上拉加载（上拉一次就会出现“已经全部加载完毕”）
3. 点击右上角的item，重新刷新tableview
4. 再次上拉刷新，footer就会消失

**Comment by CoderMJLee** [comment]
太感谢你了，问题已经修复
