### ISSUE TITLE
 UISearchDisplayController ~挡着了下拉刷新文字

### ISSUE THREAD

**Issue by Gaozn** [CoderMJLee/MJRefresh#573]
![mygif](https://cloud.githubusercontent.com/assets/10608257/14804743/8ae45dde-0b98-11e6-9c22-0f187a24dcaf.gif)
UISearchBarUISearchBar 和UISearchDisplayController结合使用时~ 
首先 self.tableView.tableHeaderView = searchBar;
    searchDisplayController = [[UISearchDisplayController alloc] initWithSearchBar:searchBar contentsController:self];//加了这句·~下拉刷新时的文字会被挡着~~ 怎么解决呢？之前都正常使用的

**Comment by Gaozn** [comment]
不是UISearchDisplayController挡着了~~~
UIView *view = [[UIView alloc] initWithFrame:(CGRect){0,0,SCREEN_WIDTH,44}];
[view addSubview:searchBar];
self.tableView.tableHeaderView = view;
这样就好了~~~不知道咋回事~~~

**Comment by CoderMJLee** [comment]
UISearchBar是系统自带的控件，内部有很多默认行为。tableHeaderView和tableFooterView也是比较特殊的属性，有很多默认行为。一般情况下，可以考虑包装一个UIView来处理

**Comment by Gaozn** [comment]
谢谢~

**Comment by fuboyou** [comment]
我在UISearchController中也遇到了这个问题，使用View包装一下searchBar，再添加到tableHeaderView，同样了我的问题，感谢！
