### ISSUE TITLE
pagingEnabled= YES,下拉回弹

### ISSUE THREAD

**Issue by TLcv** [CoderMJLee/MJRefresh#584]
3.1版本，ScrollView设置分页，下拉刷新会出现回弹，取消分页状态是正常的；
看到issues里有好几个之前版本提到这个问题，但是目前版本还是有存在这个问题。。。

**Comment by shiyaorong** [comment]
这个问题解决了吗？急。

**Comment by TLcv** [comment]
@shiyaorong
我目前是这样做的，在MJRefreshHeader.m
willMoveToSuperview方法里记录状态
self.savePage = self.scrollView.pagingEnabled;

转为即将刷新状态时添加
_scrollView.pagingEnabled = NO;

恢复inset和offset动画结束时添加
_scrollView.pagingEnabled = self.savePage;

最后自己监听scrollViewDidEndDecelerating代理方法
设置 self.scroll.pagingEnabled = YES;

**Comment by HJXu** [comment]
我的也出现了这个问题,你们解决后还有问题吗,可以加个联系方式?我想请教你下,谢谢.QQ1527237042

**Comment by shiyaorong** [comment]
我上拉加载的时候修改了他的偏移量，让他回弹原来的样子。
CGFloat everyPageHeight = SCREEN_HEIGHT - NAVIBAR_HEIGHT - TABBAR_HEIGHT + FITHEIGHT(7);
    CGFloat nextPageOffset = (currentPage + 1) * everyPageHeight;
    [self.collectionView setContentOffset:CGPointMake(0, nextPageOffset) animated:YES];

**Comment by HJXu** [comment]
好的,方便加个联系方式吗

**Comment by HJXu** [comment]
我早上改了下MJ框架内部代码,暂时可以满足我的需求.不知道后期会不会出现问题

**Comment by shiyaorong** [comment]
我之前改过，当这个页面没数据的时候，你下拉就会飘，你单一个加载还行，如果有刷新又有加载，那么问题就有很多，

**Comment by HJXu** [comment]
我现在改了之后,没有回弹.

**Comment by shiyaorong** [comment]
那就可以了

**Comment by alexiscn** [comment]
I found some tricky method to solve this problem.

add scrollViewDidScroll delegate to your UICollectionView or  UITableView. 

if `contentOffset.y < 0` means we are pulling, then we disable pagingEnable of the scrollView
else enable pagingEnable.

Hope that helps

**Comment by HJXu** [comment]
thank you

**Comment by wolfcon** [comment]
#311

**Comment by sunhuaiwu** [comment]
> I found some tricky method to solve this problem.
> 
> add scrollViewDidScroll delegate to your UICollectionView or UITableView.
> 
> if `contentOffset.y < 0` means we are pulling, then we disable pagingEnable of the scrollView
> else enable pagingEnable.
> 
> Hope that helps

Nice
