### ISSUE TITLE
下拉刷新抖动

### ISSUE THREAD

**Issue by iURWang** [CoderMJLee/MJRefresh#587]
- (void)setMj_offsetX:(CGFloat)mj_offsetX
  {
  CGPoint offset = self.contentOffset;
  offset.x = mj_offsetX;
  self.contentOffset = offset;
  }
  改为：
- (void)setMj_offsetX:(CGFloat)mj_offsetX
  {
  CGPoint offset = self.contentOffset;
  offset.x = mj_offsetX;
  [self setContentOffset:offset animated:NO];
  }

**Comment by hhw2020** [comment]
应该是改setMj_offsetY吧
