### ISSUE TITLE
UITableViewAutomaticDimension Bug

### ISSUE THREAD

**Issue by rongloveyan** [CoderMJLee/MJRefresh#595]
当uitableview设置了UITableViewAutomaticDimension后，footer会无限滑动，无限load more，求解决

**Comment by MrReN** [comment]
MJ应该不更新这个库了，这个问题好像一直没解决@CoderMJLee

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
