### ISSUE TITLE
杰哥,最新版本3.1.0下拉控件显示问题

### ISSUE THREAD

**Issue by coderflower** [CoderMJLee/MJRefresh#599]
- (void)setupTableView
  {
  // 添加下拉控件
    self.tableView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreStatues)];
  }

/**
-  上拉加载更多数据
  */
  - (void)loadMoreStatues
    {
    // 程序不执行到该方法,试过不论是MJRefreshAutoNormalFooter MJRefreshBackNormalFooter ,都不会调用,该方法,直接用block形式的也不回调
    NSLog(@"%s",**func**);
    }

// 最终解决使用MJRefresh 3.0.8 什么都没改直接就好使啦

**Comment by PengfeiWang666** [comment]
杰哥，NavigationController+WKWebView，下拉刷新完毕以后，webView.scrollView的contentOffset.y变成0，导致部分页面被NavigationBar遮挡

**Comment by ChrisCaixx** [comment]
我遇到的问题是,如果在tableView的数据源方法 numberOfRowsInSection
中设置隐藏footer,那么就会直接不显示footer了,之前用3.0.8正常的,用3.1.0就会这样,在3.1.0里面不能在numberOfRowsInSection方法中隐藏footer
,应该是只需要调用footer的endRefreshing方法;

2016-05-21 15:03 GMT+08:00 王鹏飞 <notifications@github.com>:

**Comment by ChrisCaixx** [comment]
我遇到的问题是,如果在tableView的数据源方法 numberOfRowsInSection 中设置隐藏footer,那么就会直接不显示footer了,之前用3.0.8正常的,用3.1.0就会这样,在3.1.0里面不能在numberOfRowsInSection方法中隐藏footer ,应该是只需要调用footer的

**Comment by ChrisCaixx** [comment]
我遇到的问题是,如果在tableView的数据源方法 numberOfRowsInSection 中设置隐藏footer,那么就会直接不显示footer了,之前用3.0.8正常的,用3.1.0就会这样,在3.1.0里面不能在numberOfRowsInSection方法中隐藏footer ,应该是只需要调用footer的endRefreshing就可以了

**Comment by iHTCboy** [comment]
[footer setAutomaticallyHidden:YES]

也没有起作用啊！！
