### ISSUE TITLE
- (MJRefreshLegendHeader *)addLegendHeader;

### ISSUE THREAD

**Issue by heistings** [CoderMJLee/MJRefresh#60]
请问 `- (MJRefreshLegendHeader *)addLegendHeader;` 这个接口的意义何在？

**Comment by CoderMJLee** [comment]
当初设计的初衷是希望开发者把更多的精力放到header身上，不要关注scrollView，所以希望开发者能先添加header，然后拿到header进行相应的设置

**Comment by heistings** [comment]
我的意思是，它没有回调接口？什么情况下，我会使用 `- (MJRefreshLegendHeader *)addLegendHeader;` 而不是 `- (MJRefreshLegendHeader *)addLegendHeaderWithRefreshingBlock:(void (^)())block;` ?

**Comment by heistings** [comment]
还有就是，为什么会有两种接口？`- (MJRefreshLegendHeader *)addLegendHeaderWithRefreshingTarget:(id)target refreshingAction:(SEL)action;` 和 `- (MJRefreshLegendHeader *)addLegendHeaderWithRefreshingBlock:(void (^)())block;`

**Comment by CoderMJLee** [comment]
其实addLegendHeader可以删掉。
有些人喜欢用block回调，所以提供addLegendHeaderWithRefreshingBlock:。
但是block有循环引用问题，需要通过__weak来解决，有些人不喜欢，所以提供了target和action的方式

**Comment by heistings** [comment]
我有一个想法，可以考虑为 2.0的接口，大致的使用流程如下：

1. 初始化一个 MJRefreshGifHeader/MJRefreshLegendHeader，setup 它的属性；
2. 设置为 scrollView的 headerview: `@property (nonatomic, strong) MJRefreshHeader *header;`
3. MJRefreshGifHeader/MJRefreshLegendHeader 以 delegate 的形式进行回调

原因如下：
a. 用户可以自己实现 MJRefreshHeader 的子类，进一步定制自己的功能;
b. 我们没有在 view 中使用 GCD，使用 block 可能有点过度设计；只有 UIButton 这样有很多 UIControlEvent 的 UIControl使用的是 target & action接口，绝大多数如 UITableView, UIScrollView使用的都是 delegate协议回调。

**Comment by CoderMJLee** [comment]
1. 在2013年刚创建这个MJRefresh时，当时使用的是delegate\协议的方式，虽然规范，后来因为觉得代码量较多、事件也比较单一，就一个进入刷新事件，所以转为block和target\action。
2. 其实delegate还有个好处就是以后可以传递更多的事件出去，进行更多个性化的定制。
3. @property (nonatomic, strong) MJRefreshHeader *header;这条建议我觉得非常赞，这样就不仅仅局限于addLegendHeader和addGifHeader了，只要是MJRefreshHeader就OK。
4. 可以考虑在2.0版本增加自定义header的功能，做一些更加个性化的定制。谢谢提醒，太棒了！

**Comment by heistings** [comment]
@CoderMJLee 感谢你的耐心与投入，真是太棒了！

**Comment by CoderMJLee** [comment]
我觉得@property (nonatomic, weak) MJRefreshHeader *header;会不会更好？添加到scrollView内部的控件，没必要strong了

**Comment by heistings** [comment]
我的理解是这样的:

1. 如果声明 `@property (nonatomic, strong) id property;` 自己又没有写 setter，框架自动生成的代码大概是：

    **非ARC**
    
    ```objective-c
    - (void)setProperty:(id)property
    {
        _property = [property retain];
    }
    ```

2. 如果声明 `@property (nonatomic, strong) id property;` 自己写了 setter，那么我们实现的代码就应该遵循 strong 的声明，换句话说，也应该做上面那样的处理。或者反过来将，这时候声明应该根据实现。

3. 同理，`@property (nonatomic, weak) id property;` 对应的默认代码：

	**非ARC**
	
    ```objective-c
    - (void)setProperty:(id)property
    {
        _property = property;
    }
    ```

**Comment by CoderMJLee** [comment]
现在都是ARC环境了。weak会比strong安全点，当header销毁了，weak指针会自动变为nil指针，不再引用那个内存，就不会有野指针现象存在哈

**Comment by heistings** [comment]
用非 ARC只是为了更好的说明，参考 UITableView，tableHeaderView 和 tableFooterView也是 subView：

```
@property (nonatomic, retain) UIView *tableHeaderView;
@property (nonatomic, retain) UIView *tableFooterView;
```

**Comment by heistings** [comment]
@CoderMJLee 我 update了几次，刚开始没写好，麻烦你重新看一眼……

**Comment by CoderMJLee** [comment]
哈哈，我觉得都行吧，使用习惯和理解方式不一样。那就用strong了。

**Comment by heistings** [comment]
👍

**Comment by heistings** [comment]
我仔细想了想，用 OBJC_ASSOCIATION_ASSIGN 没关系，但是 `[self addSubview:header];` 了引用计数加1了声明应该用 strong。你是打算用 OBJC_ASSOCIATION_RETAIN 了吗？

**Comment by CoderMJLee** [comment]
[self addSubview:header]的计数器加减是由self内部管理的，跟外面声明无关。所以我觉得外面strong和weak都行的哈。可以继续用OBJC_ASSOCIATION_ASSIGN，表面strong和weak没关系，关键看我们内部用啥

**Comment by heistings** [comment]
我的意思是，内部实现应该与外部声明一致。我们跳出来，我是一个用户，正在写 controller，如果我遇到一个 weak 的 property，那我通常还需要声明一个 strong（默认变量是 strong） 的变量来持有它。但是我们实际上的内部实现是 strong的，这意味着用户没必要再额外声明一个变量来持有它，只需要设新的值就可以。

**Comment by CoderMJLee** [comment]
赞！👍！这个解释真正地说服我了！
那就外面用strong，内部的addSubView其实就相当于strong了，所以继续用OBJC_ASSOCIATION_ASSIGN

**Comment by heistings** [comment]
理解万岁👍

**Comment by CoderMJLee** [comment]
另外我打算开个2.0分支，准备加入自定义header和footer的功能

**Comment by heistings** [comment]
我 pull了一个  2.0，开始给 header写构造方法，但是它应该被 merge 到新的2.0分支上。构造方法有了之后，我们再把 header 改成 strong，这样就可以开始改 demo了。

**Comment by heistings** [comment]
当然，在这之前，我们可以重新设计一下 header 的回调接口，保留一套就够了：比如改成 delegate，然后在状态切换的时候回调。

**Comment by danipralea** [comment]
can anyone care to translate this stuff?
I just updated to 2.4.7 from 1.4.7 and I encounter a lot of errors

**Comment by CoderMJLee** [comment]
@danipralea Please reference to the README, thanks.

**Comment by danipralea** [comment]
Thank you @CoderMJLee !
