### ISSUE TITLE
iOS 9 提示语言本地化的问题

### ISSUE THREAD

**Issue by xiaolouxinyue** [CoderMJLee/MJRefresh#602]
比如上拉刷新的时候，显示的是英文的提示  lastupdate ...

现在通过改您的框架解决了，还是希望您能抽空更新下。

**Comment by qfyige** [comment]
self.automaticallyAdjustsScrollViewInsets ＝ NO;设置这句话 也不行么 ，我用web的时候没有这个问题 。                             原始邮件                             发件人: xiaolouxinyue<notifications@github.com>收件人: CoderMJLee/MJRefresh<MJRefresh@noreply.github.com>发送时间: 2016年5月23日(周一) 11:07主题: [CoderMJLee/MJRefresh] iOS 9 提升语言本地化的问题 (#602)比如上拉刷新的时候，显示的是英文的提示  lastupdate ...

现在通过改您的框架解决了，还是希望您能抽空更新下。

**Comment by xiaolouxinyue** [comment]
语言选择的问题。调试代码的时候，发现首选语言的第一个是zh-Hans-CN。多了一个这个，导致默认选择了英文

**Comment by CoderMJLee** [comment]
已经做了本地化处理，可以下载最新版试试

**Comment by xiaopin** [comment]
针对iOS9以上的本地化处理，在iOS10模拟器下会崩溃，崩溃代码为MJRefreshComponent.m第150行，原因是执行NSString *language = [NSLocale preferredLanguages].firstObject;这行代码后，language值为@"en"并非是@"en-US"，但是iPhone5S iOS10真机测试通过，所以可能只是模拟器问题，或者可能iOS后续版本会再次进行调整。
