### ISSUE TITLE
iOS7下自定义gifHeader/gifFooter(添加约束时Crash)(新版本修复了吗?)

### ISSUE THREAD

**Issue by yuanshuainiuniu** [CoderMJLee/MJRefresh#606]
原因:MJRefreshComponent.m文件里
- (void)layoutSubviews
  {
  [super layoutSubviews];
  
  [self placeSubviews];  
  }
  应改为
- (void)layoutSubviews
  {
  [self placeSubviews];
  
  [super layoutSubviews];

}

**Comment by yuanshuainiuniu** [comment]
新版本修复了吗?

**Comment by CoderMJLee** [comment]
为啥会crash？错误信息是？

**Comment by yuanshuainiuniu** [comment]
*** Assertion failure in -[CustomerRefreshHeader layoutSublayersOfLayer:], /SourceCache/UIKit/UIKit-2903.23/UIView.m:8540

**Comment by yuanshuainiuniu** [comment]
//
//  CustomerRefreshHeader.m
//  lyfen
//
//  Created by laiyifen on 15/11/2.
//  Copyright © 2015年 YU Harry. All rights reserved.
//

#import "CustomerRefreshHeader.h"
@implementation CustomerRefreshHeader

#pragma mark - 重写方法
#pragma mark 基本设置
- (void)prepare
{
    [super prepare];
    
    // 设置普通状态的动画图片
    NSMutableArray *idleImages = [NSMutableArray array];
    for (NSUInteger i = 1; i<=20; i++) {
        UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"loading%zd", i]];
        [idleImages addObject:image];
    }
    [self setImages:idleImages forState:MJRefreshStateIdle];
    
    // 设置即将刷新状态的动画图片（一松开就会刷新的状态）
    NSMutableArray *refreshingImages = [NSMutableArray array];
    for (NSUInteger i = 1; i<=40; i++) {
        UIImage *image = [UIImage imageNamed:[NSString stringWithFormat:@"loading%zd", i]];
        [refreshingImages addObject:image];
    }
    [self setImages:refreshingImages forState:MJRefreshStatePulling];
    
    // 设置正在刷新状态的动画图片
    [self setImages:refreshingImages forState:MJRefreshStateRefreshing];
    
    // 设置文字
    [self setTitle:@"下拉即可刷新" forState:MJRefreshStateIdle];
    [self setTitle:@"松开立即刷新" forState:MJRefreshStatePulling];
    [self setTitle:@"正在刷新中..." forState:MJRefreshStateRefreshing];
    // 设置字体
    self.stateLabel.font = [UIFont boldSystemFontOfSize:14];
    self.lastUpdatedTimeLabel.font = [UIFont systemFontOfSize:12];
    
    // 设置颜色
    self.stateLabel.textColor = [UIColor colorWithHexString:@"#666666"];
    self.lastUpdatedTimeLabel.textColor = [UIColor lightGrayColor];
    
}
- (void)placeSubviews{
    
    self.mj_h = MJRefreshHeaderHeight;
    self.gifView.contentMode = UIViewContentModeScaleAspectFit;
    [self.gifView mas_remakeConstraints:^(MASConstraintMaker *make) {
        make.width.mas_equalTo(RealValue(30));
        make.height.equalTo(self.gifView.mas_width);
        make.centerY.equalTo(self);
    }];
    [self.stateLabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.equalTo(self.gifView);
        make.centerX.equalTo(self);
        make.left.equalTo(self.gifView.mas_right).mas_equalTo(5);
    }];
    [self.lastUpdatedTimeLabel mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.equalTo(self.stateLabel);
        make.top.equalTo(self.stateLabel.mas_bottom).mas_equalTo(5);
    }];
    [super placeSubviews];

}
- (void)setImages:(NSArray *)images forState:(MJRefreshState)state
{
    [self setImages:images duration:images.count * 0.02 forState:state];
}
@end

**Comment by yuanshuainiuniu** [comment]
[
![e94ade2c-d1b5-451e-9cf9-84381eaba14c](https://cloud.githubusercontent.com/assets/9314006/16513091/501544e0-3f94-11e6-9834-bc256177e880.png)
](url)

**Comment by huang1988519** [comment]
[self setImages:[self imageNamesFrom:start end:end] forState:MJRefreshStateRefreshing];
这样写时崩溃libc++abi.dylib: terminate_handler unexpectedly threw an exception
，但是
[self setImages:[self imageNamesFrom:start - 30/*空白帧*/ end:endOfOneLoop] forState:MJRefreshStateIdle];

idle 不会崩溃。
