### ISSUE TITLE
使用cocoapods导入MJRefresh使用时崩溃

### ISSUE THREAD

**Issue by jin1050260** [CoderMJLee/MJRefresh#609]
崩溃在- (void)setMj_h:(CGFloat)mj_h方法
崩溃原因CUICatalog: Invalid asset name supplied: 
2016-05-26 15:29:12.391 FKBSAAS[29716:1946497] -[MJRefreshNormalHeader setMj_h:]: unrecognized selector sent to instance 0x7fae838ec5a0
2016-05-26 15:29:25.415 FKBSAAS[29716:1946497] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MJRefreshNormalHeader setMj_h:]: unrecognized selector sent to instance 0x7fae838ec5a0'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010ca4bd85 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010f5fadeb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010ca54d3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
    3   CoreFoundation                      0x000000010c99acfa ___forwarding_** + 970
    4   CoreFoundation                      0x000000010c99a8a8 _CF_forwarding_prep_0 + 120
    5   FKBSAAS                             0x0000000108d5bdf4 -[MJRefreshHeader prepare] + 116
    6   FKBSAAS                             0x0000000108d5f076 -[MJRefreshStateHeader prepare] + 54
    7   FKBSAAS                             0x0000000108d5d5e6 -[MJRefreshNormalHeader prepare] + 54
    8   FKBSAAS                             0x0000000108d59f7f -[MJRefreshComponent initWithFrame:] + 159
    9   UIKit                               0x000000010e11119e -[UIView init] + 62
    10  FKBSAAS                             0x0000000108d5bc63 +[MJRefreshHeader headerWithRefreshingBlock:] + 83
    11  FKBSAAS                             0x00000001086d91ce -[CJExpenseListViewController myTableView] + 1310
    12  FKBSAAS                             0x00000001086dde44 -[CJExpenseListViewController viewDidLoad] + 116
    13  UIKit                               0x000000010e219984 -[UIViewController loadViewIfRequired] + 1198
    14  UIKit                               0x000000010e219cd3 -[UIViewController view] + 27
    15  FKBSAAS                             0x0000000108a42f9c -[SlideSwitchView setup] + 908
    16  FKBSAAS                             0x0000000108a4317a -[SlideSwitchView reloadData] + 58
    17  FKBSAAS                             0x0000000108829799 -[CJExpenseViewController initAppearance] + 761
    18  FKBSAAS                             0x0000000108828e9c -[CJExpenseViewController viewDidLoad] + 92
    19  UIKit                               0x000000010e219984 -[UIViewController loadViewIfRequired] + 1198
    20  UIKit                               0x000000010e21f93b -[UIViewController __viewWillAppear:] + 120
    21  UIKit                               0x000000010e24f750 -[UINavigationController _startCustomTransition:] + 1203
    22  UIKit                               0x000000010e25fb9b -[UINavigationController _startDeferredTransitionIfNeeded:] + 712
    23  UIKit                               0x000000010e260d0b -[UINavigationController __viewWillLayoutSubviews] + 57
    24  UIKit                               0x000000010e40f503 -[UILayoutContainerView layoutSubviews] + 248
    25  UIKit                               0x000000010e139980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
    26  QuartzCore                          0x000000010be2ac00 -[CALayer layoutSublayers] + 146
    27  QuartzCore                          0x000000010be1f08e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    28  QuartzCore                          0x000000010be1ef0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    29  QuartzCore                          0x000000010be133c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
    30  QuartzCore                          0x000000010be41086 _ZN2CA11Transaction6commitEv + 486
    31  QuartzCore                          0x000000010be417f8 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 92
    32  CoreFoundation                      0x000000010c970c37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    33  CoreFoundation                      0x000000010c970ba7 __CFRunLoopDoObservers + 391
    34  CoreFoundation                      0x000000010c9667fb __CFRunLoopRun + 1147
    35  CoreFoundation                      0x000000010c9660f8 CFRunLoopRunSpecific + 488
    36  GraphicsServices                    0x0000000112944ad2 GSEventRunModal + 161
    37  UIKit                               0x000000010e07ef09 UIApplicationMain + 171
    38  FKBSAAS                             0x0000000108a1bbef main + 111
    39  libdyld.dylib                       0x0000000110fdc92d start + 1
    40  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

手动导入库倒是没有问题

**Comment by Jowyer** [comment]
+1
