### ISSUE TITLE
貌似没有支持Carthage

### ISSUE THREAD

**Issue by seedotlee** [CoderMJLee/MJRefresh#613]
最近换Carthage了，但是拉控件的时候发现MJRefresh竟然不支持Carthage，于是自己fork了一个，
在工程里面添加了一个MJRefresh的framework用于支持Carthage。**但是需要将工程的deployment target改为8.0**，我也推了这个PR，不知道您愿不愿接受这个PR，但是为了有使用Carthage的同学方便，将我自己的链接放上了

https://github.com/seedotlee/MJRefresh.git

**Comment by CoderMJLee** [comment]
已经支持Carthage了
