### ISSUE TITLE
NavigationController+WKWebView下拉刷新问题

### ISSUE THREAD

**Issue by PengfeiWang666** [CoderMJLee/MJRefresh#620]
NavigationController+ViewController+WKWebView下拉刷新的时候，有50%几率造成刷新后webView的上移，即frame相对屏幕为self.view.bounds

**Comment by DarkAngel7** [comment]
我也出现同样的问题，找不到解决办法，不知你解决了吗？

**Comment by wolfcon** [comment]
你的下拉刷新调用的是什么方法? reload? 你需要监听 HTML 的 `document.body.offsetHeight` 去对页面进行微调, 因为渲染到 ScrollView 的关系, 这个 ContentSize 会异常. 每个系统实现还有可能因为 Apple 修改 Renderer 的关系, 导致其他 bug
