### ISSUE TITLE
偶遇一个蛋疼BUG，因为MJRefreshFooter创建方法错误，导致Footer遮挡住了顶部Header的点击事件

### ISSUE THREAD

**Issue by moosoul** [CoderMJLee/MJRefresh#621]
在一个collectionView中，有Header的时候。
我添加错了footer
添加方式为

``` objectivec
    collectionView.mj_footer = [MJRefreshFooter footerWithRefreshingBlock:^{
        [collectionView.mj_footer endRefreshing];
    }];
```

此时问题来了，第一个Header的点击时间无论如何无法响应。

一分析视图发现是 MJRefreshFooter视图覆盖在我的第一行Header之上了。

---

真是炸了一半天没找出问题，有同样问题的小伙伴可以看看是不是 MJRefreshFooter 写错了....

---

tag: collectionView header 第一行 不响应 点击事件

**Comment by SpacetimeMaster** [comment]
我现在用的3.7.5也出现了这个问题,
[MJRefreshFooter footerWithRefreshingBlock:^{
        [collectionView.mj_footer endRefreshing];
    }];
用的这个方法创建的,footer跑到tab顶部把第一行的cell挡住了

**Comment by Caprioce** [comment]
> 我现在用的3.7.5也出现了这个问题, [MJRefreshFooter footerWithRefreshingBlock:^{ [collectionView.mj_footer endRefreshing]; }]; 用的这个方法创建的,footer跑到tab顶部把第一行的cell挡住了

兄弟解决了吗
