### ISSUE TITLE
CollectionView Footer

### ISSUE THREAD

**Issue by yun0628** [CoderMJLee/MJRefresh#625]
@CoderMJLee 
我有一个collection 布局 有点复杂 我用sb绘制了一个footer  然后当我加载时 第一页只有一个数据的时候 无论如何都没办法把footer 给干掉不知道是否是我自定义的 和mj_footer 的冲突了 

我把能找到隐藏的方法都给写上去了 还是不行 刚看了一个删除footer的方法  删除后如何再添加上去呢  跪求小马哥 解答 。。。
` [self.orderCollectionView.mj_footer endRefreshing];
                [self.orderCollectionView.mj_footer endRefreshingWithNoMoreData];
                self.orderCollectionView.mj_footer.automaticallyHidden = YES;
                [self.orderCollectionView.mj_footer resetNoMoreData];
                self.orderCollectionView.mj_footer.hidden = YES;

![simulator screen shot 2016 6 6 15 58 09](https://cloud.githubusercontent.com/assets/8709108/15815481/f334484a-2bff-11e6-9db5-f7cb7802b8ed.png)`

**Comment by CoderMJLee** [comment]
删除以后，重新创建设置mj_footer就可以了
