### ISSUE TITLE
MJ老师好，如何取消第一次进入界面的这次刷新呢

### ISSUE THREAD

**Issue by liuyan3176** [CoderMJLee/MJRefresh#63]
每次进入界面都需要刷新，用户会感觉界面很卡的样子....

**Comment by liuyan3176** [comment]
另外还有两个小问题，在UITableView界面，loadNewData 里用以下的顺序感觉速度会快一些。
// 拿到当前的下拉刷新控件，结束刷新状态
    [_tbView.header endRefreshing];
    [self getMeetingMsg];    
    // 刷新表格
    [_tbView reloadData];
另外一个也是在UITableView，当右侧有index索引时，下拉刷新会造成index位置改变，导致界面在这一段时间变得比较难看....

**Comment by CoderMJLee** [comment]
不希望进入界面就刷新，那就不要调用[self.tableView.header beginRefreshing]

**Comment by heistings** [comment]
@liuyan3176 
1. 如果你希望用户第二次进入这个界面的时候仍然保留上一次的状态：
    a. 只在 `- (void)viewDidLoad` 中调用 `[self.tableView.header beginRefreshing]`(Demo中也是这样用的)
    b. 返回上一级 controller 时候不要销毁刚才 push 的 controller，除非用户进入另一个 subController(参考百度贴吧 iOS客户端，反复点击同一个帖子，内容是不会刷新的)
2. 这得看产品定义，一般情况下的定义都是新数据回来之前，header一直是刷新状态；
3. `下拉刷新会造成index位置改变，导致界面在这一段时间变得比较难看` 这个问题能否麻烦你提供相关截图说明？

**Comment by liuyan3176** [comment]
前两个问题都解决了，非常感谢。
最后index的问题可能我之前描述的不太清楚，当下拉准备刷新时右侧的index位置并没有变化，不过松开手指，index会瞬间向上滑动至header的位置，然后回到原位。此时显示的是正在刷新数据中...因为需要读取数据，会有零点几秒的时间index保持固定，但是结束刷新后index又会出现向下的位移，然后恢复原位，这时整个界面读取刷新完毕
因为index的两次不规则位移，导致了界面右侧index位置的混乱。

**Comment by heistings** [comment]
@liuyan3176 我重现了这个问题，这个问题是由于修改了 contentInset导致的。我感觉这个问题很难修正，因为我们在 UIScrollView 上工作，不方便对 UITableView 的 indexView 进行追踪，以后可能还会有更多的 UIScrollView子类……

我有一个解决方案，就是使用 indexView的替代方案，这样 indexView 在 UITableView 的外面。
[点击打开 MJNIndexView](https://github.com/matthewfx/MJNIndexView)

@CoderMJLee 你什么看法？

**Comment by CoderMJLee** [comment]
只要是黏在tableView上的控件，都不好控制，所以如果坚持使用tableView自带的indexView，这个问题几乎无法解决。可以考虑使用你推荐的第三方IndexView：[IndexView](https://github.com/matthewfx/MJNIndexView)
