### ISSUE TITLE
国际化 怎么用啊   MJRefresh 3.1.3  解决问题了  有问题的朋友请升级库

### ISSUE THREAD

**Issue by wxpasta** [CoderMJLee/MJRefresh#633]
真机操作  pod更新之后 效果全变成英文  我需要什么操作    （模拟器没问题）

**Comment by CoderMJLee** [comment]
你的模拟器或者设备是中文么？

**Comment by wxpasta** [comment]
我iOS9.3.1 真机  iphone6s

**Comment by chinesemanbobo** [comment]
同求！！！设置了一番还是英文！

**Comment by CoderMJLee** [comment]
我的手机和模拟器上没有问题哦，你们试试最新的3.1.2版本安徽

**Comment by wxpasta** [comment]
我没做国际化  是不是还要配置一些东西

**Comment by CoderMJLee** [comment]
只要你的设备是中文环境就行

**Comment by chinesemanbobo** [comment]
我也说不清，正在研究，也跟MJ沟通呢，还没回复，估计很快会有结果！




发自 网易邮箱大师
在2016年06月13日 20:07，巴糖 写道:

我没做国际化 是不是还要配置一些东西

**Comment by chinesemanbobo** [comment]
我的是中文，你看我给你微博私信的截图，还是我配置错了？




发自 网易邮箱大师
在2016年06月13日 20:13，M了个J 写道:

只要你的设备是中文环境就行

**Comment by wxpasta** [comment]
你没做配置吗

**Comment by chinesemanbobo** [comment]
没有，明天有空配置下！


发自 网易邮箱大师
在2016年06月13日 20:29，巴糖 写道:

你没做配置吗

**Comment by wxpasta** [comment]
我一个工程 包含几个项目

**Comment by CoderMJLee** [comment]
你们再试试吧，这次应该没问题里，上次的bug是因为没有兼容pod 1.x

**Comment by chinesemanbobo** [comment]
好的，正在下载！


发自 网易邮箱大师
在2016年06月13日 21:38，M了个J 写道:

你们再试试吧，这次应该没问题里，上次的bug是因为没有兼容pod 1.x

**Comment by wxpasta** [comment]
-> Installing MJRefresh 3.1.3 (was 3.1.2)   问题解决了

**Comment by CoderMJLee** [comment]
@wxpasta @chinesemanbobo 谢谢你们的支持
