### ISSUE TITLE
UIViewController+Example.h这个类到底怎么用？

### ISSUE THREAD

**Issue by wangjuanlsx** [CoderMJLee/MJRefresh#635]
在MJExampleViewController这个类里看你导入了UIViewController+Example.h，但是我把它删了程序也没有报错，后面只有两个类导入了UIViewController+Example.h，但是，到底在哪里删除。我看遍了代码，没找到调用这个方法啊！但是运行的时候又有调用
- (void)load
  {
  Method method1 = class_getInstanceMethod([self class], NSSelectorFromString(@"dealloc"));
  Method method2 = class_getInstanceMethod([self class], @selector(deallocSwizzle));
  method_exchangeImplementations(method1, method2);
  }
- (void)deallocSwizzle
  {
  NSLog(@"%@被销毁了", self);
  
  [self deallocSwizzle];  （这里为什么还要再杀自己一次）
  }
  后两个类导入的UIViewController+Example.h只看到调用了这两个方法啊
  static char MethodKey;
- (void)setMethod:(NSString *)method
  {
  objc_setAssociatedObject(self, &MethodKey, method, OBJC_ASSOCIATION_COPY_NONATOMIC);
  }
- (NSString *)method
  {
  return objc_getAssociatedObject(self, &MethodKey);
  }

**Comment by wangjuanlsx** [comment]
qq：429811196   谁知道作者试例中这个类到底怎么使用的UIViewController+Example.h！！！
qq：429811196   谁知道作者试例中这个类到底怎么使用的UIViewController+Example.h！！！
qq：429811196   谁知道作者试例中这个类到底怎么使用的UIViewController+Example.h！！！

**Comment by CoderMJLee** [comment]
App运行时，系统会自动调用UIViewController+Example的load方法，然后交换deallocSwizzle和dealloc方法的实现
