### ISSUE TITLE
localizedStringForKey报错

### ISSUE THREAD

**Issue by yuzhiyou1990** [CoderMJLee/MJRefresh#637]
MJRefreshComponent.m的localizedStringForKey需要加上range.location != NSNotFound这句不然会报错（测试设备iphone4s模拟器）
比如language是en，range就是NSNotFound，会导致substringToIndex:range异常退出

、、、、、、、、、、、、、以下是加上后代码片段、、、、、、、、、、、、
 // 获得设备的语言
        NSString *language = [NSLocale preferredLanguages].firstObject;
        // 如果是iOS9以上，截取前面的语言标识
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
               NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
               if(range.location != NSNotFound)
                   language = [language substringToIndex:range.location];
        }

**Comment by zhuozhuo** [comment]
我也刚才被苹果打回，刚检查到这个地方，
NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
  language = [language substringToIndex:range.location];
这写的太有问题了。

**Comment by CoderMJLee** [comment]
已经修复
