### ISSUE TITLE
明杰老师,今天更新的3.1.4会在系统语言是英文情况下造成死循环

### ISSUE THREAD

**Issue by RivenDarry** [CoderMJLee/MJRefresh#641]
![image](https://cloud.githubusercontent.com/assets/11863208/16038869/97e37cd0-3259-11e6-98d2-f43097157979.png)
当language = en时, 不含字符"-", 得到的location是一个无穷大的数, 然后会一直卡在这里.
考虑到有很多中国用户习惯使用英文系统, 该问题需要紧急修复.
目前我的工程已经回退到以前版本, 没有闪退.

**Comment by CoderMJLee** [comment]
最新代码已经改了的
```objc
if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
    NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
    if (range.location != NSNotFound) {
        language = [language substringToIndex:range.location];
    }
}
```
