### ISSUE TITLE
结束刷新和开始刷新同时调用问题

### ISSUE THREAD

**Issue by augsun** [CoderMJLee/MJRefresh#642]
结束刷新方法有一个0.1s的延迟
```objc
#pragma mark - 公共方法
- (void)endRefreshing
{
    if ([self.scrollView isKindOfClass:[UICollectionView class]]) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            [super endRefreshing];
        });
    } else {
        [super endRefreshing];
    }
}
```
如果是标签切换要结束上一次正在刷新然后再开始下一个刷新, 就会导致先开始刷新, 然后再结束. 最终导致不显示刷新.
类似百思不得姐的左侧关注很快点击的时候.调用
```objc
[self.collectionView.mj_header endRefreshing];
[self.collectionView.mj_header beginRefreshing];
```
有些地方又不会, 是啥情况...
上面的一个判断, 为什么呢...
```objc
[self.scrollView isKindOfClass:[UICollectionView class]]
```
试了下, 这个问题我是在 UICollectionView 下遇到, 然后用 UITableView 试, 居然不会...

是不是 UICollectionView 的刷新方法与 UI 布局的时机与 UITableView 的不同. 
似乎 UITableView 只要 reloadData 后 UI 的布局都是定好的, 而 UICollectionView 好像要等一段时间.

**Comment by CoderMJLee** [comment]
最新版本已经用别的方式取代0.1s了

**Comment by augsun** [comment]
如果

**Comment by CoderMJLee** [comment]
可以尝试这样
```objc
[self.collectionView.mj_header endRefreshing];
dispatch_after(.... {
    // 0.1s后执行这个代码
    [self.collectionView.mj_header beginRefreshing];
});
```

**Comment by augsun** [comment]
这样的话, 如果第二次在第一次触发后 0.1s 内触发, 如果有个标签页 self.currentIndex, 第一次触发 self.currentIndex = 1; 第二次 self.currentIndex = 2;
那么第一次由于 0.1s, 执行 @selector 的时候, 捕获的已经是被第二次触发修改后的 self.currentIndex = 2 了, 明明第一次触发要加载第一页, 却变成两次都加载第二页, 如果在 0.1s 内触发多页, 那么问题会变得更复杂. 我测了下, 好像 beginRefreshing 的发起会有这种情况.
```objc
// 下拉的 @selector(loadDataFromNet)
- (void)loadDataFromNet {
    printf("bbb");
}

// 其它方法
- (void)msgToMethod {
    printf("ccc");
}

// 刷新触发所在方法
- (void)btnAction {
    printf("aaa");
    [self.collectionView.mj_header beginRefreshing];
    [self msgToMethod];
}
```
打出的顺序是 aaa -> ccc -> bbb
似乎是因为动画时间 MJRefreshFastAnimationDuration 结束才执行 executeRefreshingCallback.
原来我理解的能马上调用它的 @selector 是不对的^^...以上所有问题我觉得是同步调用就好办了, 当然框架内部要考虑的远比想像的多.
这些似乎都是比较极端测试才会. 我也不折腾了, 浪费了小码哥这么多时间...

**Comment by CoderMJLee** [comment]
我在3.1.7加了2个新方法，保证代码的先后顺序你看看能不能满足你的要求
```objc
- (void)beginRefreshingWithCompletionBlock:(void (^)())completionBlock;
- (void)endRefreshingWithCompletionBlock:(void (^)())completionBlock;

__weak typeof(self) weakSelf = self;
[self.collectionView.mj_header beginRefreshingWithCompletionBlock:^{
    [weakSelf msgToMethod];
}];
```

**Comment by augsun** [comment]
现在我那个功能模块在外部用状态缓存做了, 有时间我再 branch 一个出来试试. 谢谢MJ大神```

**Comment by CoderMJLee** [comment]
不客气，谢谢你的使用与支持
