### ISSUE TITLE
所有 header 的最后更新时间是一个, 因为用了一个 key, 这样各个 header 就相互影响了.

### ISSUE THREAD

**Issue by g-enius** [CoderMJLee/MJRefresh#645]
现在的效果是第一个页面刷新之后, 之后页面在未刷新的时候就已经显示了第一个页面的最后刷新时间.
是不是应该每个页面都用不同的 Key (MJRefreshHeaderLastUpdatedTimeKey), 这样不同页面(比如 UITabBarController 里面的各个页面) 可以分别显示各自的最后刷新时间. 

![screen shot 2016-06-15 at 4 10 03 pm](https://cloud.githubusercontent.com/assets/16376917/16072902/e03a3ef8-3315-11e6-86b5-ca616b49b708.png)
![screen shot 2016-06-15 at 4 17 46 pm](https://cloud.githubusercontent.com/assets/16376917/16072904/e0a374c2-3315-11e6-9eda-8ec2dc304ecf.png)

**Comment by CoderMJLee** [comment]
是的，你可以这样设置key，可以保证不同控制器都有自己独立的时间
```objc
header.lastUpdatedTimeKey = NSStringFromClass(控制器类名);
```
