### ISSUE TITLE
明杰老师 3.1.5以上有个问题

### ISSUE THREAD

**Issue by lsflhuyy** [CoderMJLee/MJRefresh#646]
一个UIScrollView下拉刷新 处理完数据之后调用方法
` [self.scrollView.mj_header endRefreshing];`
然后我因为某种逻辑又需要调用setContentOffset方法
`[self.scrollView setContentOffset:CGPointZero animated:YES];`

控件的高度是50

这种情况下3.1.5以上 就导致这个UIScrollView更新完数据之后的ContentOffset多上移了50（一个mjheader的高度）
3.1.4以下没问题

**Comment by CoderMJLee** [comment]
为了解决你的这种情况，我加了个新方法，你试试。这样就可以保证是先结束刷新、再执行你自己的操作
```objc
__weak typeof(self) weakSelf = self;
[self.scrollView.mj_header endRefreshingWithCompletionBlock:^{
    [weakSelf.scrollView setContentOffset:CGPointZero animated:YES];
}];
```

**Comment by kingslay** [comment]
@CoderMJLee 这个对原有的代码改动量比较大。有些页面我们都会先调用endRefreshing 然后在调用beginRefreshing。但是因为现在你的endRefreshing是在异步主线程进行处理动画结束的。导致我们现在很多页面的下拉刷新动画都有问题了。特别是有些业务的是根据mj_header.state的状态来进行判断。但是endRefreshing是在异步进行设置状态。无法保证状态设置的先后顺序了。

**Comment by kingslay** [comment]
@CoderMJLee 我看了，你这个好像是为了解决0.1s延迟的问题。我不大清楚之前UICollectionView为什么有0.1的特殊处理。能不能还是只有UICollectionView放在异步主线程处理，不要影响到uitableview。

**Comment by CoderMJLee** [comment]
可以考虑自定义Header，重写以下几个方法（自定义Header以后还有很多好处，可以不修改框架源码就实现一些个性化的定制）
```objc
- (void)beginRefreshing
{
    self.state = MJRefreshStateRefreshing;
}

- (void)endRefreshing
{
    self.state = MJRefreshStateIdle;
}
```
