### ISSUE TITLE
beginRefreshing提示语问题

### ISSUE THREAD

**Issue by hengchengfei** [CoderMJLee/MJRefresh#648]
为何刚进入页面的时候，会显示“上拉加载更多”，这几个字能去掉吗（第一次进入的时候）

![1](https://cloud.githubusercontent.com/assets/3182964/16138922/f8f19940-3474-11e6-841e-4645e3c910ef.jpg)

**Comment by CoderMJLee** [comment]
那你就需要自己去隐藏它（因为你设置了footer，它肯定会出现的）
```objc
self.tableView.mj_footer.hidden = YES; // 后面再找个时机显示出来
```
