### ISSUE TITLE
设置endRefreshingWithNoMoreData后，如何再恢复上拉加载更多

### ISSUE THREAD

**Issue by hengchengfei** [CoderMJLee/MJRefresh#649]
比如一直上拉，直到加载更多完了后，再下拉刷新，此时应该恢复上拉加载更多

**Comment by CoderMJLee** [comment]
```objc
[footer resetNoMoreData];
```

**Comment by Will-ZJ** [comment]
> ```objc
> [footer resetNoMoreData];
> ```

resetNoMoreData无效，这时候的mj_footer的frame.y 值是个很大的值，上拉不能触发刷新，在tableview上

**Comment by wolfcon** [comment]
@Will-ZJ Demo?
