### ISSUE TITLE
代码设置scrollview的偏移量，触发刷新

### ISSUE THREAD

**Issue by PanZhow** [CoderMJLee/MJRefresh#652]
是这样的，我打算设置offset来触发刷新，但是我看到在源文件中判断scrollview是否在draging状态才执行。
请问有什么办法使用代码设置scrollview便宜来触发刷新么？用offset好像不能触发，并且可以拖动很多。

**Comment by qinxiaoxin** [comment]
同问 lz解决了没

**Comment by wolfcon** [comment]
如果使用偏移触发, 那么你要做的事情会多到你想象不到. 因为系统在很多情况下都会去修改 offset, 比如横竖屏, 切换 Navigation, 你适配 estimated height 设置不正确. 等等.
你自定义 Header/Footer 可以实现的, 参见 `AutoFooter` 里面有一个属性 `onlyRefreshPerDrag`, 关闭它, 就会使用 `offset`, 进行野蛮式触发了

**Comment by PanZhow** [comment]
感谢，使用 自定义 Header/Footer 是比较合适的方案。
