### ISSUE TITLE
MJ老师，请问最新框架怎么设置回中文

### ISSUE THREAD

**Issue by imbahong** [CoderMJLee/MJRefresh#653]
iOS9.0，操作系统是中文，用cocoa pods默认安装完是英文，重新安装好几遍，版本是3.1.7,小白求指教

**Comment by LaughDaxiong** [comment]
这个问题我也遇到过，有时是中文，有时是英文。是因为源码中的语言环境代码判断不够完善，或者是系统原因导致的。

**Comment by CoderMJLee** [comment]
系统返回的语言字符串确实不稳定，在不同的iOS版本下，返回的情况不一样。我改了下判断思路，请看最新的3.1.8，谢谢

**Comment by corderguo** [comment]
..

**Comment by imbahong** [comment]
下载最新版的依然是英文...

**Comment by rain1458** [comment]
你可以自定义提示文字

**Comment by IU-CC** [comment]
可以进框架里修改默认语言, 强制修改为zh-Hans即可

**Comment by CoderMJLee** [comment]
@imbahong 你的设备设置的啥语言

**Comment by imbahong** [comment]
MJ老师今天发现原因了，把模拟器设置成中文就好....，很谢谢您为小白解答 @CoderMJLee

**Comment by CoderMJLee** [comment]
不客气 @imbahong
