### ISSUE TITLE
本地化问题求解

### ISSUE THREAD

**Issue by LaughDaxiong** [CoderMJLee/MJRefresh#654]
李老师您好，我在使用该刷新的时候，发现本地化的一个问题，不知何原因，求解：
设备iphone5s，ios9.3，debug调试情况下，有时候运行到你的源码中的 NSString *language = [NSLocale preferredLanguages].firstObject;时，有时候获取结果为language=@“zh-Hans”，但是有时候却是language=@“zh-Hans-CN”。所以在接下来的代码
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
            if (range.location != NSNotFound) {
                language = [language substringToIndex:range.location];
            }
        }
中将可能导致language=@“zh”。最新版的虽然添加了[language isEqualToString:@"zh"]判断，但只是判断的HK，而此时我的设备中设置的语言环境是简体中文，所以显示可能导致问题。

请问该问题能否解决，或者说是如何导致的？
谢谢~

**Comment by CoderMJLee** [comment]
系统返回的语言字符串确实不稳定，在不同的iOS版本下，返回的情况不一样。我改了下判断思路，请看最新的3.1.8，谢谢

**Comment by LaughDaxiong** [comment]
修改后的方法，最新3.1.8中，使用了方法containsString，该方法最低只支持ios8，低于ios8将导致挂机。
- (BOOL)containsString:(NSString *)str NS_AVAILABLE(10_10, 8_0);

**Comment by CoderMJLee** [comment]
谢谢提醒，已经搞定这个低级错误
