### ISSUE TITLE
MJRefresh (3.1.7) 闪退

### ISSUE THREAD

**Issue by huangboju** [CoderMJLee/MJRefresh#656]
- (void)setState:(MJRefreshState)state
{
    MJRefreshCheckState
    
    // 根据状态做事情
    if (state == MJRefreshStatePulling || state == MJRefreshStateRefreshing) {
        NSArray *images = self.stateImages[@(state)];
        if (images.count == 0) return;
        
        [self.gifView stopAnimating];
        if (images.count == 1) { // 单张图片
            self.gifView.image = [images lastObject];
        } else { // 多张图片
            self.gifView.animationImages = images;
            self.gifView.animationDuration = [self.stateDurations[@(state)] doubleValue];
            [self.gifView startAnimating];
        }
    } else if (state == MJRefreshStateIdle) {
        [self.gifView stopAnimating];
    }
}

**Comment by CoderMJLee** [comment]
麻烦贴出报错信息，谢谢

**Comment by huangboju** [comment]
不好意思 是我自己错了 动态图片名字写错了  估计gifView那里为空 导致闪退  建议加个断言
