### ISSUE TITLE
轻微封装 有刷新效果 但是无法调用方法 求帮助

### ISSUE THREAD

**Issue by wxpasta** [CoderMJLee/MJRefresh#657]
#import "UICollectionView+AM.h"
#import "MJRefresh.h"

@implementation UICollectionView (AM)

#pragma mark -
- (void)wx_addHeaderForCollectionWithAddTarget:(nullable id)target action:(nullable SEL)action
{
    self.mj_header = [MJRefreshNormalHeader headerWithRefreshingTarget:target refreshingAction:@selector(action)];
    [self.mj_header beginRefreshing];
}

- (void)wx_addFooterForCollectionWithAddTarget:(nullable id)target action:(nullable SEL)action
{
    self.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:target refreshingAction:@selector(action)];
}
@end

调用方法     [self.collectionView wx_addFooterForCollectionWithAddTarget:self action:@selector(onRefreshFooter)];  无效  求帮助

**Comment by CoderMJLee** [comment]
去掉@selector
```objc
- (void)wx_addHeaderForCollectionWithAddTarget:(nullable id)target action:(nullable SEL)action
{
    self.mj_header = [MJRefreshNormalHeader headerWithRefreshingTarget:target refreshingAction:action];
    [self.mj_header beginRefreshing];
}

- (void)wx_addFooterForCollectionWithAddTarget:(nullable id)target action:(nullable SEL)action
{
    self.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:target refreshingAction:action];
}
```

**Comment by wxpasta** [comment]
不太懂 @selector(action)  和 action    区别   为什么要去掉@selector 使用
