### ISSUE TITLE
使用mj_header替代header crash问题

### ISSUE THREAD

**Issue by xiaoyadong** [CoderMJLee/MJRefresh#658]
`MJRefreshNormalHeader *header = [MJRefreshNormalHeader headerWithRefreshingTarget:self refreshingAction:@selector(loadNewData)];
    header.lastUpdatedTimeLabel.hidden = YES;
    header.stateLabel.hidden = YES;
    self.tableView.mj_header = header; // crash发生在这里
    [self.tableView.mj_header beginRefreshing];`
将mj_header替换为header则不会crash,但是会报出警告,提示使用mj_header.
若是使用错误,还请指教

**Comment by CoderMJLee** [comment]
麻烦贴出报错信息，谢谢

**Comment by RookiePyl** [comment]
我在用的时候 也出现了上述问题：（下面是控制台的报错提示）
[UITableView setMj_header:]: unrecognized selector sent to instance 0x7ff105832200

+[CATransaction synchronize] called within transaction

**Comment by RookiePyl** [comment]
MJRefresh 版本是3.1.12
