### ISSUE TITLE
最新版在我的工程里二级controller 刷新高度都偏低 换回3.0.7又正常了

### ISSUE THREAD

**Issue by applejian** [CoderMJLee/MJRefresh#659]
最新版在我的工程里二级controller 刷新高度都偏低 换回3.0.7又正常了

**Comment by CoderMJLee** [comment]
高度可以自由调整的哈
```objc
header.mj_h = 60;
```

**Comment by applejian** [comment]
比如说我界面结构是 
self.view 是全屏的 ，automaticallyAdjustsScrollViewInsets = NO
![img_9817](https://cloud.githubusercontent.com/assets/3965066/16651260/6c06cd8c-4475-11e6-8491-d1311cb9538b.PNG)

如果tableview上方有其他视图 就会出现这个高度偏差问题 下拉刷新不会收回
tableview的几个参数设置的是 contentinsets 108 0 0 0
frame 0 0 640 1136

**Comment by CoderFenchHU** [comment]
同样的问题。
