### ISSUE TITLE
上拉加载不好

### ISSUE THREAD

**Issue by culmek** [CoderMJLee/MJRefresh#66]
今天更新一下 pod ，发觉有更新：
Installing MJRefresh 1.3.7 (was 0.0.1) 。。。

之前写的代码：
    [mTable addHeaderWithTarget:self action:@selector(headerRereshing)];
    [mTable headerBeginRefreshing];
    [mTable addFooterWithTarget:self action:@selector(footerRereshing)];

改成现在这样：
  [mTable addLegendHeaderWithRefreshingTarget:self refreshingAction:@selector(headerRereshing)];
  [mTable.header beginRefreshing];
  [mTable addLegendFooterWithRefreshingTarget:self refreshingAction:@selector(footerRereshing)];

1、其实是没错的，我现在的项目是没有 HUD 的，也就是第一次进去的时候就刷新了，这样的话上拉的 “点击加载更多”就会显示出来了？（本来的是没有显示的，本来的footer应该是用contentoffset来判断的？）
2、上拉 self.loadMoreButton  = automaticallyRefresh ?  “上拉加载更多” : “点击加载更多”;
这样会不会好点。（而且上拉的位置再下点会好点吧？我还没完全到下面的时候他已经加载了）

其实主要是第一个问题，因为网络加载失败的话，“点击加载更多” 还是会出现的。

**Comment by CoderMJLee** [comment]
你可以自己控制footer的显示或者隐藏哈，比如设置self.tableView.footer.hidden = YES;
