### ISSUE TITLE
v3.18 不支持iOS7

### ISSUE THREAD

**Issue by chinny1009104514** [CoderMJLee/MJRefresh#660]
+[NSBundle(MJRefresh) mj_localizedStringForKey:value:] (NSBundle+MJRefresh.m:46)

**Comment by lsflhuyy** [comment]
我也刚想问:) NSBundle+MJRefresh.m  line46 是ios8以上的方法 @CoderMJLee

**Comment by a5978445** [comment]
同问 ：[language containsString:@"Hans"]

**Comment by a5978445** [comment]
先手动改下吧 。 if([language rangeOfString:@"Hans"].location != NSNotFound)

**Comment by CoderMJLee** [comment]
谢谢提醒，已经搞定这个低级错误
