### ISSUE TITLE
gifheader如何在开始刷新和结束刷新设置不同的帧动画数组

### ISSUE THREAD

**Issue by xiongzenghuidegithub** [CoderMJLee/MJRefresh#661]
- gifheader如何在 `开始刷新` 和 `结束刷新` 设置不同的帧动画数组
- 因为目前看代码只有一个标记为`MJRefreshStateIdle`作为开始与解释时的标记位

那么如何区分开始和结束刷新时设置不同的帧动画数组了？

**Comment by CoderMJLee** [comment]
Sorry，按照MJRefresh设计的本意，刷新结束就是代表恢复开始状态了。如果你希望做一些个性化的定制，可以考虑继承MJRefreshHeader来自定义Header

**Comment by xiongzenghuidegithub** [comment]
重写了gifheader，然后加了点逻辑，代码如下，希望能帮到其他的人:

`#import "FQLPullRefreshAnimateHeader.h"

static const NSTimeInterval kDurateTime = 0.3;

@implementation FQLPullRefreshAnimateHeader

- (void)placeSubviews {
    [super placeSubviews];
    
    self.stateLabel.hidden = YES;
    self.lastUpdatedTimeLabel.hidden = YES;
    self.gifView.contentMode = UIViewContentModeBottom;
}

- (void)prepare
{
    [super prepare];
    
    // 设置普通状态的动画图片
    NSMutableArray *idleImages = [NSMutableArray array];
    UIImage *image = [UIImage imageNamed:@"maotouying_start"];
    [idleImages addObject:image];
    [self setImages:idleImages forState:MJRefreshStateIdle];
    
    NSMutableArray *refreshingImages = [NSMutableArray array];
    for (int i = 0; i< 25; i++) {
        NSString *imageName = [NSString stringWithFormat:@"maotouying_00%zd", i];
        UIImage *image = [UIImage imageNamed:imageName];
        [refreshingImages addObject:image];
    }
    
    // 设置即将刷新状态的动画图片（一松开就会刷新的状态）
//    [self setImages:refreshingImages forState:MJRefreshStatePulling];
    
    // 设置正在刷新状态的动画图片
    [self setImages:refreshingImages forState:MJRefreshStateRefreshing];

}

- (void)beginRefreshing {
    [super beginRefreshing];
    
    NSMutableArray *idleImages = [NSMutableArray array];
    UIImage *image = [UIImage imageNamed:@"maotouying_end"];//睁眼
    [idleImages addObject:image];
    [self setImages:idleImages forState:MJRefreshStateIdle];
    
}

- (void)endRefreshing {
    [super endRefreshing];
    
    NSMutableArray *endImages = [NSMutableArray array];
    UIImage *image = [UIImage imageNamed:@"maotouying_start"];//闭眼
    [endImages addObject:image];
    [self setImages:endImages forState:MJRefreshStateIdle];
    
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(kDurateTime * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSMutableArray *idleImages = [NSMutableArray array];
        UIImage *image = [UIImage imageNamed:@"maotouying_end"];//睁眼
        [idleImages addObject:image];
        [self setImages:idleImages forState:MJRefreshStateIdle];
    });
}

@end
`
