### ISSUE TITLE
上拉加载如何自动回收加载占位？

### ISSUE THREAD

**Issue by tunfo** [CoderMJLee/MJRefresh#662]
上拉加载的时候底部会出现加载动画，如果没有任何数据的话我调_tableView.mj_footer endRefreshing，但是加载动画是消失了，但是底部的空间并没有消失，还是占了一大块。正确调用方法是什么呢

**Comment by CoderMJLee** [comment]
2种做法。
做法1：
```objc
[_tableView.mj_footer endRefreshingWithNoMoreData]; // 希望恢复正常状态的话，调用一下resetNoMoreData
```

做法2：
```objc
_tableView.mj_footer.hidden = YES; // 再次用到时设置hidden = NO
```

**Comment by tunfo** [comment]
这样感觉不是特别友好，希望可以考虑一下添加一个方法，如果没有加载数据的话自然的收缩底部，并且并不影响再次上拉加载。

**Comment by CoderMJLee** [comment]
从全局的角度思考，不建议增加这个功能哈。因为没有加载到数据时，究竟想显示还是隐藏，每个项目的需求和功能都不一定的。究竟想怎么做，开发者自己去控制是最灵活的

**Comment by xdream86** [comment]
_tableView.mj_footer.hidden = YES; // 再次用到时设置hidden = NO
这种方法会导致滑到最后界面会震动一下，因为占位突然消失，tableview迅速移动回补这个占位。

**Comment by chengongwen** [comment]
几个控制器同时加载，有的控制器的head回不去了

**Comment by zjjzmw1** [comment]
我也建议添加一个方法，否则的话，如果用户希望展示一下 footer后，再自动收缩回去的情况下，就不好处理了。您上面说的方案，效果不好。

**Comment by wolfcon** [comment]
这个自定义一下就好了.
