### ISSUE TITLE
相同代码在Release和Debug下效果不同

### ISSUE THREAD

**Issue by wanshanhu79** [CoderMJLee/MJRefresh#663]
[self.homeTV.mj_header endRefreshing];
    [self.homeTV.mj_footer endRefreshing];
    if (self.task.state == NSURLSessionTaskStateRunning || self.task.state == NSURLSessionTaskStateSuspended) {
        [self.task cancel];
    }
##    [self.homeTV.mj_header beginRefreshing];

代码如上，在Debug模式下，头刷新方法会调用，
在Release下，头刷新方法不会调用。

为什么先停止刷新，再开始刷新，是为了在更改筛选信息后可以立即进行头刷新，避免上一次头刷新仍在进行再次更改筛选信息头刷新无法执行。

**Comment by wanshanhu79** [comment]
源代码是这样写的
- (void)endRefreshing
{
    dispatch_async(dispatch_get_main_queue(), ^{
        self.state = MJRefreshStateIdle;
    });
}
---------------------
我将停止刷新代码从：
[self.homeTV.mj_header endRefreshing];
改为
 self.homeTV.mj_header.state = MJRefreshStateIdle;
后。
在Debug和Release模式都可以执行刷新方法

**Comment by wolfcon** [comment]
Duplicate of #1258
