### ISSUE TITLE
iOS7 上autlyout 会crash 

### ISSUE THREAD

**Issue by tuluigi** [CoderMJLee/MJRefresh#664]
Auto Layout still required after executing -layoutSubviews. OCNRefreshHeadView's implementation of -layoutSubviews needs to call super.
(null)

在iOS7 MJRefreshComponent 的 layoutSubviews 中的 [super layoutSubviews] 需要放到最后调用 \，否则会crash .
- (void)layoutSubviews
{
    [super layoutSubviews];
    
    [self placeSubviews];
}

**Comment by CoderMJLee** [comment]
已经调整
