### ISSUE TITLE
校长, MJRefresh最新版支持cocoapods问题

### ISSUE THREAD

**Issue by Initial-C** [CoderMJLee/MJRefresh#670]
校长, 最新3.19什么时候能支持cocoapods啊?

**Comment by CoderMJLee** [comment]
一直都支持哦，你需要pod repo update一下

**Comment by Initial-C** [comment]
谢谢校长! 搞定了~
在 2016年6月28日，22:09，M了个J <notifications@github.com<mailto:notifications@github.com>> 写道：


一直都支持哦，你需要pod repo update一下

**Comment by CoderMJLee** [comment]
不客气
