### ISSUE TITLE
footer 与 UICollectionView performBatchUpdates:completion: 不兼容

### ISSUE THREAD

**Issue by hpsoar** [CoderMJLee/MJRefresh#675]
由于contentSize在completion里，才发生变化，而collectionView的内容中performBatchUpdates里已经变化。会出现footer位置更新不及时，与collectionView的内容重合的情况。

目前想到的方案是加一个状态：MJRefreshStateUpdating，
performBatchUpdates:completion时设为该状态，隐藏footer中的所有内容
completion中设为MJRefreshStateIdle

**Comment by Mark-SS** [comment]
@hpsoar 需要相同的问题，请问下你现在是怎么解决的？我之前使用隐藏 foot view 上面的 label，performBatchUpdates:completion，completion 里面然后显示该 label。

**Comment by hpsoar** [comment]
我只是写demo，后来没管了，感觉只能trick地解决一下了
