### ISSUE TITLE
bug~处于刷新状态中的vc返回时无法注销

### ISSUE THREAD

**Issue by karmaios** [CoderMJLee/MJRefresh#677]
请问怎么移除mjfooter?

**Comment by karmaios** [comment]
像这个刷新库就提供了这么一个方法
![12345](https://cloud.githubusercontent.com/assets/11553684/16539179/895f75b6-406d-11e6-8326-488126f54370.png)

**Comment by CoderMJLee** [comment]
```objc
tableView.mj_footer = nil;
```
