### ISSUE TITLE
刷新后刷新控件无法收回,设置nil会空出那么一块位置.无法进行多次刷新,只有第一次刷新有效.

### ISSUE THREAD

**Issue by 657651096** [CoderMJLee/MJRefresh#678]
![qq20160703-0 2x](https://cloud.githubusercontent.com/assets/18746810/16545477/d1f44f44-415e-11e6-9c26-7b9aada2d665.png)
![qq20160703-1 2x](https://cloud.githubusercontent.com/assets/18746810/16545481/e2aa4ad2-415e-11e6-86f3-82bc59e36c8c.png)

**Comment by CoderMJLee** [comment]
收回刷新控件的正确做法是：
```objc
[tableView.mj_header endRefreshing];
```

**Comment by 657651096** [comment]
多谢MJ哥,新手给你添麻烦了

**Comment by CoderMJLee** [comment]
不客气哦
