### ISSUE TITLE
cocoa pod can not search the MJRefresh 

### ISSUE THREAD

**Issue by Bintong** [CoderMJLee/MJRefresh#68]
![image](https://cloud.githubusercontent.com/assets/3366351/6656824/8d4acc42-cb71-11e4-8683-6baf8f9406ef.png)

**Comment by Bintong** [comment]
but pod the address is ok may be is not new one
![image](https://cloud.githubusercontent.com/assets/3366351/6656839/d7c7d922-cb71-11e4-83eb-05d83f199747.png)

**Comment by CoderMJLee** [comment]
Please run 'pod repo update' on your terminal.3Q

**Comment by Bintong** [comment]
ok,the issues is fixed . thanks
