### ISSUE TITLE
国际化版本bug

### ISSUE THREAD

**Issue by YGLau** [CoderMJLee/MJRefresh#680]
明杰老师，我在使用你的框架时发现了一个bug，你的这个框架支持三种语言，简体中文、繁体中文和英文，但是iPhone手机中繁体中文又分为繁体中文、台湾繁体中文、香港繁体中文三种，也就是说，当用户切换为台湾或香港繁体中文后下拉刷新空间将显示源码,在MJRefreshComponent类中；我做了修改，你看
下我的图片。

![21 pic](https://cloud.githubusercontent.com/assets/17176518/16557560/3bc4d588-4213-11e6-88d5-885a6e9ff9e0.jpg)

**Comment by CoderMJLee** [comment]
最新版已经不是这样判断了哈，你看看最新版能否满足你的需求

**Comment by YGLau** [comment]
谢谢明杰老师~
