### ISSUE TITLE
编译时报 Expected a type 及自我解决

### ISSUE THREAD

**Issue by kingcos** [CoderMJLee/MJRefresh#682]
@*问题：*
`MJRefresh/NSBundle+MJRefresh.h` 文件
第 13 行报 `Parse Issue: Expected a type`

*解决：*
加入 UIKit 头文件：`#import <UIKit/UIKit.h>`
之后编译且运行成功，但不确定是否正确，或是 Beta 版的 Bug

*Info:*
Xcode 8 beta
Swift 3.0

> 第一次提 Issue，如有错误，还望斧正，谢谢。

**Comment by CoderMJLee** [comment]
谢谢你的提醒，确实是应该这么做，因为我的Demo里有PCH，所以我不小心忽略了这个问题。已经在3.1.10中修复
