### ISSUE TITLE
给collectionview加MJRefreshAutoNormalFooter的时候回改变collectionview的内边距

### ISSUE THREAD

**Issue by wlerl** [CoderMJLee/MJRefresh#688]
```
    如题，就是我在给一个collectionview加了一个mj的上拉刷新，下拉刷新我用的是系统的，
```

如果只保留系统的刷新，发现collectionview的内边距底部并未发生变化，但是加了mj的下拉刷新后，collectionview的内边距的底部就发生了变化，就是我设置collectionview的内边距的底部为0，顶为44，这个时候显示的底部为44，设置顶为44，底为49的时候，实际显示collectionview的内边距底部是44+49（用reval查看的），主要想做的是在上拉刷新的时候，下面的loading可以显示出来，但是单双切换，我就改变collectionview的内边距（这个时候主要改变的是左右边距），但是Loading有的显示在屏幕下边，有的时候是可以在底部看到的，基本就是设置底为0，然后重启，就可以刚刚看到，这个时候内边距的底为44（也就是顶），切换的时候就不对了。不是都刚好出现 在我要的底部，其实其中还想问的就是为什么系统的refresh不会改变collectionview的内边距，而mj的改变了，大神求指教。真心求指教。

**Comment by wolfcon** [comment]
因为 MJRefresh 是依托于 insets 去实现功能的, 实现方式不同
