### ISSUE TITLE
上提加载更多时，到最后一页时提示一下没有更多数据了，我如下所写，但是提到最后一页时候并不显示没有更多数据，而是显示   点击加载更多，怎么解决

### ISSUE THREAD

**Issue by shanyulaile** [CoderMJLee/MJRefresh#689]
上提加载更多时，到最后一页时提示一下没有更多数据了，我如下所写，但是提到最后一页时候并不显示没有更多数据，而是显示   点击加载更多，怎么解决
if(最后一页数据){
[weakself.tableView.footer setTitle:@"没有更多数据" forState:MJRefreshFooterStateNoMoreData];
                [weakself.tableView.footer noticeNoMoreData];
}

**Comment by shanyulaile** [comment]
当只有一页数据时显示，多页情况下到最后一页就不显示

**Comment by yanqizhao** [comment]
[weakself.tableView.footer setTitle:@"没有更多数据" forState:MJRefreshFooterStateNoMoreData];
这一句放在prepare方法里

**Comment by shanyulaile** [comment]
已经解决，我直接使用这个框架里的方法就出现了，然而封装之后使用就不会出现，可能是我封装的错误，谢谢
