### ISSUE TITLE
设置contentinsert的时候有问题

### ISSUE THREAD

**Issue by 276523923** [CoderMJLee/MJRefresh#690]
使用 MJRefreshHeader
如果contentinsert设置比如 {12,12,12,12,};
 [self.scrollView setContentOffset:CGPointMake(0, -top) animated:NO];
这句话会使界面出错，请修改。
 // 设置滚动位置
CGPoint offset = self.scrollView.contentOffset;
 offset.y = -top;
[self.scrollView setContentOffset:offset animated:NO];

 else if (state == MJRefreshStateRefreshing) {
         dispatch_async(dispatch_get_main_queue(), ^{
            [UIView animateWithDuration:MJRefreshFastAnimationDuration animations:^{
                CGFloat top = self.scrollViewOriginalInset.top + self.mj_h;
                // 增加滚动区域top
                self.scrollView.mj_insetT = top;
                // 设置滚动位置
                [self.scrollView setContentOffset:CGPointMake(0, -top) animated:NO];
            } completion:^(BOOL finished) {
                [self executeRefreshingCallback];
            }];
         });

**Comment by 276523923** [comment]
还有   
 self.mj_y = - self.mj_h - self.ignoredScrollViewContentInsetTop;
应该是
self.mj_y = - self.mj_h - self.ignoredScrollViewContentInsetTop - self.scrollViewOriginalInset.top;

**Comment by wolfcon** [comment]
已经修复
