### ISSUE TITLE
国际化崩溃

### ISSUE THREAD

**Issue by jiangmingz** [CoderMJLee/MJRefresh#691]
// 获得设备的语言
        NSString *language = [NSLocale preferredLanguages].firstObject;
        // 如果是iOS9以上，截取前面的语言标识
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
            language = [language substringToIndex:range.location];
        }
当返回值为 en 的时候就崩溃了

**Comment by CoderMJLee** [comment]
试试更新到最新版，上个月已经解决一些问题了哈
