### ISSUE TITLE
NSBundle (MJRefresh)没有#import<UIKit/UIKit.h>报错

### ISSUE THREAD

**Issue by diaoshihao** [CoderMJLee/MJRefresh#693]
难道是大家都发现这个错了顺手补上去，觉得这个不是问题？好吧，我是菜鸟，花了几分钟才知道是因为这个报错

**Comment by cwenqing** [comment]
我这边报 了个 linker command failed with exit code 1  的错误，连找都到不到那里出了问题

**Comment by diaoshihao** [comment]
本来我是用cocoaPods下载MJRefresh的，但是使用normalHeader会报错：
Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSTaggedPointerString substringToIndex:]: Index 9223372036854775807 out of bounds; string length
随后我从GitHub下载导入项目，发现如果不导入UIKit会出现如下错误：

现在使用正常，没有报错，也没有你那边报 linker command failed with exit code 1的错误

2016年7月21日 下午12:25，C_wenqing <notifications@github.com> 写道：

我这边报 了个 linker command failed with exit code 1 的错误，连找都到不到那里出了问题
