### ISSUE TITLE
您好，MJ哥，现在的版本怎么才能使得footer不要显示出来，上拉才显示出来，刷新完了就隐藏呀（现在“点击加载更多总是显示出来”）？就像以前的版本那样

### ISSUE THREAD

**Issue by xiayiyong88** [CoderMJLee/MJRefresh#70]

**Comment by heistings** [comment]
正常情况下，每次加载的数据应该超过一屏，点击加载应该被顶到屏幕外面才对。

**Comment by heistings** [comment]
如果你不想让用户看到点击加载更多的话，还有一个方案就是把 Idle 和 Refreshing 的 title 设置成相同的：
```objective-c
    [self.tableView.footer setTitle:@"Loading more ..." forState:MJRefreshFooterStateIdle];
    [self.tableView.footer setTitle:@"Loading more ..." forState:MJRefreshFooterStateRefreshing];

```

**Comment by xiayiyong88** [comment]
就是有些特殊情况，UIScrollView高度没有整屏，现在效果要求不需要显示文字 ，上拉一段才显示出菊花，刷新完了隐藏菊花，以前版本就是这么做的，现在只能用以前的版本了。。。，要是现在版本也有老版本这个效果就好了，杰哥能完善下这个功能嘛？

**Comment by heistings** [comment]
@xiayiyong88 哦，你是这个需求啊，这个功能是支持的：

```objective-c
    [self.tableView.footer setTitle:@"" forState:MJRefreshFooterStateIdle];
```

**Comment by heistings** [comment]
@xiayiyong88 你的问题解决了吗？

**Comment by CoderMJLee** [comment]
可以参考MJCollectionViewController.m中的示例。其实就是self.tableView.footer.hidden = YES;然后以后在hidden = NO;显示出来

**Comment by xiayiyong88** [comment]
@heistings 试过了，还是没有解决问题，这么做只是看不到文字，但是现在稍微往上滑动UIScrollView就开始loading..，而且点击UIScrollView最下面也会loading..，我需要往上滑动UIScrollView等到footer完全显示出来才开始loading...   不知道我表达清楚没有？就是老版本的那种效果

**Comment by heistings** [comment]
@xiayiyong88 

```objective-c
    // 当上拉刷新控件出现50%时（出现一半），就会自动刷新。这个值默认是1.0（也就是上拉刷新100%出现时，才会自动刷新）
//    self.tableView.footer.appearencePercentTriggerAutoRefresh = 0.5;
    
    // 隐藏状态
    self.tableView.footer.stateHidden = YES;
 
    [self.tableView.footer setTitle:@"" forState:MJRefreshFooterStateIdle];

    // 此时self.tableView.footer == self.tableView.gifFooter
    
    // 由于动画图片是黑色的，所以故意设置tableView底色为黑色
    self.tableView.backgroundColor = [UIColor blackColor];
```

**Comment by heistings** [comment]
@xiayiyong88 按道理不拉到底部是不会开始加载的。

**Comment by xiayiyong88** [comment]
@heistings  我这个  UISCcrollView 高度只有手机高度一半，而且 contentSize.height=UISCcrollView.height  也就只有一页数据，上拉开始时慢慢显示箭头，上拉到footer完全显示出来才开始l显示菊花，完了菊花菊花消失。。。

**Comment by CoderMJLee** [comment]
Sorry啊，以前那个功能已经彻底删掉了，现在的上拉加载已经改方案了，跟微信、QQ控件、微博、网易新闻都一样的，这才是主流方案
