### ISSUE TITLE
提交到Appstroe后崩溃了

### ISSUE THREAD

**Issue by roshanman** [CoderMJLee/MJRefresh#702]
使用的是V3.1.0

崩溃log

Last Exception Backtrace:
0   CoreFoundation                  0x180d7edb0 __exceptionPreprocess + 124
1   libobjc.A.dylib                 0x1803e3f80 objc_exception_throw + 56
2   CoreFoundation                  0x180d7ecf8 +[NSException raise:format:] + 120
3   Foundation                      0x18167cb28 -[NSString substringToIndex:] + 128
4   MJRefresh                       0x100b8aae0 -[MJRefreshComponent localizedStringForKey:withDefault:](MJRefreshComponent.m:150)
5   MJRefresh                       0x100b8e27c -[MJRefreshStateHeader setLastUpdatedTimeKey:](MJRefreshStateHeader.m:107)
6   MJRefresh                       0x100b8c518 -[MJRefreshHeader prepare](MJRefreshHeader.m:37)
7   MJRefresh                       0x100b8e504 -[MJRefreshStateHeader prepare](MJRefreshStateHeader.m:115)
8   MJRefresh                       0x100b8d258 -[MJRefreshNormalHeader prepare](MJRefreshNormalHeader.m:52)
9   MJRefresh                       0x100b8a38c -[MJRefreshComponent initWithFrame:](MJRefreshComponent.m:26)
10  MJRefresh                       0x100b8c424 +[MJRefreshHeader headerWithRefreshingBlock:](MJRefreshHeader.m:20)

**Comment by CoderMJLee** [comment]
现在最新是3.1.10，可以试试哈

**Comment by qingfeng** [comment]
MJRefresh 3.1.12 同遇到此问题

**Comment by xiaonan0527** [comment]
这应该是一个bug，当模拟器是英文环境时也会发生，把语言环境还成中文久好了
