### ISSUE TITLE
继承MJRefreshBackNormalFooter的问题

### ISSUE THREAD

**Issue by TongCong** [CoderMJLee/MJRefresh#707]
杰哥，我自定义footer，继承MJRefreshBackNormalFooter。
然后设置给这个MJRefreshStateNoMoreData状态设置提醒消息“没有数据了”
但是我在控制器判断返回数据没有的时候，调用了[weakSelf.tableView.mj_footer endRefreshingWithNoMoreData];
并没有用，“没有数据了”这个提示显示不出来。
怎么解决啊

**Comment by CoderMJLee** [comment]
怎么设置的提醒消息？代码看看哈

**Comment by TongCong** [comment]
`- (void)prepare {
    [super prepare];
    
    [self setTitle:@"上拉刷新数据" forState:MJRefreshStateIdle];
    [self setTitle:@"释放立即刷新" forState:MJRefreshStatePulling];
    [self setTitle:@"正在刷新..." forState:MJRefreshStateRefreshing];
    [self setTitle:@"没有数据了" forState:MJRefreshStateNoMoreData];`
额，解决了。。。
`            if (moreSpeBankCards.count == 0) {
                
                
                YTLLog(@"没有数据了");
                // 告诉用户没有数据了
                [weakSelf.tableView.mj_footer endRefreshingWithNoMoreData];
            }else {
            
                // 结束刷新
                [weakSelf.tableView.mj_footer endRefreshing];
            }`
我没有把endRefreshing 这个方法放到else里，导致前面还没显示出来，就被后面的一句代码给结束了。。
但是我现在有新的问题了。。。一般下拉刷新，成功的时候要显示“刷新成功”，但是状态总共就那几种，我应该调mj_header的什么方法让或者设置mj_header的什么状态啊
