### ISSUE TITLE
Swift 不能使用

### ISSUE THREAD

**Issue by itjhDev** [CoderMJLee/MJRefresh#708]
之前是可以了, pod update以后Bridging-Header.h文件引入#import <MJRefresh/MJRefresh.h> 提示找不到！

**Comment by williambao** [comment]
这种方式应该可以import
```#import <MJRefresh/MJRefresh.h>```

**Comment by zzycami** [comment]
最新的pod的话是动态联机库， 你可以考虑import，另外希望作者出swift版本的

**Comment by itjhDev** [comment]
应该是最新版pod的问题
