### ISSUE TITLE
禁止自动加载

### ISSUE THREAD

**Issue by heistings** [CoderMJLee/MJRefresh#71]
我不确定这是否是 bug，`self.tableView.footer.automaticallyRefresh = NO;` 设置后，用户是否应该只能通过点击加载？example16 中用户仍然可以通过上拉加载新的数据。

**Comment by CoderMJLee** [comment]
不是BUG，自动加载的意思是：滚动底部的时候，自动进入刷新状态。非自动加载呢：滚动底部了，不会进入刷新状态，需要点击或者用力往上拽才会进入刷新状态

**Comment by heistings** [comment]
哦，是否需要增加一种功能，就是用户只能通过点击才能加载？比如百度贴吧浏览某个贴吧的页面，自动加载几次之后就会变成 `点击加载第二页`

**Comment by CoderMJLee** [comment]
我觉得不需要哈，由开发者自己去控制automaticallyRefresh属性吧

**Comment by heistings** [comment]
好。
