### ISSUE TITLE
contentInset如果根据请求下来的数据动态改变，刷新控件显示就会有问题

### ISSUE THREAD

**Issue by swsdyg** [CoderMJLee/MJRefresh#711]
您好，我在使用中的需求就是每次刷新之后，我会根据请求下来的内容动态的调整contentInset的值，但我发现一般我修改了contentInset的值之后，在mj_header收起动画结束之后，就又会把contentInset的值修改成上次保存的值，这样就会导致要么刷新控件在外面收不回去，要么就是收的过了导致tableview的部分内容被导航栏挡住看不到

**Comment by wolfcon** [comment]
contentInset 不要修改, 刷新控件是依托这个在工作的.
