### ISSUE TITLE
部分没有使用到MJRefresh的Tableview会崩溃

### ISSUE THREAD

**Issue by wanglang** [CoderMJLee/MJRefresh#713]
您好，我在工程中部分没有使用的MJRefresh，也没有包含任何相关头文件的tableview，执行reloaddata， 程序会崩溃在 mj_reloadData ，调试的时候，po self 显示对象为空

**Comment by githubzxq** [comment]
我也是。

**Comment by lqcjdx** [comment]
@wanglang @githubzxq 请问下你们，这个问题解决了么？我这里也会时不时奔溃一下，查看日志是在mj_reloadData方法里面。
