### ISSUE TITLE
MJ哥  在5s上面    识别语言   会崩溃   越界    求解决

### ISSUE THREAD

**Issue by zhanglizhong1002** [CoderMJLee/MJRefresh#714]
// 获得设备的语言
        NSString *language = [NSLocale preferredLanguages].firstObject;
        // 如果是iOS9以上，截取前面的语言标识
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];

```
        //laozhang报错地带
```

//            language = [language substringToIndex:range.location];

```
    }
```

**Comment by Herohahaha** [comment]
同问，我也是在模拟器5S上崩溃到这个地方了，可有什么解决的办法？

**Comment by XQ0820** [comment]
the same to me.
我在模拟器上跑的时候也是崩溃,程序已经跑不起来了..
求解决办法

**Comment by LeeJoyce** [comment]
我也是这个位置崩溃。

**Comment by XQ0820** [comment]
我把模拟器的语言设置成中文后,不崩溃了
