### ISSUE TITLE
使用beginRefreshing时，不能endRefreshing 

### ISSUE THREAD

**Issue by asd8855** [CoderMJLee/MJRefresh#718]

**Comment by asd8855** [comment]
[self.tableView.mj_header beginRefreshing];  有这句代码以后刷新之后不能停止,通过追踪 运行到了 endRefreshing但会出现zhe这种情况，明杰大神，求助
<img width="330" alt="2016-08-05 4 30 20" src="https://cloud.githubusercontent.com/assets/20153584/17430977/f6446124-5b29-11e6-889d-630f5603dfb8.png">

**Comment by asd8855** [comment]
已经解决

**Comment by vincent-cihan** [comment]
@asd8855 哥们，求解决方法，我也出现了

**Comment by zsybupt** [comment]
同问

**Comment by QDDLoveIT** [comment]
同问

**Comment by hackjie** [comment]
同问

**Comment by Demon2112** [comment]
兄弟这个问题  当初你是怎么解决的
