### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by heistings** [CoderMJLee/MJRefresh#72]
@CoderMJLee 按照我们之前讨论的结果，我依照新的接口重写了代码，你可以看一下我的 dev_2.0 分支。如果没有问题，我们就起一个 2.0 分支继续迭代吧，我把代码 pull request 到 2.0分支上。我觉得新的接口甚至能简化到这样的程度：

```objective-c
@interface UIScrollView (MJRefresh)

@property (nonatomic, strong) MJRefreshHeader *header;
@property (nonatomic, strong) MJRefreshFooter *footer;

@end

```

**Comment by CoderMJLee** [comment]
很好，让开发者面向header和footer开发

**Comment by heistings** [comment]
我现在看不到 CoderMJLee/MJRefresh 的 2.0 分支，你已经建了吗？

**Comment by CoderMJLee** [comment]
还没有，今晚建

**Comment by CoderMJLee** [comment]
2.0分支已经创建完毕

**Comment by heistings** [comment]
👍

**Comment by heistings** [comment]
@CoderMJLee 你看看都有哪些地方需要修改？我们现在 2.0 分支上迭代出一个比较完美的版本吧？等差不多了才往 master 上合并。

**Comment by CoderMJLee** [comment]
没问题，谢谢你的用心。但是我这几天比较忙哈，我会尽力抽出时间一起搞

**Comment by heistings** [comment]
喔喔，你已经尽力了。
