### ISSUE TITLE
由于iOS9上面语言判断这块导致在个别设备上崩溃问题，导致我们的应用2次被拒，发现后展示细节如下

### ISSUE THREAD

**Issue by Asrake** [CoderMJLee/MJRefresh#727]
- (NSString *)localizedStringForKey:(NSString *)key withDefault:(NSString *)defaultString
  {
  static NSBundle *bundle = nil;
  if (bundle == nil) {
      // 获得设备的语言
      NSString *language = [NSLocale preferredLanguages].firstObject;
      // 如果是iOS9以上，截取前面的语言标识
      if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
          NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];

//起 起止之间的代码是我们上线被拒之后分析后添加的，不是完美的解决方案，如果语言标识不含“-”则将语言改为“”这样会导致默认语言为中文，不是最好的解决方案，希望MJ能修改一下这一块
            if (range.location != NSNotFound) {
                language = [language substringToIndex:range.location];
            }else{
                language = @"";
            }
//止

```
    }

    if (language.length == 0) {
        language = @"zh-Hans";
    }

    // 先从MJRefresh.bundle中查找资源
    NSBundle *refreshBundle = [NSBundle mj_refreshBundle];
    if ([refreshBundle.localizations containsObject:language]) {
        bundle = [NSBundle bundleWithPath:[refreshBundle pathForResource:language ofType:@"lproj"]];
    }
}
defaultString = [bundle localizedStringForKey:key value:defaultString table:nil];
return [[NSBundle mainBundle] localizedStringForKey:key value:defaultString table:nil];
```

}

**Comment by Asrake** [comment]
刚刚想了一下
//
else{
language = @"";
}
//这段代码可以不要，因为如果按照"-"去找没找到"-"的话证明当前设备的偏好语言没有“zh-Hans”这样的分支

**Comment by xiky** [comment]
我今天也遇到这个问题. 打全局断点之后也崩在这个地方. 目前也加了这个判断. 撤销审核了

**Comment by billychen2014** [comment]
我强制的把language = @"zh-Hans";写死了，就只支持中文了。。。
