### ISSUE TITLE
-[UITableView setMj_footer]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by rabewu** [CoderMJLee/MJRefresh#729]
```
self.tableView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        // doSomething...
    }];
```

以上代码会崩溃，-[UITableView setMj_footer]: unrecognized selector sent to instance

改成
self.tableView.footer不会崩溃，只会警告，比较蛋疼，使用的应该是最新版，看了其他issue也有类似这个问题，请问解决了没有？

**Comment by Liuhuan247** [comment]
我也遇到了这个问题。在同事的电脑上就不会，就在我的电脑上崩，pod 版本都是1.0.1
