### ISSUE TITLE
MJRefreshHeader.m - (void)endRefreshing   不能用异步

### ISSUE THREAD

**Issue by guoyalun** [CoderMJLee/MJRefresh#734]
- (void)endRefreshing
  {
  dispatch_async(dispatch_get_main_queue(), ^{
      self.state = MJRefreshStateIdle;
  });
  }

我们在使用过程中，发现这里这样写会有问题，比如快速切换tab的时候，如果MJRefreshHeader 是共用的， 可能是先endRefreshing  再beginRefreshing，如果endRefreshing使用的dispatch_async 会导致执行顺序不一致，导致下拉刷新的控件不能正常收回。 直接修改成下面这样就OK了。 很是奇怪。
- (void)endRefreshing
  {
      self.state = MJRefreshStateIdle;
  }

**Comment by Thememont** [comment]
`[self.header endRefreshing];`
`[self.header beginRefreshing];`

这样调用的话      self.state = MJRefreshStateIdle   会在    self.state = MJRefreshStateRefreshing  后面执行，导致页面下拉瞬间就被收回

**Comment by ieliwb** [comment]
我也遇到这种问题了，新版的有问题，老版本的是好的，怎么解决

**Comment by ieliwb** [comment]
作者是不是放弃这个库了?

**Comment by guoyalun** [comment]
我稍微修改了一下。凑合能用了

**Comment by wolfcon** [comment]
#1258
