### ISSUE TITLE
你好，发现一个Bug

### ISSUE THREAD

**Issue by Shulin-Zhang** [CoderMJLee/MJRefresh#736]
header下拉刷新的过程中，**_刚刚变成可刷新状态_**，即**_箭头刚刚朝上_**，松手时会突然向上顿一下。100%都会重现

**Comment by kyleduo** [comment]
我也发现了这个问题。跟踪代码发现，是`MJRefreshComponent`这个类中的`-(void)setState:`方法里面调用`[self setNeedsLayout]`方法导致的，但是并没有发现上移的逻辑具体是什么。

**Comment by kyleduo** [comment]
遇到同样的问题，在MJRefreshHeader的setState中跟踪_ScrollView的offsetY，发现在执行完setState方法之后，执行回滚到正在刷新位置的代码之前，offsetY的位置发生了偏移，怎么引起的还不清楚。
