### ISSUE TITLE
APP crashed while using ipv6 network

### ISSUE THREAD

**Issue by billychen2014** [CoderMJLee/MJRefresh#739]
Hello,
在MJRefreshComponent.m文件中，
第150行， language = [language substringToIndex:range.location]; 最新的9.3.5系统会crash,statck:
2   CoreFoundation                  0x180bf2cf8 +[NSException raise:format:] + 120
3   Foundation                      0x1814f0b28 -[NSString substringToIndex:] + 128
4   XXXX                    0x10020df78 -[MJRefreshComponent localizedStringForKey:withDefault:](MJRefreshComponent.m:150)
5   XXXX                    0x100211714 -[MJRefreshStateHeader setLastUpdatedTimeKey:](MJRefreshStateHeader.m:107)
6   XXXX                    0x10020f9b0 -[MJRefreshHeader prepare](MJRefreshHeader.m:37)
7   XXXX                    0x10021199c -[MJRefreshStateHeader prepare](MJRefreshStateHeader.m:115)
8   XXXX                    0x1002106f0 -[MJRefreshNormalHeader prepare](MJRefreshNormalHeader.m:52)
9   XXXX                    0x10020d824 -[MJRefreshComponent initWithFrame:](MJRefreshComponent.m:26)
10  XXXX                    0x10020f930 +[MJRefreshHeader headerWithRefreshingTarget:refreshingAction:]

**Comment by qingfeng** [comment]
同遇到

**Comment by 12207480** [comment]
同遇到 ios10

**Comment by qingfeng** [comment]
后来升级到最新版本MJRefresh之后好了

**Comment by billychen2014** [comment]
我是强制把语言写在zh-cn了，没用取的变量。
