### ISSUE TITLE
MJ哥，能不能实现，没有上拉到低，自动加载更多了？

### ISSUE THREAD

**Issue by iHTCboy** [CoderMJLee/MJRefresh#74]

**Comment by CoderMJLee** [comment]
// 当上拉刷新控件出现50%时（出现一半），就会自动刷新。这个值默认是1.0（也就是上拉刷新100%出现时，才会自动刷新）
self.tableView.footer.appearencePercentTriggerAutoRefresh = 0.5;
// 如果赋值为0，那就只要出现一点点，就自动刷新

**Comment by iHTCboy** [comment]
好的，谢谢MJ哥！
