### ISSUE TITLE
杰哥：三种语言的切换问题

### ISSUE THREAD

**Issue by UncleShen** [CoderMJLee/MJRefresh#749]
在不切换设备系统语言的情况下，切换APP内部语言（APP内部做三种语言切换），如何设置您的这个刷新提示文字和APP内部的当前语言一致？

**Comment by fzq2016** [comment]
一样想知道，MJRefresh怎么不跟随系统语言改变，而是根据项目内语言改变呢？

**Comment by UncleShen** [comment]
//转圈+文字刷新
            MJRefreshNormalHeader *header = [MJRefreshNormalHeader headerWithRefreshingTarget:self refreshingAction:@selector(refreshLoadDataToVodView)];
            [header setTitle:[[StringUtil sharedInstance] getString:@"idleText"] forState:MJRefreshStateIdle];
            [header setTitle:[[StringUtil sharedInstance] getString:@"pullingText"] forState:MJRefreshStatePulling];
            [header setTitle:[[StringUtil sharedInstance] getString:@"refreshingText"] forState:MJRefreshStateRefreshing];
这些相关的语言文字自定义，有几种语言就建几个语言包。（自定义，换了语言会换语言包，取对应语言包中的对应文字）
