### ISSUE TITLE
使用过程中 快速从这个界面pop回去的时候程序崩溃

### ISSUE THREAD

**Issue by ianisme** [CoderMJLee/MJRefresh#75]
崩溃在 [self deallocSwizzle];
![2015-03-17 1 40 41](https://cloud.githubusercontent.com/assets/6585635/6681984/41775cf0-ccab-11e4-91bb-e1115775fcbf.png)

**Comment by CoderMJLee** [comment]
Sorry啊，我一直没有遇到这样的问题，能发个有这个问题的Demp么？

**Comment by ianisme** [comment]
不好意思，是我代码写的有误。结束刷新方法调用多次导致的崩溃，不好意思

**Comment by CoderMJLee** [comment]
没事，解决问题就好，恭喜你
