### ISSUE TITLE
左拉刷新右拉加载更多的UICollectionView

### ISSUE THREAD

**Issue by yaooort** [CoderMJLee/MJRefresh#750]
请问如何快速实现左拉刷新，右拉加载更多.产品需求实在没办法

**Comment by YueLiXing** [comment]
+1

**Comment by CrazyGitter** [comment]
https://github.com/CrazyGitter/EhanCollectionView  这个可以，左右视图可以根据contentoffset自定义  @cloudoort @YueLiXing
