### ISSUE TITLE
iOS10相关问题

### ISSUE THREAD

**Issue by Deabel** [CoderMJLee/MJRefresh#751]
李明杰老师：今早升级了Xcode8 ,出现以下问题
// 如果是iOS9以上，截取前面的语言标识
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
            if (range.length) {
                **language = [language substringToIndex:range.location];**
            }
        }
错误信息：(NSRange) range = location=9223372036854775807, length=0

**Comment by songhailiang** [comment]
升级到最新版再试试吧

**Comment by usaokok** [comment]
我也出现了这个问题,必须设置模拟器的语言才行,就是模拟器第一次启动未设置语言(默认语言的情况下).
