### ISSUE TITLE
MJ老师，你的框架在iOS10下报错误啦！！

### ISSUE THREAD

**Issue by liyang123** [CoderMJLee/MJRefresh#752]
![snip20160914_5](https://cloud.githubusercontent.com/assets/14366049/18504179/9a0052f4-7a93-11e6-80a3-b1eddb150983.png)
![snip20160914_6](https://cloud.githubusercontent.com/assets/14366049/18504180/9bd35f5e-7a93-11e6-8921-3f3412b35796.png)
快回来更新下吧

**Comment by wodegitzhanghao** [comment]
刚想提个issues  过来顶下

**Comment by gsj602** [comment]
那就顶顶吧

**Comment by alenQingshan** [comment]
if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0&&[UIDevice currentDevice].systemVersion.floatValue < 10.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
            language = [language substringToIndex:range.location];
        }
        if ([UIDevice currentDevice].systemVersion.floatValue >= 10.0) {
            language = [language substringToIndex:2];
        }
