### ISSUE TITLE
iOS10,加载时报错

### ISSUE THREAD

**Issue by alenQingshan** [CoderMJLee/MJRefresh#755]
MJRefreshComponent.m中错误断点在第150行
language = [language substringToIndex:range.location];

**Comment by y1024** [comment]
因为 iOS9以后获取的云烟返回的数组不一样了。。这个还是交给mj改吧

**Comment by alenQingshan** [comment]
不用mj,自己也能改
if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0&&[UIDevice currentDevice].systemVersion.floatValue < 10.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
            language = [language substringToIndex:range.location];
        }
        if ([UIDevice currentDevice].systemVersion.floatValue >= 10.0) {
            language = [language substringToIndex:2];
        }
