### ISSUE TITLE
MJRefreshComponent.m文件的150行的NSRange没做NSNotFound判断

### ISSUE THREAD

**Issue by iCoobin92** [CoderMJLee/MJRefresh#761]
// 如果是iOS9以上，截取前面的语言标识
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
           //应该加上 NSNotFound。当language为“en”时下面的获取子串报错
            if (range.location != NSNotFound) {
                language = [language substringToIndex:range.location];
            }
        }

**Comment by dengsss** [comment]
之前用xcode7一直好好的，结果今天更新xcode8后，就遇到了和你一样的问题，加了判断之后果然就好了。谢谢分享。

**Comment by ReasonYoung** [comment]
请问这个判断应该加在哪里呢？
