### ISSUE TITLE
在下拉刷新时 jin，先endRefreshing，再beginRefreshing，header 会始终显示而不回弹

### ISSUE THREAD

**Issue by mymaple** [CoderMJLee/MJRefresh#765]
再业务需求中遇到，有两个 tableview同在一个控制器中，且左边 tableview 控制右边
为避免右边tableview的刷新状态由上次数据控制做出就先endRefreshing，再beginRefreshing，
header 会始终显示而不回弹

于是做出下列测试案例，如果连续点击 test 按钮，整个 tableview还出现连续下移问题，

希望 MJ 老师帮忙看看是什么问题

```
-(void)viewDidLoad {
    [super viewDidLoad];
    self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc]initWithTitle:@"test" style:UIBarButtonItemStylePlain target:self action:@selector(leftClick:)];
    self.tableview.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [self.tableview.mj_header endRefreshing];
    }];

}

- (void)leftClick:(UIButton*)ban {
    DebugLog(@"");
    [self.tableview.mj_header endRefreshing];
    [self.tableview.mj_header beginRefreshing];
}

```

**Comment by mymaple** [comment]
初始化的时候执行了一次
[self.tableview.mj_header beginRefreshing];
问题好像就得以解决
o(╯□╰)o，是不是这样的

**Comment by fero2004** [comment]
@mymaple 
如果先endRefreshing再beginRefreshing的话 界面会有问题的
我是这样解决的
修改MJRefreshComponent.m里的beginRefreshing函数 
`- (void)beginRefreshing
{
    dispatch_async(dispatch_get_main_queue(), ^{
        [UIView animateWithDuration:MJRefreshFastAnimationDuration animations:^{
            self.alpha = 1.0;
        }];
        self.pullingPercent = 1.0;
        // 只要正在刷新，就完全显示
        if (self.window) {
            self.state = MJRefreshStateRefreshing;
        } else {
            // 预发当前正在刷新中时调用本方法使得header insert回置失败
            if (self.state != MJRefreshStateRefreshing) {
                self.state = MJRefreshStateWillRefresh;
                // 刷新(预防从另一个控制器回到这个控制器的情况，回来要重新刷新一下)
                [self setNeedsDisplay];
            }
        }
    });
}
`
