### ISSUE TITLE
提一个产品设计问题,关于下拉刷新时间

### ISSUE THREAD

**Issue by cocos543** [CoderMJLee/MJRefresh#773]
您好,我从源码里看到下拉刷新时间并没有对外开放修改功能.
/*\* 上一次下拉刷新成功的时间 */
@property (strong, nonatomic, readonly) NSDate *lastUpdatedTime;

这个设计总感觉不妥当.例如你一个引入MJ的界面,一般进入这个界面的时候都会刷新一下数据,这个时候MJ的下拉刷新时间其实是指的是用户下拉动作的时间.这就可能造成一个问题,假如用户是昨天下拉的,但是今天他打开这个界面数据也是最新的了.但是下拉的时候组件还是显示最后更新是昨天,这应该不适当了.

提一个建议就是开放这个时间的设置,外部设置这个属性的同时,把他保存在本地里.
或者您有其他更好的建议或者想法呢?

**Comment by DriftingWind** [comment]
我下载的最新版本我的可以用，我用的3.1.12
