### ISSUE TITLE
关于iOS10 MJRefresh Crash 问题

### ISSUE THREAD

**Issue by Q14** [CoderMJLee/MJRefresh#774]
- (NSString *)localizedStringForKey:(NSString *)key withDefault:(NSString *)defaultString
  {
  static NSBundle *bundle = nil;
  if (bundle == nil) {
      // 获得设备的语言
      NSString *language = [NSLocale preferredLanguages].firstObject;
      // 如果是iOS9以上，截取前面的语言标识
      if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
          NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
          language = [language substringToIndex:range.location];
      }
  
  ```
  if (language.length == 0) {
      language = @"zh-Hans";
  }
  
  // 先从MJRefresh.bundle中查找资源
  NSBundle *refreshBundle = [NSBundle mj_refreshBundle];
  if ([refreshBundle.localizations containsObject:language]) {
      bundle = [NSBundle bundleWithPath:[refreshBundle pathForResource:language ofType:@"lproj"]];
  }
  ```
  
  }
  defaultString = [bundle localizedStringForKey:key value:defaultString table:nil];
  return [[NSBundle mainBundle] localizedStringForKey:key value:defaultString table:nil];
  }

走到这回crash

**Comment by Q14** [comment]
感觉像是版本判断的问题 iOS10 同样不需要截取

**Comment by xieyh** [comment]
确实有问题我暂时注释掉了，希望下个版本更新

**Comment by iChenwin** [comment]
我也碰到这bug，英文版iOS10就会crash

**Comment by SayHeiGitHub** [comment]
我也遇到这样的问题,英文版语言有问题,希望早点解决..

**Comment by mydy1987** [comment]
遇到相同的问题+1

**Comment by ZengSir** [comment]
pod MJRefresh 3.1.12    已经解决这个问题了。

**Comment by ZengSir** [comment]
@SayHeiGitHub 有啊，是不是因为你pod本地仓库没有更新。

pod search MJRefresh

-> MJRefresh (3.1.12)
   An easy way to use pull-to-refresh
   pod 'MJRefresh', '~> 3.1.12'
   - Homepage: https://github.com/CoderMJLee/MJRefresh
   - Source:   https://github.com/CoderMJLee/MJRefresh.git
   - Versions: 3.1.12, 3.1.11, 3.1.10, 3.1.9, 3.1.8, 3.1.7, 3.1.6, 3.1.5, 3.1.4,
   3.1.3, 3.1.2, 3.1.1, 3.1.0, 3.0.8, 3.0.7, 3.0.6, 3.0.5, 3.0.4, 3.0.3, 3.0.2,
   3.0.1, 3.0.0, 2.5.0, 2.4.12, 2.4.11, 2.4.10, 2.4.9, 2.4.8, 2.4.7, 2.4.6,
   2.4.5, 2.4.4, 2.4.3, 2.4.2, 2.4.1, 2.4.0, 2.3.2, 2.3.1, 2.3.0, 2.2.1, 2.2.0,
   2.1.0, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3,
   1.4.1, 1.4.0, 1.3.8, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0,
   1.2.0, 1.1.0, 1.0.5, 1.0.4, 1.0.3, 0.0.1 [master repo]

**Comment by Oil-Knight** [comment]
例如当本机语言是英文是   language=en 因而range.location 数值很大，截取字符串时会造成越界崩溃
