### ISSUE TITLE
iphone5s 使用奔溃问题

### ISSUE THREAD

**Issue by wushenchao** [CoderMJLee/MJRefresh#777]
```
self.webView.scrollView.contentInset = UIEdgeInsetsMake(self.headViewHeight, 0, 0, 0);
self.webView.scrollView.contentOffset = CGPointMake(0, -self.headViewHeight);
MJRefreshNormalHeader *normalHeader = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
    [weakSelf.webView reload];
}];
normalHeader.ignoredScrollViewContentInsetTop = self.headViewHeight;
self.webView.scrollView.mj_header = normalHeader;
```

在此方法下使用mj在5s机器上会出现下崩溃问题
![2016-10-13 5 16 06](https://cloud.githubusercontent.com/assets/8774296/19343451/d9f3d21e-9168-11e6-9230-bd12da8208d3.png)
![2016-10-13 5 16 26](https://cloud.githubusercontent.com/assets/8774296/19343452/da6be6e6-9168-11e6-8544-a2c15cf8b616.png)
![2016-10-13 5 16 35](https://cloud.githubusercontent.com/assets/8774296/19343453/da708778-9168-11e6-8516-2972d77faa48.png)

**Comment by iOSXH** [comment]
遇到同样的问题！
