### ISSUE TITLE
/** 提示没有更多的数据 */ - (void)noticeNoMoreData;

### ISSUE THREAD

**Issue by iHTCboy** [CoderMJLee/MJRefresh#78]
/** 提示没有更多的数据 */
- (void)noticeNoMoreData;  
[self.mainCollection.footer noticeNoMoreData];

MJ哥，我的搜索页面里共用一个collctionview，当我搜索一次，加载 没有更多时，调用这个方法后，以后搜索时，只能显示没有更多了，不能在加载了，能重置吗？谢谢MJ哥！

**Comment by CoderMJLee** [comment]
重置为普通状态：self.mainCollection.footer.state = MJRefreshFooterStateIdle;
或者你更新下框架，我刚才为你增加了一个resetNoMoreData方法哈
