### ISSUE TITLE
当滑动到最底部的时候，如何实现自动进入上拉获取更多？

### ISSUE THREAD

**Issue by ymsmile** [CoderMJLee/MJRefresh#780]
3.1.12 这个版本能实现像以前一样，如self.tableView.footer.automaticallyRefresh = YES;这样的功能吗？
类似于微博官方的客户端，当滑动到底部的时候，会自动进入上拉状态

**Comment by monkeyRing** [comment]
现在直接用 `MJRefreshAutoFooter`
