### ISSUE TITLE
当本机语言是英文时  language=en 因而range.location 数值很大，截取字符串时会造成越界崩溃

### ISSUE THREAD

**Issue by SmallGardener** [CoderMJLee/MJRefresh#783]
在- (NSString *)localizedStringForKey:(NSString *)key withDefault:(NSString *)defaultString方法中
     // 如果是iOS9以上，截取前面的语言标识
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
             language = [language substringToIndex:range.location];
        }
中   language = [language substringToIndex:range.location]; 这样写些问题，例如当本机语言是英文是       language=en 因而range.location 数值很大，截取字符串时会造成越界崩溃

**Comment by duckls** [comment]
怎么解决的

**Comment by duckls** [comment]
@Oil-Knight  怎么解决的 改源码吗 我也遇到这个问题 ，且应该是在 5 机型上崩溃

**Comment by Oil-Knight** [comment]
@duckls 新版的已解决这个问题mj_localizedStringForKey

**Comment by liyizhezhe** [comment]
今天因为这个原因app闪退被拒了，现在已经更新新版了。油骑士辛苦了^_^
