### ISSUE TITLE
求更新下拉 更新时间 lastUpdatedTimeLabel 的自定义文字

### ISSUE THREAD

**Issue by nihaocgl** [CoderMJLee/MJRefresh#786]
有时不想要刷新时间 ,想修改  却覆盖不掉..   求杰哥修改一下

**Comment by CoderZhuXH** [comment]
刷新时间可以影藏
    MJRefreshNormalHeader *mjHeader = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
    }];
    mjHeader.lastUpdatedTimeLabel.hidden = YES;
    self.tableView.mj_header = mjHeader;

**Comment by nihaocgl** [comment]
thx
