### ISSUE TITLE
MJ哥，能把点击“点击加载更多”这个不要吗？

### ISSUE THREAD

**Issue by hengchengfei** [CoderMJLee/MJRefresh#79]
我是想滑到下面时，只需要actiview显示，不要显示文字，可以吗？

**Comment by CoderMJLee** [comment]
self.tableView.footer.stateHidden = YES;

**Comment by hengchengfei** [comment]
collectionview即使设置了，还是会有的

**Comment by hengchengfei** [comment]
MJ哥,我加了你上面说的方法,但是,仍然还是有"点击加载更多",我打印了一下,  self.stateLabel.text=
"正在加载更多的数据...",我还是想不要"点击加载更多",这个怎么办?

**Comment by CoderMJLee** [comment]
为何不要想要啊？那就[self.tableView.footer setTitle:nil forState:MJRefreshFooterStateIdle];
