### ISSUE TITLE
中文语言下显示英文key值，箭头也消失了

### ISSUE THREAD

**Issue by colayet** [CoderMJLee/MJRefresh#791]
![screen shot 2016-11-07 at 16 24 19](https://cloud.githubusercontent.com/assets/8639365/20050904/fc3b19a2-a506-11e6-97d8-56ee79a3504d.png)
在iphone7 plus上出现的 10.1.1  pod导入的3.1.0。
因为是客户的手机，没有条件复现问题。 
看起来似乎是bundle找不到的样子，但是在其他任何手机都是正常的。
issues里面有类似问题，用重写方法解决的。有谁知道根本原因是什么？

**Comment by AresPeng** [comment]
我的也是，在开发时候中文，上传app，审核通过后，下载的就变成key值了

**Comment by leoou** [comment]
怎么解决？

**Comment by zwlnihao** [comment]
怎么解决，，，急求

**Comment by leoou** [comment]
@zwlnihao 应该是cocoapods问题，重新建立项目，重新导入pod，可以解决

**Comment by zwlnihao** [comment]
@leoou 谢谢，已解决，应该是 cocoapods 的问题，通过手动方式导入之后就没有这个问题了

**Comment by sunSink** [comment]
把MJRefresh.bundle手动拖拽到项目 build phased-copy bundle resources 里面就可以了

**Comment by sunSink** [comment]
@AresPeng 把MJRefresh.bundle手动拖拽到项目 build phased-copy bundle resources 里面就可以了
