### ISSUE TITLE
关于[NSLocale preferredLanguages]获得设备语言

### ISSUE THREAD

**Issue by victorylau** [CoderMJLee/MJRefresh#792]
iOS10.1 模拟器 xcode8.1  MJRefresh v3.1.0
NSString *language = [NSLocale preferredLanguages].firstObject;
languaage = 'en'

寻找'-' 应该是NSNotFound 会报错。

**Comment by sunwell** [comment]
我也遇到了相同的问题

iOS10.0  Xcode8.0  MJRefresh3.1.0

加一条判断条件`if (language && [language containsString:@"-"])`解决模拟器奔溃的问题，模拟器上刷新提示英文，真机上没问题的。
这个地方本意想使用本地化方便设置刷新提示的，但是代码写得不太严谨。
