### ISSUE TITLE
连续下拉刷新,导致collectionView的item无法触发点击事件!!!

### ISSUE THREAD

**Issue by shenguanjiejie** [CoderMJLee/MJRefresh#795]
在父CollectionView的ReusableHeaderView中添加子collectionView,连续刷新父collectionView的mj_header ,会导致父collectionView的所有item点击事件消失,子collectionView的item能够正常使用.

**Comment by shenguanjiejie** [comment]
我把子collectionView改成放到父collectionView的item中 , 结果跟上面一样!!!!!!! 求修复啊

**Comment by wolfcon** [comment]
Duplicate of #1218
