### ISSUE TITLE
上拉刷新的时候sectionHeader会跳跃

### ISSUE THREAD

**Issue by mg459046365** [CoderMJLee/MJRefresh#798]
当滚动到某section,sectionHeader悬浮时，此刻上拉刷新，sectionHeader会有跳跃的效果，非常严重。希望MJ老师，能够修复一下。谢谢啦。

**Comment by haijiaoliuhao91** [comment]
你解决这个问题了吗

**Comment by haijiaoliuhao91** [comment]
@mg459046365 我也遇到了 你是怎么解决的

**Comment by wolfcon** [comment]
Duplicate of #1009
