### ISSUE TITLE
storyboard实现的UICollectionView上拉加载更多时触发很多次

### ISSUE THREAD

**Issue by jevonszmx** [CoderMJLee/MJRefresh#80]
我的UICollectionViewController是用Storyboard拖拽的，cell是自定义的，用上拉加载更多代码：

```
// 上拉刷新
    [self.collectionView addLegendFooterWithRefreshingBlock:^{
        NSLog(@"Footer");
//        
        dispatch_async(dispatch_get_main_queue(), ^{
//            [weakSelf.collectionView reloadData];
            
            // 结束刷新
            [weakSelf.collectionView.footer endRefreshing];
        });
    }];
```

log中查看，触发了N多次Footer，而你的example却没有，是怎么回事？

**Comment by CoderMJLee** [comment]
之前有网友发生过类似的问题，你先试试最新的框架代码，如果还不行，麻烦把Demo发给我看看哈，谢谢

**Comment by zenghaojim33** [comment]
同样出现了这种情况：
-(void)footerRefresh
{
    
    NSString * userid = [[NSUserDefaults standardUserDefaults]objectForKey:@"userid"];
    _page++;
    
    [HTTPRequestManager getURL:[NSString stringWithFormat:@"%@&userid=%@&select=up&size=15&index=%ld",GET_PRODUCT_API,userid,(long)_page] andParameter:nil onCompletion:^(NSDictionary *dict, NSError *error) {
        
        [_productList addObjectsFromArray:dict[@"result"]];
        
        dispatch_async(dispatch_get_main_queue(), ^{
            [_myTableView reloadData];
            [self.myTableView.footer endRefreshing];
        });
    }];
    
    
    
    
    
}

刷新一下这个方法被调用了10多次
问题找到了，如果当cell的数量不多，“点击加载更多”这几个字的位置偏上的话，就不会出现这种情况
但是如果“点击加载更多”靠近tableview的底部的时候刷新就会不断调用

**Comment by CoderMJLee** [comment]
好的，我看看。那我问几个问题，了解多一点哈。
1.这10次调用，是一次性调用？还是一次调用完一段时候后再接着下一次？
2.没调用1次，你的数据会越来越多么？

**Comment by zenghaojim33** [comment]
瞬间调用10+次（由于我的HUD封装在网络请求内，可以看到载入画面非常快地闪了10多次）
不会，如果有数据马上就结束了，没有数据就一直闪

**Comment by CoderMJLee** [comment]
好的，谢谢提醒，我定会抽时间修改下。给你带来的不便，十分抱歉哈

**Comment by zenghaojim33** [comment]
客气了，我暂时还是先用旧版的：）

**Comment by jevonszmx** [comment]
已经解决，和zenghaojim33现象是一样的，基本上这个问题是因为[self.collectionView reloadData];是放在不同进程中导致的，只要把reloadData移到数据加载的进程后就可以，比如：

```
// 上拉刷新
    [self.collectionView addLegendFooterWithRefreshingBlock:^{
        [weakSelf loadData];
       // 这里面不能放[self.collectionView reloadData];
    }];
```

```
-(void)loadData {
dispatch_async(dispatch_get_global_queue( DISPATCH_QUEUE_PRIORITY_LOW, 0), ^{

             ....... do some thing , eg:  [Model loadData];

                dispatch_async(dispatch_get_main_queue(), ^{
                    [self.collectionView reloadData];
                    if (self.collectionView.header.isRefreshing) {
                        NSLog(@"header.isRefreshing");
                        [self.collectionView.header endRefreshing];
                    }
                    else if (self.collectionView.footer.isRefreshing){
                        NSLog(@"footer isRefreshing");
                        [self.collectionView.footer endRefreshing];
                    }
                });
}

```

**Comment by HQforC** [comment]
多次添加和移除footer会出现scrollView的底部多出一截空白区域，高度目测是footer.height * 添加的次数
