### ISSUE TITLE
header和footer都无法自动隐藏

### ISSUE THREAD

**Issue by AniOSDeveloper** [CoderMJLee/MJRefresh#800]
在低速或网络异常情况下，无论是无返回数据还是有1条返回数据，header和footer都无法自动隐藏，页面会同时显示mjheader和mjfooter，环境是Xcode8.1，ios8.1和10.1都有此情况发生

最新情况：在低速或网络异常情况下，每下拉刷新一次，mjheader就会下移一个mjheader高度，若多次下拉刷新，mjheader会下移多次，最终可能会出现屏幕上没有内容且mjheader已经移到屏幕下方。如何重置mjheader到原始位置？

**Comment by chengongwen** [comment]
我也遇到过，几个视图控制都都有 mj_header 方法，当下拉一个控制器的时候，马上切换到另外一个控制器下拉，然后在返回到前一个控制器，heade无法自动隐藏，一直在外面，即屏幕下方

**Comment by Wangmafei** [comment]
我也遇到过，最新的版本，footer 不能自动隐藏 ，automaticallyHidden = YES; 不生效
