### ISSUE TITLE
How to use it in swift3?

### ISSUE THREAD

**Issue by liaodalin19903** [CoderMJLee/MJRefresh#802]
self.tableView.mj_footer = MJRefreshBackNormalFooter(refreshingBlock: { () -> Void in
            
            self.myTableView.mj_footer.endRefreshing()
        })

error: 不能找到MJRefreshBackNormalFooter

**Comment by mancongiOS** [comment]
__unsafe_unretained UITableView *tableView = self.tableView;
    
    // 下拉刷新
    tableView.mj_header= [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        // 模拟延迟加载数据，因此2秒后才调用（真实开发中，可以移除这段gcd代码）
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            // 结束刷新
            [tableView.mj_header endRefreshing];
        });
    }];

**Comment by liaodalin19903** [comment]
@mancongiOS 问下__unsafe_unretianed 这个对其有和作用呢‘
