### ISSUE TITLE
下拉刷新的问题(比较奇怪的问题)

### ISSUE THREAD

**Issue by ghost** [CoderMJLee/MJRefresh#804]
**A页面有一个悬浮的按钮button(是添加到window上面的)，同时A页面还集成了MJRefresh，在A页面下拉刷新的时候（正在下拉刷新,下拉刷新动画还存在)(下拉刷新的动画是自定义的)，此时点击悬浮的按钮button** Push到B界面(B界面是需要隐藏导航栏的),在B界面所属的控制器的viewDidLoad、viewWillApper、viewDidApper 都写了隐藏导航栏的代码，但导航栏还是无法隐藏。只有在下拉刷新动画结束的时候，去点击那个悬浮的按钮button  Push 到 B界面的时候，B界面的导航栏才可以被隐藏起来。

**Comment by Zcating** [comment]
你需要在原来的View中添加 endRefreshing 方法。

**Comment by Zcating** [comment]
添加在 view will disappear中
