### ISSUE TITLE
- [MJRefreshComponent isRefreshing] 应该添加一个只读属性声明

### ISSUE THREAD

**Issue by zhangchn** [CoderMJLee/MJRefresh#809]
目前在Swfit项目中，想替换UIRefreshControl的情况下，必须修改isRefresing的调用：

    refreshControl.isRefreshing
到

    refreshControl.isRefreshing()

如果isRefreshing能作为只读属性，如：

    @property (assign, nonatomic, readonly, getter=isRefreshing) BOOL refreshing;
则Swift下，可以减少UIRefreshControl->MJRefresh的迁移成本。

实际上添加上述@interface属性声明不需要改变任何@implementation代码。

**Comment by CoderMJLee** [comment]
谢谢建议，下个版本可能会更新
