### ISSUE TITLE
调用mj_footer.endRefreshing() 之后 又触发一次上拉刷新

### ISSUE THREAD

**Issue by fengqiangboy** [CoderMJLee/MJRefresh#813]
调用mj_footer.endRefreshing() 之后 又触发一次上拉刷新

**Comment by hackjie** [comment]
@CoderMJLee MJ大神,确实存在这样的问题,代码虽然写了[tableView.mj_header endRefreshing];但实际上没有执行
- (void)endRefreshing
{
    dispatch_async(dispatch_get_main_queue(), ^{
        self.state = MJRefreshStateIdle;
    });
}

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
