### ISSUE TITLE
苹果审核crash log中提到了很多了MJRefresh,不知道是哪里的问题

### ISSUE THREAD

**Issue by bianzhifeng** [CoderMJLee/MJRefresh#816]
0   libsystem_kernel.dylib        	0x000000018d87e014 __pthread_kill + 8
1   libsystem_pthread.dylib       	0x000000018d946450 pthread_kill + 112
2   libsystem_c.dylib             	0x000000018d7f23e0 abort + 140
3   libc++abi.dylib               	0x000000018d2bd2d4 __cxa_bad_cast + 0
4   libc++abi.dylib               	0x000000018d2d7688 std::__terminate(void (*)()) + 44
5   libc++abi.dylib               	0x000000018d2d6f84 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*) + 0
6   libobjc.A.dylib               	0x000000018d2e8690 _objc_exception_destructor(void*) + 0
7   CoreFoundation                	0x000000018e8ae108 -[NSException initWithCoder:] + 0
8   Foundation                    	0x000000018f2a96a0 -[NSString substringToIndex:] + 128
9   MJRefresh                     	0x0000000100b26ae0 -[MJRefreshComponent localizedStringForKey:withDefault:] (MJRefreshComponent.m:150)
10  MJRefresh                     	0x0000000100b2a27c -[MJRefreshStateHeader setLastUpdatedTimeKey:] (MJRefreshStateHeader.m:107)
11  MJRefresh                     	0x0000000100b28518 -[MJRefreshHeader prepare] (MJRefreshHeader.m:40)
12  MJRefresh                     	0x0000000100b2a504 -[MJRefreshStateHeader prepare] (MJRefreshStateHeader.m:118)
13  MJRefresh                     	0x0000000100b2638c -[MJRefreshComponent initWithFrame:] (MJRefreshComponent.m:29)
14  MJRefresh                     	0x0000000100b28498 +[MJRefreshHeader headerWithRefreshingTarget:refreshingAction:] (MJRefreshHeader.m:26)
15  TigerCoach                    	0x00000001000d257c -[TCIPhoneFeedCtrol setUpRefreshView] (TCIPhoneFeedCtrol.m:224)
16  TigerCoach                    	0x00000001000d2178 __32-[TCIPhoneFeedCtrol viewDidLoad]_block_invoke (TCIPhoneFeedCtrol.m:180)
17  AFNetworking                  	0x0000000100bea134 __116-[AFHTTPSessionManager dataTaskWithHTTPMethod:URLString:parameters:uploadProgress:downloadProgress:success:failure:]_block_invoke.80 (AFHTTPSessionManager.m:290)
18  AFNetworking                  	0x0000000100bfd4e8 __72-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]_block_invoke_2.150 (AFURLSessionManager.m:308)
19  libdispatch.dylib             	0x000000018d739200 _dispatch_call_block_and_release + 24
20  libdispatch.dylib             	0x000000018d7391c0 _dispatch_client_callout + 16
21  libdispatch.dylib             	0x000000018d73db30 _dispatch_main_queue_callback_4CF + 428
22  CoreFoundation                	0x000000018e85bf2c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
23  CoreFoundation                	0x000000018e859b18 __CFRunLoopRun + 1660
24  CoreFoundation                	0x000000018e788048 CFRunLoopRunSpecific + 444
25  GraphicsServices              	0x000000019020e198 GSEventRunModal + 180
26  UIKit                         	0x00000001947742fc -[UIApplication _run] + 684
27  UIKit                         	0x000000019476f034 UIApplicationMain + 208
28  TigerCoach                    	0x000000010018b1c8 main (main.m:15)
29  libdyld.dylib                 	0x000000018d76c5b8 start + 4

**Comment by diyinqianchang** [comment]
iOS 10  好像是会闪退

**Comment by HYJFromQc** [comment]
请问你是怎么解决的 啊，除了判断range.location != NSNotFound

**Comment by zymchen** [comment]
更新下版本吧, 好像更新就解决了

**Comment by CoderMJLee** [comment]
这个问题应该已经解决了哈
