### ISSUE TITLE
[tableView.header endRefreshing] 这个方法的会对最下面cell有动画效果

### ISSUE THREAD

**Issue by recx** [CoderMJLee/MJRefresh#82]
MJRefreshHeader.m 中的 -setState:方法
  // 恢复inset和offset
                [UIView animateWithDuration:MJRefreshSlowAnimationDuration delay:0.0 options:UIViewAnimationOptionAllowUserInteraction|UIViewAnimationOptionBeginFromCurrentState animations:^{
                    _scrollView.mj_insetT -= self.mj_h;
                } completion:nil];

这段代码的动画效果，会导致tableview的最底下的cell，有动画效果。

下面是效果截图
![qq 20150319171654](https://cloud.githubusercontent.com/assets/4349448/6727310/e4732414-ce5b-11e4-92cb-fa1963e97c9c.gif)

**Comment by CoderMJLee** [comment]
这个我真没遇到过，会不会是其他原因？你的cell内部的子控件是自定义的，还是cell自带的？

**Comment by recx** [comment]
内部的控件都是自定义的。我感觉 我内部的view 在你的动画时间内，一点点的再放大。

**Comment by CoderMJLee** [comment]
有空我试试看哈。不过有这动画也好炫的样子啊，哈哈哈，开玩笑的，别介意哈

**Comment by recx** [comment]
哈哈，是挺炫的。貌似不止我自己出现这个状况。我看别人也提交过这个问题。给你看的这个图片，是我之前写的一个app，现在写的这个 也存在这个效果。但是不知道是不是我哪里写的有问题。最近比较忙。闲下来的时候我找下是不是自己的问题。不管怎么样，这个下拉刷新确实非常好用。

**Comment by klaus01** [comment]
这个问题最终怎么解决呀？

后面的 Cell 有放大动画，是因为 endRefreshing 时内容往上移动，这时有多余的空间显示一个新的 Cell，系统实例化了这个 Cell 并且设置了 cell.frame，并且系统设置 frame 时刚好在动画时间内，所以就有了尾部 Cell 放大动画。

我大概知道原因，但没想法方法解决。
