### ISSUE TITLE
V3.1.12的bug：collectionView如果设置内边距，下拉刷新过程中会使视图发生偏移

### ISSUE THREAD

**Issue by CocoaYog** [CoderMJLee/MJRefresh#822]
项目中我设置的collectionView的左右内边距是10，下拉刷新过程中，collectionView向左偏移了10，如果设置了内边距是20，就会向左偏移20。 现在我尝试使用了3.1.0，会有同样的情况。换成3.0.8后，没有问题

**Comment by columbusLGEN** [comment]
我也遇到这个问题,请问你解决了吗

**Comment by CoderMJLee** [comment]
@CocoaYog 可以提供一个有问题的Demo看看不，我直接调试哈

**Comment by xyxdasnjss** [comment]
依然存在这个问题

**Comment by Rookie920** [comment]
请问这个问题解决了没
