### ISSUE TITLE
数据不满一页时Footer显示的问题

### ISSUE THREAD

**Issue by Steven-Yung** [CoderMJLee/MJRefresh#828]
MJ大神，设置footer的`automaticallyHidden=YES`貌似只对数据为0时起作用，当数据不满一屏幕的时候底部的footer还是显示出来的，能不能隐藏掉？
![Uploading image.png…]()

**Comment by YFWCQ** [comment]
不满一页时说明 footer 是没用的，初始化不应该加上footer，只在能确定有第二页的时候，加上footer

**Comment by meilbn** [comment]
你自己可以在数据返回的时候判断数据量来显示或不显示 footer
