### ISSUE TITLE
demo的bug

### ISSUE THREAD

**Issue by Baichenghui** [CoderMJLee/MJRefresh#829]
示例3没刷新完毕,切换其他示例会奔溃

**Comment by tyzChar** [comment]
是的，我也遇到了，就是没刷新完，跳转页面当前页面回收Tableview没有了，再调用endRefreshing会导致奔溃，就是野指针导致的 Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)，但是应该怎么解决呢？怎么告诉刷新的线程这个页面被销毁了呢？
