### ISSUE TITLE
下拉时，背景图片

### ISSUE THREAD

**Issue by iHTCboy** [CoderMJLee/MJRefresh#83]
MJ哥,现在的下拉刷新，流行起有背景的一起下拉，MJRefresh是否会提供这么好的接口吗？
如果我想改，应该在那个文件中增加呢？
先谢谢MJ哥，为我们省事不少啊！

**Comment by CoderMJLee** [comment]
暂时没有支持这种情况，如果你想自己写一个，那得参考MJRefreshHeader.m和其他Header结尾的.m文件
