### ISSUE TITLE
UICollectionView  添加HeaderView ，设置ContentInset，mj_header不显示

### ISSUE THREAD

**Issue by BestKai** [CoderMJLee/MJRefresh#830]
解决方案如下:
在MJRefreshHeader 下的placeSubViews方法里

修改    self.mj_y = - self.mj_h - self.ignoredScrollViewContentInsetTop;为
self.mj_y = - self.mj_h - self.ignoredScrollViewContentInsetTop - self.scrollViewOriginalInset.top;

**Comment by 0xdatou** [comment]
ignoredScrollViewContentInsetTop不就是解决这个的吗？上面说的是什么鬼。。
