### ISSUE TITLE
有一个小bug

### ISSUE THREAD

**Issue by laughing25** [CoderMJLee/MJRefresh#835]
#import "MJRefreshBackStateFooter.h"
- (void)setState:(MJRefreshState)state
//            因为这里加了一个动画，导致最终显示无数据的时候有一个箭头
//            [UIView animateWithDuration:MJRefreshSlowAnimationDuration animations:^{
//                self.loadingView.alpha = 0.0;
//            } completion:^(BOOL finished) {
//                
//            }];

调用顺序
mj_foot endrefresh;
mj_foot endrefreshnomoredata

**Comment by wolfcon** [comment]
直接调用 `endRefreshingWithNoMoreData` 就好了. 为什么要调用2次..

另外你的 setState 没有调用 `super` 吗?
