### ISSUE TITLE
传统上拉刷新有bug

### ISSUE THREAD

**Issue by zhongdom** [CoderMJLee/MJRefresh#84]
mj哥，MJRefresh的tableview传统上拉刷新有bug，设置section为多个，每个section1行，table:heightForFooterInSection为15，tableView heightForHeaderInSection:为0.01的时候，会有底部会有一条和heightForFooterInSection高度一样的条状view存在，拖动tableview时这个条不会动

**Comment by CoderMJLee** [comment]
试试最新版本？2.0版本

**Comment by 624560545** [comment]
最新版可以

**Comment by zhuchuanwu** [comment]
mj哥，我想上拉的时候，释放拖动手势的时候 才加载，这个能设置吗
