### ISSUE TITLE
tableview or sectionview 刷新后不能点击

### ISSUE THREAD

**Issue by zfavourite99** [CoderMJLee/MJRefresh#843]
数据量很少，只有一两条数据（内容高度不超过 frame 大小），这个时候下拉刷新后，tableview的cell 或者 collectionView 的item 无法点击。轻轻滚动一点距离之后，就又可以点击了。

我找了很久也没找到原因，但是应该和下拉刷新有关，每次刷新之后不能点，滚动一下就又能点了，再刷新一下就又不能点了。。。。。

**Comment by zhysan** [comment]
请问有找到原因和解决办法吗，我也在 plus 机型上遇到了

**Comment by CoderMJLee** [comment]
可以提供一个出现此问题的Demo么，我直接调试，谢谢哈

**Comment by CQXfly** [comment]
hi 该问题是否有解决方案 我也遇到了同样的问题
