### ISSUE TITLE
MJRefresh 快速下拉时出现的bug。

### ISSUE THREAD

**Issue by utouuzhenglong** [CoderMJLee/MJRefresh#847]
![img_1734](https://cloud.githubusercontent.com/assets/20631803/22239022/61c47e32-e24f-11e6-9888-90767ca0b524.png)

下拉的时候点击UISegmentedControl切换到其他页面的时候，mj_header偏移量未恢复初始位置，出现了拉一次就增加一次的bug,如图所示

**Comment by caohongyang** [comment]
我也出现这个问题了
<img width="375" alt="2017-02-21 3 12 53" src="https://cloud.githubusercontent.com/assets/17538734/23154356/59810d94-f848-11e6-94ec-4d8df56c59a4.png">
如何解决呢?
