### ISSUE TITLE
上拉刷新，无网络时，会一直闪。

### ISSUE THREAD

**Issue by hengchengfei** [CoderMJLee/MJRefresh#85]
一开始有数据，然后把网络断了，上拉时，底部会一直闪。

用的是uicollectionview

**Comment by CoderMJLee** [comment]
你把网络断了，那肯定不会进入成功的回调，然后肯定不会结束刷新啊。。。。你要自己去监听网络的异常，MJRefresh只负责UI展示

**Comment by hengchengfei** [comment]
如果自己监听网络时，网络断了的话，将上拉隐藏，此时网络再打开，但是上拉已经隐藏，不会再显示了。

**Comment by CoderMJLee** [comment]
哈哈，那你就再显示回来不就好了么？self.tableView.footer.hidden = NO;
