### ISSUE TITLE
滚动视图联动下拉刷新问题

### ISSUE THREAD

**Issue by iOSGL** [CoderMJLee/MJRefresh#856]
有一个视图A（TableView）,和一个视图B(scrollView)，将下拉刷新集成在B视图上，视图B根据视图A的contentOffset.y移动而移动，但是下拉A视图时，B视图能暴露出来Header，箭头却一直朝下走，没有办法出现松手加载更多，等字样。

**Comment by geng199200** [comment]
@ftp27 @RbBtSn0w @zwf @Sinkup @lawkaii  请问是什么问题

**Comment by geng199200** [comment]
@ftp27 @RbBtSn0w @zwf @Sinkup @lawkaii  请教一下，这是什么问题造成的？

**Comment by ftp27** [comment]
Would you speak English please?

**Comment by wolfcon** [comment]
你需要定制一个不需要 Drag 状态即可刷新的Header
