### ISSUE TITLE
[self.collectionView.gifHeader beginRefreshing] 进不了block方法里。

### ISSUE THREAD

**Issue by hengchengfei** [CoderMJLee/MJRefresh#86]
首次进入是有效的，当通过通知或其他方式调用beginRefreshing时，则进入不了block里面。
 [self.collectionView addGifHeaderWithRefreshingBlock:^{

    } dateKey:@"homelatest"];

之前的版本没有下面的判断,只有一句self.state = MJRefreshHeaderStateRefreshing;
如果只有这一句的话，那动画又有问题了，从左侧滑到右侧。

- (void)beginRefreshing
{
    if (self.window) {
        self.state = MJRefreshHeaderStateRefreshing;
    } else {
        self.state = MJRefreshHeaderStateWillRefresh;
    }
}

**Comment by CoderMJLee** [comment]
我没遇到这样的情况哦，你说的第一个问题最好有个Demo哈。
至于第2个问题，你表达的意思是最新代码没有动画问题了，是不是？

**Comment by hengchengfei** [comment]
MJ你好，demo已经发到你qq了

**Comment by hengchengfei** [comment]
MJ，请问解决了吗

**Comment by CoderMJLee** [comment]
Sorry，我还没时间细看，这一两内看看哈

**Comment by hengchengfei** [comment]
动画问题什么时候解决呢

**Comment by CoderMJLee** [comment]
上个月已经解决了哦

**Comment by hengchengfei** [comment]
解决了动画，出现其他问题了。demo早发给你了啊

**Comment by CoderMJLee** [comment]
Sorry，比较忙哈。你可以再试试最新的框架代码，如果还有问题，再发一次到我邮箱哈，谢谢
