### ISSUE TITLE
APP提交审核被拒

### ISSUE THREAD

**Issue by Adrift001** [CoderMJLee/MJRefresh#866]
Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with section 3.3.2 of the Apple Developer Program License Agreement and App Store Review Guideline 2.5.2. This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. 

This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

Please perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above before submitting the next update for your app for review.

上面是被拒的邮件内容,上面提到一个`method_exchangeImplementations`方法,然后搜索了一下整个项目,发现MJFefresh使用了这个方法,被拒的原因是不是因为这个呢?

**Comment by ericdream** [comment]
应该不是 method_exchangeImplementations 导致的  running remote scripts in order to change app behavior or call SPI, based on the contents of the downloaded script. 现在审核比较严了，比如热修复都开始警告了
