### ISSUE TITLE
自定义上拉刷新时刷新时出现异常

### ISSUE THREAD

**Issue by MyDarren** [CoderMJLee/MJRefresh#867]
如果继承自MJRefreshBackGifFooter自定义上拉刷新，如果图片大小较大时，即使设置self.mj_h = 60;偶尔会出现屏幕左下角闪过刷新的大图片，不知道问题出在哪里，代码:
self.imageArray = [NSMutableArray array];
    for (int i = 2; i <= 111; i++) {
        NSString *imageNameString = [NSString stringWithFormat:@"dropdown_anim_%d.png",i];
        NSString *imagePathString = [[NSBundle mainBundle] pathForResource:imageNameString ofType:nil];
        UIImage *image = [UIImage imageWithContentsOfFile:imagePathString];
        [self.imageArray addObject:image];
    }
    self.mj_h = 60;

- (void)placeSubviews{
    [super placeSubviews];
    if (self.gifView.constraints.count) return;
    if (self.stateLabel.hidden == YES && self.gifView.hidden == NO) {
        self.gifView.frame = CGRectMake(MARGIN,(self.mj_h - GIMAGEWIDTH) / 2,self.mj_w - MARGIN,GIMAGEWIDTH);
        self.gifView.contentMode = UIViewContentModeScaleAspectFit;
    }else if (self.gifView.hidden == YES && self.stateLabel.hidden == NO) {
        self.stateLabel.frame = CGRectMake(MARGIN,(self.mj_h - GIMAGEWIDTH) / 2,self.mj_w - MARGIN,GIMAGEWIDTH);
    }else {
        CGFloat stateLabelWidth = self.stateLabel.mj_textWith;
        CGFloat marginToBorder = (self.mj_w - GIMAGEWIDTH - stateLabelWidth - MARGIN) / 2;
        self.gifView.frame = CGRectMake(marginToBorder, (self.mj_h - GIMAGEWIDTH) / 2, GIMAGEWIDTH, GIMAGEWIDTH);
        self.stateLabel.frame = CGRectMake(CGRectGetMaxX(self.gifView.frame) + MARGIN, CGRectGetMinY(self.gifView.frame), stateLabelWidth, CGRectGetHeight(self.gifView.frame));
        self.gifView.contentMode = UIViewContentModeScaleAspectFit;
    }
}

- (void)setState:(MJRefreshState)state{
    MJRefreshCheckState
    // 根据状态做事情
    if (state == MJRefreshStateIdle) {
        self.gifView.hidden = YES;
        self.stateLabel.hidden = NO;
    }else if (state == MJRefreshStatePulling) {
        self.gifView.hidden = YES;
        self.stateLabel.hidden = NO;
    }else if (state == MJRefreshStateWillRefresh) {
        self.gifView.hidden = NO;
        self.stateLabel.hidden = YES;
    }else if (state == MJRefreshStateRefreshing){
        if (self.imageArray.count == 0) return;
        self.gifView.hidden = NO;
        self.stateLabel.hidden = YES;
        [self.gifView stopAnimating];
        if (self.imageArray.count == 1) { // 单张图片
            self.gifView.image = [self.imageArray lastObject];
        } else { // 多张图片
            self.gifView.animationImages = self.imageArray;
            self.gifView.animationDuration = IMAGEDURATION;
            [self.gifView startAnimating];
        }
    } else if (state == MJRefreshStateNoMoreData) {
        self.gifView.hidden = YES;
        self.stateLabel.hidden = NO;
        [self.gifView stopAnimating];
    }
}

**Comment by wolfcon** [comment]
Demo
