### ISSUE TITLE
调用方法：endRefreshingWithNoMoreData 后，如何让表格下滑一点，不想一直展示footer

### ISSUE THREAD

**Issue by zjjzmw1** [CoderMJLee/MJRefresh#868]
[wSelf.tableView.mj_footer endRefreshingWithNoMoreData];
我调用上面的方法后，一直展示footer，需要手动滚动一点才可以覆盖住footer，有的app是，暂时0.5秒 没有数据的提示后，自动消失了，

**Comment by ansonham** [comment]
wSelf.tableView.mj_footer = nil 即可
