### ISSUE TITLE
使用 method_exchangeImplementations私有Api 上线被拒

### ISSUE THREAD

**Issue by zhangnianqq** [CoderMJLee/MJRefresh#873]
2. 5 PERFORMANCE: SOFTWARE REQUIREMENTS
Performance - 2.5.2

Your app, extension, and/or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with App Store Review Guideline 2.5.2 and section 3.3.2 of the Apple Developer Program License Agreement. 

This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as dlopen(), dlsym(), respondsToSelector:, performSelector:, method_exchangeImplementations(), and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

Next Steps 

Perform an in-depth review of your app and remove any code, frameworks, or SDKs that fall in line with the functionality described above and resubmit your app’s binary for review.

**Comment by jiao808813** [comment]
真的是因为MJRefresh?

**Comment by zhangnianqq** [comment]
整个项目中只有MJRefresh使用了 method_exchangeImplementations  这个方法。。。   http://www.jianshu.com/p/20aee3dda332  可以看下这个链接， 我是已经把这个库给替换掉了

**Comment by jiao808813** [comment]
那就看你替换掉之后能否通过审核

**Comment by jjxh888** [comment]
用了MJRefresh，已通过审核，不存在该问题

**Comment by fromtaipe** [comment]
@zhangnianqq 哈喽，请问你这个问题如何解决的呀？是这个库的原因吗？

**Comment by jiao808813** [comment]
这个库的确不存在审核问题
