### ISSUE TITLE
iOS 9 以上，英文环境下，数组越界

### ISSUE THREAD

**Issue by pzhtpf** [CoderMJLee/MJRefresh#874]
MJRefreshComponent.m 

  // 如果是iOS9以上，截取前面的语言标识
        if ([UIDevice currentDevice].systemVersion.floatValue >= 9.0) {
            NSRange range = [language rangeOfString:@"-" options:NSBackwardsSearch];
            language = [language substringToIndex:range.location];
        }

英文环境下  language = @"en" ,处理出错，麻烦尽快修复

**Comment by Stevezhong0506** [comment]
好像是7plus才会这样，我把他注释掉了，我们只用中文。

**Comment by Stevezhong0506** [comment]
是的，7Plus会崩溃，只能注释掉，有无其他办法

**Comment by onehao16** [comment]
if (range.location != NSNotFound) {
                language = [language substringToIndex:range.location];
            }
可以这样判断一下
