### ISSUE TITLE
下拉刷新往下跑

### ISSUE THREAD

**Issue by yushan023** [CoderMJLee/MJRefresh#879]
![4117c92d252975b7470574bab3dfd444](https://cloud.githubusercontent.com/assets/20593532/24192177/0fc2b44e-0f29-11e7-9326-e2d9f886c885.jpg)

**Comment by qllqll** [comment]
我也同样有这个问题 还没刷新完到新的界面，然后在返回就没一直向下偏移，求解决

**Comment by Leo617** [comment]
一直以为只有我一个人有这个问题呢，解决了吗？能给个方案吗？谢谢了。

**Comment by foolish1016** [comment]
请问有人解决了吗？

**Comment by xhp281** [comment]
https://github.com/CoderMJLee/MJRefresh/issues/892
