### ISSUE TITLE
MJ老师你好,我在github上下了最新版,多次下拉刷新的时候会导致tableview整体上移,不知道是为什么?

### ISSUE THREAD

**Issue by guorenlei** [CoderMJLee/MJRefresh#88]
纠结了一下午,希望得到MJ老师的帮助

**Comment by CoderMJLee** [comment]
能发个Demo看看么？我暂时没遇到这样的情况哦

**Comment by guorenlei** [comment]
谢谢MJ老师的回复,现在我公司应用的接口是内网的,所以没办法给您发demo,我已经用之前的版本了.再就是这个问题我的同学也遇到了,和我一样的问题,根源在多次下拉刷新(连着下拉多次,然后再上拉,如果数据都加载完毕,tableVIew距离屏幕最下面会有很大的距离,下拉刷新次数越多,距离越大),我同学把下拉刷新换成系统自带的,就不会出现tableView整体上移的情况了

**Comment by hongdong** [comment]
上移的情况我也遇到过

**Comment by guorenlei** [comment]
@hongdong 你上移的情况是怎么解决的?

**Comment by CoderMJLee** [comment]
你再下载最新代码试试哈，我刚才参考旧版本，修改了一下

**Comment by guorenlei** [comment]
@CoderMJLee 好的,我下载试试,老师辛苦了
