### ISSUE TITLE
在下拉时，禁止上拉

### ISSUE THREAD

**Issue by GorCat** [CoderMJLee/MJRefresh#883]
你好~，我想问一下，如果我想实现在下拉时禁止上拉，和上拉时禁止下拉，要如何实现比较好呢？

**Comment by Nododo** [comment]
我碰到了类似的问题，如果用户上拉马上下拉会造成 indexPath.row > numberOfRowsInSection，在cellForRowAtIndexPath 里 return 一个用不到的cell，发生一些意外的闪退
