### ISSUE TITLE
网速慢的时候正在下拉，到一个新页面 然后返回，位置偏移

### ISSUE THREAD

**Issue by qllqll** [CoderMJLee/MJRefresh#885]
在网速较慢的时候，下拉刷新，正在刷新的时候到一个新页面，然后返回，就会发现刷新头，向下偏移，如果多重复几次，刷新头一直向下偏移，请问一下，你们的怎么解决的 ？

**Comment by RylynnLai** [comment]
遇到同样的情况，这样不知道行不行
- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
    [self.tableView.mj_header endRefreshing];
    [self.tableView.mj_footer endRefreshing];
}

**Comment by wolfcon** [comment]
已经解决
