### ISSUE TITLE
最新版 MJTestViewController

### ISSUE THREAD

**Issue by housenkui** [CoderMJLee/MJRefresh#887]
您好：
最新版 MJTestViewController
有个宏
#define MJPerformSelectorLeakWarning(Stuff) \
do { \
_Pragma("clang diagnostic push") \
_Pragma("clang diagnostic ignored \"-Warc-performSelector-leaks\"") \
Stuff; \
_Pragma("clang diagnostic pop") \
} while (0)

_Pragma 声明能看懂，但是这里面加 do{} while(0)，我觉得多余。为什么要加这个呢？
谢谢。

**Comment by MatrixMiaou** [comment]
宏是做文本替换的，do{} while{0} 只调用一次而已，加这个的目的是为了防止在某种情况下进行文本替换的过程导致语义混淆甚至是语法错误，具体可以去了解宏的用法

**Comment by CoderMJLee** [comment]
@MatrixMiaou 是的。
@housenkui 可以参考这个链接：http://blog.csdn.net/yasi_xi/article/details/19483197

**Comment by housenkui** [comment]
谢谢
