### ISSUE TITLE
上拉刷新会多次重复调用刷新方法

### ISSUE THREAD

**Issue by QuentinGui** [CoderMJLee/MJRefresh#89]
当按照示例程序的 ex11进行添加,然后刷新方法是:
```//drag down to reload
-(void)dragDownReloading
{
    DDLogVerbose(@"dragdown");
    // 刷新表格
    [self.dealTableview reloadData];
    
    // 拿到当前的下拉刷新控件，结束刷新状态
    [self.dealTableview.header endRefreshing];
}```
当上拉控件的时候,会看到控制台不断打印

**Comment by QuentinGui** [comment]
解决了,原来就是那么设计の,如果要防止重复重复刷新.需要添加以下代码
`//防止重复刷新 self.dealTableview.footer.automaticallyRefresh = NO;`

**Comment by mzying2013** [comment]
Fuck This!   我调试了好久      日！

**Comment by lockezhang** [comment]
你自己没有设置好还怪别人，还骂人，真没有素质。
MJ老师辛辛苦苦写这个，无私的贡献出来容易吗。
我用了很好用。绝对支持MJ老师

**Comment by CoderMJLee** [comment]
淡定淡定，言论自由嘛，哈哈

**Comment by mzying2013** [comment]
Sorry,  是我太激动   没有足够理解MJRefresh
我上面的并不是针对任何人，只是加班调试了很久   然后解决了bug的肆嚎... 
请理解
