### ISSUE TITLE
MJRefresh  基类 里面的 beginRefreshing 方法最后调用  [self setNeedsDisplay]; why??

### ISSUE THREAD

**Issue by housenkui** [CoderMJLee/MJRefresh#890]
MJRefresh  基类 里面的 beginRefreshing 方法最后调用  [self setNeedsDisplay]; 我觉得不对因为图形已经画好了，应该调用[self setNeedsLayout]；

**Comment by CoderMJLee** [comment]
跟图形没有关系哈，这个方法在那个位置是用来解决控制器切换相关问题的
