### ISSUE TITLE
在执行刷新动作的时候,切换tab再切回来,刷新头回不去

### ISSUE THREAD

**Issue by XHJiang** [CoderMJLee/MJRefresh#892]

**Comment by sun8801** [comment]
把mjrefreshheader.m中
- (void)scrollViewContentOffsetDidChange:(NSDictionary *)change方法中的
if(self.window == nil) return；注释掉应该没问题了

**Comment by XHJiang** [comment]
谢谢

**Comment by ShenYj** [comment]
试一下

**Comment by suxiaoyao** [comment]
遇到同样的问题，总不能每次重新pod都去改代码吧？希望得到回复，应该怎么解决？

**Comment by hangshaoSH** [comment]
一个界面上面有多个选择按钮  选择了都是自动下拉刷新  如果网速太慢  一直选择 下拉箭头和字就会一直往下走 如果清空数组 还会出现闪退

**Comment by sjjvenu** [comment]
`if (self.tableView.mj_header.scrollViewOriginalInset.top > 0 && self.tableView.mj_header.state == MJRefreshState.idle) {
            let oldContentInset = self.tableView.contentInset;
            self.tableView.contentInset = UIEdgeInsets.init(top: 0, left: oldContentInset.left, bottom: oldContentInset.bottom, right: oldContentInset.right);
        }
`
我是这样解决的，在viewwillappear里面加这段代码，需要判断下当前状态，直接设置成为会把上拉刷新给移到屏幕外了

**Comment by myDonghao** [comment]
self.edgesForExtendedLayout = UIRectEdgeNone;

**Comment by leirenbaobao** [comment]
why remove 'if(self.window == nil)' can fix this problem？

**Comment by Yulei-Duan** [comment]
why remove 'if(self.window == nil)' can fix this problem？ 同问

**Comment by AAChartModel** [comment]
虽然临时解决了问题,但总归不是完美的方案啊,话说李明杰老师为毛不在 pod 的文件中改一下呢?

**Comment by sun8801** [comment]
因为当当前VC不可见时，view.widonw 会为nil,所以代码就不会继续执行复原操作。

**Comment by sun8801** [comment]
因为当当前VC不可见时，view.widonw 会为nil,所以代码就不会继续执行复原操作。
