### ISSUE TITLE
下拉刷新偶尔会出现位置偏移，也就是最近刷新时间的文字会露出来，这是为何

### ISSUE THREAD

**Issue by ZFKK** [CoderMJLee/MJRefresh#893]
采用的是
 _MyTable.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingTarget:self refreshingAction:@selector(loadMoreDate)];
  _MyTable.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [self loadNewData];
    }];

**Comment by wxwldu** [comment]
我也是出现了偏移，使劲往下拉才显示文字，有解决吗？

**Comment by ZFKK** [comment]
好尴尬，网上有的资料说block效果会好些，但是我没发现，另外，现在就是在scrollView减速结束时，判断偏移量来修正，但是效果不太好，所以。。。

**Comment by ZFKK** [comment]
我的是位置偏下，而不是偏上

**Comment by wenhao-fly** [comment]
我也这问题

**Comment by sun8801** [comment]
可以看下issue#892的回答，可能是那个问题
