### ISSUE TITLE
iOS10未设置语言时，国际化方法崩溃

### ISSUE THREAD

**Issue by clguoguo** [CoderMJLee/MJRefresh#894]
MJ老师，iOS10默认语言为“en”, 在MJRefreshComponent的方法：- (NSString *)localizedStringForKey:(NSString *)key withDefault:(NSString *)defaultString会发生crash,加个判断就好了 if (range.location != NSNotFound) {
                language = [language substringToIndex:range.location];
            }
老师抽空fix下哈。

**Comment by CoderMJLee** [comment]
之前应该解决了哈，谢谢提醒
