### ISSUE TITLE
使用addChildViewController其中的下拉刷新会多64的位移

### ISSUE THREAD

**Issue by Jorye** [CoderMJLee/MJRefresh#895]
下拉刷新到64的位置，就会跳动一下多了64的位移。不使用addChildViewController，直接写在页面不会出现这个问题。

**Comment by HsuBob** [comment]
请问你解决了吗

**Comment by youkiC** [comment]
那个页面用到了，另一个人写的“基础页面框架”，最后没使用那个“基础页面框架“才搞定。

**Comment by wolfcon** [comment]
能给出 Demo 吗?
