### ISSUE TITLE
tableview 下拉 和状态栏scrollsToTop 导致界面空白

### ISSUE THREAD

**Issue by menhui222** [CoderMJLee/MJRefresh#898]
//tableview设置 contentInset = UIEdgeInsetsMake(44 , 0, 64, 0)点击下拉的时候回调的瞬间 在点击 状态栏scrollsToTop
导致出现列表卡住  点击一下 界面就可以回到头部了

**Comment by Larrycal** [comment]
我也遇到了这个问题，请问你找到问题的原因了吗？
