### ISSUE TITLE
content 无限插入 mj_header 的高度

### ISSUE THREAD

**Issue by echolife** [CoderMJLee/MJRefresh#899]
很多情况下 我们需要结束当前的刷新 变更请求条件
1.如果安装以下操作 contentinset 的top 会 成倍增加
[self.tableView.mj_header endRefreshing];
 [self.tableView.mj_header beginRefreshing];
2.如果不结束上一次的刷新 直接 
 [self.tableView.mj_header beginRefreshing];
发现 快速切换条件调用以上方法 会导致 block不会调用

**Comment by ioswangpengwei** [comment]
if ([self.myTableView.mj_header isRefreshing]) {
        
        [self.myTableView.mj_header endRefreshing];
        [self.myTableView setContentInset:  ];
    }
