### ISSUE TITLE
自定义HeaderView 位置错误？

### ISSUE THREAD

**Issue by 438810364** [CoderMJLee/MJRefresh#90]
MJ哥：自定义tableView headerView的时候，下拉刷新时headerView位置错误，刷新完恢复正常，这个有办法解决吗？

**Comment by CoderMJLee** [comment]
如果是Section Header，这个不好解决哦，苹果自带的UIRefreshControl也会出现这样的情况。除非你把HeaderView放到Cell里面去

**Comment by 438810364** [comment]
嗯，好吧，谢谢了，收到你的回复很高兴

发自我的 iPhone
