### ISSUE TITLE
小码哥，你好。我遇到contentoffset.y值不连贯的问题。

### ISSUE THREAD

**Issue by PrismXX** [CoderMJLee/MJRefresh#900]
比如：在下拉刷新的时候，下拉到contentoffset.y的值为-300，这时候手松开,mjrefresh会显示正在刷新，contentoffset.y的值会直接跳到-54（header的默认高度），刷新完成后，contentoffset.y的值直接跳到0。获取到的值不连贯，不会像原来tableview那样-300...-250...-190.....0这样。。。我是希望可以通过获取到的contentoffset,y做一些动画的，请问该如何解决，谢了。

**Comment by CoderMJLee** [comment]
应该自定义刷新控件哈，参考MJDIYHeader，重写setPullingPercent:和setState:方法应该可以满足你的需求了

**Comment by PrismXX** [comment]
我试试，谢谢回复。
