### ISSUE TITLE
SOS！！！刷新的问题

### ISSUE THREAD

**Issue by NSObject-RC** [CoderMJLee/MJRefresh#901]
用的 【MJRefreshNormalHeader headerWithRefreshingBlock】，设置了进界面就自动刷新：beginRefreshing，但是一进界面 head 和 foot 会同时出来，如果不加self.tableView.mj_footer也没问题。而且如果用16年的MJ库，代码不变是没问题的。git最新的就有这个问题了？求解

**Comment by SunXu231** [comment]
@NSObject-RC  你可以看他的 demo 里面实现的方式，我是刚开始的时候进去将 footer 隐藏了，这样就不会显示了。看看 demo ，一般的问题都能够解决掉。

**Comment by NSObject-RC** [comment]
我看了，，也进来就直接隐藏footer，，直接设置进去就开始刷新beginRefreshing，还是会出来，用16年的MJ就不会有任何问题？不知道为什么

**Comment by SunXu231** [comment]
@NSObject-RC  你用的是  MJRefreshBackNormalFooter 这个类创建的吗？我之前就是疏忽了这个类的问题，发现才会那样的。

**Comment by NSObject-RC** [comment]
MJRefreshAutoNormalFooter 我用的是这个类，，而且如果我不添加footer刷新就不会出来，，

**Comment by SunXu231** [comment]
@NSObject-RC  你换成我写的那个类进行实例化操作，你看看能不能好？

**Comment by NSObject-RC** [comment]
用这个MJRefreshBackNormalFooter类是可以的，但是这个不是我想要的效果，这个类还需上拉一段距离松开才会加载更多数据，，我想要的是MJRefreshAutoNormalFooter类的效果，只要上拉一小段就直接刷新加载更多数据

**Comment by SunXu231** [comment]
哦哦  明白了，好吧。那就只能好好研究研究了，看看 demo 里面有没有你想要的吧，仔细检查一下自己的代码吧

**Comment by Arthurcsh** [comment]
有个悬浮的UITableHeaderView，上拉时部分置顶，发现“加载更多”失效了，这个怎么处理？

- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section {
    return 90;
}
- (void) scrollViewDidScroll:(UIScrollView *)scrollView {
    if (scrollView == self.tableView) {
        CGFloat sectionHeaderHeight = 45;
        if (scrollView.contentOffset.y<=sectionHeaderHeight&&scrollView.contentOffset.y>=0) {
            scrollView.contentInset = UIEdgeInsetsMake(-scrollView.contentOffset.y, 0, 0, 0);
        } else if (scrollView.contentOffset.y>=sectionHeaderHeight) {
            scrollView.contentInset = UIEdgeInsetsMake(-sectionHeaderHeight, 0, 0, 0);
        }
    }
}

**Comment by CoderMJLee** [comment]
@Arthurcsh 问题解决了么
