### ISSUE TITLE
UICollectionView的刷新视图挡住Cell

### ISSUE THREAD

**Issue by StoryOfLittleDuck** [CoderMJLee/MJRefresh#903]
<img width="318" alt="31a8e274-1518-4a49-bd73-c820aa556f6e" src="https://cloud.githubusercontent.com/assets/19772620/25985937/d762b620-371f-11e7-9d07-9b57e58e092f.png">
<img width="347" alt="66dc9835-da40-43de-abda-c76d959e09a4" src="https://cloud.githubusercontent.com/assets/19772620/25985936/d72e59ca-371f-11e7-86f0-62449b97fcc5.png">
<img width="301" alt="0702b4e5-c0d4-4934-a2b8-551e724d6067" src="https://cloud.githubusercontent.com/assets/19772620/25985935/d71c3376-371f-11e7-9888-e92f4b732c40.png">
<img width="176" alt="3916070d-2703-456f-b850-617c9e5ca1b9" src="https://cloud.githubusercontent.com/assets/19772620/25985938/d76b12a2-371f-11e7-9df2-efe38ea0ab93.png">
tableView的刷新视图在tableView和Cell之间，但collectionView的刷新视图在cell上面，导致遮挡collectionView，有什么办法解决嘛？

**Comment by zhujieshan** [comment]
你好 你的解决了吗? 我也是用来UICollectionView 然后刷新视图会在最上层 会遮挡collectionView

**Comment by StoryOfLittleDuck** [comment]
没，这个问题我还存在，希望有大神可以看到，帮忙解决。

**Comment by wolfcon** [comment]
方便提供一份 Demo 吗?
