### ISSUE TITLE
杰哥 下拉刷新之后回不去了

### ISSUE THREAD

**Issue by githubofsanren** [CoderMJLee/MJRefresh#907]
点一个tabbar的选项，做了下拉刷新，也许是网络请求慢吧，请求还没回来，又点了另一个tabbar的选项，再回到上一个，刷新就回不去了

**Comment by xhp281** [comment]
我也遇到了，解决了没。

**Comment by githubofsanren** [comment]
没有啊




------------------ 原始邮件 ------------------
发件人: "海贼王";<notifications@github.com>;
发送时间: 2017年7月12日(星期三) 中午1:37
收件人: "CoderMJLee/MJRefresh"<MJRefresh@noreply.github.com>; 
抄送: "伞下好乘凉"<1002059187@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [CoderMJLee/MJRefresh] 杰哥 下拉刷新之后回不去了 (#907)




我也遇到了，解决了没。

**Comment by xhp281** [comment]
https://github.com/CoderMJLee/MJRefresh/issues/892   这个完美解决。

**Comment by IPOSDai** [comment]
为什么我注册了，还是没有解决该问题

**Comment by IPOSDai** [comment]
注释

**Comment by githubofsanren** [comment]
我也遇到同样的问题，下拉之后回不去了

**Comment by githubofsanren** [comment]
下拉刷新之后  还是回不去

**Comment by githubofsanren** [comment]
如果说UIScrollView加了UITableView 是不是导致下拉刷新回不去的原因呢
