### ISSUE TITLE
MJRefresh不停上拉加载的问题

### ISSUE THREAD

**Issue by RQBian** [CoderMJLee/MJRefresh#909]
问题还存在，依旧不停进行上拉加载操作。

解决方法：把self.tableView.estimatedRowHeight=150.0f;150这个数值是你cell的平均高度，如果estimatedRowHeight设置非常小，MJRefresh的KVO会监听错误的contentoffset，造成不停进行上拉加载操作。

解决问题的过程：首先我反复的验证我代码逻辑，确保代码逻辑无误。之后我把重点代码打断点一行一行debug，因为毕竟眼睛验证过的逻辑容易出现漏洞，再确保没有循环调用上拉操作方法的情况下。我怀疑是工程中有其他类监听了contentoffset，于是看MJRefresh源码，KVO中监听了contentoffset contentsize refreshstate三个属性，监听方法打断点调试，发现每次调用上拉操作后，监听者又监听到contentoffset的变化，说明contentoffset还是处于变化当中，而estimatedRowHeight预估行高后算出一个contentoffset值，cell以实际大小布局后，contentoffset又会算出一个值，这样KVO就会监听到contentoffset的变化，就会去调用上拉操作的接口，加载出来的数据会去填充tableview，estimatedRowHeight会预估行高算出一个contentoffset，之后cell会已实际大小布局，contentoffset又会算出一个值，之后就循环开来。

--------------------------------
通过以上方式加大了预估值的大小, 倒是不再不停加载了,但是导致tableview在滑动的时候卡顿!
往指点怎么解决,谢谢!!!

**Comment by wolfcon** [comment]
Duplicate of #1009
