### ISSUE TITLE
strong or weak

### ISSUE THREAD

**Issue by f33chobits** [CoderMJLee/MJRefresh#91]
J兄，我看UIScrollview+MJRefresh.h里面header用strong声明的，.m里面用runtime设置了assign。子View的生命周期归父管，所以assign肯定是对的，但是我想确定一下，在外面声明的时候却声明成strong，意思是不是告诉用这个lib的人不要操心那个header的引用计数问题，‘这问题不用你管’，是这个意思吗？不知我表达的是否清楚

**Comment by CoderMJLee** [comment]
外面的strong仅仅是提醒开发者，传进来的header对象内部会通过某些手段保留这个对象，外面就不用使用强引用保留它了

**Comment by f33chobits** [comment]
额，就是想问这个，看来我表达能力还有待提高。。。

**Comment by broccolii** [comment]
@CoderMJLee 
为什么内容不使用OBJC_ASSOCIATION_RETAIN 来修饰呢
