### ISSUE TITLE
Header 中的 endRefreshing 方法探讨

### ISSUE THREAD

**Issue by NJHu** [CoderMJLee/MJRefresh#910]
1,情景描述:  2个 tableView 联动请求数据的时候, 左边的 tableView 是静态数据, 刷新右边的 tableView, 
2 问题:   当点击左侧的 cell 速度`**很快**`的时候, 右边tableView 的刷新状态没有结束, 虽然写了结束刷新的代码

```
    // 结束刷新状态
    ![self.tableView.mj_header isRefreshing] ?: [self.tableView.mj_header endRefreshing];
```

3 导致: 紧接着 tableView 的 header`beginRefreshing`接下来没有调用 `executeRefreshingCallback` 的方法, 接着就不会调用项目中的网络请求代码

4, 选中刷新代码如下: 

```
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    
    if (tableView == self.leftTagTableView) {
        
    // 结束刷新状态
    ![self.tableView.mj_header isRefreshing] ?: [self.tableView.mj_header endRefreshing];

        // 清除上一个数据
        [self.tableView reloadData];

        if (左侧对应右边的数据.count == 0) {

            [self.tableView.mj_header beginRefreshing];

        }
    }
}

```

5, 解决
方案一: 当我尝试把您代码里边的这个地方修改后, 就解决问题了, 

```
#pragma mark - 公共方法
- (void)endRefreshing
{

// 注释掉   dispatch_sync(dispatch_get_main_queue(), ^{

        NSLog(@"MJRefreshStateIdleMJRefreshStateIdleMJRefreshStateIdleMJRefreshStateIdleMJRefreshStateIdleMJRefreshStateIdle");
        self.state = MJRefreshStateIdle;

//  注释掉  });
}

```

方案二: 或者把在结束刷新的时候改变下 State = MJRefreshStateIdle, 也可以解决

```
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    
    if (tableView == self.leftTagTableView) {
        
    // 结束刷新状态
    ![self.tableView.mj_header isRefreshing] ?: [self.tableView.mj_header endRefreshing];
// 改变state
    self.tableView.mj_header.state = MJRefreshStateIdle;

        // 清除上一个数据
        [self.tableView reloadData];

        if (左侧对应右边的数据.count == 0) {

            [self.tableView.mj_header beginRefreshing];

        }
    }
}

```

6, 为什么Header 中的 endRefreshing 没有改变 header 的 State为 MJRefreshStateIdle

**Comment by ieliwb** [comment]
兄弟解决了吗？UIScrollView+EmptyDataSet 和这个一起，endRefreshing不是实时的太蛋痛了
- (BOOL)emptyDataSetShouldDisplay:(UIScrollView *)scrollView
{
    return (self.tableView.mj_header.isRefreshing) ? NO : YES;
}

**Comment by ieliwb** [comment]
[self.tableView.mj_header endRefreshingWithCompletionBlock:^{
        [self.tableView reloadEmptyDataSet];
    }];
这个貌似可以解决

**Comment by NJHu** [comment]
![image](https://user-images.githubusercontent.com/18454795/51960546-6765df00-2494-11e9-8e61-3e7720e0483d.png)
这样也可以

**Comment by wolfcon** [comment]
不要直接修改 state. 

使用如下代码
```swift
tableView.mj_footer.endRefreshingWithNoMoreData()
```
#1258 #1020
