### ISSUE TITLE
MJRefresh 的下拉刷新与下拉放大如何解决在放大视图的底部出现空白。

### ISSUE THREAD

**Issue by IPOSDai** [CoderMJLee/MJRefresh#911]

**Comment by lengain** [comment]
我也遇到空白的问题了额

**Comment by CoderMJLee** [comment]
可以截图看看么

**Comment by IPOSDai** [comment]
我现在的已经被我解决了，不知道现在的新版本会出现这个问题不，您可以试试，在创建一个带有两三个tabbar的项目，每个tabbar控制器下的根控制器使用UITableView，添加好mj_header，向下拉拉住不放，另外一只手点击其他的tabbar，然后回来，您就能看到这个bug了。不知道现在的版本有没有。
