### ISSUE TITLE
iOS11适配问题

### ISSUE THREAD

**Issue by xhp281** [CoderMJLee/MJRefresh#913]
iOS 11 tableview顶部会有个空白，mj大大求更新。

**Comment by zhangliukou** [comment]
iOS11上这个问题和MJRefresh应该没什么关系

**Comment by leonylcatwork** [comment]
参考 http://www.jianshu.com/p/d4a17c32abdf
看 UIScrollView 部分.

设置 contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever

**Comment by pupboss** [comment]
@leonylcatwork 这个思路。。。苹果默认推荐自动计算 inset，最好还是用，用完之后发现的问题是下拉刷新，缩回去之后，这个时候布局是不对的，然后 cell 会自己慢慢下落一段距离，这个时候布局就对了，感觉还是 MJRefresh 这个库在布局需要改进。

另外，在 iPad 转屏的时候，如果不做特殊处理，下拉刷新的位置也不是靠中间，可能改写 MJRefresh 的布局才能解决这些问题

**Comment by xhp281** [comment]
@pupboss 感觉 mj 已经弃坑了。

**Comment by CoderMJLee** [comment]
已经兼容iOS11了，试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry

**Comment by pupboss** [comment]
@CoderMJLee 先谢谢明杰前辈，注意身体

**Comment by xhp281** [comment]
@CoderMJLee 卧槽惊现 mj 大大，只要你还在就好。创业不容易，多加注意身体。

**Comment by CoderMJLee** [comment]
大家都要注意身体
