### ISSUE TITLE
表没有数据时，footerView显示在界面上

### ISSUE THREAD

**Issue by zouwl** [CoderMJLee/MJRefresh#915]
当TableView没有数据时，headerview和footerview会靠在一起，并且显示在界面上。建议修改如下：
- (void)scrollViewContentSizeDidChange:(NSDictionary *)change {
    [super scrollViewContentSizeDidChange:change];
    // 设置位置
    if(self.scrollView.mj_contentH < self.scrollView.bounds.size.height) {
        self.mj_y = self.scrollView.bounds.size.height;
    }  else {
        self.mj_y = self.scrollView.mj_contentH;
    }
}

修改前的代码如下：
- (void)scrollViewContentSizeDidChange:(NSDictionary *)change {
    [super scrollViewContentSizeDidChange:change];
    // 设置位置
    self.mj_y = self.scrollView.mj_contentH;
}

**Comment by haijiaoliuhao91** [comment]
/** 自动根据有无数据来显示和隐藏（有数据就显示，没有数据隐藏。默认是NO） */
@property (assign, nonatomic, getter=isAutomaticallyHidden) BOOL automaticallyHidden;
这个属性可以设置footer
