### ISSUE TITLE
mj_footer

### ISSUE THREAD

**Issue by xqwIOS** [CoderMJLee/MJRefresh#917]
使用上拉加载加载的时候 第一次上拉加载 可以加载数据 但是我再次上拉的时候 不走block里的请求方法了

**Comment by xqwIOS** [comment]
- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.InvestTableView.delegate = self;
    self.InvestTableView.dataSource = self;
    self.InvestTableView.tableFooterView = [[UIView alloc] init];
    self.automaticallyAdjustsScrollViewInsets = NO;
    
    investInfoArray = [[NSMutableArray alloc] init];
    
    __weak typeof (self) weakSelf = self;
    
    self.InvestTableView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        currentIndex++ ;
        [weakSelf getData:currentIndex ];
    }];
    self.InvestTableView.mj_footer.automaticallyHidden = YES;
    [self refreshData];
}

**Comment by luojc0517** [comment]
我也遇到同样的问题

**Comment by lovisty** [comment]
I have the same problem

**Comment by FrankSwift** [comment]
有人解决了吗 我也遇到了
