### ISSUE TITLE
关于使用MJRefreshAutoNormalFooter

### ISSUE THREAD

**Issue by mushao1990** [CoderMJLee/MJRefresh#919]
比如有两页数据，下滑到最底部（此时提示没有更多数据加载），然后push到其他界面， 当从其他界面返回，通过reloadRowsAtIndexPaths刷新最底部的一些行的时候，会出现footer控件先上移然后消失的状况。
我看了之前有人提出过这个问题（他的情况是deleteRow），但是老师没有回答，希望能帮忙解答一下，谢谢！

**Comment by wolfcon** [comment]
Duplicate of #818
