### ISSUE TITLE
MJ你好，如果箭头回去的方向能和下来的方向相反，效果是否更好

### ISSUE THREAD

**Issue by JFwen** [CoderMJLee/MJRefresh#92]
你下拉的时候是顺时针下来，回去的时候也是顺时针，是否对用户体验不好，如果下来的时候转89.9度，回去的时候转90.1度(这两个数字只是举个例子，加起来180度就可以，接近90度就可以)，就能按原来的方向回去了。

**Comment by CoderMJLee** [comment]
这个问题已经从1.0版本开始调整过来了哈
