### ISSUE TITLE
ios11下拉刷新会跳动

### ISSUE THREAD

**Issue by ryanzhuang** [CoderMJLee/MJRefresh#922]
暂时的解决方案先这样解决：
if (@available(iOS 11.0, *)) {
        self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        self.tableView.contentInset = UIEdgeInsetsMake(64, 0, 0, 0);
    } else {
        // Fallback on earlier versions
    }

**Comment by XuYang8026** [comment]
感谢楼主分享解决方案，但此方案美中不足的是，滚动条会被NavigationBar和TabBar遮住，完美解决方案：
```
       if (@available(iOS 11.0, *)) {
            _tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
            _tableView.contentInset = UIEdgeInsetsMake(64, 0, 49, 0);
            _tableView.scrollIndicatorInsets = _tableView.contentInset;
        }
```
[展开全部](http://www.jianshu.com/p/a6e5cc20a008)

**Comment by xd54622** [comment]
这里对iPhone X的适配还是有问题啊，因为iPhone X的导航栏高度不是64，难道要再根据不同机型来调整不同的ContentInset吗？

**Comment by XuYang8026** [comment]
[适配 iOS11 & iPhone X](http://www.jianshu.com/p/a6e5cc20a008)

**Comment by CoderMJLee** [comment]
谢谢大家的用心。目前MJRefresh已经兼容iOS11了，试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry

**Comment by wolfcon** [comment]
Duplicate of #1009
