### ISSUE TITLE
小码哥教育师资真垃圾

### ISSUE THREAD

**Issue by honkycoder** [CoderMJLee/MJRefresh#925]

**Comment by EricYellow** [comment]
在这说人家教育不好,可不是个好行为

**Comment by HjExplorer** [comment]
MJ无可厚非技术是不错，但是开的班确实都是坡脚老师，有点圈钱的味道
时间长了，什么问题都暴露出来了~人的良心也是一样
这样的开班本质和电信诈骗是没有任何区别的
