### ISSUE TITLE
3.1.12版！在swift中引用不到header和footer类

### ISSUE THREAD

**Issue by kai120897660** [CoderMJLee/MJRefresh#927]
我在OC和swift桥接文件里引用了#import <MJRefresh/MJRefresh.h>却在swift中报了找不到类的错误
![image](https://user-images.githubusercontent.com/16075552/28455158-a0592054-6e30-11e7-81f5-55a5b710f4f9.png)
这种问题怎么解决！

**Comment by linbx08** [comment]
swift中3.1.12是不用桥接文件了 导入就可以直接用了 @kai120897660

**Comment by chaoyueshan1012** [comment]
同样遇到，是什么原因，有解决方案吗

**Comment by wolfcon** [comment]
为什么要桥接?

```swift
@import MJRefresh
```
