### ISSUE TITLE
下拉的时候按住不放,  去点击TabBar上的其他选项 再点击回去,  下拉控件回下移,然后每次重复操作, 回叠加,刷新控件顶部空白, 每次增加64

### ISSUE THREAD

**Issue by FSAnonymous** [CoderMJLee/MJRefresh#932]
下拉的时候按住不放,  去点击TabBar上的其他选项 再点击回去,  下拉控件会下移,然后每次重复操作, 会叠加,刷新控件顶部空白, 每次增加64

**Comment by haijiaoliuhao91** [comment]
#892这个应该可以解决

**Comment by haijiaoliuhao91** [comment]
#892 这个方法可以解决

**Comment by IPOSDai** [comment]
请问你们是如何解决的啊？好像#892这样做也没法解决问题

**Comment by IPOSDai** [comment]
我查看了一下，每次view出现的时候scrollViewOriginalInset在改变，特别是使用容器视图的自控制器的tableView的mj_header的scrollViewOriginalInset在累加，在这个时候#892注释掉也没有用，暴力的方法是在viewWillAppear的时候，self.tableView.contentInset = UIEdgeInsetsZero,这样有个问题是如果还在刷新的动画直接被干掉，当然也可以通过判断来设置这个

**Comment by Andrewmika** [comment]
可以在viewWillAppear的时候添加如下代码解决
    if (self.tableView.mj_header.scrollViewOriginalInset.top > 0) {
        self.mainTableView.contentInset = UIEdgeInsetsZero;
    }

**Comment by IPOSDai** [comment]
这么做好像，如果当前页面正在刷新的话，你这么做是有问题的， 会强制关闭当前的刷新。最好判断的条件加上self.tableView.mj_header.state 是空闲的
