### ISSUE TITLE
triggerAutomaticallyRefreshPercent参数设置为-5，会连续刷新两次

### ISSUE THREAD

**Issue by wangxiGitHub** [CoderMJLee/MJRefresh#933]
triggerAutomaticallyRefreshPercent默认为1，控件出现是开始刷新，我如果想提前开始刷新把它设为负数比如-5，确实能实现效果，会出现连续刷新两次的问题，看源码解决了松手重复刷新的问题，这个问题要怎么解决，或者设置别的属性达到提前一段距离开始刷新的效果，谢谢

**Comment by ToLengSon** [comment]
自己重写下MJRefreshFooter的beginRefreshing方法，然后里面判断下是offsetY是否大于0，如果满足就调用super

**Comment by wolfcon** [comment]
设置为0.5/0.3
