### ISSUE TITLE
MJRefreshAutoFooter 在tableView行数很少的情况下不在底部，附临时解决方案

### ISSUE THREAD

**Issue by RITL** [CoderMJLee/MJRefresh#938]
MJ老师你好，最近在使用`MJRefreshAutoFooter`的时候发现了一个问题，如果`UITableView`的行数过少会出现如下情况：

<img height = 320, src="http://ov65indxb.bkt.clouddn.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-08-24%20%E4%B8%8A%E5%8D%8810.58.56.png"></img>

初步定位在`MJRefreshAutoFooter.m : 58`中发生contentSize变化的方法如下:
```
- (void)scrollViewContentSizeDidChange:(NSDictionary *)change
{
    [super scrollViewContentSizeDidChange:change];
    
    // 设置位置
    self.mj_y = self.scrollView.mj_contentH;
}
```

修改为下面就可以确保footer在tableView的下方：
```
- (void)scrollViewContentSizeDidChange:(NSDictionary *)change
{
    [super scrollViewContentSizeDidChange:change];
    
    CGFloat mj_contentH = self.scrollView.mj_contentH;
    CGFloat mj_minHeight = self.scrollView.bounds.size.height;
    
    // 设置位置
    self.mj_y = MAX(mj_contentH, mj_minHeight);
}
```

不知道大家遇到过没有，期待您的回复😀

**Comment by linbx08** [comment]
hello, 我觉得这个问题很容易解决 
你叫你们家后台给你一个类似total_entities的字段,表面你们这个列表有多少个count
然后和你数据源的count数对比 如果你数据源的count >= 这个total 那么就隐藏这个顶部view
示例代码如下:
`let total = model.data?.total_entities ?? 0
`
`self.tableView.mj_footer.isHidden = self.msgArr.count >= total`
希望能帮助到你

**Comment by RITL** [comment]
@linbx08  恩，谢谢你😀

**Comment by JsonKit** [comment]
MJRefreshBackFooter在行数很少的时候是在tableView底部,MJRefreshAutoFooter在行数很少的时候是在内容底部,个人觉得行数很少的时候再内容底部好看一点(个人观点,不喜勿喷)

**Comment by RITL** [comment]
@JsonKit 恩恩 ，没关系，是我想偷懒了，用一个自定义的footerView就好了，谢谢你😀
