### ISSUE TITLE
重大bug！！！！！！上拉加载的时候如果没有更多数据，用上次的数据刷新tableview 然后【self.tableView.mj_footer endRefreshing】后，回调将会多次调用

### ISSUE THREAD

**Issue by programer001** [CoderMJLee/MJRefresh#941]
self.tableView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        STRONG_SELF;
        [self loadNextPage];
   }];
   如题：没有更多数据的时候         [self loadNextPage]会无限执行，这么严重的bug，难道没人发现？很容易测试啊

**Comment by wys13114** [comment]
我也发现了一样的问题。。。

**Comment by zichenJack** [comment]
发现了, 所以做了一些处置. MJ 貌似生病了, 没有再更新这个框架了

**Comment by gongyucheng** [comment]
@zichenJack 请问如何处理的？

**Comment by happy2014** [comment]
@zichenJack  请问是如何处理的呢,我也出现了同样的问题,一天了都没有解决

**Comment by luran2358** [comment]
用代理试试, 别用block

**Comment by programer001** [comment]
回复楼上不知如何解决的同志。提供两种方式。1、手动判断没有更多数据的时候不要去刷新tableview
2、无更多数据的时候调用【self.tableView.mj_footer endRefreshingWithNoMoreData】 不要去用endRefreshing

**Comment by CoderMJLee** [comment]
@programer001 正解。近几个月身体抱恙，所以未及时更新，Sorry。目前的最新版本3.1.13已经兼容iOS11了
