### ISSUE TITLE
设置无更多数据

### ISSUE THREAD

**Issue by yuewenyan** [CoderMJLee/MJRefresh#944]
通过self.tableView.mj_footer.state = MJRefreshStateNoMoreData 设置无更多数据有时不起作用，有时是设置成功了但箭头还在没有隐藏，有时是正确的，页面初始化加载数据时没有刷新或加载操作设置可以成功，其他情况就不成功了，有人遇到这个问题了吗

**Comment by wolfcon** [comment]
不要直接修改 state. 

使用如下代码
```swift
tableView.mj_footer.endRefreshingWithNoMoreData()
```
#1258 #1020
