### ISSUE TITLE
使用MJRefreshBackNormalFooter出现了一个问题

### ISSUE THREAD

**Issue by CainLuo** [CoderMJLee/MJRefresh#946]
使用MJRefreshBackNormalFooter出现了一个问题, 当上拉加载更多的时候是正常的, 但如果上拉加载没有更多数据的时候, TableView就会中间就会跳断一下, 不知道MJ有没有邮箱, 有的话, 我可以发给你问题图

**Comment by 1506874981** [comment]
我也遇到这个问题了

**Comment by wolfcon** [comment]
Duplicate of #1009
