### ISSUE TITLE
设置uiscrollview原始位置为 负20 的时候，下拉刷新时 很小的距离就触发刷新了；

### ISSUE THREAD

**Issue by dengxingwen** [CoderMJLee/MJRefresh#948]
为了让uiscrollview从状态栏顶部也就是屏幕左上角开始布局uiscrollview，所以给uiscrollview设置的frame为：_contentScrollView = [[UIScrollView alloc] initWithFrame:CGRectMake(0, -20, SCREEN_WIDTH, SCREEN_HEIGHT-49+20)];

在添加了下拉刷新功能后，下拉的距离明显不够 就触发了；请问应该做哪些设置；
_contentScrollView.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        [self getNetData];
    }];
    
    [_contentScrollView.mj_header beginRefreshing];

**Comment by FunnyCoderWang** [comment]
running into the same question : )

**Comment by CoderMJLee** [comment]
设置一下scrollView的contentInset.top，让scrollView内容往下移动？

**Comment by FunnyCoderWang** [comment]
小马哥晚上好，我这里的场景是，导航视图控制中配置导航栏透明，然后调整*scrollview*的*contentInset*让内容融合在导航栏跟状态栏一起，目前refreshheader表现为稍微下拉就触发进入了**MJRefreshStatePulling**状态。大致看了可配置的选项没有有效线索。是使用方法不对吗？看起来要通过调整scrollViewContentOffsetDidChange内部实现来处理。

使用的是 3.1.12 版本。我有遗漏什么重要信息吗？

**Comment by FunnyCoderWang** [comment]
我这里通过设置自动调整滚动视图缩进为NO正常了。
if (@available(iOS 11.0, *)) {
        self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    } else {
        self.automaticallyAdjustsScrollViewInsets = NO;
    }
