### ISSUE TITLE
Masonry UITableViewAutomaticDimension 自适应cell高度 上拉加载会无限进行

### ISSUE THREAD

**Issue by RunerZhang** [CoderMJLee/MJRefresh#949]
使用Masonry自适应cell高度 
其中调用        
_listTable.estimatedRowHeight = 110;
_listTable.rowHeight = UITableViewAutomaticDimension;
上拉加载会无限进行 暂时没有找到解决办法

**Comment by SherlockQi** [comment]
请问解决了吗

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
