### ISSUE TITLE
第一次加入gifHeader，第二次再加入gifHeader，判断出现问题导致闪退

### ISSUE THREAD

**Issue by podywu** [CoderMJLee/MJRefresh#95]
在webView 的 scrollView 中，调用 addGifHeaderWithRefreshingBlock ,加入gifHeader ，webView刷新后由于根据加载url判断是否需要加入刷新，重新调用addGifHeaderWithRefreshingBlock，则出现闪退。

在 UIScrollView+MJRefresh.m 中

#pragma mark header
static char MJRefreshHeaderKey;
- (void)setHeader:(MJRefreshHeader *)header
{
    if (header != self.header) {
        [self.header removeFromSuperview];
        
        [self willChangeValueForKey:@"header"];
        objc_setAssociatedObject(self, &MJRefreshHeaderKey,
                                 header,
                                 OBJC_ASSOCIATION_ASSIGN);
        [self didChangeValueForKey:@"header"];
        
        [self addSubview:header];
    }
}

该方法中 header != self.header 判断有问题，应改为 ![header isEqual:self.header] 
麻烦看下这个问题

**Comment by podywu** [comment]
同时要如何判断gifHeader是否已存在，当webview中的scrollview已经加入gifHeader，重新判断gifHeader时，使用 
if(self.webView.scrollView.gifHeader == nil){ }  ， 闪退，

在 UIScrollView+MJRefresh.m 中

- (MJRefreshGifHeader *)gifHeader
{
    if ([self.header isKindOfClass:[MJRefreshGifHeader class]]) {
        return (MJRefreshGifHeader *)self.header;
    }
    
    return nil;
}

这里 [self.header isKindOfClass:[MJRefreshGifHeader class]]) ，报了EXC_BAD_ACCESS错误，麻烦查看下

**Comment by podywu** [comment]
以上判断gifHeader是否存在，改为 [self.webView.scrollView.gifHeader isEqual:nil] ,判断成功

**Comment by CoderMJLee** [comment]
如果重新添加header，可以考虑先[scrollView removeHeader];然后再addGifHeaderWith....。这样可以么？

**Comment by podywu** [comment]
使用[scrollView removeHeader]; 还是不行，同样在 header != self.header 报错

**Comment by CoderMJLee** [comment]
能否来个Demo看看

**Comment by podywu** [comment]
找到原因了，原来是 [scrollview.gifHeader removeFromSuper] 导致的问题，改为 [scrollView removeHeader]; 就可以。谢谢了

**Comment by CoderMJLee** [comment]
不客气哈
