### ISSUE TITLE
下拉刷新触发后 -(void)scrollViewDidScroll:(UIScrollView *)scrollView 代理方法失效

### ISSUE THREAD

**Issue by halohily** [CoderMJLee/MJRefresh#951]
项目中有根据 -(void)scrollViewDidScroll:(UIScrollView *)scrollView 代理方法实现的动态效果，下拉刷新触发后，不松手继续上下滑动页面，scrollView.contentOffset.y 值会固定在初始值，请问这里该怎么处理呢

**Comment by CoderMJLee** [comment]
好像没遇到此情况哈，只要你滚动了scrollView，scrollViewDidScroll就会调用的，不会因为刷新控件的存在而影响
