### ISSUE TITLE
pull offset is not right in iPhone X

### ISSUE THREAD

**Issue by ruomu023** [CoderMJLee/MJRefresh#952]
In iPhone X simulator,first show ViewController ,the tableView's offset is not correct.

![simulator screen shot - iphone x - 2017-09-13 at 17 00 44](https://user-images.githubusercontent.com/25837071/30368871-1ee4689a-98a5-11e7-9cab-50fbced29af9.png)

**Comment by CoderMJLee** [comment]
I had it fixed just now.
