### ISSUE TITLE
iOS11: push back后，collectionView的contentOffset会变

### ISSUE THREAD

**Issue by tounaobun** [CoderMJLee/MJRefresh#954]
push一个vc，然后pop回去后，collectionView的内容会往上移动一段距离，貌似就是tabBar的高度。iOS10没问题。

**Comment by tanpengsccd** [comment]
iOS11  tableView 也有类似问题。

**Comment by jprothwell** [comment]
同样啊.楼上老哥有解决的没?

**Comment by dengshunlai** [comment]
这个不是MJRefresh的问题，我也遇到类似的问题：http://www.cocoachina.com/bbs/read.php?tid-1725965.html 大家一起来讨论讨论

**Comment by tanpengsccd** [comment]
[UIScrollView appearance].contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever; 这个不起作用的

**Comment by tounaobun** [comment]
`    if (@available(iOS 11.0, *)) {
        [UIScrollView appearance].contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    } else {
        // Fallback on earlier versions
    }`
