### ISSUE TITLE
iOS11  上啦加载，停不下来了

### ISSUE THREAD

**Issue by pengGitHubUp** [CoderMJLee/MJRefresh#955]
iOS11  上啦加载，停不下来了，[tableView.mj_header endRefreshing]调用后，
//上拉加载
        MJRefreshAutoNormalFooter *footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
            // 网络请求
        }];
 block里的方法依旧被调用；
测试设备：1: iPhoneX（iOS11）模拟器
                  2:iPhone7 （iOS11）

**Comment by happy2014** [comment]
我也遇到了同样的问题,而且reloaddata之后,tableview的偏移量不知道是不是变了,导致又上拉加载了

**Comment by Clemmie-L** [comment]
项目有个界面的情况同上；还有一个界面：上拉一次连续被调用2次刷新，但是不会滚到最低部；

**Comment by Clemmie-L** [comment]
以上是在tableView出现的。第三个界面用collectionView做的，是正常的。

**Comment by JsonKit** [comment]
试试加入下面这3行代码
`self.tableView.estimatedRowHeight = 0;
    self.tableView.estimatedSectionHeaderHeight = 0;
    self.tableView.estimatedSectionFooterHeight = 0;`
iOS11默认开启self-sizing,所以在tableView reload之后contentSize会产生突变,对于代码中监听contentSize的地方可能会产生影响

**Comment by CoderMJLee** [comment]
已经兼容iOS11了，试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry

**Comment by pengGitHubUp** [comment]
ok
