### ISSUE TITLE
关于iOS11 上下拉刷新无法返回的问题，不关MJRefresh的事，解答

### ISSUE THREAD

**Issue by Rogue24** [CoderMJLee/MJRefresh#956]
iOS11弃用了automaticallyAdjustsScrollViewInsets属性，新增contentInsetAdjustmentBehavior来替代它，不想系统帮我们自动设置边距则要在iOS11中加上这句 scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

**Comment by csdwd** [comment]
Very good!👍

**Comment by csdwd** [comment]
`if #available(iOS 11.0, *) {
            collectionView.contentInsetAdjustmentBehavior = .never
        } else {
            // Fallback on earlier versions
        }`

swift中添加改行代码

**Comment by xd54622** [comment]
这样改的话，导航栏就要挡住tableview了。而设置contentInset的话，虽然可以解决遮挡问题，但是iPhone X的导航栏高度又不一样，又要根据机型来设置不同的contenInset，感觉不是很合理。

**Comment by Rogue24** [comment]
iPhoneX 就是苹果告诉我们状态栏和tabbar高度不要写死，要动态获取

**Comment by SanlinBlackball** [comment]
那是不是不能设置tableView为self.view.bounds

**Comment by Rogue24** [comment]
可以，但是contentInset要设置正确

**Comment by CoderMJLee** [comment]
@Rogue24 谢谢你的热心。
我也尝试让MJRefresh兼容iOS11了，大家可以试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry

**Comment by Rogue24** [comment]
绝对要保重身体啊mj哥！你可是我偶像呀
________________________________
发件人: M了个J <notifications@github.com>
发送时间: 2017年9月27日 9:53:31
收件人: CoderMJLee/MJRefresh
抄送: JianPingZhou; Mention
主题: Re: [CoderMJLee/MJRefresh] 关于iOS11 上下拉刷新无法返回的问题，不关MJRefresh的事，解答 (#956)


@Rogue24<https://github.com/rogue24> 谢谢你的热心。
我也尝试让MJRefresh兼容iOS11了，大家可以试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry

―
