### ISSUE TITLE
mj用weakself的时候 页面释放掉后返回崩溃

### ISSUE THREAD

**Issue by MarsLeo** [CoderMJLee/MJRefresh#957]
__weak typeof(self) weakSelf = self;
    self.mTableView.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        weakSelf.PageIndex = 1;
        [weakSelf GetProductDataAnalysisFromServer:NO];
    }];
self.mTableView.mj_header = [MJRefreshBackNormalFooter footerWithRefreshingBlock:^{
        [weakSelf GetProductDataAnalysisFromServer:NO];
    }];
这样的用法点击返回按钮后回崩溃

**Comment by sunzhongliangde** [comment]
你应该看看崩的位置是在哪里，是自己写的代码还是mj源码里面

**Comment by MarsLeo** [comment]
直接就崩溃到main函数啦
