### ISSUE TITLE
iOS11下iPhoneX的MJRefresh适配解决点

### ISSUE THREAD

**Issue by LimyronChin** [CoderMJLee/MJRefresh#959]
适配方法：

注：首先这个下拉刷新的偏移量并不是MJRefresh造成的，但是确实需要适配，比如通栏ViewController显示的时候，刘海会遮住下拉刷新的组件，解决办法是对下拉刷新控件自定义，调整内部组件的布局，通栏的ViewController地方使用自定义的下拉控件。

对于iOS11下的iPhoneX适配下拉刷新有以下几点：

1，首先请配置相应的启动图，尺寸是**1125*2436**；
2，对于通栏ViewController中的UIScrollView，系统会默认根据`contentInsetAdjustmentBehavior`属性改变其`bounds`的`y`值为`-44`，导致UIScrollView中的所有子控件下移，解决办法是，对于通栏ViewController，请设置其UIScrollView的`contentInsetAdjustmentBehavior = .never`。

其他适配点：

1，iOS11下的iPhoneX的导航栏为高度44，状态栏高度也调整为44，所以整个顶部状态栏的高度和导航栏的高度一起是88，自定义导航栏的同学需要根据系统机型控制导航栏高度；
2，iOS11下的iPhoneX的tabBar的高度调整为83，自定义tabBar的同学建议使用Frame布局；
3，iOS11下的iPhoneX下，屏幕底部默认显示了长条状的Home键指示器，可以通过`UIViewController (UIHomeIndicatorAutoHidden)`分类中的`prefersHomeIndicatorAutoHidden`来隐藏，但是官方并不建议这样做。

以上。

**Comment by CoderMJLee** [comment]
谢谢热心的朋友。已经兼容iOS11了，试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry

**Comment by SunnySunning** [comment]
`- (void)prepare {
    [super prepare];
    if (IS_IPHONEX) {
        self.mj_h = MJRefreshHeaderHeight + kStatusBarHeight;
        self.ignoredScrollViewContentInsetTop = -kStatusBarHeight * 0.5;
    } else {
        self.mj_h = MJRefreshHeaderHeight;
    }
}`
这个代码，完美解决

**Comment by Ave838** [comment]
> `- (void)prepare { [super prepare]; if (IS_IPHONEX) { self.mj_h = MJRefreshHeaderHeight + kStatusBarHeight; self.ignoredScrollViewContentInsetTop = -kStatusBarHeight * 0.5; } else { self.mj_h = MJRefreshHeaderHeight; } }`
> 这个代码，完美解决

非常完美  但是下拉间距有一点大  self.ignoredScrollViewContentInsetTop = -kStatusBarHeight * 0.35f，而且加入属性判断是否是隐藏了导航刷新，放在placeSubviews方法中重写更合理一些，兼容所有情况
