### ISSUE TITLE
关于footer一直显示的问题

### ISSUE THREAD

**Issue by FutureChen** [CoderMJLee/MJRefresh#96]
您好MJ老师 ，
     项目中更新了最近版本的MJRefresh，突然觉得foot设定改了好多，变成可以点击的了，并且会跟随显示在最后一条数据下方。 但是这种设定觉得很奇怪，或者说应该单独提取成一种功能模式，而不是替代了以前的方式？ 
     现在我的网络请求就返回三条数据，数据后面总是显示footer点击加载很多，但事实上我可能没有更多数据了，这个footer就非常有误导效果了。我现在都需要判断设置成[self.tableView.footer noticeNoMoreData]; 并且把字体设置成@“” 以隐藏这个效果。发起下拉刷新请求以后又要resetNoMoreData，貌似复杂了不少。
   有其他更好的方式么？

**Comment by CoderMJLee** [comment]
1.现在主流的上拉方法都是这样子哈，不再是以前的拼命往上拽
2.其实我的建议是直接noticeNoMoreData就好了，友善提示用户没有数据嘛。
3.如果你是想没有更多数据它就隐藏的话，直接self.tableView.footer.hidden = YES\NO就好了

**Comment by zsk425** [comment]
@CoderMJLee 无法赞同你的观点，我和@FutureChen的使用方式一样，应用性降低了。

**Comment by CoderMJLee** [comment]
好的，那我再看看怎么改进

**Comment by zsk425** [comment]
@CoderMJLee 辛苦了
