### ISSUE TITLE
MJRefresh iOS11 上拉刷新问题

### ISSUE THREAD

**Issue by ChildrenGreens** [CoderMJLee/MJRefresh#960]
iOS上拉刷新，存在回弹效果。刷新完成，整个ScrollView会向上回弹一段距离

**Comment by ap0806109** [comment]
有解决方案吗？ 我也遇到这个问题

**Comment by kaich** [comment]
@ChildrenGreens 同样遇到，请问解决了没有啊？

**Comment by HarrySu** [comment]
同样遇到。。

**Comment by wuzhe1993** [comment]
不管 mj 的事，是 tableView 的原因。
    self.tableView.estimatedRowHeight = 0;
    self.tableView.estimatedSectionHeaderHeight = 0;
    self.tableView.estimatedSectionFooterHeight = 0;

**Comment by wuzhe1993** [comment]
@ChildrenGreens  是 tableView 的原因。
self.tableView.estimatedRowHeight = 0;
self.tableView.estimatedSectionHeaderHeight = 0;
self.tableView.estimatedSectionFooterHeight = 0;

**Comment by ChinaFanCheng** [comment]
http://www.jianshu.com/p/1535b0b8d3d6

**Comment by ChildrenGreens** [comment]
@kaich  @HarrySu @ap0806109

**Comment by CoderMJLee** [comment]
已经兼容iOS11了，试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry
