### ISSUE TITLE
iPhoneX 的留海造成 表头没有隐藏

### ISSUE THREAD

**Issue by icefox57** [CoderMJLee/MJRefresh#963]
如图, 如果列表在安全区, 则表头没隐藏. 

是不是 吧 alpha 加入到动画效果里? 默认 0?

![image](https://user-images.githubusercontent.com/1716737/30738283-3ad4a712-9f4f-11e7-86cf-97853b8d9145.png)

**Comment by CoderMJLee** [comment]
建议自己设置一下contentInset.top，让tableView的内容往下挪动

**Comment by icefox57** [comment]
但是这样 head 就彻底露出来了 ,  原来head 是藏在上方的.

**Comment by CoderMJLee** [comment]
搞个白色的view，盖在tableView顶部，也就是刷新控件上面试试

**Comment by FSAnonymous** [comment]
哈哈, 好笨,开玩笑^_^
