### ISSUE TITLE
iOS11加载更多，cell乱跳

### ISSUE THREAD

**Issue by shasha7** [CoderMJLee/MJRefresh#966]
乱跳情况很严重

**Comment by JiongXing** [comment]
如果是约束自动算高的话，需要给cell足够大的估算高度，试试看？

**Comment by shasha7** [comment]
@JiongXing 问题目前已经暂时解决了。造成乱跳的原因是iOS11默认打开了Self-Sizing，我将它它预先计算的高度的属性全部设置为0，通过代理返回正确高度，就没有这个问题了。非常感谢您的回复

**Comment by JiangWenjia** [comment]
嗯，嗯设置成0就ok了

**Comment by CoderMJLee** [comment]
已经兼容iOS11了，试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry
