### ISSUE TITLE
iOS11下拉刷新头部视图UI显示错误

### ISSUE THREAD

**Issue by zzcshao** [CoderMJLee/MJRefresh#967]
`
self.tableView.mj_header = [MJRefreshNormalHeader headerWithRefreshingBlock:^{
        
    }];

- (UITableView *)tableView
{
    if (_tableView == nil) {
        CGRect frame = CGRectMake(0, 0, KDeviceHeight, KDeviceHeight);
        _tableView = [[UITableView alloc] initWithFrame:frame style:UITableViewStylePlain];
        _tableView.delegate = self;
        _tableView.dataSource = self;
        _tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
        //iOS11下不想使用Self-Sizing的话，可以通过以下方式关闭
        _tableView.estimatedRowHeight = 0;
        _tableView.estimatedSectionHeaderHeight = 0;
        _tableView.estimatedSectionFooterHeight = 0;
        if (@available(iOS 11.0, *)) {
            _tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }
    }
    return _tableView;
}`
运行环境 : iOS11系统  iPhone 6模拟器
截图链接如下:
https://i.loli.net/2017/09/26/59ca11aa98e74.png

**Comment by zzcshao** [comment]
https://i.loli.net/2017/09/26/59ca11aa98e74.png

**Comment by zzcshao** [comment]
有哪位遇到相同情况的帮忙解释下 , 谢谢 ~

**Comment by CoderMJLee** [comment]
已经兼容iOS11了，试试版本3.1.13。近几个月身体抱恙，所以未及时更新，Sorry
