### ISSUE TITLE
上拉加载的底部控件，在适配iPhone X时，会显示在安全区域外，该如何解决？

### ISSUE THREAD

**Issue by thunder0513** [CoderMJLee/MJRefresh#968]
同样的header也会有这样的问题，有好的解决方案吗？

**Comment by CoderMJLee** [comment]
分别添加一个有背景色（跟tableView背景色一样）的view在tableView的顶部或底部，盖住MJRefreshHeader和MJRefreshFooter？

**Comment by idbeny** [comment]
@CoderMJLee 
在AppDelegate里加上下面的代码就没事了
if (@available(iOS 11.0, *)){
        [[UIScrollView appearance] setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];
    }

**Comment by pdsliuzhen** [comment]
如果我既想要 安全区域，又想要列表到底部正常隐藏这个footer呢。

**Comment by TheLittleBoy** [comment]
期待解决办法。

**Comment by zhyKing** [comment]
@pdsliuzhen 我目前的做法是：
if (@available(iOS 11.0, *)) {
        self.myTableView.contentInsetAdjustmentBehavior = UIApplicationBackgroundFetchIntervalNever;
    }
然后
- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section{
    if (self.myTableDataSourceArray.count - 1 == section && iPhoneX) {
        return 34;
    }
    return 0.0001;
}
无奈之举ㄟ( ▔, ▔ )ㄏ  🤷‍♀️
各位dalao有什么好的方法没？还是坐等更新？

**Comment by TheLittleBoy** [comment]
我的办法是更换为MJRefreshAutoNormalFooter，效果还行吧

**Comment by zhyKing** [comment]
@TheLittleBoy 用MJRefreshAutoNormalFooter的话没有更多数据的时候你是怎么隐藏的呢？是不是就没有回弹效果了？

**Comment by TheLittleBoy** [comment]
@zhyKing self.tableView.mj_footer.hidden = YES;  
不要设置self.myTableView.contentInsetAdjustmentBehavior = UIApplicationBackgroundFetchIntervalNever;  这不符合iPhone X的设计规范！对于一个可以滑动的列表，请参考模拟器--设置页面的实现效果。

**Comment by zhyKing** [comment]
@TheLittleBoy 不设置`self.myTableView.contentInsetAdjustmentBehavior = UIApplicationBackgroundFetchIntervalNever;`的话push和pop时TableView会出现下拉回弹的动画（我也不清楚具体是什么原因造成的）。
至于你说的iPhone X的设计规范问题是指当列表滑到最底部的时候Home Indicator位置（底部超出安全区域的34高度的位置）不应展示列表内容吧？对于这个问题我是设置最后一个FooterIn的高度为34来解决的。

**Comment by TheLittleBoy** [comment]
下拉回弹动画的问题这就不清楚了。但是，要想实现系统设置的列表效果，就不能设置UIApplicationBackgroundFetchIntervalNever。

**Comment by zhyKing** [comment]
目前我项目中的关于适配iPhone X时遇到的坑和解决的办法，我总结了一下并发表在简书了。
[iOS 11 和 iPhoneX适配](https://www.jianshu.com/p/fd240dad1c2c)
其中第二条是当前讨论的问题。
如有意见或建议欢迎提出来

**Comment by MrCaiWH** [comment]
@zhyKing 照你的方法修改，tableview顶部钻入导航栏了，你碰到了吗？

**Comment by MrCaiWH** [comment]
#define SafeAreaBottomHeight (KScreenHeight == 812.0 ? 34 : 0)
    self.tableView.frame = CGRectMake(0, 0, KScreenWidth, KScreenHeight + SafeAreaBottomHeight);

@CoderMJLee @zhyKing 已解决😁

**Comment by zhyKing** [comment]
@MrCaiWH 谢谢提醒，我才发现我那种方法只适合navigationBar为不透明状态下。

**Comment by xieliying** [comment]
在 viewWillAppear: 方法里添加一段代码：
`self.tableView.mj_footer.ignoredScrollViewContentInsetBottom = kIsiPhoneX ? 34 : 0;`
用于设置【忽略多少scrollView的contentInset的bottom】

**Comment by tbfyniiswcy** [comment]
> 在 viewWillAppear: 方法里添加一段代码：
> `self.tableView.mj_footer.ignoredScrollViewContentInsetBottom = kIsiPhoneX ? 34 : 0;`
> 用于设置【忽略多少scrollView的contentInset的bottom】

我改进了一下，可以这样：self.tableView.mj_footer.ignoredScrollViewContentInsetBottom = UIApplication.shared.keyWindow?.safeAreaInsets.bottom ?? 0
