### ISSUE TITLE
3.1.13版本cocoapods 查找不到

### ISSUE THREAD

**Issue by linbx08** [CoderMJLee/MJRefresh#969]
MJ老师你好, 3.1.13版本cocoapods未能查找到 ,已更新pod repo update/ pod update /pod install --repo-update 目前只是3.1.12版本 请问有解决方法不

**Comment by 94else** [comment]
pod 'MJRefresh', :git => 'https://github.com/CoderMJLee/MJRefresh.git', :commit => '4590486'

**Comment by linbx08** [comment]
@94else  这个是你自己的分支?

**Comment by 94else** [comment]
:git => 指 那个仓库  :commit => 指 提交的 记录

**Comment by linbx08** [comment]
thanks you very much

**Comment by SimleCp** [comment]
直接指向主线  好像也是可以的. pod 'MJRefresh', :git => 'https://github.com/CoderMJLee/MJRefresh.git'

**Comment by linbx08** [comment]
wow, 学到了. 感谢

**Comment by SimleCp** [comment]
@linbx08 我刚刚更新了下仓库  现在已经能搜索到了

**Comment by linbx08** [comment]
@SimleCp 目前我是通过pod 'MJRefresh', :git => 'https://github.com/CoderMJLee/MJRefresh.git', :commit =>'4590486'这样更新的 但是如果使用pod 'MJRefresh', '~> 3.1.13'是更新不到的

**Comment by CoderMJLee** [comment]
不好意思，昨天操作失误，没有传上去。刚才已经OK了。

**Comment by SimleCp** [comment]
我去, 那我昨天怎么搜索cocoapods能搜索到3.1.13    =. =
