### ISSUE TITLE
请问下拉刷新时，动画从左侧滑入的问题解决了吗？

### ISSUE THREAD

**Issue by hengchengfei** [CoderMJLee/MJRefresh#97]
MJ你好。

**Comment by CoderMJLee** [comment]
上个月已经解决了哈，你下载最新代码试试

**Comment by hengchengfei** [comment]
动画问题解决了，但是会产生另外一个问题。
[xx.gifHeader beginRefresh]方法只会在刚进来的时候调用有效，以后再调用就不起作用了。

在MJRefreshHeader.m的-(void)beginRefreshing的方法里做的判断有bug。

**Comment by CoderMJLee** [comment]
我用的没事哦，是不是用错了？有示例程序或者代码看看么？3Q

**Comment by rickytan** [comment]
哪个 commit 修复的？最近的 3.1.12 代码用于 collection view 还是有问题
