### ISSUE TITLE
 新版本MJRefresh3.1.13 AutoNormalFooter  加载数据后还是会回弹

### ISSUE THREAD

**Issue by FSAnonymous** [CoderMJLee/MJRefresh#970]
新版本MJRefresh3.1.13 AutoNormalFooter  加载数据后还是会回弹

**Comment by FSAnonymous** [comment]
iOS 11

**Comment by CoderMJLee** [comment]
回弹是啥意思？可以具体一点么

**Comment by wdq123550** [comment]
意思就是說下拉沒有刷新的過程，下拉之後直接結束刷新了

**Comment by wdq123550** [comment]
可能上拉也有這種情況

**Comment by wdq123550** [comment]
ios11出現過 pod update之後升級到3.1.13下拉刷新問題就解決了

**Comment by FSAnonymous** [comment]
就是当我用这个AutoNormalFooter类型的时候，滑动到最后自动进行加载下一页数据，加载数据后正常来讲是直接将数据显示在当前位置，但是现在出现加载数据后会跳一下！，正常应该是直接显示第一页的底部和下一页第一条数据的一部分，现在是跳了一下，滚动后才看见第二页的第一条数据

**Comment by CoderMJLee** [comment]
你确定用的是AutoNormalFooter？不是BackNormalFooter？

**Comment by FSAnonymous** [comment]
恩恩  _tableView.mj_footer = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
          }];

**Comment by wdq123550** [comment]
之前有没有这种情况？检查下cell的高度是否正确。

发自我的 iPhone

**Comment by FSAnonymous** [comment]
我看你的demo里面不会出现这种情况,  我看看是我哪里出现了其他问题

**Comment by Suzhibin** [comment]
我也出现了这样的问题

**Comment by zhenLuoxiaoming** [comment]
我也是呀，李大哥

**Comment by Suzhibin** [comment]
@zhenLuoxiaoming @FSAnonymous  您们是不是 kvo观察 contentSize和contentOffset值的变化.进行一些动画。

**Comment by bananaboss** [comment]
我也是出现这个情况

**Comment by batkov** [comment]
I experiencing this too

**Comment by cyW0923** [comment]
我也是，在简书上看到说设置估计高度，但是估计高度给大了就向上回弹，给小了就向下回弹。。

**Comment by goham** [comment]
貌似我也有这个情况？有没有解决办法

**Comment by wolfcon** [comment]
Duplicate of #1009
