### ISSUE TITLE
iOS11 3.1.13 重复点击顶部 titleItem 触发下拉刷新 类似于今日头条那种, 回滚不正常

### ISSUE THREAD

**Issue by yinqiangw** [CoderMJLee/MJRefresh#973]
上拉刷新后即第二页,  重复点击 顶部 titleItem  触发下拉刷新, 回滚不正常, 回滚是乱的, 也回滚不到顶部

回滚指的是第二页的某个 cell,  回滚到第一页的第一个cell  并刷新数据

iOS 10 是可以正常的回滚到顶部, 并执行下拉刷新的

**Comment by VicoWang** [comment]
我也遇到了，不知道可有什么好的解决方案
