### ISSUE TITLE
下载的最新版本，自动加载下一页到底部没数据的时候，会无限触发自动加载。

### ISSUE THREAD

**Issue by devkiang** [CoderMJLee/MJRefresh#976]
_tableView.mj_footer=[MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
        
    }];
断点MJRefreshAutoFooter.m 的scrollViewContentOffsetDidChange方法发现该方法一直被触发，change参数中的，newValue和oldValue是一样的，不懂为啥会一直触发，导致到底部无限自动加载。
IOS8下面试验就没问题，发现在IOS11存在这个问题

**Comment by rockerkekex** [comment]
碰到了同样的问题。。。

**Comment by wys13114** [comment]
设置已给预算高度为0 就好了！   下面代码仅供参考。     
if (@available(iOS 11.0, *)){
            if ([self isKindOfClass:[UITableView class]]) {
                UITableView *tableView = (UITableView *)self;
                tableView.estimatedRowHeight = 0;
                tableView.estimatedSectionHeaderHeight = 0;
                tableView.estimatedSectionFooterHeight = 0;
            }
        }

**Comment by devkiang** [comment]
楼上的方法真的可以，这是什么原因。
之前的代码也没写过estimatedRowHeight的，为什么在这里写上就没事了 ？

**Comment by devkiang** [comment]
IOS11以后，Self-Sizing默认开启，包括Headers, footers。如果项目中没使用estimatedRowHeight属性，在IOS11下会有奇奇怪怪的现象，因为IOS11之前，estimatedRowHeight默认为0，Self-Sizing自动打开后，contentSize和contentOffset都可能发生改变。可以通过以下方式禁用：

self.tableView.estimatedRowHeight = 0; 
self.tableView.estimatedSectionHeaderHeight = 0; 
self.tableView.estimatedSectionFooterHeight = 0;

**Comment by MJHee** [comment]
同样的问题遇到过，可以用 MJRefreshBackNormalFooter 替代 MJRefreshAutoNormalFooter

**Comment by cyW0923** [comment]
如果我tableView需要使用Self-Sizing就不能设置为0，设置大了就向上回弹，设置小了就向下回弹，怎么破啊？

**Comment by CoderMJLee** [comment]
大家可以试试3.1.15版本，iOS11真是不让人省心呐😆
