### ISSUE TITLE
iOS 11中，隐藏导航栏的情况下拉刷新视图会暴露出来

### ISSUE THREAD

**Issue by 1046996647** [CoderMJLee/MJRefresh#978]
![2017-09-29 17 16 28](https://user-images.githubusercontent.com/15166526/31009431-00e65d48-a53a-11e7-87ad-8c2af1e9d7a4.png)

**Comment by xdkhan** [comment]
iOS 11安全区域

**Comment by shutup** [comment]
`mainTableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;`

**Comment by wolfcon** [comment]
```swift
tableView.mj_header.automaticallyChangeAlpha = true
```
