### ISSUE TITLE
下拉刷新箭头不显示，刷新状态显示有问题

### ISSUE THREAD

**Issue by laoSanDr** [CoderMJLee/MJRefresh#979]
![cbd4b3de-a39d-4d26-a9b7-0f3119832fda](https://user-images.githubusercontent.com/15378738/31042267-a7a078a2-a5d6-11e7-85db-350fa46d62cf.png)

刷新显示就像这样，原来的箭头也不显示了

**Comment by Damon-YJ** [comment]
我滴哥..你bundle都没加载...
