### ISSUE TITLE
希望能够设置 下拉刷新的背景色；比如：表格是白色的，我希望下拉刷新的是灰色

### ISSUE THREAD

**Issue by zhanxp** [CoderMJLee/MJRefresh#98]
希望能够设置 下拉刷新的背景色；比如：表格是白色的，我希望下拉刷新的是灰色；
不是修改TableView 或者 ViewController 的背景色，仅仅修改下拉刷新露出来的部分的背景色；或者背景图片；

**Comment by CoderMJLee** [comment]
self.tableView.header.backgroundColor = xxx;

**Comment by zhanxp** [comment]
试了这个方法，有问题；  
只能设置一小段高度的颜色； 下拉之后会露出View的颜色；
![qq20150514-20 2x](https://cloud.githubusercontent.com/assets/1018464/7626498/aaf918da-fa3c-11e4-8511-2c4fafed328b.png)

**Comment by CoderMJLee** [comment]
那就是只能在view的顶部-后面增加一个Y值为0的比较高的灰色view

**Comment by CoderMJLee** [comment]
那就只能在view的顶部-后面增加一个Y值为0的比较高的灰色view哈

**Comment by csc-EricWu** [comment]
MJ 哥可以给个代码吗？底部也有这个问题，而且添加view会增加整体高度！！！

**Comment by csc-EricWu** [comment]
IKRefreshGifHeader* header=(IKRefreshGifHeader*)webCollectionView.header;
    IKRefreshBackGifFooter* footer=(IKRefreshBackGifFooter*)webCollectionView.footer;
    header.backgroundColor=kCommunityMaskColor;
    footer.backgroundColor=kCommunityMaskColor;
    
    UIView* maskView=[UIView viewWithFrame:webCollectionView.frame];
    maskView.backgroundColor = kCommunityMaskColor;
    maskView.y-=maskView.height;
    [webCollectionView.header addSubview:maskView];
    
    maskView=[UIView viewWithFrame:webCollectionView.frame];
    maskView.backgroundColor=kCommunityMaskColor;
    [webCollectionView.footer insertSubview:maskView atIndex:0];



我这里写出来了，希望别人能看到！
