### ISSUE TITLE
是否考虑增加一种模式，当前只有Auto和Back模式

### ISSUE THREAD

**Issue by liangdahong** [CoderMJLee/MJRefresh#980]
## 可能有这样的一种上拉加载需求
1. footer在正常上拉时使用Back模式，footer永远在tableView的底部，不管Cell的多少（不想打搅用户的使用，提示无效信息）。
2. 在无更多数据时，使用Auao模式，footer永远在tableView的最后一个Cell底部（方便提醒用户已经没有更多数据，不需要上拉一下才知没有数据了）。

> 不知是否合理，望MJ老师给点建议，我们可以使用Back和Auao组合的方式，但是感觉较麻烦，而且不合理。

**Comment by xixisplit** [comment]
这个应该是自己开发吧.比如我的项目.返回的 data 里面有整体数据条数.也是可以做到你这种体验的.应该根据自己的项目实际情况来做开发.

**Comment by liuhaoliang** [comment]
使用MJRefreshAutoNormalFooter

**Comment by asiosldh** [comment]
@xixisplit 可以由项目需求来开发，但较麻烦，同时需支持：    `UICollectionView`; `UIScrollView`; `UITableView`; `UIWebView`。
@liuhaoliang 可以使用`MJRefreshAutoNormalFooter`，但似乎`MJRefreshAutoNormalFooter`会导致当数据量较少时footer在最后一个cell底部,实际我想在UIScrollView底部。

我简单封装了下有兴趣可以瞧瞧。https://github.com/asiosldh/MJRefresh-Custom
