### ISSUE TITLE
上拉加载更多的bug

### ISSUE THREAD

**Issue by liuhaoliang** [CoderMJLee/MJRefresh#981]
在iOS11中，当rowheight很大时（比如rowheight=100），上拉加载更多时，列表的contentOffset_y会突然改变,显示在视图上的数据会往上偏移。大家可以在作者的demo中测试。

**Comment by wty302857194** [comment]
我也会出现这样的问题,貌似是在3.1.12版本上面,作者好像已经更新到3.1.13了,但是我还是更新不到.

**Comment by veryitman** [comment]
新版本已经解决了.
需要自己 

> pod repo update --verbose

 一下自己的本地 pod 仓库.

**Comment by cao903775389** [comment]
更新到最新3.1.14还是会出现上拉加载更多时上下偏移的问题

**Comment by LDreame** [comment]
3.1.14的确还是会出现,你们的解决了吗

**Comment by ShanJiJi** [comment]
最近发现在iOS11中，mj_footer refreshing时block回调会触发两次，如果数据请求报错会一直重复触发。这个问你们都有遇到过吗？？refresh版本 3.1.14

**Comment by YYDD** [comment]
对于tableview会跳动和多次调用block的最终原因是因为ios11 开始 tableview默认开启了self-sizing的原因。所以才会出现contentOffset的计算错误等。因此出现这些问题的tableview应该是都没有实现estimatedRowHeight这个属性吧。
由于ios11默认开启了，所以才会出现类似问题。
最简单的兼容方式 就是主动关闭self-sizing。实现如下：
````
  tableView.estimatedRowHeight = 0;
  tableView.estimatedSectionHeaderHeight = 0;
  tableView.estimatedSectionFooterHeight = 0;


````

**Comment by c5p0** [comment]
上拉block 执行多次啊

**Comment by SenorSamuel** [comment]
我碰到的问题是上拉加载时tableView会跳动,查了资料发现是iOS11默认开启了self-sizing的原因,由于并没有使用到预估行高,所以使用了以下方法来关闭iOS11下的self-sizing
在`AppDelegate`中统一修改UITableView的样式:
```objc
    [UITableView appearance].estimatedRowHeight = 0;
    [UITableView appearance].estimatedSectionHeaderHeight = 0;
    [UITableView appearance].estimatedSectionFooterHeight = 0;
```

**Comment by veryitman** [comment]
@SenorSamuel 
这样处理后, 其他页面使用了 estimatedRowHeight 或者 estimatedSectionHeaderHeight的属性, 不会有影响吗?

**Comment by SenorSamuel** [comment]
肯定是会的啊 我全局都没有使用到这三个属性，所以就禁用掉啦




发自网易邮箱大师
在2017年10月26日 10:39，mark 写道：

@SenorSamuel
这样处理后, 其他页面使用了 estimatedRowHeight 或者 estimatedSectionHeaderHeight的属性, 不会有影响吗?

**Comment by RocChiu2015** [comment]
@YYDD 这种方法我试过，但是不管用，请问还有其他的方法吗？

**Comment by YYDD** [comment]
@RocChiu2015  我刚重新check了下 我这边是ok的。我是3.1.14版本的。
然后问下 你是偏移量的问题 还是说多次调用的问题？

**Comment by Lucaziki** [comment]
@YYDD 我的TableView是使用AutoLayout的，Cell都是用布局撑起来的，使用了tableView的自动高度计算（estimatedRowHeight和UITableViewAutomaticDimension）。在tableView拉到底部没有更新内容的时候也会出现本Issue描述的问题。

**Comment by CoderMJLee** [comment]
大家可以试试3.1.15版本，iOS11真是不让人省心呐😆

**Comment by SoftBoys** [comment]
3.1.15.3版本在iOS11上上拉加载无更多数据 设置为 endRefreshingWithNoMoreData 时，还是会出现footer向上偏移的BUG

**Comment by kopuCoder** [comment]
> 大家可以试试3.1.15版本，iOS11真是不让人省心呐😆

hello,明杰大神，现在在iOS11上，上拉加载更多时，偏移量会随着上拉的次数越变越高，最后会发现，"上拉可以加载更多"这个控件都跑屏幕中间了(版本已更新到最新，尝试使用了上边提到的所有办法都没有作用)。求解答，谢谢

**Comment by zhanght-02** [comment]
hello,明杰大神，现在在iOS11上，上拉加载更多时，偏移量会随着上拉的次数越变越高，最后会发现，"上拉可以加载更多"这个控件都跑屏幕中间了(版本已更新到最新的3.1.15.7，尝试使用了上边提到的所有办法都没有作用)。这个问题有解决吗

**Comment by wolfcon** [comment]
Duplicate of #1009

**Comment by jeffasd** [comment]
lazy var tableView: UITableView = {
        let view = UITableView(frame: .zero, style: .plain)
        view.isPagingEnabled = true
        view.register(MainListTableViewCell.self, forCellReuseIdentifier: kCellIdentify)
        view.delegate = self
        view.dataSource = self
        
        let header = MJRefreshNormalHeader(refreshingTarget: self, refreshingAction: #selector(loadNewData))
        header.lastUpdatedTimeLabel?.isHidden = true
        view.mj_header = header
        
        let footer = MJRefreshAutoNormalFooter.init(refreshingTarget: self, refreshingAction: #selector(loadMoreData))
        view.mj_footer = footer
        footer.triggerAutomaticallyRefreshPercent = -2.0
        footer.autoTriggerTimes = -1
        
        if abs(footer.triggerAutomaticallyRefreshPercent - 0.0) >= 0.0001 {
            view.estimatedRowHeight = 0
            view.contentInsetAdjustmentBehavior = .never
            /// fix UITableView enable isPagingEnabled and MJRefreshAutoNormalFooter triggerAutomaticallyRefreshPercent is not zero,
            /// when footer auto refresh cell offset is error.
            view.mj_insetB = 0
        }
        
        return view
    }()

**Comment by gitph101** [comment]
您好，邮件已收到。

**Comment by 309598016** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
