### ISSUE TITLE
iPhone X上可以看到下拉控件

### ISSUE THREAD

**Issue by fangshufeng** [CoderMJLee/MJRefresh#983]
![c06c6d3f-4360-4e38-8147-52cfd84ef377](https://user-images.githubusercontent.com/16829768/31332041-7925b034-acaa-11e7-9bbe-f5920cd38b05.png)

**Comment by TheLittleBoy** [comment]
怎么解决？

**Comment by topjx** [comment]
怎么解决？

**Comment by luoshuisheng** [comment]
怎么解决的

**Comment by TheLittleBoy** [comment]
我的办法是更换为MJRefreshAutoNormalFooter，效果还行吧

**Comment by topjx** [comment]
增加安全区域的约束，我用的masonry

**Comment by zy364601065** [comment]
@topjx 设置了安全区域虽然可以达到目的，但是底部34pt的区域为空白，这样不浪费了全面屏的特性吗

**Comment by luoshuisheng** [comment]
设置隐藏吧

**Comment by topjx** [comment]
@zy364601065  用全屏也可以啊 不过和虚拟HOME键的响应区域重叠了不好吧 后面看看大厂都是怎么操作的 学学

**Comment by sclcoder** [comment]
这是个值得解决的问题

**Comment by zhyKing** [comment]
[iOS 11 和 iPhoneX适配](https://www.jianshu.com/p/fd240dad1c2c)
第二个问题：MJRefresh的footer出现在Home Indicator位置上

**Comment by wolfcon** [comment]
```swift
tableView.mj_footer.automaticallyChangeAlpha = true
```
