### ISSUE TITLE
更新到3.1.14后，我的webview下拉刷新结束后在状态栏还是能见刷新UI

### ISSUE THREAD

**Issue by zoey0820ivy** [CoderMJLee/MJRefresh#984]
![image](https://user-images.githubusercontent.com/14231130/31368330-bb105b5a-ad42-11e7-8b83-095c78670945.png)

**Comment by dreamlivemeng** [comment]
你设置tableview的顶部约束  make.top.equalTo(self.view).offset(22);然后再设置  _tableView.clipsToBounds=YES;
  _tableView.contentInset = UIEdgeInsetsMake(-22, 0, 0, 0);

**Comment by dreamlivemeng** [comment]
或者直接使用这个属性也可以self.automaticallyAdjustsScrollViewInsets = NO;

**Comment by wolfcon** [comment]
Duplicate of #1130
