### ISSUE TITLE
更新到xcode9 iOS11 下拉提示显示英文 箭头也没了？咋处理啊？

### ISSUE THREAD

**Issue by twisturn** [CoderMJLee/MJRefresh#985]
更新到xcode9 iOS11 下拉提示显示英文 箭头也没了？咋处理啊？

**Comment by liuxueming** [comment]
在build phases  -- Copy Bundle Resources手动增加 bundle 文件即可解决。

**Comment by twisturn** [comment]
@liuxueming 已经解决了，谢谢
