### ISSUE TITLE
iOS 11,下拉刷新不显示文字和更新时间

### ISSUE THREAD

**Issue by mike1023** [CoderMJLee/MJRefresh#986]

**Comment by wangkeshuai** [comment]
在MJRefreshHeader 的setState方法里修改一下
if (state == MJRefreshStateRefreshing) {
         dispatch_async(dispatch_get_main_queue(), ^{
            [UIView animateWithDuration:MJRefreshFastAnimationDuration animations:^{
						 CGFloat top = self.scrollViewOriginalInset.top + self.mj_h;
							if(@available(iOS 11.0,*))//自己加的
							{
								top+=self.mj_h;//自己加的
							}//自己加的
							
                // 增加滚动区域top
                self.scrollView.mj_insetT = top;
                // 设置滚动位置
                [self.scrollView setContentOffset:CGPointMake(0, -top) animated:NO];
            } completion:^(BOOL finished) {
                [self executeRefreshingCallback];
            }];
         });
    }
