### ISSUE TITLE
iOS 11下显示英文箭头不出现 或者 导航栏向下偏移20px 解决办法。

### ISSUE THREAD

**Issue by liuxueming** [CoderMJLee/MJRefresh#987]
我也是遇到了这种情况，最后解决了，现在分享下。
1.在build phases -- Copy Bundle Resources手动增加 bundle 文件即可解决。
2.在viewDidLoad增加几句代码
#ifdef __IPHONE_11_0
    if ([self.tableView respondsToSelector:@selector(setContentInsetAdjustmentBehavior:)]) {
        if (@available(iOS 11.0, *)) {
            self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        } else {
        }
    }
#endif

**Comment by Heisenbean** [comment]
我也出现了这个问题,感谢分享,已解决.
:)
