### ISSUE TITLE
关于@available 的BUG

### ISSUE THREAD

**Issue by yanyibin** [CoderMJLee/MJRefresh#988]
@available语法仅支持XCode9
由于#ifdef __IPHONE_11_0的限定在XCode8上也能跑
但是将MJRefresh被framework的形式塞入打包后，却无法获取@available，会导致编译报错
所以@available暂时还不能用于版本判断

**Comment by yanyibin** [comment]
由于上述原因，故打算framework包中指定MJRefresh版本为3.1.12
但是pod依赖加载的时候会忽略第三位版本，会直接取3.1.X（X为bugfix版本中的最高位版本）
所以取到的一直会是3.1.14，导致3.1.12用不了了
所以建议以后版本更新修改小版本号。

**Comment by AlanMelody** [comment]
升级到 Xcode9 不就行了？

**Comment by russellyi** [comment]
Xcode9也会存在这个问题， 使用iOS 9.0，不管是真机还是模拟器都会调用 iOS11的方法`adjustedContentInset`，从而导致APP闪退。
PS: 通过Carthage集成MJRefresh到Swift项目

```
- (UIEdgeInsets)mj_inset
{
#ifdef __IPHONE_11_0
    if(@available(iOS 11.0, *)){
        return self.adjustedContentInset;
    }
#endif
    return self.contentInset;
}
```

**Comment by russellyi** [comment]
[@available 和 #available](http://swift.gg/2016/04/13/swift-qa-2016-04-13/) , 是否需要将 `@available ` 改成 `#available`

**Comment by russellyi** [comment]
PR #997 使用其他检查系统版本的方式，不使用 `@available`  在iOS 11以下系统暂时没有问题。不过就是出现警告。

**Comment by TheLittleBoy** [comment]
不适配iPhone X了？ 还是用xcode9吧！

**Comment by dklinzh** [comment]
@russellyi 请问使用Cocoapods会出现`@available`不兼容的问题吗？
