### ISSUE TITLE
loadingView属性不能隐藏，影响全部自定义的ui设计

### ISSUE THREAD

**Issue by shuymx** [CoderMJLee/MJRefresh#990]
@property (weak, nonatomic) UIActivityIndicatorView *loadingView;
MJRefreshBackNormalFooter.m 文件的loadingView属性没有提供隐藏方法,也没有暴露出来，今天我处理的时候很不方便，希望李老师能够优化一下，方便我们开发的同学完全自定义集成刷新。

**Comment by yanyibin** [comment]
KVC即可。

**Comment by CoderMJLee** [comment]
尝试继承MJRefreshBackFooter或者MJRefreshBackStateFooter试试？
