### ISSUE TITLE
iOS11 上拉加载更多时，回调block会触发多次，甚至一直触发

### ISSUE THREAD

**Issue by ShanJiJi** [CoderMJLee/MJRefresh#991]
最近发现在iOS11中，mj_footer refreshing时block回调会触发两次，如果数据请求报错会一直重复触发。这个问你们都有遇到过吗？？refresh版本 3.1.14   

使用的是：MJRefreshAutoFooter

在iOS11版本以下都正常触发一次

**Comment by wdq123550** [comment]
我也是這個情況

**Comment by YYDD** [comment]
https://github.com/CoderMJLee/MJRefresh/issues/981 
查看这个issue 里面有解释

**Comment by c5p0** [comment]
不紧紧在ios11 ios  9 也存在上拉block执行多次

**Comment by mTerminal** [comment]
没错，最新版就是有这个 BUG，主要原因是因为返回数据为 nil ，没有调用 `endRefreshingWithNoMoreData` 如果仅仅使用 `endRefreshing` 就会出现反复刷新。
还有 关闭 self-sizing 这种方式根本不合理啊，我需要用到，强制让我关闭，也太不合理了。
还是等大佬更新吧。只能暂时用 `MJRefreshBackStateFooter ` 替代了。

**Comment by YYDD** [comment]
关于关闭self-sizing这一点是说，默认开启的如果不对其进行设置的时候才会出现这样的问题，也就是说如果你使用了，那么就是有设置`estimatedRowHeight `之类的值，就不会出现问题了。
当然因为我们用的是mj的库，最终还是要等作者更新使用其原内容。这个方案我是觉得说在作者还没更新，而要使用新的sdk进行打包发布版本的使用试用下

**Comment by CoderMJLee** [comment]
@ShanJiJi @c5p0 @mTerminal @wdq123550 因为近期时间比较紧，能否麻烦朋友们抽空写一个出现这个问题的Demo出来，然后我直接调试一下。谢谢

**Comment by mTerminal** [comment]
@CoderMJLee [Refresh Demo](http://orw4ygcvy.bkt.clouddn.com/MJRefresh_Demo.zip) demo 写好了，您可以看一下。  其他看到的朋友酌情下载，免费七牛云外链，下载过多会失效，不要影响 m 哥调试，多谢。

**Comment by RocChiu2015** [comment]
@CoderMJLee 我也遇到了同样的问题，在ios11机器上上拉加载的时候会重复调用loadMoreData方法，即便加上```
self.tableView.estimatedRowHeight =0;
self.tableView.estimatedSectionHeaderHeight =0;
self.tableView.estimatedSectionFooterHeight =0;
```也不管用，但是在ios10上面就不会出现重复调用的问题。

**Comment by RocChiu2015** [comment]
@CoderMJLee 我也遇到了同样的问题，在ios11机器上上拉加载的时候会重复调用loadMoreData方法，即便加上
```
self.tableView.estimatedRowHeight =0;
self.tableView.estimatedSectionHeaderHeight =0;
self.tableView.estimatedSectionFooterHeight =0;
```
也不管用，但是在ios10上面就不会出现重复调用的问题。

**Comment by CoderMJLee** [comment]
@mTerminal 谢谢你的Demo。大家可以试试3.1.15版本，iOS11真是不让人省心呐😆

**Comment by HoweLv** [comment]
iOS11，3.1.15.1版本，上拉回触发7次

**Comment by caoyunxiao** [comment]
使用MJRefreshBackStateFooter，确实就不会了
不过用MJRefreshAutoNormalFooter就会一直回调

**Comment by 13hoop** [comment]
![image](https://user-images.githubusercontent.com/7189963/53624903-a6768400-3c3c-11e9-94a1-1c768de1c8b1.png)
这个问题貌似还没解决啊

**Comment by Jayxiang** [comment]
MJRefreshAutoNormalFooter  如果不松手他会一直加载2-3次。松手后又会加载一次。确实有问题。
改用MJRefreshBackStateFooter了

**Comment by wolfcon** [comment]
Duplicate of #1009
