### ISSUE TITLE
iOS11 上拉刷新会跳动  iOS10没有这种问题

### ISSUE THREAD

**Issue by CoderDeYu** [CoderMJLee/MJRefresh#992]
AutoNormalFooter 在iOS10中上拉刷新就是接着末端刷新的数据  iOS11刷新完了之后会跳动 跳了两个Item这样

**Comment by CoderDeYu** [comment]
#981
好吧参照这个解决了 但是要每个tableView都加有点麻烦..

**Comment by AdminTestsGitHub** [comment]
# UIScrollView (MJRefresh) 里面统一加就可以

#pragma mark - footer
static const char MJRefreshFooterKey = '\0';
- (void)setMj_footer:(MJRefreshFooter *)mj_footer
{
    if (mj_footer != self.mj_footer) {
        // 删除旧的，添加新的
        [self.mj_footer removeFromSuperview];
        [self insertSubview:mj_footer atIndex:0];
        
        **// ios11 适配 关闭self-sizing
        if ([self isKindOfClass:[UITableView class]]) {
            UITableView *view = (UITableView *)self;
            view.estimatedRowHeight = 0;
            view.estimatedSectionHeaderHeight = 0;
            view.estimatedSectionFooterHeight = 0;
        }**

        // 存储新的
        [self willChangeValueForKey:@"mj_footer"]; // KVO
        objc_setAssociatedObject(self, &MJRefreshFooterKey,
                                 mj_footer, OBJC_ASSOCIATION_ASSIGN);
        [self didChangeValueForKey:@"mj_footer"]; // KVO
    }
}

**Comment by Xingefb** [comment]
如果我是自动计算的高度那不都完蛋了？

**Comment by HanXiaoTeng** [comment]
我的cell的高度是自动计算的，estimatedRowHeight不能设置为0啊

**Comment by CoderMJLee** [comment]
大家可以试试3.1.15版本，iOS11真是不让人省心呐😆

**Comment by AdminTestsGitHub** [comment]
好像并没有修复耶，明杰大大.

**Comment by CoderMJLee** [comment]
@AdminTestsGitHub 提供一个有问题的Demo看看哈，我直接调试

**Comment by Gitool** [comment]
已经解决。
参看[【已解决】iOS11使用MJRefresh上拉加载结束tableView闪动、跳动的问题](https://www.cnblogs.com/cchHers/p/9883646.html)

**Comment by wolfcon** [comment]
Duplicate of #1009

PR is #1306 
Will launch in `3.3.0`
