### ISSUE TITLE
ios11 下拉刷新嵌套在左右滚动的页面，无法下拉

### ISSUE THREAD

**Issue by loumzy** [CoderMJLee/MJRefresh#993]
一个可以左右滚动的controller里，放置两个子 viewcontroller， 两个子ViewController中是使用的下拉刷新，此时发现无法下拉，如果只有一个子ViewController 是可以下拉刷新的

**Comment by loumzy** [comment]
貌似是 横向滑动事件和 下拉刷新事件冲突了，我现在禁止了横向滑动就正常下拉刷新了

**Comment by sclcoder** [comment]
@loumzy 应该不是刷新控价的问题
