### ISSUE TITLE
MJRefreshHeader.m第133行设置滚动位置的问题

### ISSUE THREAD

**Issue by liuxiaoxinxin** [CoderMJLee/MJRefresh#996]
原实现为  [self.scrollView setContentOffset:CGPointMake(0, -top) animated:NO];
如果contentInset.left为非零或contentOffset为非0将会出现不恰当的动画；
应该改为：
                CGPoint offset = self.scrollView.contentOffset;
                offset.y = -top;
                [self.scrollView setContentOffset:offset animated:NO];

**Comment by CoderMJLee** [comment]
谢谢
