### ISSUE TITLE
在3.0+版本中在有UISearchController的页面中使用的时候发现下拉的时候header不显示。3.0以前的版本能使用。

### ISSUE THREAD

**Issue by sjustfly** [CoderMJLee/MJRefresh#998]
具体请看这位博主的帖子
[传送门](http://blog.csdn.net/qq_29892943/article/details/51831307)

**Comment by CoderMJLee** [comment]
3.0+版本使用这位博主的方法还是有问题么？

**Comment by sjustfly** [comment]
是的，我项目刚更行了一下该库，导致这个问题的产生

**Comment by CoderMJLee** [comment]
麻烦写一个出现这个问题的Demo，方便我直接调试哈，谢谢
